erda-project/erda

quick-start/docker-compose.yml
quick-start/env
quick-start/nginx.conf
quick-start/quick-start.sh

bugfix: quick-start support *.erda.local visit from inside k8s cluster

---

modules/hepa/common/log_helper.go
modules/hepa/k8s/k8s_adapter.go

/kind feature
support response code & body in hepa's access log

enhancing the access log of hepa

---

modules/cmp/cache/cache.go
modules/cmp/cache/cache_test.go

/kind bugfix
calc size of cache interface value

fix: 🐛 calc size of cache interface value

---

conf/cmp/i18n/component-protocol.yaml
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/operationButton/model.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/operationButton/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/operationButton/render_test.go

/kind feature
prohibit delete system workload

prohibit delete system workload

---

pkg/database/sqlparser/ddlreverser/reverser.go
pkg/database/sqlparser/snapshot/snapshot.go
pkg/database/sqlparser/snapshot/snapshot_test.go

/kind feature
feature: trim charset except utf8,utf8mb4

feature: trim charset except utf8,utf8mb4

---

modules/pipeline/metrics/pipeline.go
modules/pipeline/metrics/task.go

/kind bugfix
modify metric label scope id to org name

modify label scope id to org name

---

apistructs/autotest_scene.go
apistructs/autotest_scene_test.go
modules/dop/component-protocol/components/test-dashboard/overview_group/blocks/at/at_num_api/render.go
modules/dop/services/autotest_v2/scene.go

/kind bugfix
fix: update api and scene count of test dash board
/assign @sfwn 

fix: update api and scene count of test dash board

---

erda.yml

/kind bugfix
add orchestrator addr
/assign @sfwn 

add orchestrator addr

---

erda.yml
modules/dop/component-protocol/components/addon-mysql-account/accountTable/render.go
modules/dop/component-protocol/components/addon-mysql-account/accountTable/render_test.go
modules/dop/component-protocol/components/addon-mysql-account/accountTable/table/table.go
modules/dop/component-protocol/components/addon-mysql-account/addAccountButton/render.go
modules/dop/component-protocol/components/addon-mysql-account/filter/render.go
modules/dop/component-protocol/components/addon-mysql-account/viewPassword/render.go
modules/dop/component-protocol/components/addon-mysql-account/viewPasswordModal/render.go
modules/dop/component-protocol/components/addon-mysql-attachment/attachmentTable/render.go
modules/dop/component-protocol/components/addon-mysql-attachment/config/configCopyParams/render.go
modules/dop/component-protocol/components/addon-mysql-attachment/config/configDrawer/render.go
modules/dop/component-protocol/components/addon-mysql-attachment/config/configPanel/render.go
modules/dop/component-protocol/components/addon-mysql-attachment/editFormModal/render.go
modules/dop/component-protocol/components/addon-mysql-attachment/filter/render.go
modules/orchestrator/components/addon/mysql/kms.wrapper.go
modules/orchestrator/components/addon/mysql/kms.wrapper.impl.go
modules/orchestrator/components/addon/mysql/mysql.service.go
modules/orchestrator/components/addon/mysql/mysql.service_test.go
modules/orchestrator/components/addon/mysql/provider.go
modules/orchestrator/dbclient/addon_mysql_account.go
modules/orchestrator/initialize.go
modules/orchestrator/services/addon/addon.go
modules/orchestrator/services/addon/addon_handler.go
modules/orchestrator/services/addon/addon_mysql.go
modules/orchestrator/services/addon/addon_mysql_test.go

/kind bugfix
fix addon mysql account some not work
/assign @sfwn 

fix addon mysql account some not work

---

modules/cmp/alert.go

/kind bugfix
| 🇺🇸 English |       Trigger internationalization       |
| 🇨🇳 中文    |       cmp下的触发条件国际化       |

Trigger internationalization

---

go.mod
go.sum
modules/cmp/steve/middleware/audit.go
modules/cmp/steve/middleware/dispatcher.go
modules/cmp/steve/middleware/dispatcher_test.go
modules/cmp/steve/websocket/decode.go
modules/cmp/steve/websocket/decode_test.go

/kind feature
support bash cmd line
/label cmp
/label feature

feat: 🎸 support bash cmd line

---

modules/dop/component-protocol/components/issue-dashboard/bar/stateVerticalBarChart/model.go
modules/dop/component-protocol/components/issue-dashboard/bar/stateVerticalBarChart/render.go
modules/dop/component-protocol/scenarios/issue-stats.yml

feature
Hide iteration bar chart when single iteration is selected
/assign @sfwn 

Hide iteration bar chart when single iteration is selected

---

modules/cmp/component-protocol/components/cmp-dashboard-nodeDetail/common/model.go
modules/cmp/component-protocol/components/cmp-dashboard-nodeDetail/common/utils.go
modules/cmp/component-protocol/components/cmp-dashboard-nodeDetail/infoMapTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/chart/model.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/utils.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/cpuTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/memTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/podTable/render.go
modules/cmp/metrics/metrics.go
modules/cmp/resource/class.go
modules/cmp/steve/middleware/dispatcher.go
modules/cmp/steve/middleware/dispatcher_test.go

1.add some test for dipatcher and fix bugs
2.remove unused function of cmp
/kind refactor

refactor: 💡 add test, remove redundant code

---

apistructs/code_coverage_exec_record.go

/kind bugfix
modify code coverage chart tooltip display complete path
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=246108&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=541&type=BUG) …

modify code coverage chart tooltip

---

modules/core/monitor/alert/alert-apis/alert.service.go
modules/msp/apm/alert/alert.service.go

/kind bugfix
| 🇺🇸 English |       add cluster application in 1.4       |
| 🇨🇳 中文    |       修复1.4中过滤条件缺少cluster_name和application_id       |

add cluster application in 1.4

---

modules/dop/dao/autotest_exec_history.go
modules/dop/services/autotest_v2/testplan_v2.go
modules/dop/services/autotest_v2/testplan_v2_test.go

fix: remove itrIDs filter to rate scene and api chart
/kind polish
fix: remove itrIDs filter to rate scene and api chart
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/task?id=246275&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDA2LDQ0MDddfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjIsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=541&type=TASK)
/assign @sfwn 
> For details on the cherry pick process, see the [cherry …

fix: remove itrIDs filter to rate scene and api chart

---

modules/orchestrator/components/addon/mysql/mysql.service.go
modules/orchestrator/components/addon/mysql/mysql.service_test.go
modules/orchestrator/components/addon/mysql/permission.wrapper.go

/kind bugfix
fix wrong audit template & missing params
/assign @sfwn 

fix wrong audit template & missing params

---

.erda/migrations/pipeline/20211026-pipeline-cron-row-format.sql

/kind feature
ALTER TABLE `pipeline_crons` ROW_FORMAT=DYNAMIC ;

feature: ALTER TABLE  ROW_FORMAT=DYNAMIC ;

---

modules/core/monitor/alert/alert-apis/adapt/customize.go
modules/msp/apm/alert/alert.service.go

/kind bugfix
| 🇺🇸 English |      tk instead of tenantgroup        |
| 🇨🇳 中文    |     创建大盘使用tk代替tenantgroup       |

tk instead of tenantgroup

---

modules/msp/apm/checker/apis/checker.v1.service.go
modules/msp/apm/checker/apis/checker.v1.service_test.go
modules/msp/apm/checker/plugins/http/provider.go

bugfix: history checker

---

apistructs/audits.go

/kind bugfix
fix regexp pattern to support multiple line
/assign @sfwn 

fix regexp pattern to support multiple line

---

conf/msp/msp.yaml

/kind bugfix
| 🇺🇸 English |      Fix the bug that query data from es fail in Micro Service platform(disable es query in default)        |
| 🇨🇳 中文    |     修复了 msp 平台的查询es失败问题(关闭默认查询es)         |

close span query from es

---

go.mod
go.sum
modules/cmp/steve/middleware/audit.go
modules/cmp/steve/middleware/dispatcher.go
modules/cmp/steve/middleware/dispatcher_test.go

fix: 🐛 audit bug

---

modules/monitor/apm/topology/topology.go
modules/monitor/apm/topology/topology_test.go

bugfix: service analysis of HTTP list sort 

---

conf/dop/dop.yaml
conf/dop/i18n/component-protocol.yaml
modules/dop/component-protocol/components/test-dashboard/scenario.go
modules/dop/component-protocol/components/test-dashboard/tip/render.go
modules/dop/component-protocol/scenarios/test-dashboard.yml

/kind feature
feature: add tip to test dashboard
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=246522&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=-1&type=TASK)
/assign @sfwn  …

feature: add tip to test dashboard

---

modules/msp/apm/trace/query/provider.go
modules/msp/apm/trace/query/trace.service.go

/kind bugfix
| 🇺🇸 English |      Fix the bug that span es storageReader optional set error in msp platform        |
| 🇨🇳 中文    |       修复msp平台span的es storageReader服务依赖设置为非必要问题    |

set span es storage-reader optional to false

---

modules/msp/apm/checker/apis/checker.v1.service.go
modules/msp/apm/checker/apis/checker.v1.service_test.go

polish: checker

---

.erda/migrations/cmdb/20211109-fix-sys-role.sql
modules/dop/component-protocol/components/addon-mysql-account/accountTable/render.go
modules/dop/component-protocol/components/addon-mysql-account/accountTable/render_test.go
modules/dop/component-protocol/components/addon-mysql-account/addAccountButton/render.go
modules/dop/component-protocol/components/addon-mysql-account/common/datainit.go
modules/dop/component-protocol/components/addon-mysql-account/viewPassword/render.go
modules/dop/component-protocol/components/addon-mysql-attachment/attachmentTable/render.go
modules/orchestrator/components/addon/mysql/mysql.service.go
modules/orchestrator/components/addon/mysql/mysql.service_test.go

/kind bugfix
fix permission check
/assign @sfwn 

fix permission check

---

modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/workloadInfo/render_test.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/workloadStatus/render_test.go

fix unit test

---

apistructs/cmp_resource_overview.go
conf/cmp/i18n/component-protocol.yaml
modules/cmp/resource/report_table.go

/kind bugfix
fix: accuracy group by owner

fix: accuracy group by owner

---

modules/scheduler/executor/plugins/edas/edas.go

/kind bugfix
- fix: modify deployment name find methods
| 🇺🇸 English |fix: modify deployment name find methods|
| 🇨🇳 中文    |修复 edas 集群 deployment 查询的方式 |

fix: modify deployment name find methods

---

quick-start/kratos/identity.schema.json

feature
Update quick start identity schema

Update quick start identity schema

---

.erda/migrations/.patches/patch-20211031-mysql-account.sql
.erda/migrations/orchestrator/20211031-mysql-account.sql

/kind bugfix
patch 20211031-mysql-account.sql

patch: 20211031-mysql-account.sql

---

modules/dop/component-protocol/components/addon-mysql-account/common/datainit.go
modules/dop/component-protocol/components/addon-mysql-account/common/datainit_test.go

/kind bugfix
fix mysql addon page slow
/assign @sfwn 

fix mysql addon page slow

---

.erda/migrations/qa/20211110-auto-test-plan-update-data.sql

/kind polish
fix: add dice_autotest_plan migration
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=247055&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=541&type=BUG)
/assign @sfwn 
> …

fix: add dice_autotest_plan migration

---

go.mod
go.sum
modules/cmp/steve/middleware/audit.go
modules/cmp/steve/middleware/dispatcher.go
modules/cmp/steve/middleware/dispatcher_test.go

fix: 🐛 audit log start with new line

---

modules/openapi/auth/user.go

/kind bugfix
shared bundle in auth

shared bundle in auth

---

modules/core-services/services/project/cache.go
modules/core-services/services/project/project.go

/kind bugfix
feature: cache workspace quota

feature: cache workspace quota

---

build/scripts/cluster-agent/shell-setup.sh

…ine prefix
/kind bugfix
1. Remove envs in cluster-agent
2. Display full path in bash cmd lind prefix

fix: remove envs in cluster-agent

---

modules/core-services/dao/project.go
modules/core-services/services/project/cache.go
modules/core-services/services/project/project.go

/kind bugfix
fix: delete cache

fix: delete cache

---

modules/admin/manager/cluster.go
modules/admin/manager/cluster_test.go

/kind feature
/kind bugfix
/kind polish
/kind refactor
/kind document
| 🇺🇸 English | admin identity bugfix |
| 🇨🇳 中文    |  admin 身份信息 bugfix |

admin identity bugfix

---

.erda/migrations/cmdb/20211110-fix-dice-audit.sql
.erda/migrations/cmdb/20211110-fix-slow-audit-and-ticket.sql
.erda/migrations/qa/20211110-auto-test-fix-slow-sql.sql
modules/core-services/services/audit/audit.go

/kind polish
add index for dice_autotest_scene_step,dice_mboxs,ps_ticket and dice_audit.
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=243888&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjkyIl19&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=-1&type=TASK)
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUT …

fix dop slow sql

---

modules/cluster-agent/client/client.go
modules/cluster-agent/client/credential.go
modules/cluster-dialer/server/dialer_test.go
modules/cluster-dialer/server/tunnel-server_test.go
modules/cmp/impl/clusters/credential.go
modules/cmp/impl/clusters/credential_test.go
modules/cmp/impl/clusters/import_cluster.go

/kind bugfix
upgrade falut tolerance
| 🇺🇸 English | upgrade falut tolerance  when update from 1.3 to 1.4    |
| 🇨🇳 中文    |  提升 1.3 到 1.4 版本升级，对 aksk 的容错            |

fix: upgrade falut tolerance

---

modules/openapi/component-protocol/scenarios/auto-test-plan-list/protocol.yml

bugfix
Fix auto test plan table column width, add scroll
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=247463&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMDczIl19&issueGantt__urlQuery=eyJwYWdlTm8iOjEsInBhZ2VTaXplIjoxMCwiaXNzdWVWaWV3R3JvdXBWYWx1ZSI6ImdhbnR0IiwiSXNzdWVUeXBlIjoiQUxMIn0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjIsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)
/assign @sfwn  …

Fix auto test plan table column width, add scroll

---

modules/dop/component-protocol/components/issue-dashboard/scatterPlot/render.go
modules/dop/component-protocol/components/issue-dashboard/scatterPlot/render_test.go

bugfix
Fix illegal time data in issue dashboard scatter plot\
/assign @sfwn 

Fix illegal time data in issue dashboard scatter plot

---

conf/cmp/i18n/component-protocol.yaml
modules/cmp/component-protocol/components/cmp-dashboard-nodeDetail/operationButton/model.go
modules/cmp/component-protocol/components/cmp-dashboard-nodeDetail/yamlFileEditor/model.go
modules/cmp/component-protocol/components/cmp-dashboard-nodeDetail/yamlFileEditor/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodeDetail/yamlFileEditor/render_test.go
modules/cmp/component-protocol/components/cmp-dashboard-podDetail/yamlFileEditor/model.go
modules/cmp/component-protocol/components/cmp-dashboard-podDetail/yamlFileEditor/render.go
modules/cmp/component-protocol/components/cmp-dashboard-podDetail/yamlFileEditor/render_test.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/restartButton/model.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/restartButton/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/yamlFileEditor/model.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/yamlFileEditor/render.go

/kind feature
add success message for delete, update and restart

add success message

---

modules/openapi/component-protocol/scenarios/auto-test-scenes/components/executeInfo/render.go

/kind bugfix
fix: Recovery pass rate and execution rate statistics
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=248127&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)
Add comment like `/cherry-pick release/1.0` when …

fix: Recovery pass rate and execution rate statistics of auto test scene

---

modules/core-services/endpoints/namespace.go

/kind bugfix
fix: ignore platform namespaces

fix: ignore platform namespaces

---

apistructs/autotest_space.go
apistructs/autotest_space_test.go
bundle/autotest_space.go
modules/dop/dao/autotest_space.go
modules/dop/endpoints/autotest_scene.go
modules/dop/endpoints/autotest_scene_step.go
modules/dop/endpoints/autotests_space.go
modules/dop/endpoints/scenesets.go
modules/dop/services/autotest_v2/space.go
modules/dop/services/sceneset/sceneset.go
modules/openapi/component-protocol/scenarios/auto-test-space-list/components/spaceAddButton/render.go
modules/openapi/component-protocol/scenarios/auto-test-space-list/components/spaceFormModal/render.go
pkg/erda-configs/audit/template.json

feature
Auto test space update time whenever elements in the space change
/assign @sfwn 

Auto test space update time whenever elements in the space change

---

apistructs/cluster_info.go
modules/dop/services/pipeline/pipeline.go
modules/dop/services/pipeline/pipeline_test.go

/kind bugfix
use job cluster as cluster name if not empty

use job cluster as cluster name if not empty

---

modules/core-services/services/project/project.go
modules/core-services/services/project/project_test.go

/kind bugfix
patch resource config default by cluster config

patch resource config default by cluster config

---

apistructs/service.go
modules/scheduler/executor/plugins/k8s/daemonset.go
modules/scheduler/executor/plugins/k8s/deployment.go
modules/scheduler/executor/plugins/k8s/k8s.go
modules/scheduler/executor/plugins/k8s/namespace.go
modules/scheduler/executor/plugins/k8s/namespace_test.go
modules/scheduler/executor/plugins/k8s/runtime.go
modules/scheduler/executor/plugins/k8s/secret.go
modules/scheduler/executor/plugins/k8s/secret/secret.go
modules/scheduler/executor/plugins/k8s/secret_test.go
modules/scheduler/executor/plugins/k8s/statefulset.go

/kind bugfix
- fix: update secret when use image username and password
| 🇺🇸 English |fix: update secret when use image username and password|
| 🇨🇳 中文    | 修复使用 image username 和password 不会更新 secret 的问题|

fix: update secret when use image username and password

---

apistructs/bigdata.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sspark/k8sspark.go

/kind feature
spark task support python files
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=217812&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=-1&type=REQUIREMENT)
| 🇺🇸 English | Support spark task use python files              |
| 🇨🇳 中文    | 实现spark任务支持python文件执行 …

support spark crd use pyFiles

---

.erda/migrations/hepa/20211115-hepa-domain-add-org-1.sql
.erda/migrations/hepa/20211115-hepa-domain-add-org-2.sql
modules/hepa/gateway/dto/manage_domain_info.go
modules/hepa/k8s/k8s_adapter.go
modules/hepa/providers/endpoint_api/endpoint.api.service.go
modules/hepa/repository/orm/gateway_domain.go
modules/hepa/services/domain/impl/impl.go
modules/hepa/services/domain/interface.go
modules/hepa/services/endpoint_api/impl/impl.go
modules/hepa/services/endpoint_api/interface.go
modules/hepa/services/runtime_service/impl/impl.go

/kind feature
domain manage support use org id

domain manage support use org id

---

modules/core/monitor/log/query/log.query.service.go

/kind bugfix
fix log query bug if failed to create Iterator

fix log query bug

---

apistructs/cmp_k8s_clusters.go
modules/cmp/component-protocol/components/cmp-dashboard-events-list/eventTable/render.go
modules/cmp/endpoints/endpoints.go
modules/cmp/endpoints/k8s_cluster.go
modules/cmp/steve/aggregator.go
modules/cmp/steve/middleware/auth.go
modules/openapi/api/apis/cmp/cmp_k8s_clusters.go

/kind feature
list ready and unready clusters registered in steve aggregator

add list k8s clusters

---

apistructs/audits.go
apistructs/autotest_space.go
modules/dop/services/autotest_v2/space.go
modules/dop/services/autotest_v2/space_test.go
modules/openapi/component-protocol/scenarios/auto-test-space-list/components/spaceList/operation.go
pkg/erda-configs/audit/template.json

bugfix
Fix auto test space list pageNo reset
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=249626&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMDczIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)
/assign @sfwn  …

Fix auto test space list pageNo reset

---

modules/core/monitor/log/storage/elasticsearch/iterator.go

/kind bugfix
log query compatiblity for source=deploy

log query compatiblity for source=deploy

---

modules/cmp/component-protocol/components/cmp-dashboard-nodeDetail/addLabelModal/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodeDetail/addLabelModal/render_test.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/table/table.go

fix: 🐛 add label bug

---

apistructs/cmp_k8s_clusters.go
modules/cmp/component-protocol/components/cmp-dashboard-events-list/eventTable/render.go
modules/cmp/endpoints/k8s_cluster.go

/kind bugfix
change cluster list resp to erda style

fix: change cluster list resp to erda style

---

modules/dop/dao/issue_issue_relation.go
modules/dop/endpoints/issue_related.go

bugfix
Check for existence when adding issue relation
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=227823&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMDczIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)
/assign @sfwn  …

Check for existence when adding issue relation

---

modules/scheduler/executor/plugins/k8s/k8s.go
modules/scheduler/executor/plugins/k8s/k8s_test.go
pkg/istioctl/engines/local_engine.go

/kind refactor
refactor the istio ct logic with new k8sclient

refactor the istio control logic with new k8sclient

---

modules/dop/dao/autotest_exec_history.go

/kind bugfix
fix: update to solve the slow sql and order problems
/assign @sfwn 
cherry-pick release/1.4
cherry-pick release/1.5-alpha1

fix: update to solve the slow sql and order problems

---

modules/core/monitor/alert/alert-apis/adapt/alert_convert.go

/kind bugfix
| 🇺🇸 English |      compatible old customize alert        |
| 🇨🇳 中文    |      兼容老的自定义告警规则        |

compatible old customize alert

---

modules/scheduler/executor/plugins/edas/edas.go

/kind bugfix
- fix(edas): set cpu request error when scale the service group
| 🇺🇸 English | fix(edas): set cpu request error when scale the service group |
| 🇨🇳 中文    |  修复扩容 serviceGroup 时错误设置了 CPU 的值  |

fix(edas): set cpu request error when scale the service group

---

modules/cmp/component-protocol/components/cmp-dashboard-events-list/eventTable/render.go
modules/cmp/endpoints/cluster.go
modules/cmp/endpoints/steve.go
modules/cmp/steve/aggregator.go

/kind feature
delete steve server when offline cluster

delete steve server when offline cluster

---

conf/cmp/cmp.yaml
go.mod
go.sum
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/filter/filter.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/table/table.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/table/table_test.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/cpuTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/memTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/nodeFilter/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/nodeFilter/render_test.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/podTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/tableTabs/model.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/tableTabs/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/tableTabs/render_test.go
modules/cmp/component-protocol/scenarios/cmp-dashboard-nodes.yml

fix: 🐛 add cmp dashboard node list url

---

modules/core/monitor/alert/alert-apis/adapt/alert_convert.go
modules/core/monitor/alert/alert-apis/adapt/customize.go

/kind bugfix
| 🇺🇸 English |      any instead of any        |
| 🇨🇳 中文    |      用any代替all操作        |

any instead of any

---

conf/msp/msp.yaml

/kind feature
/kind bugfix
/kind polish
/kind refactor
/kind document

Fix span es url env

---

.erda/migrations/.patches/patch-20211115-hepa-domain-add-org-1.sql

/kind bugfix
add hepa patch sql

add hepa patch sql

---

conf/monitor/log-service/log-service.yaml
modules/extensions/loghub/metrics/analysis/consumer.go
modules/extensions/loghub/metrics/analysis/processors/processors.go
modules/extensions/loghub/metrics/analysis/processors/processors_test.go
modules/extensions/loghub/metrics/analysis/processors/regex/regex.go
modules/extensions/loghub/metrics/analysis/processors/regex/regex_test.go
modules/extensions/loghub/metrics/rules/routes.go

/kind feature
feature: log metrics support multiple scope rules

feature: log metrics support multiple scope rules

---

apistructs/core_services_quota.go
apistructs/core_services_quota_test.go
modules/core-services/dao/quota.go
modules/core-services/services/project/project.go

/kind bugfix
Fix the problem of missing projects with 0 request in the project resource ranking
| 🇺🇸 English | Fix the problem of missing projects with 0 request in the project resource ranking |
| 🇨🇳 中文    | 修复了项目资源排行中缺失资源使用值为 0  的项目的问题 |

Fix the problem of missing projects with 0 request in the project resource ranking

---

modules/cmp/component-protocol/components/cmp-dashboard-podDetail/podStatus/render.go
modules/cmp/component-protocol/components/cmp-dashboard-pods/podsCharts/model.go
modules/cmp/component-protocol/components/cmp-dashboard-pods/podsCharts/render.go
modules/cmp/component-protocol/components/cmp-dashboard-pods/podsCharts/render_test.go
modules/cmp/component-protocol/components/cmp-dashboard-pods/podsTable/model.go
modules/cmp/component-protocol/components/cmp-dashboard-pods/podsTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-pods/podsTable/render_test.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/podsTable/render.go
modules/cmp/component-protocol/cputil/util.go

/kind polish
change pods status color 

Pods color

---

conf/cmp/i18n/cp/scenarios/cmp-dashboard-workload-detail.yaml
conf/cmp/i18n/cp/scenarios/cmp-dashboard-workloads-list.yaml
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/filter/model.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/filter/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadChart/model.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadChart/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadChart/render_test.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadTable/model.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadTable/render_test.go
modules/cmp/component-protocol/cputil/util.go
modules/cmp/component-protocol/cputil/util_test.go

/kind polish
add Updating status for deployment, change error to abnormal

add Updating status for deployment

---

.erda/migrations/msp/20211119-menu.sql

/kind bugfix
bugfix: update microservice menu jump key

bugfix: update microservice menu jump key

---

build/dockerfiles/Dockerfile-action-agent
cmd/actionagent/main.go
modules/actionagent/callback.go
modules/actionagent/define.go
modules/actionagent/execute.go
modules/actionagent/exit.go
modules/actionagent/file_watch.go
modules/actionagent/file_watch_collector.go
modules/actionagent/file_watch_collector_test.go
modules/actionagent/filewatch/watch.go
modules/actionagent/prestop.go
modules/actionagent/step_logic.go
modules/actionagent/step_prepare.go

/kind bugfix
action-agent: stop filewatcher after callback
Tested in [erda-dev](https://erda.dev.terminus.io/sfwn-org/dop/projects/62/apps/65/pipeline?nodeId=NjIvNjUvdHJlZS9tYXN0ZXIvLmRpY2UvcGlwZWxpbmVzL3Rlc3QtY2IueW1s&pipelineID=10065716) (Normal scenario and use collector)
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=250668&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyI5MiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=TASK)
/assign @Effet

fix actionagent callback

---

modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sflink/flink.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sjob/k8sjob.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sspark/k8sspark.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/scheduler.go

/kind bugfix
set executor normal log debug level
| 🇺🇸 English |Fix the bug that executor too many logs in pipeline platform              |
| 🇨🇳 中文    | 修复了pipeline executor 日志打印过多的问题             |

set executor normal log debug level

---

go.mod
modules/cmp/component-protocol/components/cmp-dashboard-events-list/eventTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-events-list/filter/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/addWorkloadButton/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/addWorkloadDrawer/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/addWorkloadFileEditor/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/filter/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadChart/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadTitle/render.go
modules/cmp/steve/dynamiccolumns.go
modules/cmp/steve/schemas.go
modules/cmp/steve/server.go

/kind bugfix
add meta.k8s.io/v1beta1 in restconfig
Need cherry-pick to release/1.4 and release/1.5

fix: add meta.k8s.io/v1beta1 in restconfig

---

modules/hepa/apipolicy/policies/server-guard/policy.go

/kind bugfix
add log plugin in limit location

add log plugin in limit location

---

conf/cmp/i18n/cp/scenarios/cmp-dashboard-nodes.yaml
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/table/table.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/table/table_test.go

/kind refactor
change value of unused rate

refactor: 💡 change unused rate

---

conf/monitor/streaming/streaming.yaml
erda.yml

/kind feature
/kind bugfix
/kind polish
/kind refactor
/kind document

Update streaming group id

---

.erda/migrations/qa/20211110-test-file-record-err-info.sql
apistructs/file_records.go
modules/dop/dao/file_records.go
modules/dop/services/testcase/export.go
modules/dop/services/testcase/file_records.go
modules/dop/services/testcase/import.go

feature
Add error info in test file record, available when task failed
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/ticket?assignee[]=1001073&id=244123&pageNo=1)
/assign @sfwn 

Add error info in test file record, available when task failed

---

go.mod
go.sum

go get erda-infra

---

modules/core-services/services/dingtalk/api/manager/accesstoken_manager.go

/kind bugfix
feature: ak expires little bit early than the real expire time

optimize: ak expires little bit early than the real expire time

---

conf/cmp/i18n/cp/scenarios/cmp-dashboard-nodes.yaml
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/table/table.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/table/table_test.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/cpuTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/memTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/podTable/render.go

/kind refactor
change unused to used

refactor: 💡 change unused to used

---

modules/orchestrator/services/addon/addon_mysql.go
modules/orchestrator/services/addon/addon_mysql_test.go

/kind bugfix
try decrypt for old-style mysql addon
/assign @sfwn 

try decrypt for old-style mysql addon

---

modules/cmp/component-protocol/components/cmp-dashboard-pods/podsCharts/model.go
modules/cmp/component-protocol/components/cmp-dashboard-pods/podsCharts/render.go
modules/cmp/component-protocol/components/cmp-dashboard-pods/podsCharts/render_test.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadChart/render.go
modules/cmp/steve/request.go

/kind bugfix
1. modify color of workload chart
2. fix panic in auth
3. modify pods charts

modify color of workload chart; fix panic in auth

---

modules/dop/component-protocol/components/auto-test-scenes/leftPage/fileFormModal/render.go
modules/dop/component-protocol/components/auto-test-scenes/leftPage/fileTree/render.go
modules/dop/component-protocol/components/auto-test-scenes/leftPage/fileTree/scenes.go
modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/stages/render.go
modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/render.go
modules/dop/services/autotest_v2/scene.go
modules/dop/services/autotest_v2/testplan_v2.go
modules/openapi/component-protocol/scenarios/auto-test-plan-detail/protocol.yml

bugfix
Fix auto test scenes feature interaction, remove drag in filetree

Fix auto test scenes feature interaction, remove drag in filetree

---

conf/cmp/cmp.yaml
conf/cmp/i18n/cp/scenarios/cmp-cluster-list.yaml
conf/openapi/openapi.yaml
modules/cmp/cmp_interface/provider.go
modules/cmp/component-protocol/components/all.go
modules/cmp/component-protocol/components/cmp-cluster-list/common/model.go
modules/cmp/component-protocol/components/cmp-cluster-list/list/model.go
modules/cmp/component-protocol/components/cmp-cluster-list/list/render.go
modules/cmp/component-protocol/components/cmp-cluster-list/list/render_test.go
modules/cmp/component-protocol/components/cmp-cluster-list/page/model.go
modules/cmp/component-protocol/components/cmp-cluster-list/page/render.go
modules/cmp/component-protocol/components/cmp-cluster-list/scenario.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/cpuTable/render.go
modules/cmp/component-protocol/scenarios/cmp-cluster-list.yml
modules/cmp/metrics/metrics.go
modules/cmp/provider.go

/kind feature
cluster for component protocol

refactor: 💡 cluster for component protocol

---

modules/cmp/component-protocol/components/cmp-dashboard-events-list/eventTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-events-list/filter/render.go
modules/cmp/component-protocol/components/cmp-dashboard-podDetail/yamlFileEditor/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/yamlFileEditor/render.go

/kind bugfix
fix: get pod and workload failed by support user: no matches for kind xxx in version xxx

fix: use CRClient to get k8s resources

---

modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/table/render.go
modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/table/render_test.go

/kind bugfix
fix: solve the panic of auto test plan
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=256222&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)
/assign @sfwn 
> For details on the cherry …

fix: solve the panic of auto test plan

---

modules/dop/component-protocol/components/auto-test-scenes/leftPage/fileTree/scenes.go

/kind feature
remove copy operation of ref scene
/assign @swfn

remove copy operation of ref scene

---

modules/hepa/k8s/k8s_adapter.go
modules/hepa/services/domain/impl/impl.go
modules/hepa/services/global/impl/impl.go
modules/hepa/services/runtime_service/impl/impl.go
modules/hepa/services/zone/impl/impl.go

/kind bugfix
fix use admin endpoint error

fix use admin endpoint error

---

modules/cmp/component-protocol/components/cmp-dashboard-events-list/eventTable/render.go
modules/cmp/endpoints/cluster.go
modules/cmp/steve/aggregator.go

…clusters
/kind bugfix
1. Create steve server when import cluster
2. Modify interval of watching clusters

create steve server when import cluster

---

modules/cmp/component-protocol/components/cmp-dashboard-pods/podsTable/model.go
modules/cmp/component-protocol/components/cmp-dashboard-pods/podsTable/render.go

/kind bugfix
fix: add namespaces in pod table to fix pod monitor graph

fix: add namespaces in pod table to fix pod monitor graph

---

conf/monitor/monitor/chartview/cmp/cmp-dashboard-podDetail.json

/kind bugfix
change expression function of pod io graph from diff to diffps

fix: pod io monitor graph

---

modules/dop/component-protocol/components/auto-test-scenes/leftPage/fileTree/render.go

bugfix
Fix empty scene id when editing scene set stages

Fix empty scene id when editing scene set stages

---

conf/cmp/i18n/cp/scenarios/cmp-cluster-list.yaml
modules/cmp/component-protocol/components/cmp-cluster-list/list/render.go
modules/cmp/component-protocol/components/cmp-cluster-list/list/render_test.go
modules/cmp/metrics/metrics.go

fix: 🐛 change quota to limit

---

erda.yml

/kind bugfix
Scheduler will try to create all cluster executor, then start web server.
maybe failed when  too many clusters are unreachable.  
| 🇺🇸 English |  fix: scheduler health check time            |
| 🇨🇳 中文    |    临时调整 scheduler 健康检查时间          |

fix: scheduler health check time

---

modules/dop/services/autotest_v2/testplan_v2.go
modules/pipeline/aop/plugins/pipeline/apitest_report/plugin.go

/kind bugfix
fix: no statistics if scene try latest success result
/assign @sfwn 

fix: no statistics if scene try latest success result

---

conf/monitor/streaming/event_index_template.json
conf/monitor/streaming/log_index_template.json
conf/monitor/streaming/span_index_template.json
conf/monitor/streaming/streaming.yaml

optimize: change es storage parameters

---

modules/cmp/metrics/metrics.go

/kind bugfix
fix async get cluster resource

fix: 🐛 fix async get cluster resource

---

conf/monitor/streaming/span_index_template.json
conf/msp/msp.yaml
modules/msp/apm/trace/storage/elasticsearch/iterator.go

fix trace query

---

modules/hepa/k8s/k8s_adapter.go

/kind feature
the new version of ingress controller use the label of `app=ingress-nginx`

support native ingress

---

conf/cmp/i18n/cp/scenarios/cmp-dashboard-nodes.yaml
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/table/table.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/memTable/render.go
modules/cmp/metrics/metrics.go

/kind bugfix
divide zoro if node does not has request

fix: 🐛 divide zoro if node does not has request

---

build/scripts/make-version.sh

/kind polish
polish make version script
/assign @sfwn 

polish make version script

---

modules/msp/tenant/project/project.service.go
modules/msp/tenant/project/project.service_test.go
modules/msp/tenant/project/project_statistics.go

/kind bugfix
/cherry-pick release/1.5-alpha2

bugfix: microservice projects statistics error

---

modules/dop/component-protocol/components/auto-test-scenes/leftPage/fileFormModal/model.go
modules/dop/component-protocol/components/auto-test-scenes/leftPage/fileFormModal/render.go
modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesSetConfig/scenesStages/model.go
modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesSetConfig/scenesStages/operation.go

bugfix
Fix auto test scene filetree edit scene
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=257182&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMDczIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)
/assign @sfwn 
Add comment like `/cherry-pick release/1.5-alpha2` when this PR is merged. …

Fix auto test scene filetree edit scene

---

modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadTotal/model.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadTotal/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadTotal/render_test.go

/kind bugfix
sum abnormal and updating workloads in workloadTotal component

fix: workload total error

---

conf/monitor/streaming/span_index_template.json
modules/msp/apm/trace/storage/elasticsearch/iterator.go
modules/msp/tenant/project/project_statistics.go

/kind feature
/kind bugfix
/kind polish
/kind refactor
/kind document

Fix span query bug

---

modules/hepa/k8s/k8s_adapter.go
modules/hepa/k8s/k8s_adapter_test.go

/kind feature
support 1.x nginx ingress controller

support 1.x nginx ingress controller

---

modules/dop/services/iteration/iteration.go

/kind bugfix
don't need return error if empty iterations

return nil if empty iterations

---

modules/hepa/k8s/k8s_adapter.go

/kind feature
use new version ingress first

use new version ingress first

---

modules/msp/registercenter/register.center.service.go

/kind bugfix
ingore registercenter query error

ingore registercenter query error

---

modules/msp/registercenter/register.center.service.go

/kind bugfix
ingore registercenter query error

ignore registercenter query error

---

pkg/k8s/interface_factory/ingress.go

/kind feature
use networking.k8s.io/v1 ingress if version exists

use networking.k8s.io/v1 ingress if version exists

---

modules/dop/component-protocol/components/test-dashboard/at_api_chart_group/at_api_avg_cost_chart/render.go
modules/dop/component-protocol/components/test-dashboard/at_api_chart_group/at_api_rate_failed_chart/render.go
modules/dop/component-protocol/components/test-dashboard/at_case_rate_trending_chart_group/chart/render.go
modules/dop/component-protocol/components/test-dashboard/common/gshelper/helper.go
modules/dop/component-protocol/components/test-dashboard/filter/render.go
modules/dop/component-protocol/components/test-dashboard/overview_group/blocks/at/at_block_header_filter/render.go
modules/dop/component-protocol/components/test-dashboard/overview_group/blocks/at/at_num_api/render.go
modules/dop/component-protocol/components/test-dashboard/overview_group/blocks/at/at_num_scene/render.go
modules/dop/component-protocol/components/test-dashboard/scene_chart_group/scene_avg_cost_chart/render.go
modules/dop/component-protocol/components/test-dashboard/scene_chart_group/scene_rate_failed_chart/render.go
modules/dop/component-protocol/components/test-dashboard/scene_chart_group/scene_rate_passed_chart/render.go
modules/dop/dao/autotest_exec_history.go
modules/dop/dao/autotest_scene.go
modules/dop/services/autotest_v2/scene.go

/kind polish
fix: reduce global state to solve the problem of slow loading
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=257257&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)
/assign @sfwn 
/cherry-pick release/1.5-alpha2 …

fix: reduce global state to solve the problem of slow loading

---

bundle/events.go
modules/core-services/services/notify/channel/notify.chanel.service.go
modules/dop/endpoints/issue_callback.go
modules/dop/endpoints/issue_callback_test.go
modules/eventbox/subscriber/dingtalk_worknotice/dingtalk_worknotice.go
pkg/erda-configs/i18n/notify_item.yml

/kind feature
issues support dingding talk notice
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=258536&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=TASK)
| 🇺🇸 English | issues support dingding talk notice in dop platform             |
| 🇨🇳 中文    | …

issues support dingding talk notice

---

modules/scheduler/executor/plugins/edas/edas.go

/kind bugfix
fix edas 601 ongoing problem

fix edas 601 ongoing problem

---

modules/cmp/component-protocol/components/cmp-cluster-list/list/render.go
modules/cmp/metrics/metrics.go
modules/cmp/metrics/metricsReq.go
modules/cmp/metricsImpl.go

/kind refactor
1.filter virtual node ,show cluster list with display name
2.change disk metrics source

refactor: 💡 disk metrics data

---

modules/cmp/component-protocol/components/cmp-dashboard-podDetail/containerTable/render.go

/kind bugfix
fix: container restart log

fix: container restart log

---

go.mod
modules/cmp/steve/dynamiccolumns.go
modules/cmp/steve/schemas.go
modules/cmp/steve/server.go

/kind bugfix
cherry-pick "add meta.k8s.io/v1beta1 in restconfig" to release/1.4

cherry-pick: add meta.k8s.io/v1beta1 in restconfig

---

bundle/middleware.go
modules/cmp/component-protocol/components/cmp-dashboard-events-list/eventTable/render.go

/kind feature
add bundle method to list middleware

feat: add bundle method to list middleware

---

modules/cmp/impl/clusters/credential.go
modules/cmp/impl/clusters/credential_test.go
pkg/k8sclient/client.go
pkg/k8sclient/config/config.go

/kind bugfix
| 🇺🇸 English |  reset credential when create action in master cluster            |
| 🇨🇳 中文    |   master集群点击创建认证时触发重置认证信息           |

fix: reset credential when create action in master cluster

---

modules/core-services/services/notify/channel/notify.chanel.service.go
modules/core-services/services/notify/channel/notify.chanel.service_test.go
tools/gotools/go-test-sum/main.go

bugfix: Notify channels use nicknames to show the creator

---

conf/monitor/streaming/streaming.yaml
erda.yml
go.mod
modules/oap/collector/receivers/common/interceptors.go
pkg/common/trace/trace.go

/kind feature
/kind bugfix
/kind polish
/kind refactor
/kind document

Lightweight opentelemetry config

---

modules/oap/collector/receivers/common/interceptors.go

/kind feature
/kind bugfix
/kind polish
/kind refactor
/kind document

Fix set terminus_key tag

---

conf/monitor/streaming/streaming.yaml

/kind feature
/kind bugfix
/kind polish
/kind refactor
/kind document

Add erda-trace-metrics topic to metric consumer

---

modules/cmp/endpoints/officer.go

/kind feature
/kind bugfix
fix cidepcache image recycle problem

fix cidepcache image recycle problem

---

pkg/parser/diceyml/define.go

/kind feature
- feat: unmarshal binds yaml
| 🇺🇸 English | feat: unmarshal binds yaml             |
| 🇨🇳 中文    | 增加对 binds 结构的 yaml 解析            |

feat: unmarshal binds yaml

---

modules/dop/component-protocol/components/test-dashboard/at_case_rate_trending_chart_group/chart/render.go

/kind polish
fix: update time format to executeTime

fix: update time format to executeTime

---

erda.yml

/kind feature
/kind bugfix
/kind polish
/kind refactor
/kind document

Set erda trace disable default

---

modules/dop/component-protocol/components/issue-gantt/filter/model.go
modules/dop/component-protocol/components/issue-gantt/filter/render.go
modules/dop/services/issue/issue.go

Add filter url query, fix time validation

---

modules/cmp/impl/nodes/query.go

/kind bugfix
cmp query record timeout check
| 🇺🇸 English |  cmp query record timeout check |
| 🇨🇳 中文    |  增加 cmp 操作超时时间检查 |

cmp query record timeout check

---

apistructs/issue.go
modules/dop/component-protocol/components/common/issue.go
modules/dop/component-protocol/components/issue-manage/issueKanban/issue_kanban.go
modules/dop/component-protocol/components/issue-manage/issueKanban/render.go
modules/dop/component-protocol/scenarios/issue-manage.yml
modules/dop/services/issue/convert.go

/kind feature
- feature: issue-manage cp add syncIntervalSecond to 30s
- feature: issue-kanban card add status and labels
- feature: issue-kanban drag support async operation
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=259242&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyI5MiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=TASK)
/assign @Effet @shuofan

kanban card new style

---

modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesSetConfig/scenesStages/model.go

/kind polish
fix: added second confirmation for scene deletion
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=261398&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjYxIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG) …

fix: added second confirmation for scene deletion

---

modules/cmp/component-protocol/components/cmp-dashboard-events-list/eventTable/model.go
modules/cmp/component-protocol/components/cmp-dashboard-events-list/eventTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-podDetail/containerTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-pods/podsTable/model.go
modules/cmp/component-protocol/components/cmp-dashboard-pods/podsTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/podsTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadTable/render_test.go

/kind polish
1. Align left for all columns
2. Hidden some columns to display completely in mac monitor

polish pods table and events table

---

conf/cmp/i18n/cp/scenarios/cmp-cluster-list.yaml
modules/cmp/component-protocol/components/cmp-cluster-list/list/model.go
modules/cmp/component-protocol/components/cmp-cluster-list/list/render.go
modules/cmp/component-protocol/components/cmp-cluster-list/list/render_test.go

feat: 🎸 add cluster version

---

apistructs/issue.go
modules/dop/component-protocol/components/issue-gantt/filter/model.go
modules/dop/component-protocol/components/issue-gantt/filter/render.go
modules/dop/component-protocol/components/issue-gantt/gantt/render.go
modules/dop/component-protocol/components/issue-manage/issueViewGroup/render.go
modules/dop/dao/issue_issue_relation.go
modules/dop/services/issue/issue.go

Fix issue gantt iteration filter, remove deprecated gantt chart

---

apistructs/issue.go
apistructs/issue_state.go
modules/dop/component-protocol/components/issue-gantt/gantt/render.go
modules/dop/dao/issue.go
modules/dop/dao/issue_issue_relation.go
modules/dop/services/issue/issue.go

feature
Issue children count, query issue items not included

Issue children count, query issue items not included

---

.erda/migrations/cmdb/20211207-issue-plan-start-time.sql
modules/dop/dao/issue_issue_relation.go

feature
Issue plan started at db migration

Issue plan started at db migration

---

modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/podsTable/model.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/podsTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadChart/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadTable/render.go
modules/cmp/component-protocol/cputil/util.go
modules/cmp/component-protocol/cputil/util_test.go

/kind bugfix
1. fix: pending pod not exists in workload detail
2. polish: workloads status

fix: pending pod not exists in workload detail

---

conf/cmp/i18n/cp/scenarios/cmp-dashboard-workload-detail.yaml
conf/cmp/i18n/cp/scenarios/cmp-dashboard-workloads-list.yaml
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/filter/model.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/filter/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadChart/model.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadChart/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadTable/model.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadTotal/model.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadTotal/render.go
modules/cmp/component-protocol/cputil/util.go
modules/cmp/component-protocol/cputil/util_test.go

/kind feature
add stopped status for workload
Nedd cherry-pick to release/1.5

feat: add stopped status for workload

---

modules/openapi/api/apis/msp/apm/log_service/msp_addon_logs_search_sequential.go
modules/openapi/api/apis/msp/apm/log_service/msp_addon_logs_statistic.go

bugfix: log statistics api spec migrate

---

apistructs/cmp.go
bundle/org.go
modules/cmp/endpoints/cluster.go
modules/cmp/endpoints/endpoints.go
modules/cmp/impl/clusters/offline_edge_cluster.go
modules/cmp/impl/clusters/offline_test.go
modules/core-services/dao/org_cluster_relation.go
modules/core-services/endpoints/endpoints.go
modules/core-services/endpoints/organization.go

/kind feature
add cluster batch offline & cluster offline bugfix
| 🇺🇸 English |  add cluster batch offline & cluster offline bugfix  |
| 🇨🇳 中文    | 集群批量下线于集群下线 bugfix |

add cluster batch offline

---

.github/workflows/git-sync.yml
pipeline.yml

/kind feature
add git-sync.yml & pipeline.yml for ci
/assign @sfwn 

add git-sync.yml & pipeline.yml for ci

---

modules/msp/apm/service/apm.service.service.go

feature: interval 4m for chart overview of service list 

---

modules/dop/component-protocol/components/issue-gantt/gantt/model.go
modules/dop/component-protocol/components/issue-gantt/gantt/render.go
modules/dop/services/issue/issue.go

bugfix
Fix issue gantt update time from milli, updated issue in inparams
/assign @sfwn 

Fix issue gantt update time from milli, updated issue in inparams

---

conf/msp/instrumentationlibrary/jaeger-template.yaml
modules/msp/apm/adapter/adapter.service.go

/kind feature
/kind bugfix
/kind polish
/kind refactor
/kind document

Fix msp.env.id replace

---

modules/dop/component-protocol/components/issue-gantt/gantt/render.go
modules/dop/dao/issue.go

feature
Issue gantt chart filtered by unfinished state belongs
/assign @sfwn 

Issue gantt chart filtered by unfinished state belongs

---

conf/openapi/openapi.yaml

/kind feature
add scenarios to openapi.yaml

add scenarios to openapi.yaml

---

modules/dop/component-protocol/components/issue-manage/issueTable/render.go

feature
New style issue table item
/assign @sfwn 

New style issue table item

---

modules/dop/component-protocol/components/requirement-task-overview/chartBlock/burnoutChart/render.go
modules/dop/component-protocol/components/requirement-task-overview/container/info/model.go
modules/dop/component-protocol/components/requirement-task-overview/container/info/render.go

fix the bugs of require-task-overview
/kind bugfix

fix the bugs of require-task-overview

---

conf/cmp/i18n/cp/scenarios/cmp-cluster-list.yaml
modules/cmp/component-protocol/components/cmp-cluster-list/list/model.go
modules/cmp/component-protocol/components/cmp-cluster-list/list/render.go
modules/cmp/component-protocol/components/cmp-cluster-list/list/render_test.go

/kind refactor
change cluster list data

refactor: 💡 change cluster list data

---

modules/pipeline/dbclient/op_pipeline_task.go

/kind bugfix
update pipeline result

update pipeline result

---

modules/dop/component-protocol/components/requirement-task-overview/container/simpleChart/render.go

/kind bugfix
fix the bug of simple chart of requirement task overview

fix the bug of simple chart of requirement task overview

---

modules/dop/component-protocol/scenarios/issue-manage.yml

/kind feature
feature: issue-manage stop sync temporarily
/assign @Effet

feature: issue-manage stop sync temporarily

---

.erda/migrations/cmdb/20211210-issue-expiry-status-update-index.sql

/kind feature
/kind bugfix
/kind polish
/kind refactor
/kind document
slow sql query
/assign @sfwn 

Add issue update undefined expiry status index

---

modules/dop/dao/issue.go
modules/dop/services/issue/issue.go

/kind feature
/kind bugfix
/kind polish
/kind refactor
/kind document

Fix issue gantt find issue root query

---

pkg/database/sqlparser/snapshot/config.go
pkg/database/sqlparser/snapshot/config_test.go
pkg/database/sqlparser/snapshot/error.go
pkg/database/sqlparser/snapshot/error_test.go
pkg/database/sqlparser/snapshot/snapshot.go
quick-start/docker-compose.yml

/kind feature
dump data while snapshotting database

dump data while snapshotting database

---

modules/core/monitor/log/query/log.query.service.go
modules/core/monitor/log/query/log.query.service_test.go
modules/core/monitor/log/storage/elasticsearch/aggregate.go
modules/core/monitor/log/storage/elasticsearch/iterator.go
modules/core/monitor/log/storage/storage.go

/kind bugfix
fix the bug that log query include too many es indices

bugfix: ensure orgName filter when query log

---

modules/dop/dao/issue.go

bugfix
Fix issue gantt root query, join relation parent

Fix issue gantt root query, join relation parent

---

modules/core/monitor/log/query/log.query.service.go
modules/core/monitor/log/query/routes.go

/kind bugfix
bugfix: fix bug that download container log got empty result

bugfix: fix bug that download container log got empty result

---

apistructs/pipeline.go
modules/cluster-dialer/server/tunnel-server.go
modules/cluster-dialer/server/tunnel-server_test.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sjob/k8sjob.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sjob/k8sjob_test.go

/kind feature
pipeline support buildkit
| 🇺🇸 English |  pipeline support buildkit            |
| 🇨🇳 中文    |   pipeline 支持 buildkit          |

feature: pipeline support buildkit

---

modules/core/monitor/log/query/log.query.service.go

/kind feature
/kind bugfix
bugfix: change default log query timerange to 3 hour, for perfomance consideration.
/cherry-pick release/1.5-alpha.4

bugfix: change default log query timerange to 3 hour

---

modules/dop/component-protocol/components/issue-gantt/gantt/render.go
modules/dop/dao/issue.go

bugfix
Add issue event operator in issue gantt chart
/assign @sfwn 
Add comment like `/cherry-pick release/1.5-alpha.4` when this PR is merged.

Add issue event operator in issue gantt chart

---

modules/core/monitor/alert/alert-apis/adapt/alert_convert.go
modules/core/monitor/alert/alert-apis/adapt/customize.go
modules/core/monitor/alert/alert-apis/alert.service.go

/kind bugfix
| 🇺🇸 English |       fix the bug of release/1.3 custom alert can not send       |
| 🇨🇳 中文    |      1.3自定义告警发不出去        |

fix the bug of release/1.3 custom alert can not send

---

build/dockerfiles/agent-injector/Dockerfile
build/scripts/monitor-agent-injector/container-init.sh
build/scripts/monitor-agent-injector/deployment/deploy.sh
build/scripts/monitor-agent-injector/deployment/deployment.yaml.template
build/scripts/monitor-agent-injector/deployment/generate-keys.sh
build/scripts/monitor-agent-injector/deployment/undeploy.sh
build/scripts/monitor-agent-injector/deployment/webhook-deploy.sh
build/scripts/monitor-agent-injector/deployment/webhook-undeploy.sh
build/scripts/monitor-agent-injector/deployment/webhook.yaml.template
cmd/monitor/agent-injector/main.go
conf/monitor/agent-injector/agent-injector.yaml
conf/resources.go
erda.yml
modules/core/monitor/agent-injector/admission_review.go
modules/core/monitor/agent-injector/pods.go
modules/core/monitor/agent-injector/provider.go
modules/core/monitor/agent-injector/routes.go

/kind feature
support monitor java-agent inject

monitor agent inject

---

modules/dop/dao/issue_issue_relation.go
modules/dop/services/issue/issue.go

feature
Requirement process is based on inclusion relation stats
/assign @sfwn 

Requirement process is based on inclusion relation stats

---

apistructs/issue.go
apistructs/issue_state.go
apistructs/workbench.go
modules/dop/component-protocol/components/common/issue.go
modules/dop/component-protocol/components/issue-dashboard/common/stackhandlers/state.go
modules/dop/component-protocol/components/issue-dashboard/filter/render.go
modules/dop/component-protocol/components/issue-gantt/gantt/render.go
modules/dop/component-protocol/components/issue-manage/issueFilter/model.go
modules/dop/component-protocol/components/issue-manage/issueFilter/render.go
modules/dop/dao/issue.go
modules/dop/services/issue/issue.go
modules/openapi/component-protocol/scenarios/home-page-content/components/title/render.go

feature
Add issue type bug in gantt chart
/assign @sfwn 

Add issue type bug in gantt chart, fix typo

---

modules/actionagent/agenttool/lock.go
modules/actionagent/agenttool/lock_test.go
modules/actionagent/define.go
modules/actionagent/step_prepare.go
modules/actionagent/step_store.go

/kind bugfix
concurrent tar cache file safe, lock cache path when tar file
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=222146&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)
| 🇺🇸 English |Fix the bug that concurrent tar cache file safe              |
| 🇨🇳 …

concurrent tar cache file safe

---

cmd/core-services/main.go
conf/core-services/core-services.yaml

/kind feature
feature: add pprof for core-services

feature: add pprof for core-services

---

modules/core/monitor/metric/query/es-tsql/influxql/functions.go
modules/core/monitor/metric/query/metricmeta/type_aggregations.go

/kind feature
/kind bugfix
/kind polish
/kind refactor
/kind document

Add rateps function for metric influxql

---

build/scripts/cluster-agent/shell-setup.sh
go.mod
go.sum
modules/cmp/steve/middleware/audit.go
modules/cmp/steve/middleware/dispatcher.go
modules/cmp/steve/middleware/dispatcher_test.go
modules/cmp/steve/websocket/decode.go
modules/cmp/steve/websocket/decode_test.go

Release1.3

---

modules/core/monitor/entity/persist/statistics.go
modules/core/monitor/event/persist/statistics.go
modules/core/monitor/event/persist/statistics_test.go
modules/core/monitor/log/persist/statistics.go
modules/core/monitor/log/persist/statistics_test.go
modules/core/monitor/metric/persist/statistics.go
modules/core/monitor/metric/persist/statistics_test.go
modules/core/monitor/storekit/consume.go
modules/core/monitor/storekit/statistics.go
modules/msp/apm/exception/erda-error/persist/statistics.go
modules/msp/apm/exception/erda-event/persist/statistics.go
modules/msp/apm/trace/persist/statistics.go

/kind feature
- add read&write latency metric
- simplify some metric's label
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=264615&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJSRU9QRU4iXSwic3RhdGVzIjpbNDQwMiw3MTA0LDcxMDUsNDQwMyw0NDA0LDcxMDYsNDQwNiw0NDA3LDQ0MTIsNDUzOCw0NDEzLDQ0MTQsNDQxNSw0NDE2XSwiYXNzaWduZWVJRHMiOlsiMTAwMDMwMSJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjIsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=-1&type=TASK)
Add comment …

latency metric&simplify labels

---

apistructs/addon.go
modules/orchestrator/services/addon/addon_sourcecov.go
modules/orchestrator/services/addon/addon_sourcecov_test.go
modules/orchestrator/services/addon/addon_status.go
modules/orchestrator/spec/legacy_dice.go
modules/orchestrator/utils/deployment_utils.go
modules/scheduler/executor/plugins/k8s/k8s.go
modules/scheduler/executor/plugins/k8s/k8s_test.go

/kind bugfix
orchestartor max cpu/mem bugfix
| 🇺🇸 English |  orchestartor max cpu/mem bugfix |
| 🇨🇳 中文    | orchestartor max cpu/mem bug 修复, 不是将 cpu赋值给 max_cpu, 而是 max_cpu -> max_cpu, max_mem -> max_mem   |

orchestartor max cpu/mem bugfix

---

modules/orchestrator/services/runtime/runtime.go
modules/orchestrator/services/runtime/runtime_test.go

/kind bugfix
fix bug redeploy that pipeline on JOB_CLUSTER

fix bug redeploy that pipeline on JOB_CLUSTER

---

modules/dop/component-protocol/components/issue-gantt/filter/model.go
modules/dop/component-protocol/components/issue-gantt/filter/render.go
modules/dop/component-protocol/components/issue-gantt/gantt/render.go

feature
Add multiple iterations filter back in issue gantt
/assign @sfwn 

Add multiple iterations filter back in issue gantt

---

modules/dop/component-protocol/components/requirement-task-overview/stackChartBlock/stackChart/render.go

/kind polish
fix: update the color of stackChart

fix: update the color of stackChart

---

modules/dop/component-protocol/components/requirement-task-overview/chartBlock/burnoutChart/render.go
modules/dop/component-protocol/components/requirement-task-overview/chartBlock/burnoutChartFilter/model.go
modules/dop/component-protocol/components/requirement-task-overview/chartBlock/burnoutChartFilter/render.go
modules/dop/component-protocol/components/requirement-task-overview/common/gshelper/helper.go
modules/dop/component-protocol/scenarios/requirement-task-overview.yml

/kind feature
single selection changed to multiple selection
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=264921&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=TASK)
Add comment like `/cherry-pick release/1.0` when this …

single selection changed to multiple selection

---

modules/dop/services/issue/issue.go

/kind bugfix
fix: fix the panic of issue update
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=265590&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG) …

fix: fix the panic of issue update

---

modules/dop/component-protocol/components/requirement-task-overview/stackChartBlock/stackChart/render.go

/kind polish
fix: update stackChart style

fix: update stackChart style

---

erda.yml

bugfix: temp remove monitor-agent-injector

---

modules/dop/dao/issue.go
modules/dop/initialize.go

/kind bugfix
fix: solve multi-instance problems and compatible with old data
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=265837&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNiw0NDA1LDQ0MTddLCJvd25lcklEcyI6WyIxMDAxMjYxIl19&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)
-  [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=265801&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT0 …

fix: solve multi-instance problems and compatible with old data

---

apistructs/event.go
apistructs/event_test.go
pkg/erda-configs/i18n/notify_item.yml

/kind bugfix
modify template and set ticket link
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=265844&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)
| 🇺🇸 English |  Fix the bug that modify template and set ticket link            |
| 🇨🇳 中文    | …

modify template and set ticket link

---

modules/openapi/component-protocol/components/base/provider.go

/kind feature
cp base provider auto register for new cp framework
/assign @Effet

cp base provider auto register for new cp framework

---

modules/core/monitor/entity/storage/elasticsearch/storage.go
modules/core/monitor/entity/storage/elasticsearch/writer_test.go

optimize: update entity in batch

---

modules/dop/component-protocol/components/issue-gantt/filter/model.go
modules/dop/component-protocol/components/issue-gantt/filter/render.go

/kind feature
feature: issue-gantt support fixed iteration id
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/task?id=266339&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDA2LDQ0MDddfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=680&type=TASK)
/assign @shuofan @Effet

feature: issue-gantt support fixed iteration id

---

modules/dop/component-protocol/components/requirement-task-overview/chartBlock/burnoutChart/render.go
modules/dop/component-protocol/components/requirement-task-overview/chartBlock/burnoutChartFilter/render.go
modules/dop/component-protocol/components/requirement-task-overview/chartBlock/render.go
modules/dop/component-protocol/components/requirement-task-overview/common/vars.go
modules/dop/component-protocol/components/requirement-task-overview/container/info/render.go
modules/dop/component-protocol/components/requirement-task-overview/container/render.go
modules/dop/component-protocol/components/requirement-task-overview/container/simpleChart/render.go
modules/dop/component-protocol/components/requirement-task-overview/distributePage/render.go
modules/dop/component-protocol/components/requirement-task-overview/distributePage/topFilter/render.go
modules/dop/component-protocol/components/requirement-task-overview/page/render.go
modules/dop/component-protocol/components/requirement-task-overview/pageContent/render.go
modules/dop/component-protocol/components/requirement-task-overview/stackChartBlock/render.go
modules/dop/component-protocol/components/requirement-task-overview/stackChartBlock/stackChart/render.go
modules/dop/component-protocol/components/requirement-task-overview/stackChartBlock/stackChartFilter/render.go
modules/dop/component-protocol/components/requirement-task-overview/tabs/render.go

/kind polish
fix: update stackChart order and polish the code

fix: update stackChart order and polish the code

---

conf/dop/dop.yaml
conf/openapi/openapi.yaml
go.mod
go.sum
modules/dop/component-protocol/components/all.go
modules/dop/component-protocol/components/issue-kanban/common/gshelper/helper.go
modules/dop/component-protocol/components/issue-kanban/content/provider.go
modules/dop/component-protocol/components/issue-kanban/inputFilter/render.go
modules/dop/component-protocol/components/issue-kanban/issueExport/render.go
modules/dop/component-protocol/components/issue-kanban/issueFilter/conditions.go
modules/dop/component-protocol/components/issue-kanban/issueFilter/filterset.go
modules/dop/component-protocol/components/issue-kanban/issueFilter/filterset_test.go
modules/dop/component-protocol/components/issue-kanban/issueFilter/in_params.go
modules/dop/component-protocol/components/issue-kanban/issueFilter/options.go
modules/dop/component-protocol/components/issue-kanban/issueFilter/provider.go
modules/dop/component-protocol/components/issue-kanban/issueImport/render.go
modules/dop/component-protocol/components/issue-kanban/issueKanbanV2/provider.go
modules/dop/component-protocol/components/issue-kanban/issueOperations/render.go
modules/dop/component-protocol/components/issue-kanban/page/render.go
modules/dop/component-protocol/components/issue-kanban/scenario.go
modules/dop/component-protocol/components/issue-kanban/toolbar/render.go
modules/dop/component-protocol/components/issue-manage/issueFilter/init_filter.go
modules/dop/component-protocol/components/issue-manage/reset/render.go
modules/dop/component-protocol/components/issue-manage/scenario.go
modules/dop/component-protocol/scenarios/issue-kanban.yml
modules/dop/component-protocol/scenarios/issue-manage.yml

/kind feature
/kind bugfix
/kind polish
/kind refactor
/kind document

issue kanban component set up

---

modules/dop/component-protocol/components/issue-kanban/common/gshelper/helper.go
modules/dop/component-protocol/components/issue-manage/common/gshelper/helper.go
modules/dop/component-protocol/scenarios/issue-manage.yml

/kind feature
/kind bugfix
/kind polish
/kind refactor
/kind document

Fix issue request global state get

---

modules/dop/component-protocol/components/issue-kanban/common/gshelper/helper.go
modules/dop/component-protocol/components/issue-kanban/issueFilter/conditions.go
modules/dop/component-protocol/components/issue-kanban/issueKanbanV2/provider.go

/kind feature
kanban card add iterationID for UI.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=266446&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyI5MiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=680&type=BUG)
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=266452&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyI5MiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6Z …

feature: kanban card extra add iterationID

---

modules/core/monitor/storekit/elasticsearch/index/cleaner/clean.go
modules/core/monitor/storekit/elasticsearch/index/cleaner/routes.go

/kind bugfix
bugfix: fix the bug that expired es indices not got deleted.

bugfix: fix the bug that expired es indices not got deleted.

---

.erda/migrations/.patches/patch-20210528-spot-dashboard-base.sql
.erda/migrations/monitor/20210528-spot-dashboard-base.sql

/kind feature
feature: patch-20210528-spot-dashboard-base.sql

feature: patch-20210528-spot-dashboard-base.sql

---

apistructs/issue.go
modules/dop/component-protocol/components/issue-kanban/issueFilter/provider.go
modules/dop/component-protocol/components/issue-kanban/issueKanbanV2/provider.go
modules/dop/component-protocol/components/issue-manage/issueTable/render.go

bugfix
Fix issue update, issue kanban order, issue table props
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=266054&issueFilter__urlQuery=eyJhc3NpZ25lZUlEcyI6WyIxMDAxMDczIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=680&type=TASK)
/assign @sfwn 

Fix issue update, issue kanban order, issue table props

---

go.mod
go.sum
modules/monitor/apm/common/common.go
modules/monitor/apm/topology/topology.go
modules/msp/apm/service/apm.service.service.go
modules/msp/apm/service/components/service-list/provider.go
modules/msp/apm/service/components/service-overview/provider.go
modules/msp/apm/service/view/chart/avg_duration.go
modules/msp/apm/service/view/chart/error_rate.go
modules/msp/apm/service/view/chart/rps.go
pkg/time/time.go
pkg/time/time_test.go

bugfix: Hotfix service list

---

modules/dop/component-protocol/components/issue-kanban/common/gshelper/helper.go
modules/dop/endpoints/issue.go

/kind feature
/kind bugfix
/kind polish
/kind refactor
/kind document

Update issue Kanban key

---

modules/gittar/auth/auth.go
modules/gittar/helper/git_cmd.go
modules/gittar/pkg/gitmodule/repo.go

/kind polish
modify the file name of the compressed package
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODEsNzcyLDY4MF0sIm1lbWJlciI6WyIxMDAxMjYxIl19&id=227609&iterationID=772&pId=0&type=REQUIREMENT)

modify the file name of the compressed package

---

bundle/filetree.go
modules/dop/services/filetree/filetree.go
modules/dop/services/pipeline/pipeline.go
modules/openapi/component-protocol/scenarios/app-pipeline-tree/components/fileTree/render.go
modules/openapi/component-protocol/scenarios/app-pipeline-tree/components/nodeFormModal/render.go

/kind feature
support store pipeline yml in .erda/pipelines
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls3NzJdLCJtZW1iZXIiOlsiMTAwMTIwNSJdfQ%3D%3D&id=252899&iterationID=772&pId=0&type=REQUIREMENT)
| 🇺🇸 English |  support store pipeline yml in .erda/pipelines            |
| 🇨🇳 中文    |  用.erda/pipelines目录存放pipeline，切兼容老的应用            | …

support store pipeline yml in .erda/pipelines

---

modules/orchestrator/services/addon/addon_deploy.go
modules/orchestrator/services/addon/addon_deploy_test.go
modules/orchestrator/services/addon/addon_status.go
modules/orchestrator/services/addon/middleware.go
modules/orchestrator/services/addon/middleware_test.go

/kind feature
support es later version
/assign @luobily @Effet @sixther-dc 
| 🇺🇸 English |   support es later version           |
| 🇨🇳 中文    |   支持 es 更高版本（base: 6.8.9）           |

feature: support es later version

---

.erda/migrations/cmdb/20211222-dice-member-character.sql

/kind bugfix
fix: modify the character set of the table `dice-member` to support emoji
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls3NzJdLCJtZW1iZXIiOlsiMTAwMTI2MSJdfQ%3D%3D&id=252163&iterationID=772&pId=0&type=BUG)
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIB …

fix: modify the character set of the table `dice-member` to support emoji

---

.erda/pipelines/ci-build-ce.yml

/kind polish
update ci pipeline.yml to embed extensions into dicehub image
/assign @sfwn 

update ci pipeline.yml to embed extensions into dicehub image

---

go.sum
modules/core-services/services/project/project.go
modules/core-services/services/project/project_test.go

/kind polish
check if an addon that is not a platform exists when the project is deleted
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODEsNzcyXSwibWVtYmVyIjpbIjEwMDEyNjEiXX0%3D&id=209165&iterationID=772&pId=0&type=BUG)
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CON …

check if an addon that is not a platform exists when the project is deleted

---

modules/msp/menu/menu.service.go

/kind feature
feature: enable alert-center menu for msp project

feature: enable alert-center menu for msp project

---

go.sum
modules/msp/apm/service/components/service-list/grid/provider.go
modules/msp/apm/service/components/service-list/page/provider.go
modules/msp/apm/service/components/service-list/scenario.go
modules/msp/apm/service/components/service-overview/grid/provider.go
modules/msp/apm/service/components/service-overview/page/provider.go
modules/msp/apm/service/components/service-overview/scenario.go

bugfix: fix service files missing

---

modules/actionagent/callback.go
modules/actionagent/step_logic.go

/kind bugfix
action-agent: force add newline for tail done to fix tail pending forever
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls3NzIsNjgwXSwibWVtYmVyIjpbIjkyIl19&id=268081&iterationID=772&pId=0&type=TASK)
/assign @Effet

fix: agent tail done flag add force-new-line

---

modules/hepa/services/legacy_consumer/impl/impl.go

/kind bugfix
fix: do not create credential when creating defautl consumer

fix: do not create credential when creating defautl consumer

---

go.sum
modules/msp/apm/service/components/service-list/grid/provider.go
modules/msp/apm/service/components/service-list/page/provider.go
modules/msp/apm/service/components/service-list/scenario.go
modules/msp/apm/service/components/service-overview/grid/provider.go
modules/msp/apm/service/components/service-overview/page/provider.go
modules/msp/apm/service/components/service-overview/scenario.go

Cherry pick of: bugfix: fix service files missing #3454

---

build/scripts/base_image.sh
build/scripts/docker_image.sh

/kind feature
feature: build support specific DOCKER_PLATFORM, default is linux/amd64
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=268153&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=TASK)
/assign @Effet

feature: build support specific DOCKER_PLATFORM, default is linux/amd64

---

modules/core/monitor/log/query/log.query.service.go
modules/core/monitor/log/query/log.query.service_test.go
modules/core/monitor/storekit/iterator.go
modules/core/monitor/storekit/iterator_test.go

/kind feature
- optimize the query speed when first open the container log panel
- balance between the query speed and max query history timespan

feature: add slicedIterator for log query

---

erda.yml
modules/core/monitor/log/query/log.query.service.go

/kind feature
- change streaming default max memory limit to 2Gi
- optimize log query code

feature: increase streaming max memory

---

modules/orchestrator/services/addon/addon_handler.go
modules/orchestrator/services/addon/addon_status.go
modules/orchestrator/services/deployment/deployment_context.go
modules/orchestrator/services/deployment/deployment_context_test.go
modules/orchestrator/services/log/log.go

feature: deploy log add dice_org_name tag

---

modules/dop/dao/issue.go
modules/dop/dao/issue_test.go
modules/dop/services/issue/issue.go
modules/dop/services/issue/issue_test.go
modules/dop/services/issuerelated/issue_related.go

bugfix
After issue inclusion relation change, update parent issue plan
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=268052&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMDczIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=680&type=BUG)
/assign @sfwn  …

After issue inclusion relation change, update parent issue plan

---

modules/orchestrator/services/addon/addon_handler.go
modules/orchestrator/services/addon/addon_handler_test.go

/kind polish
the production environment does not allow the deployment of basic addon
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODEsNzcyXSwibWVtYmVyIjpbIjEwMDEyNjEiXX0%3D&id=235101&iterationID=772&pId=0&type=REQUIREMENT)

the production environment does not allow the deployment of basic addon

---

pipeline.yml

/kind polish
add ce build script
/assign @sfwn 

add ce build script

---

modules/orchestrator/services/runtime/runtime.go

/kind bugfix
hotfix: orchestrator show runtime without last deployment
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=206096&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyI5MiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjMsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG)
/assign @Effet

hotfix: orchestrator show runtime without last deployment

---

.erda/migrations/cmdb/20211221-dice-member-userID-varchar.sql

/kind polish
fix: modify the length of the user_id in the dice_member table

fix: modify the length of the user_id in the dice_member table

---

modules/admin/component-protocol/components/workbench/projAppList/provider.go
modules/admin/provider.go

/kind bugfix
admin component protocol bugfix
| 🇺🇸 English |  admin component protocol  init bugfix |
| 🇨🇳 中文    |   admin bufix, 回滚组件化协议 init   |

admin bugfix

---

bundle/app.go
bundle/msp.go
bundle/workbench.go

/kind bugfix
bundle bugfix
| 🇺🇸 English |  bundle bugfix, slice init size should be zero|
| 🇨🇳 中文    |  bundle bugfix, slice 初始化 size 应该为 0  |

bundle bugfix

---

apistructs/pipeline.go
go.sum
modules/actionagent/file_watch_collector.go
modules/actionagent/step_validate.go
modules/dop/services/autotest_v2/scene.go
modules/dop/services/autotest_v2/sceneset.go
modules/dop/services/autotest_v2/testplan_v2.go
modules/pipeline/pipengine/actionexecutor/plugins/apitest/logic/log_collector.go
modules/pipeline/pipengine/actionexecutor/plugins/apitest/logic/main.go
modules/pipeline/pipengine/reconciler/taskrun/taskop/prepare.go
modules/pipeline/spec/pipeline_extra.go

/kind polish
add org tags to action agent log
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls3NzJdLCJtZW1iZXIiOlsiMTAwMTI2MSJdfQ%3D%3D&id=267283&iterationID=772&pId=0&type=REQUIREMENT)
/assign @sfwn 

add org tags to pipeline&actionAgent log

---

modules/orchestrator/services/addon/addon_handler.go
modules/orchestrator/services/deployment/deployment_context.go
modules/orchestrator/services/log/log.go
modules/pkg/monitor/log.go
modules/pkg/monitor/tagkey.go

feature: define common tags for reference from other modules

---

modules/core/monitor/metric/query/es-tsql/influxql/functions.go

feature: support not_include function

---

modules/msp/apm/service/apm.service.service.go
modules/msp/apm/service/apm.service.service_test.go

bugfix: service list complex query

---

apistructs/pipeline.go
apistructs/service.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sjob/k8sjob.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sjob/k8sjob_test.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/logic/job.go
pkg/k8s/elastic/vk/detect_label.go
pkg/k8s/elastic/vk/detect_label_test.go

/kind feature
pipeline support csi and eci
| 🇺🇸 English | pipeline support csi and eci             |
| 🇨🇳 中文    |    pipeline 支持 csi 以及 aliyun eci          |

feature: pipeline support csi and eci

---

modules/msp/apm/service/apm.service.service.go
modules/msp/apm/service/apm.service.service_test.go

bugfix: fix has error service list

---

apistructs/issue.go
modules/dop/services/issue/issue.go
modules/dop/services/issue/issue_test.go

bugfix
Fix issue update plan time validation
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=269090&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG)
/assign @sfwn 
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/maste …

Fix issue update plan time validation

---

modules/orchestrator/dbclient/addon_instance.go
modules/orchestrator/endpoints/endpoints.go
modules/orchestrator/initialize.go
modules/orchestrator/initialize_test.go

/kind polish
clean up the remaining addon
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls3NzJdLCJtZW1iZXIiOlsiMTAwMTI2MSJdfQ%3D%3D&id=243768&iterationID=772&pId=0&type=BUG)

clean up the remaining addon

---

go.mod
go.sum

/kind polish
upgrade infra version for cp
related infra pr: https://github.com/erda-project/erda-infra/pull/164
/assign @Effet

upgrade infra version for cp

---

modules/dop/component-protocol/components/auto-test-scenes/common/gshelper/helper.go
modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileExecute/executeAlertInfo/render.go
modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileExecute/executeHead/cancelExecuteButton/render.go
modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileExecute/executeHead/refreshButton/render.go
modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileExecute/executeInfo/render.go
modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileExecute/executeTaskBreadcrumb/render.go
modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileExecute/executeTaskTable/render.go
modules/openapi/component-protocol/pkg/gshelper/helper.go
modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeAlertInfo/render.go
modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeInfo/render.go
modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeTaskBreadcrumb/render.go
modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/refreshButton/render.go

/kind feature
Repeated interface calls slow down
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODEsNzcyXSwibWVtYmVyIjpbIjEwMDA1NjAiXX0%3D&id=258180&iterationID=772&pId=0&type=BUG)
| 🇺🇸 English |       Repeated interface calls slow down       |
| 🇨🇳 中文    |       接口重复调用导致速度变慢       |

Automated test repeat interface calls slow down

---

apistructs/publish_item.go
apistructs/publish_item_test.go
bundle/cluster.go
bundle/clusterinfo.go
bundle/lib-reference.go
bundle/publish_item.go
modules/cmp/component-protocol/components/cmp-dashboard-events-list/filter/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/filter/render.go
modules/cmp/endpoints/cloud_resource_gateway.go
modules/cmp/impl/addons/config.go
modules/cmp/impl/aliyun-resources/clusterinfo.go
modules/cmp/tasks/collect_daily_quota.go
modules/dicehub/endpoints/publish_item.go
modules/dicehub/initialize.go
modules/dicehub/registry/manifests.go
modules/dicehub/service/publish_item/item.go
modules/dop/endpoints/endpoints.go
modules/dop/endpoints/publisher.go
modules/dop/services/apierrors/errors.go
modules/dop/services/project/get.go
modules/openapi/api/apis/dop/publish_item_query_my.go

/kind refactor
relieve dicehub's dependence on dop and scheduler

feature: Relieve dicehub's dependence on dop

---

modules/orchestrator/services/addon/addon.go
modules/orchestrator/services/addon/addon_handler.go

/kind refactor
optimize addon request error
/assign @sfwn 

refactor: optimize addon request error

---

apistructs/issue.go
apistructs/issue_test.go
modules/dop/component-protocol/components/issue-gantt/gantt/render.go
modules/dop/dao/issue.go
modules/dop/services/issue/issue.go
modules/dop/services/issue/issue_test.go

bugfix 
Fix issue update request time and daily update sql
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=269090&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=0&type=BUG)
/assign @sfwn 
Add comment like `/cherry-pick release/1.5` when this PR is merged.

Fix issue update request time and daily update sql

---

conf/monitor/monitor/alert/trigger_conditions.yaml

/kind bugfix
| 🇺🇸 English |       modify msp filter condition       |
| 🇨🇳 中文    |        修改微服务平台获取服务名和应用名的过滤条件      ｜

modify msp filter condition

---

apistructs/issue.go

bugfix
Fix issue time marshal
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=269998&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=680&type=BUG)
/assign @sfwn 
Add comment like `/cherry-pick release/1.5` when this PR is merged. …

Fix issue time marshal

---

modules/orchestrator/dbclient/addon_instance.go

/kind bugfix
the count of addon filter deleted
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODEsNzcyXSwibWVtYmVyIjpbIjEwMDEyNjEiXX0%3D&id=200885&iterationID=772&pId=0&type=BUG)
/assign #Effet

the count of addon filter deleted

---

modules/dop/dao/sceneset.go

/kind bugfix
The automated test scenario set uses the pre_id link to form a linked list. If there is the same pre_id scenario set，only part of it can be displayed
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls3NzJdLCJtZW1iZXIiOlsiMTAwMDU2MCJdfQ%3D%3D&id=269345&iterationID=772&pId=0&type=BUG)
| 🇺🇸 English |      Automated test scenario set mobile verification whether the same pre_id exists        |
| 🇨🇳 中文    |        自动化测试场景集移动校验是否存在相同的pre_id      |

Check whether the same pre exists when the automatic test scenario set  pre_id

---

modules/orchestrator/dbclient/addon_instance.go
modules/orchestrator/endpoints/middleware.go
modules/orchestrator/services/addon/middleware.go

/kind polish
Addon statistical performance optimization
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODEsNzcyXSwibWVtYmVyIjpbIjEwMDEyNjEiXX0%3D&id=252779&iterationID=772&pId=0&type=BUG)

Addon statistical performance optimization

---

modules/core-services/dao/application.go
modules/core-services/endpoints/application.go
modules/core-services/endpoints/application_test.go
modules/core-services/model/application.go

/kind feature
batch query app runtime counts
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls3NzIsNjgwLDg4MSw4ODNdLCJtZW1iZXIiOlsiMTAwMTIwNSJdfQ%3D%3D&id=269979&iterationID=772&pId=0&type=TASK)
| 🇺🇸 English |  Optimize of query app runtime count            |
| 🇨🇳 中文    |优化我的应用查询runtime数量              | …

batch query app runtime counts

---

modules/core/monitor/log/query/log.query.service.go
modules/core/monitor/log/storage/cassandra/iterator.go
modules/core/monitor/log/storage/elasticsearch/iterator.go
modules/core/monitor/log/storage/kubernetes-logs/storage.go
modules/core/monitor/log/storage/storage.go

feature: adjust container log search as keyword style search

---

conf/monitor/log-service/log-service.yaml
conf/monitor/monitor/monitor.yaml
conf/monitor/streaming/streaming.yaml
conf/msp/msp.yaml

/kind feature
feature: enable es as storage for log,span,entity,event
/cherry-pick release/1.5

feature: enable es as storage for log,span,entity,event

---

.erda/migrations/core-services/20211220-erda_subscribe_management.sql
apistructs/subscribe.go
bundle/subscribe.go
modules/core-services/dao/subscribe.go
modules/core-services/endpoints/subscribe.go
modules/core-services/model/subscribe.go
modules/core-services/services/subscribe/subscribe.go
modules/core-services/services/subscribe/subscribe_test.go

/kind bugfix
subscribe bugfix
| 🇺🇸 English |  subscribe bugfix, create subscribe with org_id  |
| 🇨🇳 中文    | subscribe bugfix, 订阅企业隔离|

subscribe bugfix support enterprise isolation

---

modules/admin/component-protocol/components/personal-workbench/messageList/messageList.go

/kind feature
message list bugfix: columns info & click operation
| 🇺🇸 English |  message list bugfix: columns info & click operation |
| 🇨🇳 中文    |  未读消息，列信息 与 点击操作 bugfix |

message list bugfix: columns info & click operation

---

erda.yml

feature: enable monitor-agent-injector

---

.gitignore

/kind polish
.gitignore: add .history dir for local history
/assign @Effet @shuofan

.gitignore: add .history dir for local history

---

.erda/migrations/dicehub/20211220-decehub.sql
modules/dop/component-protocol/components/release-manage/releaseTable/render.go

/kind bugfix
delete default value for all text fields in table dice_release

fix dbmigration

---

.github/semantic.yml

/kind feature
enable semantic pr
/assign @sfwn 

chore: create semantic.yml and enable semantic pr

---

bundle/project.go
modules/admin/services/workbench/project.go
modules/core-services/endpoints/project.go
modules/core-services/endpoints/project_test.go

/kind bugfix
list project keep msp
| 🇺🇸 English | list project keep msp, default ingore  |
| 🇨🇳 中文    | 获取项目列表时，保留 msp 项目，默认不保留 |

fix: list project keep msp

---

modules/dop/endpoints/issue.go
modules/dop/services/issuestream/issue_stream.go
modules/dop/services/issuestream/issue_stream_template.go
modules/dop/services/issuestream/issue_stream_template_test.go

/kind bugfix
issue stream support i18n
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODEsNzcyXSwibWVtYmVyIjpbIjEwMDEyNjEiXX0%3D&id=234419&iterationID=772&pId=0&type=BUG)
| 🇺🇸 English |       issue stream support i18n        |
| 🇨🇳 中文    |     issue活动日志支持国际化         | …

feat: issue stream support i18n

---

conf/monitor/agent-injector/agent-injector.yaml
erda.yml

fix: update monitor-injector config

---

modules/dop/component-protocol/components/requirement-task-overview/stackChartBlock/stackChart/render.go

fix: numerical problem adjustments to the stack chart
| 🇺🇸 English |      numerical problem adjustments to the stack chart       |
| 🇨🇳 中文    |       累积流图数值问题调整       |

fix: numerical problem adjustments to the stack chart

---

build/scripts/monitor-agent-injector/deployment/generate-keys.sh
build/scripts/monitor-agent-injector/deployment/webhook-deploy.sh
build/scripts/monitor-agent-injector/deployment/webhook.yaml.template

fix: Update webhook deploy script

---

pipeline.yml

| 🇺🇸 English |    add monitor-agent-injector build          |
| 🇨🇳 中文    |         添加  monitor-agent-injector 构建   |

fix: add monitor-agent-injector build

---

bundle/audit.go
conf/core-services/i18n/i18n.yaml
modules/admin/manager/audit.go
modules/core-services/endpoints/audit.go
modules/core-services/initialize.go
modules/core-services/provider.go
modules/core-services/services/audit/audit.go
pkg/http/httputil/header.go

/kind bugfix
fix: update the export of audit & i18n support
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODEsNzcyXSwibWVtYmVyIjpbIjEwMDEyNjEiXX0%3D&id=229469&iterationID=772&pId=0&type=BUG)
| 🇺🇸 English |      update the export of audit and i18n support      |
| 🇨🇳 中文    |       审计日志导出问题修复，国际化支持         | …

fix: update the export of audit & i18n support

---

erda.yml

| 🇺🇸 English |         fix: update cert dirs     |
| 🇨🇳 中文    |          修改 injector cert 目录挂载    |

fix: update cert dirs

---

apistructs/project.go
conf/admin/i18n/cp/scenarios/personal-workbench.yaml
modules/admin/component-protocol/components/personal-workbench/i18n/i18n.go
modules/admin/component-protocol/components/personal-workbench/workCards/provider.go
modules/admin/component-protocol/components/personal-workbench/workList/app.go
modules/admin/component-protocol/components/personal-workbench/workList/app_test.go
modules/admin/component-protocol/components/personal-workbench/workList/provider.go
modules/core/openapi-ng/auth/ory-kratos/user.go
modules/core/openapi-ng/auth/uc-session/user.go
modules/openapi/auth/user.go
pkg/ucauth/user.go

1. add limit of collect count
2. remove api design link of app
3. add i18n for tag of app
| 🇺🇸 English |      fix some bugs in admin module        |
| 🇨🇳 中文    |       修复了一些admin 模块的bug       |

fix(cp): fix some admin bugs

---

modules/dop/component-protocol/components/issue-kanban/issueExport/render.go
modules/dop/component-protocol/components/issue-kanban/issueImport/render.go
modules/dop/component-protocol/components/issue-manage/issueExport/render.go
modules/dop/component-protocol/components/issue-manage/issueImport/render.go
modules/dop/component-protocol/scenarios/issue-kanban.yml
modules/dop/component-protocol/scenarios/issue-manage.yml

| 🇺🇸 English |      import and export button style       |
| 🇨🇳 中文    |      导入导出按钮        |

style: Change issue operation import export type

---

apistructs/release.go
modules/dicehub/endpoints/endpoints.go
modules/dicehub/endpoints/release.go
modules/dicehub/service/apierrors/errors.go
modules/dicehub/service/release/release.go
modules/dop/component-protocol/components/release-manage/inputFilter/render.go
modules/dop/component-protocol/components/release-manage/releaseFilter/model.go
modules/dop/component-protocol/components/release-manage/releaseFilter/render.go
modules/dop/component-protocol/components/release-manage/releaseFilter/render_test.go
modules/openapi/api/apis/dicehub/dicehub_releases_check_version.go

add check version to check whether verison is unique

feat: add check version

---

conf/dop/i18n/cp/scenarios/release-manage.yaml
modules/dicehub/service/release/release.go
modules/dop/component-protocol/components/release-manage/releaseTable/model.go
modules/dop/component-protocol/components/release-manage/releaseTable/render.go

1. do i18n for error info in release-manage
2. pre check access for project release
| 🇺🇸 English | 1.do i18n for error info in release-manage; 2. pre check access for project release |
| 🇨🇳 中文    | 1. 对release-manage的错误信息做国际化 2. 对项目级制品提前鉴权，无权限时把按钮置灰 |

fix: do i18n for error info and pre check access

---

apistructs/issue_stream_locale.go

fix: add English i18n key of issue stream
| 🇺🇸 English |     add English i18n key of issue stream         |
| 🇨🇳 中文    |       补充英文国际化       |

fix: add English i18n key of issue stream

---

modules/admin/component-protocol/components/personal-workbench/messageTabs/messageTabs.go
modules/admin/component-protocol/components/personal-workbench/workList/provider.go
modules/admin/component-protocol/scenarios/personal-workbench.yml

| 🇺🇸 English |  message list bugfix |
| 🇨🇳 中文    |未读消息数量 bugfix |

fix: message list bugfix

---

modules/admin/component-protocol/components/personal-workbench/workCards/provider.go

fix i18n for msp icon
| 🇺🇸 English |             add i18n for msp project |
| 🇨🇳 中文    |         增加msp项目的翻译     |

fix: i18n for msp icon

---

modules/admin/component-protocol/components/personal-workbench/workList/provider.go

replace name with displayName for project list
| 🇺🇸 English |   replace name with displayName for project list |
| 🇨🇳 中文    |        使用项目的displayName       |

fix(admin cp): add porject display name

---

modules/admin/component-protocol/components/personal-workbench/workList/project.go

| 🇺🇸 English |         fix icon consistent with card and list      |
| 🇨🇳 中文    |            修复了card 和 list 中icon的不一致 |

fix(admin): fix icon consistent with card and list

---

modules/admin/component-protocol/components/personal-workbench/messageTabs/messageTabs.go

| 🇺🇸 English | remove message number |
| 🇨🇳 中文    | 删除未读消息数 |

fix: remove message number

---

modules/dop/component-protocol/components/release-manage/releaseFilter/render.go

change user name to nick name in release filter
| 🇺🇸 English | change user name to nick name in release filter |
| 🇨🇳 中文    | 将制品管理页面中按用户名筛选改为按照用户昵称筛选 |

fix: change user name to nick name

---

bundle/subscribe.go
modules/admin/component-protocol/components/personal-workbench/common/gshelper/helper.go
modules/admin/component-protocol/components/personal-workbench/workCards/provider.go
modules/admin/component-protocol/components/personal-workbench/workCards/provider_test.go
modules/admin/component-protocol/components/personal-workbench/workList/app.go
modules/admin/component-protocol/components/personal-workbench/workList/project.go
modules/admin/component-protocol/components/personal-workbench/workList/provider.go
modules/admin/component-protocol/components/personal-workbench/workTabs/workTabs.go
modules/admin/component-protocol/scenarios/personal-workbench.yml
modules/admin/services/workbench/issue.go
modules/admin/services/workbench/project.go

| 🇺🇸 English |            workbench optimize performance  |
| 🇨🇳 中文    |   个人工作台性能优化    |

fix: workbench optimize performance

---

apistructs/extention.go
modules/dicehub/dbclient/extention.go
modules/dicehub/endpoints/extention.go
modules/dicehub/service/extension/extension.go
modules/orchestrator/services/addon/addon.go
modules/pipeline/services/pipelinesvc/detail.go
modules/pipeline/services/pipelinesvc/graph.go
pkg/erda-configs/i18n/orchestrator.json

The action and addon lists support internationalization
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls3NzJdLCJtZW1iZXIiOlsiMTAwMDU2MCJdfQ%3D%3D&id=206505&iterationID=772&pId=0&type=BUG)
| 🇺🇸 English |      The action and addon lists support internationalization        |
| 🇨🇳 中文    |        action 和 addon 列表支持国际化      |

fix: dicehub extension internationalization

---

apistructs/audits.go
modules/dicehub/endpoints/audit.go
modules/dicehub/endpoints/release.go
modules/dicehub/service/release/release.go
modules/dop/component-protocol/components/release-manage/inputFilter/render.go
modules/dop/component-protocol/components/release-manage/releaseFilter/render.go
modules/dop/component-protocol/components/release-manage/releaseTable/render.go

add audit for release-manage
| 🇺🇸 English | add audit for release-manage |
| 🇨🇳 中文    | 制品管理支持审计日志 |

feat: add audit for release-manage

---

pkg/erda-configs/permission/front/org/project/project.yml

add project release create permission
| 🇺🇸 English | Added project - level artifact creation permission control. |
| 🇨🇳 中文    | 增加了项目级制品的创建权限控制。  |

feat: add project release create permission

---

apistructs/release.go
apistructs/release_test.go

hotfix: parser release yaml error
| 🇺🇸 English | hotfix: parser release yaml error |
| 🇨🇳 中文    | 修复解析 release yml 文件错误的问题 |

fix: parser release yaml error

---

modules/admin/component-protocol/components/personal-workbench/workCards/provider.go
modules/admin/component-protocol/components/personal-workbench/workCards/provider_test.go

| 🇺🇸 English |    async render cardlist          |
| 🇨🇳 中文    |           异步渲染cardlist   |

refactor(admin cp): add async render

---

bundle/msp.go
bundle/subscribe.go
modules/admin/component-protocol/components/personal-workbench/messageList/messagelist_test.go
modules/admin/component-protocol/components/personal-workbench/messageTabs/messageTabs.go
modules/admin/component-protocol/components/personal-workbench/workList/provider.go
modules/admin/services/workbench/project.go
modules/admin/services/workbench/project_test.go
modules/admin/services/workbench/workbench_test.go

| 🇺🇸 English | worklist start bugfix update star status in place |
| 🇨🇳 中文    | 原地更新 star 状态, 修复未读消息数量 |

fix: worklist start and message size bugfix

---

conf/dop/i18n/cp/scenarios/release-manage.yaml
modules/dop/component-protocol/components/release-manage/releaseTable/render.go

fix: change version to release name
| 🇺🇸 English | fix: change version to release name|
| 🇨🇳 中文    | 将release-manage表格中的”版本名称“改为”制品名称“ |

fix: change version to release name

---

modules/core-services/dao/application.go
modules/core-services/model/project.go
modules/core-services/services/project/project.go
modules/core-services/services/project/project_test.go

opmitization of interface-list-project, batch query unblock app num
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls3NzIsNjgwLDg4MSw4ODNdLCJtZW1iZXIiOlsiMTAwMTIwNSJdfQ%3D%3D&id=269979&iterationID=772&pId=0&type=TASK)
| 🇺🇸 English | Optimize batch query project's unblock app             |
| 🇨🇳 中文    |    优化了项目查询速度          | …

perf: batch query project's unblock app

---

apistructs/extention.go

The action and addon lists support internationalization
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls3NzJdLCJtZW1iZXIiOlsiMTAwMDU2MCJdfQ%3D%3D&id=206505&iterationID=772&pId=0&type=BUG)
| 🇺🇸 English |      The action and addon lists support internationalization        |
| 🇨🇳 中文    |        action 和 addon 列表支持国际化      |

fix: dicehub extension internationalization change

---

modules/admin/component-protocol/components/personal-workbench/common/common.go
modules/admin/component-protocol/components/personal-workbench/workCards/provider.go
modules/admin/component-protocol/components/personal-workbench/workList/project.go
modules/admin/component-protocol/components/personal-workbench/workList/project_test.go
modules/admin/component-protocol/components/personal-workbench/workList/provider.go
modules/admin/services/workbench/issue.go
modules/admin/services/workbench/issue_test.go

| 🇺🇸 English | workbench issue filter bugfix |
| 🇨🇳 中文    | 个人工作台 issue 过滤 bugfix, 处理人指定本人 |

fix: workbench issue filter bugfix

---

modules/dop/component-protocol/components/release-manage/releaseTable/model.go
modules/dop/component-protocol/components/release-manage/releaseTable/render.go

1. add ignore data
2. add debug logs
| 🇺🇸 English | add ignore data; add debug logs |
| 🇨🇳 中文    | 忽略data字段回传；添加调试日志 |
need cherry-pick to feature/project-release-audit

fix: add ignore data and debug logs

---

modules/dop/dao/issue_property_relation.go
modules/dop/services/issue/convert.go

Skip invalid property relations with empty property id
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/ticket?assignee[]=1001073&id=270646&pageNo=1)
| 🇺🇸 English |    Fix issue import with property          |
| 🇨🇳 中文    |   修复了包含自定义字段的事项导入           |

fix: Fix issue import with property,  skip invalid property relations with empty property id

---

modules/dop/dao/contribution.go
modules/dop/providers/contribution/service.go

Member active rank limit and coefficient update
- [Erda Cloud Link 1](https://erda.cloud/erda/dop/projects/387/issues/all?id=271319&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMDczIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=TASK)
- [Erda Cloud Link 2](https://erda.cloud/erda/dop/projects/387/issues/all?id=271293&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMDczIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG)
| 🇺🇸 …

feat: Member active rank limit and coefficient update

---

.erda/migrations/cmdb/20211227-project-soft-delete.sql
.erda/migrations/config.yml
modules/core-services/dao/project.go
modules/core-services/model/project.go

/kind feature
project support soft delete
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODEsNzcyXSwibWVtYmVyIjpbIjEwMDEyNjEiXX0%3D&id=267061&iterationID=772&pId=0&type=TASK)
| 🇺🇸 English |     project support soft delete         |
| 🇨🇳 中文    |      项目支持软删除         |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.m …

feat: project support soft delete

---

modules/admin/component-protocol/components/personal-workbench/workCards/provider.go
modules/admin/component-protocol/components/personal-workbench/workCards/provider_test.go
modules/admin/component-protocol/components/personal-workbench/workList/provider.go
modules/dop/component-protocol/scenarios/project-runtime.yml

| 🇺🇸 English |       fix msp url       |
| 🇨🇳 中文    |           修复了msp url   |

fix(admin cp): fix msp url

---

modules/cmp/component-protocol/components/cmp-cluster-list/list/render.go

| 🇺🇸 English |        show name if display name is empty      |
| 🇨🇳 中文    |         如果displayname 为空则展示name     |

fix(cluster): show name if display name is empty

---

apistructs/service.go
modules/pipeline/pipengine/reconciler/taskrun/taskop/prepare.go
pkg/schedule/schedulepolicy/constraintbuilders/k8s/build.go
pkg/schedule/schedulepolicy/labelconfig/labelconfig.go
pkg/schedule/schedulepolicy/labelpipeline/identity.go
pkg/schedule/schedulepolicy/labelpipeline/identity_test.go

support bigdata source pipeline custom affinity
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=269801&issueFilter__urlQuery=eyJ0aXRsZSI6IuOAkOa7muWKqOmcgOaxguOAkSBwaXBlbGluZeWumuaXtuS7u%2BWKoeWinuWKoOWPguaVsO%2B8jHBpcGVsaW5l5rWB5rC057q%2F6IO95aSf6Ieq5a6a5LmJbm9kZSBsYWJlbO%2B8jOWwhuS7u%2BWKoei%2FkOihjOWcqOaMh%2BWumuagh%2BetvueahOacuuWZqOS4iyIsInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=883&type=REQUIREMENT)
| 🇺🇸 English |   support bigdata source pipeline custom affinity           |
| 🇨🇳 中文    | …

feat: pipeline support bigdata affinity label

---

apistructs/release.go
modules/dicehub/dbclient/release.go
modules/dicehub/endpoints/release.go
modules/dicehub/service/release/release.go
modules/dop/component-protocol/components/release-manage/releaseTable/render.go

1. fix: the newly created application cannot be listed immediately
2. modify parse-version
| 🇺🇸 English | 1. fix: the newly created application cannot be listed immediately 2. modify parse-version |
| 🇨🇳 中文    | 1.修复页面上创建release后偶现list不到的问题 2. 修改上传文件解析版本接口 |
Need cherry-pick to release/1.6-alpha.1

fix: the newly created application cannot be listed immediately

---

apistructs/release.go
modules/dicehub/service/release/release.go
modules/dop/component-protocol/components/release-manage/releaseFilter/render.go

polish: remove parsing image in list release
| 🇺🇸 English | polish: remove parsing image in list release |
| 🇨🇳 中文    | 在list制品接口中删除解析镜像的逻辑，优化接口响应时间 |
Need cherry-pick to release/1.6-alpha.1

fix: remove parsing image in list release

---

modules/dop/endpoints/issue_callback.go
modules/dop/endpoints/issue_callback_test.go

add issue email link to dingding group params
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=272194&issueFilter__urlQuery=eyJ0aXRsZSI6IuS9v%2BeUqOmSiemSiemAmuefpee7hOWPkeWHuueahOa2iOaBr%2BS4rSIsInN0YXRlcyI6WzQ0MTIsNDUzOCw0NDEzLDQ0MTQsNDQxNSw0NDE2XX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG)
| 🇺🇸 English |  Fix the bug that dingding group link            |
| 🇨🇳 中文    |     修复了钉钉群通知链接         |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to …

fix: add issue email link to dingding group params

---

apistructs/extention.go
modules/dicehub/dbclient/extention.go
modules/dicehub/endpoints/extention.go
modules/dicehub/service/extension/extension.go
modules/dop/services/issue/issue_test.go
modules/orchestrator/services/addon/addon.go
modules/pipeline/services/pipelinesvc/detail.go
modules/pipeline/services/pipelinesvc/graph.go
pkg/erda-configs/i18n/orchestrator.json

Cherry pick of #3572 #3589 on release/1.5.
Squashed commit message:
commit a41fff2bbfb057963c05bb3702f15da066e1385c
Author: kakj <18579115540@163.com>
Date:   Fri Dec 31 11:09:29 2021 +0800
dicehub extension internationalization (#3572)
dicehub extension internationalization change (#3589)

feat: cherry pick 3572 3589

---

modules/msp/apm/service/view/card/avg_duration.go
modules/msp/apm/service/view/card/error_count.go
modules/msp/apm/service/view/card/error_rate.go
modules/msp/apm/service/view/card/req_count.go
modules/msp/apm/service/view/card/rps.go
modules/msp/apm/service/view/card/slow_count.go
modules/msp/apm/service/view/chart/avg_duration.go
modules/msp/apm/service/view/chart/error_count.go
modules/msp/apm/service/view/chart/error_rate.go
modules/msp/apm/service/view/chart/http_code.go
modules/msp/apm/service/view/chart/rps.go
modules/msp/apm/service/view/chart/slow_count.go
modules/msp/apm/service/view/common/sqlutils.go
modules/msp/apm/service/view/table/transaction.go

bugfix: fix cache、mq、db chart no data
/assign @liuhaoyang @innerpeacez 
| 🇺🇸 English |      bugfix: fix cache、mq、db chart no data        |
| 🇨🇳 中文    |      修复了服务监控中缓存、数据库、消息队列图表无数据的问题        |
/cherry-pick release/1.6

fix: Fix cache、mq、db chart no data

---

bundle/app.go
conf/dop/dop.yaml
conf/dop/i18n/cp/scenarios/app-list-all.yaml
conf/openapi/openapi.yaml
modules/dop/component-protocol/components/all.go
modules/dop/component-protocol/components/app-list-all/common/gshelper/helper.go
modules/dop/component-protocol/components/app-list-all/filter/render.go
modules/dop/component-protocol/components/app-list-all/list/app.go
modules/dop/component-protocol/components/app-list-all/list/provider.go
modules/dop/component-protocol/components/app-list-all/scenario.go
modules/dop/component-protocol/components/app-list-all/tabs/render.go
modules/dop/component-protocol/scenarios/app-list-all.yml

App list component protocol set up
/assign @sfwn 
| 🇺🇸 English |   app list component protocol set up         |
| 🇨🇳 中文    |  应用列表 使用list标准组件           |

feat: App list component protocol set up

---

go.mod
go.sum
modules/admin/component-protocol/components/personal-workbench/common/gshelper/helper.go
modules/admin/component-protocol/components/personal-workbench/common/gshelper/helper_test.go
modules/admin/component-protocol/scenarios/personal-workbench.yml

| 🇺🇸 English | workbench parallel rending enable |
| 🇨🇳 中文    | 个人工作台后端开启并发渲染 |

feat: workbench parallel enable

---

pipeline.yml

refine ee package
/assign @sfwn 
| 🇺🇸 English |     refine ee package         |
| 🇨🇳 中文    |        优化企业/社区镜像打包      |

ci: refine ee package

---

modules/gittar/api/merge.go

fix: solve the panic of closing mr
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODMsNzcyLDg4MV0sIm1lbWJlciI6WyIxMDAxMjYxIl19&id=272392&iterationID=772&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |      solve the panic of closing mr        |
| 🇨🇳 中文    |      解决关闭mr引起的panic        |

fix: solve the panic of closing mr

---

.erda/pipelines/ci-build-ce.yml
build/scripts/docker_image.sh
pipeline.yml

support to specify image-tag
| 🇺🇸 English |    Remove the version in pipeline.yaml         |
| 🇨🇳 中文    |   去掉 pieline.yml 中的 version，解决重复生成 image tag           |
release/1.5 release/1.6.alpha.1

refactor: remove the version in pipeline.yaml

---

conf/dop/i18n/cp/scenarios/app-list-all.yaml
modules/dop/component-protocol/components/app-list-all/list/app.go
modules/dop/component-protocol/components/app-list-all/tabs/render.go

Fix app list updated time format, project service app, tabs order
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=272934&issueFilter__urlQuery=eyJ0aXRsZSI6IjI3MjkzNCIsInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNiw0NDA1LDE2NTg5LDQ0MDgsMTY1ODgsNDQxN119&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG)
| 🇺🇸 English |   Fix app list updated time format, project service app, tabs order           |
| 🇨🇳 中文    |   修复应用列表 更新时间格式 项目应用            | …

fix: Fix app list updated time format, project service app, tabs order

---

modules/dicehub/endpoints/release.go
pkg/strutil/regexp.go
pkg/strutil/regexp_test.go

feat: match semver from branch name
| 🇺🇸 English | to generate release version if the branch is matched [semver](https://semver.org/) |
| 🇨🇳 中文    | 分支名称符合 [语义化版本号](https://semver.org/lang/zh-CN/) 时为制品生成版本号 |

feat: match semver from branch name

---

apistructs/env_config.go
modules/dop/endpoints/config.go
modules/dop/services/environment/env_config.go
pkg/arrays/arrays_test.go

add batch update env config function
| 🇺🇸 English |        add batch update env config function       |
| 🇨🇳 中文    |       增加批量更新部署参数方法       |

feat: add batch update env config function

---

modules/core/monitor/log/persist/consume.go
modules/extensions/loghub/exporter/output.go

fix: trace_id, request_id compatible
| 🇺🇸 English |       add trace_id if missing       |
| 🇨🇳 中文    |        缺少trace_id的日志补充上该字段      |
/cherry-pick release/1.6-alpha.1

fix: trace_id, request_id compatible

---

conf/admin/i18n/cp/scenarios/personal-workbench.yaml
conf/dop/i18n/cp/scenarios/app-list-all.yaml
modules/dop/component-protocol/components/app-list-all/list/provider.go

Add app list item description, fix project app text
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=272934&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjIsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG)
| 🇺🇸 English |   Add app list item description           |
| 🇨🇳 中文    |  应用列表描述            |
Add comment like `/cherry-pick release/1.6-alpha.1` when this PR is merged. …

fix: Add app list item description, fix project app text

---

apistructs/runtime_constant.go
apistructs/runtime_dto.go
apistructs/service.go
bundle/orchestrator.go
modules/orchestrator/dbclient/deployment.go
modules/orchestrator/endpoints/endpoints.go
modules/orchestrator/endpoints/server_handler.go
modules/orchestrator/endpoints/server_handler_test.go
modules/scheduler/endpoints/endpoints.go
modules/scheduler/executor/plugins/k8s/daemonset.go
modules/scheduler/executor/plugins/k8s/deployment.go
modules/scheduler/executor/plugins/k8s/deployment_test.go
modules/scheduler/executor/plugins/k8s/k8s.go
modules/scheduler/executor/plugins/k8s/statefulset.go
modules/scheduler/executor/plugins/k8s/statefulset/statefulset.go
modules/scheduler/executor/plugins/k8s/statefulset_test.go
modules/scheduler/impl/servicegroup/scale.go
pkg/http/httpserver/response.go

surpport  runtimes batch scaledown/scaleup/redeploy/delete
/assign @luobily @sixther-dc @iutx 
orchestrator add API:   {Path: "/api/runtimes/actions/batch-update-pre-overlay", Method: http.MethodPut, Handler: e.BatchUpdateOverlay}
| 🇺🇸 English |         surpport  runtimes batch scaledown/scaleup/redeploy/delete    |
| 🇨🇳 中文    |        支持  runtimes 批量操作     |

feat: surpport runtomes batch scaledown/scaleup/reDeploy/delete

---

.erda/migrations/orchestrator/20220104-deployment-order.sql
apistructs/deployment_order.go
apistructs/runtime_dto.go
bundle/api_asset.go
modules/orchestrator/dbclient/deployment_order.go
modules/orchestrator/endpoints/deployment_order.go
modules/orchestrator/services/apierrors/errors.go
modules/orchestrator/services/deployment_order/deployment_order_create.go
modules/orchestrator/services/deployment_order/deployment_order_get.go
modules/orchestrator/services/deployment_order/deployment_order_get_test.go
modules/orchestrator/services/deployment_order/deployment_order_list.go
modules/orchestrator/services/runtime/runtime.go

| 🇺🇸 English | dice action execute error with deploy center |
| 🇨🇳 中文    |  修复了部署中心状态下 dice action 执行报错问题  |

fix: dice action execute error with deploy center

---

pkg/database/sqlparser/migrator/block.go
pkg/database/sqlparser/migrator/equal.go
pkg/database/sqlparser/migrator/migrator.go
pkg/database/sqlparser/migrator/migrator_test.go

feature: sort by all scripts
| 🇺🇸 English | Migration scripts is sorted by all scripts |
| 🇨🇳 中文    | 优化 migration 执行过程，按所有脚本总排序，不再区分模块 |

feat: sort by all scripts

---

bundle/orchestrator.go

returns for runtimes batch process for different action with different results, need return specific result for action。
根据 action 返回对应的确定结构的结果数据类型。  
Feature: 优化 runtime 批量处理结果返回，以支持按 action 返回特定数据结构
| 🇺🇸 English |       split batch runtomes bundle API       |
| 🇨🇳 中文    |    拆分 runtime 批量处理 API 以支持按 action 返回特定数据结构         |

feat: split batch runtomes bundle API

---

apistructs/release.go
modules/dicehub/dbclient/release.go
modules/dicehub/endpoints/release.go
modules/dicehub/service/release/release.go
modules/dop/component-protocol/components/release-manage/releaseTable/model.go
modules/dop/component-protocol/components/release-manage/releaseTable/render.go
modules/openapi/api/apis/dicehub/dicehub_releases_parse_version.go
modules/openapi/api/apis/dicehub/dicehub_releases_upload.go

1. add upload project release to openapi
2. add parse version to openapi
3. modify upload release
| 🇺🇸 English | 1. add upload project release to openapi; 2. add parse version to openapi; 3. modify upload release |
| 🇨🇳 中文    | 1. 将上传制品添加到openapi 2. 将解析文件的version接口添加到openapi 3. 修改上传制品逻辑 |

feat: support upload project release

---

conf/dop/i18n/cp/scenarios/app-list-all.yaml
modules/dop/component-protocol/components/app-list-all/common/gshelper/helper.go
modules/dop/component-protocol/components/app-list-all/list/provider.go
modules/dop/component-protocol/components/app-list-all/tabs/render.go

Add new tab my app list in app list scenario
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls3NzIsNjgwXSwibWVtYmVyIjpbIjEwMDEwNzMiXX0%3D&id=273517&iterationID=772&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |  Add new tab my app list in app list scenario            |
| 🇨🇳 中文    |   应用列表增加 ”我参与的"  选项          |

feat: Add new tab my app list in app list scenario

---

modules/dop/dao/contribution.go

Update project table name in contribution join sql
/assign @sfwn 
| 🇺🇸 English |    Update contribution sql          |
| 🇨🇳 中文    |    更新个人贡献的sql          |

refactor: Update project table name in contribution join sql

---

.erda/migrations/orchestrator/20220104-deployment-order.sql
apistructs/audits.go
apistructs/deployment_order.go
modules/openapi/api/apis/orchestrator/orchestrator_deployment_order_cancel.go
modules/openapi/api/apis/orchestrator/orchestrator_deployment_order_create.go
modules/openapi/api/apis/orchestrator/orchestrator_deployment_order_deploy.go
modules/openapi/api/apis/orchestrator/orchestrator_deployment_order_get.go
modules/openapi/api/apis/orchestrator/orchestrator_deployment_order_list.go
modules/openapi/api/apis/orchestrator/orchestrator_deployment_order_render_name.go
modules/orchestrator/dbclient/deployment_order.go
modules/orchestrator/endpoints/deployment_order.go
modules/orchestrator/endpoints/endpoints.go
modules/orchestrator/services/apierrors/errors.go
modules/orchestrator/services/deployment/deployment_context.go
modules/orchestrator/services/deployment_order/deployment_order.go
modules/orchestrator/services/deployment_order/deployment_order_cancel.go
modules/orchestrator/services/deployment_order/deployment_order_create.go
modules/orchestrator/services/deployment_order/deployment_order_create_test.go
modules/orchestrator/services/deployment_order/deployment_order_get.go
modules/orchestrator/services/deployment_order/deployment_order_get_test.go
modules/orchestrator/utils/parse.go
pkg/erda-configs/audit/template.json

| 🇺🇸 English |   deployment center permission check            |
| 🇨🇳 中文    |    部署中心鉴权          |

feat: deployment center permission check

---

bundle/orchestrator.go

batch runtimes scale return data is map[string]interface{}, need transfer to specifical data struct  
Bugfix： Fix the  data struct assert bug for  map[string]interface{}
| 🇺🇸 English |      Fix the  data struct assert bug for  map[string]interface{}         |
| 🇨🇳 中文    |         修复数据结构断言 panic 问题     |

fix: transfer data struct

---

providers/audit/interceptor.go
providers/audit/options.go
providers/audit/provider.go

support set context options for audit
| 🇺🇸 English |       support set context options for audit      |
| 🇨🇳 中文    |       审计拦截器支持设置在context上设置 option       |

feat: support set context options for audit

---

conf/monitor/monitor/i18n/alert.yml
conf/monitor/monitor/metricmeta/i18n/_type_aggregations.yml
modules/core/monitor/alert/alert-apis/adapt/expression.go
modules/core/monitor/metric/query/metricmeta/type_aggregations.go

| 🇺🇸 English |      release 1.3 add distinct count        |
| 🇨🇳 中文    |      1.3分支增加去重计数        |

feat: release 1.3 add distinct count

---

apistructs/deployment_order.go
modules/orchestrator/services/deployment_order/deployment_order_create.go
modules/orchestrator/services/deployment_order/deployment_order_create_test.go
modules/orchestrator/services/deployment_order/deployment_order_get.go
modules/orchestrator/services/deployment_order/deployment_order_get_test.go
modules/orchestrator/services/deployment_order/deployment_order_list.go

| 🇺🇸 English |    order list or detail repsonse           |
| 🇨🇳 中文    |   修复部署单列表/详细信息返回错误           |

fix: order list or detail repsonse

---

modules/openapi/api/apis/orchestrator/orchestrator_deployment_order_render_detail.go
modules/orchestrator/endpoints/deployment_order.go
modules/orchestrator/services/deployment_order/deployment_order_create.go

| 🇺🇸 English |  fix render deployment order detail openapi            |
| 🇨🇳 中文    |   修复渲染部署单详情接口错误           |

fix: create deployment order api

---

apistructs/runtime_dto.go
bundle/api_asset.go
conf/dop/i18n/cp/scenarios/project-runtime.yaml
go.mod
go.sum
modules/admin/component-protocol/components/personal-workbench/messageList/messageList.go
modules/admin/component-protocol/components/personal-workbench/workList/provider.go
modules/dop/component-protocol/components/all.go
modules/dop/component-protocol/components/project-runtime/advanceFilter/advanceFilter.go
modules/dop/component-protocol/components/project-runtime/advanceFilter/advanceFilter_test.go
modules/dop/component-protocol/components/project-runtime/cleanData/model.go
modules/dop/component-protocol/components/project-runtime/cleanData/render.go
modules/dop/component-protocol/components/project-runtime/common/common.go
modules/dop/component-protocol/components/project-runtime/filterContainer/filterContainer.go
modules/dop/component-protocol/components/project-runtime/inputFilter/inputFilter.go
modules/dop/component-protocol/components/project-runtime/inputFilter/inputFilter_test.go
modules/dop/component-protocol/components/project-runtime/list/list.go
modules/dop/component-protocol/components/project-runtime/list/list_test.go
modules/dop/component-protocol/components/project-runtime/page/page.go
modules/dop/component-protocol/components/project-runtime/scenario.go
modules/dop/component-protocol/scenarios/project-runtime.yml
modules/orchestrator/dbclient/runtime.go
modules/orchestrator/services/runtime/runtime.go

add project runtime
| 🇺🇸 English |    add project runtime with component protocol          |
| 🇨🇳 中文    |      增加项目级别的runtime列表        |

feat: add project runtime with component protocol

---

apistructs/application.go
bundle/app.go
modules/core-services/dao/application.go
modules/core-services/endpoints/application.go
modules/core-services/endpoints/endpoints.go
modules/core-services/services/apierrors/errors.go
modules/core-services/services/application/appliation.go
modules/dicehub/service/release/release.go
modules/dop/component-protocol/components/release-manage/releaseTable/render.go

add getAppIDByNames to fix creating release when number of apps larger than 100 
| 🇺🇸 English | add getAppIDByNames to fix creating release when number of apps larger than 100  |
| 🇨🇳 中文    | 添加getAppIDByNames接口，用于修复应用数量大于100时导致创建制品失败的问题 |

fix: add get app id by names

---

.erda/migrations/cmdb/20220112-set-org-private.sql

Make all orgs private
| 🇺🇸 English |    Make all orgs private          |
| 🇨🇳 中文    |    组织设置为私有           |

feat: Make all orgs private

---

modules/orchestrator/endpoints/endpoints.go
modules/orchestrator/services/runtime/runtime.go

Restart, Rollback runtime decoupling scheduler and gittar component
| 🇺🇸 English |         Restart, Rollback runtime decoupling pipeline and gittar component     |
| 🇨🇳 中文    |       runtime的重启，回滚解耦gittar跟pipeline      |

feat: Restart, Rollback runtime decoupling pipeline and gittar component

---

modules/dop/component-protocol/components/project-runtime/advanceFilter/advanceFilter.go
modules/dop/component-protocol/components/project-runtime/advanceFilter/advanceFilter_test.go
modules/dop/component-protocol/components/project-runtime/inputFilter/inputFilter.go
modules/dop/component-protocol/components/project-runtime/inputFilter/inputFilter_test.go

| 🇺🇸 English |     add url filter          |
| 🇨🇳 中文    |          增加url筛选功能    |

feat(cp): project runtime: add url filter

---

apistructs/issue.go
modules/dop/services/issue/issue.go

Fix issue creation request with empty time
/assign @sfwn 
| 🇺🇸 English |    Fix issue creation request with empty time          |
| 🇨🇳 中文    |    修复创建事项的时间为空          |

fix: Fix issue creation request with empty time

---

apistructs/audits.go
apistructs/release.go
modules/dicehub/endpoints/release.go
modules/dop/component-protocol/components/release-manage/releaseTable/render.go

update release audit
| 🇺🇸 English | add release type in release batch operation audit message |
| 🇨🇳 中文    | 在制品的批量操作审计日志中添加制品类型信息（项目制品或应用制品） |

fix: update release audit

---

modules/orchestrator/services/deployment_order/deployment_order_create.go
modules/orchestrator/services/deployment_order/deployment_order_create_test.go
modules/orchestrator/services/deployment_order/deployment_order_get.go
modules/scheduler/executor/plugins/k8s/secret.go
modules/scheduler/executor/plugins/k8s/secret_test.go
modules/scheduler/executor/plugins/k8s/service.go
modules/scheduler/impl/servicegroup/create.go

scheduler detail error at service and image secret
| 🇺🇸 English |   scheduler detail error at service and image secret           |
| 🇨🇳 中文    |   修复调度器 service/secret 存在报错           |

fix: scheduler detail error at service and image secret

---

go.mod
go.sum
modules/dop/component-protocol/components/app-list-all/list/provider.go

Add list register operation, update erda infra
/assign @sfwn 
| 🇺🇸 English |  升级 erda infra           |
| 🇨🇳 中文    |    update erda infra          |

fix: Add list register operation, update erda infra

---

modules/orchestrator/endpoints/server_handler.go
modules/orchestrator/endpoints/server_handler_test.go

runtimes bacth process expose more error infos for know why failed.
| 🇺🇸 English |       runtimes bacth process expose more error infos       |
| 🇨🇳 中文    |        runtimes 批量处理暴露更详细的错误信息      |

fix: runtimes bacth process expose more error infos

---

.erda/migrations/qa/20220110-file-record-soft-delete.sql
apistructs/file_records.go
apistructs/permission.go
apistructs/project.go
modules/dop/dao/file_records.go
modules/dop/endpoints/endpoints.go
modules/dop/endpoints/file_records.go
modules/dop/endpoints/project.go
modules/dop/endpoints/project_test.go
modules/dop/initialize.go
modules/dop/services/apierrors/errors.go
modules/dop/services/project/export_template.go
modules/dop/services/project/export_template_test.go
modules/dop/services/project/import_template.go
modules/dop/services/project/import_template_test.go
modules/dop/services/project/project.go
modules/dop/services/project/project_template.go
modules/dop/services/testcase/file_records.go
modules/openapi/api/apis/dop/project_template_export.go
modules/openapi/api/apis/dop/project_template_import.go
modules/openapi/api/apis/dop/project_template_parse.go
pkg/erda-configs/permission/backend/sys/org/org.yml
pkg/erda-configs/permission/backend/sys/org/project/project.yml

support project template import export
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=267145&issueFilter__urlQuery=eyJ0aXRsZSI6IumhueebruaooeeJiOeahOWvvOWHuuWSjOWvvOWFpeWunueOsCIsInN0YXRlcyI6WzQ0MDYsNDQwN119&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=TASK)
| 🇺🇸 English | support project template import export              |
| 🇨🇳 中文    | 实现项目模版导入导出             | …

feat: support project template import export

---

apistructs/deployment_order.go
modules/orchestrator/dbclient/deployment_order.go
modules/orchestrator/endpoints/deployment_order.go
modules/orchestrator/services/deployment_order/deployment_order_cancel.go
modules/orchestrator/services/deployment_order/deployment_order_create.go
modules/orchestrator/services/deployment_order/deployment_order_create_test.go
modules/orchestrator/services/deployment_order/deployment_order_get.go
modules/orchestrator/services/deployment_order/deployment_order_list.go
modules/orchestrator/services/runtime/runtime.go
modules/orchestrator/utils/parse.go
modules/orchestrator/utils/parse_test.go
modules/scheduler/executor/plugins/k8s/service.go

deployment order started time error
| 🇺🇸 English |   deployment order started time error           |
| 🇨🇳 中文    |    部署单开始时间错误          |

fix: deployment order started time error

---

go.mod
go.sum
modules/monitor/apm/topology/topology.go
modules/monitor/apm/topology/topology_test.go
modules/msp/apm/service/components/resources-container-monitor/container/provider.go
modules/msp/apm/service/components/resources-node-monitor/node/provider.go
modules/msp/apm/service/components/resources-runtime-monitor-java/runtime/provider.go
modules/msp/apm/service/components/resources-runtime-monitor-nodejs/runtime/provider.go

| 🇺🇸 English |     use host ip to query node monitor         |
| 🇨🇳 中文    |      使用 host ip 查询 node 信息        |

fix: use host ip to query node monitor

---

.erda/migrations/orchestrator/20220104-deployment-order.sql
apistructs/deployment_order.go
apistructs/runtime.go
apistructs/runtime_dto.go
modules/orchestrator/dbclient/deployment_order.go
modules/orchestrator/dbclient/runtime.go
modules/orchestrator/endpoints/deployment_order.go
modules/orchestrator/services/deployment_order/deployment_order.go
modules/orchestrator/services/deployment_order/deployment_order_cancel.go
modules/orchestrator/services/deployment_order/deployment_order_create.go
modules/orchestrator/services/deployment_order/deployment_order_create_test.go
modules/orchestrator/services/deployment_order/deployment_order_get.go
modules/orchestrator/services/deployment_order/deployment_order_list.go
modules/orchestrator/services/deployment_order/deployment_order_list_test.go
modules/orchestrator/services/runtime/runtime.go
modules/orchestrator/utils/parse_test.go

deployment order name rule
| 🇺🇸 English |    fix deployment order name rule          |
| 🇨🇳 中文    |     修复部署单名称规则       |

fix: deployment order name rule

---

go.mod
go.sum
modules/dop/component-protocol/components/app-list-all/list/provider.go

Fix register operation return empty function
/assign @sfwn 
| 🇺🇸 English |  Fix register operation return empty function            |
| 🇨🇳 中文    |   修复返回空函数    |

fix: Fix register operation return empty function

---

apistructs/file_records.go
apistructs/project.go
modules/dop/endpoints/project.go
modules/dop/services/project/export_template.go
modules/dop/services/project/project_template.go
modules/dop/services/testcase/file_records.go

fix project-template bug
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls3NzIsNjgwLDg4MSw4ODMsNDY3XSwibWVtYmVyIjpbIjEwMDEyMDUiXX0%3D&id=275179&iterationID=772&pId=0&type=BUG)
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls3NzIsNjgwLDg4MSw4ODMsNDY3XSwibWVtYmVyIjpbIjEwMDEyMDUiXX0%3D&id=275205&iterationID=772&pId=0&type=BUG)
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls3NzIsNjgwLDg4MSw4ODMsNDY3XSwibWVtYmVyIjpbIjEwMDEyMDUiXX0%3D&id=275250&iterationID=772&pId=0&type=BUG)
- [Erda Cloud Issue …

fix: Fix/erda file record project name

---

modules/msp/apm/service/common/custom/service_inparams.go
modules/msp/apm/service/components/resources-container-monitor/container/provider.go
modules/msp/apm/service/components/resources-node-monitor/node/provider.go
modules/msp/apm/trace/query/commom/custom/trace_inparams.go

| 🇺🇸 English |     kb -> KB     |
| 🇨🇳 中文    |       kb -> KB      |

fix: unit kb -> KB

---

modules/dicehub/dbclient/extention.go
modules/dicehub/service/extension/extension.go
pkg/expression/expression_reconcile.go

Extension spec yml i18n set up
| 🇺🇸 English |     Extension spec yml  support i18n        |
| 🇨🇳 中文    |    拓展 spec.yml 支持国际化          |

feat: Extension spec yml support i18n

---

apistructs/runtime_dto.go
modules/dop/services/environment/env_config.go
modules/orchestrator/services/deployment/deployment_context.go
modules/orchestrator/services/runtime/runtime.go

fix: runtime response add application name
| 🇺🇸 English |   fix runtime response add application name           |
| 🇨🇳 中文    |     修复 runtime 返回值，添加应用名称         |

fix: runtime response add application name

---

bundle/app.go
conf/dop/i18n/cp/scenarios/project-runtime.yaml
go.sum
modules/dop/component-protocol/components/app-list-all/list/provider.go
modules/dop/component-protocol/components/project-runtime/advanceFilter/advanceFilter.go
modules/dop/component-protocol/components/project-runtime/advanceFilter/advanceFilter_test.go
modules/dop/component-protocol/components/project-runtime/cleanData/render.go
modules/dop/component-protocol/components/project-runtime/list/list.go
modules/dop/component-protocol/components/project-runtime/list/list_test.go

| 🇺🇸 English |       change some style        |
| 🇨🇳 中文    |      修改了一些样式        |

refactor: change some style

---

bundle/dashboard.go
modules/cmp/endpoints/log.go
modules/cmp/impl/nodes/log.go
modules/dop/endpoints/apitest.go
modules/dop/endpoints/cicd.go
modules/dop/services/cdp/cdp.go
modules/orchestrator/endpoints/addon.go
modules/orchestrator/endpoints/migration.go
modules/orchestrator/endpoints/runtime.go
modules/orchestrator/services/runtime/runtime.go

bugfix: get log request add orgName
| 🇺🇸 English |     bugfix: get log request add orgName         |
| 🇨🇳 中文    |     修复了自动化等模块查询日志没传orgName查不到日志的问题        |
/cherry-pick release/1.6-alpha.1

fix: get log request add orgName

---

modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go

fix: fix the bug of table sort
| 🇺🇸 English |       fix the bug of table sort       |
| 🇨🇳 中文    |      解决表格排序问题        |

fix: fix the bug of table sort

---

conf/dop/i18n/cp/common.yaml
go.mod
go.sum
modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go

fix: table column support hidden
| 🇺🇸 English |      table column support hidden        |
| 🇨🇳 中文    |        表格支持隐藏      |

fix: table column support hidden

---

modules/dop/provider.go
modules/dop/providers/projectpipeline/service_impl.go
modules/dop/services/pipeline/pipeline.go
modules/pipeline/aop/plugins/pipeline/definitionreport/plugin.go
modules/pipeline/services/pipelinesvc/create.go
modules/pipeline/services/pipelinesvc/rerun.go

bugfix
return remove / path
report status
rerun and rerun-failed
report pipeline
| 🇺🇸 English |       Fixed many project pipeline bugs       |
| 🇨🇳 中文    |        修复了很多项目流水线的bug      |

fix: project pipelien bug fix

---

modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/filterContainer/customFilter/provider.go
modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
modules/dop/component-protocol/scenarios/project-pipeline.yml
modules/dop/providers/projectpipeline/service_impl.go

fix: fix the bug of project pipeline table
| 🇺🇸 English |       fix the bug of project pipeline table       |
| 🇨🇳 中文    |        解决项目级流水线表格问题      |

fix: fix the bug of project pipeline table

---

modules/dop/component-protocol/components/project-pipeline/myPage/pageHeader/pipelineTabs/model.go
modules/dop/component-protocol/components/project-pipeline/myPage/pageHeader/pipelineTabs/render.go
modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go

fix: fix the bug of pipelineTab
| 🇺🇸 English |     fix the bug of pipelineTab         |
| 🇨🇳 中文    |       解决项目级流水线页面问题       |

fix: fix the bug of pipelineTab

---

modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
modules/dop/providers/projectpipeline/service_impl.go

cron project pipeline
| 🇺🇸 English |       cron project pipeline       |
| 🇨🇳 中文    |        cron project pipeline      |

fix: cron project pipeline

---

modules/orchestrator/services/deployment_order/deployment_order_get.go

fix: deployment order detail application id error
| 🇺🇸 English | fix deployment order detail application id error             |
| 🇨🇳 中文    |     修复部署单详情返回应用id空的场景         |

fix: deployment order detail application id error

---

modules/dop/component-protocol/components/auto-test-scenes/leftPage/leftHead/leftHeadTitle/render.go
modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/fileInfoHead/fileInfoTitle/fileInfoTitle.go
modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/inParamsTitle/inParamsTitle.go
modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/outPutTitle/outPutTitle.go
modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/stagesTitle/stagesTitle.go
modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesSetConfig/scenesSetTitle/scenesSetTitle.go
modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesSetConfig/scenesStagesTitle/scenesStagesTitle.go
modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileExecute/executeHead/executeHistory/executeHistoryPop/render.go
modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileExecute/executeHead/executeHistory/render.go
modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileExecute/executeTaskTitle/render.go

Fix i18n json unmarshal
/assign @sfwn 
| 🇺🇸 English |   Fix i18n json unmarshal           |
| 🇨🇳 中文    |    国际化修复         |

fix: Fix i18n json unmarshal

---

apistructs/deployment_order.go
modules/orchestrator/dbclient/deployment_order.go
modules/orchestrator/endpoints/deployment_order.go
modules/orchestrator/services/deployment_order/deployment_order_list.go
modules/orchestrator/services/deployment_order/deployment_order_list_test.go

fix deployment order permission
| 🇺🇸 English |  fix deployment order permission            |
| 🇨🇳 中文    |     修复部署请求权限      |

fix: deployment order permission

---

modules/msp/apm/service/view/card/slow_count.go
modules/msp/apm/service/view/chart/slow_count.go
modules/msp/apm/service/view/table/transaction.go

| 🇺🇸 English |       fix the bug that slow transaction count error       |
| 🇨🇳 中文    |         修复了慢调用数统计错误的问题     |

fix: fix slow transaction count

---

modules/dop/component-protocol/components/project-pipeline/common/vars.go
modules/dop/component-protocol/components/project-pipeline/myPage/pageHeader/pipelineTabs/model.go
modules/dop/component-protocol/components/project-pipeline/myPage/pageHeader/pipelineTabs/render.go
modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go

fix: fix the bug of mine pipeline
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODMsNzcyXSwibWVtYmVyIjpbIjEwMDEyNjEiXX0%3D&id=275703&iterationID=772&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |      fix the bug of mine pipeline        |
| 🇨🇳 中文    |       解决我的流水线问题       |

fix: fix the bug of mine pipeline

---

modules/dop/providers/projectpipeline/service_impl.go

fix: fix the statics of Failed pipeline
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODMsNzcyXSwibWVtYmVyIjpbIjEwMDEyNjEiXX0%3D&id=275709&iterationID=772&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |   update the statics of Failed pipeline           |
| 🇨🇳 中文    |     修改错误流水线统计方式         |

fix: update the statics of Failed pipeline

---

conf/dop/i18n/cp/common.yaml
go.mod
go.sum
modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go

fix: update the text of table
fix: update the text of table
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=275521&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG
/assign @sfwn 
| 🇺🇸 English |      fix: update the text of table        |
| 🇨🇳 中文    |      文案修改        | …

fix: update the text of table

---

modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go

fix: modify the display of the delete button
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODMsNzcyXSwibWVtYmVyIjpbIjEwMDEyNjEiXX0%3D&id=275759&iterationID=772&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |     modify the display of the delete button         |
| 🇨🇳 中文    |     修改删除按钮的展示         |

fix: modify the display of the delete button

---

modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go

fix: fix time zone issues
/assign @sfwn 
| 🇺🇸 English |      fix time zone issues        |
| 🇨🇳 中文    |       解决时区问题       |

fix: fix time zone issues

---

modules/dop/endpoints/application.go
modules/dop/initialize.go
modules/dop/services/namespace/namespace.go
modules/dop/services/project/export_template.go
modules/dop/services/project/import_template.go
modules/dop/services/project/option.go
modules/dop/services/project/project.go
modules/dop/services/project/project_template.go

generate extra info for app
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls3NzIsNjgwLDg4MSw4ODMsNDY3XSwibWVtYmVyIjpbIjEwMDEyMDUiXX0%3D&id=275884&iterationID=772&pId=0&type=BUG)
| 🇺🇸 English |   Fix the bug that generate extra info for app           |
| 🇨🇳 中文    |  项目模版导入导出为应用配置workspace            |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/maste …

fix: generate extra info for app

---

modules/msp/credential/credential.service.go

add ak creatorid
| 🇺🇸 English |       add ak creatorid       |
| 🇨🇳 中文    |      接入配置没有返回创建人id        |

fix: add ak creatorid

---

modules/msp/apm/browser/components/scenarios/browser-overview.yml

| 🇺🇸 English |     improve browser-overview         |
| 🇨🇳 中文    |       改进前端监控总览页       |

feat: improve browser-overview

---

modules/msp/apm/alert/alert.service.go

find tenant by tk
| 🇺🇸 English |       find tenant by tk       |
| 🇨🇳 中文    |      用tk 查找tenant       |

fix: find tenant by tk

---

modules/msp/apm/browser/components/browser-overview/models/in_params.go
modules/msp/apm/service/common/slow-transaction/inparams.go
modules/msp/apm/service/view/table/transaction.go

| 🇺🇸 English |       fix: fix transaction table empty bug       |
| 🇨🇳 中文    |       修复事务调用列表缺少数据的问题       |

fix: fix transaction table empty bug

---

modules/msp/credential/credential.service.go

ak return userIds
| 🇺🇸 English |      ak return userIds        |
| 🇨🇳 中文    |       接入配置返回userIds       |

fix: ak return userIds

---

modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/filterContainer/customFilter/provider.go

fix: clear state of customfilter when switch tab
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODMsNzcyXSwibWVtYmVyIjpbIjEwMDEyNjEiXX0%3D&id=275820&iterationID=772&pId=0&type=BUG)
| 🇺🇸 English |        clear state of customfilter when switch tab      |
| 🇨🇳 中文    |         切换项目级流水线清空过滤条件     |

fix: clear state of customfilter when switch tab

---

conf/dop/i18n/cp/scenarios/project-runtime.yaml
modules/dop/component-protocol/components/project-runtime/list/list.go

| 🇺🇸 English |      change some style         |
| 🇨🇳 中文    |     修改部署中心的一些样式         |

refactor(project-runtime): change some style

---

modules/orchestrator/dbclient/deployment_order.go
modules/orchestrator/services/deployment_order/deployment_order.go
modules/orchestrator/services/deployment_order/deployment_order_cancel.go
modules/orchestrator/services/deployment_order/deployment_order_create.go
modules/orchestrator/services/deployment_order/deployment_order_create_test.go
modules/orchestrator/services/deployment_order/deployment_order_get.go
modules/orchestrator/services/deployment_order/deployment_order_get_test.go
modules/orchestrator/services/deployment_order/deployment_order_list.go
modules/orchestrator/services/deployment_order/deployment_order_list_test.go

feat: deployment order list release without dicehub bundle
| 🇺🇸 English |  deployment order list release without dicehub bundle            |
| 🇨🇳 中文    |     部署单查询接口不依赖请求 dicehub         |

feat: deployment order list release without dicehub bundle

---

go.sum
modules/dop/component-protocol/components/project-runtime/advanceFilter/advanceFilter.go
modules/dop/component-protocol/components/project-runtime/list/list.go

| 🇺🇸 English |      get all runtime        |
| 🇨🇳 中文    |      获取全量app        |

refactor(project-runtime): get all runtime

---

conf/hepa/hepa.yaml
conf/hepa/i18n/log-trans.yaml
modules/dop/services/project/list_resources.go
modules/hepa/cache/org/org.go
modules/hepa/i18n/i18n.go
modules/hepa/i18n/i18n_test.go
modules/hepa/provider.go
modules/hepa/providers/runtime_service/runtime.service.go
modules/hepa/services/endpoint_api/impl/impl.go
modules/hepa/services/runtime_service/impl/impl.go
pkg/cache/cache.go
pkg/cache/cache_test.go
pkg/http/httpserver/wrapper.go

i18n for deployment log in hepa
| 🇺🇸 English | I18n for deployment |
| 🇨🇳 中文    | 优化部署日志国际化 |

feat: hepa i18n

---

conf/orchestrator/i18n/log-trans.yaml
conf/orchestrator/orchestrator.yaml
modules/dop/services/project/list_resources.go
modules/orchestrator/cache/org/org.go
modules/orchestrator/i18n/i18n.go
modules/orchestrator/i18n/i18n_test.go
modules/orchestrator/initialize.go
modules/orchestrator/provider.go
modules/orchestrator/services/addon/addon.go
modules/orchestrator/services/addon/addon_deploy.go
modules/orchestrator/services/addon/addon_handler.go
modules/orchestrator/services/deployment/deployment_context.go
modules/orchestrator/services/deployment/deployment_context_test.go
pkg/cache/cache.go
pkg/cache/cache_test.go
pkg/http/httpserver/wrapper.go

i18n for deployment log in orchestrator
| 🇺🇸 English | I18n for deployment |
| 🇨🇳 中文    | 优化部署日志国际化 |

feat: orchestrator i18n

---

conf/scheduler/i18n/log-trans.yaml
conf/scheduler/scheduler.yaml
modules/dop/services/project/list_resources.go
modules/scheduler/cache/org/org.go
modules/scheduler/executor/plugins/k8s/check_quota.go
modules/scheduler/executor/plugins/k8s/check_quota_test.go
modules/scheduler/executor/plugins/k8s/instanceinfosync/pod.go
modules/scheduler/executor/plugins/k8s/instanceinfosync/sync.go
modules/scheduler/i18n/i18n.go
modules/scheduler/i18n/i18n_test.go
modules/scheduler/initialize.go
modules/scheduler/provider.go
pkg/cache/cache.go
pkg/cache/cache_test.go
pkg/http/httpserver/wrapper.go

i18n for deployment log in scheduler
| 🇺🇸 English | I18n for deployment |
| 🇨🇳 中文    | 优化部署日志国际化 |

feat: i18n scheduler

---

modules/monitor/apm/topology/topology.go
modules/monitor/apm/topology/topology_test.go

| 🇺🇸 English |    topology node rps metric calculate error          |
| 🇨🇳 中文    |      拓扑节点 rps 指标计算错误        |

fix:  topology node rps metric calculate error

---

conf/msp/i18n/msp-i18n.yaml
modules/msp/apm/checker/apis/checker.v1.service.go
modules/msp/apm/checker/apis/checker.v1.service_test.go
modules/msp/apm/checker/apis/provider.go

| 🇺🇸 English |     checker i18n         |
| 🇨🇳 中文    |      主动监控国际化        |

fix: checker i18n

---

modules/cmp/component-protocol/components/cmp-cluster-list/list/render.go
modules/dop/component-protocol/components/project-runtime/list/list.go

| 🇺🇸 English |    change allocatable to capacity          |
| 🇨🇳 中文    |      clsuter列表使用capacity        |

refactor(cp-cluster): change allocatable to capacity

---

apistructs/deployment_order.go
apistructs/release.go
modules/orchestrator/dbclient/addon_instance.go
modules/orchestrator/dbclient/deployment_order.go
modules/orchestrator/endpoints/deployment_order.go
modules/orchestrator/services/deployment_order/deployment_order.go
modules/orchestrator/services/deployment_order/deployment_order_cancel.go
modules/orchestrator/services/deployment_order/deployment_order_create.go
modules/orchestrator/services/deployment_order/deployment_order_create_test.go
modules/orchestrator/services/deployment_order/deployment_order_get.go
modules/orchestrator/services/deployment_order/deployment_order_list.go
modules/orchestrator/services/deployment_order/deployment_order_render.go
modules/orchestrator/services/deployment_order/deployment_order_render_test.go

feat: add deployment order precheck
| 🇺🇸 English |  add deployment order precheck            |
| 🇨🇳 中文    |    部署单增加前置校验          |

feat: add deployment order pre check

---

modules/dop/component-protocol/components/project-runtime/advanceFilter/advanceFilter.go
modules/dop/component-protocol/components/project-runtime/list/list.go
modules/dop/component-protocol/components/project-runtime/list/list_test.go
modules/openapi/api/apis/orchestrator/orchestrator_projectruntime_count.go
modules/orchestrator/dbclient/runtime.go
modules/orchestrator/endpoints/endpoints.go
modules/orchestrator/endpoints/runtime.go
modules/orchestrator/services/runtime/runtime.go

| 🇺🇸 English |      add count of each workspace        |
| 🇨🇳 中文    |        增加runtime计数接口      |

feat: add count of each workspace

---

modules/dop/component-protocol/components/requirement-task-overview/chartBlock/burnoutChart/model.go
modules/dop/component-protocol/components/requirement-task-overview/chartBlock/burnoutChart/render.go

fix: optimize burnchart of efficacy measure
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODMsNzcyXSwibWVtYmVyIjpbIjEwMDEyNjEiXX0%3D&id=274124&iterationID=772&pId=0&type=BUG)
| 🇺🇸 English |      optimize burnchart of efficacy measure        |
| 🇨🇳 中文    |       燃尽图优化       |

fix: optimize burnchart of efficacy measure

---

go.mod
go.sum
modules/dop/component-protocol/components/project-pipeline/common/vars.go
modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/filterContainer/customFilter/condition.go
modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/filterContainer/customFilter/provider.go

fix: Optimize project pipeline customfilter
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODMsNzcyXSwibWVtYmVyIjpbIjEwMDEyNjEiXX0%3D&id=275813&iterationID=772&pId=0&type=BUG)
| 🇺🇸 English |       Optimize project pipeline customfilter       |
| 🇨🇳 中文    |     项目级流水线过滤交互优化         |

fix: Optimize project pipeline customfilter

---

modules/core/monitor/dataview/data.view.service.go
pkg/common/apis/header.go

delete GetMSPInfo
| 🇺🇸 English |      delete GetMSPInfo        |
| 🇨🇳 中文    |       删除无意义的GetMSPInfo       |

feat: delete GetMSPInfo

---

modules/dicehub/endpoints/release.go
modules/dicehub/service/release/release.go
modules/dop/component-protocol/components/release-manage/releaseTable/render.go

1. check dedup app when update release
2. check projectID and projectName when update creating release
| 🇺🇸 English | 1. check dedup app when update release 2. check projectID and projectName when update creating release |
| 🇨🇳 中文    | 1. 更新制品时检查是否有应用选择了多次，有则报错 2. 创建制品时检查项目ID和项目名称 |

fix: check dedup app when update release

---

modules/orchestrator/dbclient/deployment_order.go
modules/orchestrator/services/deployment/deployment_context.go
modules/orchestrator/services/runtime/runtime.go
modules/orchestrator/services/runtime/runtime_test.go

feat:optimize the response time of the runtime list
| 🇺🇸 English |      feat:optimize the response time of the runtime list        |
| 🇨🇳 中文    |        优化runtime列表的响应时间      |

feat: optimize the response time of the runtime list

---

modules/admin/component-protocol/components/personal-workbench/workCards/provider.go

| 🇺🇸 English |      change url of collect app        |
| 🇨🇳 中文    |     修改收藏app的路径         |

fix(cp-person): change url of collect app

---

conf/dop/i18n/cp/scenarios/project-runtime.yaml
go.mod
go.sum
modules/dop/component-protocol/components/project-runtime/list/list.go
modules/dop/component-protocol/components/project-runtime/list/list_test.go

| 🇺🇸 English |          add disable tip    |
| 🇨🇳 中文    |     增加list disable效果         |

fix(cp): add disable tip

---

modules/dop/initialize.go
modules/dop/services/assetsvc/svc.go
modules/dop/services/assetsvc/svc_test.go

use bundle by singleton
| 🇺🇸 English |  fix the problem that failed to create contrat in API management |
| 🇨🇳 中文    | 修复了 API 管理中创建合约失败的问题 |

feat: fix the problem that failed to create contrat in API management

---

modules/monitor/apm/topology/topology.go
modules/monitor/apm/topology/topology_test.go

| 🇺🇸 English |  Filter useless associations between topology nodes           |
| 🇨🇳 中文    |    过滤拓扑节点之间无用的关联关系          |

fix: Filter useless associations between topology nodes

---

conf/msp/i18n/msp-i18n.yaml
modules/msp/member/mebmer.service.go
modules/msp/member/provider.go

notify group member list internationalization
| 🇺🇸 English |       notify group member list internationalization      |
| 🇨🇳 中文    |       通知组成员列表国际化       |

feat: notify group member list internationalization

---

conf/monitor/monitor/chartview/apim/apim_client.json
conf/monitor/monitor/chartview/apim/apim_summary.json

update apim dashboard i18n configuration
| 🇺🇸 English | update apim dashboard i18n configuration |
| 🇨🇳 中文    | 更新 api 管理大盘国际化配置 |

feat: apim dashboard i18n config

---

modules/cmp/component-protocol/components/cmp-dashboard-pods/consoleButton/render.go
modules/cmp/component-protocol/components/cmp-dashboard-pods/scenario.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/consoleButton/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/scenario.go
modules/cmp/component-protocol/scenarios/cmp-dashboard-pods.yml
modules/cmp/component-protocol/scenarios/cmp-dashboard-workloads-list.yml

add console button
| 🇺🇸 English | add console button |
| 🇨🇳 中文    | 将cmp中的kubectl console改为组件化，解决英文状态下该按钮与创建按钮重叠的问题 |

fix: add console button

---

apistructs/release.go
conf/dop/i18n/cp/scenarios/release-manage.yaml
modules/dicehub/dbclient/release.go
modules/dicehub/endpoints/release.go
modules/dicehub/service/release/release.go
modules/dop/component-protocol/components/release-manage/inputFilter/render.go
modules/dop/component-protocol/components/release-manage/releaseFilter/model.go
modules/dop/component-protocol/components/release-manage/releaseFilter/render.go
modules/dop/component-protocol/components/release-manage/releaseTable/model.go
modules/dop/component-protocol/components/release-manage/releaseTable/render.go

feat: add jump to application releases
| 🇺🇸 English | feat: add jump to application releases |
| 🇨🇳 中文    | 在项目制品列表中添加查看引用制品的操作 |

feat: add jump to application releases

---

cmd/monitor/collector/main.go
cmd/monitor/collector/main_test.go

support config file initializer
| 🇺🇸 English |       support collector config file initializer       |
| 🇨🇳 中文    |      collector支持配置文件变量初始化        |

fix: support init config file

---

cmd/monitor/collector/main.go
cmd/monitor/collector/main_test.go

fix getfile logic
| 🇺🇸 English |       fix getConfigFile logic       |
| 🇨🇳 中文    |        修复配置文件逻辑bug      |

fix: fix getfile logic

---

apistructs/pipeline_page.go
modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/pipelineTable/provider.go
modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
modules/dop/providers/projectpipeline/service_impl.go
modules/pipeline/aop/plugins/pipeline/definitionreport/plugin.go
modules/pipeline/services/pipelinesvc/convert.go

fix: fix the bug of project pipeline executor
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODMsNzcyXSwibWVtYmVyIjpbIjEwMDEyNjEiXX0%3D&id=277099&iterationID=772&pId=0&type=BUG)
| 🇺🇸 English |      fix the bug of project pipeline executor        |
| 🇨🇳 中文    |         解决项目流水线执行人错误     |

fix: fix the bug of project pipeline executor

---

modules/dop/component-protocol/components/release-manage/releaseTable/model.go
modules/dop/component-protocol/components/release-manage/releaseTable/render.go

fix: release filter by applicationIDs
| 🇺🇸 English | fix: release filter by applicationIDs |
| 🇨🇳 中文    | 修复制品管理按照应用筛选失效的问题 |

fix: release filter by applicationIDs

---

modules/dop/component-protocol/scenarios/project-pipeline.yml

fix: add rendering to customFilter
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODMsNzcyXSwibWVtYmVyIjpbIjEwMDEyNjEiXX0%3D&id=277133&iterationID=772&pId=0&type=BUG)
| 🇺🇸 English |      add rendering to customFilter        |
| 🇨🇳 中文    |       customFilter组件增加rendering       |

fix: add rendering to customFilter

---

.github/workflows/git-sync.yml
pipeline.yml

remove hack part of mirror
/assign @sfwn 
| 🇺🇸 English |    remove hack part of mirror          |
| 🇨🇳 中文    |      移除不必要的hack mirror逻辑        |

chore: remove hack part of mirror

---

modules/core-services/services/project/project.go
modules/orchestrator/services/runtime/runtime.go

delete relationship of orchestrator and pipeline
| 🇺🇸 English |     delete relationship of orchestrator and pipeline         |
| 🇨🇳 中文    |        解除orchestrator跟pipeline的耦合      |

feat: delete relationship of orchestrator and pipeline

---

conf/dop/i18n/cp/common.yaml
modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go

fix: support i18n to execute operation
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODMsNzcyXSwibWVtYmVyIjpbIjEwMDEyNjEiXX0%3D&id=277088&iterationID=772&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |     support i18n to execute operation         |
| 🇨🇳 中文    |       执行操作支持国际化       |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTIN …

fix: support i18n to execute operation

---

modules/dop/component-protocol/components/project-runtime/list/list.go
modules/dop/component-protocol/components/project-runtime/list/list_test.go

| 🇺🇸 English |       disable tip        |
| 🇨🇳 中文    |      disable提示     |

fix(cp): disable tip

---

modules/orchestrator/dbclient/deployment_order.go

deployment order support name fuzzy search
| 🇺🇸 English |   deployment order support name fuzzy search           |
| 🇨🇳 中文    |    部署单支持名称模糊搜索          |

feat: deployment order support name fuzzy search

---

conf/msp/i18n/msp-i18n.yaml
go.mod
go.sum
modules/msp/apm/browser/components/browser-overview/charts/api_resources_req_count/provider.go
modules/msp/apm/browser/components/browser-overview/charts/api_resources_req_duration/provider.go
modules/msp/apm/browser/components/browser-overview/charts/page_req_duration_distribution/provider.go
modules/msp/apm/browser/components/browser-overview/charts/pv_uv_count/provider.go
modules/msp/apm/service/components/transaction-cache-analysis/table_filter/provider.go
modules/msp/apm/service/components/transaction-db-analysis/table_filter/provider.go
modules/msp/apm/service/components/transaction-http-analysis/table_filter/provider.go
modules/msp/apm/service/components/transaction-mq-analysis/table_filter/provider.go
modules/msp/apm/service/components/transaction-rpc-analysis/table_filter/provider.go
modules/msp/apm/service/datasources/transaction.go
modules/msp/apm/trace/query/components/trace-query/req_distribution/provider.go

feature: browser/service-transaction charts support dynamic Y unit
/assign @liuhaoyang @innerpeacez 
| 🇺🇸 English |        feat: browser/service-transaction charts support dynamic Y unit      |
| 🇨🇳 中文    |       前端监控/服务调用 图表支持y轴动态单位       |

feat: browser/service-transaction charts support dynamic Y unit

---

pipeline.yml

force tag version to release artifact
| 🇺🇸 English |    force tag version to release artifact          |
| 🇨🇳 中文    |        强制指定制品版本      |

ci: force tag version to release artifact

---

pipeline.yml

disable migration in artifact
| 🇺🇸 English |      disable migration in artifact        |
| 🇨🇳 中文    |        关闭migration      |

ci: disable migration in artifact

---

go.mod
go.sum
modules/admin/component-protocol/components/personal-workbench/workList/provider.go
modules/dop/component-protocol/components/app-list-all/list/provider.go
modules/dop/component-protocol/components/project-runtime/common/common.go
modules/dop/component-protocol/components/project-runtime/list/list.go
modules/dop/component-protocol/components/project-runtime/list/list_test.go

| 🇺🇸 English |      add runtime status        |
| 🇨🇳 中文    |     增加runtime状态         |

feat(cp): add runtime status

---

modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/filterContainer/customFilter/condition.go
modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/filterContainer/customFilter/provider.go
modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/pipelineTable/provider.go
modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/filterContainer/customFilter/condition.go
modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/filterContainer/customFilter/provider.go
modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
modules/dop/component-protocol/components/util/vars.go
modules/dop/providers/projectpipeline/service_impl.go

bugfix project pipeline Reduce status queries
bugfix project pipeline create precheck same name definition
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODMsNzcyXSwibWVtYmVyIjpbIjEwMDA1NjAiXX0%3D&id=275799&iterationID=772&pId=0&type=BUG)
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODMsNzcyXSwibWVtYmVyIjpbIjEwMDA1NjAiXX0%3D&id=276321&iterationID=772&pId=0&type=BUG)
| 🇺🇸 English |       project pipeline Reduce status queries and create precheck       |
| 🇨🇳 中文    |      项目流水线减少状态查询并创建预检查        |

fix: project pipeline Reduce status queries and create precheck

---

modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/podsTable/render.go

fix: remove pod console and log operation
| 🇺🇸 English | fix: remove pod console and log operation |
| 🇨🇳 中文    | 移除CMP工作负载中pod的查看日志和控制台按钮 |

fix: remove pod console and log operation

---

bundle/member.go
modules/dop/endpoints/member.go
modules/msp/member/mebmer.service.go
modules/msp/member/mebmer.service_test.go

msp dop project interational
| 🇺🇸 English |       msp dop project interational       |
| 🇨🇳 中文    |       msp dop项目成员国际化       |

feat: msp dop project interational

---

modules/dop/component-protocol/components/release-manage/releaseFilter/model.go
modules/dop/component-protocol/components/release-manage/releaseFilter/render.go
modules/dop/component-protocol/components/release-manage/releaseFilter/render_test.go

fix: release url query
| 🇺🇸 English | fix: release url query |
| 🇨🇳 中文    | 修复release筛选器中releaseID没有在urlQuery中生效的问题 |

fix: release url query

---

modules/pipeline/providers/definition/pipeline_definition.go

fix: fix the bug of definition update
| 🇺🇸 English |     fix the bug of definition update         |
| 🇨🇳 中文    |      解决流水线定义修改bug        |

fix: fix the bug of definition update

---

modules/pipeline/pipengine/reconciler/dbgc.go
modules/pipeline/pipengine/reconciler/pipeline_gc_compensator.go

Fix pipeline slow sql query
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=277902&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=TASK)
| 🇺🇸 English |      Solve the slow SQL caused by some gc tasks in the pipeline        |
| 🇨🇳 中文    |       解决流水线中 一些gc任务导致的慢 sql       |

fix: pipeline slow sql query 

---

conf/cmp/i18n/cp/scenarios/cmp-dashboard-nodes.yaml
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/chart/model.go

| 🇺🇸 English |         change chart style      |
| 🇨🇳 中文    |          修改展示样式    |

refactor(cp-nodes): change chart style

---

apistructs/file_records.go
apistructs/issue.go
modules/dop/conf/conf.go
modules/dop/endpoints/endpoints.go
modules/dop/endpoints/issue.go
modules/dop/initialize.go
modules/dop/services/issue/export.go
modules/dop/services/issue/import.go
modules/dop/services/issue/issue.go
modules/dop/services/testcase/file_records.go

make import-export issue excel async
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=263103&issueFilter__urlQuery=eyJ0aXRsZSI6IuOAkOaAp%2BiDveS8mOWMluOAkeWvvOWFpeWvvOWHuuS8mOWMliIsInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG)
| 🇺🇸 English | make import-export issue excel async              |
| 🇨🇳 中文    |   性能优化，导入导出事项异步           | …

fix: issue import export asynchronous

---

apistructs/extention.go

Fix extension query with menu
/assign @sfwn 
| 🇺🇸 English |    Fix extension query with menu          |
| 🇨🇳 中文    |    修复了 扩展菜单 查询           |

fix: Fix extension query with menu

---

modules/msp/tenant/project/project.service_test.go
modules/msp/tenant/project/project_statistics.go

fix: project list statistics error
| 🇺🇸 English |       fix: project list statistics error       |
| 🇨🇳 中文    |       修复微服务治理项目列表统计值错误问题       |

fix: project list statistics error

---

bundle/member.go
conf/msp/i18n/msp-i18n.yaml
modules/dop/endpoints/member.go
modules/msp/member/mebmer.service.go
modules/msp/member/mebmer.service_test.go
modules/msp/member/provider.go
pkg/http/httputil/header.go

release/1.5 notify group member international
| 🇺🇸 English |      release/1.5 notify group member international        |
| 🇨🇳 中文    |        release/1.5通知组成员国际化      |

feat: release/1.5 notify group member international

---

conf/dop/i18n/cp/common.yaml
go.mod
go.sum
modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/pipelineTable/provider.go
modules/dop/component-protocol/components/project-pipeline/myPage/pageHeader/pipelineTabs/render.go
modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go

fix: update project pipeline style
| 🇺🇸 English |      fix: update project pipeline style       |
| 🇨🇳 中文    |      项目流水线表格样式调整     |

fix: update project pipeline style

---

modules/dop/component-protocol/components/release-manage/releaseFilter/render.go
modules/dop/component-protocol/components/release-manage/releaseTable/render.go

1. remove releaseID filter for app release
2. modify i18n
| 🇺🇸 English | polish: remove releaseID filter for app release; modify i18n |
| 🇨🇳 中文    | 移除项目制品页面中按照ID搜索的选项；修改表格文案 |

fix: remove releaseID filter for app release

---

apistructs/file_records.go
apistructs/issue.go
modules/dop/conf/conf.go
modules/dop/endpoints/endpoints.go
modules/dop/endpoints/issue.go
modules/dop/initialize.go
modules/dop/services/issue/export.go
modules/dop/services/issue/import.go
modules/dop/services/issue/issue.go
modules/dop/services/testcase/file_records.go

This reverts commit 8677882444f6fc6a55a0d59b8e88d9c5090faa61.
revert issue import export asynchronous
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls3NzIsNjgwLDg4MSw4ODMsNDY3XSwibWVtYmVyIjpbIjEwMDEyMDUiXX0%3D&id=263103&iterationID=772&pId=0&type=BUG)
| 🇺🇸 English |  revert issue import export asynchronous            |
| 🇨🇳 中文    |   先回退事项异步导入导出           | …

revert: "fix: issue import export asynchronous (#3764)"

---

conf/msp/i18n/msp-i18n.yaml

| 🇺🇸 English |    update msp i18n config          |
| 🇨🇳 中文    |      更新msp国际化配置        |

fix: update msp i18n config

---

modules/openapi/api/apis/dop/config_manage/config_manage_config_post.go

add checkToken to config_post url
| 🇺🇸 English |         add checkToken to config_post url     |
| 🇨🇳 中文    |       增加配置接口添加token检验       |

feat: add checkToken to config_post url

---

modules/dop/providers/projectpipeline/service_impl.go

fix:  fix pipeline permission issues
| 🇺🇸 English |     fix:  fix project pipeline permission issues         |
| 🇨🇳 中文    |       解决项目流水线权限问题       |

fix:  fix project pipeline permission issues

---

modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/pipelineTable/provider.go

fix: update project pipeline style
see: https://github.com/erda-project/erda/pull/3769

fix: project pipeline records add userIDs

---

modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go

fix: remove app and branch column
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODMsNzcyXSwibWVtYmVyIjpbIjEwMDEyNjEiXX0%3D&id=278247&iterationID=772&pId=0&type=BUG)
| 🇺🇸 English |      fix: remove app and branch column       |
| 🇨🇳 中文    |    去除app和branch column          |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRI …

fix: remove app and branch column

---

bundle/api_asset.go
modules/dop/component-protocol/components/project-runtime/list/list.go
modules/openapi/api/apis/orchestrator/orchestrator_runtime_batch_services.go
modules/orchestrator/endpoints/endpoints.go
modules/orchestrator/endpoints/runtime.go
modules/orchestrator/services/runtime/runtime.go

| 🇺🇸 English |      change service query        |
| 🇨🇳 中文    |      修改service 查询方式        |

refactor(cp-project): change service query

---

modules/dop/component-protocol/components/release-manage/releaseTable/model.go
modules/dop/component-protocol/components/release-manage/releaseTable/render.go
modules/dop/component-protocol/components/release-manage/releaseTable/render_test.go

fix: release formal filter
| 🇺🇸 English | fix: release formal filter |
| 🇨🇳 中文    | 修复制品管理页面不能同时获取正式和非正式制品的问题 |

fix: release formal filter

---

conf/msp/instrumentationlibrary/jaeger-template.yaml
modules/msp/apm/adapter/adapter.service.go
modules/msp/apm/adapter/adapter.service_test.go
modules/msp/apm/adapter/model.go

access config international
| 🇺🇸 English |       access config international       |
| 🇨🇳 中文    |       接入配置做国际化       |

feat: access config international

---

modules/dicehub/dbclient/extention.go

Fix extension spec i18n replace value instead of text
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODMsNzcyLDY4MF0sIm1lbWJlciI6WyIxMDAxMDczIl19&id=278841&iterationID=772&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |   Fix extension  i18n           |
| 🇨🇳 中文    |    修复 扩展 国际化          |

fix: Fix extension spec i18n replace value instead of text

---

modules/orchestrator/dbclient/deployment.go
modules/orchestrator/dbclient/runtime.go
modules/orchestrator/services/runtime/runtime.go
modules/orchestrator/services/runtime/runtime_test.go

The deployment status query in runtime is changed to a one-time query
| 🇺🇸 English |     The deployment status query in runtime is changed to a one-time query         |
| 🇨🇳 中文    |       查询runtime的部署状态改为一次查询       |

feat: The deployment status query in runtime is changed to a one-time query

---

modules/admin/component-protocol/components/personal-workbench/messageList/messageList.go
modules/admin/component-protocol/components/personal-workbench/workList/provider.go
modules/admin/component-protocol/components/personal-workbench/workList/provider_test.go
modules/dop/component-protocol/components/app-list-all/list/provider.go

workbench star bugfix, selectable should set to true
| 🇺🇸 English | workbench star bugfix, selectable should set to true |
| 🇨🇳 中文    |  列表星标 bugfix, 需设置新增字段 selectable 为 true |

fix: workbench star bugfix

---

conf/dop/i18n/cp/scenarios/addon-mysql-account.yaml
conf/dop/i18n/cp/scenarios/addon-mysql-consumer.yaml
modules/dop/component-protocol/components/addon-mysql-account/accountTable/render.go
modules/dop/component-protocol/components/addon-mysql-account/accountTable/render_test.go
modules/dop/component-protocol/components/addon-mysql-account/addAccountButton/render.go
modules/dop/component-protocol/components/addon-mysql-account/filter/render.go
modules/dop/component-protocol/components/addon-mysql-account/viewPassword/render.go
modules/dop/component-protocol/components/addon-mysql-account/viewPasswordModal/render.go
modules/dop/component-protocol/components/addon-mysql-attachment/attachmentTable/render.go
modules/dop/component-protocol/components/addon-mysql-attachment/config/configCopyParams/render.go
modules/dop/component-protocol/components/addon-mysql-attachment/config/configDrawer/render.go
modules/dop/component-protocol/components/addon-mysql-attachment/editFormModal/render.go
modules/dop/component-protocol/components/addon-mysql-attachment/filter/render.go

add i18n for mysql account
| 🇺🇸 English |       add i18n for mysql account       |
| 🇨🇳 中文    |       mysql 账号管理的国际化       |

feat(dop): add i18n for mysql account

---

conf/cmp/i18n/cp/scenarios/cmp-dashboard-nodes.yaml
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/chart/model.go

| 🇺🇸 English |      change charts style        |
| 🇨🇳 中文    |      更新图表样式        |

refactor: change charts style

---

conf/dop/i18n/cp/common.yaml
modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
modules/pipeline/aop/plugins/task/definitionreport/plugin.go

fix(dop): only success status will be reported in project pipeline process
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODMsNzcyXSwibWVtYmVyIjpbIjEwMDEyNjEiXX0%3D&id=278903&iterationID=772&pId=0&type=BUG)
| 🇺🇸 English |   only success status will be reported in project pipeline process           |
| 🇨🇳 中文    |     重新计算流水线执行进度，只有成功的才会上报         | …

fix(dop,pipeline): only success status will be reported in project pipeline process

---

apistructs/issue.go
apistructs/issue_stream_locale.go
conf/dop/dop.yaml
conf/dop/i18n/contribution.yaml
modules/dop/component-protocol/components/auto-test-scenes/leftPage/fileFormModal/render.go
modules/dop/component-protocol/components/scenes-import-record/filter/render.go
modules/dop/providers/contribution/provider.go
modules/dop/providers/contribution/service.go
modules/openapi/component-protocol/scenarios/project-list-all/components/filter/render.go
modules/openapi/component-protocol/scenarios/project-list-my/components/filter/render.go
pkg/erda-configs/i18n/project_list_all.json

Add i18n content, issue stream, contribution
/assign @sfwn 
| 🇺🇸 English |    Add i18n content, issue stream, contribution          |
| 🇨🇳 中文    |     增加国际化内容         |

fix: Add i18n content, issue stream, contribution

---

apistructs/issue.go
apistructs/issue_stream_locale.go
conf/dop/dop.yaml
conf/dop/i18n/contribution.yaml
modules/dop/endpoints/issue.go
modules/dop/services/issuestream/issue_stream.go
modules/dop/services/issuestream/issue_stream_template.go
modules/dop/services/issuestream/issue_stream_template_test.go
modules/openapi/component-protocol/scenarios/project-list-all/components/filter/render.go
modules/openapi/component-protocol/scenarios/project-list-my/components/filter/render.go
pkg/erda-configs/i18n/project_list_all.json

| 🇺🇸 English |   fix i18n content           |
| 🇨🇳 中文    |     修复了国际化         |

fix: Release i18n content

---

modules/dop/component-protocol/components/issue-kanban/issueExport/render.go
modules/dop/component-protocol/components/issue-kanban/issueImport/render.go
modules/dop/component-protocol/components/issue-manage/issueExport/render.go
modules/dop/component-protocol/components/issue-manage/issueImport/render.go

| 🇺🇸 English |    fix i18n          |
| 🇨🇳 中文    |     修复了 国际化         |

fix: Issue import i18n

---

modules/dop/component-protocol/scenarios/issue-kanban.yml

Add issue kanban refresh operation
/assign @sfwn 
| 🇺🇸 English |  Add issue kanban refresh operation            |
| 🇨🇳 中文    |   事项看板 刷新操作      |

feat: Add issue kanban refresh operation

---

modules/dop/component-protocol/components/addon-mysql-account/accountTable/render.go

fix(dop): bad i18n template usage
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls3NzIsODgzXSwibWVtYmVyIjpbIjU1IiwiMTAwMTIwNSIsIjkyIiwiMTAwMTA3MyIsIjEwMDA1NjAiLCIxMDAxMjYxIl19&id=279919&iterationID=772&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |      fix(dop): bad i18n template usage        |
| 🇨🇳 中文    |        修复错误的 i18n 模版      |

fix(dop): bad i18n template usage

---

modules/dop/services/autotest_v2/testplan_v2.go

fix(dop): solve the same name check bug
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODMsNzcyXSwibWVtYmVyIjpbIjEwMDEyNjEiXX0%3D&id=274164&iterationID=772&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |     duplicate name check is not case sensitive         |
| 🇨🇳 中文    |        重名验证不区分大小写      |

fix(dop): duplicate name check is not case sensitive

---

modules/core/monitor/log/storage/provider.go
modules/core/monitor/log/storage/provider_test.go
modules/core/monitor/log/storage/storage.go
modules/core/monitor/log/storage/ttl.go
modules/core/monitor/log/storage/ttl_test.go

fix: fix log storate ttl bug

---

apistructs/issue_state.go
modules/dop/endpoints/project.go
modules/dop/services/issuestate/issuestate.go
modules/dop/services/issuestate/issuestate_test.go
modules/dop/services/issuestate/state-en_US.json
modules/dop/services/issuestate/state-zh_CN.json

i18n of issue states
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=206495&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=-1&type=BUG)
| 🇺🇸 English | Fix the bug thati18n of issue states             |
| 🇨🇳 中文    |  修复了事项工单的国际化            | …

fix: i18n of issue states

---

modules/dop/component-protocol/components/project-list-all/components/list/provider.go
modules/dop/component-protocol/scenarios/project-list-all.yml

Project list item default logo, hierarchy change
| 🇺🇸 English |    Project list item default logo, hierarchy change          |
| 🇨🇳 中文    |    项目列表 默认图标 结构变化          |

feat:  Project list item default logo, hierarchy change

---

modules/core/monitor/metric/storage/elasticsearch/provider.go

| 🇺🇸 English |         remove apm metrics compatible     |
| 🇨🇳 中文    |        在存储时移除apm metrics的tag兼容      |

feat: remove apm metrics compatible

---

conf/cmp/i18n/cp/scenarios/cmp-cluster-list.yaml
modules/cmp/component-protocol/components/cmp-cluster-list/list/render.go
modules/cmp/component-protocol/components/cmp-cluster-list/list/render_test.go

change memory to mem in chart
| 🇺🇸 English |          change memory to mem in chart    |
| 🇨🇳 中文    |       修改集群列表内存翻译       |

refactor(cp-cluster): change memory to mem in chart

---

modules/scheduler/executor/executor.go
modules/scheduler/impl/cluster/clusterutil/clusterutil.go

Scheduler create executor failed when can not connect to cluster, this will result in executors never being created.
Try creating executor when you want to use it.
| 🇺🇸 English |   scheduler executor create at runtime           |
| 🇨🇳 中文    |    调度器在运行时创建执行器          |

fix: scheduler executor create at runtime

---

apistructs/file_records.go
apistructs/issue.go
modules/dop/conf/conf.go
modules/dop/endpoints/issue.go
modules/dop/initialize.go
modules/dop/services/issue/export.go
modules/dop/services/issue/import.go
modules/dop/services/issue/issue.go
modules/dop/services/testcase/file_records.go

issue import export asynchronous
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=263103&issueFilter__urlQuery=eyJ0aXRsZSI6IuOAkOaAp%2BiDveS8mOWMluOAkeWvvOWFpeWvvOWHuuS8mOWMliIsInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG)
| 🇺🇸 English |  Fix the bug that issue import export asynchronous            |
| 🇨🇳 中文    |  事项导入导出的异步优化            | …

fix: issue import export asynchronous（reopen）

---

modules/cmp/component-protocol/scenarios/cmp-dashboard-pods.yml
modules/cmp/component-protocol/scenarios/cmp-dashboard-workloads-list.yml

fix: console button
| 🇺🇸 English | fix: console button |
| 🇨🇳 中文    | 修复控制台按钮消失的问题 |

fix: console button

---

modules/dop/component-protocol/components/release-manage/releaseFilter/render.go

feat: aggregate release by default
| 🇺🇸 English | feat: aggregate release by default |
| 🇨🇳 中文    | 制品管理页面默认按照分支聚合 |

feat: aggregate release by default

---

bundle/core_services.go
bundle/orchestrator.go
modules/cmp/impl/clusters/offline_edge_cluster.go
modules/cmp/impl/clusters/offline_test.go
modules/core-services/dao/project.go
modules/core-services/endpoints/project.go
modules/core-services/services/apierrors/errors.go
modules/core-services/services/project/project.go
modules/orchestrator/dbclient/addon_instance_routing.go
modules/orchestrator/dbclient/runtime.go
modules/orchestrator/endpoints/runtime.go
modules/orchestrator/services/runtime/runtime.go

| 🇺🇸 English | cluster delete bugfix, check cluster reference info with org id |
| 🇨🇳 中文    | 集群删除 bugfix，检查集群引用信息时需要针对具体的企业 |

fix: delete cluster bugfix

---

apistructs/job.go
apistructs/pipeline_container_instance.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sjob/k8sjob.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/logic/job.go
modules/pipeline/pipengine/reconciler/taskrun/taskop/prepare.go
modules/pipeline/pkg/container_provider/container_instance_provider.go
modules/pipeline/pkg/container_provider/container_provider_test.go
modules/pipeline/services/pipelinesvc/create_task.go
modules/pipeline/services/pipelinesvc/create_v2.go
modules/pipeline/services/pipelinesvc/run.go
modules/pipeline/spec/pipeline_extra.go
modules/pipeline/spec/pipeline_task.go

pipeline eci refactor
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=274468&issueFilter__urlQuery=eyJ0aXRsZSI6IuOAkHBpcGVsaW5l44CRcGlwZWxpbmXmlLnpgKDmiJDkuIrlsYLmlK%2FmjIFlY2nnmoTphY3nva4iLCJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=TASK)
| 🇺🇸 English |  pipeline eci refactor            |
| 🇨🇳 中文    |  优化了pipeline eci的逻辑            | …

refactor: pipeline eci refactor

---

apistructs/deployment_order.go
conf/orchestrator/i18n/deployment-order-precheck.yaml
modules/orchestrator/dbclient/deployment_order.go
modules/orchestrator/dbclient/runtime.go
modules/orchestrator/endpoints/deployment_order.go
modules/orchestrator/i18n/i18n.go
modules/orchestrator/services/deployment/deployment_context.go
modules/orchestrator/services/deployment_order/deployment_order_create.go
modules/orchestrator/services/deployment_order/deployment_order_create_test.go
modules/orchestrator/services/deployment_order/deployment_order_get.go
modules/orchestrator/services/deployment_order/deployment_order_render.go
modules/orchestrator/services/deployment_order/deployment_order_render_test.go
modules/orchestrator/services/runtime/runtime.go

support deploy with specified version from pipeline
| 🇺🇸 English |  support deploy with specified version from pipeline            |
| 🇨🇳 中文    |   支持流水线驱动项目制品/应用制品部署           |

feat: support deploy with specified version from pipeline

---

modules/core-services/endpoints/project.go

fix: sort project list
| 🇺🇸 English | fix sorting project list |
| 🇨🇳 中文    | 修复了管理中心项目排序失败的问题 |

fix: sort project list

---

go.mod
go.sum
modules/cmp/component-protocol/scenarios/cmp-dashboard-poddetail.yml
modules/cmp/component-protocol/scenarios/cmp-dashboard-pods.yml
modules/cmp/component-protocol/scenarios/cmp-dashboard-workload-detail.yml
modules/cmp/component-protocol/scenarios/cmp-dashboard-workloads-list.yml

fix: comp not found
/assign @sfwn 
| 🇺🇸 English | fix: comp not found |
| 🇨🇳 中文    | 修复组件不存在的问题 |

fix: comp not found

---

modules/dop/component-protocol/components/release-manage/releaseFilter/render.go

fix: hide aggregate button
| 🇺🇸 English | fix: hide aggregate button |
| 🇨🇳 中文    | 暂时隐藏制品聚合按钮 |

fix: hide aggregate button

---

modules/dop/component-protocol/components/project-runtime/list/list.go

| 🇺🇸 English |        change style      |
| 🇨🇳 中文    |          修改样式    |

refactor(cp-deploy): change style

---

modules/dop/component-protocol/scenarios/code-coverage.yml
modules/dop/component-protocol/scenarios/test-report.yml
providers/component-protocol/issueFilter/filterset.go
providers/component-protocol/issueFilter/provider.go

Fix issueFilter default states, return all components
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=282047&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMDczIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG)
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=282000&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMDczIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG)
/assign @sfwn 
| …

fix: Fix issueFilter default states, return all components

---

conf/monitor/diagnotor-agent/diagnotor-agent.yaml
modules/core/monitor/diagnotor/agent/bootstrap/bootstrap.go
modules/core/monitor/diagnotor/agent/process.go
modules/core/monitor/diagnotor/agent/provider.go
modules/core/monitor/diagnotor/controller/diagnotor.service.go
modules/core/monitor/diagnotor/controller/schedule.go
modules/openapi/api/apis/monitor/monitor_filemanager_upload.go

monitor diagnotor agent auto exit
| 🇺🇸 English |      monitor diagnotor agent auto exit        |
| 🇨🇳 中文    |       诊断 agent 自动退出处理       |

feat: monitor diagnotor agent auto exit

---

modules/pipeline/dbclient/op_pipeline_report.go

fix delete pipeline reports
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=282260&issueFilter__urlQuery=eyJ0aXRsZSI6InJlcG9ydOihqOaVsOaNruWkquWkmumcgOimgea4heeQhiIsInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1090&type=TASK)
| 🇺🇸 English | Fix the bug that delete pipeline reports             |
| 🇨🇳 中文    |  修复了pipeline reports太多没有清除            | …

fix: use `where` delete pipeline reports

---

modules/scheduler/executor/plugins/k8s/deployment.go
modules/scheduler/executor/plugins/k8s/deployment_test.go
pkg/parser/diceyml/diceyml.go
pkg/strutil/interpolate.go
pkg/strutil/interpolate_test.go

feat: dereference env
| 🇺🇸 English | Support to reference other env in some env value in erda.yml |
| 🇨🇳 中文    | 支持在 erda.yml 的某个环境变量中引用其他环境变量 |

feat: dereference env

---

modules/dop/component-protocol/components/project-runtime/list/list.go
modules/dop/component-protocol/components/project-runtime/list/list_test.go

| 🇺🇸 English |     change status         |
| 🇨🇳 中文    |       修改runtime状态    |

refactor(cp-project): change status

---

apistructs/cmp.go
modules/cmp/endpoints/cluster.go
modules/cmp/impl/clusters/add_edge_cluster.go
modules/cmp/impl/clusters/offline_edge_cluster.go
modules/cmp/impl/clusters/offline_test.go

| 🇺🇸 English | add precheck feature for cluster offline |
| 🇨🇳 中文    |  为机器下线添加 precheck 功能  |

feat: add precheck for cluster offline

---

.erda/migrations/config.yml

| 🇺🇸 English |       修复sql检查问题       |
| 🇨🇳 中文    |    fix the sql check          |

feat: ignore org_id deleted_at sql check befor 20220209

---

.erda/migrations/config.yml

| 🇺🇸 English |       ignore sql check for old files     |
| 🇨🇳 中文    |          忽略旧sql检查      |

feat: ignore org_id deleted_at sql check befor 20220215

---

modules/dop/services/autotest_v2/testplan_v2.go

remove the same name check of test plan updating
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOlsxMDkwLDc3Ml0sIm1lbWJlciI6WyIxMDAxMjYxIl19&id=274164&iterationID=772&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |   remove the same name check of test plan updating           |
| 🇨🇳 中文    |    取消同名验证          |

fix(dop): remove the same name check of test plan updating

---

modules/dop/component-protocol/components/project-runtime/list/list.go

| 🇺🇸 English |   show kvinfo without service           |
| 🇨🇳 中文    |     service不存在时  展示kvinfo         |

fix(cp-project): show kvinfo without service

---

go.mod
go.sum

fix: update infra to fix cmp component not found
| 🇺🇸 English | fix: update infra to fix cmp component not found |
| 🇨🇳 中文    | 更新erda-infra，修复cmp组件化协议中custom类型组件找不到的问题 |

fix: update infra

---

modules/dop/services/cdp/cdp.go
pkg/erda-configs/i18n/notify_item.yml

modify pipeline notify markdown
reduce pipeline failed logs
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOlsxMDkwXSwibWVtYmVyIjpbIjEwMDEyMDUiXX0%3D&id=282901&iterationID=1090&pId=0&type=BUG)
| 🇺🇸 English | Fix the bug that pipeline notify too long             |
| 🇨🇳 中文    |    修复了流水线通知内容过长          |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/maste …

fix: pipeline notify content

---

modules/scheduler/executor/plugins/k8s/deployment.go
modules/scheduler/executor/plugins/k8s/deployment_test.go
modules/scheduler/executor/plugins/k8s/k8s.go

feat: add root domin env to runtime
| 🇺🇸 English |     add root domin env to runtime         |
| 🇨🇳 中文    |       runtime增加root_domain的环境变量      |

feat: add root domin env to runtime

---

modules/dop/component-protocol/components/project-runtime/advanceFilter/advanceFilter.go
modules/dop/component-protocol/components/project-runtime/list/list.go

| 🇺🇸 English |      sync render list with filter param        |
| 🇨🇳 中文    |       定期刷新增加查询条件       |

fix(cp-project): sync render list with filter param

---

conf/eventbox/eventbox.yaml

modify eventbox.yaml
| 🇺🇸 English |       modify eventbox.yaml       |
| 🇨🇳 中文    |      修改eventbox中的messenger为core-service        |

fix: modify eventbox.yaml

---

modules/scheduler/impl/servicegroup/servicegroup.go

Compatibility for old service volumes and new service volume defines
Bugfix： Fix the bug that can not compatible with old volume defines
| 🇺🇸 English |      Compatibility for old service volumes and new service volume defines        |
| 🇨🇳 中文    |      Compatibility for old service volumes and new service volume defines        |

fix: fix compatibility for old service volumes

---

pkg/apitestsv2/netportal.go
pkg/http/httpclientutil/urlwrap.go

Add the scheme to the header when the automation test agent requests
| 🇺🇸 English |    Add the scheme to the header when the automation test agent requests       |
| 🇨🇳 中文    |       自动化测试代理请求的时候将 scheme 加入到 header 中      |

feat: Add the scheme to the header when the automation test agent requests

---

modules/orchestrator/services/deployment/deployment_context.go

Fix compatible for old volume
Bugfix： Fix the bug that   compatible for old volume（兼容 service 的 volume 定义支持通过 storage 和 path 定义，并使用已经存在的卷，不创建 PVC）
| 🇺🇸 English |       Fix the bug that   compatible for old volume       |
| 🇨🇳 中文    |       兼容 service 的 volume 定义支持通过 storage 和 path 定义，并使用已经存在的卷，不创建 PVC       |

fix: fix compatible for old volume

---

modules/dop/component-protocol/components/project-runtime/advanceFilter/advanceFilter.go

| 🇺🇸 English |       show filter state        |
| 🇨🇳 中文    |       展示filter筛选状态       |

fix(cp-project): show filter state

---

.erda/migrations/pipeline/20220217-pipeline-task-add-index.sql

add index to table pipeline_tasks
/assign @sfwn 
| 🇺🇸 English |      add index to table pipeline_tasks        |
| 🇨🇳 中文    |      表pipeline_tasks增加索引        |

fix(pipeline): add index to table pipeline_tasks

---

conf/msp/i18n/cp/msp-alert-event-detail.yaml

| 🇺🇸 English |       fix i18n config       |
| 🇨🇳 中文    |     修复 i18n         |

fix: fix i18n

---

.erda/migrations/msp/20220217-alert_event_suppress.sql
modules/core/monitor/alert/alert-apis/alert.service.go
modules/msp/apm/alert/components/msp-alert-event-list/common/constants.go

| 🇺🇸 English |       add dbmigration       |
| 🇨🇳 中文    |      添加dbmigration        |

fix: db migration

---

modules/messenger/notify/db/alert_notify_index.go
modules/messenger/notify/db/notify_history.go
modules/messenger/notify/notify.service.go
modules/msp/apm/alert/components/common/constants.go
modules/msp/apm/alert/components/msp-notify-detail/common/utils.go
modules/msp/apm/alert/components/msp-notify-detail/eventStatusInfo/model.go
modules/msp/apm/alert/components/msp-notify-detail/eventStatusInfo/provider.go
modules/msp/apm/alert/components/msp-notify-list/table/provider.go
modules/msp/apm/alert/components/provider.go

Get notifiy details in msp module
| 🇺🇸 English |       Get notifiy details in msp module       |
| 🇨🇳 中文    |       在msp模块中获取通知组详情       |

fix: Get notifiy details in msp module

---

modules/dop/services/environment/env_config.go

fix: update file type config error
| 🇺🇸 English |      fix: update file type config error        |
| 🇨🇳 中文    |      修复更新文件类型的配置参数类型错误问题        |

fix: update file type config error

---

go.mod
go.sum
modules/dop/component-protocol/components/project-runtime/list/list.go

| 🇺🇸 English |       change serverData icon from string to struct       |
| 🇨🇳 中文    |    批量操作serverData icon 转为结构体     |

fix(cp-deploy): change serverData icon from string to struct

---

modules/hepa/services/runtime_service/impl/impl.go
modules/hepa/services/runtime_service/impl/impl_test.go
pkg/parser/diceyml/basic_validate_visitor.go
pkg/parser/diceyml/basic_validate_visitor_test.go

endpoint support platform placeholder
| 🇺🇸 English |  endpoint support platform placeholder            |
| 🇨🇳 中文    |   ep 支持平台级占位符           |

feat: endpoint support platform placeholder

---

apistructs/gittar.go
bundle/gittar.go
conf/dop/i18n/cp/scenarios/app-list-all.yaml
modules/admin/services/workbench/app.go
modules/dop/component-protocol/components/app-list-all/list/app.go
modules/dop/component-protocol/components/app-list-all/list/provider.go
modules/gittar/api/merge.go
modules/gittar/initialize.go
modules/gittar/models/merge_request.go

App list item show open merge requests count
/assign @sfwn 
| 🇺🇸 English |    App list item show open merge requests count          |
| 🇨🇳 中文    |      列表中的进行中的合并请求数        |

feat: App list item show open merge requests count

---

modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/stagesOperations/apiEditorDrawer/apiEditorContainer/apiEditor/render.go
modules/dop/component-protocol/components/issue-gantt/filter/model.go
modules/dop/component-protocol/components/issue-gantt/filter/provider.go
modules/dop/services/issue/issue.go

…lid type
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls3NzIsMTA5MF0sIm1lbWJlciI6WyIxMDAxMDczIl19&id=284391&iterationID=1090&pId=0&type=BUG)
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls3NzIsMTA5MF0sIm1lbWJlciI6WyIxMDAxMDczIl19&id=283444&iterationID=1090&pId=0&type=BUG)
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls3NzIsMTA5MF0sIm1lbWJlciI6WyIxMDAxMDczIl19&id=283091&iterationID=1090&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |  Issue gantt filter condition key update, issue …

fix: Issue gantt filter condition key update, issue stage stream skip invalid type

---

modules/core/monitor/alert/alert-apis/adapt/alert.go
modules/core/monitor/alert/alert-apis/adapt/alert_route.go
modules/msp/apm/alert/alert.go

modify record url
| 🇺🇸 English |       modify record url       |
| 🇨🇳 中文    |      修改查看记录的路径        |

fix: modify record url

---

modules/pipeline/dbclient/op_pipeline.go

Solve the problem of index hit failure caused by forced indexing
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMDkwXSwiYXNzaWduZWUiOlsiMTAwMTI2MSJdfQ%3D%3D&id=283779&iterationID=1090&pId=0&type=TASK)
/assign @sfwn 
| 🇺🇸 English |     Solve the problem of index hit failure caused by forced indexing         |
| 🇨🇳 中文    |       解决强制索引引起的索引命中失败问题       | …

fix(dop,pipeline): Solve the problem of index hit failure caused by forced indexing

---

pkg/database/sqlparser/migrator/migrator.go
pkg/database/sqlparser/migrator/scripts.go
pkg/database/sqlparser/migrator/tabledef.go

Stop judging destructive statements
| 🇺🇸 English | Stop judging destructive statements |
| 🇨🇳 中文    | Sandbox 中不再判断 SQL 语句是否为破坏性语句，对 SQL 的判断仅放在 SQL Lint 中 |

feat: Stop judging destructive statements

---

modules/dop/component-protocol/components/issue-gantt/gantt/render.go

Fix issue gantt return full data
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOls3NzIsNjgwLDg4MSw4ODMsMTA2OSwxMDkwXSwiYXNzaWduZWUiOlsiMTAwMTA3MyJdfQ%3D%3D&id=285100&iterationID=1090&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |  Fix issue gantt return full data            |
| 🇨🇳 中文    |    修复甘特图全量返回数据          |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTR …

fix: Fix issue gantt return full data

---

apistructs/deployment_order.go
conf/orchestrator/orchestrator.yaml
modules/orchestrator/dbclient/deployment_order.go
modules/orchestrator/endpoints/deployment_order.go
modules/orchestrator/initialize.go
modules/orchestrator/provider.go
modules/orchestrator/services/deployment/deployment_context.go
modules/orchestrator/services/deployment_order/deployment_order_create.go
modules/orchestrator/services/deployment_order/deployment_order_cron.go
modules/orchestrator/services/deployment_order/deployment_order_cron_test.go
modules/orchestrator/services/deployment_order/deployment_order_get.go
modules/orchestrator/services/deployment_order/deployment_order_get_test.go
modules/orchestrator/services/deployment_order/deployment_order_render.go
modules/orchestrator/services/runtime/runtime.go

deployment order support show batch status
| 🇺🇸 English |   deployment order support show batch status           |
| 🇨🇳 中文    |   部署单支持分批状态显示           |

feat: deployment order support show batch status

---

modules/pipeline/pipengine/reconciler/cron_strategy_compensator.go

Fixed the problem that the scheduled task did not execute the compensation policy and could not get cronid from etcd
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=283779&issueFilter__urlQuery=eyJhc3NpZ25lZUlEcyI6WyIxMDAxMjYxIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1090&type=TASK)
| 🇺🇸 English |       Fixed the problem that the scheduled task did not execute the compensation policy and could not get cronid from etcd       |
| 🇨🇳 中文    |       修复定时任务未执行补偿策略无法从 etcd 获取 cronid 的问题       |

fix: Fixed the problem that the scheduled task did not execute the compensation policy and could not get cronid from etcd

---

modules/core-services/services/filesvc/svc.go

core-services add log for kms
| 🇺🇸 English |    core-services add log for kms          |
| 🇨🇳 中文    |     core-services 增加 kms 相关日志         |

feat(core-services): core-services add log for kms

---

conf/scheduler/i18n/log-trans.yaml

| 🇺🇸 English |    fix i18n param           |
| 🇨🇳 中文    |   i18n 参数           |

fix(deploy): fix i18n param

---

erda.yml
pipeline.yml

switch mysql to rds
/assign @sfwn 
| 🇺🇸 English |     switch mysql to rds for intergration env         |
| 🇨🇳 中文    |      集成环境切换到 rds        |

ci: switch mysql to rds

---

pkg/kms/kmscrypto/define.go
pkg/kms/kmscrypto/rsa_2048_4096.go
pkg/kms/kmscrypto/util.go
pkg/kms/kmstypes/api_key.go
pkg/kms/kmstypes/key.go
pkg/kms/plugins/dicekms/kms.go
pkg/kms/stores/etcd/store.go

kms support rsa 4096 3072 2048
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOlsxMDkwXSwibWVtYmVyIjpbIjEwMDEyMDUiXX0%3D&id=282915&iterationID=1090&pId=0&type=TASK)
| 🇺🇸 English | Support kms rsa 4096 3072 2048            |
| 🇨🇳 中文    |   kms的rsa           |

feat: kms support rsa 4096 3072 2048

---

modules/gittar/helper/git_cmd.go

Add error output log to git cmd
/assign @sfwn 
| 🇺🇸 English |     Add error output log to git cmd         |
| 🇨🇳 中文    |      git cmd增加错误输出        |

feat(gittar): add error output log to git cmd

---

pipeline.yml

custom migration username
/assign @sfwn 
| 🇺🇸 English |       custom migration username       |
| 🇨🇳 中文    |       自定义migration用户名       |

ci: custom migration username

---

cmd/monitor/extensions/slb-metric/main.go
conf/monitor/extensions/slb-metric/slb-metric.yaml
modules/extensions/loghub/sls-log-to-metric/consumer.go
modules/extensions/loghub/sls-log-to-metric/consumer_manager.go
modules/extensions/loghub/sls-log-to-metric/provider.go

sls log to metric
| 🇺🇸 English |      sls-log to metric        |
| 🇨🇳 中文    |      sls日志直接转指标        |

feat: sls-log-to-metric

---

erda.yml

fix: add dicehub port env in erda.yml
| 🇺🇸 English | fix: add dicehub port env in erda.yml |
| 🇨🇳 中文    | 在erda.yml中添加dicehub的端口环境变量  |
Need cherry-pick to release/1.6-alpha.4

fix: add dicehub port env in erda.yml

---

modules/dop/component-protocol/components/project-runtime/advanceFilter/advanceFilter.go
modules/dop/component-protocol/components/project-runtime/cleanData/render.go
modules/dop/component-protocol/components/project-runtime/list/list.go

| 🇺🇸 English |          add filter init param    |
| 🇨🇳 中文    |       增加过滤器初始化参数     |

feat(cp-project): add filter init param

---

modules/msp/apm/alert/components/msp-alert-event-detail/event-history-table/provider.go
modules/msp/apm/alert/components/msp-alert-event-detail/event-overview-info/command.go
modules/msp/apm/alert/components/msp-alert-event-list/table/provider.go
modules/msp/apm/alert/components/msp-alert-overview/alert-event-charts/groupby-level-count/provider.go
modules/msp/apm/alert/components/msp-alert-overview/alert-event-charts/groupby-type-count/provider.go
modules/msp/apm/alert/components/msp-alert-overview/composite-header/cards/statistics.go

| 🇺🇸 English |        fix bug that alert events still display when  suppressed    |
| 🇨🇳 中文    |       修复被屏蔽的告警事件依然展示在告警事件历史的问题      |

fix: exclude suppressed alert events when query

---

pkg/database/sqlparser/migrator/db.go
pkg/database/sqlparser/snapshot/error.go

feat: use default character set utf8 in sandbox
| 🇺🇸 English |use default character set utf8 in sandbox |
| 🇨🇳 中文    | Migration 沙盒数据库中默认使用 character set utf8 |

feat: use default character set utf8 in sandbox

---

.erda/pipelines/daily-deploy.yml

add daily deploy pipeline
| 🇺🇸 English |     add daily deploy pipeline         |
| 🇨🇳 中文    |      增加日部署集成的流水线        |

ci: add daily deploy pipeline

---

modules/dop/component-protocol/components/project-runtime/list/list.go

| 🇺🇸 English |     wrong param when get my apps         |
| 🇨🇳 中文    |       获取app参数错误       |

refactor(cp-project): wrong param when get my apps

---

.erda/msg.jsonnet
.erda/pipelines/daily-deploy.yml

add ding bot notify
| 🇺🇸 English |    add ding bot notify          |
| 🇨🇳 中文    |     增加日构建钉钉通知         |

ci: add ding bot notify

---

apistructs/deployment_order.go
modules/orchestrator/services/deployment_order/deployment_order_create.go
modules/orchestrator/services/deployment_order/deployment_order_create_test.go
modules/orchestrator/services/deployment_order/deployment_order_get.go
modules/orchestrator/utils/parse.go
modules/orchestrator/utils/parse_test.go

deploy without branch from dice-action
| 🇺🇸 English |   deploy without branch from dice-action           |
| 🇨🇳 中文    |    action 支持通过流水线部署没有分支概念的runtime          |

feat: deploy without branch from dice-action

---

modules/dop/component-protocol/components/app-list-all/tabs/render.go
modules/dop/component-protocol/components/project-pipeline/common/vars.go

Modify the default displayed tab of app and pipeline
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMDkwXSwiYXNzaWduZWUiOlsiMTAwMTI2MSJdfQ%3D%3D&id=286092&iterationID=1090&pId=0&type=TASK)
| 🇺🇸 English |     Modify the default displayed tab of app and pipeline         |
| 🇨🇳 中文    |        修改应用和流水线默认展示的tab      |
/cherry-pick release/1.6-alpha.4 …

feat(dop): Modify the default displayed tab of app and pipeline

---

conf/dop/i18n/cp/scenarios/release-manage.yaml
modules/dop/component-protocol/components/release-manage/releaseFilter/model.go
modules/dop/component-protocol/components/release-manage/releaseFilter/render.go
modules/dop/component-protocol/components/release-manage/releaseFilter/render_test.go
modules/dop/component-protocol/components/release-manage/releaseTable/model.go
modules/dop/component-protocol/components/release-manage/releaseTable/render.go

1. change aggregate button to list
2. modify the text of aggregate list
3. fix the bug that the aggregate state disappeared when change from formal to all
4. fix UTC time in release list
| 🇺🇸 English | 1. change aggregate button to list; 2. modify the text of aggregate list; 3. fix the bug that the aggregate state disappeared when change from formal to all; 4. fix UTC time in release list |
| 🇨🇳 中文    | 1. 将分支聚合按钮改为下拉列表；2. 修改分支聚合文案；3. 修复分支聚合状态在从正式或非正式页面切换到全部页面时消失的问题；4. 修复在列表中显示UTC时间的问题|
Need cherry-pick to release/1.6-alpha.4

fix: release aggregate by branch

---

modules/core/monitor/alert/alert-apis/adapt/alert_route.go
modules/msp/member/mebmer.service.go

modify the display_url path
| 🇺🇸 English |       modify the display_url path       |
| 🇨🇳 中文    |       修改查看详情的跳转路径       |

fix: modify the display_url path

---

modules/orchestrator/scheduler/executor/plugins/k8s/deployment.go
modules/orchestrator/scheduler/executor/plugins/k8s/deployment_test.go
pkg/strutil/interpolate.go
pkg/strutil/interpolate_test.go

| 🇺🇸 English | Replace "recursion" with "loop" to ensure exit |
| 🇨🇳 中文    | 修复渲染环境变量可能的 panic 问题，由递归改为循环且确保能退出 |

feat: Replace "recursion" with "loop" to ensure exit

---

modules/msp/member/mebmer.service.go

modify add member check permission
| 🇺🇸 English |       modify add member check permission       |
| 🇨🇳 中文    |        修改成员管理      |

fix: modify add member check permission

---

modules/orchestrator/services/deployment_order/deployment_order_cron.go

deployment order cron panic error
| 🇺🇸 English |   deployment order cron panic error           |
| 🇨🇳 中文    |    部署单分批部署推进 panic 错误          |

fix: deployment order cron panic error

---

modules/dop/component-protocol/components/project-runtime/advanceFilter/advanceFilter.go

| 🇺🇸 English |    init filter          |
| 🇨🇳 中文    |   初始化过滤器           |

fix(cp-project): init filter

---

.erda/msg.jsonnet
.erda/pipelines/daily-deploy.yml

remove some mirrors
| 🇺🇸 English |   remove some mirrors           |
| 🇨🇳 中文    |     移除部分 mirror         |

ci: remove some mirrors

---

api/proto-go/core/monitor/alert/client/client.go
api/proto-go/core/monitor/alert/pb/alert.form.pb.go
api/proto-go/core/monitor/alert/pb/alert.http.pb.go
api/proto-go/core/monitor/alert/pb/alert.json.pb.go
api/proto-go/core/monitor/alert/pb/alert.pb.go
api/proto-go/core/monitor/alert/pb/alert.validator.pb.go
api/proto-go/core/monitor/alert/pb/alert_grpc.pb.go
api/proto/core/monitor/alert/alert.proto
cmd/monitor/monitor/main.go
conf/monitor/monitor/monitor.yaml
modules/cmp/alert_monitor_test.go
modules/core/monitor/alert/alert-apis/alert.service.go
modules/core/monitor/alert/alert-apis/db/alert_event.go
modules/core/monitor/alert/jobs/unrecover-alerts/provider.go
modules/msp/apm/alert/alert_monitor_test.go
modules/msp/apm/alert/components/msp-alert-overview/common/util.go
modules/msp/apm/alert/components/msp-alert-overview/composite-header/unrecover-alert-chart/model.go
modules/msp/apm/alert/components/msp-alert-overview/composite-header/unrecover-alert-chart/provider.go

| 🇺🇸 English |      Fix  unrecover alert count error        |
| 🇨🇳 中文    |       修复未恢复告警数错误的问题       |

fix: unrecover alert count error

---

modules/dicehub/extension/action.go
modules/dicehub/extension/source.go

Sync action updates all fields
| 🇺🇸 English |     Sync actions updates all fields         |
| 🇨🇳 中文    |        同步action更新所有字段      |
/cherry-pick release/1.6-alpha.4

fix(dop,dicehub): Sync actions updates all fields

---

modules/dop/component-protocol/components/project-runtime/common/common.go
modules/dop/component-protocol/components/project-runtime/common/common_test.go
modules/dop/component-protocol/components/project-runtime/list/list.go

| 🇺🇸 English |     ignore name filter case and space         |
| 🇨🇳 中文    |    忽略名称过滤器的大小写和空格          |

refactor(cp-project): ignore name filter case and space

---

modules/dop/component-protocol/components/project-pipeline/myPage/pageHeader/pipelineTabs/render.go

Solve the problem of tab switching when filter event trigger
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTE1LDEwOTBdLCJhc3NpZ25lZSI6WyIxMDAxMjYxIl19&id=288025&iterationID=1115&pId=0&type=BUG)
| 🇺🇸 English |       Solve the problem of tab switching when filter event trigger       |
| 🇨🇳 中文    |       解决filter事件tab切换问题       | …

fix(dop): Solve the problem of tab switching when filter event trigger

---

modules/pipeline/providers/definition/pipeline_definition.go

git push --set-upstream origin feature/dop-pipeline-name-check
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTE1LDEwOTBdLCJhc3NpZ25lZSI6WyIxMDAxMjYxIl19&id=287548&iterationID=1090&pId=0&type=BUG)
| 🇺🇸 English |      Solve the problem of Chinese character length judgment        |
| 🇨🇳 中文    |        解决中文字符长度判断问题      | …

fix(dop,pipeline): Solve the problem of Chinese character length judgment

---

conf/dop/i18n/cp/scenarios/release-manage.yaml
modules/dicehub/release/db/release.go
modules/dop/component-protocol/components/release-manage/releaseFilter/render.go
modules/dop/component-protocol/components/release-manage/releaseTable/render.go

fix: search release by version or releaseID
| 🇺🇸 English | fix: search release by version or releaseID |
| 🇨🇳 中文    | 制品筛选搜索框改为按照版本或ID搜索 |
Need cherry-pick to release/2.0

fix: search release by version or releaseID

---

modules/gittar/helper/git_cmd.go
modules/gittar/helper/git_cmd_test.go
modules/gittar/helper/git_protocol.go
modules/gittar/models/push_event.go

- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=287033&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDA2LDQ0MDddfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1115&type=TASK)
/assign @sfwn 
| 🇺🇸 English |      update push event and add create pipeline link to remote        |
| 🇨🇳 中文    |      修复preReceiveHook问题，remote增加link信息       |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRI …

feat(dop,gittar): update preReceiveHook and add create pipeline link to remote

---

apistructs/audits.go
modules/dicehub/endpoints/endpoints.go
modules/dicehub/endpoints/release_rule.go
modules/dicehub/service/apierrors/errors.go
modules/dicehub/service/release_rule/release_rule.go
modules/dop/component-protocol/components/release-manage/releaseFilter/render.go
modules/dop/component-protocol/components/release-manage/releaseTable/render.go

feat: add audit for releaseRule
| 🇺🇸 English | feat: add audit for releaseRule |
| 🇨🇳 中文    | 为制品规则添加审计 |

feat: add audit for releaseRule

---

modules/gittar/api/repo.go
modules/gittar/pkg/gitmodule/repo_branch.go

Create event box when new branch is created
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTE1XSwiYXNzaWduZWUiOlsiMTAwMTI2MSJdfQ%3D%3D&id=287036&iterationID=1115&pId=282942&type=TASK)
/assign #sfwn 
| 🇺🇸 English |     Create event box when new branch is created         |
| 🇨🇳 中文    |        创建新分支后发送事件      |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md …

feat(dop,gittar): Create event box message when new branch is created

---

conf/monitor/log-service/log-service.yaml

| 🇺🇸 English |       fix log-service conf error       |
| 🇨🇳 中文    |      修复 log-service 配置文件错误        |

fix: log-service conf

---

modules/dop/component-protocol/components/project-runtime/advanceFilter/advanceFilter.go
modules/dop/component-protocol/components/project-runtime/list/list.go

| 🇺🇸 English |     add init url          |
| 🇨🇳 中文    |     初始化url         |

fix(cp-project): add init url

---

conf/dop/i18n/cp/scenarios/app-runtime.yaml
conf/openapi/openapi.yaml
modules/dop/component-protocol/components/app-runtime/cleanData/model.go
modules/dop/component-protocol/components/app-runtime/cleanData/render.go
modules/dop/component-protocol/components/app-runtime/common/common.go
modules/dop/component-protocol/components/app-runtime/common/common_test.go
modules/dop/component-protocol/components/app-runtime/list/list.go
modules/dop/component-protocol/components/app-runtime/list/list_test.go
modules/dop/component-protocol/components/app-runtime/page/page.go
modules/dop/component-protocol/components/app-runtime/scenario.go
modules/dop/component-protocol/scenarios/app-runtime.yml
modules/orchestrator/dbclient/runtime.go
modules/orchestrator/endpoints/runtime.go
modules/orchestrator/services/runtime/runtime.go

| 🇺🇸 English |    add app deploy component protocol          |
| 🇨🇳 中文    |      增加应用级部署组件化        |

feat(cp-app): add app deploy component protocol

---

modules/orchestrator/services/deployment/deployment_context.go

fsm request scheduler update servicegroup remove loop
result:
| 🇺🇸 English | fsm request scheduler update servicegroup remove loop             |
| 🇨🇳 中文    |   请求调度器更新 servicegroup 取消重试调用           |

fix: fsm request scheduler update servicegroup remove loop

---

modules/dop/component-protocol/components/project-runtime/list/list.go

| 🇺🇸 English |        filter by name |
| 🇨🇳 中文    |       根据名称过滤        |

fix(cp-project): filter by name

---

apistructs/issue_related.go
modules/dop/dao/issue.go
modules/dop/dao/issue_issue_relation.go
modules/dop/endpoints/issue_related.go
modules/dop/services/issuerelated/issue_related.go

Batch create issue relations, get issue relations by all types
/assign @sfwn 
| 🇺🇸 English |  Batch create issue relations, get issue relations by all types            |
| 🇨🇳 中文    |   批量创建事项关联关系           |

feat: Batch create issue relations, get issue relations by all types

---

modules/dop/services/pipeline/pipeline.go

dop `cicd` remove workspace label
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=274388&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDA4XSwiYXNzaWduZWVJRHMiOlsiMTAwMTA1NSJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1115&type=TASK)
| 🇺🇸 English |dop `cicd` remove workspace label              |
| 🇨🇳 中文    |    cicd创建流水线去除workspace的标签          | …

fix(dop): dop remove workspace label

---

modules/orchestrator/endpoints/runtime.go

| 🇺🇸 English |      count runtime by app        |
| 🇨🇳 中文    |    根据app计算runtime       |

fix(cp-app): count runtime by app

---

modules/gittar/auth/auth.go
modules/gittar/helper/git_cmd.go
modules/gittar/pkg/gitmodule/repo.go

Add a create pipeline link to the push remote information
Temporarily add a link to the listing page
/assign @sfwn 
| 🇺🇸 English |        Add a create pipeline link to the push remote information      |
| 🇨🇳 中文    |      push remote返回信息增加创建流水线链接        |

feat(gittar):  Add a create pipeline link to the push remote information

---

modules/dop/component-protocol/components/all.go
modules/dop/component-protocol/components/app-runtime/advanceFilter/advanceFilter.go
modules/dop/component-protocol/components/app-runtime/advanceFilter/advanceFilter_test.go
modules/dop/component-protocol/components/app-runtime/filterContainer/filterContainer.go
modules/dop/component-protocol/components/app-runtime/list/list.go
modules/dop/component-protocol/components/app-runtime/list/list_test.go
modules/dop/component-protocol/components/app-runtime/scenario.go
modules/dop/component-protocol/scenarios/app-runtime.yml

| 🇺🇸 English |         app deployment with cp     |
| 🇨🇳 中文    |      应用级部署中心        |

refactor(cp-app): app deployment with cp

---

modules/dop/component-protocol/components/project-runtime/list/list.go

| 🇺🇸 English |       get list state when initializing       |
| 🇨🇳 中文    |   list 组件获取初始化状态           |

fix(cp-dc): get list state when initializing

---

modules/dop/component-protocol/components/app-runtime/advanceFilter/advanceFilter.go
modules/dop/component-protocol/components/app-runtime/list/list.go
modules/dop/component-protocol/components/project-runtime/list/list.go

| 🇺🇸 English |    init param of page          |
| 🇨🇳 中文    |      初始化增加列表参数        |

fix(cp-deploy): init param of page

---

conf/eventbox/eventbox.yaml
modules/eventbox/subscriber/common.go
modules/eventbox/subscriber/dingding/dingding.go
modules/eventbox/subscriber/dingtalk_worknotice/dingtalk_worknotice.go
modules/eventbox/subscriber/email/email.go
modules/eventbox/subscriber/mbox/mbox.go
modules/eventbox/subscriber/sms/sms.go
modules/eventbox/subscriber/vms/vms.go

fix the bug of eventbox null pointer exception
| 🇺🇸 English |       fix the bug of eventbox null pointer exception       |
| 🇨🇳 中文    |      eventbox存储通知空指针异常       |

fix: fix the bug of eventbox null pointer exception

---

modules/dop/component-protocol/components/issue-gantt/filter/provider.go

Handle fixed iteration value in issue gantt filter operation
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTMxLDExNDYsMTExNSwxMDkwLDEwNjksODgzXSwiYXNzaWduZWUiOlsiMTAwMTA3MyJdfQ%3D%3D&id=289246&iterationID=1115&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |  Fix issue gantt filter under iteration            |
| 🇨🇳 中文    |   修复甘特图 迭代下筛选           | …

fix: Handle fixed iteration value in issue gantt filter operation

---

modules/gittar/api/repo.go

/assign @sfwn 
| 🇺🇸 English |     Solve the problem of incorrect branch name when sending git push event        |
| 🇨🇳 中文    |        解决发送git push事件分支名不正确问题      |

fix(gittar): Solve the problem of incorrect branch name when sending git push event

---

modules/dop/component-protocol/components/app-runtime/list/list.go
modules/dop/component-protocol/components/app-runtime/list/list_test.go

| 🇺🇸 English |   change app target           |
| 🇨🇳 中文    |    修改app target          |

    fix(cp-app): change app target

---

apistructs/manual_review.go
bundle/review.go
conf/admin/i18n/cp/scenarios/personal-workbench.yaml
modules/admin/component-protocol/components/personal-workbench/messageList/approval.go
modules/admin/component-protocol/components/personal-workbench/messageList/messageList.go
modules/admin/component-protocol/components/personal-workbench/messageTabs/messageTabs.go
modules/core-services/services/manual_review/manual_review.go
pkg/arrays/arrays.go

Approval management setup in personal workstation
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMDkwLDExMTUsMTA2OSwxMTMxLDExNDZdLCJhc3NpZ25lZSI6WyIxMDAxMDczIl19&id=275130&iterationID=1115&pId=0&type=REQUIREMENT)
/assign @sfwn 
| 🇺🇸 English |    Approval management setup in personal workstation          |
| 🇨🇳 中文    |    个人工作台 审批          | …

feat: Approval management setup in personal workstation

---

modules/dop/component-protocol/components/app-runtime/list/list.go
modules/dop/component-protocol/components/project-runtime/list/list.go

| 🇺🇸 English |        init page params
|
| 🇨🇳 中文    |     初始化page 参数         |

    fix(cp-deploy): init page params

---

modules/eventbox/dispatcher/filters/lastfilter.go

eventbox close errsCh
| 🇺🇸 English |       eventbox close errsCh       |
| 🇨🇳 中文    |       eventbox关闭管道       |

fix: eventbox close errsCh

---

modules/orchestrator/initialize.go

Modify the error of 'xxx not found' check
| 🇺🇸 English |       Modify the error of 'xxx not found' check        |
| 🇨🇳 中文    |      修改xxx不存在错误判断        |
/cherry-pick release/2.0

fix(orchestrator): Modify the error of 'xxx not found' check

---

modules/admin/component-protocol/components/personal-workbench/workList/provider.go
modules/extensions/loghub/sls-import/product_rds.go
modules/openapi/component-protocol/scenarios/home-page-content/components/title/render.go

remove some useless code
| 🇺🇸 English | remove some useless code             |
| 🇨🇳 中文    |   删除几个无用的代码           |

fix: remove some useless code

---

conf/dop/i18n/cp/scenarios/project-runtime.yaml
modules/dop/component-protocol/components/project-runtime/advanceFilter/advanceFilter.go
modules/dop/component-protocol/components/project-runtime/advanceFilter/advanceFilter_test.go
modules/dop/component-protocol/components/project-runtime/common/common.go
modules/dop/component-protocol/components/project-runtime/list/list.go

| 🇺🇸 English |        add all involved app name in filter      |
| 🇨🇳 中文    |     增加已参与筛选项        |

refactor(cp-project): add all involved app name in filter

---

modules/core/monitor/alert/alert-apis/alert.service.go
modules/core/monitor/alert/alert-apis/db/alert.go
modules/core/monitor/alert/alert-apis/db/alert_event.go
modules/core/monitor/alert/jobs/unrecover-alerts/provider.go
modules/msp/apm/log-service/query/log.service.search.go

| 🇺🇸 English |       unrecover alert exclude disabled alert ids       |
| 🇨🇳 中文    |     未恢复告警数统计剔除已停用的告警策略         |
/cherry-pick release/2.0

fix: unrecover alert exclude disabled alert ids

---

.erda/migrations/config.yml
.erda/migrations/qa/20220305-testcase-desc-length.sql
apistructs/testcase.go
modules/dop/services/testcase/create.go
modules/dop/services/testcase/update.go

Increase size of test case desc column, add length validation
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTMxLDExNDYsMTExNSw0NjddLCJhc3NpZ25lZSI6WyIxMDAxMDczIl19&id=289724&iterationID=1115&pId=0&type=TASK)
/assign @sfwn 
| 🇺🇸 English |  Increase size of test case desc column, add length validation            |
| 🇨🇳 中文    |   增加测试用例描述长度并校验           | …

feat: Increase size of test case desc column, add length validation

---

modules/dop/dao/issue.go

Fix issue gantt parent query without matched children
/assign @sfwn 
| 🇺🇸 English |  Fix issue gantt parent query without matched children            |
| 🇨🇳 中文    |    修复甘特图查询          |

fix: Fix issue gantt parent query without matched children

---

modules/msp/apm/log-service/query/log.service.search.go

| 🇺🇸 English |     fix log query exception when click the last page         |
| 🇨🇳 中文    |    修复日志查询最后一页报错问题          |
Add comment like `/cherry-pick release/2.0` when this PR is merged.

fix: log query limit size to 10000

---

modules/dop/services/cdp/cdp.go

truncate failed task logs
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=282901&iterationID=1115&pId=0&type=BUG)
| 🇺🇸 English | Fix the bug that truncate failed task logs             |
| 🇨🇳 中文    |  修复流水线日志过长            |

fix: truncate failed task logs

---

modules/dop/dao/issue_issue_relation.go

- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=290235&issueFilter__urlQuery=eyJ0aXRsZSI6IuS6i%2BmhueivpuaDhSIsInN0YXRlcyI6WzQ0MTIsNDUzOCw0NDEzLDQ0MTQsNDQxNSw0NDE2XX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1115&type=BUG)
/assign @sfwn 
| 🇺🇸 English |  Fix issue relation repeat existence validation            |
| 🇨🇳 中文    |   修复事项关联关系重复校验           | …

fix: Fix issue relation repeat existence validation

---

modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeTaskTable/render.go

Automatic test plan execution list hidden refresh button
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=267961&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDA1NjAiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1115&type=BUG)
| 🇺🇸 English |        Automatic test plan execution list hidden refresh button      |
| 🇨🇳 中文    |       自动化测试计划执行列表隐藏刷新按钮       |

feat(openapi): Automatic test plan execution list hidden refresh button

---

apistructs/extension_test.go
apistructs/extention.go
bundle/dicehub.go
modules/dicehub/endpoints/extention.go
modules/pipeline/conf/conf.go
modules/pipeline/pkg/container_provider/container_instance_provider.go
modules/pipeline/pkg/container_provider/container_provider_test.go
modules/pipeline/services/extmarketsvc/define.go
modules/pipeline/services/extmarketsvc/list.go
modules/pipeline/services/pipelinesvc/create_v2.go
modules/pipeline/services/pipelinesvc/create_v2_test.go

pipeline support action custom eci disable label
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=288345&iterationID=1115&pId=0&type=TASK)
| 🇺🇸 English | pipeline support action custom eci disable label             |
| 🇨🇳 中文    |    pipeline支持action自定义是否禁止eci          | …

feat(pipeline): pipeline support action custom eci

---

modules/dop/providers/projectpipeline/service_impl.go
modules/pipeline/services/pipelinesvc/cron.go
modules/pipeline/services/pipelinesvc/run.go
pkg/parser/pipelineyml/define.go

Solve the problem that the state data is incorrect after the execution of the timing pipeline
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTMxLDEwOTAsMTExNV0sImFzc2lnbmVlIjpbIjEwMDEyNjEiXX0%3D&id=289092&iterationID=1115&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |      Solve the problem that the state data is incorrect after the execution of the timing pipeline        |
| 🇨🇳 中文    |      解决定时流水线执行后状态数据不正确问题        |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-p …

fix(dop,pipeline): Solve the problem that the data is incorrect after the execution of the cron pipeline

---

modules/orchestrator/scheduler/executor/plugins/k8s/deployment.go

Adjust ECI Pod fluent-bit sidecar container Env
/assign @sixther-dc @iutx @luobily 
Feature: Adjust ECI Pod fluent-bit sidecar container Env（调整 ECI Pod 的 fluent-bit 容器的环境变量）
| 🇺🇸 English |       Adjust ECI Pod fluent-bit sidecar container Env       |
| 🇨🇳 中文    |       调整 ECI Pod 的 fluent-bit 容器的环境变量       |

feat: adjust ECI Pod fluent-bit sidecar container Env

---

modules/dicehub/release/release.go
modules/dop/component-protocol/components/release-manage/releaseTable/render.go

fix: multiple latest release in one git branch
| 🇺🇸 English | fix: multiple latest release in one git branch |
| 🇨🇳 中文    | 修复同一个分支上有多个最新版制品的问题 |
Need cherry-pick to release/2.0

fix: multiple latest release in one git branch

---

modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sflink/flink.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sspark/k8sspark.go

spark and flink job on eci, sc specified error
before fix:
```shell
$ kubectl get po -n pipeline-10028077 -owide 
NAME                                          READY   STATUS      RESTARTS   AGE     IP          NODE                            NOMINATED NODE   READINESS GATES
pipeline-10028077.pipeline-task-11862-g82dv   0/1     Completed   0          4m31s   10.0.6.79   virtual-kubelet-cn-hangzhou-k   <none>           <none>
pipeline-task-11864-driver                    0/1     Completed   0          86s     10.0.6.80   virtual-kubelet-cn-hangzhou-k   <none>           <none>
$ kubectl get pvc -n pipeline-10028077
NAME                                      STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                   AGE …
```

fix: spark and flink job on eci, sc specified error

---

conf/msp/i18n/cp/msp-notify-list.yaml
modules/msp/apm/alert/components/msp-notify-list/configurableFilter/provider.go

notify filter to do internationalization
| 🇺🇸 English |      notify filter to do internationalization        |
| 🇨🇳 中文    |       通知筛选器做国际化       |

fix: notify filter to do internationalization

---

conf/dop/i18n/cp/scenarios/release-manage.yaml
modules/dop/component-protocol/components/release-manage/releaseTable/model.go
modules/dop/component-protocol/components/release-manage/releaseTable/render.go

fix: add formal tag for formal release
| 🇺🇸 English | fix: add formal tag for formal release |
| 🇨🇳 中文    | 在全部制品列表中为正式制品添加标签 |

fix: add formal tag for formal release

---

modules/msp/apm/trace/persist/consume.go

| 🇺🇸 English |       avoid nil reference panic on invalid span-metric data        |
| 🇨🇳 中文    |       避免遇到异常的span指标数据时引发panic异常       |

fix: avoid nil reference panic on invalid span-metric data

---

modules/openapi/component-protocol/scenarios/action/components/actionForm/action_form.go

OpenAPI search action spec close ymlformat
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=291087&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDA1NjAiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1115&type=BUG)
| 🇺🇸 English |      OpenAPI search action spec close ymlformat        |
| 🇨🇳 中文    |      openapi  搜索 action spec 关闭 ymlformat        |

fix(dop): OpenAPI search action spec close ymlformat

---

modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sflink/flink.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sjob/k8sjob.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sspark/k8sspark.go

idempotent create pvc
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=291365&iterationID=1115&pId=0&type=BUG)
| 🇺🇸 English |  Fix the bug that create pvc idempotent            |
| 🇨🇳 中文    |  修复了pipeline幂等地创建pvc            |

fix(pipeline): idempotent create pvc

---

pkg/database/sqllint/linters/base.go

rm useless print, which appear in cli
/assign @luobily @dspo 
| 🇺🇸 English |       remove needless output message       |
| 🇨🇳 中文    |       去除日志打印       |

fix: rm needless fmt

---

modules/oap/collector/common/util_test.go
modules/oap/collector/core/model/odata/buffer_test.go
modules/oap/collector/plugins/exporters/kafka/provider.go
modules/oap/collector/plugins/receivers/collector/post.http

fix pointer topic misuse
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTE1LDEwOTAsMTE0NiwxMTMxXSwiYXNzaWduZWUiOlsiMTAwMDMwMSJdLCJsYWJlbCI6WzE0NTVdfQ%3D%3D&id=291410&iterationID=1146&pId=0&type=TASK)
| 🇺🇸 English |       kafka[exporter] bugfix       |
| 🇨🇳 中文    |       kafka[exporter] bugfix       | …

fix: pointer mistake bugfix

---

modules/dop/component-protocol/components/release-manage/releaseFilter/provider.go

fix: remove false option in release aggregate operation
| 🇺🇸 English | fix: remove false option in release aggregate operation |
| 🇨🇳 中文    | 移除全部制品列表中只显示latest制品的”否“选项 |

fix: remove false option in release aggregate operation

---

api/proto-go/core/dicehub/release/pb/release.form.pb.go
api/proto-go/core/dicehub/release/pb/release.json.pb.go
api/proto-go/core/dicehub/release/pb/release.pb.go
api/proto-go/core/dicehub/release/pb/release.validator.pb.go
api/proto/core/dicehub/release/release.proto
modules/dicehub/release/provider.go
modules/dicehub/release/release.service.go
modules/dop/component-protocol/components/release-manage/releaseTable/render.go

feat: add addons in get project release response
| 🇺🇸 English | feat: add addons in get project release response  |
| 🇨🇳 中文    | 获取项目制品的接口中添加依赖的addon信息 |

feat: add addons in get project release response

---

apistructs/file_records.go
apistructs/gittar.go
apistructs/permission.go
apistructs/project.go
bundle/addon.go
bundle/gittar.go
bundle/project.go
bundle/release.go
go.sum
modules/dop/endpoints/endpoints.go
modules/dop/endpoints/project.go
modules/dop/initialize.go
modules/dop/services/apierrors/errors.go
modules/dop/services/project/export_package.go
modules/dop/services/project/import_package.go
modules/dop/services/project/project_package.go
modules/dop/services/testcase/file_records.go
modules/openapi/api/apis/dop/project_package_export.go
modules/openapi/api/apis/dop/project_package_import.go
modules/openapi/api/apis/dop/project_package_parse.go
pkg/erda-configs/permission/backend/sys/org/org.yml

apis for export/import package of project
/assign @luobily @chengjoey 
| 🇺🇸 English |      Support export/import project package in DevOps platform        |
| 🇨🇳 中文    |        实现/优化了 DevOps 平台的项目工程包导入导出      |

feat: export/import project-package

---

modules/orchestrator/scheduler/executor/plugins/k8s/k8s.go
modules/orchestrator/scheduler/executor/plugins/k8s/nodelabel.go
modules/orchestrator/scheduler/executor/plugins/k8s/statefulset.go

| 🇺🇸 English |       check quota       |
| 🇨🇳 中文    |         检查quota     |

refactor(orchestrator): check quota

---

modules/dop/component-protocol/components/release-manage/releaseTable/model.go
modules/dop/component-protocol/components/release-manage/releaseTable/render.go
modules/dop/component-protocol/components/release-manage/releaseTable/render_test.go

fix: alig the release list
| 🇺🇸 English | fix: alig the release list |
| 🇨🇳 中文    | 对齐制品制品列表 |

fix: alig the release list

---

modules/dop/component-protocol/scenarios/project-pipeline-exec-list.yml

add customerFilter rendering to pipeline exec list to ensure order of execution
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTE1LDEwOTAsMTEzMSwxMTQ2XSwiYXNzaWduZWUiOlsiMTAwMTI2MSJdfQ%3D%3D&id=291541&iterationID=1115&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |        add customerFilter rendering to pipeline exec list      |
| 🇨🇳 中文    |         增加rendering来确保执行顺序     | …

fix(dop): add customerFilter rendering to pipeline exec list

---

modules/core/monitor/alert/alert-apis/db/alert_expression.go
modules/core/monitor/expression/expression.service.go

delete LogMode
| 🇺🇸 English |      delete LogMode        |
| 🇨🇳 中文    |      删除sql打印        |

feat: delete LogMode

---

modules/dicehub/endpoints/release.go
modules/dicehub/release/release.service.go
modules/dop/component-protocol/components/release-manage/access/check.go
modules/dop/component-protocol/components/release-manage/releaseTable/render.go

fix: check project access if appliction was deleted when write release
| 🇺🇸 English | fix: check project access if appliction was deleted when write release |
| 🇨🇳 中文    | 修复应用被删除后该应用的制品删除失败的问题 |

fix: check project access if appliction was deleted when write release

---

conf/monitor/monitor/analyzer/metrics/apm/application_cache_service.json
conf/monitor/monitor/analyzer/metrics/apm/application_db_service.json
conf/monitor/monitor/analyzer/metrics/apm/application_http_service.json
conf/monitor/monitor/analyzer/metrics/apm/application_mq_service.json
conf/monitor/monitor/analyzer/metrics/apm/application_rpc_service.json
conf/monitor/monitor/analyzer/metrics/apm/jvm_service_node.json
conf/monitor/monitor/analyzer/metrics/apm/mobile_register_user_retention.json
conf/monitor/monitor/analyzer/metrics/apm/nodejs_service_node.json
conf/monitor/monitor/analyzer/metrics/apm/trace_tags.json

modify metric expression
| 🇺🇸 English |       modify metric expression       |
| 🇨🇳 中文    |       修改指标表达式配置文件       |

fix: modify metric expression

---

bundle/gittar.go
bundle/release.go
modules/dop/services/project/export_package.go
modules/dop/services/project/import_package.go
modules/dop/services/project/project_package.go

1. check project name
2. fix err resp from gittar
3. addon name with -
| 🇺🇸 English |    fix bug found by testing          |
| 🇨🇳 中文    |      修复自测发现的bug        |

fix: bugs in project package

---

pipeline.yml

build cli and upload to oss in daliy pipeline
/assign @luobily  @dspo @Effet 
| 🇺🇸 English |       build cli and upload to oss in daliy pipeline       |
| 🇨🇳 中文    |        每日回归中构建cli并上传oss      |

feat: build cli in daily pipeline

---

tools/cli/common/application.go

fix bug in cli
| 🇺🇸 English |    bugfix in cli func for applications      |
| 🇨🇳 中文    |       cli 里面获取应用函数 bugfix   |

fix: params in application func

---

modules/admin/component-protocol/components/personal-workbench/messageList/approval.go

Approval list is sorted in reverse chronological order
/assign @sfwn 
| 🇺🇸 English |   Approval list is sorted in reverse chronological order           |
| 🇨🇳 中文    |   审批列表按时间倒序排列           |

feat: Approval list is sorted in reverse chronological order

---

modules/dop/component-protocol/scenarios/project-pipeline.yml

add pipelineTabs rendering to pipeline list to ensure order of execution
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTMxLDExMTUsMTA5MCwxMTQ2XSwiYXNzaWduZWUiOlsiMTAwMTI2MSJdfQ%3D%3D&id=291717&iterationID=1146&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |   add pipelineTabs rendering to pipeline list to ensure order of execution       |
| 🇨🇳 中文    |       增加rendering来确保执行顺序       | …

fix(dop): add pipelineTabs rendering to pipeline list

---

modules/pipeline/providers/reconciler/legacy/reconciler/listen.go
modules/pipeline/providers/reconciler/legacy/reconciler/reconcile_data_process.go

move teardownPipeline to update status after reconcile
/assign @sfwn 
| 🇺🇸 English | Fix the bug that snippet pipeline task teardown             |
| 🇨🇳 中文    |    修复了嵌套流水线无法停止          |

fix(pipeline): snippet pipeline task teardown

---

modules/core/monitor/alert/alert-apis/alert.service.go
modules/core/monitor/alert/alert-apis/db/alert.go
modules/core/monitor/alert/alert-apis/db/alert_event.go
modules/core/monitor/alert/jobs/unrecover-alerts/provider.go

| 🇺🇸 English |       fix: unrecover alerts count error       |
| 🇨🇳 中文    |       修复未恢复告警数统计错误的问题       |
Add comment like `/cherry-pick release/2.0` when this PR is merged.

fix: unrecover alerts count error

---

modules/admin/component-protocol/components/personal-workbench/common/common.go
modules/admin/component-protocol/components/personal-workbench/workList/app.go

| 🇺🇸 English |        change target and param      |
| 🇨🇳 中文    | 修改deploy target 和参数          |

fix: cp-person change target and param

---

modules/pipeline/providers/engine/provider.go

pipengine register cluster hook until success when init
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=291694&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDA2LDQ0MDddfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1146&type=TASK)
| 🇺🇸 English |   pipengine register cluster hook until success when init            |
| 🇨🇳 中文    |   pipeline 引擎启动时注册集群相关 Hook 直至成功           | …

feat: pipengine register cluster hook until success when init

---

modules/dop/dao/issue_issue_relation.go
modules/dop/endpoints/issue_related.go
modules/dop/services/issue/issue.go

Issue connection changed to unidirectional relation
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTMxLDExMTUsMTE0Nl0sImFzc2lnbmVlIjpbIjEwMDEwNzMiXX0%3D&id=291693&iterationID=1115&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |  Issue connection changed to unidirectional relation            |
| 🇨🇳 中文    |     事项关联改为单向关系         |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/ma …

feat: Issue connection changed to unidirectional relation

---

modules/orchestrator/dbclient/addon_attachment.go
modules/orchestrator/endpoints/addon.go
modules/orchestrator/initialize.go
modules/orchestrator/services/addon/addon_attachment.go

Solve the addon attachment leak problem
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTMxLDExMTVdLCJhc3NpZ25lZSI6WyIxMDAxMjYxIl19&id=290232&iterationID=1115&pId=0&type=BUG)
| 🇺🇸 English |    Solve the addon attachment leak problem          |
| 🇨🇳 中文    |     解决addon attachment泄露问题         |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md) …

fix(orchestrator): Solve the addon attachment leak problem

---

modules/orchestrator/scheduler/executor/plugins/k8s/daemonset.go
modules/orchestrator/scheduler/executor/plugins/k8s/deployment.go
modules/orchestrator/scheduler/executor/plugins/k8s/k8s.go
modules/orchestrator/scheduler/executor/plugins/k8s/statefulset.go
modules/orchestrator/services/deployment/deployment_context.go

| 🇺🇸 English |    addon quota |
| 🇨🇳 中文    |      addon 配额        |

fix(orchestrator): addon quota

---

modules/pipeline/initialize.go
modules/pipeline/services/pipelinesvc/define.go

Pipeline cron refactoring causes fdp to create a pipeline panic and report an error
| 🇺🇸 English |       Pipeline cron refactoring causes fdp to create a pipeline panic and report an error       |
| 🇨🇳 中文    |      pipeline cron 重构导致 fdp 创建流水线 panic 报错        |

fix(pipeline): Fix fdp creation pipeline panic problem

---

.erda/migrations/cmdb/20220307-cluster.sql
apistructs/cluster.go
modules/cluster-manager/endpoints/cluster.go
modules/cluster-manager/model/model.go
modules/cluster-manager/services/cluster/cluster.go
modules/orchestrator/scheduler/executor/plugins/k8s/clusterinfo/clusterinfo.go
modules/orchestrator/scheduler/executor/plugins/k8s/k8s.go
modules/orchestrator/scheduler/instanceinfo/clusterInfo.go

| 🇺🇸 English |    insert cluster info to database          |
| 🇨🇳 中文    |        cluster info 插入数据库      |

feat(orchestrator): insert cluster info to database

---

apistructs/addon.go
apistructs/project_workspace_ability.go
modules/core-services/endpoints/project_workspace.go
modules/openapi/api/apis/orchestrator/orchestrator_addons_scale.go
modules/openapi/api/apis/orchestrator/orchestrator_runtimes_batch_scale.go
modules/orchestrator/dbclient/addon_attachment.go
modules/orchestrator/endpoints/server_handler.go
modules/orchestrator/services/addon/addon.go
tools/cli/cmd/config.go
tools/cli/cmd/config_delete.go
tools/cli/cmd/config_get.go
tools/cli/cmd/config_set.go
tools/cli/cmd/config_update.go
tools/cli/cmd/project_deployment.go
tools/cli/cmd/project_deployment_start.go
tools/cli/cmd/project_deployment_stop.go
tools/cli/command/context.go
tools/cli/common/project.go

erda-cli add config and  project-deployment command
Feature: Add erda-cli config/project-deployment command （erda-cli  添加 config 和 project-deployment 子命令 ）
| 🇺🇸 English |      Add erda-cli config/project-deployment command     |
| 🇨🇳 中文    |     erda-cli  添加 config 和 project-deployment 子命令      |

feat: erda-cli add config and  project-deployment command

---

modules/dop/component-protocol/components/release-manage/releaseTable/render.go

fix: referenced releases options error
| 🇺🇸 English | fix: referenced releases options error |
| 🇨🇳 中文    | 修复查看引用制品按钮跳转后勾选按分支聚合的问题 |

fix: referenced releases options error

---

erda.yml

remove expose for uc-adaptor
/assign @sfwn 
| 🇺🇸 English |    remove expose for uc-adaptor          |
| 🇨🇳 中文    |      移除 uc-adaptor 的公网暴露        |
nope

refactor: remove expose for uc-adaptor

---

modules/dop/component-protocol/components/auto-test-plan-list/components/filter/provider.go
modules/dop/component-protocol/components/common/urlQuery.go

add urlQuery params to auto test plan
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTQ2LDExMzEsMTExNSwxMTY0XSwiYXNzaWduZWUiOlsiMTAwMTI2MSJdfQ%3D%3D&id=246389&iterationID=1146&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |      add urlQuery param to auto test plan        |
| 🇨🇳 中文    |    自动化测试增加urlQuery          |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUT …

fix(dop): add urlQuery param to auto test plan

---

.erda/migrations/orchestrator/20220314-add-runtime-filetoken.sql
modules/orchestrator/dbclient/runtime.go
modules/orchestrator/services/deployment/deployment_context.go
modules/orchestrator/services/runtime/runtime.go

fix: token expire when runtime download env of file type
| 🇺🇸 English |        token expire when runtime download env of file type      |
| 🇨🇳 中文    |           修复runtime现在文件类型环境变量token过期问题   |

fix: token expire when runtime download env of file type

---

modules/pipeline/providers/reconciler/legacy/reconciler/define.go
modules/pipeline/providers/reconciler/legacy/reconciler/listen.go
modules/pipeline/providers/reconciler/legacy/reconciler/listen_test.go
modules/pipeline/providers/reconciler/legacy/reconciler/teardown.go

remove useless etcd listen code
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=290594&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDA2LDQ0MDddfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1146&type=TASK)
| 🇺🇸 English |  reconciler remove useless Etcd listen code            |
| 🇨🇳 中文    |  Reconciler 删除已经无用的 Etcd 监听代码            |

chore: reconciler remove useless etcd listen code

---

apistructs/extention.go
bundle/dicehub.go
modules/dicehub/dbclient/extention.go
modules/dicehub/service/extension/extension.go
modules/pipeline/services/extmarketsvc/list.go

set latest-version extension as default
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that set latest-version extension as default           |
| 🇨🇳 中文    |   将最新版本的extension设为默认           |

fix(pipeline): set latest-version extension as default

---

conf/monitor/collector/collector-agent.yaml

disable debug config
| 🇺🇸 English |        collector config fix      |
| 🇨🇳 中文    |       collector配置修改       |

fix: collector-agent config fix

---

erda.yml

remove test nfs_root config for erda.yaml
| 🇺🇸 English |       remove test nfs_root config for erda.yaml       |
| 🇨🇳 中文    |          去掉erda.yaml中nfs_root的配置    |

fix: remove test nfs_root config for erda.yaml

---

bundle/gittar.go
modules/dop/services/project/import_package.go
modules/dop/services/project/project_package.go
tools/cli/cmd/create.go

support application without gittar repo
| 🇺🇸 English |     support application without gittar repo         |
| 🇨🇳 中文    |       支持没有代码仓库的应用       |

fix: support no repo in application

---

modules/openapi/api/apis/orchestrator/orchestrator_projectruntime_count.go
modules/orchestrator/endpoints/runtime.go

| 🇺🇸 English |   count runtime by env           |
| 🇨🇳 中文    |       根据env统计runtime数量      |

feat(dop): count runtime by env

---

modules/dop/component-protocol/components/release-manage/releaseTable/render.go
modules/dop/services/publish_item/item_statistic.go

fix: panic in pubilsh item metrics
| 🇺🇸 English | fix: panic in pubilsh item metrics  |
| 🇨🇳 中文    | 修复我的发布——统计大盘在监控组件异常时panic的问题 |

fix: panic in pubilsh item metrics

---

modules/dop/component-protocol/components/project-runtime/common/common.go

| 🇺🇸 English |       refactor tolower func       |
| 🇨🇳 中文    |     更改tolower函数         |

refactor(cp-project): refactor tolower func

---

modules/dop/services/project/export_package.go

handle duplicate addon in different release
rm addon found no config kv
| 🇺🇸 English |       fix: duplicate addon and no config addon       |
| 🇨🇳 中文    |      解决重复和无配置的 addon       |

fix: duplicate addon in different release

---

modules/dop/component-protocol/components/auto-test-plan-list/components/filter/provider.go
modules/dop/component-protocol/components/common/urlQuery.go

Solve the problem that the urlQuery does not take effect
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTQ2XSwiYXNzaWduZWUiOlsiMTAwMTI2MSJdfQ%3D%3D&id=246389&iterationID=1146&pId=0&type=BUG)
| 🇺🇸 English |     Solve the problem that the urlQuery does not take effect         |
| 🇨🇳 中文    |       解决urlQuery不生效问题       | …

fix(dop): Solve the problem that the urlQuery does not take effect

---

modules/pipeline/providers/reconciler/legacy/reconciler/reconcile.go

sleep 30 second to delay next reconcile that caused by cluster offline exception
/assign @sfwn 
| 🇺🇸 English |  Fix the bug that sleep 30 second to delay next reconcile that caused by cluster offline exception    |
| 🇨🇳 中文    |  修复了由集群下线导致的流水线异常重试           |

fix(pipeline): sleep 30 second to delay next reconcile that caused by cluster offline exception

---

modules/core/openapi-ng/auth/ory-kratos/user.go
pkg/ucauth/kratos.go
pkg/ucauth/kratos/identity.schema.json
pkg/ucauth/kratos/kratos.yml
pkg/ucauth/kratos/sms.request.jsonnet
pkg/ucauth/model.go

Update kratos yml with email and sms config
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTMxLDExMTUsMTE0NiwxMDkwLDExNjQsLTFdLCJhc3NpZ25lZSI6WyIxMDAxMDczIl19&id=229752&iterationID=1146&pId=292832&type=TASK)
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTMxLDExMTUsMTE0NiwxMDkwLDExNjQsLTFdLCJhc3NpZ25lZSI6WyIxMDAxMDczIl19&id=292688&iterationID=1146&pId=292832&type=TASK)
| 🇺🇸 English |   Update kratos yml with email and sms config           |
| 🇨🇳 中文    |   升级kratos配置 邮箱和短信验证           |
Add comment like `/cherry-pick release/1.0` when this PR is …

feat: Update kratos yml with email and sms config

---

erda.yml

fix: reduce cmp resource
| 🇺🇸 English | fix: reduce cmp resource |
| 🇨🇳 中文    | 修改erda.yml中为cmp分配的资源量 |

fix: reduce cmp resource

---

modules/orchestrator/scheduler/executor/plugins/k8s/k8s.go

| 🇺🇸 English |          check quota with different workspace    |
| 🇨🇳 中文    |    检查不同环境的quota          |

fix(quota): check quota with different workspace

---

modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/podsTable/render.go

fix: cmp workloadDetail panic
| 🇺🇸 English | fix: cmp workloadDetail panic  |
| 🇨🇳 中文    | 修复cmp工作负载详情页面的panic             |

fix: cmp workloadDetail panic

---

modules/core/monitor/log/log.go
modules/core/monitor/log/persist/v1/consumer.go
modules/core/monitor/log/persist/v1/consumer_test.go
modules/core/monitor/log/persist/v1/storage.go
modules/core/monitor/log/persist/v1/storage_test.go
modules/core/monitor/log/storage/elasticsearch/iterator.go
modules/core/monitor/log/storage/kubernetes-logs/storage.go

| 🇺🇸 English |      fix typo        |
| 🇨🇳 中文    |      修复单词错误        |

fix: typo in log module

---

modules/dop/component-protocol/components/requirement-task-overview/chartBlock/burnoutChart/render.go
modules/dop/component-protocol/components/requirement-task-overview/chartBlock/burnoutChart/render_test.go

Deal with situations that have been completed before the iteration begins
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTQ2XSwiYXNzaWduZWUiOlsiMTAwMTI2MSJdfQ%3D%3D&id=291454&iterationID=1146&pId=0&type=TASK)
| 🇺🇸 English |   Deal with situations that have been completed before the iteration begins           |
| 🇨🇳 中文    |      处理在迭代开始之前就已经完成的情况        | …

fix(dop): Deal with situations that tasks have been completed before the iteration begins

---

go.mod
go.sum

| 🇺🇸 English |       update erda-infra       |
| 🇨🇳 中文    |      更新 erda-infra        |

feat: update go-mod

---

modules/dop/services/issue/adjust.go
modules/dop/services/issue/cache.go
modules/dop/services/issue/issue.go
modules/dop/services/issue/validate.go

Verify issue planned end time and issue state with iteration
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTMxLDExMTUsMTE0NiwxMDkwLDExNjRdLCJhc3NpZ25lZSI6WyIxMDAxMDczIl19&id=292854&iterationID=1146&pId=0&type=TASK)
/assign @sfwn 
| 🇺🇸 English |   Verify issue planned end time and issue state with iteration           |
| 🇨🇳 中文    |     事项截止时间和状态与迭代校验         | …

feat: Verify issue planned end time and issue state with iteration

---

modules/dop/providers/api-management/provider.go

fix: paging
| 🇺🇸 English | fix paging error in downloading apis records list |
| 🇨🇳 中文    | 修复了下载 API 列表记录页面分页错误的问题 |

fix: paging

---

modules/pipeline/pipengine/actionexecutor/k8s_helper.go

fix k8s executor concurrent interator and write map
| 🇺🇸 English |   Fix the bug that update and delete k8s executor by factory           |
| 🇨🇳 中文    |   修复了k8sexecutor并发遍历写map的问题           |

fix(pipeline): update and delete k8s executor by factory

---

modules/pipeline/providers/leaderworker/worker/worker.go

fix copy issue of handlers, which cause task never done.
`handlers` is always nil before this pr.
| 🇺🇸 English |   fix pipeline worker's issue of copy handlers         |
| 🇨🇳 中文    |   修复了流水线 worker handler 的拷贝问题           |
Add comment like `/cherry-pick release/2.1-beta.2` when this PR is merged.

fix(pipeline): fix copy issue of handlers, which cause task never done

---

modules/orchestrator/scheduler/executor/plugins/k8s/job.go
modules/orchestrator/scheduler/executor/plugins/k8s/k8s.go
modules/orchestrator/scheduler/executor/plugins/k8s/runtime.go
modules/orchestrator/services/deployment/deployment_context.go

fix: deployment exit when job failed
| 🇺🇸 English |     deployment exit when job failed        |
| 🇨🇳 中文    |       job运行失败则部署单失败退出       |

fix: deployment exit when job failed

---

build/dockerfiles/Dockerfile-cli
build/dockerfiles/base/Dockerfile
build/scripts/cli/run.sh
pipeline.yml

image for erda cli
| 🇺🇸 English |        make image for erda-cli      |
| 🇨🇳 中文    |         制作 erda-cli 镜像      |

feat: make image for cli

---

apistructs/issue_stream.go
apistructs/issue_stream_locale.go
modules/dop/dao/issue.go
modules/dop/initialize.go
modules/dop/provider.go
modules/dop/providers/issue/stream/provider.go
modules/dop/providers/issue/stream/service.go
modules/dop/services/issue/cache.go
modules/dop/services/issue/issue.go
modules/dop/services/issuestream/issue_stream_template.go
pkg/ucauth/user_admin.go

Issue state automation set up, add issue stream by system
| 🇺🇸 English |   Issue state automation set up, add issue stream by system           |
| 🇨🇳 中文    |   事项状态流的自动化           |

feat: Issue state automation set up, add issue stream by system

---

go.sum
modules/pipeline/dbclient/dbclient.go
modules/pipeline/dbclient/dbclient_test.go
pkg/common/common.go
pkg/database/dbengine/conf.go
pkg/database/dbengine/conf_test.go

Database connection increases tls configuration
| 🇺🇸 English |      Database connection adds tls support       |
| 🇨🇳 中文    |        数据库连接增加 tls 支持      |

feat(pipeline): Database connection increases tls configuration

---

modules/dicehub/release/release.service.go
modules/dicehub/release/release_test.go

feat: parse job image from dice.yaml for release
| 🇺🇸 English | feat: parse job image from dice.yaml for release |
| 🇨🇳 中文    | 添加对dice.yml中job镜像的解析 |

feat: parse job image from dice.yaml for release

---

modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/filterContainer/customFilter/provider.go
modules/dop/component-protocol/components/project-pipeline/myPage/pageHeader/pipelineTabs/model.go
modules/dop/component-protocol/components/project-pipeline/myPage/pageHeader/pipelineTabs/render.go
modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/filterContainer/customFilter/provider.go
modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go

project pipeline add url query support
| 🇺🇸 English |       project pipeline add url query support       |
| 🇨🇳 中文    |     项目管道添加 url 查询支持         |

feat(dop): project pipeline add url query support

---

tools/cli/install.sh

script for install cli
| 🇺🇸 English |        cli install script      |
| 🇨🇳 中文    |       cli 安装脚本       |

feat: cli install script

---

erda.yml

remove test values
| 🇺🇸 English | fix: remove test values             |
| 🇨🇳 中文    |    移除测试环境配置          |

fix: remove test values

---

apistructs/gittar.go
go.mod
go.sum
pkg/terminal/table/table.go
tools/cli/cmd/build.go
tools/cli/cmd/clone.go
tools/cli/cmd/issue.go
tools/cli/cmd/issue_close.go
tools/cli/cmd/issue_fix.go
tools/cli/cmd/issue_open.go
tools/cli/cmd/mr.go
tools/cli/cmd/mr_compare.go
tools/cli/cmd/mr_create.go
tools/cli/cmd/mr_open.go
tools/cli/cmd/view.go
tools/cli/command/context.go
tools/cli/command/root_cmd.go
tools/cli/common/application.go
tools/cli/common/browser.go
tools/cli/common/issue.go
tools/cli/common/mr.go
tools/cli/common/project.go
tools/cli/utils/workspace.go

commands for list/open/fix/close issue, create/open mr
| 🇺🇸 English |        commands for list/open/fix/close issue, create/open mr      |
| 🇨🇳 中文    |        事件的罗列、打开、解决、关闭命令；合并请求的创建、打开命令      |

feat: cmds for issue and mr

---

apistructs/pipeline.go
apistructs/project_pipeline.go
modules/dop/endpoints/endpoints.go
modules/dop/endpoints/pipeline.go
modules/dop/endpoints/release.go
modules/dop/initialize.go
modules/dop/providers/projectpipeline/service_impl.go

Project pipeline binding on merge and push events
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTQ2LDExNjQsMTEzMSwxMTE1LDEwOTBdLCJhc3NpZ25lZSI6WyIxMDAwNTYwIl19&id=293877&iterationID=1146&pId=292482&type=TASK)
| 🇺🇸 English |       The project level pipeline can display the records generated by on merge and push events      |
| 🇨🇳 中文    |      项目级流水线可以展示 on merge 和 push 事件产生的记录        |

feat(dop): Project pipeline binding on merge and push events

---

pkg/database/sqlparser/ddlreverser/reverser.go
pkg/database/sqlparser/migrator/migrator.go
pkg/database/sqlparser/snapshot/config.go
pkg/database/sqlparser/snapshot/config_test.go
pkg/database/sqlparser/snapshot/snapshot.go
pkg/database/sqlparser/snapshot/snapshot_test.go

feat: skip big tables while smapling
| 🇺🇸 English | skip big tables while smapling |
| 🇨🇳 中文    | 数据采样时跳过大表以缩短采样时间 |

feat: skip big tables while smapling

---

erda.yml

remove eventbox from erda.yml
| 🇺🇸 English |       remove eventbox from erda.yml       |
| 🇨🇳 中文    |       移除eventbox       |

feat: remove eventbox from erda.yml

---

modules/dop/component-protocol/components/release-manage/releaseTable/render.go
modules/orchestrator/scheduler/executor/plugins/k8s/k8s.go

fix: check quota memory error
| 🇺🇸 English | fix: check quota memory errorz |
| 🇨🇳 中文    | 修复检查配额时内存计算错误的问题 |

fix: check quota memory error

---

modules/orchestrator/services/deployment_order/deployment_order_cron.go

fix: order cron error when release deleted
| 🇺🇸 English |    fix: order cron error when release deleted          |
| 🇨🇳 中文    |   修复制品被删除导致的消费失败          |

fix: order cron error when release deleted

---

pkg/http/httpclient/client.go

log level to debug avoiding msg when https redirect in using cli
/assign @luobily @sfwn @wangzhuzhen 
| 🇺🇸 English |       change log level to debug avoiding msg when https redirect        |
| 🇨🇳 中文    |        降低日志级别避免https重定向时打印日志      |

fix: change log level to debug avoiding msg when https redirect in using cli

---

modules/msp/apm/service/common/error-transaction/table.go
modules/msp/apm/service/common/slow-transaction/table.go
modules/msp/apm/service/components/transaction-cache-error/metric_table_filter/provider.go
modules/msp/apm/service/components/transaction-cache-slow/metric_table_filter/provider.go
modules/msp/apm/service/components/transaction-db-error/metric_table_filter/provider.go
modules/msp/apm/service/components/transaction-db-slow/metric_table_filter/provider.go
modules/msp/apm/service/components/transaction-http-error/metric_table_filter/provider.go
modules/msp/apm/service/components/transaction-http-slow/metric_table_filter/provider.go
modules/msp/apm/service/components/transaction-mq-error/metric_table_filter/provider.go
modules/msp/apm/service/components/transaction-mq-slow/metric_table_filter/provider.go
modules/msp/apm/service/components/transaction-rpc-error/metric_table_filter/provider.go
modules/msp/apm/service/components/transaction-rpc-slow/metric_table_filter/provider.go
modules/msp/apm/service/view/common/sqlutils.go
modules/msp/apm/service/view/table/error_transaction.go
modules/msp/apm/service/view/table/slow_transaction.go

| 🇺🇸 English |    support input float for duration range          |
| 🇨🇳 中文    |     持续时间范围支持输入浮点数         |

fix: support input float for duration range

---

modules/pipeline/providers/cron/daemon/cron_task.go

The repair cron task cannot be turned on or off
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=297877&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDA1NjAiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1146&type=BUG)
| 🇺🇸 English |      The repair cron task cannot be started normally        |
| 🇨🇳 中文    |       修复定时任务无法正常启动       |

fix(pipeline): The repair cron task cannot be turned on or off

---

apistructs/issue.go
apistructs/issue_stream_locale.go
modules/dop/services/issue/adjust.go
modules/dop/services/issue/issue.go
modules/dop/services/issue/validate.go
modules/dop/services/issue/validate_test.go

Fix iteration validator comparing by date, validate planFinishedAt
| 🇺🇸 English |  Fix iteration validator comparing by date, validate planFinishedAt            |
| 🇨🇳 中文    |   修复迭代日期校验           |

fix: Fix iteration validator comparing by date, validate planFinishedAt

---

modules/gittar/api/repo.go
modules/gittar/conf/conf.go

add link for gittar delete branch event
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTQ2XSwiYXNzaWduZWUiOlsiMTAwMTIwNSJdfQ%3D%3D&id=297904&iterationID=1146&pId=0&type=BUG)
| 🇺🇸 English |    Fix the bug that add link param for gittar delete branch event           |
| 🇨🇳 中文    |   修复了gittar事件丢失链接的问题           | …

fix(gittar): add link param for gittar delete branch event

---

modules/monitor/apm/topology/topology.go
modules/monitor/apm/topology/topology_test.go

| 🇺🇸 English |    gateway topology node isn't displayed correctly          |
| 🇨🇳 中文    |    网关拓扑节点未正确显示          |

fix: gateway topology node isn't displayed correctly

---

modules/core/monitor/alert/alert-apis/alert.service.go
modules/core/monitor/alert/alert-apis/db/alert_event.go

| 🇺🇸 English |     fix: fix alert event list filter error         |
| 🇨🇳 中文    |      修复告警事件列表过滤错误问题        |

fix: fix alert event list filter error

---

apistructs/project_pipeline.go
conf/dop/i18n/project-pipeline.yaml
modules/dop/providers/projectpipeline/service_impl.go
modules/dop/services/filetree/filetree.go

update pipeline category
| 🇺🇸 English |    update pipeline category          |
| 🇨🇳 中文    |    更新流水线分类          |

feat(dop): update pipeline category

---

modules/dop/component-protocol/components/project-runtime/list/list.go

| 🇺🇸 English |     add error handle         |
| 🇨🇳 中文    |        增加错误处理      |

fix(cp-app): add error handle

---

modules/core-services/endpoints/project_workspace.go
modules/orchestrator/scheduler/executor/plugins/k8s/addon/redis/legacy/redis.go
modules/orchestrator/scheduler/executor/plugins/k8s/addon/redis/redis.go
modules/orchestrator/services/addon/addon.go
modules/orchestrator/services/addon/addon_status.go
modules/orchestrator/services/addon/addon_test.go
modules/orchestrator/utils/elastic_container_utils.go
tools/cli/cmd/project_deployment_stop.go
tools/cli/common/project.go

redis operator addon support scale down and scale up
Feature: Support redis operator addon scale down and scale up（实现 Redis operator addon 的 停止/启动）
| 🇺🇸 English |       Support redis operator addon scale down and scale up       |
| 🇨🇳 中文    |       实现 Redis operator addon 的 停止/启动      |

feat: redis operator addon support scale down and scale up

---

modules/orchestrator/scheduler/instanceinfo/clusterInfo.go

fix: bug of write clusterinfo to database
| 🇺🇸 English |    bug of write clusterinfo to database.          |
| 🇨🇳 中文    |       修复写clusterinfo到数据库的bug      |

fix: bug of write clusterinfo to database

---

modules/orchestrator/dbclient/runtime.go
modules/orchestrator/services/deployment/deployment_context.go
modules/orchestrator/services/deployment/deployment_context_test.go

feat: use project namespace when create new runtime in old project
| 🇺🇸 English |       feat: use project namespace when create new runtime in old project       |
| 🇨🇳 中文    |         老项目中新的runtime默认使用项目级namespace     |

feat: use project namespace when create new runtime in old project

---

modules/pipeline/providers/reconciler/task_reconciler.go

The cluster information is lost during scenario execution, resulting in the failure of sending the request
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=298355&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDA1NjAiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1146&tab=BUG&type=BUG)
| 🇺🇸 English |           fix The cluster information is lost during scenario execution, resulting in the failure of sending the request                  |
| 🇨🇳 中文    |        修复场景执行丢失集群信息导致发送请求失败      |

fix(pipeline): The context inside taskrun cannot be passed, resulting in the loss of some information during the execution of api-test executor

---

modules/pipeline/providers/reconciler/pipeline_reconciler.go
modules/pipeline/providers/reconciler/task_reconciler.go

pipeline reconciler bypass tx temporarily
| 🇺🇸 English |   pipeline reconciler bypass tx temporarily           |
| 🇨🇳 中文    |   流水线 reconciler 临时去除事务           |
Add comment like `/cherry-pick release/2.1-beta.3` when this PR is merged.

fix: pipeline reconciler bypass tx temporarily

---

modules/orchestrator/services/deployment/deployment_context.go

feat: deployment cancel is force default
| 🇺🇸 English |       feat: deployment cancel is force default.       |
| 🇨🇳 中文    |         部署单默认取消为强制取消     |

feat: deployment cancel is force default

---

modules/hepa/repository/service/gateway_az_info_service.go

| 🇺🇸 English |  remove dependency of clusterinfo of orchestrator            |
| 🇨🇳 中文    |    移除hepa对orchestrator中clusterInfo 接口的依赖         |

refactor(hepa): remove dependency of clusterinfo of orchestrator

---

apistructs/project_pipeline.go
modules/dop/providers/projectpipeline/service_impl.go
modules/dop/providers/projectpipeline/service_impl_test.go
modules/dop/services/filetree/filetree.go

Solve the problem of category query error
| 🇺🇸 English |      Solve the problem of category query error        |
| 🇨🇳 中文    |      解决分类查询错误问题        |

fix(dop): Solve the problem of category query error

---

apistructs/extention.go
bundle/dicehub.go
modules/dicehub/dbclient/extention.go
modules/dicehub/endpoints/extention.go
modules/dicehub/service/extension/extension.go
modules/orchestrator/endpoints/addon.go
modules/orchestrator/services/addon/addon.go
modules/pipeline/services/extmarketsvc/list.go

Fix list extension versions query, add param all
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTQ2XSwiYXNzaWduZWUiOlsiMTAwMTA3MyJdfQ%3D%3D&id=298010&iterationID=1146&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |    Fix list extension versions query, add param all          |
| 🇨🇳 中文    |   修复拓展版本查询           | …

fix: Fix list extension versions query, add param all

---

modules/dop/services/issue/issue.go

Fix issue update request iteration id check nil
/assign @sfwn 
| 🇺🇸 English |    Fix issue update request iteration id check nil          |
| 🇨🇳 中文    |     修复了事项更新时迭代为空         |
release/2.1-beta.3

fix: Fix issue update request iteration id check nil

---

modules/hepa/apipolicy/policies/csrf/policy.go

fix csrf switch
| 🇺🇸 English | fix csrf-token plugin switch |
| 🇨🇳 中文    | 修复 csrf-token 开关硬编码的问题 |

feat: csrf switch

---

modules/dop/component-protocol/components/project-pipeline/common/gshelper/helper.go
modules/dop/component-protocol/components/project-pipeline/myPage/pageHeader/pipelineTabs/render.go
modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/filterContainer/customFilter/condition.go
modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
modules/dop/providers/projectpipeline/service_impl.go

Optimize project pipeline query time
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTQ2LDExNjQsMTEzMSwxMTE1XSwiYXNzaWduZWUiOlsiMTAwMTI2MSJdfQ%3D%3D&id=299210&iterationID=1164&pId=299206&type=TASK)
/assign @sfwn 
| 🇺🇸 English |     Optimize project pipeline query time         |
| 🇨🇳 中文    |      优化项目流水线查询耗时        |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBU …

perf(dop): Optimize project pipeline list query time

---

.erda/migrations/pipeline/20220326-pipeline-crons.sql
conf/monitor/monitor/monitor.yaml

add modify pipeline_crons extra pipelineyaml sql
| 🇺🇸 English |       add modify pipeline_crons extra pipelineyaml sql       |
| 🇨🇳 中文    |       修改pipeline_crons表中的extra字段       |

fix: add modify pipeline_crons extra pipelineyaml sql

---

bundle/bundle_test.go
modules/admin/dingtalktest/provider.go
modules/admin/provider.go
modules/cluster-manager/endpoints/endpoints.go
modules/cmp/initialize.go
modules/cmp/steve/middleware/middleware_test.go
modules/core-services/initialize.go
modules/dicehub/initialize.go
modules/dop/provider.go
modules/dop/providers/autotest/testplan/provider.go
modules/openapi/api/apis/presale_survey.go
modules/orchestrator/events/provider.go
modules/orchestrator/initialize.go
modules/orchestrator/scheduler/scheduler.go
modules/pipeline/aop/plugins/pipeline/testplan_after/plugin.go
modules/pipeline/providers/clusterinfo/provider.go
pkg/discover/address.go

delete eventbox_addr in pipeline
| 🇺🇸 English |       delete eventbox_addr in pipeline       |
| 🇨🇳 中文    |       删除eventbox地址       |

fix: delete eventbox_addr in pipeline

---

modules/orchestrator/services/addon/addon_status.go

feature: add ZK_SERVER_HEAP to zk addon
| 🇺🇸 English |     add ZK_SERVER_HEAP to zk addon        |
| 🇨🇳 中文    |      给 zk addon 增加 ZK_SERVER_HEAP 环境变量，用于设置 jvm heap       |
no

feat: add ZK_SERVER_HEAP to zk addon

---

apistructs/project_pipeline.go
modules/pipeline/providers/definition/db/define.go

update pipeline category and polish sql
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTY0XSwiYXNzaWduZWUiOlsiMTAwMTI2MSJdfQ%3D%3D&id=299545&iterationID=1164&pId=295915&type=TASK)
| 🇺🇸 English |     update pipeline category and polish the sql         |
| 🇨🇳 中文    |     更新流水线分类并且优化sql         |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.m …

feat(dop): update pipeline category and polish the sql

---

modules/dop/component-protocol/components/release-manage/releaseTable/render.go
modules/orchestrator/services/deployment_order/deployment_order_create.go
modules/orchestrator/services/deployment_order/deployment_order_cron.go

fix: deployList can not be empty
| 🇺🇸 English | fix: deployList can not be empty |
| 🇨🇳 中文    | 修复部署单选中模式为空时panic的问题 |

fix: deployList can not be empty

---

.erda/migrations/cmdb/20220329-dice_member_extra-charset-collate.sql
.erda/migrations/config.yml

dice_member_extra set charset collate utf8mb4_general_ci
| 🇺🇸 English |  dice_member_extra set charset collate utf8mb4_general_ci            |
| 🇨🇳 中文    |  dice_member_extra 设置字符集 COLLATE 为 utf8mb4_general_ci            |

fix(core-services): dice_member_extra set charset collate utf8mb4_general_ci

---

modules/core-services/services/approve/approve.go

Update approval url in notify message
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTY0LDExNzgsMTEzMV0sImFzc2lnbmVlIjpbIjEwMDEwNzMiXX0%3D&id=298014&iterationID=1164&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |    Update approval url in notify message          |
| 🇨🇳 中文    |  更新通知中的审批链接             |

fix: Update approval url in notify message

---

modules/dop/component-protocol/components/release-manage/releaseTable/render.go
modules/orchestrator/services/deployment_order/deployment_order_create.go

fix: only check project release
| 🇺🇸 English |  fix: only check project release  |
| 🇨🇳 中文    | 只对项目制品进行mode为空的检查 |

fix: only check project release

---

modules/hepa/apipolicy/policies/csrf/policy.go
modules/hepa/providers/api_policy/api.policy.service.go
modules/hepa/services/api_policy/impl/impl.go

feat: csrf by route
| 🇺🇸 English | csrf by route |
| 🇨🇳 中文    | 修复了 CSRF 插件启用时对所有引用网关的域名都生效的问题，修复为按 路由生效 |

feat: csrf by route

---

go.mod
go.sum
modules/pipeline/providers/dispatcher/dispatcher.go
modules/pipeline/providers/leaderworker/leader_framework.go

leader-worekr safe invoke functions
| 🇺🇸 English |  ppipeline leader-worekr provider safe invoke functions            |
| 🇨🇳 中文    |  流水线 leader-worker 模块安全调用函数            |
Add comment like `/cherry-pick release/2.1-beta.3` when this PR is merged.

feat(pipeline): leader-worekr safe invoke functions

---

pkg/database/sqlparser/migrator/parameters.go
pkg/database/sqlparser/migrator/parameters_test.go
tools/cli/cmd/migrate.go

| 🇺🇸 English |        support tls of migration      |
| 🇨🇳 中文    |       migration 支持 tls       |

feat(migration): support tls on migration

---

api/proto-go/go.mod
api/proto-go/go.sum
modules/dop/providers/cms/cicdcmsservice.go
modules/dop/providers/cms/provider.go

cms provider Add error format encapsulation
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=301026&type=BUG)
| 🇺🇸 English |      cms provider Add error format encapsulation        |
| 🇨🇳 中文    |      cms提供程序添加错误格式封装        |

fix(dop): cms provider Add error format encapsulation

---

modules/orchestrator/services/deployment_order/deployment_order_create.go
modules/orchestrator/services/deployment_order/deployment_order_cron.go

fix: deployment order unable to stop deployment
1. stop deploying when runtime deleted
2. stop deploying when release deleted
3. fix panic when release not found
| 🇺🇸 English |  fix deployment order unable to stop deployment            |
| 🇨🇳 中文    |     修复部署单无法停止部署         |

fix: deployment order unable to stop deployment

---

modules/pipeline/providers/reconciler/task_reconciler.go

append log to task inspect when get executor failed
| 🇺🇸 English |  append log to task inspect when get executor failed            |
| 🇨🇳 中文    | 任务执行器获取失败时，往任务 Inspect 里追加日志             |

feat(pipeline): append log to task inspect when get executor failed

---

modules/admin/component-protocol/components/personal-workbench/workCards/provider.go

| 🇺🇸 English |     change target of app runtime         |
| 🇨🇳 中文    |       修改app runtime 点击跳转target       |

fix(cp-person): change target of app runtime

---

modules/admin/component-protocol/components/personal-workbench/workCards/provider.go

| 🇺🇸 English |     add target param         |
| 🇨🇳 中文    |       修改 target  参数     |

fix(cp-person): add target param

---

modules/dop/component-protocol/components/issue-dashboard/filter/model.go
modules/dop/component-protocol/components/issue-dashboard/filter/render.go
modules/dop/component-protocol/components/requirement-task-overview/distributePage/topFilter/model.go
modules/dop/component-protocol/components/requirement-task-overview/distributePage/topFilter/render.go
modules/openapi/component-protocol/components/filter/filter.go

Requirement task overview in fixed iteration
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTY0LDExMzEsMTE3OCwxMTc0XSwiYXNzaWduZWUiOlsiMTAwMTA3MyJdfQ%3D%3D&id=299957&iterationID=1164&pId=296313&type=TASK)
/assign @sfwn 
| 🇺🇸 English |  Requirement task overview in fixed iteration            |
| 🇨🇳 中文    |   迭代内新增研发统计       |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/maste …

feat: Requirement task overview in fixed iteration

---

erda.yml

add erda test env resource values
| 🇺🇸 English | add erda test env resource values             |
| 🇨🇳 中文    |   添加 erda 集成环境 request 资源值           |

feat: add erda test env resource values

---

modules/hepa/cache/org/org.go
modules/hepa/cache/org/org_test.go
modules/hepa/gateway/dto/manage_domain_info.go
modules/hepa/providers/domain/domain.service.go
modules/hepa/services/domain/impl/impl.go

Optimized the domain name list management permission prompt on CMP
| 🇺🇸 English | Optimized the domain name list management permission prompt on CMP |
| 🇨🇳 中文    | 优化了多云管理平台域名列表管理权限提示 |

feat: Optimized the domain name list management permission prompt on CMP

---

modules/pipeline/providers/cms/db/op.go

Solve the deadlock problem in multi-transaction
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTY0XSwiYXNzaWduZWUiOlsiMTAwMTI2MSJdfQ%3D%3D&id=301858&iterationID=1164&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |     Solve the deadlock problem in multi-transaction         |
| 🇨🇳 中文    |      解决在多事物场景下死锁问题        |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTI …

fix(pipeline): Solve the deadlock problem in multi-transaction

---

modules/dop/component-protocol/components/release-manage/releaseTable/render.go
modules/orchestrator/services/deployment_order/deployment_order_create.go

fix: select default mode if no mode provide in request
| 🇺🇸 English | fix: select default mode if no mode provide in request |
| 🇨🇳 中文    | 创建部署单请求若不提供模式，则默认选择default模式 |
Need cherry-pick to release/2.1-beta.3-2

fix: select default mode if no mode provide in request

---

pkg/database/sqlparser/migrator/db.go
pkg/database/sqlparser/migrator/parameters.go
pkg/database/sqlparser/migrator/parameters_test.go
tools/cli/cmd/migrate.go

| 🇺🇸 English | revert  migrate           |
| 🇨🇳 中文    |     revert migrate 代码         |

revert(migrate): revert

---

go.mod
go.sum
modules/pipeline/pipengine/actionexecutor/logic/status.go
modules/pipeline/pipengine/actionexecutor/plugins/k8sflink/flink.go

change flink fourth level domain to three
/kind bug
/assign @sfwn 
| 🇺🇸 English |  change flink fourth level domain to three            |
| 🇨🇳 中文    | 将flink-ui的四级域名改为三级             |

fix: change flink fourth level domain to three

---

conf/monitor/monitor/metricmeta/i18n/_group.yml

| 🇺🇸 English |       fix i18n error       |
| 🇨🇳 中文    |      修复国际化文案错误        |

fix: i18n error fix

---

modules/core/monitor/log/storage/clickhouse/iterator.go

| 🇺🇸 English |    fix  log _id sort error         |
| 🇨🇳 中文    |        修复日志分析上下文浏览id顺序错误的问题      |

fix: id order should same with the timestamp order

---

modules/dicehub/release/release.service.go

fix: add get release debug logs
| 🇺🇸 English | fix: add get release debug logs |
| 🇨🇳 中文    | 添加项目制品详情接口的debug日志 |

fix: add get release debug logs

---

modules/dop/services/pipeline/pipeline.go
modules/pipeline/services/pipelinesvc/create_v2.go

Add cron expression to pipeline YML file to automatically create cron records
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTY0XSwiYXNzaWduZWUiOlsiMTAwMDU2MCJdfQ%3D%3D&id=299688&iterationID=1164&pId=0&type=REQUIREMENT)
| 🇺🇸 English |        Add cron expression to pipeline YML file to automatically create cron records      |
| 🇨🇳 中文    |       pipeline  yml 文件增加 cron 表达式，自动创建定时记录       |

feat(dop): Add cron expression to pipeline YML file to automatically create cron records

---

modules/eventbox/subscriber/sms/sms.go

modify sms templateCode
| 🇺🇸 English |       modify sms templateCode       |
| 🇨🇳 中文    |      eventbox发送短信templateCode获取错误        |

fix: modify sms templateCode

---

modules/pipeline/dbclient/op_pipeline.go
modules/pipeline/dbclient/op_pipeline_report.go
modules/pipeline/providers/cron/compensator/provider.go
modules/pipeline/providers/dbgc/dbgc.go
modules/pipeline/providers/dbgc/dbgc_test.go
modules/pipeline/providers/reconciler/taskpolicy/provider.go
modules/pipeline/providers/resourcegc/compensator.go
modules/pipeline/providers/resourcegc/compensator_test.go
modules/pipeline/services/pipelinesvc/list.go

Change the compensation policy not executed by cron, and change the policy of the latest one after successful execution to the latest one after execution termination
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTY0XSwiYXNzaWduZWUiOlsiMTAwMDU2MCJdfQ%3D%3D&id=230962&iterationID=1164&pId=0&type=REQUIREMENT)
| 🇺🇸 English |       Change the compensation policy not executed by cron, and change the policy of the latest one after successful execution to the latest one after execution termination       |
| 🇨🇳 中文    |        更改 cron 未执行补偿策略，将执行成功往后最新一条的策略改成执行终止状态往后最新一条      |

feat(pipeline): Change the compensation policy not executed by cron

---

modules/core/monitor/log/storage/clickhouse/query_parser/query_parser.go
modules/core/monitor/log/storage/clickhouse/sql_builder.go
modules/core/monitor/log/storage/clickhouse/utils/utils.go
modules/core/monitor/storekit/clickhouse/table/creator/creator.go
modules/core/monitor/storekit/clickhouse/table/loader/interface.go

| 🇺🇸 English |       ck releated bugfix       |
| 🇨🇳 中文    |       ck相关bug修复       |

fix: ck related bugfix

---

conf/monitor/monitor/monitor.yaml
modules/core/monitor/log/storage/clickhouse/aggregate.go
modules/core/monitor/log/storage/elasticsearch/aggregate.go
modules/extensions/loghub/index/query/log_query.go
modules/msp/apm/log-service/query/log.service.histogram.go
modules/msp/apm/log-service/query/log.service.search.go
modules/msp/apm/log-service/query/log.service.terms.go

| 🇺🇸 English |      fix compatibility  between ck and es for log query       |
| 🇨🇳 中文    |        修复日志查询es和ck兼容性问题      |

fix: fix compatible with es and ck

---

.github/workflows/git-sync.yml

update remote
| 🇺🇸 English |     update remote         |
| 🇨🇳 中文    |      修改源        |

ci: update remote

---

modules/dop/component-protocol/components/issue-manage/issueTable/render.go

Update requirement progress format in issue table
/assign @sfwn 
| 🇺🇸 English |   Update requirement progress format in issue table           |
| 🇨🇳 中文    |   更新需求进度           |

feat: Update requirement progress format in issue table

---

modules/dop/services/issue/issue.go

Fix sync issue children with planning iteration id
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTc4LDExNzQsMTE2NF0sImFzc2lnbmVlIjpbIjEwMDEwNzMiXX0%3D&id=303698&iterationID=1164&pId=0&type=BUG)
| 🇺🇸 English |     Fix sync issue children with planning iteration id          |
| 🇨🇳 中文    |    修复了事项同步到待规划的迭代          | …

fix: Fix sync issue children with planning iteration id

---

modules/dicehub/release/provider.go

fix: do not check modes when update applicaiton release
| 🇺🇸 English | fix: do not check modes when update applicaiton release |
| 🇨🇳 中文    | 修复更新应用制品时检查modes为空的问题 |

fix: do not check modes when update applicaiton release

---

modules/pipeline/endpoints/endpoints.go
modules/pipeline/endpoints/mysql.go
modules/pipeline/initialize.go
modules/pipeline/provider.go

add mysql stats to pipeline
/assign @sfwn 
| 🇺🇸 English |      add mysql stats to pipeline        |
| 🇨🇳 中文    |      pipeline增加mysql统计信息        |

feat(pipeline): add mysql stats to pipeline

---

modules/dop/providers/projectpipeline/service_impl.go

PipelineCategory list include all app
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTY0LDExNzRdLCJhc3NpZ25lZSI6WyIxMDAxMjYxIl19&id=303509&iterationID=1164&pId=0&type=BUG)
| 🇺🇸 English |    PipelineCategory list include all app          |
| 🇨🇳 中文    |     流水线分类列表包括所有应用         |

fix(dop): PipelineCategory list include all app

---

conf/monitor/streaming/clickhouse/logs_ddl_create_default_tables.sql
conf/monitor/streaming/clickhouse/logs_ddl_create_tenant_tables.sql
modules/core/monitor/log/query/log.query.service.go
modules/core/monitor/log/query/log.query.service_test.go
modules/core/monitor/log/storage/clickhouse/iterator.go
modules/core/monitor/log/storage/storage.go

| 🇺🇸 English |      optimize clickhouse log query performance        |
| 🇨🇳 中文    |     优化clickhouse日志查询性能         |

fix: not return tags field if not necessary

---

modules/cluster-agent/client/client.go
modules/cluster-agent/client/credential.go
modules/cluster-agent/provider.go
modules/cluster-dialer/server/dialer_test.go
modules/cluster-dialer/server/tunnel-server_test.go

fix  cluster-agent goroutine leak
local test:
| 🇺🇸 English |  fix  cluster-agent goroutine leak            |
| 🇨🇳 中文    |  修复 cluster-agent goroutine 泄漏问            |

fix: cluster-agent goroutine leak

---

modules/dop/utils/generate_name.go

solve the problem of git author
/assign @sfwn 
| 🇺🇸 English |    solve the problem of git author env          |
| 🇨🇳 中文    |     解决 git author 环境变量为注入问题         |
/cherry-pick release/2.1-beta.3-3

fix(dop): solve the problem of git author env

---

modules/pipeline/providers/cron/compensator/provider.go

cron compensation executes pipeline adding run user id, If it is not added, the release action will report an error
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTc0LDExNjRdLCJhc3NpZ25lZSI6WyIxMDAwNTYwIl19&id=304210&iterationID=1174&pId=0&type=BUG)
| 🇺🇸 English |      cron compensation executes pipeline adding run user id        |
| 🇨🇳 中文    |      定时补偿执行添加执行者        |

fix(pipeline): cron compensation executes pipeline adding run user id 

---

modules/orchestrator/scheduler/executor/plugins/k8s/deployment.go
modules/orchestrator/scheduler/executor/plugins/k8s/deployment_test.go
modules/orchestrator/scheduler/executor/plugins/k8s/job.go

feat: support rendor erda env to job
| 🇺🇸 English |       support rendor erda env to job       |
| 🇨🇳 中文    |         job中支持erda环境变量的渲染    |

feat: support rendor erda env to job

---

apistructs/job.go
go.mod
modules/pipeline/dbclient/op_pipeline_config.go
modules/pipeline/pipengine/actionexecutor/plugins/docker/docker.go
modules/pipeline/pipengine/actionexecutor/plugins/docker/docker_test.go
modules/pipeline/pipengine/actionexecutor/plugins/k8sjob/k8sjob.go
modules/pipeline/pkg/container_provider/container_instance_provider.go
modules/pipeline/pkg/container_provider/container_provider_test.go
modules/pipeline/spec/pipeline_task.go

pipeline action executor add docker executor
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=301588&iterationID=1174&pId=292707&type=TASK)
| 🇺🇸 English |  Support pipeline docker executor for cicd            |
| 🇨🇳 中文    |     pipeline action增加docker执行器         |

feat(pipeline): pipeline engine add docker executor

---

modules/pipeline/metrics/task.go

| 🇺🇸 English |     remove env tags from dice_pipeline_task metric         |
| 🇨🇳 中文    |    删除 dice_pipeline_task 指标中的环境变量 tags           |

fix: remove env tags from dice_pipeline_task metric

---

modules/pipeline/providers/cms/pipeline_cms.go

Optimize the cms get api, change it to concurrent decryption
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTc0XSwiYXNzaWduZWUiOlsiMTAwMTI2MSJdfQ%3D%3D&id=299207&iterationID=1174&pId=303771&type=TASK)
/assign @sfwn 
| 🇺🇸 English |     Optimize the cms get api, change it to concurrent decryption         |
| 🇨🇳 中文    |     优化cms获取接口，改为并发解密         | …

feat(pipeline): Optimize the cms get api, change it to concurrent decryption

---

.erda/migrations/orchestrator/20220412-modes-env.sql
apistructs/runtime.go
modules/orchestrator/dbclient/deployment_order.go
modules/orchestrator/dbclient/runtime.go
modules/orchestrator/services/deployment/deployment_context.go
modules/orchestrator/services/deployment_order/deployment_order_create.go
modules/orchestrator/services/runtime/runtime.go

feat: add deploy modes env
| 🇺🇸 English | feat: add deploy modes env |
| 🇨🇳 中文    | 添加部署模式环境变量`ERDA_DEPLOY_MODES` |

feat: add deploy modes env

---

modules/dicehub/initialize.go

fix: change log time format
| 🇺🇸 English | fix: change log time format |
| 🇨🇳 中文    | 修改dicehub组件日志的时间格式，方便排查问题 |

fix: change log time format

---

modules/pipeline/initialize.go
modules/pipeline/providers/cache/secret.go
modules/pipeline/providers/reconciler/interface.go
modules/pipeline/providers/reconciler/snippet.go
modules/pipeline/services/pipelinesvc/batch_create.go
modules/pipeline/services/pipelinesvc/create.go
modules/pipeline/services/pipelinesvc/create_v2.go
modules/pipeline/services/pipelinesvc/precheck.go
modules/pipeline/services/pipelinesvc/rerun_failed.go
modules/pipeline/services/pipelinesvc/run.go

Only autoRun can use cache
and only autoRun can use cache 
/assign @sfwn 
| 🇺🇸 English |     only autoRun can use cache          |
| 🇨🇳 中文    |      只有自动运行才使用缓存        |

fix(pipeline): Only autoRun can use cache

---

modules/dop/services/issue/issue.go
modules/dop/services/issuerelated/issue_related.go

Fix empty issue plan time after inclusion change
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTc4LDExOTAsMTE3NF0sImFzc2lnbmVlIjpbIjEwMDEwNzMiXX0%3D&id=303784&iterationID=1174&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |   Fix empty issue plan time after inclusion change and iteration validation on requirement           |
| 🇨🇳 中文    |    修复了包含关系改变时事项计划时间为空, 需求迭代校验         | …

fix: Fix empty issue plan time after inclusion change
