.gitignore

add macOS files
add vim files
add vscode files
Special notes for your reviewer:
/cc @luobily @liuhaoyang

update(gitignore): add some ignore files in git ignore

---

CONTRIBUTING.md
README.md

- Add CONTRIBUTING.md
- Modify README.md

Modify README

---

apistructs/log.go

/kind feature
Update apistructs collector LogPushLine ID field type to string.
The ID field in collector side is string. and we use json tag `string` to force marshal uint64 to string before this pr.
In this pr, change the type to string and action-agent will use it later.
Fixes #
@Effet

feature: update apistructs collector LogPushLine ID field type to string

---

bundle/member.go
bundle/org.go
bundle/project.go

feature
List public org/project list bundle, pass additional user id for request from component protocol
Fixes #
@Effet 
```release-note
None
```
```docs
```

Add public org/project list bundle

---

README.md

add license icon
Fixes #
@liuhaoyang 
```release-note
```
```docs
```

add license icon

---

Makefile
build/scripts/docker_image.sh
go.mod

/kind feature
build all modules support
@liuhaoyang @Effet 
```docs
make
OR
make build-all
```

build all modules support

---

apistructs/audits.go
bundle/notify_group.go

/kind bug
fix notify and audit for fdp
@Effet

fdp notify and audit modify

---

apistructs/edge_app.go
apistructs/edge_openapi.go
apistructs/edge_site.go
bundle/ops_edge.go

/kind feature
Update the structure of edge application、edge openapi and edge sites.
Add bundle function for edge site‘s restart and offline.
Fixes #
@sixther-dc @Effet 
```release-note
```
```docs
```

feature: update apistructs and bundle to support edge platform

---

apistructs/tmc.go

/kind feature
hepa project namespace modify
@Effet

hepa ProjectNamespace

---

apistructs/pipeline_dto.go
apistructs/pipeline_dto_test.go
bundle/servicegroup.go

feature
apistructs add pipeline storage config

feature: apistructs add pipeline storage config

---

pkg/parser/pipelineyml/visitor_ref_op.go

hotfix
remove useless snippet action ref handler in pipelineyml parser to fix compile error.

hotfix: pipelineymlparser remove snippet action ref handler

---

OWNERS

feat(Owners): update owners file
Fixes #
/assgin @luobily 
```release-note
```
```docs
```

feat(Owners): update owners file

---

.github/workflows/golangci-lint.yml
.golangci.yml
apistructs/member.go

/kind feature
checks code style for PR
None
@liuhaoyang @johnlanni 
```release-note
NONE
```
```docs
```

feature: add golangci-lint & github-action

---

apistructs/permission.go

feature
add issue import permission

feature: add issue import permission

---

.github/PULL_REQUEST_TEMPLATE.md

/kind feature
- feat(template): update pull request template
Fixes #
```release-note
/release-note-none
```
```docs
```

feat(template): update pull request template

---

bundle/ops_edge.go

/ kind feature
Add identify authentication to ops module.
Use orgID and userID.
Fixes #
@Effet @sixther-dc @luobily 
```release-note
```
```docs
```

feature: add authentication to ops

---

modules/pipeline/conf/conf.go
modules/pipeline/pipengine/reconciler/taskrun/taskop/prepare.go
modules/pipeline/services/pipelinesvc/create_v2.go
modules/pipeline/services/pipelinesvc/precheck.go
modules/pipeline/spec/pipeline_extra.go

feature
In some scenarios, erda doesn't have privilege to create k8s volume. So, pipeline need a switch to disable create context volume, and only have value type context reference.
Fixes #
none
already tested in release/3.21
/assgin @Effet

feature: pipeline support disable context volume

---

modules/pipeline/pipengine/actionexecutor/plugins/demo/demo.go
modules/pipeline/pipengine/actionexecutor/plugins/memory/memory.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/scheduler.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/scheduler_test.go
modules/pipeline/pipengine/actionexecutor/types/define.go
modules/pipeline/pipengine/reconciler/gc.go

feature
pipeline action executor interface support batchDelete, use it instead of deleteNamespace (some k8s cluster we only have one namespace, cannot delete namespace).
Fixes #
none
already tested in release/3.21
/assgin @Effet

feature: pipeline action executor interface support batchDelete

---

.github/workflows/ci-it.yml

Add ci and ut coverage
/kind ci

Add ci and ut coverage

---

.github/workflows/ci-it.yml
README.md

Add code coverage badge

---

.github/workflows/ci-it.yml
codecov.yml

Fixes #
```release-note
```
```docs
```

Add codecov.yml

---

.github/workflows/ci-it.yml

/kind bug
fix cilint run error:  context loading failed: no go files to analyze
https://github.com/golangci/golangci-lint-action/issues/23
https://github.com/argoproj/argo-rollouts/pull/579/commits/1acf99b59678840be1e72b7151e4c8fc97407cad#diff-678682767f2477de3e3c546746f8568b9a1942b2c647d32331d7e774b8ff8d9f
@Effet @sfwn

fix golang-cilint run

---

README.md

add the conntact way of 'zhihu' in the readme file

add the conntact way of 'zhihu' in the readme file

---

modules/scheduler/executor/plugins/edas/edas.go
modules/scheduler/executor/plugins/k8s/addon/interface.go
modules/scheduler/executor/plugins/k8s/addon/redis/legacy/redis.go
modules/scheduler/executor/plugins/k8s/addon/redis/redis.go
modules/scheduler/executor/plugins/k8s/daemonset.go
modules/scheduler/executor/plugins/k8s/daemonset/daemonset.go
modules/scheduler/executor/plugins/k8s/deployment.go
modules/scheduler/executor/plugins/k8s/deployment/deployment.go
modules/scheduler/executor/plugins/k8s/k8s.go
modules/scheduler/executor/plugins/k8s/namespace/namespace.go
modules/scheduler/executor/plugins/k8s/pod/pod.go
modules/scheduler/executor/plugins/k8s/runtime.go
modules/scheduler/executor/plugins/k8s/service.go
modules/scheduler/executor/plugins/k8sflink/flink.go
modules/scheduler/executor/plugins/k8sflink/utils.go

/kind bug
- fix(scheduler): update runtime label to support global service in the namespace
Fixes #
/assgin @luobily @sixther-dc 
```release-note
```
```docs
```

fix(scheduler): update runtime label to support global service in the namespace

---

LICENSE
README.md

Modify LICENSE to AGPL v3
<!--

Modify LICENSE to AGPL v3

---

modules/scheduler/endpoints/endpoints.go
modules/scheduler/executor/plugins/k8s/clusterinfo/clusterinfo.go
modules/scheduler/executor/plugins/k8s/event/event.go
modules/scheduler/executor/plugins/k8s/event/parse.go
modules/scheduler/executor/plugins/k8s/k8serror/error.go
modules/scheduler/executor/plugins/k8s/precheck_test.go
modules/scheduler/executor/plugins/k8sflink/flink.go
modules/scheduler/executor/plugins/k8sjob/job.go
modules/scheduler/impl/job/delete.go
modules/scheduler/impl/job/job.go
modules/scheduler/schedulepolicy/constraintbuilders/k8s/build.go
modules/scheduler/server/server.go
pkg/clientgo/clientset/versioned/typed/config/v1alpha2/config_client.go
pkg/clientgo/clientset/versioned/typed/flinkoperator/v1beta1/flinkoperator_client.go
pkg/clientgo/clientset/versioned/typed/networking/v1alpha3/networking_client.go
pkg/clientgo/clientset/versioned/typed/networking/v1beta1/networking_client.go
pkg/clientgo/clientset/versioned/typed/openyurt/v1alpha1/apps_client.go
pkg/clientgo/clientset/versioned/typed/rbac/v1alpha1/rbac_client.go
pkg/clientgo/clientset/versioned/typed/security/v1beta1/security_client.go
pkg/clientgo/customclient/clientset.go
pkg/clientgo/discovery/discovery_client.go
pkg/clientgo/kubernetes/apps/v1/apps_client.go
pkg/clientgo/kubernetes/batch/v1/batch_client.go
pkg/clientgo/kubernetes/clientset.go
pkg/clientgo/kubernetes/core/v1/core_client.go
pkg/clientgo/kubernetes/policy/v1beta1/policy_client.go

/kind feature
cherry-pick code from release 3.21 support specific namespaces
Fixes #
/assgin @luobily @sixther-dc 
```release-note
```
```docs
```

cherry-pick code from release 3.21 support specific namespaces

---

modules/scheduler/executor/plugins/k8sflink/utils.go

/kind bug
update(flink): modify log level from error to info
Fixes #
/assgin @luobily @sixther-dc 
```release-note
```
```docs
```

update(flink): modify log level from error to info

---

cmd/action-runner/config.json
cmd/action-runner/main.go
modules/action-runner/apis.go
modules/action-runner/conf.go
modules/action-runner/logs.go
modules/action-runner/runner.go
modules/action-runner/task.go

migrate
migrate action-runner into erda.

migrate action-runner

---

cmd/action_runner_scheduler/main.go
conf/action_runner_scheduler/action_runner_scheduler.yaml
modules/action-runner-scheduler/conf/conf.go
modules/action-runner-scheduler/dbclient/dbclient.go
modules/action-runner-scheduler/dbclient/runner_task.go
modules/action-runner-scheduler/endpoints/endpoints.go
modules/action-runner-scheduler/endpoints/info.go
modules/action-runner-scheduler/endpoints/runner_task.go
modules/action-runner-scheduler/initialize.go
modules/action-runner-scheduler/provider.go
modules/action-runner-scheduler/services/apierrors/errors.go
modules/action-runner-scheduler/services/runnertask/runner_task.go

migrate
migrate action_runner_scheduler as module

migrate action_runner_scheduler

---

go.mod
go.sum

fix
resolve file conflicts of go.sum

resolve file conflicts of go.sum

---

modules/pipeline/conf/conf.go
modules/pipeline/pipengine/actionexecutor/plugins/apitest/logic/log_collector.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/scheduler.go
modules/pipeline/services/pipelinesvc/create.go
modules/pipeline/services/pipelinesvc/precheck.go
modules/pipeline/services/pipelinesvc/secret.go

feature
pipeline use  to discover other module's addr, not from env

pipeline use  to discover other module's addr

---

docs/guides/dev/How-to-build-erda-project.md

Fixes #
```release-note
```
```docs
```

How to build the Erda project.

---

Makefile
docs/guides/dev/How-to-build-erda-project.md

Fixes #
```release-note
```
```docs
```

DOCS: build a single module

---

README.md

documentation
add show case gif
Fixes #
```release-note
```
```docs
```

docs: add show case gif in readme

---

build/dockerfiles/soldier/Dockerfile
build/dockerfiles/soldier/sql.sh
cmd/soldier/main.go
conf/soldier/soldier.yaml
go.mod
modules/soldier/auth/auth.go
modules/soldier/autoop/action.go
modules/soldier/autoop/collect.go
modules/soldier/autoop/cron.go
modules/soldier/autoop/env.go
modules/soldier/autoop/env_test.go
modules/soldier/autoop/handler.go
modules/soldier/autoop/writer.go
modules/soldier/autoop/writer_test.go
modules/soldier/client/client.go
modules/soldier/command/command.go
modules/soldier/command/dump.go
modules/soldier/command/terminal.go
modules/soldier/conf/conf.go
modules/soldier/initialize.go
modules/soldier/mysql/mysql.go
modules/soldier/provider.go
modules/soldier/proxy/proxy.go
modules/soldier/registry/remove_layers.go
modules/soldier/registry/remove_manifests.go
modules/soldier/settings/settings.go

/kind feature
Init soldier module
- New image has been validated in the development environment.
go.mod
- Upgrade kr/pty to version v1.1.8, suite golang 1.15.
Fixes #
/assgin @luobily @sixther-dc 
```release-note
```
```docs
```

init soldier module

---

pkg/customhttp/request.go

/kind bug
Since netportal always in default namespace when deploy in k8s.

Adjust netportal default address

---

modules/monitor/core/metrics/index/clean.go
modules/monitor/core/metrics/index/disk_checker.go
modules/monitor/core/metrics/index/manager.go
modules/monitor/core/metrics/index/provider.go
modules/monitor/core/metrics/index/rollover.go
modules/monitor/core/metrics/index/ttl.go

- Translate content of the annotation 
- Repair metrics index injection mode
Special notes for your reviewer:
thx for review
Specified Reivewers:
Kindhearted person
Does this PR introduce a user-facing change?
NONE

Metrics index internationalization

---

modules/scheduler/executor/plugins/k8s/daemonset.go
modules/scheduler/executor/plugins/k8s/deployment.go
modules/scheduler/executor/plugins/k8s/secret.go
modules/scheduler/executor/plugins/k8sjob/job.go

/kind bug
fix(scheduler): support to create the volume of ds when use bind in YAML
Fixes #
/assgin @luobily @sixther-dc @johnlanni 
```release-note
```
```docs
```

fix(scheduler): support to create the volume of ds when use bind in YAML

---

build/scripts/docker_image.sh

/kind bug
the root directory name is not fixed

change all-in-one image name

---

build/dockerfiles/Dockerfile

/kind bug
gittar need find the libgit2.so
/assgin @johnlanni

add LD_LIBRARY_PATH for gittar

---

README.md

remove the codecov from readme

remove the codecov from readme

---

modules/pipeline/pipengine/actionexecutor/plugins/apitest/logic/main.go
modules/pipeline/pipengine/actionexecutor/plugins/apitest/logic/netportal.go
modules/pipeline/pipengine/actionexecutor/plugins/apitest/logic/netportal_test.go
modules/pipeline/pipengine/reconciler/taskrun/taskop/prepare.go
pkg/apitestsv2/apitest.go
pkg/apitestsv2/netportal.go
pkg/apitestsv2/netportal_test.go
pkg/apitestsv2/url.go

feature
pipeline apitest actionexexutor access api through netportal

pipeline apitest actionexexutor access api through netportal

---

build/dockerfiles/Dockerfile
cmd/monitor/main.go
conf/monitor/monitor.yaml
go.mod
go.sum

- Add monitor module health check to start the container smoothly
- Synchronous common conf setting route
Does this PR introduce a user-facing change?
NONE

Monitor module container start repair

---

modules/monitor/core/metrics/metricq/provider.go

- Open metrics to query related api
Does this PR introduce a user-facing change?
NONE

Open metrics to query related api

---

apistructs/pipeline_event.go
modules/pipeline/dbclient/op_pipeline_event.go
modules/pipeline/events/emit.go
modules/pipeline/events/event_pipeline_stream.go
modules/pipeline/pipengine/reconciler/queuemanage/queue/range_pending_queue.go

fix
Pipeline queueManager fix stream event's timestamp

Pipeline queueManager fix stream event's timestamp

---

modules/pipeline/pipengine/reconciler/taskrun/taskop/prepare.go

feature
disable PipelineVolume all pipeline task close volume

disable PipelineVolume all pipeline task close volume

---

build/dockerfiles/Dockerfile
pkg/jsonpath/jackson.go
pkg/jsonpath/jq.go

feature
update jackson version to fix linux long args error

update jackson version to fix linux long args error

---

apistructs/openapi.go
modules/eventbox/conf/conf.go
modules/eventbox/webhook/builtin.go
modules/openapi/conf/conf.go
modules/openapi/proxy/director.go
modules/openapi/proxy/director_test.go

/kind feature
our service's domain name is fixed(e.g. "xxx.default.svc.cluster.local"), we need make the domain name is configurable
/assgin @Effet

support config k8s fqdn

---

cmd/uc-adaptor/main.go
conf/uc-adaptor/uc-adaptor.yaml
modules/uc-adaptor/conf/conf.go
modules/uc-adaptor/dao/mysql.go
modules/uc-adaptor/dao/uc_sync_record.go
modules/uc-adaptor/endpoints/endpoints.go
modules/uc-adaptor/endpoints/info.go
modules/uc-adaptor/initialize.go
modules/uc-adaptor/provider.go
modules/uc-adaptor/service/adaptor/recevier_audit.go
modules/uc-adaptor/service/adaptor/recevier_members.go
modules/uc-adaptor/service/adaptor/ucadaptor.go
modules/uc-adaptor/ucclient/ucclient.go

/kind feature
move uc-adaptor out
/assgin @Effet

move uc-adaptor out

---

.gitignore
quick-start/docker-compose.yml
quick-start/kratos/identity.schema.json
quick-start/kratos/kratos.yml

/kind feature
use kratos to replace uc
Fixes #
/assgin @sfwn

quickstart changes: use kratos to replace uc

---

modules/pipeline/pipengine/reconciler/taskrun/taskop/prepare.go
modules/pipeline/services/pipelinesvc/create_task.go
modules/pipeline/services/pipelinesvc/create_task_test.go
modules/pipeline/services/pipelinesvc/pipeline_resources_test.go
modules/pipeline/services/pipelinesvc/user_test.go

bug
Fix the processing logic of the task request resource in queue.

Fix the processing logic of the task request resource in queue

---

quick-start/docker-compose.yml

feature
quick start on local need to do database migration by this tool
Fixes #
@Effet  🙏  
```release-note
```
```docs
```

feature: add dbmigration-4 to quick-start

---

apistructs/event.go
apistructs/pipeline_dto.go
modules/pipeline/events/event_pipeline.go
modules/pipeline/services/pipelinesvc/detail.go

feature
pipeline detail provides k8s-like stream events info

pipeline detail provides k8s-like stream events info

---

modules/monitor/apm/topology/topology.go

- Support trace translation time limit and optimize sort
Does this PR introduce a user-facing change?
NONE

Support trace translation time limit and optimize sort

---

conf/monitor/i18n/topology.yml
modules/monitor/apm/topology/routes.go
modules/monitor/apm/topology/topology.go

Support: add service instance state API

---

conf/dicehub/dicehub.yaml
modules/openapi/component-protocol/scenarios/org-list-all/components/list/model.go
modules/openapi/component-protocol/scenarios/org-list-all/components/list/render.go
modules/openapi/component-protocol/scenarios/org-list-all/protocol.yml
modules/openapi/component-protocol/scenarios/project-list-all/components/list/list.go
modules/openapi/component-protocol/scenarios/project-list-my/components/list/list.go

feature
Update project icons, fix dicehub metric endpoint
Fixes #
@Effet 
```release-note
```
```docs
```

Update project icons, fix dicehub metric endpoint

---

conf/hepa/hepa.yaml
go.mod
go.sum
modules/hepa/provider.go
modules/hepa/repository/orm/base_ability.go

/kind bug
1. fix the db sources config field.
2. fix the xormplus version for supporting open a new session in one connection.
3. fix orm baserow tag

fix hepa's config and update depenency of xormplus

---

build/dockerfiles/soldier/Dockerfile

/kind bug
add mariadb-client package to soldier Dockerfile, support `mysql` command.
Fixes #
/assgin @luobily 
```release-note
```
```docs
```

add mariadb-client package

---

.github/workflows/ci-it.yml
apistructs/pipeline_dto.go
apistructs/pipeline_dto_test.go
modules/pipeline/pipengine/reconciler/taskrun/taskop/prepare.go

feature
bugfix some pipeline task run error: declared volume not found in job.Volumes after taskRun.Start done, storage: dice-local-volume

bugfix some pipeline task run error: declared volume not found in job.Volumes after taskRun.Start done, storage: dice-local-volume

---

modules/openapi/component-protocol/scenarios/auto-test-scenes/components/inParamsForm/inParamsForm.go
modules/openapi/component-protocol/scenarios/auto-test-scenes/components/outPutForm/outPutForm.go

feature
autotest inParams add width

autotest inParams add width

---

go.mod
modules/pipeline/pipengine/reconciler/queuemanage/manager/pipeline.go
modules/pipeline/pipengine/reconciler/queuemanage/queue/add_pipeline.go
modules/pipeline/pipengine/reconciler/queuemanage/queue/define.go
modules/pipeline/pipengine/reconciler/queuemanage/queue/range_pending_queue.go
modules/pipeline/pipengine/reconciler/queuemanage/queue/start.go
modules/pipeline/pipengine/reconciler/queuemanage/queue/usage.go
pkg/numeral/decimal.go
pkg/numeral/decimal_test.go

Reconciler queue manager support fast reRange

---

modules/pipeline/pipengine/reconciler/taskrun/taskop/prepare.go

bug
Some error was ate at task prepare step.

Task prepare step return error correctly

---

modules/cmdb/conf/conf.go
modules/cmdb/services/org/org.go
modules/cmdb/services/org/org_test.go

feature
Make org auth compatible with multiple root domain
Fixes #
@Effet 
```release-note
```
```docs
```

Make org auth compatible with multiple root domain

---

modules/extensions/loghub/metrics/analysis/processors/processors_test.go
modules/monitor/core/metrics/index/clean.go
modules/monitor/core/metrics/index/disk_checker.go
modules/monitor/core/metrics/index/manager.go
modules/monitor/core/metrics/index/rollover.go
modules/monitor/core/metrics/storage/meta_processor.go
modules/pipeline/dbclient/op_pipeline_queue_test.go
pkg/router/router_test.go
pkg/sqllint/linters/allowed_stmt_linter_test.go
pkg/sqlparser/ddlreverser/reverser_test.go
pkg/sqlparser/ddlreverser/slice_test.go

- Metrics index module optimize
/kind bug
- Optimize generate a limited range of weighted random number writing 
- Supply error judgment

Metrics index module optimize

---

go.mod
go.sum
modules/hepa/repository/service/gateway_kong_info_service.go

/kind feature
When the address of kong starts with "http://", the "inet://" header is automatically spliced ​​to be compatible with the new address generation method

optimize kong's address acquisition logic

---

modules/gittar/conf/conf.go
modules/gittar/initialize.go
modules/gittar/pkg/gc/gc.go
modules/gittar/pkg/limit_sync_group/group.go
modules/gittar/pkg/limit_sync_group/wait_test.go

feature
If you do not clean up the git warehouse regularly, too long a time will cause the access to the warehouse to time out

cron task to clean up the repository

---

pkg/sqlparser/migrator/db.go
pkg/sqlparser/migrator/model.go
pkg/sqlparser/migrator/scripts.go

feature
this is dependency of erda migration tools.
the ClearSandbox can clear sandbox status before every module's migration. 
Fixes #
@johnlanni 
```release-note
```
```docs
```

feature: add function to clear sandbox

---

apistructs/application.go
modules/cmdb/endpoints/application.go

bug
update git repo to solve the problem of git clone
Fixes #
```release-note
```
```docs
```

fix: update git repo to solve the problem of git clone

---

README.md
modules/scheduler/endpoints/endpoints.go
modules/scheduler/executor/plugins/k8sjob/job.go
modules/scheduler/impl/job/job.go
modules/scheduler/impl/job/stop.go

/kind bug
feat(prefix): change dice prefix to erda
Fixes #

The scheduler doesn't delete namespace when set retainNamespace is true

---

modules/pipeline/conf/conf.go
modules/pipeline/pipengine/actionexecutor/plugins/apitest/logic/main.go
pkg/apitestsv2/apitest.go
pkg/apitestsv2/netportal.go
pkg/apitestsv2/netportal_test.go
pkg/apitestsv2/options.go

feature
API-TEST support judge whether to use netportal by host

API-TEST support judge whether to use netportal by host

---

modules/cmdb/services/issue/export.go

bug
Check issues empty when renaming table
Fixes #
@sfwn @Effet 
```release-note
```
```docs
```

Fix export excel when issue table is empty

---

modules/openapi/auth/user.go

feature
Make openapi org auth compatible with empty org info
Fixes #
@sfwn 
```release-note
```
```docs
```

Make openapi org auth compatible with empty org info

---

modules/scheduler/executor/plugins/k8sjob/job.go

/kind bug
- fix(scheduler): adapt job for edas platform
Fixes #
/assgin @luobily 
```release-note
```
```docs
```

fix(scheduler): adapt job for edas platform

---

.github/PULL_REQUEST_TEMPLATE.md

/kind cleanup
update PULL REUQEST TEMPLATE.md
/assgin @luobily @huangzx618

update PULL REUQEST TEMPLATE.md

---

modules/qa/dao/autotest_scene_step.go

feature
Steps are added to the two scenes separately. These two steps will be associated. This is wrong. should filter by scene id when querying the database.

bug fix scene step add, other scene will lost

---

modules/openapi/component-protocol/scenarios/home-page-content/components/emptyProjectContent/render.go
modules/openapi/component-protocol/scenarios/home-page-content/components/tableGroup/model.go
modules/openapi/component-protocol/scenarios/home-page-content/components/tableGroup/render.go
modules/openapi/component-protocol/scenarios/home-page-sidebar/components/myProjectTitle/render.go
modules/openapi/component-protocol/scenarios/home-page-sidebar/protocol.yml

/kind fix
Fixes # modify workbench style
/assgin

modify workbench components style

---

modules/qa/endpoints/testplan.go
modules/qa/services/testcase/paging.go

bug
fix: update the total of the list to fix the bug of paging
Fixes #

fix: update the total of the list to fix the bug of paging

---

modules/cmdb/dao/issue.go
modules/openapi/component-protocol/scenarios/issue-manage/components/issueFilter/model.go
modules/openapi/component-protocol/scenarios/issue-manage/components/issueTable/render.go

feature
Display id in issue table, add search by issue id
Fixes #
@Effet @sfwn

Display id in issue table, search by issue title and id

---

modules/openapi/component-protocol/scenarios/auto-test-scenes/components/apiEditor/helper.go

apitest add width

---

modules/cmdb/services/approve/approve.go

/kind bug
/kind bug
/kind cleanup
/kind feature
/kind design
fix: modify the url to solve the jump failure problem
Fixes #

fix: modify the url to solve the jump failure problem

---

modules/openapi/component-protocol/scenarios/auto-test-scenes/protocol.yml
modules/scheduler/conf/conf.go
modules/scheduler/impl/terminal/terminal.go

feature
Scheduler support multiple root domain.
Alert info position adjust in auto test execution page.
Fixes #
@Effet @sfwn

Scheduler support multiple root domain, alert info position adjust in auto test execution page.

---

modules/pipeline/services/crondsvc/crond.go

/kind bug
fix pipeline crond snapshot mutex seize bug
Fixes #

fix pipeline crond snapshot mutex seize bug

---

modules/openapi/component-protocol/scenarios/auto-test-scenes/components/apiEditor/helper.go

apitest reduce width

---

modules/openapi/component-protocol/scenarios/home-page-content/components/emptyProjectTitle/render.go
modules/openapi/component-protocol/scenarios/home-page-content/components/tableGroup/render.go
modules/openapi/component-protocol/scenarios/home-page-sidebar/components/myApplicationList/render.go
modules/openapi/component-protocol/scenarios/home-page-sidebar/components/myProjectList/render.go
modules/openapi/component-protocol/scenarios/home-page-sidebar/components/orgSwitch/render.go

/kind bug
modify display name to name

change org,project,app display name to name

---

modules/qa/services/autotest/global_config.go
modules/qa/services/autotest_v2/scene.go

/kind feature
autotest global config if is random expression use same value

autotest global config if is random expression use same value

---

apistructs/testplan.go
modules/cmdb/services/issuepanel/issue_panel.go

feature
Enable test plan cases excel batch export filter issue custom board
@Effet  @sfwn

Enable test plan cases excel batch export, filter issue custom board

---

modules/pipeline/commonutil/statusutil/status.go
modules/pipeline/commonutil/statusutil/status_test.go
modules/pipeline/pipengine/reconciler/reconcile.go

feature
CalculatePipelineTaskAllDone mean all task was end, bug now if have one task status is error function will return true

CalculatePipelineTaskAllDone mean all task was end, bug now if have one task status is error function will return true

---

modules/pipeline/services/pipelinesvc/detail.go
modules/pipeline/services/pipelinesvc/graph.go

/kind feature
SearchExtensions filter same action type

SearchExtensions filter same action type

---

modules/qa/services/autotest/global_config.go
pkg/parser/pipelineyml/visitor_secret.go

/kind feature
autotest global random use same value

autotest global random use same value

---

apistructs/manual_review.go
modules/cmdb/dao/manual_review.go
modules/cmdb/endpoints/manual_review.go
modules/cmdb/services/manual_review/manual_review.go
modules/openapi/component-protocol/scenarios/action/components/actionForm/render.go

/kind feature
manual review interface return user info

manual review interface return user info

---

build/dockerfiles/base/Dockerfile
modules/orchestrator/services/addon/addon.go
modules/orchestrator/services/addon/addon_helper.go
modules/orchestrator/services/addon/addon_helper_test.go

/kind bug
1. [create certificate failed](https://erda-org.erda.cloud/workBench/projects/387/issues/all?id=59798&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls0MzZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDQzNiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=436&type=BUG)
2. [can't delete custom addon password](https://erda-org.erda.cloud/workBench/projects/387/issues/all?id=57008&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls0MzZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDQzNiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGrou …

fix custom addon can't delete password

---

modules/monitor/alert/storage/alert-record/consumer.go
modules/monitor/notify/storage/notify-record/consumer.go

/kind bug
fix the bug of alert list is empty
Fixes #
Specified Reivewers:
/assgin @liuhaoyang

fix the bug of alert list is empty

---

modules/monitor/alert/storage/alert-record/consumer.go
modules/monitor/notify/storage/notify-record/consumer.go

/kind fix
fix the bug of record insert into mysql is failed
@recallsong

fix the bug of record insert into mysql is failed

---

modules/actionagent/callback_test.go
modules/monitor/core/metrics/metricq/es-tsql/functions.go
modules/monitor/core/metrics/metricq/es-tsql/functions_test.go
modules/openapi/api/apis/uc/uc_user_export_test.go

What type of PR is this?
Complete unit test of custom function without environment dependency in SELECT.
/kind unit test

Unit test coverage optimize for metrics query module

---

modules/hepa/gateway/service/gateway_openapi_consumer_service.go

/kind bug
If there is no api authz rule, display the endpoint authz infos.

fix api authz bug

---

modules/openapi/component-protocol/scenarios/issue-manage/components/issueTable/render.go

feature
Reset pageNo by filter conditions in issue table
@sfwn

Reset pageNo by filter conditions in issue table

---

apistructs/testcase.go
modules/qa/services/testcase/export.go
modules/qa/services/testcase/export_excel.go
modules/qa/services/testcase/export_xmind.go

bug
Too many needless db requests for testset quering. Polish it.
Already tested in dev and passed.

qa manual testcase export reduce needless db requests

---

modules/hepa/gateway/service/gateway_domain_service.go
modules/hepa/repository/service/gateway_az_info_service.go
modules/hepa/repository/service/interface.go

/kind bug
when cluster changed, the runtime's domain need update normally.

fix change cluster issue

---

modules/cmdb/services/issue/import.go

bug
Reset failed imported issue and import stat
@sfwn

Reset failed imported issue and import stat

---

.golangci.yml

/kind feature
/kind bug
/kind cleanup
/kind feature
/kind design
add exclude
Fixes #
/assgin @sfwn

add exclude

---

apistructs/issue.go
modules/openapi/component-protocol/scenarios/issue-manage/components/issueKanban/issue_kanban.go
pkg/erda-configs/permission/backend/sys/org/project/project.yml

/kind bug
fix 1.0 bugs
Fixes
1. [epic's permission error](https://erda-org.erda.cloud/workBench/projects/387/issues/all?id=60328&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDQzNiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=436&type=BUG) 
2. [remove issueKanban's MoveOutOperation](https://erda-org.erda.cloud/workBench/projects/387/issues/all?id=60429&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiLCJET05FIl0sImFzc2lnbmVlSURzIjpbIjEwMDA0MzYiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6Imthb …

remove issueKanban's MoveOutOperation and modify issue epic's permission

---

modules/cmdb/conf/conf.go
modules/cmdb/endpoints/file.go

cherry-pick for [pr#408](https://github.com/erda-project/erda/pull/408)

hotfix: cmdb disable file permission check for multi-domain temporarily

---

modules/gittar-adaptor/conf/conf.go
modules/gittar-adaptor/initialize.go

/kind feature
make bundle timeout configurable through env.

gittar-adaptor: make bundle timeout configurable

---

docs/guides/deploy/How-to-install-the-Erda.md

update(install_doc): update install document for user

---

modules/scheduler/executor/plugins/k8s/deployment.go
modules/scheduler/executor/plugins/k8s/runtime.go
modules/scheduler/executor/util/util.go

- fix(scheduler): get the mistaken name of service dependency
Fixes #

fix(scheduler): get the mistaken name of service dependency

---

docs/guides/deploy/How-to-install-the-Erda.md

- update(install_doc): update install document for user 
Fixes #

update(install_doc): update install document for user 

---

modules/cmdb/dao/issue_stage.go
modules/cmdb/endpoints/issue.go
modules/cmdb/services/issue/convert.go
modules/cmdb/services/issue/export.go

/kind bug
fix: update the excel export of task and bug
Fixes #
https://erda-org.erda.cloud/workBench/projects/387/issues/all?id=60249&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMTI2MSJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=-1&type=BUG
/assgin @sfwn

fix: update the excel export of task and bug

---

modules/cmdb/conf/conf.go
modules/cmdb/endpoints/file.go

/kind bug
optimize file upload to avoid OOM 
Fixes #
/assgin @sfwn

optimize file upload to avoid OOM 

---

modules/cmdb/conf/conf.go
modules/openapi/component-protocol/scenarios/issue-manage/components/issueFilter/render.go

/kind bug
/kind cleanup
/kind feature
/kind design
Fix org auth, add legacy UI public address
Fixes #
@sfwn

Fix org auth, add legacy UI public address

---

modules/cmdb/conf/conf.go
modules/openapi/component-protocol/scenarios/issue-manage/components/issueFilter/render.go

feature
Fix org auth, add legacy UI public address
Delay time when changing issue filter conditions
@sfwn

Fix org auth, add legacy UI public address (#429)

---

modules/openapi/component-protocol/scenarios/issue-manage/components/issueTable/render.go
modules/openapi/component-protocol/scenarios/issue-manage/components/issueTable/render_test.go

/kind bug
fix: update the table list return of component protocol
https://erda-org.erda.cloud/erda/workBench/projects/387/issues/all?id=60835&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMTI2MSJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=429&type=BUG
/assgin @QvodSoldier

fix: update the table list return of component protocol

---

pkg/storage/fs.go

bug
upload the file return after flush the file in-memory to disk
Fixes #

upload the file return after flush the file in-memory to disk

---

apistructs/pipeline_yml.go
pkg/parser/pipelineyml/graph_pipelineyml.go

/kind bug
user save pipeline will lost action caches

pipeline graph lost action caches

---

.github/PULL_REQUEST_TEMPLATE.md
apistructs/issue.go
modules/cmdb/dao/issue.go
modules/openapi/component-protocol/scenarios/issue-manage/components/issueFilter/model.go
modules/openapi/component-protocol/scenarios/issue-manage/components/issueFilter/state.go
modules/openapi/component-protocol/scenarios/issue-manage/components/issueFilter/state_conditions.go
modules/openapi/component-protocol/scenarios/issue-manage/components/issueTable/render.go
modules/openapi/component-protocol/scenarios/issue-manage/scenario.go

feature
Bug closed time and item pagination in issue table, typo in pr template
@Effet  @sfwn

Bug closed time and item pagination in issue table, typo in pr template

---

modules/ops/impl/aliyun-resources/redis/factory.go
modules/ops/impl/aliyun-resources/redis/get.go

/kind bug
Create redis bugfix
Originally, redis will be created in the vswitch which has ecs; but this vswithc may not allowed to create redis; now available vswitch/zone got from official api;
Specified Reivewers:

redis create bugfix

---

modules/ops/impl/aliyun-resources/oss/object.go
modules/ops/impl/aliyun-resources/overview/overview.go

/kind bug
overview optimize & add more debug info
overview optimize & add more debug info
Specified Reivewers:

overview optimize

---

modules/scheduler/endpoints/endpoints.go
modules/scheduler/executor/plugins/edas/edas.go
modules/scheduler/executor/plugins/k8s/instanceinfosync/sync.go
modules/scheduler/executor/plugins/k8sjob/job.go
modules/scheduler/impl/job/job.go
modules/scheduler/impl/job/stop.go

/kind bug
- fix(scheduler): leak namespace
Fixes #

fix(scheduler): leak namespace

---

modules/pipeline/pipengine/actionexecutor/plugins/scheduler/scheduler.go

/kind bug
loop task cannot cancel, loop task cannot cancel, task uuid error should be include loop times

loop task cannot cancel

---

modules/cmdb/endpoints/endpoints.go
modules/cmdb/endpoints/health.go

feature
cmdb component health check interface
@Effet @sfwn

Setup cmdb component health check interface

---

bundle/servicegroup.go
modules/orchestrator/conf/conf.go
modules/orchestrator/services/deployment/deployment.go
modules/orchestrator/services/deployment/deployment_context.go
modules/orchestrator/services/runtime/runtime.go

modify timeout of InspectServiceGroupWithTimeout

---

modules/cluster-dialer/server/tunnel-server_test.go

/kind bug
ut may failure when client connected, but server not process yet.

fix ut failure

---

.erda/migrations/config.yml
go.mod
go.sum
pkg/sqllint/configuration/configuration.go
pkg/sqllint/configuration/default.go
pkg/sqllint/configuration/default_test.go
pkg/sqllint/linters/explicit_collation_linter.go
pkg/sqllint/linters/explicit_collation_linter_test.go
pkg/sqllint/linters/index_length_linter.go

/kind feature
add explicit collation linter
Fixes #
/assign @johnlanni

feature: add explicit collation linter

---

modules/cmdb/services/member/member.go

/kind feature
work with kratos, make first user as admin
Fixes #
/assign @sfwn

feat: first user become admin, only if kratos enabled

---

modules/monitor/core/metrics/metricq/es-tsql/influxql/functions.go

/kind bug
Fixes #
fix the unit when targetTimeUnit be unset.

ElasticSearch custom function diffps unit fixed

---

conf/monitor/monitor/monitor.yaml
modules/monitor/alert/alert-apis/adapt/customize.go
modules/monitor/alert/alert-apis/provider.go

/kind bug
Hide fields that should not be displayed
Fixes #

Hide fields that should not be displayed

---

apistructs/pipeline_queue.go
modules/pipeline/aop/plugins/pipeline/plugins/precheck_before_pop/before_run_check.go
modules/pipeline/aop/plugins/pipeline/plugins/precheck_before_pop/plugin.go
modules/pipeline/pipengine/reconciler/queuemanage/queue/range_pending_queue.go

/kind feature
before run check add millisecond field

before run check add millisecond field

---

codecov.yml

adjust
Adjust codecov project target from 15% to 10%

Adjust codecov project target from 15% to 10%

---

modules/pipeline/pipengine/queue/priorityqueue/priority_queue.go
modules/pipeline/pipengine/queue/priorityqueue/priority_queue_test.go
modules/pipeline/pipengine/reconciler/queuemanage/queue/add_pipeline.go
modules/pipeline/pipengine/reconciler/queuemanage/queue/define.go
modules/pipeline/pipengine/reconciler/queuemanage/queue/range_pending_queue.go

feature
Queue set needReRangePendingQueue flag if newItem's order is higher than the current ranging one.

feature(pipeline): queue polish the logic to set needReRangePendingQueue flag

---

modules/monitor/apm/topology/topology.go

/kind bug
Switch the exception analysis list from looking up Cassandra to ElasticSearch, and adjust part of the logic.
Fixed the problem of occasionally querying invalid empty data to optimize performance.

Reconstruction anomaly analysis

---

quick-start/docker-compose.yml

/kind bug
Fixes #
/assign @sfwn

fix: org create failure in local erda

---

apistructs/openapi.go
modules/eventbox/webhook/builtin.go
modules/gittar/conf/conf.go

Fix the ci problem of erda self

---

modules/monitor/apm/topology/topology.go

/kind bug
/kind cleanup
/kind feature
/kind design
Fixes #

External topology node data

---

.golangci.yml

/kind bug
fix exclude
/assign @sfwn 

fix golangci exclude

---

apistructs/testcase.go
apistructs/testplan.go
modules/qa/dbclient/apitest.go
modules/qa/services/testcase/apis.go
modules/qa/services/testcase/apitest.go
modules/qa/services/testcase/convert.go
modules/qa/services/testcase/export.go
modules/qa/services/testcase/export_excel.go
modules/qa/services/testcase/paging.go
modules/qa/services/testplan/export.go
pkg/excel/export_by_cell.go

/kind polish
- Manual testcase export use batch processing
- limit: max allowed number for testcase export: 2000, and tell user to use xmind
- [Erda Cloud Issue Link](https://erda.cloud/erda/workBench/projects/387/issues/all?id=64916&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiOTIiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=-1&type=BUG)
yes. /cherry-pick release/1.0

polish manual testcase export

---

modules/gittar/conf/conf.go
modules/gittar/uc/user_center.go
modules/openapi/component-protocol/scenarios/issue-manage/components/issueTable/render.go
modules/openapi/hooks/posthandle/injectuserinfo.go
modules/openapi/hooks/posthandle/injectuserinfo_test.go
pkg/ucauth/kratos.go
pkg/ucauth/user_admin.go

feature
Add kratos config in gittar, openapi posthandler
@Effet

Add kratos config in gittar, openapi posthandler

---

conf/msp/msp.yaml
go.mod
go.sum
modules/msp/instance/db/instance_tenant.go
modules/msp/instance/db/tables.go
modules/msp/instance/db/tmc.go
modules/msp/instance/permission/permission.go
modules/msp/instance/permission/provider.go
modules/msp/instance/service_type.go
modules/msp/menu/provider.go
modules/msp/menu/test.http
pkg/common/permission/error.go
pkg/common/permission/permission.go
pkg/common/permission/permission_test.go
pkg/common/permission/provider.go

/kind polish
1、permission interceptor
@liuhaoyang 
no

permission interceptor

---

README.md
docs/guides/deploy/How-to-install-the-Erda-zh.md
docs/guides/deploy/How-to-install-the-Erda.md

/kind document
- docs(install): add simplified chinese install doc
Add comments like `/cherry-pick release/1.0` when this PR is merged.

docs(install): add simplified chinese install doc

---

docs/guides/deploy/How-to-install-the-Erda-zh.md
docs/guides/deploy/How-to-install-the-Erda.md

/kind document
- update(docs): update install documents format

update(docs): update install documents format

---

README.md
docs/guides/deploy/How-to-install-Erda-zh.md
docs/guides/deploy/How-to-install-Erda.md

/kind document
- update(doc): add Simplified Chinese install document

update(doc): add Simplified Chinese install document

---

modules/openapi/component-protocol/scenarios/project-list-my/components/emptyText/model.go
modules/openapi/component-protocol/scenarios/project-list-my/components/emptyText/render.go

feature
Modify link to public project menu in my projects page
@Effet @sfwn

Modify link to public project menu in my projects page

---

.github/workflows/ci-it.yml
tools/cli/cmd/migration_lint.go

/kind feature
add Erda MySQL Lint to github pr ci
/assign @sfwn

feature: add migration lint to github ci

---

modules/pipeline/services/pipelinesvc/create.go

bugfix
/kind bug
batch create pipeline lost storageConfig then pipeline run will lost nfs volume

batch create pipeline lost storageConfig then pipeline run will lost nfs volume

---

modules/cmdb/services/issue/issue.go

/kind bug
issue retain:
- creator
- assignee
- createdAt
- manHour 
after type changing
- [Erda Cloud Issue Link](https://erda.cloud/erda/workBench/projects/387/issues/all?id=66035&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiOTIiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=436&type=BUG)
- [Erda Cloud Issue Link](https://erda.cloud/erda/workBench/projects/387/issues/all?id=66222&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiOTIiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueV …

bugfix(dop): issue retain creator&assignee&createdAt&manHour after type changing

---

cmd/msp/main.go
conf/msp/msp.yaml
go.mod
go.sum
modules/msp/configcenter/config.center.service.go
modules/msp/configcenter/nacos/adapter.go
modules/msp/instance/connom.go
modules/msp/instance/db/instance.go
modules/msp/instance/db/instance_tenant.go
modules/msp/instance/db/tables.go
modules/msp/registercenter/nacos/adapter.go
modules/msp/registercenter/nacos/service_search_result.go
modules/msp/registercenter/provider.go
modules/msp/registercenter/register.center.service.go
modules/msp/registercenter/register.center.service.host.go
modules/msp/registercenter/register.center.service.host.runtime.go
modules/msp/registercenter/register.center.service.monitor.go
modules/msp/registercenter/register.center.service.route.go
modules/msp/registercenter/zkproxy/adapter.go
pkg/common/apis/response.go
pkg/common/errors/parameter_test.go
pkg/database/gormutil/gorm.go
pkg/http/httputil/url.go
pkg/http/httputil/url_test.go

/kind feature
1、add msp registercenter apis
@liuhaoyang 
no

msp registercenter api

---

modules/monitor/apm/topology/topology.go

/kind bug
- Fixes #66559
- [Erda Cloud Issue Link](Fix the problem that the forced conversion may be abnormal )

Fix the problem that the forced conversion may be abnormal

---

apistructs/org.go
modules/cmdb/endpoints/organization.go
modules/cmdb/model/organization.go
modules/cmdb/services/org/org.go
modules/openapi/component-protocol/scenarios/home-page-sidebar/components/orgFormModal/render.go

/kind feature
add free org and only admin could create paying org
/assign @Effet

add free org

---

pkg/erda-configs/permission/backend/sys/org/project/project.yml

feature
Add PD,QA,Dev in issue type role permission
/assign @Effet

Add PD,QA,Dev in issue type update role permission

---

modules/openapi/component-protocol/scenarios/issue-manage/components/issueTable/render.go

bug
Hide and reorder disabled Issue state button in issue table
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/workBench/projects/387/issues/all?id=63953&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMTA3MyJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=-1&type=BUG)

Hide and reorder disabled Issue state button in issue table

---

apistructs/runtime_dto.go
modules/orchestrator/services/runtime/runtime.go

/kind bug
If a workspace has multiple runtimes, the list runtime only returns one runtime
Not needed

list runtime doesn't return all runtimes

---

modules/openapi/api/apis/openapi/component_protocol/render.go
modules/openapi/component-protocol/scenario_render.go

bugfix
/kind bug
render return error then continue render info and show error info

render return error then continue render info and show error info

---

erda.yml
modules/cluster-manager/conf/conf.go
modules/ecp/conf/conf.go

/kind feature
add cluster-manager && cluster-dialer module.

feature: add cluster-manager && cluster-dialer

---

.github/workflows/ci-it.yml
modules/scheduler/endpoints/endpoints.go
modules/scheduler/executor/executortypes/types.go
modules/scheduler/executor/plugins/demo/demo.go
modules/scheduler/executor/plugins/edas/edas.go
modules/scheduler/executor/plugins/flink/flink.go
modules/scheduler/executor/plugins/k8s/deployment.go
modules/scheduler/executor/plugins/k8s/k8s.go
modules/scheduler/executor/plugins/k8sflink/flink.go
modules/scheduler/executor/plugins/k8sjob/job.go
modules/scheduler/executor/plugins/k8sspark/spark.go
modules/scheduler/executor/plugins/marathon/marathon.go
modules/scheduler/executor/plugins/metronome/metronome.go
modules/scheduler/executor/plugins/spark/spark.go
modules/scheduler/impl/servicegroup/scale.go
modules/scheduler/impl/servicegroup/servicegroup.go
modules/scheduler/server/server.go
modules/scheduler/task/task.go

/kind feature
- feat(scale): support scale the resource not restart pod

feat(scale): support scale the resource not restart pod

---

modules/scheduler/endpoints/endpoints.go
modules/scheduler/executor/plugins/k8sjob/job.go

/kind bug
- fix(job): update specify namespace error when deal job

fix(job): update specify namespace error when deal job

---

.github/workflows/ci-it.yml
modules/scheduler/endpoints/endpoints.go
modules/scheduler/executor/executortypes/types.go
modules/scheduler/executor/plugins/demo/demo.go
modules/scheduler/executor/plugins/edas/edas.go
modules/scheduler/executor/plugins/flink/flink.go
modules/scheduler/executor/plugins/k8s/deployment.go
modules/scheduler/executor/plugins/k8s/k8s.go
modules/scheduler/executor/plugins/k8sflink/flink.go
modules/scheduler/executor/plugins/k8sjob/job.go
modules/scheduler/executor/plugins/k8sspark/spark.go
modules/scheduler/executor/plugins/marathon/marathon.go
modules/scheduler/executor/plugins/metronome/metronome.go
modules/scheduler/executor/plugins/spark/spark.go
modules/scheduler/impl/servicegroup/scale.go
modules/scheduler/impl/servicegroup/servicegroup.go
modules/scheduler/server/server.go
modules/scheduler/task/task.go

[cherry-pick] feat(scale): support scale the resource not restart pod (#633)

---

apistructs/service.go
modules/scheduler/executor/plugins/k8s/addon/elasticsearch/elasticsearch.go
modules/scheduler/executor/plugins/k8s/addon/interface.go
modules/scheduler/executor/plugins/k8s/addon/redis/legacy/redis.go
modules/scheduler/executor/plugins/k8s/addon/redis/redis.go
modules/scheduler/executor/plugins/k8s/daemonset.go
modules/scheduler/executor/plugins/k8s/deployment.go
modules/scheduler/executor/plugins/k8s/k8s.go
modules/scheduler/executor/plugins/k8s/k8s_stateful.go
modules/scheduler/executor/plugins/k8s/k8sservice/service.go
modules/scheduler/executor/plugins/k8s/runtime.go
modules/scheduler/executor/plugins/k8s/service.go

/kind bug
- fix(service): on project namespace create service error

fix(service): on project namespace create service error

---

modules/scheduler/executor/plugins/k8s/deployment.go
modules/scheduler/impl/servicegroup/scale.go

/kind bug
- feat(scale): support scale the resource not restart pod (#645)

[cherry-pick] feat(scale): support scale the resource not restart pod (#645)

---

apistructs/service.go
modules/scheduler/executor/plugins/k8s/addon/elasticsearch/elasticsearch.go
modules/scheduler/executor/plugins/k8s/addon/interface.go
modules/scheduler/executor/plugins/k8s/addon/redis/legacy/redis.go
modules/scheduler/executor/plugins/k8s/addon/redis/redis.go
modules/scheduler/executor/plugins/k8s/daemonset.go
modules/scheduler/executor/plugins/k8s/deployment.go
modules/scheduler/executor/plugins/k8s/k8s.go
modules/scheduler/executor/plugins/k8s/k8s_stateful.go
modules/scheduler/executor/plugins/k8s/k8sservice/service.go
modules/scheduler/executor/plugins/k8s/runtime.go
modules/scheduler/executor/plugins/k8s/service.go

/kind bug
- fix(service): on project namespace create service error (#634)
- 

[cherry-pick] fix(service): on project namespace create service error

---

apistructs/service.go
bundle/servicegroup.go
modules/orchestrator/dbclient/runtime_test.go
modules/orchestrator/endpoints/server_handler.go
modules/orchestrator/services/runtime/runtime.go
modules/orchestrator/services/runtime/runtime_test.go

/kind feature
Really expand and contract, not restart
- [bug](https://erda-org.erda.cloud/erda/workBench/projects/387/issues/all?id=57011&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDQzNiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=429&type=BUG)
- [task](https://erda-org.erda.cloud/erda/workBench/projects/387/issues/all?id=59983&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDQzNiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUi …

update runtime's scale

---

apistructs/file_records.go
apistructs/testcase.go
modules/dop/conf/conf.go
modules/dop/dao/file_records.go
modules/dop/endpoints/endpoints.go
modules/dop/endpoints/file_records.go
modules/dop/endpoints/testcase.go
modules/dop/initialize.go
modules/dop/services/apierrors/errors.go
modules/dop/services/testcase/export.go
modules/dop/services/testcase/file_records.go
modules/dop/services/testcase/import.go
modules/openapi/api/apis/dop/qa_records_get.go
modules/openapi/api/apis/dop/qa_records_list.go
pkg/excel/export_by_cell.go
pkg/http/httpclient/request.go
pkg/xmind/xml.go

feature
Asynchronous import/export of test cases, add file records table
@Effet @sfwn

Asynchronous import/export of test cases, add file records table

---

modules/openapi/component-protocol/scenarios/org-list-all/components/list/render.go

User in public org go to my projects instead of public projects

---

apistructs/pipeline_label.go
modules/pipeline/dbclient/op_pipeline_labels.go
modules/pipeline/endpoints/endpoints.go
modules/pipeline/endpoints/pipeline.http
modules/pipeline/endpoints/pipeline_label.go
modules/pipeline/services/apierrors/errors.go
modules/pipeline/services/pipelinesvc/create_label.go

/kind bug
batch insert pipeline labels

batch insert pipeline labels

---

apistructs/issue.go
modules/dop/dao/issue.go
modules/dop/services/issuepanel/issue_panel.go
modules/openapi/component-protocol/scenarios/issue-manage/components/issueTable/render.go

bug
Custom issue panel remove pagination params, issue button operation key update
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/workBench/projects/387/issues/all?id=62844&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMTA3MyJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=429&type=BUG)
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/workBench/projects/387/issues/all?id=63953&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMTA3MyJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&iss …

Fix custom issue panel query, issue button operation key update

---

modules/pipeline/conf/conf.go
modules/pipeline/services/pipelinesvc/cron_compensate.go
modules/pipeline/services/pipelinesvc/cron_compensate_test.go

/kind feature
before use concurrent execution cron compensate, databases cpu use will high, so use sync to compensate

use sync to strategy compensate cron job, and add cron interval conf

---

.github/workflows/ci-it.yml
modules/scheduler/executor/plugins/k8s/deployment.go
modules/scheduler/impl/servicegroup/scale.go

/kind bug
feat(resource): update request resource with ratio directly

feat(resource): update request resource with ratio directly

---

modules/cmdb/endpoints/endpoints.go
modules/cmdb/endpoints/health.go
modules/cmdb/endpoints/info.go

/kind feature
/kind bug
/kind polish
/kind document
fix: recover cmdb health check  for integrate
/assign @sfwn 

fix: recover cmdb health check for integrate

---

bundle/org.go
modules/cmdb/initialize.go
modules/cmdb/services/cluster/cluster.go

/kind bug
fix: cmdb can't get cluster
will move to admin module as quickly as possible
/assign @sfwn @Effet 

fix: cmdb can't get cluster

---

modules/core-services/conf/conf.go

/kind bug
fix: update conf of core-services

fix: update conf of core-services

---

modules/pipeline/pipengine/reconciler/task_loop.go

/kind bug
cherry-pick of #713.
File path changed, so manually cherry picked.

bugfix(pipeline): task loop reset flags for wait step timeout

---

build/dockerfiles/Dockerfile
build/dockerfiles/soldier/Dockerfile
modules/soldier/autoop/cron.go

- fix(soldier): the error file path for edas

fix(soldier): the error file path for edas

---

modules/scheduler/executor/plugins/edas/edas.go

/kind bug
- fix(edas): scale will restart pod
/assign #luobily

fix(edas): scale will restart pod

---

build/dockerfiles/Dockerfile

/kind bug
- remove tar.gz from dockerfile

remove tar.gz from dockerfile

---

modules/hepa/repository/service/gateway_kong_info_service.go
modules/hepa/repository/service/gateway_kong_info_service_test.go

/kind bug
fix kong addr acquire logic & add UT

fix kong addr acquire logic & add UT

---

build/dockerfiles/soldier/Dockerfile

/kind feature
ops was move to cmp, change dockerfile copy addr

change soldier dockerfile copy addr

---

modules/core-services/services/security/process.go

/kind feature
permission use db not use bdl

permission use db not use bdl

---

quick-start/docker-compose.yml

/kind feature
update erda-migration image in quick-start docker compose file.
/assign 

feature: update erda-migration image in quick-start

---

pkg/clusterdialer/dialer.go

/kind feature
avoid the automatic activation

optimize the init of cluster dialer's session logic

---

modules/scheduler/executor/plugins/edas/edas.go
modules/scheduler/executor/plugins/k8s/k8s.go

/kind bug
- fix(scheduler): do not create any service when port count equal 0

fix(scheduler): do not create any service when port count equal 0

---

modules/dop/initialize.go
modules/dop/services/filetree/filetree.go

/kind bug
fix: remove the case that dop call dop

fix: remove the case that dop call dop

---

pkg/clusterdialer/dialer.go

/kind bug
cluster dialer addr bug

should not make new parameter clusterDialAddr in if logic

---

modules/openapi/component-protocol/scenarios/app-pipeline-tree/protocol.yml

/kind feature
add new pipeline input length too short

add new pipeline input length too short

---

modules/scheduler/executor/plugins/k8s/deployment.go

/kind bug
- fix(scheduler): depend on inject error server name

fix(scheduler): depend on inject error server name

---

.erda/migrations/cmdb/20210702-updateMbox.sql
apistructs/event.go
apistructs/event_test.go
apistructs/issue.go
apistructs/issue_stream_locale.go
apistructs/mbox.go
bundle/events.go
modules/core-services/dao/mbox.go
modules/core-services/model/mbox.go
modules/core-services/services/mbox/mbox.go
modules/core-services/services/mbox/mbox_test.go
modules/dop/conf/conf.go
modules/dop/dao/issue.go
modules/dop/dao/issue_subscriber.go
modules/dop/endpoints/endpoints.go
modules/dop/endpoints/issue.go
modules/dop/endpoints/issue_callback.go
modules/dop/endpoints/issue_stream.go
modules/dop/services/issue/issue.go
modules/dop/services/issuestream/issue_stream.go
modules/eventbox/subscriber/email/email.go
modules/eventbox/subscriber/mbox/mbox.go
modules/openapi/api/apis/dop/cmdb_issue_subscribe.go
modules/openapi/api/apis/dop/cmdb_issue_subscribe_batchupdate.go
modules/openapi/api/apis/dop/cmdb_issue_unsubscribe.go
pkg/erda-configs/i18n/notify_item.yml

/kind feature
add personal message for issue subscriber
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/workBench/projects/387/issues/all?id=57395&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDQzNiJdfQ%3D%3D&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=429&type=REQUIREMENT)
/assign @Effet

personal message for issue

---

modules/dop/endpoints/organization.go

/kind bug
this maby cause database pressure and this interface currently does not need these data, maybe add some cache when we need these data
/assign @Effet

remove publisher id in listOrg

---

erda.yml
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sjob/k8sjob.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/logic/job.go
modules/pipeline/pipengine/reconciler/taskrun/taskop/prepare.go

/kind feature
use k8sjob executor create job volume instead of call scheduler

task prepare use k8sjob executor create volume

---

modules/core-services/services/member/member.go

downgrade log level for `become-admin` function

---

modules/msp/apm/checker/apis/test.http
modules/msp/configcenter/nacos/adapter.go
modules/msp/registercenter/nacos/adapter.go
modules/msp/registercenter/nacos/service_search_result.go
modules/msp/registercenter/provider.go
modules/msp/registercenter/test.http

/kind bug
fix register center bug
@liuhaoyang 
NO

fix register center bug

---

pkg/http/httpclient/request.go

/kind bug
invoke grpc http server require the Accept header

bugfix: httpclient add default accept header

---

bundle/approve.go
bundle/audit.go
bundle/notice.go
modules/admin/manager/approve.go
modules/admin/manager/audit.go
modules/admin/manager/cluster.go
modules/admin/manager/id.go
modules/admin/manager/manager.go
modules/admin/manager/notice.go
modules/admin/manager/user.go
modules/cmp/autoscanner/autoScanner.go

update(admin): forward api to backend and add user api

---

go.mod
go.sum
modules/openapi/api/generate/generate_doc.go

/kind feature
feature: generate oas3 document of all services when make prepare
```shell
% make prepare
% cd modules/openapi/api/generate 
generate % ls *.yml
action-runner-scheduler-swagger.yml     core-services-swagger_all.yml           fdp-master-swagger.yml                  msp-swagger_all.yml                     pipeline-swagger.yml
action-runner-scheduler-swagger_all.yml dicehub-swagger.yml                     fdp-master-swagger_all.yml              officer-swagger.yml                     pipeline-swagger_all.yml
admin-swagger.yml                       dicehub-swagger_all.yml                 gittar-swagger.yml                      officer-swagger_all.yml                 scheduler-swagger.yml
admin-swagger_all.yml                   dop-swagger.yml …
```

feature: generate oas3 document of all services when make prepare

---

CHANGELOG/CHANGELOG-1.0.md
CHANGELOG/CHANGELOG-1.1.md
CHANGELOG/CHANGELOG-template.md
CHANGELOG/README.md
README.md

/kind document
add CHANGELOG for v1.0.0 & v1.0.1.
preview: https://github.com/sfwn/erda/tree/feature/add-changelog
`/cherry-pick release/1.0` when this PR is merged.

document: add CHANGELOG

---

CHANGELOG/CHANGELOG-1.0.md
CHANGELOG/CHANGELOG-template.md

/kind document
Polish changelog [comment](https://github.com/erda-project/erda/pull/804#pullrequestreview-701707634) by @Dreamica

document: polish changelog template and 1.0.md

---

bundle/approve.go
bundle/notice.go
modules/admin/manager/notice.go
modules/cmp/autoscanner/autoScanner.go

/kind bug
- fix(admin): from json body to raw body when forward to backend

fix(admin): from json body to raw body when forward to backend

---

modules/openapi/api/apis/msp/apm/exception/exception_event.go
modules/openapi/api/apis/msp/apm/exception/exception_event_id_list.go

-/api/msp/apm/exceptions/event-ids

update exception openapi

---

go.mod
go.sum
modules/msp/resource/deploy/handlers/monitorcollector/monitor_collector.go
modules/msp/resource/provider.go
modules/msp/resource/resource.service.go
modules/openapi/api/apis/tmc/tmc_monitor_instance.go

/kind feature
migrate /api/monitor/instances/{tk} api from tmc to msp

feature: migrate /api/monitor/instances/{tk} api

---

erda.yml

/kind bug
1. make eventbox send email success in hongkong-ci, erda.yml env has a higher priority than deploy settings of application
2. adapt to the modification of msp
/assign @Effet

update erda.yml for eventbox and orchestrator

---

conf/msp/i18n/msp-i18n.yaml
conf/msp/msp.yaml
go.mod
go.sum
modules/msp/apm/trace/db/tables.go
modules/msp/apm/trace/db/trace_request_history.go
modules/msp/apm/trace/provider.go
modules/msp/apm/trace/trace.service.go
modules/msp/apm/trace/trace.service_test.go
modules/openapi/api/apis/msp/apm/trace/get_trace_debug_history.go
modules/openapi/api/apis/msp/apm/trace/get_trace_debug_history_status.go
modules/openapi/api/apis/msp/apm/trace/list_trace_debug_histories.go
modules/openapi/api/apis/msp/apm/trace/post_trace_debug_history.go
modules/openapi/api/apis/msp/apm/trace/put_trace_debug_history_stop.go

refer to:
- https://github.com/erda-project/erda-proto/pull/56
- https://github.com/erda-project/erda-proto-go/pull/42

feature: Implement Trace debug

---

modules/core-services/endpoints/user.go
modules/dop/endpoints/issue.go
modules/dop/endpoints/sonar.go
modules/dop/initialize.go
modules/dop/services/issue/issue.go
modules/dop/services/pipeline/pipeline.go
modules/dop/services/testplan/testlan_case_rel.go
modules/dop/services/testplan/testplan.go

/kind bug
ix: remove the case of call themself with dop and core-services
/assign @sfwn 

fix: remove the case of call themself with dop and core-services

---

.gitignore
apistructs/user.go
bundle/user.go
modules/admin/manager/user.go
modules/openapi/api/apis/admin/admin_user_list.go
modules/openapi/api/apis/admin/admin_user_search.go

/kind feat
- feat(admin): adapt to the user methods include search and list

feat(admin): adapt to the  methods of user model include search and list

---

modules/openapi/component-protocol/scenarios/issue-manage/components/issueFilter/props.go

bug
Add project member query pagesize as temporary solution.
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/workBench/projects/387/issues/all?id=63698&issueFilter__urlQuery=eyJ0aXRsZSI6IumhueebruWNj%2BWQjOS4reWkhOeQhuS6uuacieWtmOWcqOaQnOS4jeWIsOeahOeOsOixoSIsInN0YXRlQmVsb25ncyI6WyJPUEVOIiwiV09SS0lORyIsIldPTlRGSVgiLCJSRU9QRU4iLCJSRVNPTFZFRCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=-1&type=BUG)

Add project member query pagesize

---

modules/core-services/endpoints/organization.go
modules/core-services/utils/regexp.go
modules/core-services/utils/regexp_test.go
modules/openapi/component-protocol/scenarios/home-page-content/components/emptyOrgContent/render.go
modules/openapi/component-protocol/scenarios/home-page-sidebar/components/createProjectTip/render.go
modules/openapi/component-protocol/scenarios/home-page-sidebar/components/createProjectTipWithoutOrg/render.go
modules/openapi/component-protocol/scenarios/home-page-sidebar/components/emptyOrgText/render.go
modules/openapi/component-protocol/scenarios/home-page-sidebar/components/orgFormModal/render.go
modules/openapi/component-protocol/scenarios/home-page-sidebar/components/projectTipWithoutOrg/render.go

/kind bug
fix workbench link bug,create org pattern
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/workBench/projects/387/issues/all?id=71540&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=429&type=BUG)

modify workbench create org rule and some jump link

---

modules/msp/instance/db/instance_tenant.go
modules/msp/resource/deploy/handlers/servicemesh/servicemesh.go

bugfix: servicemesh deploy terminus_key read error

---

pkg/database/sqlparser/pygrator/package.go

/kind feature
the pip install argument `--no-cache-dir` may cause error when installing requirements.txt, fix it

feature: fix pip install command

---

modules/core-services/endpoints/organization.go
modules/core-services/utils/regexp.go
modules/core-services/utils/regexp_test.go
modules/dop/endpoints/organization.go
modules/openapi/component-protocol/scenarios/home-page-content/components/tableGroup/render.go
modules/openapi/component-protocol/scenarios/home-page-content/i18n/i18n.go
modules/openapi/component-protocol/scenarios/home-page-sidebar/components/orgFormModal/render.go
pkg/erda-configs/i18n/workbench.json

/kind bug
modify org name regex, add default value if planFinishedAt is nil

modify create org regex, add default if not planFinishedAt

---

modules/dop/endpoints/attempt.go
modules/dop/endpoints/endpoints.go

/kind bug
fix: fix the bug of execute manaual test api
/assign @sfwn 

fix: fix the bug of execute manaual test api

---

conf/msp/msp.yaml
go.mod
go.sum
modules/msp/apm/checker/storage/sync-cache/provider.go

/kind bug
1、update erda-infra version
2、fix typo
@liuhaoyang 

update erda-infra version

---

modules/monitor/alert/alert-apis/adapt/alert_convert.go

/kind feature
fix the crate strategy  save value is nil
@liuhaoyang

fix the crate strategy  save value is nil

---

erda.yml
modules/cluster-dialer/server/tunnel-server.go
modules/cluster-manager/model/model.go
modules/cluster-manager/services/cluster/cluster.go
modules/cmp/impl/clusters/import_cluster.go
modules/scheduler/executor/plugins/k8s/k8s.go
modules/scheduler/executor/plugins/k8s/terminal.go

/kind feature
/kind bug
fix:
1. scheduler terminal
2. import cluster doesn't have org-id

fix: terminal && import cluster

---

modules/monitor/alert/alert-apis/alert.service.go
modules/monitor/alert/storage/alert-record/consumer.go
modules/msp/apm/alert/alert.service.go
modules/msp/apm/alert/permission.go
modules/openapi/api/apis/tmc/tmc_micro_service_alert.go
modules/openapi/api/apis/tmc/tmc_micro_service_alert_create.go
modules/openapi/api/apis/tmc/tmc_micro_service_alert_delete.go
modules/openapi/api/apis/tmc/tmc_micro_service_alert_record.go
modules/openapi/api/apis/tmc/tmc_micro_service_alert_record_attrs.go
modules/openapi/api/apis/tmc/tmc_micro_service_alert_record_histories.go
modules/openapi/api/apis/tmc/tmc_micro_service_alert_record_issue_create.go
modules/openapi/api/apis/tmc/tmc_micro_service_alert_record_issue_update.go
modules/openapi/api/apis/tmc/tmc_micro_service_alert_records.go
modules/openapi/api/apis/tmc/tmc_micro_service_alert_switch.go
modules/openapi/api/apis/tmc/tmc_micro_service_alert_update.go
modules/openapi/api/apis/tmc/tmc_micro_service_alerts.go
modules/openapi/api/apis/tmc/tmc_micro_service_alerts_rules.go
modules/openapi/api/apis/tmc/tmc_micro_service_customize_alert.go
modules/openapi/api/apis/tmc/tmc_micro_service_customize_alert_create.go
modules/openapi/api/apis/tmc/tmc_micro_service_customize_alert_dash_preview.go
modules/openapi/api/apis/tmc/tmc_micro_service_customize_alert_delete.go
modules/openapi/api/apis/tmc/tmc_micro_service_customize_alert_metrics.go
modules/openapi/api/apis/tmc/tmc_micro_service_customize_alert_notify_target.go
modules/openapi/api/apis/tmc/tmc_micro_service_customize_alert_switch.go
modules/openapi/api/apis/tmc/tmc_micro_service_customize_alert_update.go
modules/openapi/api/apis/tmc/tmc_micro_service_customize_alerts.go

/kind fix
bug fix and modify backendPath
@liuhaoyang

bug fix and modify backendPath

---

go.mod
go.sum

/kind fix
get new proto-go,msp interface httpcode is 404
@liuhaoyang

get new proto-go

---

cmd/monitor/streaming/main.go

/kind fix
add alert storage in streaming
@liuhaoyang

add alert storage in streaming

---

modules/cmp/impl/clusters/import_cluster.go
modules/openapi/api/apis/cmp/cmp_cluster_init_retry.go

/kind bug
fix: cluster init retry

fix: cluster init retry

---

modules/monitor/alert/storage/alert-record/consumer.go
modules/openapi/api/apis/tmc/tmc_micro_service_alert_record_attrs.go

/kind fix
modify crated_time is now
@liuhaoyang

modify created_time is now

---

modules/admin/manager/host.go
modules/admin/model/base.go
modules/admin/model/host.go

/kind feature
- move db table struct from cmdb to admin

move db table struct from cmdb to admin

---

modules/scheduler/impl/cluster/hook.go

/kind bug
fix: scheduler cpu subscribe radio patch error

fix: scheduler cpu subscribe radio patch error

---

conf/msp/init_sqls/tmc/nacos.sql
modules/msp/resource/deploy/handlers/mysql/mysql.go

bugfix: nacos sql duplicate key error

---

erda.yml

/kind bug
replace CREATE_ORG_ENABLE to CREATE_ORG_ENABLED

modify erda.yml create_org_enable env

---

modules/msp/resource/deploy/handlers/apigateway/apigateway.go

/kind bug
bugfix: api-gateway config error
/assign @liuhaoyang @johnlanni

bugfix: api-gateway config error

---

apistructs/file_records.go
modules/dop/endpoints/file_records.go
modules/dop/services/i18n/i18n.go
modules/dop/services/testcase/file_records.go
pkg/erda-configs/i18n/qa.json

feature
Test file records response i18n
yes release/1.1

Test file records response i18n

---

modules/msp/apm/trace/trace.service.go

need tracing when create trace debug.

bugfix: fix no tracing

---

modules/msp/resource/deploy/handlers/handler.go
modules/orchestrator/endpoints/addon.go
modules/orchestrator/services/addon/addon_deploy.go
modules/orchestrator/services/addon/addon_handler.go
pkg/mysqlhelper/mysql_test.go

bugfix: fix addon deploy callback struct json serialization error

---

modules/msp/resource/deploy/handlers/handler.go
modules/orchestrator/endpoints/addon.go
modules/orchestrator/services/addon/addon_deploy.go
modules/orchestrator/services/addon/addon_handler.go
pkg/mysqlhelper/mysql_test.go

/kind bug
cherry-pick of #939 

Cherry-pick: fix addon deploy callback struct json serialization error

---

modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/fileInfo/render.go
modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/refreshButton/render.go
modules/openapi/component-protocol/scenarios/auto-test-plan-detail/protocol.yml
modules/openapi/component-protocol/scenarios/auto-test-scenes/components/refreshButton/render.go
modules/openapi/component-protocol/scenarios/auto-test-scenes/protocol.yml

/kind feature
autotest auto refresh execute info, that Users can refresh without manually clicking

autotest auto refresh execute info

---

go.mod
go.sum
pkg/clusterdialer/dialer.go
pkg/mysqlhelper/mysql.go

cherry pick Feature/add debug logs 

---

go.mod
go.sum

bug
Fix empty cells in Mac OS Numbers
Yes  release/1.1

Xlsx package upgrade to v3.2.4

---

modules/openapi/component-protocol/scenarios/home-page-sidebar/components/orgFormModal/render.go

/kind bug
modify the orgFormModal org`s name regexp
the previous regexp don`t match uppercase letter

modify orgFormModal org name regexp

---

modules/pipeline/conf/conf.go
modules/pipeline/spec/pipeline.go

/kind feature
gc(db&resource) config support setup from env
Tested in erda-dev.
- [Erda Cloud Issue Link](https://erda.cloud/erda/workBench/projects/387/issues/all?id=72979&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiOTIiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=467&type=BUG)

feature(pipeline): gc(db&resource) config support setup from env

---

go.mod
go.sum

feature
Cherry pick Xlsx package upgrade to v3.2.4 (#935)
/assign @sfwn

Xlsx package upgrade to v3.2.4 (#935)

---

modules/dicehub/service/publish_item/item_statistics.go

/kind bug
fix mobile application affecting user ratio data
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/workBench/projects/387/issues/all?id=72814&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDQzNiJdfQ%3D%3D&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=429&type=BUG)
/assign @Effet

fix mobile users affecting user ratio data

---

go.mod
go.sum
modules/msp/apm/checker/apis/checker.v1.service.go
modules/msp/apm/checker/apis/permission.go
modules/msp/apm/trace/db/trace_request_history.go
modules/msp/apm/trace/trace.service.go
modules/msp/configcenter/config.center.service.go
modules/msp/instance/permission/permission.go
modules/msp/menu/menu.service.go
modules/msp/registercenter/register.center.service.go
modules/msp/registercenter/register.center.service.host.go
modules/msp/registercenter/register.center.service.host.runtime.go
modules/msp/registercenter/register.center.service.route.go
pkg/common/errors/server.go

- update span proto
- modify DataBase typo

feature: update span proto

---

modules/admin/manager/cluster.go
modules/openapi/api/apis/admin/admin_cluster_get.go

fix(admin): list cluster info with correctly cluster struct

---

modules/pipeline/dbclient/op_pipeline_config.go
modules/pipeline/pipengine/reconciler/gc.go
modules/pipeline/services/pipelinesvc/create.go
modules/pipeline/services/pipelinesvc/create_task.go
modules/pipeline/services/pipelinesvc/passedDataWhenCreate.go
modules/pipeline/services/pipelinesvc/passedDataWhenCreate_test.go
modules/pipeline/spec/pipeline_task.go
modules/pipeline/spec/pipeline_task_test.go

/kind feature
encapsulate the PipelineTaskExecutorName into a type and add some methods, and separate the passedDataWhenCreate into a method and add a unit test

encapsulate the code of passedDataWhenCreate, add PipelineTaskExecutorName type and unit test

---

modules/openapi/api/apis/orchestrator/orchestrator_cluster_instances_usage.go
modules/openapi/api/apis/orchestrator/orchestrator_instances_usage.go

/kind bug
fix: add api specs of orchestrator
https://erda-org.erda.cloud/erda/workBench/projects/387/issues/all?id=73417&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=429&type=BUG
https://erda-org.erda.cloud/erda/workBench/projects/387/issues/all?id=73557&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=429&type=BUG
- …

fix: add api specs of orchestrator

---

modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeTaskTable/render.go
modules/openapi/component-protocol/scenarios/auto-test-scenes/components/executeTaskTable/render.go

/kind bug
When the automated test field is too long, the form display will be ugly
link issues: [erda-issues](https://terminus-org.app.terminus.io/erda/workBench/projects/387/issues/all?id=73167&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMjAyMCIsIjEwMDA1NjAiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=429&type=BUG)

autotest execute table auto with

---

modules/scheduler/impl/terminal/terminal.go

/kind feat
- update(scheduler): adapt soldier to get cluster-info via cluster manager

update(scheduler): adapt soldier to get cluster info via cluster manager

---

modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/refreshButton/render.go
modules/openapi/component-protocol/scenarios/auto-test-scenes/components/refreshButton/render.go

/kind feature
change autotest refresh key

change autotest refresh key

---

modules/msp/apm/trace/trace.service.go

query traces order by startTime DESC

bugfix: order by startTime desc

---

modules/msp/apm/trace/db/trace_request_history.go
modules/msp/apm/trace/trace.service.go

- time zone from local, no UTC

bugfx: fix parse time zone bug

---

modules/core-services/endpoints/user.go
pkg/ucauth/user_admin.go

bug
Search user by name and nick
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/workBench/projects/387/issues/all?id=73333&issueFilter__urlQuery=eyJ0aXRsZSI6IueuoeeQhuS4reW%2FgyIsInN0YXRlQmVsb25ncyI6WyJPUEVOIiwiV09SS0lORyIsIldPTlRGSVgiLCJSRU9QRU4iLCJSRVNPTFZFRCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=429&type=BUG)

Find user by username or nickname

---

modules/monitor/alert/details-apis/kubernetes.go
modules/msp/registercenter/nacos/adapter.go

/kind bug
1、fix register center list interface bug
2、fix pod details apis
@liuhaoyang 

msp registercenter interfaces bug

---

modules/pipeline/pipengine/reconciler/teardown.go
modules/pipeline/services/pipelinesvc/secret.go

/kind bug
fix pipeline panic
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/workBench/projects/387/issues/all?id=71488&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=429&type=BUG)

fix pipeline panic

---

go.mod
go.sum
modules/msp/apm/trace/trace.service.go

/kind feature
/kind bug
/kind polish
/kind document

feature: support query traces by trace_id

---

apistructs/pipeline_status.go
modules/pipeline/pipengine/engine.go
modules/pipeline/pipengine/reconciler/cron_strategy_compensator.go
modules/pipeline/pipengine/reconciler/gc.go
modules/pipeline/pipengine/reconciler/pipeline_gc_compensator.go
modules/pipeline/pipengine/reconciler/pipeline_gc_compensator_test.go
modules/pipeline/pipengine/reconciler/teardown.go

/kind feature
sometimes the pipeline is in downtime or restart time, then the etcd lease of gc may expire at this time, and then there is no instance get lease, which results in some namespaces pod not being gc

pipeline pod namespace gc compensator

---

cmd/monitor/main.go
conf/monitor/monitor.yaml

elasticsearch@log env read bug

Hotfix: monitor es@log

---

modules/dop/conf/conf.go
modules/dop/initialize.go
modules/openapi/component-protocol/scenarios/issue-manage/components/issueTable/render.go

feature
Test file records purge cycle config, fix issue table pagination.
/assign @sfwn 

Test file records purge cycle config, fix issue table pagination.

---

apistructs/addon.go
modules/msp/resource/deploy/coordinator/coordinator.go
modules/msp/resource/resource.service.go
modules/orchestrator/services/addon/addon_handler.go

/kind bug
bugfix: async the deployment if need real deployment action

bugfix: async the deployment if need real deployment action

---

erda.yml

/kind feature
say goodbye to soldier ~

soldier retired

---

modules/scheduler/executor/plugins/edas/edas.go
modules/scheduler/executor/plugins/k8s/daemonset.go
modules/scheduler/executor/plugins/k8s/deployment.go
modules/scheduler/executor/plugins/k8s/k8s.go
modules/scheduler/executor/plugins/k8s/pod/pod.go
modules/scheduler/executor/plugins/k8s/runtime.go

/kind bug
- fix(scheduler): solved the runtime list pending time is too long
- fix(scheduler): edas env keys will be checked via regex when it is created before

fix(scheduler): solved the runtime list pending time is too long

---

apistructs/bigdata.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sflink/util.go

/kind bug
add field logConfig to support customize flink log config
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/workBench/projects/387/issues/all?id=73526&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=429&type=TASK)

support k8s flink job customize log config

---

modules/msp/resource/deploy/coordinator/coordinator.go

/kind bug
if addon has no services or depend addons, no real deploy will perform, so we can run it sync

optimize: optimize addon deployment action check logic

---

bundle/bundle.go
modules/hepa/bundle/dice_bundle.go

/kind feature
when we use telepresence in local, first dial is very slow, more than 5 seconds.

update default bundle timeout

---

modules/cluster-dialer/server/tunnel-server.go
modules/cluster-manager/model/model.go
modules/cluster-manager/services/cluster/cluster.go
modules/cmp/services/kubernetes/kubernetes.go

/kind feature
/kind bug
fix: cmp kubernetes delete lock & dialer register

fix: cmp kubernetes delete lock & dialer register

---

modules/gittar/auth/auth.go
modules/gittar/models/repo.go
modules/gittar/pkg/gitmodule/repo.go
modules/gittar/pkg/gitmodule/repo_edit.go
modules/gittar/pkg/gitmodule/utils.go

/kind bug
fix: solve the problem of push external repository fail
https://erda-org.erda.cloud/erda/workBench/projects/387/issues/all?id=72245&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMTI2MSJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=429&type=BUG
/assign @sfwn  …

fix: solve the problem of push external repository fail

---

modules/msp/apm/exception/exception.service.go

bugfix: fix exceptions count error

---

modules/core-services/dao/manual_review.go

/kind bug
fix: solve the problem of array out of bounds
/assign @sfwn 

fix: solve the problem of array out of bounds

---

modules/hepa/provider.go
modules/msp/apm/checker/apis/checker.v1.service.go
modules/msp/apm/checker/storage/db/metric.go

/kind bug
fix checker list api bug
(paste your link here)
@liuhaoyang 

fix checker list api bug

---

modules/core-services/dao/mbox.go

/kind bug
fix total count of mbox
- [personal mssage](https://erda.cloud/erda/workBench/projects/387/issues/all?id=73840&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDQzNiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=429&type=BUG)

fix total count of mbox

---

modules/msp/apm/trace/trace.service.go

- when status = -1, result error

bugfix: fix get traces status=-1

---

modules/pipeline/conf/conf.go
modules/pipeline/endpoints/clusterinfo.go
modules/pipeline/endpoints/endpoints.go
modules/pipeline/initialize.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/manager.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/scheduler.go
modules/pipeline/pkg/clusterinfo/clusterinfo.go

/kind bug
task manager timing refresh executors sync
add endpoint to manual refresh executors

timing patch task executors and manual trigger refresh

---

modules/openapi/component-protocol/scenarios/issue-manage/components/issueKanban/issue_kanban.go

bug
fix issue kanban board filter by status type conversion error

Fix issue kanban board filter by status

---

apistructs/cmp.go
build/dockerfiles/Dockerfile-cluster-init
conf/cluster-agent/cluster-agent.yaml
erda.yml
modules/cluster-init/client/client.go
modules/cluster-init/config/config.go
modules/cluster-init/provider.go
modules/cmp/conf/conf.go
modules/cmp/endpoints/cluster.go
modules/cmp/impl/clusters/import_cluster.go
modules/cmp/impl/clusters/proxy-deploy.go

/kind feature
/kind bug
feature: upgrade cluster-init & label node

feature: upgrade cluster-init & label node

---

modules/core-services/dao/manual_review.go
modules/core-services/endpoints/manual_review.go
modules/core-services/services/manual_review/manual_review.go

/kind bug
fix: add eventBoxMessage after approve status update
fix: update the url of approve event box message
polish: polish UpdateApproval func
https://erda-org.erda.cloud/erda/workBench/projects/387/issues/all?id=74190&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMTI2MSJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=429&type=BUG
/assign @sfwn  …

fix: add eventBoxMessage after approve status update

---

go.sum
modules/cluster-dialer/server/tunnel-server.go
modules/cluster-manager/services/cluster/cluster.go
modules/cmp/i18n/i18n.go
modules/cmp/impl/clusters/clusterinfo.go

/kind feature
/kind bug
fix: cmp i18n and dialer register

fix: cmp i18n and dialer register

---

modules/openapi/component-protocol/scenarios/action/components/actionForm/render.go

/kind bug
Enable aciton to support the ability to modify operating resources
https://terminus-org.app.terminus.io/erda/workBench/projects/387/issues/bug?id=73159&type=bug

fix resource to resources

---

apistructs/pipeline_define.go
modules/pipeline/services/pipelinesvc/rerun.go

/kind feature
rerun pipeline add pipeline type，some action should get this field
linker erda issue: [erda-issue](https://terminus-org.app.terminus.io/erda/workBench/projects/387/issues/all?id=70958&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDU2MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=BUG)

rerun pipeline add pipeline type

---

docs/guides/deploy/How-to-install-Erda-zh.md
docs/guides/deploy/How-to-install-Erda.md

/kind document
- update(docs): restrict the version available for Kubernetes when users install Erda

update(docs): restrict the version available for Kubernetes when users install Erda

---

docs/guides/deploy/How-to-install-Erda-zh.md
docs/guides/deploy/How-to-install-Erda.md

/kind document
- update(docs): set Kubernetes version range when user install erda

update(docs): set Kubernetes version range when user install erda

---

apistructs/runtime_dto.go
modules/orchestrator/services/runtime/runtime.go
modules/orchestrator/utils/pipeline_utils.go
modules/orchestrator/utils/pipeline_utils_test.go

/kind bug
fake runtime should only appear when pipeline is initializing
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/workBench/projects/387/issues/all?id=74180&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDQzNiJdfQ%3D%3D&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=429&type=BUG)
/assign @Effet

fix deploy by release's fake runtime data

---

modules/msp/menu/menu.service.go

/kind bug
fix menu for edas
@johnlanni 

fix menu for edas

---

apistructs/file_records.go
modules/dop/dao/file_records.go
modules/dop/endpoints/file_records.go
modules/dop/services/testcase/file_records.go

feature
Add number of waiting tasks by types in test file records response

Add number of waiting tasks by types in test file records response

---

modules/msp/apm/exception/exception.service.go

bugfix: Fix exception timestamp

---

modules/hepa/k8s/k8s_adapter.go
pkg/k8s/interface_factory/discover.go
pkg/k8s/interface_factory/ingress.go
pkg/k8s/typed/extensions/v1beta1/ingress.go
pkg/k8s/typed/networking/v1/ingress.go
pkg/k8s/typed/networking/v1beta1/ingress.go
pkg/k8s/union_interface/ingress.go

/kind feature
use interface_factory to decide which kind resource to use.

support more ingress kind

---

modules/msp/apm/exception/exception.service.go

refer to https://github.com/erda-project/erda/pull/1100, commit to master branch

bugfix: fix exception bug

---

modules/orchestrator/utils/pipeline_utils.go

/kind bug
find creating runtime by release should filter yaml name 
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/workBench/projects/387/issues/all?id=200737&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDQzNiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=429&type=BUG)
/assign @Effet

fix list runtime 500 error

---

modules/pipeline/pipengine/reconciler/pipeline_gc_compensator.go
modules/pipeline/pipengine/reconciler/pipeline_gc_compensator_test.go

/kind bug
namespace gc count result num not sql result total

namespace gc count result num

---

go.mod
go.sum
pkg/common/apis/response.go

/kind feature
/kind polish
1、support userIDs in response
2、fix error content-type
@liuhaoyang

support userIDs in response

---

modules/orchestrator/utils/pipeline_utils.go
modules/orchestrator/utils/pipeline_utils_test.go

/kind bug
bad judgment case wrong return
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/workBench/projects/387/issues/all?id=201264&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDQzNiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=429&type=BUG)
/assign @Effet

fix the problem with the yaml name judgment condition

---

modules/pipeline/dbclient/dbclient.go

/kind bug
set charset utf8mb4 and set collation utf8mb4_unicode_ci if url is null

set charset utf8mb4 and set collation utf8mb4_unicode_ci if url is null

---

pkg/strutil/validator.go

/kind document
/kind feature
/kind bug
/kind polish
/kind document

fix typo charactors to characters

---

.erda/migrations/monitor/20210721-monitor-rules-name.sql

/kind fix
modify rule name
@liuhaoyang

modify rule name

---

modules/dop/dao/testplan_testcase_relation.go

feature
Search test plan cases by unassigned executor

Search test plan cases by unassigned executor

---

modules/openapi/component-protocol/scenarios/home-page-content/components/erdaLogo/render.go
modules/openapi/component-protocol/scenarios/home-page-content/components/orgLogo/render.go
modules/openapi/component-protocol/scenarios/home-page-content/components/tableGroup/render.go
modules/openapi/component-protocol/scenarios/home-page-sidebar/components/myApplicationList/render.go
modules/openapi/component-protocol/scenarios/home-page-sidebar/components/myProjectList/render.go
modules/openapi/component-protocol/scenarios/home-page-sidebar/components/orgImage/render.go
modules/openapi/component-protocol/scenarios/org-list-all/components/list/render.go
modules/openapi/component-protocol/scenarios/org-list-my/components/list/render.go
modules/openapi/component-protocol/scenarios/project-list-all/components/list/list.go
modules/openapi/component-protocol/scenarios/project-list-my/components/bannerImage/render.go
modules/openapi/component-protocol/scenarios/project-list-my/components/list/list.go

feature
frontend maintains config images map, use key instead of address.

Update component protocol image src keys

---

modules/pipeline/pipengine/engine.go
modules/pipeline/pipengine/reconciler/dbgc.go
modules/pipeline/pipengine/reconciler/dbgc_test.go
modules/pipeline/pipengine/reconciler/teardown.go
modules/pipeline/services/pipelinesvc/create.go

/kind feature
pipeline database gc

pipeline database gc

---

go.mod
go.sum
modules/openapi/oauth2/jwt.go
modules/openapi/oauth2/server.go

/kind polish
upgrade version of jwt-go and gin to fix potential vulnerabilities.

fix go mod vulnerabilities of jwt-go and gin

---

modules/openapi/component-protocol/scenarios/issue-manage/components/issueKanban/issue_kanban.go

/kind bug
fix: fix the bug of status issueKanban paging
https://erda-org.erda.cloud/erda/workBench/projects/387/issues/all?id=200772&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=BUG
/assign @sfwn  …

fix: fix the bug of status issueKanban paging

---

modules/pipeline/pipengine/reconciler/teardown.go
modules/pipeline/services/pipelinesvc/secret.go

/kind bug
hotfix pipeline something may make panic

hotfix pipeline panic

---

apistructs/k8s.go
apistructs/pipeline_report.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sflink/flink.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sjob/k8sjob.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sspark/k8sspark.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/types/define.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/logic/events.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/logic/job.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/scheduler.go
modules/pipeline/pipengine/reconciler/taskrun/taskop/wait.go

/kind feature
report k8sjob inspect if task failed
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/workBench/projects/387/issues/all?id=70728&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=TASK)

k8sjob add inspect interface for task

---

build/dockerfiles/Dockerfile-action-agent
modules/actionagent/define.go
modules/actionagent/file_watch.go
modules/actionagent/file_watch_test.go
modules/actionagent/step_prepare.go

/kind bug
actionagent callback stderr if match regexp in every line
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/workBench/projects/387/issues/all?id=70728&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=TASK)

actionagent callback stderr if match regexp

---

modules/core-services/services/project/project.go
modules/orchestrator/services/deployment/deployment.go
modules/orchestrator/services/runtime/runtime.go
modules/orchestrator/services/runtime/runtime_test.go

/kind bug
we need according to the rollback configuration to do release gc
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/workBench/projects/387/issues/all?id=70729&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDQzNiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=TASK)
/assign @Effet

use rollback config to do release gc

---

go.mod
go.sum

Add one of the following kinds:/kind bug
fix potential security problem.

upgrade gin to 1.7.0

---

modules/openapi/api/apis/msp/apm/adapter/get_adapter_docs.go
modules/openapi/api/apis/msp/apm/adapter/get_adapters.go

/kind feature
Add comment like `/cherry-pick release/1.2` when this PR is merged.

add msp apm adapter openapi

---

cmd/core-services/main.go
erda.yml
modules/core-services/provider.go

/kind bug
- pipeline missing grpc port expose in erda.yaml
- core-services add missing import for pipeline cms

make dop&core-services startup success

---

go.mod
go.sum
pkg/common/apis/header.go
pkg/common/pbutil/pbutil.go
pkg/common/pbutil/pbutil_test.go

/kind feature
add common pbutil and identidyInfo for easy use.

feature: add common pbutil and identityInfo

---

.github/PULL_REQUEST_TEMPLATE.md

/kind feature
In order to extract data to automatically generate changeLog.

Add changeLog section in PR template

---

go.mod
modules/msp/instance/permission/permission.go
modules/msp/menu/menu.service.go

/kind bug
fix get project id from tenant
@liuhaoyang 

fix get project id from tenant

---

modules/cmp/impl/clusters/import_cluster.go
modules/cmp/impl/clusters/update_cluster.go
modules/cmp/initialize.go

/kind bug
fix: bundle with cluster-manager
for quickstart

fix: bundle with cluster-manager

---

modules/msp/instance/permission/permission.go
modules/msp/menu/menu.service.go

/kind bug
fix project id from tenant
@liuhaoyang

fix project id from tenant for 1.1

---

modules/scheduler/executor/plugins/k8s/k8s.go

/kind bug
- fix(scheduler): inspect servicegroup status correctly when ns is non project ns

fix(scheduler): inspect servicegroup status correctly when ns is non project ns

---

modules/openapi/component-protocol/scenarios/issue-manage/components/issueTable/render.go

bug
Increase the width of title column in issue table as much as possible
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=202065&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMTA3MyJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=429&type=BUG)
/assign @sfwn 

Increase the width of title column in issue table as much as possible

---

modules/hepa/bundle/dice_bundle.go

/kind bug
Fixed the problem of local deployment of the cluster manager that could not be resolved.

fix hepa bundles

---

conf/hepa/hepa.yaml

/kind feature
add hepa conf value for special scenario.
yes

add hepa conf value

---

modules/openapi/api/apis/testplatform/testplan/autotests_testplan_execute.go
modules/openapi/component-protocol/scenarios/action/components/actionForm/render.go

kind feature
Add componentized protocol to testplan action
https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/requirement?id=70716&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&type=requirement

add component protocol and openapi of testplan-run action

---

bundle/events.go
conf/admin/admin.yaml
go.mod
go.sum
modules/admin/dingtalktest/dingtalk_test.service.go
modules/admin/dingtalktest/provider.go
modules/openapi/api/apis/admin/admin_dingtalk_test.go

/kind feature
feature: add dingtalk send test
/assign @recallsong

feature: add dingtalk send test

---

docs/guides/quickstart/quickstart-full.md

/kind bug
the "dbmigration-4" was renamed in docker-compose file, so edit it in the readme

feature: rename dbmigration-4 to erda-migration

---

erda.yml

/kind feature
/kind bug
/kind polish
/kind document
/assign @recallsong

Add ports for admin service

---

apistructs/audits.go
modules/openapi/api/apis/orchestrator/orchestrator_pre_dice_overlay_update.go
modules/openapi/api/apis/orchestrator/orchestrator_pre_dice_overlay_update_test.go
modules/orchestrator/endpoints/server_handler.go
modules/orchestrator/endpoints/server_handler_test.go
pkg/erda-configs/audit/template.json

/kind feature
add audit event for scale runtime
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=200182&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls0MzFdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDQzNiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=431&type=TASK)
/assign @sfwn @Effet

add audit for scale runtime

---

docs/guides/deploy/How-to-install-Erda-zh.md
docs/guides/deploy/How-to-install-Erda.md

/kind document
Optimize deployment documentation
/assign @Muzry 
| 🇺🇸 English |      Optimize deployment documentation        |
| 🇨🇳 中文    |      优化部署文档        |

Optimize deployment documentation

---

docs/guides/deploy/How-to-install-Erda-zh.md
docs/guides/deploy/How-to-install-Erda.md

/kind document
Optimize deployment documentation
/assign @Muzry @sfwn 
| 🇺🇸 English |       Optimize deployment documentation       |
| 🇨🇳 中文    |     优化部署文档         |

docs(install): Optimize deployment documentation

---

.erda/migrations/pipeline/20210528-pipeline-base.sql
.erda/migrations/qa/20210528-qa-base.sql

feature: fix error baseline

---

apistructs/autotest_space.go
apistructs/component_protocol.go
apistructs/file_records.go
apistructs/records.go
bundle/autotest_space.go
bundle/record.go
modules/dop/services/apierrors/errors.go
modules/dop/services/testcase/file_records.go
modules/openapi/api/apis/testplatform/autotest/space_export.go
modules/openapi/api/apis/testplatform/autotest/space_import.go
modules/openapi/component-protocol/scenarios/auto-test-space-list/components/importButton/render.go
modules/openapi/component-protocol/scenarios/auto-test-space-list/components/recordButton/render.go
modules/openapi/component-protocol/scenarios/auto-test-space-list/components/recordDrawer/render.go
modules/openapi/component-protocol/scenarios/auto-test-space-list/components/recordTable/render.go
modules/openapi/component-protocol/scenarios/auto-test-space-list/components/refreshButton/render.go
modules/openapi/component-protocol/scenarios/auto-test-space-list/components/spaceList/operation.go
modules/openapi/component-protocol/scenarios/auto-test-space-list/components/spaceList/render.go
modules/openapi/component-protocol/scenarios/auto-test-space-list/i18n/i18n.go
modules/openapi/component-protocol/scenarios/auto-test-space-list/protocol.yml
pkg/erda-configs/i18n/autotest.json

/kind feature
add autotest space import export components
| 🇺🇸 English |    add   autotest space components      |
| 🇨🇳 中文    |     自动化测试空间的导入导出组件化协议        |

add autotest space export import components

---

conf/dicehub/dicehub.yaml
modules/dicehub/image/provider.go

/kind feature
image.proto have been move to core。
so update it in erda

update dicehub image provider

---

modules/openapi/api/apis/msp/apm/adapter/get_adapter_docs.go
modules/openapi/api/apis/msp/apm/adapter/get_adapters.go
modules/openapi/api/apis/msp/tenant/create_tenants.go
modules/openapi/api/apis/msp/tenant/get_tenant.go

/kind feature
/kind bug
/kind polish
/kind document

Fix msp trace package error

---

modules/pipeline/services/actionagentsvc/ensure.go

/kind bug
edas ensure agent same with k8s cluster
| 🇺🇸 English |  edas ensure agent same with k8s cluster         |
| 🇨🇳 中文    | edas 和k8s用的一样的agent             |

edas ensure agent same with k8s cluster

---

modules/core/monitor/log/query/provider.go
modules/monitor/common/permission/permission.go

/api/orgCenter/logs permission check fix

---

go.mod
go.sum
modules/pipeline/providers/cms/cms.service.go
pkg/common/apis/header.go

/kind bug
- fix: pipeline cms use lower-case internal-client header for grpc
- local invoke use grpc transport outcoming context https://github.com/erda-project/erda-infra/pull/66
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/bug?id=202675&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=431&type=BUG)
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/bug?id=202519&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiOTIiXX0%3D& …

fix: pipeline cms use lower-case internal-client header for grpc

---

go.mod
go.sum

/kind polish
update version of erda-infra

update version of erda-infra

---

modules/openapi/component-protocol/scenarios/auto-test-plan-list/protocol.yml

kind feature
https://erda.cloud/erda/dop/projects/387/issues/all?issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDgwNSJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D
Add ID field to test plan list

add testplan-id column

---

go.mod
go.sum
pkg/database/sqlparser/migrator/db.go
pkg/database/sqlparser/migrator/migrator.go
pkg/database/sqlparser/migrator/parameters.go
pkg/database/sqlparser/migrator/scripts.go
tools/cli/cmd/migrate.go

/kind feature
add args to control migration flow, that we can
- skip migration lint
- skip sandbox
- skip pre-migration
- skip pre-migration and real migration

feature: add args to control migration flow

---

modules/openapi/api/apis/testplatform/autotest/autotests_scenes_execute.go
modules/openapi/component-protocol/scenarios/action/components/actionForm/change_model.go
modules/openapi/component-protocol/scenarios/action/components/actionForm/render.go

kind feature
Add component protocol to the testscene-run action

add testscene-run component protocol

---

modules/pipeline/conf/conf.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/manager.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/scheduler.go

/kind bug
Increase update executors frequency
if executor existed, don`t delete
| 🇺🇸 English |   add executor if not exeist in manager           |
| 🇨🇳 中文    |  更新executor时如果已存在就不更新,因为session会自动重连            |

add executor if not exist

---

modules/openapi/component-protocol/scenarios/action/components/actionForm/render.go

/kind bug
fix component protocol to the testscene-run action
https://user-images.githubusercontent.com/32703277/127469060-9394edd0-9242-4448-b4cd-402848ab0117.png

fix testscene-run component protocol

---

modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/manager.go
modules/pipeline/pipengine/reconciler/task.go
modules/pipeline/pipengine/reconciler/taskrun/framework.go

/kind bug
if k8s client abort session not found error, task should continue retry until find session

continue retry task until find session

---

.erda/migrations/scheduler/20210729-scheduler-index-update.sql
go.mod
modules/scheduler/executor/executor.go
modules/scheduler/executor/plugins/edas/edas.go
modules/scheduler/executor/plugins/k8s/instanceinfosync/gc.go
modules/scheduler/executor/plugins/k8s/instanceinfosync/pod.go
modules/scheduler/executor/plugins/k8s/instanceinfosync/sync.go
modules/scheduler/executor/plugins/k8s/k8s.go
modules/scheduler/executor/util/util.go
modules/scheduler/impl/cluster/hook.go
modules/scheduler/impl/terminal/terminal.go

/kind feature
- feat(scheduler): adapt edas call chains to kubernetes
/assign @luobily  @sixther-dc 

feat(scheduler): adapt edas call chains to kubernetes

---

modules/msp/instance/db/instance.go
modules/msp/instance/db/instance_tenant.go
modules/msp/instance/db/monitor/monitor.go

/kind bug
1、fix tenant db query
@liuhaoyang

fix tenant db query

---

pkg/erda-configs/permission/backend/sys/org/project/project.yml

/kind feature
Allow guest to create tickets
/assign @sfwn 
| 🇺🇸 English | Allow guest to create tickets             |
| 🇨🇳 中文    | 允许游客在公开项目里创建工单             |

allow guest to create ticket

---

conf/cluster-agent/cluster-agent.yaml
modules/cluster-agent/client/client.go
modules/cluster-dialer/server/tunnel-server.go
modules/cluster-init/client/client.go
modules/cmp/conf/conf.go
modules/cmp/impl/clusters/clusterinfo.go
modules/cmp/impl/clusters/import_cluster.go
modules/cmp/impl/clusters/proxy-deploy.go
modules/cmp/impl/clusters/update_cluster.go
modules/cmp/services/kubernetes/kubernetes.go

/kind feature
feature: support slave cluster connect protocol
| 🇺🇸 English |  1. cluster-agent support http/https 2. fix import cluster error  |
| 🇨🇳 中文    |    1.cluster-agent 支持 https/http，2. 修复集群导入存在的错误    |

feature: support slave cluster connect protocol

---

modules/msp/apm/alert/alert.service.go

/kind fix
micro_service add alert_type
@liuhaoyang

micro_service add alert_type

---

modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/refreshButton/render.go
modules/openapi/component-protocol/scenarios/auto-test-scenes/components/refreshButton/render.go

/kind bug
autotest remove auto refresh
erda-issue: [erda-issue](https://erda.cloud/erda/dop/projects/387/issues/all?id=202813&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDU2MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=BUG)

autotest remove auto refresh

---

modules/pipeline/pipengine/reconciler/pipeline_gc_compensator.go

/kind feature
pipeline ns gc add large page size search

pipeline ns gc add large page size search

---

pkg/http/httpserver/server.go

/kind bug
Manual decoding url var
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=203079&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls0MzFdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMTIwNSJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=BUG)

Manual decoding url var

---

modules/msp/apm/trace/trace.service.go
pkg/math/math.go
pkg/math/math_test.go

…s calculated incorrectly
/kind bug
/assign @recallsong

Bugfix: When there are child spans, the duration of the parent_span is calculated incorrectly

---

modules/gittar/api/repo.go
modules/gittar/pkg/gitmodule/repo_edit.go

/kind feature
fix: add the validations for git commit struct
https://erda.cloud/erda/dop/projects/387/issues/all?id=203071&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMTI2MSJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=431&type=BUG
/assign @sfwn  …

fix: add the validations for git commit struct

---

modules/core/monitor/settings/settings.service.go

/kind bug
1、fix monitor settings save
@liuhaoyang

fix monitor settings save

---

modules/scheduler/executor/plugins/k8s/clusterinfo/clusterinfo.go

/kind feature
- update(scheduler): reduce the cluster info sync time
| 🇺🇸 English |  update(scheduler): reduce the cluster info sync time |
| 🇨🇳 中文    | 优化 cluster info 的同步时间             |

update(scheduler): reduce the cluster info sync time

---

go.mod
modules/monitor/dashboard/org-apis/permission.go
modules/monitor/dashboard/org-apis/provider.go
modules/monitor/dashboard/project-apis/provider.go
modules/monitor/dashboard/runtime-apis/provider.go

/kind bug
1、fix query metric for multi org
@liuhaoyang

fix query metric for multi org

---

modules/dop/endpoints/issue_stream.go

/kind bug
change the username of issue stream to nickname
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=200996&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDQzNiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=BUG)

change the username of issue stream to nickname

---

modules/orchestrator/services/runtime/runtime.go

Fixed the issue when two different applications with the same branch …
/kind bug
Fixed the issue when two different applications with the same branch at the same time
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=71418&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDQzNiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=BUG)

Fixed the issue when two different applications with the same branch at the same time

---

modules/pipeline/conf/conf.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sflink/util.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sjob/k8sjob.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/logic/job.go

/kind bug
add flink status judge
change flinkcluster pull image policy
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/workBench/projects/387/issues/all?id=59230&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=BUG)

add flink status judge, change flink pull policy

---

modules/openapi/api/apis/dop/adaptor_cicd_config_namespaces.go
modules/openapi/api/apis/dop/adaptor_cicd_config_workspaces.go

/kind bug
fix: update api spec's host to avoid 502
https://erda.cloud/erda/dop/projects/387/issues/all?id=203848&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=BUG
/assign @sfwn  …

fix: update api spec's host to avoid 502

---

cmd/dicehub/main.go
conf/dicehub/dicehub.yaml
modules/dicehub/extension/db/extension.go
modules/dicehub/extension/db/table.go
modules/dicehub/extension/extention.service.go
modules/dicehub/extension/extention.service_test.go
modules/dicehub/extension/menu.go
modules/dicehub/extension/provider.go
pkg/common/apis/header.go

/kind feature
add provider named extention in dicehub

add provider named extension in dicehub

---

modules/openapi/component-protocol/scenarios/action/components/actionForm/render.go

kind bug
When entering a decimal, it is automatically converted to an integer
https://erda.cloud/erda/dop/projects/387/issues/bug?id=72816&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&type=bug

Convert the loop field to an integer

---

modules/msp/apm/checker/apis/checker.v1.service.go
modules/msp/instance/permission/permission.go
modules/msp/menu/menu.service.go

bugfix: Fix msp project permission

---

apistructs/k8s.go
apistructs/pipeline_task.go
modules/pipeline/pipengine/actionexecutor/plugins/apitest/apitest.go
modules/pipeline/pipengine/actionexecutor/plugins/demo/demo.go
modules/pipeline/pipengine/actionexecutor/plugins/memory/memory.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sjob/k8sjob.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/scheduler.go
modules/pipeline/pipengine/actionexecutor/types/define.go
modules/pipeline/pipengine/reconciler/taskrun/taskop/queue.go
modules/pipeline/pipengine/reconciler/taskrun/taskop/wait.go
modules/pipeline/pipengine/reconciler/taskrun/update.go
modules/pipeline/services/pipelinesvc/detail.go

/kind feature
record job inspect in task result
reveal job events
| 🇺🇸 English |  record job inspect in task result            |
| 🇨🇳 中文    |   记录job的inspect           |

record job inspect in task result and reveal events

---

modules/openapi/api/apis/msp/tenant/project/get_msp_projects.go

/kind bug
fix msp project list i18n.
Add comment like `/cherry-pick release/1.2` when this PR is merged.

bugfix: fix msp project list i18n.

---

modules/openapi/component-protocol/scenarios/issue-manage/components/issueKanban/issue_kanban.go

/kind bug
fix: fix the bug for kanban of filter by time
https://erda.cloud/erda/dop/projects/387/issues/all?id=203939&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=BUG
/assign @sfwn  …

fix: fix the bug for kanban of filter by time

---

bundle/autotest_space.go

/kind bug
set header user id
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=203960&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls0MzFdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=BUG)

set header user id

---

.erda/migrations/_patches_/patch-20210528-pipeline-base.sql
.erda/migrations/_patches_/patch-20210528-qa-base.sql

Reverts erda-project/erda#1258

Revert "feature: add patches migrations"

---

go.mod
go.sum
modules/msp/apm/metric/routes.go
modules/msp/tenant/project/project.service.go
modules/openapi/api/apis/msp/tenant/project/get_msp_metric_project_overview.go
modules/openapi/api/apis/msp/tenant/project/get_msp_project_overview.go
modules/openapi/api/apis/msp/tenant/project/get_msp_projects.go

feature: MSP Project overview

---

quick-start/quick-start.sh

/kind feature
- Show tip message before require sudo password
- Highlight the http url
- Chown the install location to current user to avoid sudo requirement

optimize: update quick-start.sh

---

modules/core/monitor/log/schema/manager.go
modules/core/monitor/log/storage/provider.go

log-store bootstrap bugfix

---

modules/dop/endpoints/pipeline.go

/kind feature
put the pipelineID into the request body when the action cancel pipeline
erda-issue: [erda-issue](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=72603&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDU2MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG)
link pr: https://github.com/erda-project/erda-actions/pull/121#issue-702939431

put the pipelineID into the request body when the action cancel pipeline

---

modules/core/monitor/dataview/db/db.go

/kind polish
order by dataview list
@liuhaoyang 

order by dataview list

---

modules/scheduler/executor/plugins/edas/edas.go

/kind bug
fix: edas executor connect kubernetes error
| 🇺🇸 English |  fix:  edas executor connect kubernetes error          |
| 🇨🇳 中文    |       修复 edas executor 连接 kubernetes 错误   ， 1.2 版本引入与 kubernetes 相同逻辑 |

fix: edas executor connect kubernetes error

---

quick-start/docker-compose.yml

/kind feature
update erda-migration image and envs in quick-start
- Add process control parameters
- Add patch mechanism

feature: update erda-migration image and envs in quick-start

---

modules/scheduler/executor/plugins/edas/edas.go
modules/scheduler/executor/plugins/k8s/daemonset.go
modules/scheduler/executor/plugins/k8s/deployment.go
modules/scheduler/executor/plugins/k8s/k8s.go
modules/scheduler/executor/plugins/k8s/runtime.go
modules/scheduler/executor/plugins/k8s/service.go
modules/scheduler/impl/servicegroup/delete.go

/kind feature
- add service group log when they're created or deleted
| 🇺🇸 English | add service group log when they're created or deleted    |
| 🇨🇳 中文    |  为 servicegroup 创建和删除操作增加了日志输出             |

add service group log when they're created or deleted

---

CHANGELOG/CHANGELOG-1.x.md

/kind document
add v1.1.1 changeLog
change title from second level to third level to make changeLog more clear.

doc: add v1.1.1 changeLog

---

modules/msp/tenant/project/project.service.go

/kind feature
Add comment like `/cherry-pick release/1.2` when this PR is merged.

feature: add default sort

---

modules/openapi/component-protocol/scenarios/action/components/actionForm/render.go

/kind bug
https://erda.cloud/erda/dop/projects/387/issues/bug?id=204555&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&type=bug
fix testscene-run action component protocol,Graphical interface can be displayed

fix testscene-run action component protocol

---

modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sjob/k8sjob.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/scheduler.go

/kind bug
modify k8s executor jobname when remove
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=204366&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=467&type=BUG)

modify k8s executor jobname when remove

---

.erda/migrations/.patches/patch-20210528-cmdb-base.sql
.erda/migrations/.patches/patch-20210528-monitor-base.sql
.erda/migrations/.patches/patch-20210528-orchestrator-base.sql
.erda/migrations/.patches/patch-20210528-pipeline-base.sql
.erda/migrations/.patches/patch-20210528-qa-base.sql
.erda/migrations/.patches/patch.sql
.erda/migrations/cmdb/20210528-cmdb-base.sql
.erda/migrations/orchestrator/20210528-orchestrator-base.sql
.erda/migrations/pipeline/20210528-pipeline-base.sql
pkg/database/sqlparser/migrator/db.go
pkg/database/sqlparser/migrator/equal.go
pkg/database/sqlparser/migrator/equal_test.go
pkg/database/sqlparser/migrator/migrator.go
pkg/database/sqlparser/migrator/parameters.go
pkg/database/sqlparser/migrator/schema.go
pkg/database/sqlparser/migrator/scripts.go
pkg/database/sqlparser/migrator/service.go
pkg/database/sqlparser/migrator/tabledef.go
pkg/database/sqlparser/snapshot/snapshot.go
pkg/database/sqlparser/snapshot/snapshot_test.go
tools/cli/cmd/migrate.go
tools/cli/cmd/migrate_lint.go
tools/cli/cmd/migrate_mkpypkg.go
tools/cli/cmd/migrate_record.go

/kind feature
- update migrate lint from master
- patch migrations

update migrate lint from master

---

CHANGELOG/CHANGELOG-1.x.md

/kind document
fix the link anchor

doc: fix the version link anchor

---

bundle/cluster.go

/kind bug
fix: list cluster bundle with orgID and clusterType
/assign @luobily @johnlanni 
| 🇺🇸 English |  fix: list cluster bundle with orgID and clusterType            |
| 🇨🇳 中文    |       修复bundle无法通过 orgID 过滤 Cluster       |

fix: list cluster bundle with orgID and clusterType

---

pkg/database/sqlparser/migrator/scripts.go

/kind feature
add .patches module as default

feature: add .patches module as default

---

modules/openapi/component-protocol/scenarios/home-page-content/components/emptyProjectContent/render.go
pkg/erda-configs/i18n/workbench.json

/kind bug
modify workbench copywriting
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=204682&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls0MzEsNDI5XSwic3RhdGVCZWxvbmdzIjpbIk9QRU4iLCJXT1JLSU5HIiwiV09OVEZJWCIsIlJFT1BFTiJdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjA1Il19&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=429&type=BUG)

modify workbench copywriting

---

modules/pipeline/services/pipelinesvc/convert.go

/kind bug
get detail value(projectname appname) from getLabel func
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=204516&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls0MzFdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=BUG)

get detail value from getLabel func

---

modules/dop/services/filetree/filetree.go
modules/openapi/component-protocol/scenarios/app-pipeline-tree/components/fileTree/render.go

bug
App pipeline inodes use URLEncoding instead of StdEncoding
/assign @sfwn 

App pipeline inodes use URLEncoding instead of StdEncoding

---

pkg/database/sqlparser/migrator/migrator.go
pkg/database/sqlparser/migrator/schema.go
pkg/database/sqlparser/migrator/scripts.go
pkg/database/sqlparser/migrator/service.go
pkg/database/sqlparser/migrator/tabledef.go

/kind feature
- erda-migrator supports new baseline files
- to advance log

feature: support new baseline files

---

erda.yml

/kind bug
fix services' replica parameter in erda.yml. 

fix replica in erda.yml

---

modules/dop/services/autotest/global_config.go

/kind bug
set DeleteNs true to delete cms
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=204922&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=BUG)

set DeleteNs true to delete cms

---

modules/monitor/dashboard/report/engine/resource.go

/kind bug
fix json tag
- Fixes https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=204938&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDMwMSJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=431&type=BUG …

tag rename

---

bundle/msp.go
modules/hepa/gateway/service/gateway_global_service.go
modules/msp/tenant/provider.go
modules/msp/tenant/tenant.service.go
modules/orchestrator/services/addon/addon_handler.go

/kind bug
Add comment like `/cherry-pick release/1.2` when this PR is merged.

bugfix: compatible with history projects

---

pkg/database/sqlparser/migrator/migrator.go

/kind feature
it should patch to actual db not sandbox

fix patch error

---

docs/guides/deploy/How-to-install-Erda-zh.md
docs/guides/deploy/How-to-install-Erda.md

/kind document
Supplement erda uninstall documentation
/assign @Muzry @sfwn 
| 🇺🇸 English |     Supplement erda uninstall documentation         |
| 🇨🇳 中文    |       补充 erda 卸载文档       |
/cherry-pick release/1.0 release/1.1

Supplement erda uninstall documentation

---

docs/guides/deploy/How-to-install-Erda-zh.md
docs/guides/deploy/How-to-install-Erda.md

/kind document
Supplement erda uninstall documentation
/assign @sfwn 
| 🇺🇸 English |      Supplement erda uninstall documentation        |
| 🇨🇳 中文    |     补充 erda 卸载文档         |

Release/1.0 Supplement erda uninstall documentation

---

modules/msp/apm/alert/alert.service.go

/kind bug
change dice_org_id to string
@liuhaoyang

change dice_org_id to string

---

modules/core-services/endpoints/application.go
modules/core-services/services/project/project.go
modules/core-services/services/project/project_test.go
modules/openapi/component-protocol/scenarios/home-page-content/components/content/render.go
modules/openapi/component-protocol/scenarios/home-page-content/components/emptyProjectTip/render.go
modules/openapi/component-protocol/scenarios/home-page-content/components/emptyProjectTitle/render.go
modules/openapi/component-protocol/scenarios/home-page-content/components/tableGroup/render.go
modules/openapi/component-protocol/scenarios/home-page-content/protocol.yml
modules/openapi/component-protocol/scenarios/home-page-sidebar/components/joinedBrief/render.go
modules/openapi/component-protocol/scenarios/home-page-sidebar/components/myApplication/render.go
modules/openapi/component-protocol/scenarios/home-page-sidebar/components/myApplicationList/render.go
modules/openapi/component-protocol/scenarios/home-page-sidebar/components/myProjectList/render.go
modules/openapi/component-protocol/scenarios/home-page-sidebar/components/myProjectTitle/render.go
modules/openapi/component-protocol/scenarios/home-page-sidebar/protocol.yml

bug
Optimize application list endpoint and user workbench render

Optimize application list endpoint and user workbench render

---

modules/dop/dao/autotest_scene.go
modules/dop/services/autotest_v2/scene.go

bug
Check whether there is a scene with the same name in the same scene set
erda-issue: [erda-issue](https://erda.cloud/erda/dop/projects/387/issues/all?id=206012&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDU2MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=BUG)

autotest scene check same name

---

pkg/database/sqlparser/migrator/parameters.go
pkg/database/sqlparser/pygrator/settings.go

/kind feature
add charset to dsn

feature: add charset to dsn

---

docs/guides/deploy/How-to-install-Erda-zh.md
docs/guides/deploy/How-to-install-Erda.md

/kind document
Adjust the content of the uninstall erda document
/assign @sfwn 
| 🇺🇸 English |      Adjust the content of the uninstall erda document        |
| 🇨🇳 中文    |      调整卸载 erda 的文档内容        |
/cherry-pick release/1.0 release/1.1 release/1.2

Master: Adjust the content of the uninstall erda document

---

modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sjob/k8sjob.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/logic/job.go
modules/pipeline/services/pipelinesvc/detail.go
modules/pipeline/services/pipelinesvc/detail_test.go

/kind feature
task events optimization
get pod inspect, only reveal task events when task scheduler failed
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=204653&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMTIwNSJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=-1&type=BUG)

Pipeline task event display optimization

---

modules/cmp/i18n/i18n.go
modules/cmp/impl/clusters/clusterinfo.go

/kind feature
feature: support show agent registered and remove extra field 
| 🇺🇸 English |  support show agent registered and remove extra field             |
| 🇨🇳 中文    |  支持返回Agent方式是否已注册，移除额外的一些集群详情字段            |

feature: support show agent registered and remove extra field

---

modules/pipeline/services/pipelinesvc/passedDataWhenCreate.go

/kind bug
The passedDataWhenCreate method will read the map concurrently, which will cause the pipeline to restart
erda-issue: [erda-issue](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=206764&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDU2MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=BUG)

when creating a pipeline to cache action information, add a lock to read the map

---

modules/scheduler/executor/plugins/edas/edas.go
modules/scheduler/executor/plugins/k8s/k8sapi/types.go

/kind feature
| 🇺🇸 English | update(scheduler): change delete option from Foreground to BackGround             |
| 🇨🇳 中文    | 将 scheduler 删除选项从 `Foreground` 改为 `BackGround` |

update(scheduler): change delete option from Foreground to BackGround

---

pkg/database/sqlparser/ddlreverser/reverser_test.go
pkg/database/sqlparser/migrator/migrator.go
pkg/database/sqlparser/migrator/parameters.go
pkg/database/sqlparser/migrator/schema.go
pkg/database/sqlparser/migrator/scripts.go
pkg/database/sqlparser/migrator/service.go
pkg/database/sqlparser/migrator/tabledef.go
pkg/database/sqlparser/pygrator/settings.go

/kind feature
sync migrator from branch master

sync migrator from branch master

---

CHANGELOG/CHANGELOG-1.x.md

/kind document
add v1.2.0 changelog
- NaN
/assign @daskyrk @sfwn 
| 🇺🇸 English |        add v1.2.0 changelog      |
| 🇨🇳 中文    |        新增v1.2.0 changelog      |
Nope

add v1.2.0 changelog

---

apistructs/issue.go
apistructs/workbench.go
modules/dop/dao/issue.go
modules/dop/endpoints/endpoints.go
modules/dop/endpoints/workbench.go
modules/dop/initialize.go
modules/dop/services/issue/issue.go
modules/dop/services/workbench/workbench.go
modules/dop/services/workbench/workbench_test.go
modules/openapi/component-protocol/scenarios/home-page-content/components/tableGroup/render.go

/kind bug
concurrent query issue by expire day
optimization for workbench endpoint time consuming

concurrent query issue for workbench endpoint optimization 

---

modules/orchestrator/initialize.go
pkg/erda-configs/i18n/orchestrator.json

/kind feature
feature: add i18n for addon
https://erda.cloud/erda/dop/projects/387/issues/all?id=206519&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=BUG
/assign @sfwn 
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONT …

feature: add i18n for addon

---

modules/msp/resource/deploy/handlers/loganalytics/loganalytics.go

/kind bug
index of log-analytics es not rolling
| 🇺🇸 English |    Fix  ES index of log-analytics not rolling  |
| 🇨🇳 中文    |   修复日志分析ES索引未滚动的问题     |

bugfix: change log-analytics created index prefix

---

pkg/database/sqllint/linters/not_null_linter.go
pkg/database/sqllint/linters/not_null_linter_test.go

/kind feature
not to do "not null lint" on alter table stmt

feature: not to do "not null lint" on alter table stmt

---

build/dockerfiles/Dockerfile
build/scripts/dicehub/extension-push.sh

/kind bug
Added conditional judgment, will not allow wrong code when packaging images

BUG fix: build image will false,if MODULE_PATH is not "dicehub"

---

.erda/migrations/cmdb/20210721-fixAuditHistory.sql

/kind feature
patch 2 SQL files

patch 2 migrations files

---

.erda/migrations/cmdb/20210721-fixAuditHistory.sql

/kind feature
feature: patch 2 migrations files

feature: patch 2 migrations files

---

.github/workflows/ci-it.yml
tools/gotools/go-test-sum/main.go

/kind polish
golang lint cache
| 🇺🇸 English |       quick go lint       |
| 🇨🇳 中文    |       快速 go lint       |
NO

golang lint cache

---

erda.yml

/kind polish
cmp need more cpu and memory to deploy because of steve api with cache

update cmp deploy cpu and memory

---

pkg/database/sqlparser/migrator/migrator.go
pkg/database/sqlparser/migrator/script.go
pkg/database/sqlparser/migrator/script_test.go

/kind feature
- do not exec empty patch file
- don't do patching after installation

fix: do not exec empty patch file

---

cmd/monitor/extensions/loghub/main.go
conf/monitor/extensions/loghub/output/elasticsearch-rollover.yaml
modules/extensions/loghub/exporter/output.go
modules/extensions/loghub/exporter/output/elasticsearch-proxy/proxy.go
modules/extensions/loghub/loghub.go

bugfix: fix bug of loghub

---

build/dockerfiles/Dockerfile
modules/dicehub/initialize.go

/kind bugfix
The read file address does not match the actual address

fix : create extension false when init provider

---

modules/scheduler/executor/plugins/k8s/k8s.go
modules/scheduler/executor/plugins/k8s/pod/pod.go
modules/scheduler/executor/plugins/k8s/pod/pod_test.go

/kind bug
| 🇺🇸 English | fix(service): list specify pod for status             |
| 🇨🇳 中文    |  修复 pod 状态列表获取到指定的 pod|

fix(service): list specify pod for status

---

modules/openapi/component-protocol/scenarios/project-list-all/components/list/list.go
modules/openapi/component-protocol/scenarios/project-list-all/components/list/model.go
modules/openapi/component-protocol/scenarios/project-list-my/components/list/list.go
modules/openapi/component-protocol/scenarios/project-list-my/components/list/model.go

bug
Fix project list components pagination
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=208312&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMTA3MyJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=431&type=BUG)

Fix project list components pagination

---

build/dockerfiles/Dockerfile
modules/dicehub/extension/provider.go
modules/dicehub/extension/provider_test.go

/kind bug
The read file address does not match the actual address

fix : create extension failed when init provider

---

CHANGELOG/CHANGELOG-1.x.md

/kind document
updates to v1.2.0 changelog
- NaN
/assign @sfwn 
| 🇺🇸 English |     updates to v1.2.0 changelog     |
| 🇨🇳 中文    |     v1.2.0 变更记录修正          |

updates to v1.2.0 changelog

---

modules/core-services/services/project/project.go
modules/openapi/component-protocol/scenarios/home-page-content/components/emptyProjectIssue/render.go
modules/openapi/component-protocol/scenarios/home-page-content/components/tableGroup/render.go
modules/openapi/component-protocol/scenarios/home-page-content/protocol.yml

bug
Fix work bench application list and empty content
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=208539&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMTA3MyJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=431&type=BUG)
1.2

Fix work bench application list and empty content

---

quick-start/quick-start.sh

/kind bug
update quick-start used code version to include the modified docker-compose

optimize: update quick-start code commit version

---

modules/cmp/endpoints/addons.go
modules/cmp/endpoints/cloud_resource.go
modules/cmp/endpoints/cloud_resource_account.go
modules/cmp/endpoints/cloud_resource_ecs.go
modules/cmp/endpoints/cloud_resource_vpc.go
modules/cmp/endpoints/cloud_resource_vsw.go
modules/cmp/endpoints/cluster.go
modules/cmp/endpoints/labels.go
pkg/erda-configs/permission/backend/sys/org/org.yml

/kind bug
bugfix support permission in cluster manaement
| 🇺🇸 English |    bugfix support permission in cluster manaement   |
| 🇨🇳 中文    |   修复集群群里接口的权限问题，supoort账户只读，其他一些缺失权限校验的变更接口也补充上  |

ops support permission bugfix

---

modules/gittar/pkg/gitmodule/commit.go
modules/gittar/pkg/gitmodule/repo_edit.go
modules/gittar/pkg/gitmodule/repo_edit_test.go

/kind feature
feature: add parentPath for git commit response
https://erda.cloud/erda/dop/projects/387/issues/all?id=206415&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG
/assign @sfwn  …

feature: add parentPath for git commit response

---

modules/scheduler/executor/plugins/k8s/deployment/deployment.go
pkg/parser/diceyml/define.go

/kind bug
fix the snippet not work bug.

fix patch snippet issue

---

README.md

Modify README.md file to update license statement

---

Makefile
cmd/orchestrator/main.go
conf/orchestrator/orchestrator.yaml
go.mod
go.sum
modules/core/monitor/log/storage/provider_test.go
modules/orchestrator/endpoints/endpoints.go
modules/orchestrator/initialize.go
modules/orchestrator/provider.go
pkg/loop/loop.go
pkg/loop/loop_test.go

/kind polish
The orchestrator need to run in singleton mode due to the cron jobs. 
Now we support it to run in "multiple instances" mode with the help of etcd features.
- [orchestrator 单点问题修复](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=207975&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMTM1NiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=506&type=TASK)
| 🇺🇸 English |  Support for orchestrator running with multiple instances …

support for orchestrator running with multi instances

---

modules/hepa/gateway/service/gateway_openapi_consumer_service.go
modules/hepa/gateway/service/gateway_zone_service.go
modules/hepa/k8s/k8s_adapter.go
modules/hepa/k8s/k8s_adapter_test.go

/kind feature
add more log about removing ingress 

add more log about removing ingress 

---

quick-start/quick-start.sh

/kind bug
on Mac, no netcat, only nc

bugfix: use nc command to check if netcat installed

---

modules/openapi/component-protocol/scenarios/home-page-sidebar/components/createProjectTip/render.go
modules/openapi/component-protocol/scenarios/home-page-sidebar/components/createProjectTipWithoutOrg/render.go
modules/openapi/component-protocol/scenarios/home-page-sidebar/components/emptyOrgText/render.go
modules/openapi/component-protocol/scenarios/home-page-sidebar/components/projectTipWithoutOrg/render.go

feature
/kind feature
/kind bug
/kind polish
/kind document
feat: update doc url in home page
https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=206749&issueFilter__urlQuery=eyJ0aXRsZSI6IumTvuaOpSIsInN0YXRlQmVsb25ncyI6WyJPUEVOIiwiV09SS0lORyIsIldPTlRGSVgiLCJSRU9QRU4iLCJSRVNPTFZFRCIsIkRPTkUiXSwiYXNzaWduZWVJRHMiOlsiMTAzOTAiLCIxMDc4NyJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=-1&type=TASK
| 🇺🇸 English |   feat: update doc url in home page           |
| 🇨🇳 中文 …

feat: update doc url in home page

---

CHANGELOG/CHANGELOG-1.x.md

/kind document
/assign @sfwn @daskyrk

add v1.2.1 changelog

---

README.md

/kind document
Update the installation documentation of the Readme
| 🇺🇸 English |      Update the installation documentation of the Readme        |
| 🇨🇳 中文    |       更新 Readme 安装部署文档       |

Update the installation documentation of the Readme

---

pkg/database/gormutil/logger.go
pkg/database/sqllint/linterror/error.go
pkg/database/sqllint/linters/allowed_stmt_linter.go
pkg/database/sqllint/linters/destruct_linter.go
pkg/database/sqllint/linters/keywords_linter.go
pkg/database/sqllint/linters/manual_time_setter_linter.go
pkg/database/sqllint/linters/not_null_linter_test.go
pkg/database/sqlparser/migrator/block.go
pkg/database/sqlparser/migrator/block_test.go
pkg/database/sqlparser/migrator/db.go
pkg/database/sqlparser/migrator/migrator.go
pkg/database/sqlparser/migrator/parameters.go
pkg/database/sqlparser/migrator/schema.go
pkg/database/sqlparser/migrator/script.go
pkg/database/sqlparser/migrator/scripts.go
pkg/database/sqlparser/pygrator/entrypoint.go
pkg/database/sqlparser/pygrator/entrypoint_test.go
pkg/database/sqlparser/pygrator/package.go
tools/cli/cmd/migrate.go

/kind feature
- support db connection timeout on migrator
- collect all SQLs excuted
- split and install script as blocks by DDL ro DML

feature: support db connection timeout in migrator; collect all SQLs executed; install script as block by DDL or DML

---

modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/cancelExecuteButton/render.go
modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/cancelExecuteButton/render_test.go
modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeAlertInfo/render.go
modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeInfo/render.go
modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeTaskTable/render.go
modules/openapi/component-protocol/scenarios/auto-test-plan-detail/protocol.yml
modules/pipeline/dbclient/op_pipeline_stage.go

/kind bug
Optimized the query speed of pipelineDetail.
Pass pipelineDetail between components.
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=67683&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDgwNSJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjIsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=506&type=BUG)
/assign sfwn

Optimize auto test plan detail

---

modules/cmp/steve/aggregator.go
modules/cmp/steve/formatter/node.go
modules/cmp/steve/predefined_resource.go

/kind polish
add pod exec access for support user

feat: add pod-exec access for support user

---

erda.yml

/kind bugfix
erda.yml dop add new tcp ports
/assign @Effet

erda.yml dop add new tcp ports

---

apistructs/issue_stream_locale.go
pkg/erda-configs/i18n/notify_item.yml

/kind feature
modify issue notify template
- [Erda Cloud Issue Link 1](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=57013&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDQzNiJdfQ%3D%3D&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG)
- [Erda Cloud Issue Link 2](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=208346&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDQzNiJdfQ%3D%3D&issueViewGroup__urlQuery=ey …

modify notify template

---

conf/dop/dop.yaml
erda.yml

/kind bugfix
- fix: dop yaml add missing pipeline cms config
- fix: erda.yml declare DOP_ADDR to avoid discover multi-ports issue
/assign @Effet

fix dop yaml config

---

pkg/kms/stores/etcd/store.go
pkg/kms/stores/etcd/store_test.go

/kind feature
feature: kms init check etcd status
local test screenshot:
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=206516&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDYsNDY3XSwic3RhdGVCZWxvbmdzIjpbIk9QRU4iLCJXT1JLSU5HIiwiV09OVEZJWCIsIlJFT1BFTiIsIlJFU09MVkVEIl0sImFzc2lnbmVlSURzIjpbIjkyIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=467&type=TASK)
/assign @iutx

feature: kms init check etcd status

---

modules/monitor/apm/topology/topology.go

/kind polish
/assign @recallsong @liuhaoyang

bugfix:service tag by serviceid

---

conf/dop/i18n/component-protocol.yaml
modules/dop/component-protocol/components/issue-manage/issueAddButton/render.go
modules/dop/component-protocol/components/issue-manage/issueFilter/model.go
modules/dop/component-protocol/components/issue-manage/issueFilter/render.go
modules/dop/component-protocol/components/issue-manage/issueGantt/model.go
modules/dop/component-protocol/components/issue-manage/issueGantt/render.go
modules/dop/component-protocol/components/issue-manage/issueTable/render.go
modules/dop/component-protocol/components/issue-manage/issueViewGroup/render.go

/kind feature
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=206472&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDQzNiJdfQ%3D%3D&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG)
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=206547&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDQzNiJdfQ%3D%3D&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcm …

issue-manage international

---

bundle/bundle.go
erda.yml
modules/dop/initialize.go
modules/dop/provider.go

/kind bug
fix dop registry to eventbox
/assign @sfwn

fix dop addr

---

erda.yml
modules/core/services/authentication/credentials/accesskey/model.go
modules/core/services/authentication/credentials/accesskey/model_test.go

access_key table name fix

---

erda.yml

fix svc name

---

.erda/migrations/qa/20210830-test-plan-isarchived.sql
apistructs/audits.go
apistructs/testplan.go
modules/dop/dao/testplan.go
modules/dop/services/testplan/testplan.go
pkg/erda-configs/audit/template.json

feature
Manual test plan list and update by new isArchived property
/assign @sfwn 
| 🇺🇸 English |  Test plan supports archive |
| 🇨🇳 中文    |   测试计划增加归档        |

Manual test plan list and update by new isArchived property

---

modules/openapi/component-protocol/scenarios/cmp-dashboard-events/components/eventTable/render.go
modules/openapi/component-protocol/scenarios/cmp-dashboard-workload-detail/components/podsTable/model.go
modules/openapi/component-protocol/scenarios/cmp-dashboard-workload-detail/components/podsTable/render.go
modules/openapi/component-protocol/scenarios/cmp-dashboard-workload-detail/components/podsTable/render_test.go
modules/openapi/component-protocol/scenarios/cmp-dashboard-workload-detail/components/podsTableTitle/model.go
modules/openapi/component-protocol/scenarios/cmp-dashboard-workload-detail/components/podsTableTitle/render.go
modules/openapi/component-protocol/scenarios/cmp-dashboard-workload-detail/components/workloadInfo/model.go
modules/openapi/component-protocol/scenarios/cmp-dashboard-workload-detail/components/workloadInfo/render.go
modules/openapi/component-protocol/scenarios/cmp-dashboard-workload-detail/components/workloadInfo/render_test.go
modules/openapi/component-protocol/scenarios/cmp-dashboard-workload-detail/components/workloadInfoTitle/model.go
modules/openapi/component-protocol/scenarios/cmp-dashboard-workload-detail/components/workloadInfoTitle/render.go
modules/openapi/component-protocol/scenarios/cmp-dashboard-workload-detail/components/workloadStatus/model.go
modules/openapi/component-protocol/scenarios/cmp-dashboard-workload-detail/components/workloadStatus/render.go
modules/openapi/component-protocol/scenarios/cmp-dashboard-workload-detail/components/workloadTitle/model.go
modules/openapi/component-protocol/scenarios/cmp-dashboard-workload-detail/components/workloadTitle/render.go
modules/openapi/component-protocol/scenarios/cmp-dashboard-workload-detail/protocol.yml
modules/openapi/component-protocol/scenarios/cmp-dashboard-workload-detail/util.go
modules/openapi/component-protocol/scenarios/cmp-dashboard-workloads/components/workloadChart/render.go
modules/openapi/component-protocol/scenarios/cmp-dashboard-workloads/components/workloadTable/render.go
modules/openapi/component-protocol/scenarios/cmp-dashboard-workloads/util.go

/kind feature
add workload detail scenario

feat: add workload detail scenario

---

modules/extensions/loghub/index/query/clients.go
modules/extensions/loghub/index/query/clients_test.go
modules/msp/resource/deploy/handlers/loganalytics/loganalytics.go
modules/msp/resource/deploy/handlers/logservice/logservice.go
modules/msp/resource/utils/es_client.go

/kind feature
/kind bug
add org flag to log-service index alias

optimize: add org flag to log-service index alias

---

conf/monitor/extensions/loghub/output/elasticsearch.index.template.json

/kind feature
change log-service default replicas to 1

optimize: change log-service default replicas

---

modules/cmp/impl/clusters/clusterinfo.go

/kind feature
optimize get clusterinfo
| 🇺🇸 English |  optimize get clusterinfo           |
| 🇨🇳 中文    |    优化集群管理列表展示          |

feature: optimize get clusterinfo

---

modules/pipeline/dbclient/op_pipeline_delete.go
modules/pipeline/dbclient/op_pipeline_delete_test.go
modules/pipeline/pipengine/reconciler/dbgc.go
modules/pipeline/pipengine/reconciler/dbgc_test.go

/kind bug
Compensation for database gc, some data may not be ns gc, an error will be reported when calling the interface
erda-issue: [erda-issue](https://erda.cloud/erda/dop/projects/387/issues/all?id=72979&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDU2MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG)

database gc When the ttl time arrives, you should not care whether it is ns gc

---

conf/openapi/openapi.yaml
erda.yml
go.mod
go.sum
modules/core/openapi-ng/auth/auth.go
modules/core/openapi-ng/auth/uc-session/provider.go
modules/core/openapi-ng/interceptors/csrf/csrf.go
modules/core/openapi-ng/interface.go
modules/core/openapi-ng/provider.go
modules/core/openapi-ng/proxy/proxy.go
modules/core/openapi-ng/route.go
modules/core/openapi-ng/routes/dynamic/manager.go
modules/core/openapi-ng/routes/dynamic/provider.go
modules/core/openapi-ng/routes/dynamic/static/proxy.html
modules/core/openapi-ng/routes/dynamic/static/proxy.js
modules/core/openapi-ng/routes/dynamic/test.http
modules/core/openapi-ng/routes/proto/auth.go
modules/core/openapi-ng/routes/proto/provider.go
pkg/discover/address.go

/kind feature
support openapi dynamic api
| 🇨🇳 中文    |    openapi 支持开发模式下的动态路由     |

support openapi dynamic api

---

apistructs/cluster_info.go
modules/pipeline/services/pipelinesvc/secret.go
modules/pipeline/services/pipelinesvc/secret_test.go

/kind feature
Added docker username and password
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=210067&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDgwNSJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=506&type=TASK)
/assign @sfwn 
| 🇺🇸 English |     Support third-party docker registry        |
| 🇨🇳 中文    |   支持第三方 docker registry          |

add docker registry username/password 

---

modules/msp/apm/trace/trace.service.go

bugfix: fix pspanid=spanid,Cause the recursive stack overflow

---

modules/msp/apm/trace/trace.service.go

bugfix: span.ParentSpanId = "" when spanid=pspanid

---

conf/openapi/openapi.yaml
modules/core/openapi-ng/interceptors/csrf/csrf.go
tools/gotools/go-test-sum/main.go

/kind feature
1、set csrf cookie path
2、check no test files package

set csrf cookie path、check no test files package

---

apistructs/job.go
apistructs/pipeline.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sflink/flink.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sjob/k8sjob.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sspark/k8sspark.go
modules/pipeline/pipengine/actionexecutor/plugins/scheduler/logic/job.go
modules/pipeline/services/pipelinesvc/create_task.go
modules/pipeline/services/pipelinesvc/create_task_test.go
modules/pipeline/services/pipelinesvc/create_v2.go
modules/pipeline/services/pipelinesvc/create_v2_test.go
modules/pipeline/spec/pipeline_extra.go
modules/pipeline/spec/pipeline_task.go

/kind feature
support upper layer customize pipeline namespace
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=58451&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=TASKe)
| 🇺🇸 English |  support customize namespace            |
| 🇨🇳 中文    |   支持上层自定义流水线命名空间           |
> For …

support upper layer customize pipeline namespace

---

modules/scheduler/executor/plugins/k8s/runtime.go
modules/scheduler/executor/plugins/k8s/runtime_test.go
modules/scheduler/executor/plugins/k8s/service.go

/kind bug
fix(service): replace service domain to clusterip for service
| 🇺🇸 English |fix(service): replace clusterIP to service domain for service           |
| 🇨🇳 中文    | 在服务详情中使用域名替换clusterip           |

fix(service): replace clusterIP to service domain for service

---

pkg/erda-configs/permission/front/org/org.yml

/kind feature
add view auditor log permission in org scope
/assign @Effet

add view auditor log permission in org scope

---

apistructs/release.go
apistructs/release_test.go
modules/dicehub/endpoints/publish_item.go
modules/dicehub/endpoints/publish_item_test.go

/kind feature
support android aab 
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=208336&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDQzNiJdfQ%3D%3D&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=TASK)
/assign @Effet

support aab

---

apistructs/extension_test.go
apistructs/extention.go
modules/dicehub/extension/extention.service_test.go

/kind feature
image version from "1.3-xxxxxx-xxxx" to "1.3.0-alpha-xxxxxxx-xxxxxx"
update Check()
https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=217915&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDgzMiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=TASK

support new Erda image version 

---

Makefile
build/scripts/docker_image.sh

This reverts commit 60d3d3af77038ef8c77f40b37da9c77f612fe133.
/kind polish

Revert "revert version change temporary (#1583)"

---

conf/cmp/i18n/component-protocol.yaml
modules/cmp/component-protocol/components/cmp-dashboard-events-list/eventTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-events-list/eventTable/render_test.go
modules/cmp/component-protocol/components/cmp-dashboard-events-list/filter/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/podsTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/podsTable/render_test.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/podsTableTitle/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/workloadInfo/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/workloadInfoTitle/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/filter/model.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/filter/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadChart/model.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadChart/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadChart/render_test.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadTable/model.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadTable/render_test.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadTitle/model.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadTitle/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadTitle/render_test.go
modules/cmp/component-protocol/scenarios/cmp-dashboard-workloads-list.yml

/kind feature
1. cmp component-protocol supports i18n
2. fix workloadChart and workloadTitle in scenario workloads-list

add cmp cp i18n; modify workloadChart and workloadTitle

---

pkg/erda-configs/permission/front/org/org.yml

/kind feature
add entryOrgCenter permission for Auditor

add entryOrgCenter permission for Auditor

---

modules/cluster-agent/client/client.go

/kind feature
cluster-agent connect dialer used service address at inner cluster
| 🇺🇸 English |  optimize cluster-agent connect at inner cluster    |
| 🇨🇳 中文    |  优化 cluster-agent 连接方式，Erda 所在集群通过 service 地址            |

feature: optimize cluster-agent connect at inner cluster

---

erda.yml

/kind feature
- update(erda.yml): support cpu bound label
| 🇺🇸 English |  update(erda.yml): support cpu bound label            |
| 🇨🇳 中文    |    更新 erda.yml 使组件支持 cpu bound 标签          |

update(erda.yml): support cpu bound label

---

modules/core-services/endpoints/audit.go

/kind bug
create audit shoulde allowed scope_id is 0
/assign @Effet

fix create audit

---

apistructs/pipeline_report.go
conf/pipeline/pipeline.yaml
modules/pipeline/aop/plugins/all.go
modules/pipeline/aop/plugins/pipeline/testplan_before/plugin.go
modules/pipeline/aop/plugins/pipeline/testplan_before/plugin_test.go

/kind feature
when autotest-plan is executed,report configuration

add aop autotest-plan-before

---

erda.yml

/kind feature
update erda.yml
add etcd binds for gittar
/assign @sfwn 
| 🇺🇸 English |      update erda.yml        |
| 🇨🇳 中文    |        修改erda.yml      |

fix: update erda.yml

---

modules/orchestrator/services/addon/addon.go
modules/orchestrator/services/addon/addon_helper.go
modules/orchestrator/services/addon/addon_test.go

/kind bug
fix update password or secret of  custom addon error
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=219208&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDQzNiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=506&type=BUG)
/assign @Effet

fix update custom addon

---

modules/dop/endpoints/issue.go
modules/dop/services/i18n/i18n.go
modules/dop/services/issue/convert.go
modules/dop/services/issue/convert_test.go
modules/dop/services/issue/export.go
pkg/erda-configs/i18n/issue.json

feature
Add a sample line in issue import donwload template
/assign @Effet  @sfwn

Add a sample line in issue import download template

---

.erda/migrations/qa/20210903-auto-test-plan-isarchived.sql
apistructs/audits.go
apistructs/testplan_v2.go
modules/dop/dao/testplan_v2.go
modules/dop/services/autotest_v2/testplan_v2.go
modules/dop/services/testplan/testplan.go
modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/filter/render.go
modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/filter/render_test.go
modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/table/render.go
modules/openapi/component-protocol/scenarios/auto-test-plan-list/protocol.yml
pkg/erda-configs/audit/template.json

feature
Auto test plans supports archive operation

Auto test plans supports archive operation

---

conf/msp/msp.yaml

/kind bug
| 🇺🇸 English |      modify msp connect core-services        |
| 🇨🇳 中文    |      修改core-services连接路径        |

modify msp connect core-services

---

modules/core-services/services/project/project.go
modules/core-services/services/project/project_test.go

/kind feature
remove check addon exist when delete project
/assign @Effet

remove check addon exist when delete project

---

conf/monitor/log-service/log-service.yaml
modules/extensions/loghub/exporter/output.go
modules/extensions/loghub/exporter/output_test.go
modules/extensions/loghub/metrics/analysis/consumer.go
modules/msp/resource/deploy/handlers/logservice/logservice.go

/kind feature
/kind bug
/kind polish
/kind document

Rename msp_tenant_id to msp_env_id

---

quick-start/quick-start.sh

/kind feature
quick-start use oss to speed up download

optimize: quick-start use oss to speed up download

---

.erda/migrations/qa/20210906-auto-test-plan-execute.sql
apistructs/component_protocol.go
modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/envBaseInfo/render.go
modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/envBaseInfoTitle/render.go
modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/envDrawer/render.go
modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/envGlobalInfo/render.go
modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/envGlobalTable/render.go
modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/envGlobalText/render.go
modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/envGlobalText/render_test.go
modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/envGlobalTitle/render.go
modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/envHeaderInfo/render.go
modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/envHeaderTable/render.go
modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/envHeaderText/render.go
modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/envHeaderTitle/render.go
modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeInfo/render.go
modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeInfo/render_test.go
modules/openapi/component-protocol/scenarios/auto-test-plan-detail/protocol.yml

/kind feature
add components to show autotest-plan execute env

add autotest-plan-env components

---

Makefile

/kind bug
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/bug?id=220573&issueFilter__urlQuery=eyJ0aXRsZSI6IumbhuaIkOeOr%2BWigyIsInN0YXRlQmVsb25ncyI6WyJPUEVOIiwiV09SS0lORyIsIldPTlRGSVgiLCJSRU9QRU4iLCJSRVNPTFZFRCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=506&type=BUG)
/assign @Effet

use MAJOR.MINOR as the Erda version to avoid unexpected broken

---

modules/msp/resource/deploy/handlers/logservice/logservice.go

/kind bug
bugfix: for log-service, use tenantGroup as part of es index name

bugfix: for log-service, use tenantGroup as part of es index name

---

modules/dop/services/autotest_v2/scene.go

/kind bug
convert config value like input param
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=210912&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG)

convert config value like input param

---

modules/cmp/steve/predefined_resource.go

/kind bug
fix pod/exec permission for support user

fix: support user does not have access for pod/exec

---

erda.yml

/kind feature
increase pipeline replica
| 🇺🇸 English |  increase pipeline replica            |
| 🇨🇳 中文    |  增加pipeline实例数            |

increase pipeline replica

---

cmd/dop/main.go
conf/dop/dop.yaml
modules/dop/endpoints/autotests.http
modules/dop/endpoints/endpoints.go
modules/dop/endpoints/pipeline_definition.go
modules/dop/initialize.go
modules/dop/provider.go
modules/dop/services/apierrors/errors.go
modules/dop/services/filetree/filetree.go
modules/dop/services/pipeline/pipeline.go
modules/dop/services/pipeline/pipeline_test.go
modules/pipeline/providers/definition_client/provider.go
modules/pipeline/providers/definition_client/provider_test.go

/kind feature
synchronize autotest, config-sheet, project-pipeline, gittar-pipeline to pipeline in dop
erda-issue: [erda-issue](https://erda.cloud/erda/dop/projects/387/issues/all?id=206835&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDU2MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=TASK)

pipeline definition sync provider and gittar yml sync to pipeline

---

modules/openapi/component-protocol/scenarios/issue-manage/components/issueTable/render.go

/kind feature
Add complexity column in issue table
/assign @hoozecn 

Add complexity column in issue table

---

go.mod
go.sum
modules/core/services/authentication/credentials/accesskey/dao.go
modules/msp/credential/credential.service.go

/kind fix
| 🇺🇸 English |        ak add scope and scopeid      |
| 🇨🇳 中文    |      ak增加scope和scopeid以区分环境        |

ak add scope and scopeid

---

cmd/openapi/main.go
conf/monitor/streaming/streaming.yaml
conf/openapi/openapi.yaml
erda.yml
go.mod
go.sum
modules/core/openapi-ng/routes/dynamic/manager.go
modules/core/openapi-ng/routes/dynamic/provider.go
modules/core/openapi-ng/routes/dynamic/remote_forward.go
modules/core/openapi-ng/routes/dynamic/temporary/provider.go

/kind feature
1、openapi support forward request to local
2、adjust metric clean disk threshold
| 🇺🇸 English |       openapi support forward request to local     |
| 🇨🇳 中文    |       openapi 支持转发请求到本地    |

openapi support forward request to local

---

bundle/events.go
cmd/dop/main.go
conf/dop/dop.yaml
conf/pipeline/pipeline.yaml
modules/dop/initialize.go
modules/dop/provider.go
modules/dop/providers/autotest/testplan/db/table.go
modules/dop/providers/autotest/testplan/db/testplan.go
modules/dop/providers/autotest/testplan/provider.go
modules/dop/providers/autotest/testplan/register_test.go
modules/dop/providers/autotest/testplan/register_webhook.go
modules/dop/providers/autotest/testplan/testplan.service.go
modules/dop/providers/autotest/testplan/testplan.service_test.go
modules/pipeline/aop/plugins/all.go
modules/pipeline/aop/plugins/pipeline/testplan_after/plugin.go
modules/pipeline/aop/plugins/pipeline/testplan_after/plugin_test.go
pkg/erda-configs/i18n/notify_item.yml

/kind feature
add aop testplan-after, update plan pass_rate and execute_time, send DINGING

refactor testPlan in dop to provider, add aop testplan-after

---

.erda/migrations/cmdb/20210907-add-notify-item.sql

/kind feature
add notify-item sql
https://erda.cloud/erda/dop/projects/387/issues/requirement?id=203536&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=506&type=REQUIREMENT

add notify-item sql

---

conf/dop/dop.yaml

/kind feature
due to the addition of the autotest provider, it depends on the mysql provider

add mysql provider in conf dop.yml

---

conf/cmp/i18n/component-protocol.yaml
modules/cmp/component-protocol/components/cmp-dashboard-podDetail/eventTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-podDetail/eventTable/render_test.go
modules/cmp/component-protocol/components/cmp-dashboard-podDetail/podInfo/model.go
modules/cmp/component-protocol/components/cmp-dashboard-podDetail/podInfo/render.go
modules/cmp/component-protocol/components/cmp-dashboard-pods/filter/render.go
modules/cmp/component-protocol/components/cmp-dashboard-pods/podDistribution/model.go
modules/cmp/component-protocol/components/cmp-dashboard-pods/podDistribution/render.go
modules/cmp/component-protocol/components/cmp-dashboard-pods/podTitle/model.go
modules/cmp/component-protocol/components/cmp-dashboard-pods/podTitle/render.go
modules/cmp/component-protocol/components/cmp-dashboard-pods/podsTable/model.go
modules/cmp/component-protocol/components/cmp-dashboard-pods/podsTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/podsTable/render.go
modules/cmp/component-protocol/scenarios/cmp-dashboard-poddetail.yml
modules/cmp/component-protocol/scenarios/cmp-dashboard-pods.yml
pkg/jsonstore/etcd/etcd.go

/kind bug
fix podslist and podDetail

fix podslist and podDetail

---

conf/msp/i18n/msp-i18n.yaml
go.mod
go.sum
modules/msp/apm/trace/core/common/common.go
modules/msp/apm/trace/core/debug/debug.go
modules/msp/apm/trace/core/query/query.go
modules/msp/apm/trace/core/query/query_test.go
modules/msp/apm/trace/trace.service.go
modules/msp/apm/trace/trace.service_test.go

feature: optimization trace query

---

pkg/jsonstore/etcd/etcd.go

Fix etcd path

---

apistructs/audits.go
modules/dop/endpoints/issue_state.go
modules/dop/services/testplan/testplan.go
modules/dop/services/testplan/testplan_test.go
modules/openapi/api/apis/dop/cmdb_issue_state_delete.go
modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/table/render.go

feature
Add audit of issue state creation and deletion

Add audit of issue state creation and deletion

---

go.mod

/kind polish
fix security risk.
/assign @johnlanni

polish go.mod

---

.erda/migrations/cmdb/20210908-update-notify-item.sql

/kind feature
label should be "workbench" but there are two item are "workbanch"

update nofity-item in SQL, the field is misspelled

---

apistructs/pipeline_yml.go
modules/pipeline/pipengine/reconciler/taskrun/taskop/prepare.go
pkg/expression/expression_reconcile.go
pkg/parser/pipelineyml/define.go
pkg/parser/pipelineyml/graph_pipelineyml.go
pkg/parser/pipelineyml/graph_pipelineyml_test.go
pkg/parser/pipelineyml/pipelineyml.go
pkg/parser/pipelineyml/samples/trigger.yml
pkg/parser/pipelineyml/visitor_labels.go

/kind feature
Added pipeline trigger syntax and expression
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=208384&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDA4MDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=TASK)
- [test-link](https://erda.dev.terminus.io/terminus/dop/projects/1/apps/3/pipeline?nodeId=MS8zL3RyZWUvZGV2ZWxvcC9waXBlbGluZS55bWw%3D&pipelineID=34481)

add pipeline trigger syntax and expression

---

apistructs/issue.go

/kind bug
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/bug?id=221354&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=506&type=BUG)
/assign @hoozecn  …

fix panic when complexity is empty

---

modules/dop/endpoints/pipeline.go
modules/dop/endpoints/pipeline_test.go
modules/dop/endpoints/pipelinecron.go

/kind feature
updateCmsNsConfigs when pipeline create and cron start
/assign @sfwn 
| 🇺🇸 English |    updateCmsNsConfigs when pipeline create and cron start          |
| 🇨🇳 中文    |      创建流水线和定时任务开启幂等创建cms        |

feature: updateCmsNsConfigs when pipeline create and cron start

---

conf/dop/i18n/component-protocol.yaml
modules/dop/component-protocol/components/issue-manage/issueTable/render.go
modules/dop/component-protocol/components/issue-manage/issueTable/render_test.go

/kind feature
add complexity in issue table
/assign @sfwn 

add complexity in issue table

---

apistructs/cmp_metrics.go
conf/monitor/monitor/chartview/cmp/cmp-dashboard-nodeDetail.json
modules/cmp/component-protocol/components/cmp-dashboard-nodeDetail/common/model.go
modules/cmp/component-protocol/components/cmp-dashboard-nodeDetail/infoDetail/model.go
modules/cmp/component-protocol/components/cmp-dashboard-nodeDetail/infoDetail/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/chart/model.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/filter/filter.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/model.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/table/table.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/cpuTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/memTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/nodeFilter/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/podTable/render.go
modules/cmp/component-protocol/scenarios/cmp-dashboard-nodes.yml
modules/cmp/metrics/metrics.go

fix: 🐛 cmp dashboard node list

---

.erda/migrations/cmdb/20210831-issue-expiry-status.sql
apistructs/issue.go
apistructs/project.go
apistructs/workbench.go
bundle/project.go
modules/core-services/endpoints/endpoints.go
modules/core-services/endpoints/project.go
modules/dop/conf/conf.go
modules/dop/dao/issue.go
modules/dop/endpoints/workbench.go
modules/dop/initialize.go
modules/dop/services/issue/issue.go
modules/dop/services/issue/issue_test.go
modules/dop/services/workbench/workbench.go
modules/dop/services/workbench/workbench_test.go

feature
Workbench data and issue query optimization by issue expiry status

Workbench data and issue query optimization by issue expiry status

---

conf/cmp/i18n/component-protocol.yaml
modules/cmp/component-protocol/components/cmp-dashboard-nodeDetail/infoMapTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/filter/filter.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/cpuTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/memTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/podTable/render.go

/kind feature
fix cmp dashboard i18n dict

fix cmp dashboard i18n dict

---

erda.yml

change hepa health check

---

modules/action-runner-scheduler/provider.go

change action-runner-scheduler service name

---

modules/openapi/api/apis/msp/apm/trace/get_trace_conditions_list.go

feature: openapi conditions

---

README.md

/kind bug
error install link
| 🇺🇸 English | fix  error install link            |
| 🇨🇳 中文    |   修复安装引导里的错误链接           |

fix: error install link

---

README.md

/kind bug
fix: readme 1.2 link error
| 🇺🇸 English |  readme 1.2 link error            |
| 🇨🇳 中文    |    修复1.2安装引导链接错误          |

fix: readme 1.2 link error

---

.erda/migrations/pipeline/20210908-create-pipeline-triggers.sql
cmd/pipeline/main.go
conf/pipeline/pipeline.yaml
modules/pipeline/initialize.go
modules/pipeline/provider.go
modules/pipeline/providers/trigger/db/op.go
modules/pipeline/providers/trigger/db/op_test.go
modules/pipeline/providers/trigger/db/table.go
modules/pipeline/providers/trigger/provider.go
modules/pipeline/providers/trigger/trigger.service.go
modules/pipeline/providers/trigger/trigger.service_test.go

/kind feature
add custom pipeline trigger
See the link below for details
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=208384&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDA4MDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=TASK)
/assign @sfwn

add pipeline trigger provider

---

modules/msp/apm/trace/trace.service.go

bugfix:fix span query oom

---

modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/table/render.go
modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/table/table_test.go

/kind feature
for component-protocol, update table component passRate filed type to string
| 🇺🇸 English |      update passRate filed type to string        |
| 🇨🇳 中文    |     通过率字段类型变为字符串         |

update table component passRate filed type to string

---

go.mod
go.sum
modules/hepa/common/log_helper.go
modules/hepa/common/vars/vars.go
modules/hepa/gateway/dto/open_limit_rule_dto.go
modules/hepa/kong/dto/kong_credential_resp_dto.go
modules/hepa/providers/domain/provider.go
modules/hepa/providers/micro_api/provider.go
modules/hepa/providers/micro_api/service.go
modules/hepa/providers/org_client/provider.go
modules/hepa/providers/runtime_service/provider.go
modules/hepa/services/api_policy/impl/impl.go
modules/hepa/services/micro_api/impl/impl.go
modules/hepa/services/openapi_rule/impl/impl.go
modules/monitor/common/permission/permission.go

/kind bug
fix some refactor bugs

fix some bugs

---

conf/cmp/i18n/component-protocol.yaml
conf/monitor/monitor/chartview/cmp/pod-detail.json
modules/cmp/component-protocol/components/cmp-dashboard-events-list/eventTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-events-list/filter/model.go
modules/cmp/component-protocol/components/cmp-dashboard-events-list/filter/render.go
modules/cmp/component-protocol/components/cmp-dashboard-podDetail/containerTable/model.go
modules/cmp/component-protocol/components/cmp-dashboard-podDetail/containerTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-podDetail/eventTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-podDetail/eventTitle/render.go
modules/cmp/component-protocol/components/cmp-dashboard-podDetail/podInfo/render.go
modules/cmp/component-protocol/components/cmp-dashboard-podDetail/podStatus/render.go
modules/cmp/component-protocol/components/cmp-dashboard-pods/filter/model.go
modules/cmp/component-protocol/components/cmp-dashboard-pods/filter/render.go
modules/cmp/component-protocol/components/cmp-dashboard-pods/podDistribution/render.go
modules/cmp/component-protocol/components/cmp-dashboard-pods/podsTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/podsTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/workloadStatus/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/filter/model.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/filter/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadChart/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadTable/render.go

/kind bug
fix some bug in dashboard component-protocol

Fix test cp

---

conf/cmp/i18n/component-protocol.yaml
conf/monitor/monitor/chartview/cmp/cmp-dashboard-nodeDetail.json
modules/cmp/component-protocol/components/cmp-dashboard-nodeDetail/addLabelModal/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/addLabelModal/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/chart/model.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/filter/filter.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/model.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/table/table.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/table/table_test.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/cpuTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/memTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/nodeFilter/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/podTable/render.go
modules/cmp/metrics/metrics.go

add some feature, fix some display problems and bugs
/kind feature
/kind bug
add some feature and fix some bugs
@johnlanni 

fix: 🐛 nodes list page of cmp dashboard

---

go.mod
go.sum
modules/hepa/providers/runtime_service/runtime.service.go

fix hepa proto issue

---

modules/extensions/loghub/index/query/clients.go
modules/extensions/loghub/index/query/clients_test.go
modules/extensions/loghub/index/query/db/log_deployment.go
modules/extensions/loghub/index/query/index.go
modules/extensions/loghub/index/query/log_query.go
modules/extensions/loghub/index/query/log_query_v1.go
modules/extensions/loghub/index/query/log_query_v2.go
modules/extensions/loghub/index/query/provider.go
modules/extensions/loghub/index/query/routes.go

/kind feature
log-query, filter indices by index-meta
| 🇺🇸 English |     speed up log-query         |
| 🇨🇳 中文    |      优化日志分析查询速度        |

feature: log-query, filter indices by index-meta

---

.github/workflows/ci-it.yml

/kind bug
fix: add env for test ci
/assign @sfwn 

fix: add env for test ci

---

modules/extensions/loghub/index/query/provider.go

/kind feature
log-query index-preload enabled by default

optimize: log-query index-preload enabled by default

---

erda.yml

/kind feature
/kind bug
/kind polish
/kind document

Update monitor resource

---

erda.yml

feature: change log-service default replicas to 0.

---

bundle/steve.go
bundle/steve_node.go
conf/monitor/monitor/chartview/cmp/cmp-dashboard-podDetail.json
modules/cmp/component-protocol/components/cmp-dashboard-podDetail/containerTable/model.go
modules/cmp/component-protocol/components/cmp-dashboard-podDetail/containerTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-podDetail/podStatus/model.go
modules/cmp/component-protocol/components/cmp-dashboard-podDetail/podStatus/render.go
modules/cmp/component-protocol/components/cmp-dashboard-pods/podDistribution/render.go
modules/cmp/component-protocol/components/cmp-dashboard-pods/podsTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/podsTable/model.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/podsTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/workloadStatus/model.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/workloadStatus/render.go
modules/cmp/component-protocol/scenarios/cmp-dashboard-poddetail.yml
modules/cmp/component-protocol/scenarios/cmp-dashboard-workload-detail.yml

/kind bug
1. fix pod metrics monitor
2. request target pods rather than all pods
3. fix steve bundle

fix pods list and pod detail

---

modules/orchestrator/services/addon/addon.go
modules/orchestrator/services/addon/addon_helper.go
modules/orchestrator/services/addon/addon_test.go

/kind bug
Fix bad encrypt value of custom addon

Fix bad encrypt value of custom addon

---

erda.yml

/kind bug
1. fix replicas error about cmp\schduler\cluster-manager.
2. optimize cmp resources.
| 🇺🇸 English |   fix replicas error and cmp resource.           |
| 🇨🇳 中文    |   修复cmp、scheduler、cluster-manager 副本数错误及优化 cmp 资源           |

fix: fix replicas error and cmp resource.

---

modules/openapi/api/apis/cmp/cmp_k8s_patch.go

add cmp k8s patch api

---

erda.yml

/kind bug
fix replicas error, comp: cmp,scheudler,cluster-manager,hepa
| 🇺🇸 English |  fix replicas( cmp,scheudler,cluster-manager,hepa)            |
| 🇨🇳 中文    |   修复 cmp scheduler cluster-manager hepa 高可用实例数           |

fix: fix replicas( cmp,scheudler,cluster-manager,hepa)

---

modules/dop/dao/issue.go

bug
Fix query issue by not deleted 

Fix query issue by not deleted 

---

modules/dop/services/autotest_v2/scene.go

/kind feature
Automated test step running uses the last execution record of the current scene to render the ${{ outputs.xxx.xxx }} placeholders in it

automated test step execution optimization

---

modules/openapi/component-protocol/scenarios/action/components/actionForm/render.go

/kind bug
If the 1.2 version of erda uses mysql-cli, there will be compatibility issues
action pr: https://github.com/erda-project/erda-actions/pull/189

roll back the render function of mysql-cli

---

erda.yml

/kind bug
fix: update git inner user of erda.yml
https://erda.cloud/erda/dop/projects/387/issues/all?id=222097&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=-1&type=BUG
/assign @sfwn 
| 🇺🇸 English |      update git inner user        |
| 🇨🇳 中文    |         修改git默认账户     | …

fix: update git inner user of erda.yml

---

modules/msp/apm/trace/trace.service.go

polish: span limit 10000

---

modules/extensions/loghub/index/query/log_query_v1.go
modules/extensions/loghub/index/query/log_query_v2.go

/kind feature
feature: support es query_string AND OR operator
| 🇺🇸 English |      support es query_string AND OR operator        |
| 🇨🇳 中文    |      支持es query_string AND OR operator        |

feature: support es query_string AND OR operator

---

modules/dop/services/autotest_v2/scene.go

/kind bug
The automated test step is executed, and the parsing will fail when the output parameter is json
Associated pr: https://github.com/erda-project/erda/pull/1794#issue-993006475

Automated test step executes json output parameter analysis

---

modules/core/monitor/log/query/query.go
modules/core/monitor/log/query/query_test.go
modules/core/monitor/log/query/routes.go

/kind feature
/kind bug
/kind polish
/kind document
query all log and then filter

Log query count limit

---

erda.yml
modules/gittar/auth/auth.go
modules/gittar/conf/conf.go
modules/gittar/models/permission.go
modules/pipeline/conf/conf.go

/kind feature
fix: remove git inner user env and conf
/assign @sfwn 
| 🇺🇸 English |       remove git inner user env and conf        |
| 🇨🇳 中文    |        移除git默认账户环境变量和配置      |

fix: remove git inner user env and conf

---

modules/pipeline/services/pipelinesvc/secret.go
modules/pipeline/services/pipelinesvc/secret_test.go

…resses of different types
/kind bug
add Determine the splicing result according to the given registry addresses of different types.
registry/org-project/app:tag =>  registry/org-project-app:tag
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/bug?id=220319&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=0&type=BUG)

add Determine the splicing result according to the given registry addresses of different types

---

modules/cluster-agent/client/client.go
modules/cmp/i18n/i18n.go
modules/cmp/impl/clusters/clusterinfo.go

/kind bug
1. fix: cluster-agent connect ep error when not inner cluster
2. optimize clusterinfo display
| 🇺🇸 English |   fix: cluster-agent connect ep error when not inner cluster   2. optimize clusterinfo display        |
| 🇨🇳 中文    |    1. 修复 cluster-agent 边缘集群链接中心 endpoint 错误问题  2. 优化集群详情信息名称显示         | …

fix: cluster-agent connect ep error when not inner cluster

---

pkg/parser/diceyml/define.go
pkg/parser/diceyml/define_test.go

/kind feature
A more simplify erda.yaml marshal format.

optimize erda.yml marshal

---

modules/pipeline/services/pipelinesvc/create.go
modules/pipeline/services/pipelinesvc/create_test.go

/kind bug
detail return pipeline disable action

detail return pipeline disable action

---

modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/filter/render.go
modules/openapi/component-protocol/scenarios/auto-test-plan-list/protocol.yml

bug
Auto test plan archive default filter value

Auto test plan archive default filter value

---

modules/scheduler/executor/plugins/k8s/clusterinfo/clusterinfo.go

/kind feature
feature: scheduler support return registry secret.
| 🇺🇸 English |  scheduler support return registry secret.            |
| 🇨🇳 中文    |    scheduler 支持返回 registry 认证信息          |

feature: scheduler support return registry secret.

---

modules/cmp/i18n/i18n.go
modules/cmp/impl/clusters/clusterinfo.go

/kind feature
fix: optimize cluster info display
| 🇺🇸 English | optimize cluster info display             |
| 🇨🇳 中文    |   优化集群标识显示         |

optimize cluster info display

---

modules/msp/apm/trace/trace.service.go

bugfix: fix trace depth

---

cmd/msp/main.go
conf/msp/msp.yaml
conf/openapi/openapi.yaml
modules/msp/apm/checker/apis/provider.go

add audit for msp

---

go.mod
go.sum

/kind polish
| 🇨🇳 中文    |     优化etcd分布式锁         |

update erda infra version

---

conf/cmp/i18n/component-protocol.yaml
modules/cmp/component-protocol/components/cmp-dashboard-nodeDetail/infoDetail/model.go
modules/cmp/component-protocol/components/cmp-dashboard-nodeDetail/infoDetail/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/addLabelModal/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/chart/model.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/filter/filter.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/table/table.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/cpuTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/memTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/nodeFilter/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/nodeFilter/render_test.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/tableTabs/model.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/tableTabsContainer/render.go

data demonstrate, i18n and component
/kind bugfix
fix bugs of search,add labal, i18n, color
@johnlanni 

fix: 🐛 some bugs of cmp dashboard

---

.github/stale.yml

add stale file to close stale issues

---

Makefile
go.mod
go.sum
pkg/common/errors/data.go

/kind bug
fix AlreadyExistsError http status

fix AlreadyExistsError http status

---

modules/cmp/component-protocol/components/cmp-dashboard-events-list/eventTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-events-list/eventTable/render_test.go
modules/cmp/component-protocol/components/cmp-dashboard-pods/filter/render.go
modules/cmp/component-protocol/components/cmp-dashboard-pods/podsTable/model.go
modules/cmp/component-protocol/components/cmp-dashboard-pods/podsTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/podsTable/model.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/podsTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/workloadInfo/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/workloadStatus/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/filter/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadChart/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadTitle/render.go
modules/cmp/steve/middleware/audit.go

/kind bug
1. fix event unknown lastSeen timestamp
2. fix pod wrong metrics
3. fix audit

fix events list and pod metrics

---

modules/core/openapi-ng/proxy/proxy.go
modules/core/openapi-ng/proxy/proxy_test.go

/kind bug
fix openapi get params bug
| 🇨🇳 中文    |      修复openapi获取参数bug        |

fix openapi get params bug

---

modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/chart/model.go

/kind bugfix
change chart color and style
@johnlanni 

fix: 🐛 change chart color

---

.erda/migrations/qa/20210914-auto-test-plan-execute-api-num.sql
apistructs/testplan_v2.go
go.mod
go.sum
modules/dop/dao/testplan_v2.go
modules/dop/providers/autotest/testplan/testplan.service.go
modules/dop/providers/autotest/testplan/testplan.service_test.go
modules/dop/services/autotest_v2/testplan_v2.go
modules/msp/apm/trace/trace.service.go
modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/table/render.go
modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/table/table_test.go
modules/openapi/component-protocol/scenarios/auto-test-plan-list/protocol.yml
modules/pipeline/aop/plugins/pipeline/testplan_after/plugin.go
modules/pipeline/aop/plugins/pipeline/testplan_after/plugin_test.go
pkg/erda-configs/i18n/notify_item.yml

/kind feature
cherry pick https://github.com/erda-project/erda/pull/1839/files
delete GetSpanDashboards(), it only on master brunch

cherry-pick release/1.3 update execute dingding

---

cmd/monitor/streaming/main.go
conf/monitor/streaming/streaming.yaml
go.mod
modules/core/monitor/log/schema/manager.go
modules/core/monitor/log/storage/consumer.go
modules/core/monitor/log/storage/consumer_test.go
modules/core/monitor/log/storage/monitoring.go
modules/core/monitor/log/storage/provider_test.go

/kind enhancement
1. filter the log whose org_name is invalid
1. https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=202928&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJSRU9QRU4iXSwiYXNzaWduZWVJRHMiOlsiMTAwMDMwMSJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjIsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=506&type=TASK …

filter invalid org's log

---

pkg/erda-configs/i18n/autotest.json

/kind bug
modify autotest permission notify
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=66972&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG) …

modify autotest permission notify

---

conf/cmp/i18n/component-protocol.yaml
modules/cmp/component-protocol/components/cmp-dashboard-nodeDetail/infoDetail/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodeDetail/infoMapTable/model.go
modules/cmp/component-protocol/components/cmp-dashboard-nodeDetail/infoMapTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodeDetail/statusBadge/model.go
modules/cmp/component-protocol/components/cmp-dashboard-nodeDetail/statusBadge/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/chart/model.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/filter/filter.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/table/table.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/table/table_test.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/cpuTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/memTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/nodeFilter/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/podTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/tableTabsContainer/render.go
modules/cmp/component-protocol/scenarios/cmp-dashboard-nodes.yml
modules/cmp/metrics/metrics_test.go

fix some bugs
/kind bugfix
fix search by ip, color, i18n
@johnlanni 

fix: 🐛 cmp dashboard bug

---

conf/monitor/monitor/chartview/service/service_analysis.json
conf/monitor/monitor/chartview/service/translation_analysis_cache.json
conf/monitor/monitor/chartview/service/translation_analysis_http.json
conf/monitor/monitor/chartview/service/translation_analysis_mq.json
conf/monitor/monitor/chartview/service/translation_analysis_rpc.json
conf/monitor/monitor/chartview/span/span_process_analysis_java.json
conf/monitor/monitor/chartview/span/span_process_analysis_nodejs.json
go.mod
go.sum
modules/monitor/apm/topology/routes.go
modules/monitor/apm/topology/topology.go
modules/monitor/apm/topology/topology_test.go
modules/msp/apm/trace/core/common/common.go
modules/msp/apm/trace/core/query/query.go
modules/msp/apm/trace/trace.service.go
modules/msp/apm/trace/trace.service_test.go

Cherry pick of: feature: span analysis#1817

---

modules/core/monitor/metric/query/es-tsql/influxql/functions.go
modules/core/monitor/metric/query/es-tsql/influxql/parse.go

polish: fix function typo

---

.erda/migrations/cmdb/requirements.txt
pkg/database/sqlparser/migrator/migrator.go
pkg/database/sqlparser/pygrator/requirements.go
pkg/database/sqlparser/pygrator/settings.go
pkg/database/sqlparser/pygrator/settings_test.go
pkg/database/sqlparser/snapshot/snapshot.go
pkg/database/sqlparser/snapshot/snapshot_test.go
tools/cli/cmd/migrate_mkpypkg.go

/kind feature
- fix unknow charset error when snapshot the database;
- fixe the problem where the Python mysql client could not connect to mysql8.0

fix unknow charset error; fixe the problem where the Python mysql client could not connect to mysql8.0

---

modules/core/openapi-ng/routes/proto/proto.go

/kind feature
ignore no openapi option

ignore no openapi option

---

go.mod
go.sum

bugfix: openapi fix

---

modules/msp/instance/db/instance_tenant.go
modules/msp/instance/permission/permission.go

bugfix: fix permission

---

go.mod
go.sum

bugfix: Update go mod 1.3

---

conf/monitor/monitor/chartview/cmp/cmp-dashboard-podDetail.json

/kind bug
1. change aggragration of  pod cpu and memory monitor graph from "sum" to "avg"
2. modify pod read/writes bytes graph title and unit

Fix pod monitor graph

---

conf/cmp/i18n/component-protocol.yaml
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/filter/filter.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/table/table.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/table/table_test.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/cpuTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/memTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/podTable/render.go

/kind bugfix
change table title usedRate to unusedRate
@johnlanni 

Component bugfix

---

conf/monitor/monitor/chartview/cmp/cmp-dashboard-podDetail.json

/kind bug
add "%" unit in pod cpu/mem graph
/assign @sfwn 

fix pod monitor graph unit

---

apistructs/pipeline_queue.go
apistructs/pipeline_queue_test.go
modules/pipeline/aop/plugins/pipeline/precheck_before_pop/before_run_check.go
modules/pipeline/aop/plugins/pipeline/precheck_before_pop/before_run_check_test.go
modules/pipeline/aop/plugins/pipeline/precheck_before_pop/plugin.go
modules/pipeline/pipengine/reconciler/queuemanage/queue/range_pending_queue.go

/kind bug
pipeline queue check status is end
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=224114&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG)
| 🇺🇸 English |  pipeline queue check status is end            |
| 🇨🇳 中文    |  pipeline队列增加判断流水线的状态            | …

pipeline queue check status is end

---

conf/monitor/monitor/chartview/report/daily.json
conf/monitor/monitor/chartview/report/weekly.json
conf/monitor/monitor/chartview/span/span_process_analysis_java.json
conf/monitor/monitor/chartview/span/span_process_analysis_nodejs.json
conf/monitor/monitor/i18n/charts.yml
go.mod
modules/core/monitor/dataview/data.view.service.go
modules/core/monitor/dataview/data.view.service_test.go
modules/core/monitor/dataview/provider.go

/kind feature
- system block international 

international fix

---

modules/cmp/steve/aggregator.go
modules/cmp/steve/proxy/cache_store.go
modules/cmp/steve/proxy/proxy_store.go
modules/cmp/steve/schema.go
modules/cmp/steve/server.go

/kind bug
add cluster name in cache key

fix cache cluster conflict

---

modules/pipeline/pipengine/reconciler/taskrun/framework.go
modules/pipeline/pipengine/reconciler/taskrun/task_loop.go
modules/pipeline/pipengine/reconciler/taskrun/task_loop_test.go

/kind bug
A condition is executed, and the task remains stuck when the condition is written incorrectly
erda-issue: [erda-issue](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=223416&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDU2MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG)

a condition is executed, and the task remains stuck when the condition is written incorrectly

---

pkg/erda-configs/permission/backend/sys/org/org.yml

/kind bug
fix: add the list member permission to auditor
https://erda.cloud/erda/dop/projects/387/issues/all?id=224158&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueGantt__urlQuery=eyJ0b3RhbCI6MzQsInBhZ2VObyI6MSwicGFnZVNpemUiOjIwMCwiaXNzdWVWaWV3R3JvdXBWYWx1ZSI6ImdhbnR0IiwiSXNzdWVUeXBlIjoiQUxMIn0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTAwfQ%3D%3D&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG
/assign @sfwn 
| 🇨🇳 中文 …

fix: add the list member and notice permission to auditor

---

apistructs/issue_stream_locale.go
modules/dop/services/issue/issue.go
modules/dop/services/issuestream/issue_stream.go
modules/dop/services/issuestream/issue_stream_template.go
modules/dop/services/issuestream/issue_stream_template_test.go

/kind feature
Polish sending message, different with issue streams.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=224127&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiOTIiXSwiZmluaXNoZWRBdFN0YXJ0RW5kIjpbbnVsbCwxNjMzMDE3NTk5OTk5XX0%3D&issueGantt__urlQuery=eyJ0b3RhbCI6MTksInBhZ2VObyI6MSwicGFnZVNpemUiOjIwMCwiaXNzdWVWaWV3R3JvdXBWYWx1ZSI6ImdhbnR0IiwiSXNzdWVUeXBlIjoiQUxMIn0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=506&type=BUG)
/assign @Effet

feature: issue-stream add template override for better msg sending

---

go.mod
go.sum
modules/msp/credential/credential.service.go
modules/oap/collector/receivers/jaeger/interceptor.go

/kind feature
/kind bug
/kind polish
/kind document

update proto for release/1.3

---

modules/extensions/loghub/index/query/clients.go
modules/extensions/loghub/index/query/clients_test.go
modules/extensions/loghub/index/query/db/log_deployment.go
modules/extensions/loghub/index/query/index.go
modules/extensions/loghub/index/query/index_test.go
modules/extensions/loghub/index/query/log_query.go
modules/extensions/loghub/index/query/log_query_v1.go
modules/extensions/loghub/index/query/log_query_v2.go
modules/extensions/loghub/index/query/provider.go
modules/extensions/loghub/index/query/routes.go

/kind feature
- speed up log-query
- log query support AND OR operator
| 🇺🇸 English |      log query improvement        |
| 🇨🇳 中文    |      日志查询优化        |

feature: log query improvement

---

go.mod
go.sum
modules/dop/providers/autotest/testplan/testplan.service.go
modules/dop/providers/autotest/testplan/testplan.service_test.go
modules/pipeline/aop/plugins/pipeline/testplan_after/plugin.go
modules/pipeline/aop/plugins/pipeline/testplan_after/plugin_test.go

/kind bug
fix: solve the problem of the failure of auto test of Dingding push
https://erda.cloud/erda/dop/projects/387/issues/all?id=222230&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueGantt__urlQuery=eyJ0b3RhbCI6MzQsInBhZ2VObyI6MSwicGFnZVNpemUiOjIwMCwiaXNzdWVWaWV3R3JvdXBWYWx1ZSI6ImdhbnR0IiwiSXNzdWVUeXBlIjoiQUxMIn0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTAwfQ%3D%3D&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG
/assign @sfwn 
| 🇺🇸 English | …

fix: solve the problem of the failure of auto test of Dingding push

---

go.mod
go.sum
modules/oap/collector/receivers/jaeger/interceptor.go

/kind feature
/kind bug
/kind polish
/kind document

update proto for master

---

go.mod
go.sum
modules/msp/credential/credential.service.go
modules/oap/collector/receivers/jaeger/interceptor.go

/kind feature
change traceID & spanID to string
change traceID & spanID to string

change traceID & spanID to string

---

quick-start/quick-start.sh

/kind feature
check docker version before execute quick-start install

optimize: check docker_version

---

conf/monitor/monitor/chartview/service/process_analysis_java.json
conf/monitor/monitor/chartview/service/process_analysis_nodejs.json
conf/monitor/monitor/chartview/span/span_process_analysis_java.json
conf/monitor/monitor/chartview/span/span_process_analysis_nodejs.json

/kind bug
/assign @recallsong @liuhaoyang

bugfix:Fix disk no data

---

modules/dop/component-protocol/components/issue-manage/issueFilter/model.go

/kind feature
add icon for group status (in issue filter)
/assign @sfwn 

add icon for group status (in issue filter)

---

modules/cmp/component-protocol/components/cmp-dashboard-pods/common/model.go
modules/cmp/component-protocol/components/cmp-dashboard-pods/podsTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadChart/render.go
modules/cmp/component-protocol/cputil/util.go
modules/cmp/component-protocol/cputil/util_test.go

/kind bug
change pod status color steelBlue to steelblue

change steelBlue to steelblue

---

pkg/database/sqlparser/migrator/db.go
pkg/database/sqlparser/migrator/parameters.go
pkg/database/sqlparser/migrator/parameters_test.go
quick-start/docker-compose.yml

/kind feature
- fix msyql dsn pattern for when the password is empty
- fix log
- update quick-start erda-migration image

fix msyql dsn pattern for when the password is empty

---

.erda/migrations/core-services/20210917-update-system-notice.sql

/kind feature
fix: add system-notice-update migration
https://erda.cloud/erda/dop/projects/387/issues/all?id=226430&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG
/assign @sfwn  …

fix: add system-notice-update migration

---

modules/dop/component-protocol/components/issue-manage/issueFilter/model_test.go

/kind bug
fix ut error of issue-filter
/assign @sfwn 

fix ut error of issue-filter

---

conf/msp/msp.yaml

modify ak file path

---

apistructs/issue.go
apistructs/issue_test.go
modules/dop/initialize.go
modules/dop/services/issue/convert.go
modules/dop/services/issue/import.go
modules/dop/services/issue/issue.go
pkg/erda-configs/i18n/issue.json

/kind feature
update issues when import id
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=224372&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDYsNTQxXSwic3RhdGVCZWxvbmdzIjpbIk9QRU4iLCJXT1JLSU5HIiwiV09OVEZJWCIsIlJFT1BFTiJdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjA1Il19&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=TASK) …

update issues when import id

---

modules/scheduler/executor/plugins/edas/edas.go
modules/scheduler/impl/cluster/hook.go

/kind bug
- fix(edas): use specified registry url
| 🇺🇸 English | fix(edas): use specified registry url  |
| 🇨🇳 中文    | 修复指定 registry 式取值错误的问题|

fix(edas): use specified registry url

---

conf/monitor/monitor/chartview/cmp/cmp-dashboard-nodeDetail.json
conf/monitor/monitor/chartview/cmp/cmp-dashboard-podDetail.json

/kind feature
/kind bugfix
change chart view
@johnlanni 

fix: 🐛 change chart view

---

modules/scheduler/executor/plugins/k8s/instanceinfosync/pod.go

/kind bug
- fix(instancesync): select the container of pod correctly
| 🇺🇸 English | fix(instancesync): select the container of pod correctly             |
| 🇨🇳 中文    |  修复 instance sync 时没有选择正确容器的问题            |

fix(instancesync): select the container of pod correctly

---

modules/msp/apm/adapter/adapter.service_test.go
tools/gotools/go-test-sum/main.go

/kind bug
fix test sum
/assign @hoozecn 

fix test sum

---

modules/dop/providers/autotest/testplan/testplan.service.go
modules/dop/providers/autotest/testplan/testplan.service_test.go

/kind bug
fix: solve the unmodified data caused by the failure of DingTalk push
https://erda.cloud/erda/dop/projects/387/issues/all?id=226651&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG
/assign @sfwn  …

fix: solve the unmodified data caused by the failure of DingTalk push

---

modules/oap/collector/authentication/provider.go
modules/oap/collector/authentication/validator.go
modules/oap/collector/receivers/common/constants.go
modules/oap/collector/receivers/common/interceptors.go
modules/oap/collector/receivers/jaeger/interceptor.go
modules/oap/collector/receivers/jaeger/provider.go

/kind feature
Modify Jaeger trace authentication from accessKey to token
| 🇺🇸 English |      Modify Jaeger trace authentication from accessKey to token        |
| 🇨🇳 中文    |        修改jaeger数据认证方式为token机制      |

Modify Jaeger trace authentication from accessKey to token

---

modules/oap/collector/receivers/jaeger/interceptor.go

bugfix:  assign spanid to parent spanid

---

.erda/migrations/cmdb/20210528-cmdb-base.sql
.erda/migrations/cmdb/20210610-addIssueSubscriber.sql
.erda/migrations/dicehub/20210528-dicehub-base.sql
.erda/migrations/hepa/20210528-hepa-base.sql
.erda/migrations/orchestrator/20210528-orchestrator-base.sql
.erda/migrations/scheduler/20210528-scheduler-base.sql
.erda/migrations/scheduler/20210729-scheduler-index-update.sql

/kind feature
fix index too long on mysql 5.6: add `ROW_FORMAT=DYNAMIC` to CreateTableStmt
document reference: https://dev.mysql.com/doc/refman/5.6/en/innodb-row-format.html
verified:
related pr: https://github.com/erda-project/erda-actions/pull/208 …

feature: fix index too long on mysql 5.6

---

modules/oap/collector/receivers/common/constants.go
modules/oap/collector/receivers/common/interceptors.go

/kind feature
/kind bug
/kind polish
/kind document

set service_instance_ip from jaeger ip tag

---

modules/monitor/monitoring/log_storage.go
modules/monitor/monitoring/log_storage_test.go

/kind feature
/kind bug
/kind polish
/kind document
bugfix

remove uninitiliazed logger

---

modules/dop/services/issue/convert.go
pkg/erda-configs/i18n/issue.json

/kind feature
issue export add estimate time column

issue export add estimate time column

---

modules/monitor/apm/topology/topology.go

feature: service id for topology node

---

modules/dop/component-protocol/components/issue-manage/issueTable/render.go

/kind feature
add a second row of issue table, and at most 5 tag in second row.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/bug?id=223258&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJSRU9QRU4iXSwibGFiZWxJRHMiOlsxNDUzXSwiYXNzaWduZWVJRHMiOlsiNTUiLCI5MiIsIjEwMDA1NjAiLCIxMDAxMjYxIiwiMTAwMTA3MyIsIjEwMDEyMDUiXX0%3D&issueGantt__urlQuery=eyJ0b3RhbCI6MjYsInBhZ2VObyI6MSwicGFnZVNpemUiOjIwMCwiaXNzdWVWaWV3R3JvdXBWYWx1ZSI6ImdhbnR0IiwiSXNzdWVUeXBlIjoiQlVHIn0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=506&type=BUG)
/assign @sfwn 
| 🇺🇸 …

add a second row of issue table

---

apistructs/ingress.go

/kind bug
fix the bug of create component ingress failed.

fix struct json marshal fields

---

modules/dop/services/assetsvc/create.go
modules/dop/services/assetsvc/create_test.go
modules/dop/services/assetsvc/msg.go

/kind bug
fix error link in site msg

fix: error link in site msg

---

conf/cmp/cmp.yaml
conf/cmp/i18n/component-protocol.yaml
conf/monitor/monitor/chartview/cmp/cmp-dashboard-nodeDetail.json
modules/cmp/component-protocol/components/cmp-dashboard-nodes/batchOperationTipModal/model.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/batchOperationTipModal/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/cleanData/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/model.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/table/table.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/cpuTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/memTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/podTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/scenario.go
modules/cmp/component-protocol/scenarios/cmp-dashboard-nodes.yml
modules/cmp/steve/proxy/cache_store.go

/kind bugfix
add secondary confirm
@johnlanni 

fix: 🐛 add reconfirm component

---

conf/monitor/monitor/chartview/service/services.json

bugfix: services dashboard i18n bug

---

modules/oap/collector/receivers/common/constants.go
modules/oap/collector/receivers/common/interceptors.go

/kind feature
| 🇺🇸 English |       Rewrite http_url to http_path       |
| 🇨🇳 中文    |         重写http.url tag 为 http.path     |

Rewrite http_url to http_path

---

erda.yml

/kind bug
specify cmp addr
| 🇺🇸 English |   specify cmp addr           |
| 🇨🇳 中文    |   cmp指定自身地址注册到eventbox           |

specify cmp addr

---

conf/cmp/i18n/component-protocol.yaml
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/table/table.go

/kind bugfix
fix translate
@johnlanni 

fix: 🐛 i18n

---

modules/cmp/component-protocol/components/cmp-dashboard-pods/podsTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/podsTable/render.go
modules/cmp/steve/proxy/cache_store.go
modules/cmp/steve/response.go
modules/cmp/steve_request.go

/kind bug
1. fix cronjob detail has all pods in same namespace
2. add debug logs

fix cronjob detail

---

modules/cmp/provider.go
modules/hepa/k8s/k8s_adapter.go
modules/hepa/k8s/k8s_adapter_test.go

/kind bug
remove the delay of ingress creation

remove the delay of ingress creation

---

modules/cmp/component-protocol/components/cmp-dashboard-pods/podsTable/render.go

/kind polish
add debug for get metrics

add get metrics log

---

modules/msp/menu/menu.service.go

/kind bug
| 🇺🇸 English |      fix the bug of release/1.3 AppMonitor menu Incomplete        |
| 🇨🇳 中文    |       应用监控下的菜单不完整       |

fix the bug of release/1.3 AppMonitor menu Incomplete

---

go.mod
pkg/database/sqlparser/ddlreverser/reverser.go
pkg/database/sqlparser/migrator/schema.go
pkg/database/sqlparser/migrator/service.go
pkg/database/sqlparser/snapshot/snapshot.go
pkg/database/sqlparser/snapshot/snapshot_test.go

/kind feature
feature: trim Character Set from raw CreateTableStmt

feature: trim Character Set from raw CreateTableStmt

---

modules/dop/providers/autotest/testplan/testplan.service.go
modules/dop/providers/autotest/testplan/testplan.service_test.go

/kind bug
fix: solve the problem of incorrect time
https://erda.cloud/erda/dop/projects/387/issues/all?id=227587&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMTI2MSJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG
/assign @sfwn  …

fix: solve the problem of incorrect time

---

conf/msp/instrumentationlibrary/config.yaml
conf/msp/instrumentationlibrary/instrumentationlibrary.yaml
conf/msp/instrumentationlibrary/jaeger-template.yaml
conf/msp/msp.yaml
modules/msp/apm/adapter/adapter.service.go
modules/msp/apm/adapter/adapter.service_test.go
modules/msp/apm/adapter/model.go
modules/msp/apm/adapter/provider.go

/kind feature
/kind bug
/kind polish
/kind document

Refactor instrumentationlibrary config

---

conf/msp/instrumentationlibrary/config.yaml
conf/msp/instrumentationlibrary/instrumentationlibrary.yaml
conf/msp/instrumentationlibrary/jaeger-template.yaml
conf/msp/msp.yaml
modules/msp/apm/adapter/adapter.service.go
modules/msp/apm/adapter/adapter.service_test.go
modules/msp/apm/adapter/model.go
modules/msp/apm/adapter/provider.go

cherry-pick: Refactor instrumentationlibrary config

---

pkg/erda-configs/i18n/autotest.json
pkg/expression/expression_reconcile.go
pkg/mock/mock.go
pkg/mock/mock_test.go

/kind feature
automated testing adds fixed-length integer random values, users can specify the value of length as needed
erda-issue: [erda-issue](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=229092&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDU2MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=-1&type=TASK)

random int with length

---

go.mod
go.sum
modules/cmp/steve/middleware/audit.go
modules/cmp/steve/middleware/dispatcher.go
modules/cmp/steve/middleware/dispatcher_test.go

/kind bugfix
fix console cursor move bug
@johnlanni 

fix: 🐛 audit console

---

modules/cmp/conf/conf.go
modules/cmp/impl/org-resource/org_resource.go
modules/cmp/initialize.go
modules/core-services/dao/migration.go
modules/core-services/services/user/user.go
modules/gittar/initialize.go
modules/gittar/uc/user_center.go
pkg/ucauth/identity_paging.go
pkg/ucauth/identity_paging_test.go
pkg/ucauth/kratos.go
pkg/ucauth/user_admin.go
pkg/ucauth/user_admin_test.go

bug
Find users by id compatible with user ids, remove unused uc client
/assign @Effet  @sfwn 

Find users by id compatible with user ids

---

go.mod
modules/oap/collector/receivers/common/constants.go
modules/oap/collector/receivers/common/interceptors.go

/kind feature
/kind bug
/kind polish
/kind document

Convert client.uuid to service.instance.id

---

modules/cmp/component-protocol/components/cmp-dashboard-events-list/eventTable/model.go
modules/cmp/component-protocol/components/cmp-dashboard-events-list/eventTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-podDetail/containerTable/model.go
modules/cmp/component-protocol/components/cmp-dashboard-podDetail/containerTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-podDetail/eventTable/model.go
modules/cmp/component-protocol/components/cmp-dashboard-podDetail/eventTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-pods/podsTable/model.go
modules/cmp/component-protocol/components/cmp-dashboard-pods/podsTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/podsTable/model.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/podsTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadTable/model.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadTable/render.go

/kind polish
add sortDirections for all tables in cmp cp

add sortDirections

---

modules/core/monitor/log/query/provider_test.go
modules/core/monitor/log/query/query.go
modules/core/monitor/log/query/query_test.go
modules/core/monitor/log/query/routes.go

/kind bug
code from release/1.2

migrate from release/1.2

---

.erda/migrations/hepa/20210927-hepa-optimize-runtime.sql
modules/hepa/services/runtime_service/impl/impl.go

/kind feature
optimize hepa runtime service api latency.

optimize runtime service api latency

---

modules/scheduler/executor/plugins/edas/edas.go

/kind bug
- update edas deploy application log when app scale
| 🇺🇸 English |   update edas deploy application log when app scale           |
| 🇨🇳 中文    |     更新 edas 应用扩缩容部署时的日志         |

update edas deploy application log when app scale

---

conf/monitor/monitor/chartview/cmp/cmp-dashboard-nodeDetail.json
conf/monitor/monitor/chartview/cmp/cmp-dashboard-podDetail.json
go.sum
modules/openapi/api/apis/openapi/component_protocol/notspec_response.go

/kind bug
1. get state rather than globalState in resp
2. add "show": true in graph

fix: userIDs disappear in resp

---

apistructs/cmp.go
modules/cmp/impl/clusters/offline_edge_cluster.go
modules/cmp/impl/clusters/offline_test.go

/kind feature
| 🇺🇸 English |    cluster force offline   |
| 🇨🇳 中文    |     集群强制下线，有些集群客户直接关闭了或者项目资源脏数据清理不干净，需要强制下线   |

cluster force offline

---

modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/table/table.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/podTable/render.go

/kind bugfix
fix translation of pod usage
@johnlanni 

fix: 🐛 translation of pod usage

---

modules/msp/resource/utils/nacos_client.go

/kind bug
nacos v.1.1 login api response with bearer token which should be supported.

bugfix: compatible with nacos v1.1

---

conf/dop/i18n/component-protocol.yaml
modules/dop/component-protocol/components/issue-manage/issueFilter/model.go
modules/dop/component-protocol/components/issue-manage/issueFilter/model_test.go
modules/openapi/component-protocol/components/filter/filter.go

/kind feature
add placeholder for issue filter saving
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/bug?id=228877&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiNTUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=506&type=BUG)
/assign @sfwn 

add placeholder for issue filter saving

---

apistructs/autotest_scene.go
modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeTaskTable/render.go
modules/openapi/component-protocol/scenarios/auto-test-scenes/components/addCustomScriptButton/render.go
modules/openapi/component-protocol/scenarios/auto-test-scenes/components/customScriptDrawer/render.go
modules/openapi/component-protocol/scenarios/auto-test-scenes/components/customScriptForm/render.go
modules/openapi/component-protocol/scenarios/auto-test-scenes/components/executeTaskTable/render.go
modules/openapi/component-protocol/scenarios/auto-test-scenes/components/executeTaskTable/transform_test.go
modules/openapi/component-protocol/scenarios/auto-test-scenes/components/stages/model.go
modules/openapi/component-protocol/scenarios/auto-test-scenes/components/stages/render.go
modules/openapi/component-protocol/scenarios/auto-test-scenes/components/stages/stages.go
modules/openapi/component-protocol/scenarios/auto-test-scenes/protocol.yml

/kind feature
autotest step add custom-script type
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=223155&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=TASK)
| 🇺🇸 English |  autotest step add custom-script type            |
| 🇨🇳 中文    | 自动化步骤支持自定义脚本的执行             | …

autotest step add custom-script type

---

erda.yml

/kind polish
Change default replicas of dop, gittar, orchestrator
/assign @sfwn 

Change default replicas of dop, gittar, orchestrator

---

modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeTaskTable/render.go
modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeTaskTable/render_test.go
modules/openapi/component-protocol/scenarios/auto-test-scenes/components/addWaitButton/render.go
modules/openapi/component-protocol/scenarios/auto-test-scenes/components/executeTaskTable/render.go
modules/openapi/component-protocol/scenarios/auto-test-scenes/components/executeTaskTable/transform_test.go

/kind bug
compatible the old wait time name

compatible the old wait time name

---

apistructs/pipeline_report_basic.go
modules/pipeline/aop/plugins/pipeline/basic/plugin.go

/kind feature
We need more info when use report to analyze directly.

feature: pipeline basic report add more fields

---

conf/msp/instrumentationlibrary/instrumentationlibrary.yaml
conf/msp/instrumentationlibrary/jaeger-template.yaml

/kind feature
/kind bug
/kind polish
/kind document

Add jaeger nodejs config

---

modules/hepa/provider.go

feature: fix metrics error

---

modules/pipeline/pipengine/actionexecutor/plugins/apitest/apitest.go

/kind bug
Fix the problem of inaccurate execution time of automatic test

Fix the problem of inaccurate execution time of automatic test

---

conf/monitor/monitor/chartview/cmp/cmp-dashboard-podDetail.json
modules/cmp/component-protocol/components/cmp-dashboard-events-list/eventTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-events-list/filter/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/podsTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/filter/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadTitle/render.go
modules/cmp/component-protocol/cputil/util.go
modules/cmp/steve/aggregator.go
modules/cmp/steve_request.go

/kind bug
1. fix total number disappered in workloads list
2. convert error to apierror
3. add query in workload detail to pod detail link
/assign @sfwn 

fix workload list; convert error

---

bundle/pipeline.go
modules/openapi/component-protocol/pkg/autotest/step/output.go
modules/openapi/component-protocol/pkg/autotest/step/output_test.go
modules/openapi/component-protocol/scenarios/auto-test-scenes/components/apiEditor/apiEditor.go
modules/openapi/component-protocol/scenarios/auto-test-scenes/components/apiEditor/helper.go
modules/openapi/component-protocol/scenarios/auto-test-scenes/components/apiEditor/helper_test.go
modules/openapi/component-protocol/scenarios/auto-test-scenes/components/apiEditor/render.go
modules/openapi/component-protocol/scenarios/auto-test-scenes/components/outPutForm/outPutForm.go
pkg/expression/expression_reconcile.go
pkg/expression/expression_reconcile_test.go

/kind feature
automated test configuration single out parameter reference
erda-issue: [erda-issue](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=229777&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDU2MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=467&type=REQUIREMENT)

automatic test configuration doc output reference

---

go.mod
go.sum
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/table/table.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/cpuTable/render.go

/kind bugfix
fix uncordon disabled
@sfwn 

fix: 🐛 fix uncordon disabled

---

modules/msp/tenant/project/project.service.go
modules/msp/tenant/project/project.service_test.go

feature: no display project without workspace

---

modules/cmp/component-protocol/components/cmp-dashboard-nodes/batchOperationTipModal/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/table/table.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/cpuTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/memTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/podTable/render.go
modules/cmp/component-protocol/scenarios/cmp-dashboard-nodes.yml

/kind bugfix
fix uncordon disabled
@sfwn 

fix: 🐛 no data in table when first step of batch operation

---

modules/cmp/metrics/metrics.go

/kind feature
make an queuesto control concurrency

feature: set query queue

---

modules/cmp/metrics/metrics.go

/kind feature
fix channel leak

fix: channel leak

---

modules/cmp/metrics/metrics.go

/kind feature
make an queue to control concurency

make an queue to control concurency

---

CHANGELOG/CHANGELOG-1.x.md

/kind document
/assign @hoozecn @liuhaoyang

doc: add v1.3 changelog

---

.erda/migrations/cmdb/20210930-issue-filter-enlarge.sql

/kind bug
enlarge issue filter bookmark
/assign @sfwn 

enlarge issue filter bookmark

---

modules/pipeline/dbclient/op_pipeline.go
modules/pipeline/dbclient/op_pipeline_test.go
modules/pipeline/pipengine/reconciler/reconcile.go
modules/pipeline/pipengine/reconciler/reconcile_data_process.go

/kind bugfix
hotfix: reconciler goroutine leak
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=228183&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjkyIl19&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG)
/assign @Effet @kakj-go @chengjoey 

hotfix: reconciler goroutine leak

---

modules/dop/component-protocol/components/issue-manage/issueTable/render.go
modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/envGlobalTable/render.go
modules/openapi/component-protocol/scenarios/auto-test-plan-list/protocol.yml

/kind bug
fix: adjust the style of the table
https://erda.cloud/erda/dop/projects/387/issues/all?id=231307&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG
/assign #sfwn  …

fix: adjust the style of the table

---

modules/cmp/component-protocol/components/cmp-dashboard-events-list/eventTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-events-list/filter/render.go
modules/cmp/steve/aggregator.go
modules/cmp/steve/middleware/auth.go
modules/cmp/steve/predefined_resource.go
modules/cmp/steve_request.go

/kind feature
support erda ops in dashboard

add erda ops role in dashboard

---

modules/dop/dao/issue.go

bug
Filter issues by types in home page content

Filter issues by types in home page content

---

modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/table/render.go

bug
Fix pageNo in auto test plan list table

Fix pageNo in auto test plan list table

---

modules/cmp/cache/cache.go
modules/cmp/metrics/metrics.go

/kind bugfix
cache exceed, query metrics with time limit
/assign @sfwn 

fix: 🐛 cache exceed, query metrics with time limit

---

modules/openapi/component-protocol/scenarios/home-page-sidebar/protocol.yml

bug
Fix home page sidebar scroll property

Fix home page sidebar scroll property

---

modules/msp/apm/notifygroup/notifygroup.service.go
modules/msp/apm/notifygroup/provider.go
modules/msp/member/mebmer.service.go
modules/msp/member/mebmer.service_test.go
modules/msp/member/provider.go

/kind bug
| 🇺🇸 English |      fix the bug of old project can not find project by scopeId        |
| 🇨🇳 中文    |      老项目无法通过scopeId找到project        |

fix the bug of old project can not find project by scopeId

---

conf/monitor/monitor/monitor.yaml
conf/monitor/streaming/streaming.yaml
modules/monitor/monitoring/metric_storage.go
modules/monitor/monitoring/metric_storage_test.go
modules/monitor/monitoring/provider.go

/kind bug
invoid too much pressure to ES

[hotfix]split huge query to small query

---

erda.yml
modules/cmp/metrics/metrics.go

/kind feature
reduce the time duration for agg.

update metrics acquire sqls

---

modules/pipeline/pipengine/engine.go

/kind bug
fix pipeline initiailize load running time interval

fix load running time

---

conf/monitor/monitor/chartview/trace/trace_count.json

bugfix: trace count fix

---

modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/table/table.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/cpuTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/memTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/podTable/render.go
modules/cmp/metrics/metrics.go

/kind refactor
request nodes list asynchronized

refactor: 💡 request nodes list asynchronized

---

go.mod
go.sum
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/podsTable/render.go
modules/scheduler/executor/plugins/k8s/check_quota.go
modules/scheduler/executor/plugins/k8s/check_quota_test.go

/kind bug
fix: round value in scheduler log

fix: round value in scheduler log

---

modules/cmp/component-protocol/components/cmp-dashboard-events-list/eventTable/render.go
modules/core-services/services/project/project.go
pkg/resourcecalculator/calculator.go

/kind bug
1. Add clusterName in update project quota audit
2. Fix memory quota audit error

fix: add clusterName in update project quota audit

---

modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/podsTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadChart/model.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadChart/render.go
modules/cmp/component-protocol/cputil/util.go
modules/cmp/steve_request.go

/kind bug
1. Fix: steve request poniter changed in goroutine
2. Context canceled in goroutine
3. Remove label in workload chart
4. Remove gird in workload chart

fix: steve request poniter changed in goroutine

---

modules/dop/component-protocol/components/test-dashboard/at_api_chart_group/at_api_avg_cost_chart/render.go
modules/dop/component-protocol/components/test-dashboard/at_api_chart_group/at_api_rate_failed_chart/render.go
modules/dop/component-protocol/components/test-dashboard/at_plan_latest_waterfall_chart_group/chart/model.go
modules/dop/component-protocol/components/test-dashboard/common/barchart.go
modules/dop/component-protocol/components/test-dashboard/scene_chart_group/scene_avg_cost_chart/render.go
modules/dop/component-protocol/components/test-dashboard/scene_chart_group/scene_rate_failed_chart/render.go
modules/dop/component-protocol/components/test-dashboard/scene_chart_group/scene_rate_passed_chart/render.go

/kind polish
fix: update the style to test dashboard
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=240510&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=541&type=BUG)
- - [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=240455&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDM …

fix: update the style to test dashboard

---

apistructs/org.go
modules/core-services/endpoints/organization.go
modules/core-services/services/org/org.go
modules/core-services/services/org/org_test.go
modules/openapi/api/apis/dop/cmdb_orgs_update.go
pkg/erda-configs/audit/template.json

/kind bug
fix: modify the audit message for org update
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=218107&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=541&type=BUG)
/assign @
> For …

fix: modify the audit message for org update

---

erda.yml

/kind bug
fix: update replicas to 1 for gittar, because of libgit2 may occur error  under multiple instances
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=241194&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=541&type=BUG)
/assign @sfwn 
/cherry-pick …

fix: update replicas to 1 for gittar

---

modules/core/monitor/entity/persist/provider.go
modules/core/monitor/log/storage/elasticsearch/iterator.go
modules/core/monitor/metric/persist/provider.go
modules/core/monitor/storekit/elasticsearch/iterator.go

/kind polish
elasticsearch common iterator

elasticsearch common iterator

---

modules/cmp/steve/middleware/audit.go
modules/cmp/steve/middleware/dispatcher.go
modules/cmp/steve/middleware/dispatcher_test.go

/kind feature
support reverse search in audit and send audit cmd with buffer

feat: 🎸 audit cmd with buffer

---

apistructs/cicd.go
apistructs/cicd_test.go
apistructs/pipeline.go
modules/dop/endpoints/pipeline.go
modules/pipeline/dbclient/op_pipeline.go

/kind polish
UI standard use pageNo unifiedly.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=223234&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyI5MiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=541&type=TASK) …

pagingRequest use pageNo unifiedly

---

modules/dop/component-protocol/components/test-dashboard/overview_group/quality_chart/render.go
modules/dop/component-protocol/components/test-dashboard/overview_group/quality_chart/render_test.go

/kind bugfix
fix: test-dashboard correct cacl logic of bug-reopen-score

fix: test-dashboard correct cacl logic of bug-reopen-score

---

conf/cmp/i18n/component-protocol.yaml
modules/cmp/component-protocol/components/cmp-dashboard-podDetail/operationButton/model.go
modules/cmp/component-protocol/components/cmp-dashboard-podDetail/operationButton/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/operationButton/model.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/operationButton/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/podsTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/filter/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadTable/render.go
modules/cmp/steve_request.go

/kind bug
1. Add success message in deletion options
2. Fix: remove cache failed

bugfix/fix: remove cache failed

---

modules/msp/apm/checker/plugins/http/provider.go

bugfix: record latency when http response status is ok

---

modules/cmp/component-protocol/components/cmp-dashboard-events-list/eventTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/restartButton/model.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/restartButton/render.go

/kind bug
fix: restart confirm window out of display range

fix: restart confirm window out of display range

---

modules/core/monitor/metric/storage/elasticsearch/provider.go
modules/core/monitor/metric/storage/elasticsearch/provider_test.go

/kind feature
/kind bug
/kind polish
/kind document
fix es matching error
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=240221&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJSRU9QRU4iXSwic3RhdGVzIjpbNDQwMiw3MTA0LDcxMDUsNDQwMyw0NDA0LDcxMDYsNDQwNiw0NDA3LDQ0MTIsNDUzOCw0NDEzLDQ0MTQsNDQxNSw0NDE2XSwiYXNzaWduZWVJRHMiOlsiMTAwMDMwMSJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=541&type=TASK)
Add comment …

fix es matching error

---

conf/dop/i18n/component-protocol.yaml
modules/dop/component-protocol/components/test-dashboard/overview_group/quality_chart/render.go
modules/dop/component-protocol/components/test-dashboard/overview_group/quality_chart/tip.go
modules/dop/component-protocol/components/test-dashboard/overview_group/quality_chart/tip_test.go

/kind feature
test-dashboard: add tip for quality radar
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=240772&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyI5MiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=541&type=TASK) …

test-dashboard: add tip for quality radar

---

apistructs/audits.go
modules/core-services/services/org/org.go
modules/core-services/services/org/org_test.go
modules/openapi/api/apis/dop/cmdb_orgs_update.go

/kind polish
fix: update org update audit
fix: update org update audit
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=241234&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=541&type=BUG)
Add comment like `/cherry-pick release/1.0` …

fix: update org update audit

---

conf/core-services/i18n/cs-i18n.yml
modules/core-services/services/notify/channel/notify.chanel.service.go
pkg/common/apis/response.go
pkg/common/errors/warn.go

polish: frontend note

---

modules/cmp/component-protocol/components/cmp-dashboard-events-list/eventTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/restartButton/render.go

/kind bug
Restart daemonset by daemonset client rather than statefulSet client

fix: restart daemonset failed

---

conf/monitor/monitor/monitor.yaml
modules/core/monitor/log/query/log.query.service.go
modules/core/monitor/log/query/routes.go
modules/core/monitor/log/storage/elasticsearch/iterator.go
modules/core/monitor/settings/settings.service.go

/kind bug
fix query logs and ttl bug

fix query logs and ttl bug

---

conf/monitor/monitor/chartview/service/translation_analysis_database.json

polish: rm the column width of call count 

---

modules/core-services/dao/project.go
modules/core-services/model/project.go
modules/core-services/services/project/project.go
modules/core-services/services/project/project_test.go
pkg/resourcecalculator/calculator.go
pkg/resourcecalculator/calculator_test.go

/kind bug
- fix: CoreToMillCore error; 
- fix: cluster_config error; 
- fix: rollback_config error

fix: CoreToMillCore error; fix: cluster_config error; fix: rollback_config error

---

bundle/quota.go
modules/cmp/resource/class.go
modules/cmp/resource/report_table.go
modules/cmp/resource/summary.go
modules/cmp/tasks/collect_daily_quota.go
modules/cmp/tasks/ticker.go

/kind bug
fix: resource overview i18n error

fix: resource overview i18n error

---

conf/core-services/i18n/i18n.yaml

/kind bug
feature: modify the error document

feature: modify the error document

---

modules/core/monitor/dataview/data.view.service.go
modules/core/monitor/dataview/data.view.service_test.go

/kind bug
fix dataview update time

fix dataview update time

---

modules/msp/apm/trace/trace.service.go
modules/msp/apm/trace/trace.service_test.go

bugfix: trace depth

---

conf/monitor/monitor/chartview/trace/trace_count.json

bugfix: bar -> line

---

conf/monitor/streaming/event_index_template.json

/kind bug
fix event index template, event_id、name、kind got wrong mapping

bugfix: fix event index template

---

modules/cmp/component-protocol/components/cmp-dashboard-nodes/nodeFilter/render.go

/kind feature
/kind bugfix
node filter translation

fix: 🐛 node filter translation

---

.github/PULL_REQUEST_TEMPLATE.md

/kind document
polish: pr template add kind refactor&bugfix, remove bug

polish: pr template add kind refactor&bugfix, remove bug

---

modules/dop/component-protocol/components/test-dashboard/at_plan_latest_waterfall_chart_group/chart/model.go
modules/dop/component-protocol/components/test-dashboard/mt_plan_chart_group/chart/render.go

/kind polish
polish test dashboard chart:
- use empty string for `0` number in chart
- use pureChart prop
/assign @Effet

polish test dashboard chart

---

modules/cmp/cluster_resource.go
modules/cmp/component-protocol/components/cmp-dashboard-events-list/eventTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-nodes/charts/render.go

/kind bugfix
fix: ignore virtual node when calculate resource

fix: ignore virtual node when calculate resource

---

modules/core/monitor/metric/query/metricq/metricq.go
modules/core/monitor/metric/query/metricq/provider.go
modules/monitor/apm/topology/topology.go
modules/monitor/apm/topology/topology_test.go

polish: duration unit for trace query

---

modules/cmp/component-protocol/components/cmp-dashboard-nodes/batchOperationTipModal/render.go
modules/cmp/steve/handler.go
modules/cmp/steve/parse.go
modules/cmp/steve/parse_test.go
modules/cmp/steve_request.go

/kind polish
fix: error message is not clear when permissin denied

fix: error message is not clear when permissin denied

---

modules/core/openapi-ng/interceptors/user-info/user_info.go
modules/core/openapi-ng/interceptors/user-info/user_info_test.go
modules/openapi/api/apis/openapi/component_protocol/notspec_response.go
modules/openapi/api/apis/openapi/component_protocol/render.go
modules/openapi/proxy/http/http.go
pkg/http/httputil/header.go

bug
Fix user info interceptor desensitized, remove duplicate query
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=239301&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMDczIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=541&type=BUG)
/assign @sfwn @Effet  …

Fix user info interceptor desensitized, remove duplicate query

---

modules/cmp/resource/report_table.go
modules/cmp/tasks/collect_daily_quota.go

/kind feature
fix: missing cpuRequest and memRequest in shared resource data

fix: missing cpuRequest and memRequest in shared resource data

---

modules/cmp/impl/clusters/import_cluster.go

/kind feature
import cluster with enabled workspace scheduler
| 🇺🇸 English | import cluster with enabled workspace scheduler             |
| 🇨🇳 中文    |  导入集群默认开启 workspace 调度            |

feature: schesuler workspace switch 1.3

---

apistructs/workbench.go
conf/dop/i18n/component-protocol.yaml
modules/dop/component-protocol/components/test-dashboard/overview_group/quality_chart/render.go
modules/dop/component-protocol/components/test-dashboard/overview_group/quality_chart/render_test.go
modules/dop/component-protocol/components/test-dashboard/overview_group/quality_chart/tip.go
modules/dop/dao/issue.go

/kind feature
test-dashboard:
- radar bug score only calc unclosed bugs
- fix i18n of code-coverage score formula
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=242723&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyI5MiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=541&type=TASK)
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUT …

feature: test-dashboard radar bug score only calc unclosed bugs

---

modules/extensions/loghub/exporter/output.go
modules/extensions/loghub/exporter/output_test.go

/kind feature
optimize: do not check log.Labels, this fields seems useless now.

optimize: do not check log.Labels

---

modules/msp/apm/trace/storage/consumer.go

/kind bugfix
use json number to decode span

use json number to decode span

---

go.mod
go.sum
modules/cmp/component-protocol/components/cmp-dashboard-events-list/eventTable/render.go
modules/cmp/component-protocol/components/cmp-dashboard-events-list/filter/render.go
modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/podsTable/render.go
modules/cmp/initialize.go
modules/cmp/steve/config.go
modules/cmp/steve/factory.go
modules/cmp/steve/proxy/proxy_store.go
modules/cmp/steve/schema.go
modules/cmp/steve/server.go

/kind feature
1. Support k8s 1.13
2. Add klog -v=8 by debug env
| 🇺🇸 English | k8s dashboard support k8s version < 1.16 |
| 🇨🇳 中文    | k8s 集群管理功能支持小于 1.16 版本的k8s |
Need cherry-pick to release/1.3

k8s dashboard support k8s version < 1.16

---

modules/core/openapi-ng/interceptors/user-info/user_info.go
modules/core/openapi-ng/interceptors/user-info/user_info_test.go

bugfix
Fix user info retriever, update unit test
/assign @sfwn 

Fix user info retriever, update unit test

---

conf/dop/dop.yaml
conf/dop/i18n/component-protocol.yaml
modules/dop/component-protocol/components/code-coverage/cancelButton/render.go
modules/dop/component-protocol/components/code-coverage/codeCoverChart/render.go
modules/dop/component-protocol/components/code-coverage/configButton/render.go
modules/dop/component-protocol/components/code-coverage/configForm/render.go
modules/dop/component-protocol/components/code-coverage/configModal/render.go
modules/dop/component-protocol/components/code-coverage/configTip/render.go
modules/dop/component-protocol/components/code-coverage/downloadButton/render.go
modules/dop/component-protocol/components/code-coverage/endButton/render.go
modules/dop/component-protocol/components/code-coverage/envFilter/render.go
modules/dop/component-protocol/components/code-coverage/errText/render.go
modules/dop/component-protocol/components/code-coverage/executeHistory/render.go
modules/dop/component-protocol/components/code-coverage/executeHistoryTable/render.go
modules/dop/component-protocol/components/code-coverage/scenario.go
modules/dop/component-protocol/components/code-coverage/startButton/render.go
modules/dop/component-protocol/components/code-coverage/timeSelector/render.go
modules/dop/component-protocol/components/code-coverage/tip/render.go
modules/dop/component-protocol/components/code-coverage/treeMapChart/render.go
modules/dop/component-protocol/scenarios/code-coverage.yml

/kind bugfix
add code coverage component i18n

code coverage i18n

---

cmd/pipeline/main.go
conf/pipeline/pipeline.yaml
modules/pipeline/conf/conf.go
modules/pipeline/initialize.go
modules/pipeline/metrics/init.go
modules/pipeline/metrics/pipeline.go
modules/pipeline/metrics/task.go
modules/pipeline/pipengine/reconciler/task.go
modules/pipeline/pipengine/reconciler/taskrun/taskop/wait.go
modules/pipeline/pipengine/reconciler/taskrun/update.go
modules/pipeline/pipengine/reconciler/teardown.go
modules/pipeline/provider.go

/kind bugfix
recover pipeline metrics as before
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=243783&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=541&type=BUG)
Add comment like `/cherry-pick release/1.0` when …

recover pipeline metrics as before

---

modules/core/monitor/settings/settings.service.go

/kind bugfix
remove debug code

remove debug code

---

modules/core/monitor/settings/settings.service.go

/kind bugfix
remove debug code 1.2

remove debug code 1.2

---

modules/core/monitor/log/storage/cassandra/iterator.go
modules/core/monitor/log/storage/cassandra/iterator_test.go

/kind polish
fix query log from cassandra bug

fix query log from cassandra bug

---

modules/core/monitor/alert/alert-apis/alert.service.go
modules/msp/apm/alert/alert.service.go

/kind bugfix
| 🇺🇸 English |      Fix the bug that the custom alarm filtering rules created by msp and cmp are incorrect       |
| 🇨🇳 中文    |        修复msp和cmp创建自定义告警过滤规则不正确的问题      |

modify customize alert rule

---

modules/cmp/component-protocol/components/cmp-dashboard-events-list/eventTable/render.go
modules/cmp/steve/middleware/audit.go

/kind bugfix
add nopcloser in http.request when audit

fix: empty request body

---

modules/core/monitor/alert/alert-apis/adapt/alert_route.go

/kind feature
/kind bugfix
| 🇺🇸 English |        modify the display-url splicing path      |
| 🇨🇳 中文    |        修改display-url拼接路径      |

modify display_url

---

modules/dop/component-protocol/components/test-dashboard/at_case_rate_trending_chart_group/filter/model.go
modules/dop/component-protocol/components/test-dashboard/at_case_rate_trending_chart_group/filter/render.go
modules/dop/component-protocol/components/test-dashboard/scene_and_api_filter/model.go
modules/dop/component-protocol/components/test-dashboard/scene_and_api_filter/render.go

/kind polish
fix: add borderTime to timePicker
- [Erda Cloud Issue Link](https://terminus-org.erda.cloud/erda/dop/projects/387/issues/all?id=243371&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=541&type=BUG)
/assign @sfwn 
Add comment like `/cherry-pick release/1.0` when this PR is …

fix: add borderTime to timePicker
