- apistructs/issue.go
- apistructs/issue_state.go
- modules/dop/component-protocol/components/common/issue.go
- modules/dop/component-protocol/components/requirement-task-overview/common/gshelper/helper.go
- modules/dop/component-protocol/components/requirement-task-overview/common/vars.go
- modules/dop/component-protocol/components/requirement-task-overview/container/info/model.go
- modules/dop/component-protocol/components/requirement-task-overview/container/info/render.go
- modules/dop/component-protocol/components/requirement-task-overview/container/simpleChart/model.go
- modules/dop/component-protocol/components/requirement-task-overview/container/simpleChart/render.go
- modules/dop/component-protocol/components/requirement-task-overview/distributePage/topFilter/model.go
- modules/dop/component-protocol/components/requirement-task-overview/distributePage/topFilter/render.go
- modules/dop/dao/issue.go
- modules/dop/dao/issue_state.go
- modules/dop/services/issuestate/issuestate.go
- modules/dop/services/issuestate/issuestate_mock.go
- providers/component-protocol/issueFilter/options.go
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTc4LDExOTAsMTE3NF0sImFzc2lnbmVlIjpbIjEwMDEwNzMiXX0%3D&id=299960&iterationID=1174&pId=303255&type=TASK)
/assign @sfwn 
| 🇺🇸 English |    Links on statistics of requirement and task overview          |
| 🇨🇳 中文    |  统计数据的跳转            |
> feat: Links on statistics of requirement and task overview

- modules/pipeline/providers/dispatcher/dispatcher.go
- modules/pipeline/providers/dispatcher/interface.go
- modules/pipeline/providers/engine/interface.go
- modules/pipeline/providers/leaderworker/impl_leader.go
- modules/pipeline/providers/leaderworker/interface.go
pipeline cancel on non-leader node
| 🇺🇸 English |   fix the issue that pipeline cannot cancel on non-leader node           |
| 🇨🇳 中文    |  修复了无法在非 leader 节点取消流水线的问题            |
> fix(pipeline): pipeline cancel on non-leader node

- modules/core/monitor/dataview/dashboard_file.go
| 🇺🇸 English |     custom dashboard import userinfo error       |
| 🇨🇳 中文    |       自定义大盘导入用户错误       |
> fix: custom dashboard import userinfo error

- conf/admin/i18n/cp/scenarios/personal-workbench.yaml
- conf/dop/i18n/contribution.yaml
- modules/admin/component-protocol/components/personal-workbench/workCards/provider.go
Update personal workbench i18n
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTc4LDExOTAsMTE3NF0sImFzc2lnbmVlIjpbIjEwMDEwNzMiXX0%3D&id=304868&iterationID=1174&pId=304028&type=TASK)
/assign @sfwn 
| 🇺🇸 English | Update personal workbench i18n             |
| 🇨🇳 中文    |   个人工作台国际化问题修复           |
> chore: Update personal workbench i18n

- modules/dop/component-protocol/components/common/issue.go
- modules/dop/component-protocol/components/requirement-task-overview/container/info/render.go
Fix issue finish at and state condition, code refactor
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTc4LDExOTAsMTE3NF0sImFzc2lnbmVlIjpbIjEwMDEwNzMiXX0%3D&id=305221&iterationID=1174&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |   Fix issue finish at and state condition, code refactor           |
| 🇨🇳 中文    |    修复了统计跳转的事项截止日期和状态筛选条件          | …
> fix: Fix issue finish at and state condition, code refactor

- modules/orchestrator/services/addon/addon_handler.go
- modules/orchestrator/services/addon/addon_handler_test.go
fix: case tag is empty
| 🇺🇸 English | fix the problem in deploy addons case tag is empty |
| 🇨🇳 中文    | 修复了部署 addon 时 tag 为空时造成的部署错误的问题 |
> fix: case tag is empty

- modules/dop/services/issue/adjust.go
- modules/dop/services/issue/issue.go
Adjust issue plan finish time to iteration start time
| 🇺🇸 English |   Adjust issue plan finish time to iteration start time           |
| 🇨🇳 中文    |  调整事项截止时间为迭代开始时间            |
> feat: Adjust issue plan finish time to iteration start time

- modules/dop/component-protocol/components/release-manage/releaseFilter/provider.go
fix: no data in tags filter
| 🇺🇸 English | fix: no data in tags filter  |
| 🇨🇳 中文    | 修复制品列表过滤器中没有标签数据的问题 |
> fix: no data in tags filter

- apistructs/cluster_dialer.go
- bundle/bundle.go
- bundle/cluster_dialer.go
- bundle/urls.go
- modules/cluster-dialer/auth/auth.go
- modules/cluster-dialer/server/tunnel-server.go
cluster dialer support pipeline-agent register
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=304696&iterationID=1174&pId=301655&type=TASK)
| 🇺🇸 English |   cluster dialer support pipeline-agent register           |
| 🇨🇳 中文    |     cluster-dialer支持pipeline客户端的注册         |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBU …
> feat(cluster-dialer): cluster dialer support pipeline-agent register

- apistructs/release.go
fix: modify release tag struct in apistructs
| 🇺🇸 English | fix: modify release tag struct in apistructs |
| 🇨🇳 中文    | 修改apistructs中的制品标签结构 |
> fix: modify release tag struct in apistructs

- modules/core-services/dao/label_relation.go
- modules/core-services/services/label/label.go
- modules/dop/component-protocol/components/issue-dashboard/bar/labelHorizontalBarChart/render.go
- modules/dop/dao/issue.go
fix: modify label relation refID in core-services and dop
| 🇺🇸 English | fix: modify label relation refID in core-services and dop |
| 🇨🇳 中文    | 修改core-services和dop中labelRelation的refID字段类型为string |
> fix: modify label relation refID in core-services and dop

- pipeline.yml
| 🇺🇸 English |     use ci-build-local to build agent      |
| 🇨🇳 中文    |       使用 ci-build-local 构建 agent       |
> feat: use ci-build-local to build agent

- modules/core-services/dao/label_relation.go
- modules/core-services/services/label/label.go
- modules/dop/component-protocol/components/issue-dashboard/bar/labelHorizontalBarChart/render.go
- modules/dop/dao/issue.go
cherry-pick #4621 to release/2.1-beta.4
| 🇺🇸 English | fix: modify label relation refID in core-services and dop |
| 🇨🇳 中文    | 修改core-services和dop中labelRelation的refID字段类型为string |
> fix: modify label relation refID in core-services and dop (Cherry-Pick)

- modules/dicehub/release/release.go
cherry-pick #4622 to release/2.0-beta.4
| 🇺🇸 English | fix: return null if there is no release with target tags |
| 🇨🇳 中文    | 若没有制品符合筛选标签，则返回空 |
> fix: return null if there is no release with target tags (Cherry-Pick)

- modules/dicehub/release/release.go
fix: return null if there is no release with target tags
| 🇺🇸 English | fix: return null if there is no release with target tags |
| 🇨🇳 中文    | 若没有制品符合筛选标签，则返回空 |
> fix: return null if there is no release with target tags

- modules/gittar/api/merge.go
- modules/gittar/initialize.go
- modules/gittar/models/merge_request.go
- modules/openapi/api/apis/gittar/repo_proxy_get.go
add merge request stats api for gittar
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTc0XSwiYXNzaWduZWUiOlsiMTAwMTI2MSJdfQ%3D%3D&id=306038&iterationID=1174&pId=0&type=TASK)
/assign @sfwn 
| 🇺🇸 English |    add merge request stats api for gittar          |
| 🇨🇳 中文    |     gittar 添加合并请求统计 api         |
> feat(gittar): add merge request stats api for gittar

- go.sum
- modules/orchestrator/services/deployment_order/deployment_order_render.go
fix: polish: pre check app concurrently in render-detail
| 🇺🇸 English | fix: polish: pre check app concurrently in render-detail |
| 🇨🇳 中文    | 在部署中心render-detail中并发地对应用进行检查以优化加载速度 |
> fix: polish: pre check app concurrently in render-detail

- modules/orchestrator/services/deployment_order/deployment_order_render.go
fix: render-detail panic
| 🇺🇸 English | fix: render-detail panic |
| 🇨🇳 中文    | 修复render-detail接口的panic问题 |
> fix: render-detail panic

- apistructs/job.go
- apistructs/pipeline.go
- apistructs/pipeline_task.go
- modules/pipeline/pipengine/actionexecutor/plugins/k8sflink/util.go
- modules/pipeline/pipengine/actionexecutor/plugins/k8sjob/k8sjob.go
- modules/pipeline/pipengine/actionexecutor/plugins/k8sspark/k8sspark.go
- modules/pipeline/providers/reconciler/taskrun/taskop/prepare.go
add org annotation for pipeline job
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=306028&iterationID=-1&pId=0&type=TASK)
/assign @sfwn
| 🇺🇸 English |  add org annotation for pipeline job            |
| 🇨🇳 中文    |   添加组织的元信息到pipeline job           |
> feat(pipeline): add org annotation for pipeline job

- modules/pipeline/providers/reconciler/reconcile.go
remove useless code of pipeline cancel
| 🇺🇸 English | remove useless code of pipeline cancel     |
| 🇨🇳 中文    |  删除"流水线取消"相关的无用代码            |
> chore(pipeline): remove useless code of pipeline cancel

- modules/orchestrator/services/deployment_order/deployment_order_render.go
fix: convert err to fail reasons
| 🇺🇸 English | fix: convert err to fail reasons |
| 🇨🇳 中文    | render-detail接口中precheck的错误作为原因显示在页面上，而不是直接报错 |
> fix: convert err to fail reasons

- modules/core/monitor/alert/alert-apis/adapt/alert_test.go
- modules/monitor/dashboard/org-apis/container.go
- modules/monitor/utils/map.go
- modules/monitor/utils/map_test.go
orgs-api bugfix
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/ticket?id=305832&title=15)
| 🇺🇸 English |      orgs-api bugfix        |
| 🇨🇳 中文    |      修复云管界面列表api        |
> fix: orgs-api bugfix

- apistructs/pipeline_task.go
- apistructs/pipeline_task_test.go
judge task IsErrorsExceed by calculate count frequency per hour
/assign @sfwn 
| 🇺🇸 English |   judge task IsErrorsExceed by calculate count frequency per hour           |
| 🇨🇳 中文    |    通过每小时错误的频率判断job的异常是否过多          |
> fix(pipeline): judge task `IsErrorsExceed` by calculate count frequency per hour

- conf/msp/i18n/msp-i18n.yaml
The count field of log-service in the MSP module is internationalized
| 🇺🇸 English |       The count field of log-service in the MSP module is internationalized       |
| 🇨🇳 中文    |       msp模块中log-service的count字段做国际化       |
> feat: The count field of log-service in the MSP module is internationalized

- modules/hepa/apipolicy/policies/csrf/policy.go
- modules/hepa/kong/base/kong_adapter.go
- modules/hepa/kong/dto/kong_route_req_dto.go
- modules/hepa/kong/dto/kong_route_req_dto_test.go
- modules/hepa/kong/interface.go
- modules/hepa/providers/legacy_upstream/upstream.service.go
- modules/hepa/services/api_policy/impl/impl.go
- modules/hepa/services/endpoint_api/impl/impl.go
- modules/hepa/services/legacy_upstream/impl/impl.go
- modules/hepa/services/micro_api/impl/impl.go
feat: enable csrf plugin by tag
| 🇺🇸 English | enable csrf plugin on unity package APIs |
| 🇨🇳 中文    | 在 unity 流量入口的 API 上启用 CSRF 插件 |
> feat: enable csrf plugin on unity package

- modules/hepa/gateway/dto/runtime_domains_dto.go
- pkg/strutil/slice.go
- pkg/strutil/slice_test.go
| 🇺🇸 English | fix error on revering string |
| 🇨🇳 中文    | 修复一处翻转 String 的错误 |
> fix: reverse string

- conf/monitor/monitor/alert/rules/app_resource/app_resource_container_cpu/analyzer_expression.json
modify app_resource_container_cpu invoke function
| 🇺🇸 English |       modify app_resource_container_cpu invoke function       |
| 🇨🇳 中文    |       增加app_resource_container_cpu表达式的cpu_usage_percent字段判断       |
> fix: modify app_resource_container_cpu invoke function

- Makefile
- build/scripts/docker_image.sh
| 🇺🇸 English |    rm EXTENSION_ZIP_ADDRS         |
| 🇨🇳 中文    |    删除 EXTENSION_ZIP_ADDRS          |
> feat: rm EXTENSION_ZIP_ADDRS

- modules/pipeline/providers/leaderworker/inspect.go
- modules/pipeline/providers/leaderworker/provider.go
leaderworker add inspect api
| 🇺🇸 English |  leaderworker add inspect api            |
| 🇨🇳 中文    |  leaderworker 增加 Inspect API           |
> feat(pipeline): leaderworker add inspect api

- .erda/pipelines/ci-deploy.yml
- .gitignore
- erda.yml
ci-deploy for dev
| 🇺🇸 English |    ci-deploy for dev          |
| 🇨🇳 中文    |     ci-deploy for dev         |
> ci: ci-deploy for dev

- modules/core-services/services/member/member.go
- modules/core-services/services/member/member_test.go
- modules/uc-adaptor/service/adaptor/recevier_members.go
- modules/uc-adaptor/service/adaptor/ucadaptor.go
Update member info includes avatar in uc adaptor.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTc4LDExNzQsMTE5MCwxMjE4XSwiYXNzaWduZWUiOlsiMTAwMTA3MyJdfQ%3D%3D&id=307198&iterationID=1174&pId=0&type=BUG)
| 🇺🇸 English |  Update member info includes avatar in uc adaptor.            |
| 🇨🇳 中文    |   更新成员头像           | …
> feat: Update member info includes avatar in uc adaptor.

- modules/pipeline/dbclient/op_pipeline_base.go
- modules/pipeline/dbclient/op_pipeline_cron.go
- modules/pipeline/dbclient/op_pipeline_labels.go
- modules/pipeline/dbclient/op_pipeline_queue.go
- modules/pipeline/dbclient/op_pipeline_report.go
- modules/pipeline/dbclient/op_pipeline_stage.go
- modules/pipeline/dbclient/op_pipeline_task.go
- modules/pipeline/providers/cron/db/define_extra.go
- modules/pipeline/services/pipelinesvc/create_label.go
- modules/pipeline/services/pipelinesvc/create_label_test.go
Update pipelineID、taskID、cronID、labelID and stageID to uuid
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTkwLDExNzRdLCJhc3NpZ25lZSI6WyIxMDAxMjYxIl19&id=306365&iterationID=1190&pId=306714&type=TASK)
/assign @sfwn 
| 🇺🇸 English |    Update pipelineID、taskID、cronID、labelID and stageID to uuid          |
| 🇨🇳 中文    |     pipelineID、taskID等改为uuid         | …
> feat(pipeline): Update pipelineID、taskID、cronID、labelID and stageID to uuid

- apistructs/cluster_dialer_query_ip.go
- conf/cluster-dialer/cluster-dialer.yaml
- erda.yml
- modules/cluster-dialer/provider.go
- modules/cluster-dialer/server/dialer_test.go
- modules/cluster-dialer/server/tunnel-server.go
- modules/cluster-dialer/server/tunnel-server_test.go
- modules/cmp/steve/middleware/audit.go
- pkg/apitestsv2/netportal_test.go
- pkg/clusterdialer/dialer.go
- pkg/clusterdialer/dialer_test.go
- pkg/clusterdialer/tunnel_session.go
- pkg/http/customhttp/request.go
- pkg/http/customhttp/request_test.go
fix: polish: cluster dialer with high availability
| 🇺🇸 English | fix: polish: cluster dialer with high availability |
| 🇨🇳 中文    | cluster-dialer组件支持高可用 |
> fix: polish: cluster dialer with high availability

- modules/pipeline/dbclient/op_pipeline_labels.go
- pkg/clusterdialer/dialer_test.go
fix the bug of batch create labels
/assign @sfwn 
| 🇺🇸 English |   Solve the problem of primary key conflict in batch creation of labels           |
| 🇨🇳 中文    |        解决批量创建label主键冲突问题      |
> fix(pipeline):  Solve the problem of primary key conflict in batch creation of labels

- pkg/oauth2/clientstore/mysqlclientstore/client_store.go
Fix token client table name.
/assign @sfwn 
| 🇺🇸 English |  Fix token client table name.            |
| 🇨🇳 中文    |  修复表名称            |
> fix: Fix token client table name.

- modules/dop/providers/projectpipeline/service_impl_test.go
add unit test to project pipeline
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTc0LDExOTBdLCJhc3NpZ25lZSI6WyIxMDAxMjYxIl19&id=305705&iterationID=1190&pId=0&type=TASK)
/assign @sfwn 
| 🇺🇸 English |    add unit test to project pipeline          |
| 🇨🇳 中文    |     增加单测         |
> feat: add unit test to project pipeline

- conf/cmp/cmp.yaml
- conf/cmp/i18n/cp/scenarios/cmp-dashboard-nodeDetail.yaml
- modules/cmp/component-protocol/components/cmp-dashboard-pods/podsTable/render.go
- modules/cmp/initialize.go
- modules/cmp/steve/aggregator.go
call cancel if steve server start failed
/assign @sixther-dc @jferic 
| 🇺🇸 English | fix: call cancel if steve server start failed |
| 🇨🇳 中文    | 调用steve server的cancel函数以将其垃圾回收，修复cmp的OOM问题 |
> fix: cmp OOM

- conf/monitor/collector/collector-agent.yaml
- conf/monitor/collector/collector.yaml
- modules/oap/collector/plugins/processors/k8s-tagger/metadata/pod/config.go
- modules/oap/collector/plugins/processors/k8s-tagger/metadata/pod/pod.go
- modules/oap/collector/plugins/processors/k8s-tagger/metadata/pod/pod_test.go
- modules/oap/collector/plugins/processors/k8s-tagger/provider.go
- modules/oap/collector/plugins/processors/k8s-tagger/tagger.go
k8s-taggers support multi finders
| 🇺🇸 English |       k8s-taggers support multi finders       |
| 🇨🇳 中文    |       k8s-taggers插件支持多种finder       |
> feat: k8s-taggers support multi finders

- modules/orchestrator/services/deployment/deployment_context.go
- pkg/loop/loop.go
fix: error shadowed in pkg/loop
| 🇺🇸 English | fix: error shadowed in pkg/loop |
| 🇨🇳 中文    | 解决pkg/loop包中调用函数的错误未被返回的问题，解决orchestrator组件部署失败但仍显示成功的问题 |
> fix: error shadowed in pkg/loop

- modules/dop/dao/sceneset.go
- modules/dop/services/sceneset/sceneset.go
- modules/dop/services/sceneset/sceneset_test.go
sceneSet name not case sensitive
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTkwXSwiYXNzaWduZWUiOlsiMTAwMTI2MSJdfQ%3D%3D&id=307079&iterationID=1190&pId=0&type=REQUIREMENT)
/assign @sfwn 
| 🇺🇸 English |    sceneSet name case sensitive          |
| 🇨🇳 中文    |      场景集名称区分大小写        |
> feat(dop): sceneSet name case sensitive

- erda.yml
fix: modify replica of cluster-dialer
| 🇺🇸 English | fix: modify replica of cluster-dialer |
| 🇨🇳 中文    | 修改cluster-dialer的副本数 |
> fix: modify replica of cluster-dialer

- .erda/migrations/cmdb/20220427-label-unique-key.sql
- modules/core-services/dao/label.go
- modules/core-services/services/label/label.go
- modules/dop/component-protocol/components/release-manage/releaseTable/render.go
fix: label primary key
| 🇺🇸 English | fix: label primary key |
| 🇨🇳 中文    | 修改标签唯一性约束为：项目ID，标签名称，标签类型 |
> fix: label primary key

- modules/dop/initialize.go
- modules/dop/provider_test.go
- modules/dop/services/cdp/cdp.go
- pkg/erda-configs/i18n/notify_item.yml
pipeline notifications add information for cicd
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=301476&iterationID=1190&pId=0&type=REQUIREMENT)
| 🇺🇸 English |  pipeline notifications add information for cicd             |
| 🇨🇳 中文    |   流水线通知中包含部署的关键信息           |
> feat(dop): pipeline notifications add information for cicd

- modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/filter/render.go
- modules/cmp/steve/aggregator.go
fix: add number of ready steve server in cmp
| 🇺🇸 English | fix: add number of ready steve server in cmp |
| 🇨🇳 中文    | 添加打印就绪的steve服务的数量的日志 |
Need cherry-pick to release/2.1
> fix: add number of ready steve server in cmp

- .gitattributes
ignore api/proto-go/ for github pull request
see: https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github
| 🇺🇸 English |      ignore api/proto-go/ for github pull request        |
| 🇨🇳 中文    |       pr 忽略 api/proto-go/       |
> chore: ignore api/proto-go/ for github pull request

- modules/pipeline/providers/clusterinfo/provider.go
- modules/pipeline/providers/edgepipeline_register/edge_center_use.go
- modules/pipeline/providers/edgepipeline_register/edge_center_use_test.go
- modules/pipeline/providers/edgepipeline_register/interface.go
- modules/pipeline/providers/edgepipeline_register/provider.go
edge-pipeline provider add handlers for edge, center use
/assign @sfwn 
| 🇺🇸 English |   edge-pipeline provider add handlers for edge, center use           |
| 🇨🇳 中文    |     edge-pipeline provider增加边缘中心侧的使用方法         |
> feat(pipeline): edge-pipeline provider add handlers for edge, center use

- conf/pipeline/pipeline.yaml
feat: pipeline support refresh cluster interval from env config
| 🇺🇸 English | pipeline support refresh cluster interval from env config             |
| 🇨🇳 中文    |  pipeline 支持从环境变量获取集群配置重载的时间间隔配置            |
> feat: pipeline support refresh cluster interval from env config

- modules/extensions/loghub/index/query/log_query.go
- modules/msp/apm/log-service/query/log.service.histogram.go
- modules/msp/apm/log-service/query/log.service.search.go
- modules/msp/apm/log-service/query/log.service.terms.go
fix the bug of xiexin invalid memory address or nil pointer
| 🇺🇸 English |       fix the bug of xiexin invalid memory address or nil pointer       |
| 🇨🇳 中文    |       协鑫日志分析空指针异常       |
> fix: fix the bug of xiexin invalid memory address or nil pointer

- modules/core/monitor/log/query/log.query.service.go
- modules/core/monitor/log/query/log.query.service_test.go
- modules/core/monitor/log/query/routes.go
- modules/core/monitor/log/storage/clickhouse/iterator.go
- modules/core/monitor/log/storage/clickhouse/iterator_test.go
- modules/core/monitor/log/storage/storage.go
- modules/extensions/loghub/index/query/routes.go
- modules/msp/apm/log-service/query/log.service.download.go
fix the bug that download log from clickhouse only got the first 200 lines
| 🇺🇸 English |        fix the bug that download log from clickhouse only got the first 200 lines      |
| 🇨🇳 中文    |       修复clickhouse日志下载只能下载前200条的问题       |
> fix: fix clickhouse download file size error

- modules/pipeline/providers/edgereporter/provider.go
fix typo in edge reporter config
/assign @littlejiancc 
| 🇺🇸 English |  fix typo in edge reporter config            |
| 🇨🇳 中文    |  修复 edge reporter 配置中的拼写错误            |
> fix(pipeline): typo in edge reporter config

- .gitignore
polish: add extensions dir to .gitignore
/assign @kakj-go 
| 🇺🇸 English |  add extensions dir to .gitignore            |
| 🇨🇳 中文    |   .gitignore 增加 extensions 目录           |
> polish: add extensions dir to .gitignore

- modules/pipeline/providers/edgepipeline_register/interface.go
- modules/pipeline/providers/edgepipeline_register/interface_test.go
- modules/pipeline/providers/edgepipeline_register/provider.go
1. edge side pipeline watch secret event
2. set `cluster key` as edge task token
/assign @sfwn 
| 🇺🇸 English |  edge side pipeline watch secret event            |
| 🇨🇳 中文    |    边缘pipeline监听cluster key变更          |
> feat(pipeline): edge side pipeline watch secret event

- modules/pipeline/providers/cron/compensator/provider.go
Fixed the null pointer problem of edge pipeline execution compensation
| 🇺🇸 English |       Fixed the null pointer problem of edge pipeline execution compensation       |
| 🇨🇳 中文    |       修复边缘流水线执行补偿空指针问题       |
> fix(pipeline): Fixed the null pointer problem of edge pipeline execution compensation

- conf/pipeline/pipeline.yaml
- modules/pipeline/events/event.go
- modules/pipeline/events/manager.go
- modules/pipeline/initialize.go
- modules/pipeline/providers/actionmgr/provider.go
- modules/pipeline/providers/cron/cron.service.go
- modules/pipeline/providers/cron/daemon/cron_task.go
- modules/pipeline/providers/cron/daemon/provider.go
- modules/pipeline/providers/cron/db/define.go
- modules/pipeline/providers/cron/db/define_test.go
- modules/pipeline/providers/edgepipeline/create_pipeline.go
- modules/pipeline/providers/edgepipeline_register/provider.go
- modules/pipeline/providers/edgereporter/provider.go
- modules/pipeline/providers/edgereporter/reporter.go
- edge only do db hook of event
- cron use pointer bool for `is_edge` field for db update
- add useful logs
| 🇺🇸 English |  polish pipeline edge run            |
| 🇨🇳 中文    |   优化 pipeline 边缘执行逻辑           |
> polish(pipeline): pipeline edge run

- modules/pipeline/endpoints/pipeline.go
- modules/pipeline/providers/edgepipeline/interface.go
- modules/pipeline/providers/edgepipeline/provider.go
- modules/pipeline/providers/edgepipeline/run_pipeline.go
run one edge-side created pipeline
| 🇺🇸 English | support run edge-side created-but-not-run pipeline            |
| 🇨🇳 中文    |  支持运行在边缘创建的未执行的流水线           |
> feature(pipeline): run edge-side created pipeline

- conf/monitor/monitor/monitor.yaml
- modules/core/monitor/log/storage/clickhouse/aggregate_test.go
- modules/core/monitor/log/storage/clickhouse/converter/field_name_converter.go
- modules/core/monitor/log/storage/clickhouse/provider.go
- modules/core/monitor/log/storage/clickhouse/query_parser/query_parser.go
- modules/core/monitor/log/storage/clickhouse/query_parser/query_parser_test.go
- modules/core/monitor/log/storage/clickhouse/sql_builder.go
| 🇺🇸 English |      fix the bug that query log by request_id is slow        |
| 🇨🇳 中文    |     修复通过request_id查询速度慢的问题         |
> fix: transform request_id query to trace_id

- conf/monitor/streaming/clickhouse/logs_ddl_create_default_tables.sql
- conf/monitor/streaming/clickhouse/logs_ddl_create_tenant_tables.sql
| 🇺🇸 English |       ck add column index       |
| 🇨🇳 中文    |       ck添加索引       |
> feat: ck add column index

- modules/pipeline/providers/edgereporter/db/pipeline.go
- modules/pipeline/providers/edgereporter/reporter.go
polish edge pipeline reporter
/assign @sfwn 
| 🇺🇸 English |    polish edge pipeline reporter          |
| 🇨🇳 中文    |     优化边缘pipeline上报         |
> fix(pipeline): polish edge pipeline reporter

- modules/pipeline/endpoints/pipeline.go
- modules/pipeline/providers/actionmgr/impl_test.go
- modules/pipeline/providers/actionmgr/provider.go
- modules/pipeline/providers/actionmgr/refresh.go
- modules/pipeline/providers/clusterinfo/interface_test.go
- modules/pipeline/providers/cron/cron.service_test.go
- modules/pipeline/providers/edgepipeline/cancel_pipeline.go
- modules/pipeline/providers/edgepipeline/create_cron.go
- modules/pipeline/providers/edgepipeline/create_pipeline.go
- modules/pipeline/providers/edgepipeline/interface.go
- modules/pipeline/providers/edgepipeline/provider.go
- modules/pipeline/providers/edgepipeline/rerun_failed_pipeline.go
- modules/pipeline/providers/edgepipeline/rerun_pipeline.go
- modules/pipeline/providers/edgepipeline_register/interface.go
- modules/pipeline/providers/edgepipeline_register/mock.go
- modules/pipeline/providers/edgepipeline_register/provider.go
- modules/pipeline/providers/edgereporter/provider.go
- modules/pipeline/providers/edgereporter/reporter.go
- modules/pipeline/providers/edgereporter/reporter_test.go
- modules/pipeline/providers/edgereporter/token.go
feat(pipeline): support edge cancel/rerun/rerun-failed
| 🇺🇸 English |  support edge cancel/rerun/rerun-failed             |
| 🇨🇳 中文    |   支持边缘流水线的取消/重试/重试失败节点           |
> feat(pipeline): support edge cancel/rerun/rerun-failed

- modules/dop/component-protocol/components/release-manage/releaseTable/render.go
- modules/openapi/api/apis/orchestrator/orchestrator_runtime_group_by_my_apps.go
- modules/orchestrator/endpoints/endpoints.go
- modules/orchestrator/endpoints/runtime.go
feat: add list runtime group by my apps
| 🇺🇸 English | feat: add list runtime group by my apps |
| 🇨🇳 中文    | 添加按照我的应用分组获取runtime列表的接口 |
> feat: add list runtime group by my apps

- modules/dop/endpoints/pipelinecron.go
- modules/dop/endpoints/pipelinecron_test.go
- modules/openapi/api/apis/dop/adaptor_cicd_cron_start.go
- modules/openapi/api/apis/dop/adaptor_cicd_cron_stop.go
dop adds methods to obtain appid and branch
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMjI0LDEyMTgsMTE5MF0sImFzc2lnbmVlIjpbIjEwMDA1NjAiXX0%3D&id=310567&iterationID=1190&pId=0&type=BUG)
| 🇺🇸 English |      dop adds methods to obtain appid and branch        |
| 🇨🇳 中文    |       dop 增加获取 appid 和分支的方法       |
> fix(dop): dop adds methods to obtain appid and branch

- modules/pipeline/services/pipelinesvc/create_v2.go
Pipeline did not find cron. Cronid should not be set to 0
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTkwLDExNzQsMTIxOF0sImFzc2lnbmVlIjpbIjEwMDA1NjAiXX0%3D&id=309200&iterationID=1190&pId=0&type=BUG)
| 🇺🇸 English |     Pipeline did not find cron. Cronid should not be set to 0        |
| 🇨🇳 中文    |       pipeline 没有找到 cron 不应该将 cronid 设置为 0       |
> fix(pipeline): Pipeline did not find cron. Cronid should not be set to 0

- conf/pipeline/pipeline.yaml
- modules/pipeline/providers/edgepipeline_register/access_token.go
- modules/pipeline/providers/edgepipeline_register/cluster_access_key.go
- modules/pipeline/providers/edgepipeline_register/cluster_access_key_test.go
- modules/pipeline/providers/edgepipeline_register/interface.go
- modules/pipeline/providers/edgepipeline_register/interface_test.go
- modules/pipeline/providers/edgepipeline_register/provider.go
edge pipeline store access key in etcd
/assign @sfwn 
| 🇺🇸 English | edge pipeline store access key in etcd             |
| 🇨🇳 中文    |   边缘流水线存储access key进行校验           |
> feat(pipeline): edge pipeline store access key in etcd

- modules/cmp/component-protocol/components/cmp-dashboard-pods/podsTable/render.go
- modules/openapi/api/apis/orchestrator/orchestrator_runtime_list_my_runtimes.go
- modules/orchestrator/endpoints/endpoints.go
- modules/orchestrator/endpoints/runtime.go
fix: add application name in list runtime by my apps
| 🇺🇸 English | fix: add application name in list runtime by my apps |
| 🇨🇳 中文    | 在获取我的runtimes列表接口返回值中添加应用名称 |
> fix: add application name in list runtime by my apps

- modules/orchestrator/scheduler/executor/plugins/k8s/deployment.go
modify blue_green_deploy default value is open
| 🇺🇸 English |      modify blue_green_deploy default value is open        |
| 🇨🇳 中文    |       蓝绿部署默认打开       |
> feat: modify blue_green_deploy default value is open

- pkg/clusterdialer/tunnel_session.go
fix: delete session if connect failed
| 🇺🇸 English | fix: delete session if connect failed |
| 🇨🇳 中文    | 如果session连接失败则从sync.Map中删除 |
Need cherry-pick to release/2.2-beta.1
> fix: delete session if connect failed

- conf/monitor/monitor/monitor.yaml
- modules/core/monitor/log/query/log.query.service.go
- modules/core/monitor/log/query/log.query.service_test.go
- modules/core/monitor/log/query/provider.go
fix runtime log query is empty bug.
| 🇺🇸 English |      fix runtime log query is empty        |
| 🇨🇳 中文    |     修复了运行时日志查询为空的 bug         |
> fix(monitor) fix runtime log query is empty

- modules/pipeline/providers/reconciler/pipeline_reconciler_impl.go
- modules/pipeline/providers/reconciler/pipeline_reconciler_impl_test.go
- modules/pipeline/providers/reconciler/reconcile.go
- modules/pipeline/providers/reconciler/reconcile_test.go
Solve the problem of reporting the running status of the pipeline
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTkwXSwiYXNzaWduZWUiOlsiMTAwMTI2MSJdfQ%3D%3D&id=310762&iterationID=1190&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |   Solve the problem of reporting the running status of the pipeline           |
| 🇨🇳 中文    |     解决pipeline上报running状态问题         | …
> fix(pipeline): Solve the problem of reporting the running status of the pipeline

- conf/monitor/streaming/clickhouse/logs_ddl_create_db.sql
- conf/monitor/streaming/clickhouse/logs_ddl_create_default_tables.sql
- conf/monitor/streaming/clickhouse/logs_ddl_create_tenant_tables.sql
- modules/core/monitor/log/log.go
- modules/core/monitor/log/storage/clickhouse/iterator.go
- modules/core/monitor/log/storage/clickhouse/writer.go
- modules/core/monitor/log/storage/clickhouse/writer_test.go
| 🇺🇸 English |      change clickhouse log table schema        |
| 🇨🇳 中文    |       调整 ck 日志表结构       |
> feat: refactor clickhouse log table schema

- conf/erda-server/erda-server.yaml
- conf/erda-server/i18n/cp/scenarios/personal-workbench.yaml
fix: rollback i18n file for erda-server
| 🇺🇸 English |       fix: rollback i18n file for erda-server       |
| 🇨🇳 中文    |       回滚erda-server的i18n配置文件       |
> fix: rollback i18n file for erda-server

- conf/openapi/openapi.yaml
- modules/openapi/api/apis/admin/admin_approve_get.go
- modules/openapi/api/apis/admin/admin_approve_list.go
- modules/openapi/api/apis/admin/admin_approve_update.go
- modules/openapi/api/apis/admin/admin_audits_export.go
- modules/openapi/api/apis/admin/admin_cluster_get.go
- modules/openapi/api/apis/admin/admin_cluster_list.go
- modules/openapi/api/apis/admin/admin_dingtalk.go
- modules/openapi/api/apis/admin/admin_notice_create.go
- modules/openapi/api/apis/admin/admin_notice_delete.go
- modules/openapi/api/apis/admin/admin_notice_list.go
- modules/openapi/api/apis/admin/admin_notice_publish.go
- modules/openapi/api/apis/admin/admin_notice_update.go
- modules/openapi/api/apis/admin/admin_user_search.go
fix: modify addr of personal-workbentch for component-protocol and openapi 
| 🇺🇸 English |      fix: modify addr of personal-workbentch for component-protocol and openapi         |
| 🇨🇳 中文    |        修复openapi转发erda-server的地址      |
> fix: modify addr of personal-workbentch for component-protocol and openapi 

- modules/core/monitor/log/storage/clickhouse/iterator.go
| 🇺🇸 English |       fix the bug that query from ck failed       |
| 🇨🇳 中文    |     修复查询ck时报错的问题         |
> fix: add ch field for query

- cmd/cluster-manager/main.go
- conf/dop/dop.yaml
fix: cluster-manager and dop config
| 🇺🇸 English | fix: cluster-manager and dop config |
| 🇨🇳 中文    | 修改cluster-manager和dop的配置 |
> fix: cluster-manager and dop config

- modules/core-services/services/project/project.go
- modules/core-services/services/project/project_test.go
feat: convert `project_id` to string in query condition for using index.
| 🇺🇸 English | convert `project_id` to string in query condition for using index. |
| 🇨🇳 中文    | 查询 `s_pod_info` 时 `project_id` 转换成 string, 以修复用不上索引的问题 |
> fix: convert `project_id` to string

- cmd/gittar/main.go
| 🇺🇸 English |   Fix gittar grpc client           |
| 🇨🇳 中文    |    修复    gittar grpc client      |
> fix: Fix gittar grpc client.

- conf/monitor/monitor/monitor.yaml
- conf/monitor/streaming/clickhouse/logs_ddl_create_default_tables.sql
- conf/monitor/streaming/clickhouse/logs_ddl_create_tenant_tables.sql
- conf/monitor/streaming/streaming.yaml
- modules/core/monitor/log/storage/clickhouse/aggregate_test.go
- modules/core/monitor/log/storage/clickhouse/writer.go
- modules/core/monitor/storekit/clickhouse/table/creator/creator.go
- modules/core/monitor/storekit/clickhouse/table/creator/provider.go
- modules/core/monitor/storekit/clickhouse/table/initializer/init.go
- modules/core/monitor/storekit/clickhouse/table/initializer/init_test.go
- modules/core/monitor/storekit/clickhouse/table/initializer/mock_test.go
- modules/core/monitor/storekit/clickhouse/table/initializer/provider.go
- modules/core/monitor/storekit/clickhouse/table/initializer/ttl_sync.go
- modules/core/monitor/storekit/clickhouse/table/initializer/ttl_sync_test.go
- modules/core/monitor/storekit/clickhouse/table/loader/interface.go
- modules/core/monitor/storekit/clickhouse/table/loader/provider.go
- modules/core/monitor/storekit/clickhouse/table/loader/table_loader.go
- modules/core/monitor/storekit/clickhouse/table/loader/table_loader_test.go
- modules/core/monitor/storekit/clickhouse/table/table.go
- modules/core/monitor/storekit/clickhouse/table/table_test.go
| 🇺🇸 English |       support clickhouse ttl sync and schema migration       |
| 🇨🇳 中文    |     支持 clickhouse 表结构的 ttl 和 DDL 变更  的 自动同步      |
> feat: auto sync the ck ttl and schema migration

- conf/monitor/monitor/monitor.yaml
- modules/core/monitor/log/storage/clickhouse/iterator.go
- modules/core/monitor/log/storage/clickhouse/iterator_test.go
- modules/core/monitor/log/storage/clickhouse/provider.go
| 🇺🇸 English |      support set resource limitation on log query on clickhouse        |
| 🇨🇳 中文    |       支持限制日志查询使用的服务器线程数等资源       |
> feat: support set resource limitation on log query on clickhouse

- erda.yml
specify resources for development
/assign @dspo 
| 🇺🇸 English |   specify resources for development           |
| 🇨🇳 中文    |  为开发环境声明资源配置            |
> chore: specify resources for development

- apistructs/dashboard.go
- bundle/dashboard.go
- modules/core/monitor/log/storage/clickhouse/iterator.go
- modules/core/monitor/log/storage/clickhouse/iterator_test.go
- modules/core/monitor/log/storage/kubernetes-logs/provider.go
- modules/dop/endpoints/cicd.go
| 🇺🇸 English |       fix ck timeout setting bug       |
| 🇨🇳 中文    |       修复 ck 超时设置导致查询失败问题       |
> fix: fix ck timeout setting bug

- modules/dop/component-protocol/components/release-manage/releaseTable/render.go
- modules/orchestrator/endpoints/runtime.go
feat: add appID in list my runtimes
| 🇺🇸 English | feat: add appID in list my runtimes  |
| 🇨🇳 中文    | 在list-my-runtimes接口中支持用appID过滤 |
> feat: add appID in list my runtimes

- modules/dop/providers/devflowrule/db/define.go
fix the bug of json serialization
| 🇺🇸 English |  fix the bug of json serialization            |
| 🇨🇳 中文    |     解决json序列化问题         |
> fix(dop): fix the bug of json serialization

- modules/dop/services/issue/import.go
- modules/dop/services/issue/import_test.go
Set issue import creator to operator.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=311956&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&type=BUG)
| 🇺🇸 English | Set issue import creator to operator.             |
| 🇨🇳 中文    |  创建人设为导入事项的操作人            | …
> fix: Set issue import creator to operator.

- go.mod
- go.sum
- modules/dop/provider_test.go
fix dop i18n mock  caused by infra's upgrade
| 🇺🇸 English |   fix dop i18n mock  caused by infra's upgrade         |
| 🇨🇳 中文    |   修复由于 infra 升级导致的 dop i18n mock 问题           |
> fix: dop i18n mock caused by infra's upgrade

- erda.yml
/assign @sfwn 
| 🇺🇸 English |       change default replicas of log-service in test env       |
| 🇨🇳 中文    |         调整集成环境 log-service 默认副本数     |
> feat: log-service replicas default to 1 for test env

- modules/orchestrator/scheduler/executor/plugins/k8s/job.go
feat: delete history job when create new job for task runtime
/assign 
| 🇺🇸 English |        feat: delete history job when create new job for task runtime      |
| 🇨🇳 中文    |         回收历史job     |
> feat: delete history job when create new job for task runtime

- modules/core-services/dao/migration.go
- modules/core-services/model/uc_migration.go
- modules/core-services/services/user/user.go
- modules/openapi/api/apis/uc/uc_user_create.go
- pkg/ucauth/kratos.go
- pkg/ucauth/model.go
- pkg/ucauth/user_migration.go
Update kratos user import.
| 🇺🇸 English |  Update kratos user import            |
| 🇨🇳 中文    |   更新导入用户           |
> feat: Update kratos user import.

- conf/monitor/monitor/monitor.yaml
- conf/monitor/streaming/streaming.yaml
- go.mod
- go.sum
| 🇺🇸 English |        write to clickhouse use round_robin strategy      |
| 🇨🇳 中文    |     采用round_robin的方式写入ck 日志         |
> feat: write to ck use round_robin strategy

- modules/dicehub/extension/db/extension.go
polish: extensionVersion sql
| 🇺🇸 English | polish: extensionVersion sql |
| 🇨🇳 中文    | 优化extensionVersion查询，改为在内存中过滤 |
> fix: polish: extensionVersion sql

- modules/core-services/provider.go
fix: delete dependence of ClusterService in core-services
| 🇺🇸 English | fix: delete dependence of ClusterService in core-services |
| 🇨🇳 中文    | 移除core-services对ClusterService的依赖 |
> fix: delete dependence of ClusterService in core-services

- pkg/parser/pipelineyml/graph_pipelineyml.go
pipeline-yml-graph get `disable` field from frontendAction
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=311710&iterationID=1218&pId=0&type=REQUIREMENT)
| 🇺🇸 English |  pipeline-yml-graph get `disable` field from frontendAction            |
| 🇨🇳 中文    |    pipeline图形解析接口从前端获取是否禁用字段          |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CON …
> feat(pipeline): pipeline-yml-graph get `disable` field from frontendAction

- .github/prlint.json
update pr lint
/assign @sfwn 
| 🇺🇸 English |     update pr lint         |
| 🇨🇳 中文    |      update pr lint        |
> chore: update pr lint

- modules/cluster/cluster-manager/dialer/server/dialer_test.go
- pkg/clusterdialer/dialer.go
- pkg/clusterdialer/dialer_test.go
- pkg/http/customhttp/request.go
- pkg/http/customhttp/request_test.go
fix: add port in cluster manager endpoint
| 🇺🇸 English | fix: add port in cluster manager endpoint  |
| 🇨🇳 中文    | 在dialer包返回的cluster-manager地址后加上端口号 |
> fix: add port in cluster manager endpoint in dialer

- modules/pipeline/precheck/precheck.go
- modules/pipeline/services/pipelinesvc/precheck.go
- modules/pipeline/services/pipelinesvc/precheck_test.go
precheck skip disabled task
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=312808&iterationID=1218&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English | Fix the bug that precheck skip disabled task             |
| 🇨🇳 中文    |  pipeline前置校验跳过禁用任务            |
> fix(pipeline): precheck skip disabled task

- modules/core/openapi-ng/auth/ory-kratos/login_test.go
- pkg/ucauth/user_admin.go
Add redirect url in openapi login.
| 🇺🇸 English |  Add redirect url in openapi login            |
| 🇨🇳 中文    |    重定向地址 openapi 登陆          |
> feat: Add redirect url in openapi login.

- .erda/migrations/cmdb/20220517-audit-deleted-at.sql
- .erda/migrations/config.yml
- modules/core-services/dao/audit.go
- modules/core-services/model/audit.go
Add soft deleted at and index in audit table.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMjE4LDEyNTAsMTIyNF0sImFzc2lnbmVlIjpbIjEwMDEwNzMiXX0%3D&id=312129&iterationID=1218&pId=312099&type=TASK)
| 🇺🇸 English |  Add soft deleted at and index in audit table.            |
| 🇨🇳 中文    |   审计表增加软删除和索引           |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master …
> feat: Add soft deleted at and index in audit table.

- conf/monitor/streaming/index_rollover.json
| 🇺🇸 English |      support rollover es index at max_age       |
| 🇨🇳 中文    |     支持根据max_age滚动es索引         |
> feat: index rollover in max_age

- .erda/pipelines/ci-deploy.yml
add name field for pipeline
| 🇺🇸 English |       add name field for ci       |
| 🇨🇳 中文    |         add name field for ci     |
> ci: add name field for ci

- erda.yml
fix: add replica of cluster-manager
| 🇺🇸 English | fix: add replica of cluster-manager |
| 🇨🇳 中文    | 添加cluster-manager的副本数 |
> fix: add replica of cluster-manager

- .erda/migrations/gittar/20220518-gittar-merge-join-branch-status.sql
gittar merge request table add field join_temp_branch_status
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMjI0LDEyMTgsMTE5MF0sImFzc2lnbmVlIjpbIjEwMDA1NjAiXX0%3D&id=305580&iterationID=1190&pId=0&type=REQUIREMENT)
| 🇺🇸 English |         gittar merge request table add field join_temp_branch_status      |
| 🇨🇳 中文    |      gittar 组件表添加 join_temp_branch_status 字段      |
> feat(dop): gittar merge request table add field join_temp_branch_status

- .erda/migrations/dicehub/20220510-opus.sql
- modules/apps/gallery/handler/funcs.go
- modules/apps/gallery/handler/funcs_test.go
- modules/apps/gallery/handler/gallery.go
fix datetime default value on mysql 8.0
| 🇺🇸 English | fix datetime default value on mysql 8.0 |
| 🇨🇳 中文    | 修复 mysql 8.0 中 datetime 默认值不能为 0 的问题 |
> fix: fix datetime default value on mysql 8.0

- build/dockerfiles/agent-injector/Dockerfile
- erda.yml
fix build monitor agent-injector
| 🇺🇸 English |   fix build monitor agent-injector           |
| 🇨🇳 中文    |   修复了 agent-injector 的编译           |
> fix: build monitor agent-injector

- build/dockerfiles/cluster-agent/Dockerfile
fix build cluster-agent
| 🇺🇸 English |  fix build cluster-agent            |
| 🇨🇳 中文    |   修复了 cluster-agent 的编译          |
> fix: build cluster-agent

- modules/msp/apm/log-service/query/log.service.search.go
/assign @luobily @innerpeacez 
| 🇺🇸 English |      fix: no need limit the query start time bound        |
| 🇨🇳 中文    |         查询上下文日志时不必设置默认起始时间     |
> fix: no need limit the query start time bound

- .gitignore
- Makefile
- adjust prepare step in Makefile
- add cmd bin to .gitignore
| 🇺🇸 English |  polish Makefile            |
| 🇨🇳 中文    |    优化 Makefile          |
> chore: polish Makefile

- apistructs/devflowrule.go
- apistructs/devflowrule_test.go
- modules/dop/providers/devflowrule/devflowrule.service.go
polish devflowrule
| 🇺🇸 English |     devflowrule type adjustment         |
| 🇨🇳 中文    |     研发工作流类型调整        |
> feat(dop): devflowrule type adjustment

- Makefile
Makefile: prepare before tidy
| 🇺🇸 English |  Makefile: prepare before tidy            |
| 🇨🇳 中文    |   Makefile: 在 tidy 前 prepare           |
> fix: Makefile: prepare before tidy

- modules/apps/devflow/flow/flow.service.go
When querying the task workflow, the merged MR is displayed
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=313387&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNTYwIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1218&tab=ALL&type=BUG)
| 🇺🇸 English |       When querying the task workflow, the merged MR is displayed       |
| 🇨🇳 中文    |       查询任务工作流的时候展示已合并的mr       |
> feat(dop): When querying the task workflow, the merged MR is displayed

- modules/apps/gallery/dao/option.go
- modules/apps/gallery/dao/tx.go
- modules/apps/gallery/handler/funcs.go
- modules/apps/gallery/handler/funcs_test.go
- modules/apps/gallery/handler/gallery.go
- modules/apps/gallery/provider.go
fix: i18n render and paging error
| 🇺🇸 English | fix: i18n render and paging error |
| 🇨🇳 中文    | 修复 i18n 渲染错误和翻页数据错误的问题 |
> fix: i18n render and paging error

- modules/pipeline/providers/run/run.go
- pkg/parser/pipelineyml/define.go
- pkg/parser/pipelineyml/define_test.go
Total action count does not include disabled
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMjE4LDExOTBdLCJhc3NpZ25lZSI6WyIxMDAxMjYxIl19&id=313544&iterationID=1218&pId=0&type=TASK)
/assign @sfwn 
| 🇺🇸 English |    Total action count does not include disabled          |
| 🇨🇳 中文    |       action总数统计不包括禁用的      | …
> feat(pipeline): Total action count does not include disabled

- modules/core/monitor/log/persist/v1/consumer.go
- modules/core/monitor/log/persist/v1/consumer_test.go
cassandra logstore compatibility fix
| 🇺🇸 English |      cassandra logstore compatibility fix       |
| 🇨🇳 中文    |       日志写cassandra的兼容性修复       |
> fix: cassandra logstore compatibility fix

- modules/dop/component-protocol/components/release-manage/releaseTable/render.go
fix: hide gallery button
| 🇺🇸 English | fix: hide gallery button |
| 🇨🇳 中文    | 隐藏制品列表中的应用市场按钮 |
> fix: hide gallery button

- cmd/msp/conf/i18n/msp-i18n.yaml
| 🇺🇸 English |     optimize of i18n         |
| 🇨🇳 中文    |        i18n 调整      |
> feat: i18n of tracing module

- modules/messenger/eventbox/subscriber/http/http.go
- modules/messenger/eventbox/subscriber/http/http_test.go
Solve the panic problem
/assign @sfwn 
| 🇺🇸 English |      Solve the panic problem         |
| 🇨🇳 中文    |        解决panic问题      |
> fix(core-services): Solve the panic problem

- modules/dop/component-protocol/components/issue-manage/issueTable/render.go
- modules/dop/services/issuestate/issuestate.go
- modules/dop/services/issuestate/issuestate_test.go
- providers/component-protocol/issueFilter/conditions.go
- providers/component-protocol/issueFilter/in_params.go
- providers/component-protocol/issueFilter/provider.go
Issue type ticket in issue manage scenario.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMjE4LDEyNTAsMTIyNF0sImFzc2lnbmVlIjpbIjEwMDEwNzMiXX0%3D&id=312872&iterationID=1218&pId=309353&type=TASK)
/assign @sfwn 
| 🇺🇸 English |     Issue type ticket in issue manage scenario         |
| 🇨🇳 中文    |  工单页面对接组件化            |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIB …
> feat: Issue type ticket in issue manage scenario.

- cmd/dop/conf/i18n/cp/scenarios/project-runtime.yaml
- modules/dop/component-protocol/components/app-runtime/list/list.go
- modules/dop/component-protocol/components/app-runtime/list/list_test.go
- modules/dop/component-protocol/components/project-runtime/list/list.go
- modules/dop/component-protocol/components/project-runtime/list/list_test.go
feat: check permission in runtime list
| 🇺🇸 English | feat: check permission in runtime list|
| 🇨🇳 中文    | runtime列表鉴权 |
> feat: check permission in runtime list

- pkg/discover/address.go
fix: add erda-server env
| 🇺🇸 English | fix: add erda-server env |
| 🇨🇳 中文    | 添加erda-server服务环境变量 |
> fix: add erda-server env

- modules/core/monitor/log/storage/cassandra/iterator.go
- modules/core/monitor/log/storage/cassandra/iterator_test.go
| 🇺🇸 English |        fix api test query log failed from cassandra      |
| 🇨🇳 中文    |       修复自动化测试查看日志的兼容问题       |
Add comment like `/cherry-pick release/2.1` when this PR is merged.
> fix: fix api test query log failed from cassandra

- modules/dicehub/extension/extention.service.go
- modules/dicehub/extension/extention.service_test.go
fix: skip putting on private extension
| 🇺🇸 English | fix: skip putting on private extension |
| 🇨🇳 中文    | 私有扩展不能上架 |
> fix: skip putting on private extension

- pkg/common/common.go
- pkg/common/common_test.go
- pkg/common/entrance/entrance.go
- pkg/common/entrance/entrance_test.go
- pkg/common/trace/trace.go
fix trace service name
| 🇺🇸 English |   fix trace service name           |
| 🇨🇳 中文    |   修复 trace 服务名异常问题           |
> fix: trace service name

- modules/cmp/component-protocol/components/cmp-dashboard-pods/podsTable/render.go
- modules/cmp/steve/aggregator.go
fix: panic in steve aggregator
| 🇺🇸 English | fix: panic in steve aggregator |
| 🇨🇳 中文    | 修复cmp panic的问题 |
> fix: panic in steve aggregator

- modules/dicehub/extension/extention.service.go
fix: public extension
/assign @sixther-dc @dspo 
| 🇺🇸 English | fix: put on public extension |
| 🇨🇳 中文    |  修复上架私有扩展的问题i  |
> fix: put on public extension

- Makefile
- api/proto-go/Makefile
- api/proto-go/go.mod
- api/proto-go/go.sum
- go.mod
- go.sum
support gen proto-go in local and ci
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=311919&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyI5MiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1218&type=TASK)
| 🇺🇸 English |   support gen proto-go in local and ci           |
| 🇨🇳 中文    |  支持本地和 CI 生成 proto-go 代码            |
> feat: support gen proto-go in local and ci

- pkg/cache/cache.go
- pkg/clusterdialer/dialer.go
- pkg/http/customhttp/request.go
fix: update cache synchronously
/assign @sixther-dc @dspo 
| 🇺🇸 English | fix: update cache synchronously |
| 🇨🇳 中文    | 同步更新缓存 |
> fix: update cache synchronously

- modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/filterContainer/customFilter/condition.go
- modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/filterContainer/customFilter/condition_test.go
- modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/filterContainer/customFilter/condition.go
- modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/filterContainer/customFilter/condition_test.go
- modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/filterContainer/customFilter/provider.go
- modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/filterContainer/customFilter/provider_test.go
remove appCondition and default branch in app pipeline page
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMjUwLDEyMTgsMTI4MF0sImFzc2lnbmVlIjpbIjEwMDEyNjEiXX0%3D&id=315307&iterationID=1218&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |   remove appCondition in app pipeline page           |
| 🇨🇳 中文    |    应用流水线移除app单选框          |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/ma …
> feat(dop): remove appCondition and default branch in app pipeline page

- cmd/monitor/monitor/conf/i18n/alert.yml
- cmd/msp/conf/i18n/cp/msp-notify-list.yaml
- cmd/msp/conf/i18n/msp-i18n.yaml
- modules/core/monitor/metric/meta.go
| 🇺🇸 English | fix Internationalized text error             |
| 🇨🇳 中文    |     修复国家化文本错误         |
> fix: fix Internationalized text error

- modules/core/monitor/log/storage/clickhouse/query_parser/query_parser.go
- modules/core/monitor/log/storage/clickhouse/query_parser/query_parser_test.go
| 🇺🇸 English |        escape sql string      |
| 🇨🇳 中文    |     sql防注入         |
> fix: escape sql string

- modules/core-services/services/security/process.go
Fix project-level app query in app permission.
| 🇺🇸 English | Fix project-level app query in app permission.             |
| 🇨🇳 中文    |  修复应用权限中的 项目级应用查询            |
> fix: Fix project-level app query in app permission.

- cmd/dop/conf/i18n/cp/scenarios/release-manage.yaml
fix: release list i18n
| 🇺🇸 English | fix: release list i18n  |
| 🇨🇳 中文    | 修改制品列表上下架按钮的i国际化文案 |
> fix: release list i18n

- modules/core/monitor/log/storage/elasticsearch/iterator.go
| 🇺🇸 English |       escape es query string       |
| 🇨🇳 中文    |       es query string 转义       |
> fix: escape es query string

- modules/cluster/cluster-manager/dialer/server/dialer_test.go
- modules/cluster/cluster-manager/dialer/server/tunnel-server_test.go
fix: dailer unit test
| 🇺🇸 English | fix: dailer unit test  |
| 🇨🇳 中文    | 修改dialer包的单元测试  |
> fix: dailer unit test

- modules/hepa/apipolicy/policies/sbac/policy.go
- modules/hepa/apipolicy/policies/sbac/policy_test.go
- modules/hepa/services/api_policy/impl/impl.go
- modules/hepa/services/api_policy/impl/register.go
- pkg/cache/cache.go
- pkg/clusterdialer/dialer.go
- pkg/http/customhttp/request.go
feat: sbac policy
| 🇺🇸 English | implement SBAC (ServerBasedAccessControl) policy |
| 🇨🇳 中文    | 实现 SBAC (基于服务的访问控制) 策略 |
> feat(hepa): sbac (Server Based Access Control) policy

- modules/cluster/cluster-manager/dialer/server/dialer_test.go
- modules/cluster/cluster-manager/dialer/server/tunnel-server_test.go
health check before cluster-agent start.
| 🇺🇸 English |   fix(dialer) unit test timeout error           |
| 🇨🇳 中文    |   修复 dialer 单元测试超时错误           |
> fix(dialer): unit test timeout error

- .github/workflows/ci-it-noneed.yml
- .github/workflows/ci-it.yml
- pkg/mimetype/mime_test.go
check codecov.yml for non-go
| 🇺🇸 English |  check codecov.yml for non-go            |
| 🇨🇳 中文    |   检查非 Go 代码变更时的 codecov.yml          |
> chore: check codecov.yml for non-go

- bundle/monitor.go
- cmd/msp/bootstrap.yaml
- cmd/msp/main.go
- modules/core/monitor/alert/alert-apis/audit.go
- modules/core/monitor/alert/alert-apis/audit_test.go
- modules/core/monitor/alert/alert-apis/provider.go
- modules/msp/apm/alert/audit.go
- modules/msp/apm/alert/audit_test.go
- modules/msp/apm/alert/provider.go
- modules/msp/resource/deploy/handlers/monitor/monitor.go
- modules/msp/resource/deploy/handlers/monitor/provider.go
- modules/openapi/api/apis/monitor/monitor_orgs_alert_create.go
- modules/openapi/api/apis/monitor/monitor_orgs_alert_switch.go
- modules/openapi/api/apis/monitor/monitor_orgs_customize_alert_create.go
- modules/openapi/api/apis/monitor/monitor_orgs_customize_alert_switch.go
- modules/openapi/api/apis/msp/apm/alert/apm_alert_create.go
- modules/openapi/api/apis/msp/apm/alert/apm_alert_delete.go
- modules/openapi/api/apis/msp/apm/alert/apm_alert_switch.go
- modules/openapi/api/apis/msp/apm/alert/apm_alert_update.go
- modules/openapi/api/apis/msp/apm/alert/apm_customize_alert_delete.go
- modules/openapi/api/apis/msp/apm/alert/apm_customize_alert_switch.go
- modules/openapi/api/apis/msp/apm/alert/apm_customize_alert_update.go
| 🇺🇸 English |  bundle monitor migration to grpc            |
| 🇨🇳 中文    |   bundle monitor 模块迁移 grpc           |
> feat: bundle monitor migration to grpc

- apistructs/pipeline.go
- modules/dop/component-protocol/components/project-pipeline-exec-list/common/commom.go
- modules/dop/component-protocol/components/project-pipeline-exec-list/common/gshelper/helper.go
- modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/filterContainer/customFilter/condition.go
- modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/filterContainer/customFilter/condition_test.go
- modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/filterContainer/customFilter/provider.go
- modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/pipelineTable/provider.go
- modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/pipelineTable/provider_test.go
- modules/dop/providers/projectpipeline/deftype/list_exec_history.go
- modules/dop/providers/projectpipeline/service_impl.go
- modules/pipeline/dbclient/op_pipeline.go
pipeline exec list support to view all apps in project
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMjI0LDEyNTAsMTIxOF0sImFzc2lnbmVlIjpbIjEwMDEyNjEiXX0%3D&id=315549&iterationID=1250&pId=0&type=TASK)
/assign @sfwn 
| 🇺🇸 English |    pipeline exec list support to view all apps in project          |
| 🇨🇳 中文    |         流水线记录支持查看项目下所有应用     | …
> feat(dop,pipeline): pipeline exec list support to view all apps in project

- apistructs/webhook.go
- bundle/events.go
- modules/dop/initialize.go
- modules/dop/initialize_test.go
delete guide webhook
/assign @sfwn 
| 🇺🇸 English |    delete guide webhook          |
| 🇨🇳 中文    |     删除guide相关webhook         |
> fix(dop): delete guide webhook

- .github/workflows/ci-it-noneed.yml
- .github/workflows/ci-it.yml
- pkg/mimetype/mime_test.go
codecov report cache use search-dir mode
| 🇺🇸 English |   codecov report cache use search-dir mode           |
| 🇨🇳 中文    |   codecov 报告指定目录进行缓存           |
> fix: codecov report cache use search-dir mode

- cmd/dop/conf/i18n/cp/scenarios/project-runtime.yaml
- modules/dop/component-protocol/components/app-runtime/list/list.go
- modules/dop/component-protocol/components/app-runtime/list/list_test.go
- modules/dop/component-protocol/components/project-runtime/list/list.go
- modules/dop/component-protocol/components/project-runtime/list/list_test.go
This reverts commit 390134da2b2084d000175c6e58e9f6c1b60069a3.
| 🇺🇸 English |      revert check permission in runtime list        |
| 🇨🇳 中文    |      回退检查runtime权限校验        |
> fix: revert check permission in runtime list (#4916)

- go.mod
- go.sum
| 🇺🇸 English |      update erda-infra to use optimized kafka-batch-reader        |
| 🇨🇳 中文    |        更新erda-infra依赖，以使用新的kafka-batch-reader     |
> feat: update erda-infra to use optimized kafka-batch-reader

- modules/msp/apm/trace/query/source/clickhouse_source.go
- modules/msp/apm/trace/query/source/clickhouse_source_test.go
| 🇺🇸 English |   trace query bug, missing services name           |
| 🇨🇳 中文    |     链路查询bug，丢失服务名称         |
> fix: trace query bug, missing services name

- modules/pipeline/providers/dbgc/dbgc.go
- modules/pipeline/providers/dbgc/dbgc_test.go
reset time ticker immediately before first dbgc
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=313781&iterationID=-1&pId=0&type=TASK)
/assign @sfwn 
| 🇺🇸 English | reset time ticker immediately before first dbgc             |
| 🇨🇳 中文    |    在第一次dbgc前就重置下次的时间          |
> fix(pipeline): reset time ticker immediately before first dbgc

- modules/msp/apm/checker/plugins/http/provider.go
fix: add logs for httpHandler failure
| 🇺🇸 English | fix: add logs for httpHandler failure  |
| 🇨🇳 中文    | 为http类型的主动监控请求打印错误日志 |
> fix: add logs for httpHandler failure

- modules/cluster/cluster-manager/cluster/cluster.service.go
fix(cluster-manager): list clusters response body error
| 🇺🇸 English | fix list clusters response body error            |
| 🇨🇳 中文    |    修复获取集群列表返回体错误          |
> fix(cluster-manager): list clusters response body error

- modules/msp/apm/service/view/table/transaction.go
| 🇺🇸 English |      fix bug that error-request count error        |
| 🇨🇳 中文    |       修复错误调用次数统计错误的问题       |
> fix: fix error-req count error

- cmd/pipeline/bootstrap.yaml
- cmd/pipeline/main.go
- modules/tools/openapi/legacy/api/apis/runner_scheduler/runner_task_collect_log.go
- modules/tools/openapi/legacy/api/apis/runner_scheduler/runner_task_create.go
- modules/tools/openapi/legacy/api/apis/runner_scheduler/runner_task_fetch.go
- modules/tools/openapi/legacy/api/apis/runner_scheduler/runner_task_get.go
- modules/tools/openapi/legacy/api/apis/runner_scheduler/runner_task_update.go
move action-runner-scheduler to pipeline
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=316432&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1250&type=TASK)
/assign @sfwn 
| 🇺🇸 English | move action-runner-scheduler to pipeline             |
| 🇨🇳 中文    |  action-runner-scheduler 并入 pipeline            |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cher …
> refactor: move action-runner-scheduler to pipeline

- modules/hepa/apipolicy/policies/sbac/policy.go
- modules/hepa/apipolicy/policies/sbac/policy_test.go
fix: zero length pattern in SBAC config
| 🇺🇸 English | fix the problem that Kong response error caused by zero length pattern in SBAC config |
| 🇨🇳 中文    | 修复 SBAC 配置中 patterns 长度为 0 时造成的 Kong 响应错误 |
> fix: zero length pattern in SBAC config

- .github/workflows/ci-it-noneed.yml
- .github/workflows/ci-it.yml
- api/proto/core/pipeline/action/action.proto
trigger go check if proto file changed
| 🇺🇸 English |  trigger go check if proto file changed            |
| 🇨🇳 中文    |  proto 文件变更触发 Go 工作流            |
> feat: trigger go check if proto file changed

- internal/apps/dop/component-protocol/components/release-manage/releaseTable/render.go
- internal/apps/dop/dicehub/release/release.go
fix: upload release
| 🇺🇸 English | fix: upload release |
| 🇨🇳 中文    | 修复上传制品时重复创建应用制品的问题 |
> fix: upload release

- cmd/monitor/monitor/conf/i18n/alert.yml
- cmd/msp/conf/i18n/cp/msp-notify-detail.yaml
cloud manage platform alert module, text optimization
| 🇺🇸 English |   cloud manage platform, text optimization           |
| 🇨🇳 中文    | 云管平台优化文本             |
> feat: globalization text optimization

- apistructs/pipeline_status.go
- internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sjob/error.go
- internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sjob/k8sjob.go
- internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sjob/k8sjob_test.go
- internal/tools/pipeline/providers/reconciler/taskrun/taskop/wait.go
- internal/tools/pipeline/providers/reconciler/taskrun/taskop/wait_test.go
pipeline k8sjob-task collect oomkilled reason
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=311872&iterationID=1250&pId=0&type=REQUIREMENT)
/assign @sfwn 
| 🇺🇸 English |   pipeline k8sjob-task collect oomkilled reason           |
| 🇨🇳 中文    |   流水线对oomkilled的任务展示提醒           |
> feat(pipeline): pipeline k8sjob-task collect oomkilled reason

- api/proto/dop/projectpipeline/projectpipeline.proto
- internal/apps/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/pipelineTable/provider.go
- internal/apps/dop/providers/projectpipeline/service.go
- internal/apps/dop/providers/projectpipeline/service_impl.go
- internal/apps/dop/providers/projectpipeline/service_impl_test.go
- pkg/common/apis/context.go
- pkg/common/apis/header.go
Provide pipeline execution record api
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=316195&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1250&type=TASK)
/assign @sfwn 
| 🇺🇸 English |    Provide pipeline execution record api          |
| 🇨🇳 中文    |    提供流水线执行记录接口          | …
> feat(dop): Provide pipeline execution record api

- cmd/monitor/streaming/bootstrap.yaml
- cmd/monitor/streaming/conf/clickhouse/spans/ddl_create_default_tables.sql.tpl
- internal/apps/msp/apm/trace/span.go
- internal/tools/monitor/oap/collector/core/model/processor.go
- internal/tools/monitor/oap/collector/core/pipeline/pipeline.go
- internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/log/log.go
- internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/metric/metric.go
- internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/provider.go
- internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/span/cache.go
- internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/span/span.go
- internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/span/span_test.go
- internal/tools/monitor/oap/collector/plugins/processors/aggregator/provider.go
- internal/tools/monitor/oap/collector/plugins/processors/k8s-tagger/provider.go
- internal/tools/monitor/oap/collector/plugins/processors/modifier/provider.go
- internal/tools/monitor/oap/collector/plugins/processors/stdout/provider.go
- avoid possible ttl problem with ReplacingMergeTree
- optimize code 
| 🇺🇸 English |       optimize trace storage       |
| 🇨🇳 中文    |      优化trace存储        |
> refactor: optimeze trace storage code

- internal/tools/monitor/core/log/persist/consume.go
- internal/tools/monitor/core/log/persist/consume_test.go
| 🇺🇸 English |         logging, add trace_id tag if missing     |
| 🇨🇳 中文    |        日志添加trace_id标签      |
> fix: logging, add trace_id tag if missing

- codecov.yml
set wait-for-ci to false in codecov
| 🇺🇸 English |  polish codecov            |
| 🇨🇳 中文    |   优化 codecov         |
> chore: set wait-for-ci to false in codecov

- internal/tools/monitor/core/log/query/log.query.service.go
- internal/tools/monitor/core/log/query/routes.go
- internal/tools/monitor/core/log/query/routes_test.go
- internal/tools/monitor/core/log/storage/kubernetes-logs/provider.go
- internal/tools/monitor/core/log/storage/kubernetes-logs/storage.go
- internal/tools/monitor/core/log/storage/kubernetes-logs/storage_test.go
- internal/tools/monitor/core/log/storage/storage.go
| 🇺🇸 English |    log file download support k8s log          |
| 🇨🇳 中文    |    日志文件下载支持直连 k8s          |
> feat: log file download support k8s log

- cmd/monitor/monitor/conf/i18n/charts.yml
CPU Used Percent -> CPU Usage
| 🇺🇸 English |   chart text  optimzation         |
| 🇨🇳 中文    |       图标中文本优化       |
> fix: chart text optimization

- cmd/monitor/streaming/bootstrap.yaml
- internal/apps/msp/apm/trace/query/source/clickhouse_source.go
- internal/apps/msp/apm/trace/query/source/clickhouse_source_test.go
- internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/provider.go
- internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/span/cache.go
- support merge high cardinality tag into tags
| 🇺🇸 English |        merge high cardinality      |
| 🇨🇳 中文    |      合并高基标签        |
> fix: Query support high cardinality

- internal/apps/dop/component-protocol/components/release-manage/releaseTable/render.go
- internal/apps/dop/dicehub/release/release.go
- internal/apps/dop/dicehub/release/release_test.go
fix: cancel query all projects
| 🇺🇸 English | fix: cancel query all projects |
| 🇨🇳 中文    | 删除list release 接口中请求所有项目的逻辑，优化接口速度 |
> fix: cancel query all projects

- api/proto-go/Makefile
- api/proto-go/go.mod
- api/proto-go/go.sum
- go.mod
- go.sum
update gohub
| 🇺🇸 English |   update gohub           |
| 🇨🇳 中文    |  更新 gohub            |
> chore: update gohub

- internal/apps/dop/dicehub/release/release.service.go
- internal/tools/orchestrator/hepa/kong/dto/kong_credential_resp_dto.go
- internal/tools/orchestrator/hepa/kong/dto/kong_credential_resp_dto_test.go
- internal/tools/orchestrator/hepa/kong/v2/kong_adapter.go
fix credentials timestamp error from postgreSQL.
| 🇺🇸 English | fix credentials timestamp error from postgreSQL |
| 🇨🇳 中文    | 修复 psotgreSQL 中 timestamp 位数与 erda 一般习惯不同导致的时间显示错误 |
> feat: created_at timestamp

- bundle/autotest_scene.go
The pipeline aop calls the scenario test adopts Internal-Client verification
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMjgwLDEyOTddLCJhc3NpZ25lZSI6WyIxMDAxMjYxIl19&id=318050&iterationID=1280&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |    The pipeline aop calls the scenario test adopts Internal-Client verification          |
| 🇨🇳 中文    |      pipeline aop调用场景测试采用Internal-Client校验       | …
> fix(pipeline): The pipeline aop calls the scenario test adopts Internal-Client verification

- pkg/parser/pipelineyml/visitor_ref_op.go
- pkg/parser/pipelineyml/visitor_ref_op_test.go
fix ref op wrap quote typo
/assign @sfwn 
| 🇺🇸 English | fix ref op wrap quote typo             |
| 🇨🇳 中文    |    修复parser op的错别字        |
> fix: ref op wrap quote typo

- apistructs/elf.go
- apistructs/pipeline_actions.go
- apistructs/pipeline_task.go
- internal/tools/pipeline/actionagent/callback.go
- internal/tools/pipeline/actionagent/callback_test.go
- internal/tools/pipeline/actionagent/uploaddir.go
- internal/tools/pipeline/pipengine/actionexecutor/plugins/apitest/logic/meta.go
- internal/tools/pipeline/pipengine/pvolumes/cache.go
- internal/tools/pipeline/pipengine/pvolumes/dicefiles.go
- internal/tools/pipeline/pipengine/pvolumes/generate.go
- internal/tools/pipeline/pipengine/pvolumes/workdir.go
- internal/tools/pipeline/providers/reconciler/snippet.go
- internal/tools/pipeline/providers/reconciler/task_reconciler_test.go
- internal/tools/pipeline/providers/reconciler/taskrun/taskop/prepare.go
- internal/tools/pipeline/providers/reconciler/taskrun/taskop/prepare_test.go
- internal/tools/pipeline/services/pipelinesvc/callback.go
- internal/tools/pipeline/services/pipelinesvc/detail.go
- internal/tools/pipeline/spec/pipeline_extra.go
- internal/tools/pipeline/spec/pipeline_task.go
- internal/tools/pipeline/spec/pipeline_task_test.go
- pkg/metadata/metadata.go
- pkg/metadata/metadata_test.go
- pkg/parser/pipelineyml/pipelineymlv1/evaluate.go
- pkg/parser/pipelineyml/pipelineymlv1/options.go
- pkg/parser/pipelineyml/pipelineymlv1/pipelineyml.go
- pkg/parser/pipelineyml/pipelineymlv1/pipelineyml_test.go
- pkg/parser/pipelineyml/pipelineymlv1/util.go
- pkg/parser/pipelineyml/pipelineymlv1/util_test.go
- pkg/syncmap/string_interface_map_test.go
make metadata as a pkg
| 🇺🇸 English |  make metadata as a pkg            |
| 🇨🇳 中文    |  将 metadata 抽为 pkg             |
> refactor: make metadata as a pkg

- codecov.yml
polish codecov ignore rule
| 🇺🇸 English |   polish codecov ignore rule           |
| 🇨🇳 中文    |   修改 codecov ignore rule           |
> chore: polish codecov ignore rule

- internal/apps/dop/providers/devflowrule/provider.go
add service register to devflowrule
/assign #sfwn
| 🇺🇸 English |    register devflowrule service          |
| 🇨🇳 中文    |      注册 devflowrule 服务        |
> fix(dop): register devflowrule service

- cmd/monitor/streaming/conf/clickhouse/spans/ddl_create_default_tables.sql.tpl
- internal/apps/msp/apm/trace/query/source/clickhouse_source.go
- internal/apps/msp/apm/trace/query/source/source.go
- internal/apps/msp/apm/trace/query/source/source_test.go
optimize order by(primary key) and sql
| 🇺🇸 English |       optimize trace query       |
| 🇨🇳 中文    |      优化trace查询性能        |
> refactor: Optimize distribute

- cmd/monitor/streaming/conf/clickhouse/spans/ddl_create_default_tables.sql.tpl
- internal/apps/msp/apm/trace/query/source/clickhouse_source.go
- internal/apps/msp/apm/trace/query/source/source.go
- internal/apps/msp/apm/trace/query/source/source_test.go
cherry-pick of : https://github.com/erda-project/erda/pull/5064
| 🇺🇸 English |      cherry-pick        |
| 🇨🇳 中文    |      cherry-pick        |
> refactor: cherry-pick tracing optimize

- apistructs/pipeline_actions.go
- apistructs/pipeline_task.go
- internal/apps/cmp/impl/clusters/add_edge_cluster.go
- internal/tools/pipeline/actionagent/define.go
- internal/tools/pipeline/dbclient/op_pipeline_task.go
- internal/tools/pipeline/events/event_task.go
- internal/tools/pipeline/pkg/taskerror/err.go
- internal/tools/pipeline/pkg/taskerror/err_test.go
- internal/tools/pipeline/pkg/taskerror/ordered.go
- internal/tools/pipeline/pkg/taskerror/ordered_test.go
- internal/tools/pipeline/pkg/taskinspect/inspect.go
- internal/tools/pipeline/pkg/taskinspect/inspect_test.go
- internal/tools/pipeline/pkg/taskresult/result.go
- internal/tools/pipeline/providers/reconciler/snippet.go
- internal/tools/pipeline/providers/reconciler/snippet_test.go
- internal/tools/pipeline/providers/reconciler/task_reconciler.go
- internal/tools/pipeline/providers/reconciler/task_reconciler_test.go
- internal/tools/pipeline/providers/reconciler/taskrun/framework.go
- internal/tools/pipeline/providers/reconciler/taskrun/framework_test.go
- internal/tools/pipeline/providers/reconciler/taskrun/taskop/prepare.go
- internal/tools/pipeline/providers/reconciler/taskrun/update.go
- internal/tools/pipeline/services/pipelinesvc/callback.go
- internal/tools/pipeline/services/pipelinesvc/callback_test.go
- internal/tools/pipeline/services/pipelinesvc/detail.go
- internal/tools/pipeline/spec/pipeline_task.go
- internal/tools/pipeline/spec/pipeline_task_test.go
task.result for external use, task.inspect for internal use
| 🇺🇸 English |  adjust task result & inspect            |
| 🇨🇳 中文    |   调整 task 的 result 和 inspect 字段           |
> refactor: task.result for external use, task.inspect for internal use

- internal/tools/pipeline/providers/reconciler/taskrun/framework.go
- internal/tools/pipeline/providers/reconciler/taskrun/update.go
do not  fetch latest task from db at reconcile side
tested and works fine
| 🇺🇸 English |   do not  fetch latest task from db at reconcile side           |
| 🇨🇳 中文    |   在 pipeline reconciler 侧不从数据库获取最新任务           |
> feat(pipeline): do not  fetch latest task from db at reconcile side

- cmd/erda-server/bootstrap.yaml
- cmd/erda-server/main.go
- cmd/orchestrator/bootstrap.yaml
- cmd/orchestrator/main.go
- internal/apps/admin/personal-workbench/provider.go
- internal/apps/admin/personal-workbench/services/workbench/project.go
- internal/apps/admin/personal-workbench/services/workbench/workbench.go
- internal/apps/dop/component-protocol/components/release-manage/releaseTable/render.go
- internal/tools/orchestrator/hepa/providers/global/provider.go
- internal/tools/orchestrator/hepa/services/global/impl/impl.go
- internal/tools/orchestrator/initialize.go
- internal/tools/orchestrator/provider.go
- internal/tools/orchestrator/services/addon/addon.go
- internal/tools/orchestrator/services/addon/addon_handler.go
refactor: use grpc for msp tenant
/assign @sixther-dc @snakorse 
| 🇺🇸 English | refactor: use grpc for msp tenant |
| 🇨🇳 中文    | 将msp tenant的bundle调用改为grpc调用 |
> refactor: use grpc for msp tenant

- modules/pipeline/pipengine/reconciler/listen.go
- modules/pipeline/pipengine/reconciler/teardown.go
reconciler dowatch-func memory leak
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that .reconciler dowatch-func memory leak            |
| 🇨🇳 中文    |     修复了reconciler内存泄露         |
> fix: reconciler dowatch-func memory leak

- cmd/msp/bootstrap.yaml
- cmd/msp/main.go
fix: remove msp general ability
| 🇺🇸 English | fix: remove msp general ability |
| 🇨🇳 中文    | 删除msp的general ability相关代码以解除msp对dicehub的依赖  |
> fix: remove msp general ability

- internal/tools/monitor/core/diagnotor/controller/diagnotor.service.go
- internal/tools/monitor/core/diagnotor/controller/schedule.go
- pkg/k8s-client-manager/provider.go
k8s-client-manager interface fix
/assign @sixther-dc @tomatopunk 
| 🇺🇸 English | k8s-client-manager interface caller error          |
| 🇨🇳 中文    |    修复 k8s-client-manager    调用错误      |
> fix(pkg): k8s-client-manager interface caller error

- internal/core/legacy/dao/application.go
- internal/core/legacy/dao/member.go
- internal/core/legacy/services/project/project.go
- internal/core/legacy/services/project/project_test.go
Add batch convert project, optimize project list query.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMjg2LDEyOTcsMTI4MCwxMjUwLDEyMjQsMTIxOCwxMTkwXSwiYXNzaWduZWUiOlsiMTAwMTA3MyJdfQ%3D%3D&id=317965&iterationID=1280&pId=0&type=TASK)
/assign @sfwn 
| 🇺🇸 English |   Add batch convert project, optimize project list query.           |
| 🇨🇳 中文    |      优化项目列表查询        | …
> feat: Add batch convert project, optimize project list query.

- cmd/hepa/bootstrap.yaml
- cmd/hepa/main.go
fix: add tenantService in hepa
| 🇺🇸 English | fix: add tenantService in hepa |
| 🇨🇳 中文    | 为hepa添加tenantService依赖 |
> fix: add tenantService in hepa

- internal/apps/dop/component-protocol/components/issue-manage/issueTable/props.go
- internal/apps/dop/component-protocol/components/issue-manage/issueTable/props_test.go
- internal/apps/dop/providers/issue/core/provider.go
- internal/apps/dop/providers/issue/core/service.go
- internal/apps/dop/providers/issue/stream/common/model.go
- internal/apps/dop/providers/issue/stream/core/build.go
- internal/apps/dop/providers/issue/stream/core/event.go
- internal/apps/dop/providers/issue/stream/core/provider.go
Fix issue stream uc client, reorder issue table columns, code refactor.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMjg2LDEyOTcsMTI4MCwxMjUwLDEyMjQsMTIxOCwxMTkwXSwiYXNzaWduZWUiOlsiMTAwMTA3MyJdfQ%3D%3D&id=319370&iterationID=1280&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English | Fix issue stream uc client, reorder issue table columns, code refactor.             |
| 🇨🇳 中文    |     修复事项流uc客户端         | …
> fix: Fix issue stream uc client, reorder issue table columns, code refactor.

- pipeline.yml
adjust custom script cpu request
| 🇺🇸 English |   adjust custom script cpu request           |
| 🇨🇳 中文    |    调整自定义及脚本 cpu 请求值          |
> fix(pipeline): adjust custom script cpu request

- internal/apps/devflow/flow/flow.service.go
Resolve permission issues
| 🇺🇸 English |     Resolve permission issues         |
| 🇨🇳 中文    |      解决权限问题        |
> fix(dop): Resolve permission issues

- internal/apps/devflow/flow/flow.service.go
- internal/tools/gittar/api/merge.go
gittar: Branch merge send event
dop: Only the default pipeline is supported
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMjgwXSwiYXNzaWduZWUiOlsiMTAwMTI2MSJdfQ%3D%3D&id=319010&iterationID=1280&pId=0&type=BUG)
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMjgwXSwiYXNzaWduZWUiOlsiMTAwMTI2MSJdfQ%3D%3D&id=319063&iterationID=1280&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |     fix some bug of dev work flow         |
| 🇨🇳 中文    |      解决研发工作流的一些缺陷        |
> For details on the cherry pick process, …
> fix(dop,gittar): fix some bug of dev work flow

- api/proto/dop/issue/core/core.proto
- internal/apps/dop/providers/issue/core/property.go
- internal/apps/dop/providers/issue/core/query/property.go
- internal/pkg/component-protocol/issueFilter/in_params.go
Fix issue type ticket and property instance convert.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMjg2LDEyOTcsMTI4MCwxMjUwLDEyMjQsMTIxOCwxMTkwXSwiYXNzaWduZWUiOlsiMTAwMTA3MyJdfQ%3D%3D&id=319873&iterationID=1280&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English | Fix issue type ticket and property instance convert.             |
| 🇨🇳 中文    |   修复工单和自定义字段           |
release/2.2 …
> fix: Fix issue type ticket and property instance convert.

- .github/workflows/ci-it.yml
- api/proto-go/build.sh
cleanup generated proto-go code when dir structure adjusted
| 🇺🇸 English |   cleanup generated proto-go code when dir structure adjusted           |
| 🇨🇳 中文    |   修复 proto 文件目录结构调整后可能无法删除生成的 proto-go 代码的问题           |
> fix(proto-go): cleanup generated proto-go code when dir structure adjusted

- internal/apps/devflow/flow/flow.service.go
- internal/apps/dop/providers/devflowrule/db/define.go
- internal/apps/dop/providers/devflowrule/devflowrule.service.go
- internal/apps/dop/providers/devflowrule/devflowrule.service_test.go
Handling some special cases and bugs of R&D workflow
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMjgwLDEyOTddLCJhc3NpZ25lZSI6WyIxMDAxMjYxIl19&id=319990&iterationID=1280&pId=0&type=BUG)
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMjgwLDEyOTddLCJhc3NpZ25lZSI6WyIxMDAxMjYxIl19&id=319305&iterationID=1280&pId=0&type=BUG)
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMjgwLDEyOTddLCJhc3NpZ25lZSI6WyIxMDAxMjYxIl19&id=319111&iterationID=1280&pId=0&type=BUG)
/assign @sfwn
| 🇺🇸 English | …
> fix(dop): Handling some special cases and bugs of R&D workflow

- internal/apps/dop/providers/issue/core/provider.go
- internal/apps/dop/providers/issue/core/provider_test.go
- internal/apps/dop/providers/issue/core/query/button.go
- internal/apps/dop/providers/issue/dao/core.go
- internal/apps/dop/providers/issue/stream/core/template.go
- internal/apps/dop/providers/issue/stream/core/template_test.go
- internal/apps/dop/providers/issue/stream/service.go
Fix issue mr relation, issue stream, get next issue state.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMjk3LDEyODYsMTI4MCwxMjUwXSwiYXNzaWduZWUiOlsiMTAwMTA3MyJdfQ%3D%3D&id=320240&iterationID=1280&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |  Fix issue mr relation, issue stream, get next issue state.            |
| 🇨🇳 中文    |     修复事项日志 和获取下一个状态         |
release/2.2 …
> fix: Fix issue mr relation, issue stream, get next issue state.

- api/proto/pkg/dingtalktest/dingtalktest.proto
add missing service in proto of dingtalktest
| 🇺🇸 English |  add missing service in proto of dingtalktest            |
| 🇨🇳 中文    |  dingtalktest 的 proto 增加 openapi service 字段用于转发            |
> fix(proto): add missing service in proto of dingtalktest

- internal/apps/admin/personal-workbench/component-protocol/components/personal-workbench/common/common.go
- internal/apps/admin/personal-workbench/component-protocol/components/personal-workbench/workCards/provider.go
- internal/apps/admin/personal-workbench/component-protocol/components/personal-workbench/workList/project.go
- internal/apps/admin/personal-workbench/component-protocol/components/personal-workbench/workList/provider.go
Update work bench msp project target.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMjk3LDEyODYsMTI4MCwxMjUwXSwiYXNzaWduZWUiOlsiMTAwMTA3MyJdfQ%3D%3D&id=318743&iterationID=1280&pId=0&type=BUG)
| 🇺🇸 English |   Update work bench msp project target.           |
| 🇨🇳 中文    |    更新个人工作台msp项目链接          |
release/2.2
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/mas …
> fix: Update work bench msp project target.

- api/proto/dop/projectpipeline/projectpipeline.proto
- internal/apps/dop/providers/projectpipeline/service_impl.go
- internal/apps/dop/providers/projectpipeline/service_impl_test.go
Pipeline execution records support branch filtering
/assign @sfwn 
| 🇺🇸 English |    Pipeline execution records support branch filtering          |
| 🇨🇳 中文    |        流水线执行记录支持分支过滤      |
> feat(dop): Pipeline execution records support branch filtering

- internal/apps/dop/component-protocol/components/issue-gantt/gantt/render.go
- internal/apps/dop/providers/issue/core/relation.go
- internal/apps/dop/providers/issue/core/relation_test.go
Issue inclusion supports issue type bug.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMjg2LDEyOTcsMTI4MCwxMjUwLDEyMjQsMTIxOCwxMTkwXSwiYXNzaWduZWUiOlsiMTAwMTA3MyJdfQ%3D%3D&id=318510&iterationID=1280&pId=311469&type=TASK)
/assign @sfwn 
| 🇺🇸 English |  Issue inclusion supports issue type bug.            |
| 🇨🇳 中文    |    TodoList 中支持缺陷的添加和关联          | …
> feat: Issue inclusion supports issue type bug.

- internal/tools/pipeline/actionagent/define.go
- internal/tools/pipeline/actionagent/openapi.go
- internal/tools/pipeline/actionagent/openapi_test.go
- internal/tools/pipeline/actionagent/step_validate.go
- internal/tools/pipeline/actionagent/step_validate_test.go
- internal/tools/pipeline/pipengine/pvolumes/mesos.go
- internal/tools/pipeline/pkg/env/envs.go
- internal/tools/pipeline/pkg/env/envs_test.go
- internal/tools/pipeline/providers/edgepipeline_register/provider.go
- internal/tools/pipeline/providers/reconciler/taskrun/taskop/prepare.go
move common pipeline env to pkg
/assign @sfwn 
| 🇺🇸 English |   move common pipeline env to pkg           |
| 🇨🇳 中文    |     流水线env定义和公共函数移动到pkg         |
> refactor: move common pipeline env to pkg

- apistructs/pipeline_task.go
- internal/tools/pipeline/services/pipelinesvc/detail.go
- internal/tools/pipeline/spec/pipeline_task.go
- internal/tools/pipeline/spec/pipeline_task_test.go
pipeline display task param detail
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=318516&iterationID=1280&pId=317574&type=TASK)
/assign @sfwn 
| 🇺🇸 English |    pipeline display task param detail           |
| 🇨🇳 中文    |      流水线详情展示任务详细参数        |
> feat: pipeline display task param detail

- internal/apps/dop/providers/guide/provider.go
Cancel the scheduled task of the guide
/assign @sfwn 
| 🇺🇸 English |      Cancel the scheduled task of the guide        |
| 🇨🇳 中文    |      取消guide的定时任务        |
> fix(dop): Cancel the scheduled task of the guide

- internal/apps/dop/component-protocol/components/issue-dashboard/common/stackhandlers/complexity.go
- internal/apps/dop/component-protocol/components/issue-dashboard/common/stackhandlers/priority.go
- internal/apps/dop/component-protocol/components/issue-dashboard/common/stackhandlers/severity.go
- internal/apps/dop/component-protocol/components/issue-dashboard/common/stackhandlers/stage.go
Fix issue dashboard issue model import.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMjk3LDEyODYsMTI4MCwxMjUwLDEzMjFdLCJhc3NpZ25lZSI6WyIxMDAxMDczIl19&id=321432&iterationID=1297&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |  Fix issue dashboard issue model import.            |
| 🇨🇳 中文    |   修复缺陷统计           |
2.2
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUT …
> fix: Fix issue dashboard issue model import.

- go.mod
- go.sum
- internal/apps/msp/apm/log-service/analysis/processors/regex/regex.go
fix: use regexp2
| 🇺🇸 English | fix: use regexp2 |
| 🇨🇳 中文    | 在日志分析中使用 regexp2 正则库 |
> fix: use regexp2

- internal/core/legacy/endpoints/application.go
- internal/core/legacy/endpoints/application_test.go
- internal/core/legacy/endpoints/mock_org_test.go
- internal/core/legacy/endpoints/notify.go
- internal/core/legacy/initialize.go
- internal/core/org/org.service.go
- internal/core/org/provider.go
Solve the problem of getting org without permission
/assign @sfwn 
| 🇺🇸 English |       Solve the problem of getting org without permission       |
| 🇨🇳 中文    |        解决获取org无权限问题      |
> fix(dop): Solve the problem of getting org without permission

- apistructs/k8s.go
- erda.yml
- internal/tools/orchestrator/conf/conf.go
- internal/tools/orchestrator/scheduler/executor/plugins/k8s/deployment.go
- internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s.go
- internal/tools/orchestrator/scheduler/executor/plugins/k8s/namespace.go
- internal/tools/orchestrator/scheduler/executor/plugins/k8s/secret.go
- internal/tools/orchestrator/scheduler/executor/plugins/k8s/secret_test.go
- internal/tools/orchestrator/scheduler/executor/plugins/k8s/type.go
- internal/tools/pipeline/conf/conf.go
- internal/tools/pipeline/pipengine/actionexecutor/logic/secret.go
- internal/tools/pipeline/pipengine/actionexecutor/logic/secret_test.go
- internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sflink/flink.go
- internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sflink/util.go
- internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sjob/k8sjob.go
- internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sjob/k8sjob_test.go
- internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sspark/k8sspark.go
- internal/tools/volume-provisioner/deploy/all-in-one.yaml
custom registry credential
| 🇺🇸 English |    custom registry credential secret name        |
| 🇨🇳 中文    |      自定义镜像认证 secret  名称        |
> feat(orchestrator,pipeline): custom registry credential secret name

- api/proto/apps/devflow/flow/flow.proto
- internal/apps/devflow/flow/flow.service.go
devFlowNode add mergeRequestInfo
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=311484&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1297&tab=REQUIREMENT&type=REQUIREMENT)
/assign @littlejiancc 
| 🇺🇸 English |    devFlowNode add mergeRequestInfo          |
| 🇨🇳 中文    |   devFlowNode 增加合并请求信息           |
> feat(devflow): devFlowNode add mergeRequestInfo

- internal/tools/openapi/legacy/api/generate/generate_proto.go
- internal/tools/openapi/legacy/api/generate/generate_proto_test.go
polish code to gen openapiv1 proto
| 🇺🇸 English |   polish code to gen openapiv1 proto           |
| 🇨🇳 中文    |    优化 openapiv1 protobuf 生成器的代码          |
> chore: polish code to gen openapiv1 proto

- internal/tools/openapi/legacy/api/apis/presale_survey.go
- internal/tools/openapi/legacy/api/apis/presale_survey_test.go
survey check required fields
| 🇺🇸 English |   survey check required fields           |
| 🇨🇳 中文    |  survery 接口检查必填字段            |
> feat(openapi): survey check required fields

- internal/apps/dop/component-protocol/components/test-dashboard/overview_group/quality_chart/render.go
- internal/apps/dop/component-protocol/components/test-dashboard/overview_group/quality_chart/render_test.go
- internal/apps/dop/component-protocol/types/const.go
- internal/apps/dop/initialize.go
- internal/apps/dop/providers/issue/core/service.go
- internal/apps/dop/providers/issue/core/service_test.go
- internal/apps/dop/providers/issue/dao/core.go
Fix bug count query, excludes deleted issues.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMjg2LDEyOTcsMTI4MF0sImFzc2lnbmVlIjpbIjEwMDEwNzMiXX0%3D&id=318489&iterationID=1297&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |   Fix bug count query, excludes deleted issues.           |
| 🇨🇳 中文    |   未关闭缺陷的质量分数需要将删除的缺陷过滤一下           |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/ma …
> fix: Fix bug count query, excludes deleted issues.

- apistructs/extension_test.go
- apistructs/extention.go
- apistructs/pipeline_dto.go
- apistructs/pipeline_task.go
- internal/tools/pipeline/services/pipelinesvc/detail.go
pipeline detail display action spec
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=317574&iterationID=1297&pId=0&type=REQUIREMENT)
/assign @sfwn 
| 🇺🇸 English |   pipeline detail display action spec           |
| 🇨🇳 中文    |     流水线详情展示action具体信息         |
> feat(pipeline): pipeline detail display action spec

- internal/tools/orchestrator/scheduler/executor/plugins/k8s/event/event.go
- internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s.go
optimize pod event watcher
| 🇺🇸 English | optimize pod event watcher             |
| 🇨🇳 中文    |   优化  Pod 事件 watch           |
> feat(orchestrator): optimize pod event watcher

- .erda/migrations/dop/20220628-devflowrule-migrations.py
update py script of devflowrule
/assign @sfwn 
| 🇺🇸 English |     update py script of devflowrule         |
| 🇨🇳 中文    |       修改 devflowrule sql 脚本       |
> fix: update py script of devflowrule

- internal/tools/monitor/oap/collector/plugins/exporters/kafka/provider.go
- internal/tools/monitor/oap/collector/plugins/exporters/kafka/provider_test.go
kafka v2 write fix
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAwMzAxIl19&id=322734&iterationID=1297&pId=0&type=BUG)
| 🇺🇸 English |        kafka write bugfix      |
| 🇨🇳 中文    |       kafka write bugfix        |
> fix: kafka write bugfix

- api/proto/msp/apm/log-service/log_query.proto
- internal/apps/msp/apm/log-service/query/log.service.go
- internal/apps/msp/apm/log-service/query/log.service_test.go
feat: add parse regexp
| 🇺🇸 English | feat: add parse regexp |
| 🇨🇳 中文    |  为日志分析添加解析正则表达式接口  |
> feat: add parse regexp

- api/proto/msp/apm/log-service/log_query.proto
add service field in parse-regexp interface
| 🇺🇸 English | add service field in parse-regexp interface |
| 🇨🇳 中文    |  在 parse-regexp proto描述中添加 service 字段 |
> fix: add service field

- api/proto/apps/devflow/flow/flow.proto
- internal/apps/devflow/flow/flow.service.go
- internal/apps/dop/services/branchrule/branch_rule.go
add flowRuleName field to info
add tempBranch to brach rule
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMjk3XSwiYXNzaWduZWUiOlsiMTAwMTI2MSJdfQ%3D%3D&id=323652&iterationID=1297&pId=0&type=BUG)
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMjk3XSwiYXNzaWduZWUiOlsiMTAwMTI2MSJdfQ%3D%3D&id=323581&iterationID=1297&pId=0&type=TASK)
/assign @sfwn 
| 🇺🇸 English |     add devFlowRuleName to info and add tempBranch to brach rule         |
| 🇨🇳 中文    |   增加`devFlowRuleName`字段，分支规则带上临时分支           |
> For …
> feat(dop): add devFlowRuleName to info and add tempBranch to brach rule

- cmd/cluster-manager/bootstrap.yaml
- cmd/cmp/bootstrap.yaml
- cmd/dicehub/bootstrap.yaml
- cmd/dop/bootstrap.yaml
- cmd/erda-server/bootstrap.yaml
- cmd/erda-server/main.go
- cmd/msp/bootstrap.yaml
fix erda-server
/assign @littlejiancc 
| 🇺🇸 English |   fix erda-server           |
| 🇨🇳 中文    |   修复 erda-server           |
> fix: fix erda-server

- api/proto/msp/apm/log-service/log_query.proto
fix: add auth for log_query
| 🇺🇸 English | fix: add auth for log_query |
| 🇨🇳 中文    | 修复parse-regexp接口报401的问题  |
> fix: add auth for log_query

- cmd/msp/bootstrap.yaml
| 🇺🇸 English |       config adjust       |
| 🇨🇳 中文    |       配置调整       |
> fix: spans from cassandra as default

- internal/tools/monitor/core/log/query/log.query.service.go
fix: remove tags.dice_cluster_name when query logs
| 🇺🇸 English | fix: remove tags.dice_cluster_name when query logs |
| 🇨🇳 中文    | 删除查询日志时的dice_cluster_name tag |
> fix: remove tags.dice_cluster_name when query logs

- erda.yml
remove custom registry credential
| 🇺🇸 English |   remove custom registry credential           |
| 🇨🇳 中文    |     移除自定义 registry 认证         |
> feat: remove custom registry credential

- internal/apps/admin/manager/cluster.go
- internal/apps/admin/provider.go
- internal/apps/dop/endpoints/organization.go
- internal/apps/dop/endpoints/organization_test.go
Fix bugs caused by org refactoring
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMjk3XSwiYXNzaWduZWUiOlsiMTAwMTI2MSJdfQ%3D%3D&id=324191&iterationID=1297&pId=0&type=BUG)
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMjk3XSwiYXNzaWduZWUiOlsiMTAwMTI2MSJdfQ%3D%3D&id=324092&iterationID=1297&pId=0&type=BUG)
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMjk3XSwiYXNzaWduZWUiOlsiMTAwMTI2MSJdfQ%3D%3D&id=324089&iterationID=1297&pId=0&type=BUG)
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb2 …
> fix(dop): Fix bugs caused by org refactoring

- erda.yml
update erda-server resource for daily env
| 🇺🇸 English |   update erda-server resource for daily env           |
| 🇨🇳 中文    |   更新 erda-server 在集成环境的资源           |
> chore: update erda-server resource for daily env

- internal/apps/msp/apm/log-service/analysis/processors/regex/regex.go
fix: test log rule error
| 🇺🇸 English |  fix: test log rule error |
| 🇨🇳 中文    |  修复测试日志规则报错的问题  |
> fix: test log rule error

- internal/apps/devflow/flow/flow.service.go
- internal/apps/devflow/flow/flow.service_test.go
- internal/apps/devflow/flow/mock_devflowRule.go
tempBranch checkout from sourceBranch
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMjk3XSwiYXNzaWduZWUiOlsiMTAwMTI2MSJdfQ%3D%3D&id=324669&iterationID=1297&pId=0&type=BUG)
/assign @sfwn
| 🇺🇸 English |      tempBranch checkout from sourceBranch         |
| 🇨🇳 中文    |       临时分支从源分支切出       |
> fix(dop): tempBranch checkout from sourceBranch

- internal/apps/dop/component-protocol/components/app-list-all/list/provider.go
- internal/apps/dop/component-protocol/components/app-list-all/list/provider_test.go
Fix Public app click operation authorized.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMjk3LDEyODYsMTI4MCwxMjUwLDEzMjFdLCJhc3NpZ25lZSI6WyIxMDAxMDczIl19&id=324045&iterationID=1297&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |  Fix Public app click operation authorized.            |
| 🇨🇳 中文    |   修复公开应用无权限           |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONT …
> fix: Fix Public app click operation authorized.

- internal/apps/admin/manager/manager.go
- internal/apps/dop/dicehub/release/provider.go
- internal/apps/dop/dicehub/release/release.service.go
- internal/apps/dop/dicehub/release/release.service_test.go
- internal/apps/gallery/cache/provider.go
- internal/pkg/mock/mock_org.go
use org.Interface at erda-server side
| 🇺🇸 English |   use org.Interface at erda-server side           |
| 🇨🇳 中文    |  erda-server 里使用 org.Interface 进行注入           |
> fix: use org.Interface at erda-server side

- cmd/monitor/monitor/bootstrap.yaml
- cmd/monitor/streaming/bootstrap.yaml
- cmd/msp/bootstrap.yaml
fix: add cache_key_prefix in clickhouse table loader config
| 🇺🇸 English | fix: add cache_key_prefix in clickhouse table loader config |
| 🇨🇳 中文    | 解决容器日志、日志分析时有时无的问题  |
> fix: add cache_key_prefix in clickhouse table loader config

- internal/apps/msp/apm/trace/query/source/clickhouse_source.go
fix query by start_time with skewing
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAwMzAxIl19&id=324777&iterationID=1297&pId=0&type=BUG)
| 🇺🇸 English |       span query fix       |
| 🇨🇳 中文    |      span查询修复        |
> fix: add proper skewing timing

- cmd/monitor/collector/bootstrap-agent.yaml
- cmd/monitor/collector/bootstrap.yaml
- erda.yml
- internal/tools/monitor/oap/collector/plugins/receivers/collector/post.http
- internal/tools/monitor/oap/collector/plugins/receivers/collector/provider.go
- internal/tools/monitor/oap/collector/plugins/receivers/collector/provider_test.go
agent collector config fix
| 🇺🇸 English |      collector config fix        |
| 🇨🇳 中文    |       collector配置修改       |
> fix: collector agent config fix

- bundle/org.go
- bundle/org_test.go
check idOrName for org bundle
| 🇺🇸 English |    check idOrName for org bundle          |
| 🇨🇳 中文    |   检查 org bundle 的 idOrName 参数           |
> feat: check idOrName for org bundle

- internal/apps/dop/dicehub/endpoints/endpoints.go
- internal/apps/dop/dicehub/provider.go
use org.Interface in dicehub
/assign @sfwn 
| 🇺🇸 English |    use org.Interface in erda-server          |
| 🇨🇳 中文    |      erda-server 里使用 org.Interface 进行注入        |
> fix(erda-server): use org.Interface in erda-server

- cmd/msp/bootstrap.yaml
- erda.yml
- internal/apps/msp/apm/trace/query/source/clickhouse_source.go
- internal/apps/msp/apm/trace/query/source/clickhouse_source_test.go
- internal/tools/monitor/oap/collector/plugins/exporters/collector/provider.go
- pipeline.yml
get span count bugfix
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAwMzAxIl19&id=324694&iterationID=1297&pId=0&type=BUG)
| 🇺🇸 English |      get span count bugfix        |
| 🇨🇳 中文    |      获取span数量bugfix        |
> fix: get span count fix

- cmd/pipeline/bootstrap.yaml
- internal/tools/pipeline/endpoints/v2_test.go
- internal/tools/pipeline/providers/edgereporter/mock.go
- internal/tools/pipeline/services/pipelinesvc/create_v2.go
- internal/tools/pipeline/services/pipelinesvc/create_v2_test.go
pipeline benchmark test of reconciler and queuemanager
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=318513&iterationID=-1&pId=0&type=TASK)
/assign @sfwn 
| 🇺🇸 English |    pipeline benchmark test of reconciler and queuemanager          |
| 🇨🇳 中文    |      pipeline推进压测用例        |
> feat: pipeline benchmark test of reconciler and queuemanager

- build/dockerfiles/cluster-agent/Dockerfile
- pipeline.yml
fix build image of cluster-agent
| 🇺🇸 English |    fix build image of cluster-agent          |
| 🇨🇳 中文    |   修复 cluster-agent 的镜像编译           |
> chore: fix build image of cluster-agent

- apistructs/pipeline.go
- internal/tools/pipeline/dbclient/op_pipeline.go
- internal/tools/pipeline/dbclient/op_pipeline_test.go
- internal/tools/pipeline/providers/dbgc/dbgc.go
- internal/tools/pipeline/providers/dbgc/dbgc_test.go
use batched queries instead of loading full data in dbgc
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=325245&iterationID=1321&pId=0&type=TASK)
/assign @sfwn 
| 🇺🇸 English |    Fix the bug that use batched queries instead of loading full data in dbgc          |
| 🇨🇳 中文    |      修复dbgc占用大量内存        |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTIN …
> fix(pipeline): use batched queries instead of loading full data in dbgc

- api/proto/dop/projectpipeline/projectpipeline.proto
- apistructs/pipeline.go
- internal/apps/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/pipelineTable/provider.go
- internal/apps/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/pipelineTable/provider_test.go
- internal/apps/dop/providers/projectpipeline/service_impl.go
- internal/tools/pipeline/dbclient/op_pipeline.go
Fix time zone issues
Fix the execution history issues
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMzIxXSwiYXNzaWduZWUiOlsiMTAwMTI2MSJdfQ%3D%3D&id=321543&iterationID=1321&pId=0&type=BUG)
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMzIxXSwiYXNzaWduZWUiOlsiMTAwMTI2MSJdfQ%3D%3D&id=325652&iterationID=1321&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |      Fix bugs in project pipeline         |
| 🇨🇳 中文    |      解决项目流水线bug        | …
> fix(dop): Fix bugs in project pipeline

- .github/workflows/ci-it.yml
- Makefile
- build/dockerfiles/base/Dockerfile
- build/scripts/base_image.sh
- build/scripts/docker_image.sh
upgrade erda base image, install vim for cluster-agent
/assign @CraigMChen 
| 🇺🇸 English |   upgrade erda base image           |
| 🇨🇳 中文    |   升级 erda base 镜像           |
> chore: upgrade erda base image

- .erda/migrations/config.yml
- pkg/database/sqllint/linters/scritp_checksum_linter.go
- pkg/database/sqllint/linters/scritp_checksum_linter_test.go
- pkg/database/sqllint/linters/scritp_name_linter.go
- pkg/database/sqllint/linters/scritp_name_linter_test.go
- pkg/database/sqllint/rule.go
- pkg/database/sqllint/script/script.go
- pkg/database/sqllint/visitors.go
add lint on migration script
- script name lint: lint script name by patterns
- checksum lint: lint script checksum that let script can not be altered
| 🇺🇸 English | add migration script lint for script naming and checksum |
| 🇨🇳 中文    | 增加规约检查文件命名和文件 checksum 以防篡改 |
> feat: add script lint

- cmd/orchestrator/conf/i18n/deployment-order-precheck.yaml
- cmd/orchestrator/conf/i18n/orchestrator-log-trans.yaml
- internal/tools/orchestrator/initialize.go
- internal/tools/orchestrator/services/addon/addon.go
- internal/tools/orchestrator/services/deployment/deployment_context.go
- internal/tools/orchestrator/services/deployment/deployment_context_test.go
- internal/tools/orchestrator/services/deployment_order/deployment_order.go
- internal/tools/orchestrator/services/deployment_order/deployment_order_render.go
- internal/tools/orchestrator/services/deployment_order/deployment_order_render_test.go
- internal/tools/orchestrator/services/runtime/runtime.go
- internal/tools/orchestrator/services/runtime/runtime_test.go
support addon plan check when deploy
deploy with dice action
deploy to no-prod with deployment order
deploy to prod with deployment order
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=321389&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMDU1Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1321&type=REQUIREMENT)
| 🇺🇸 English |   support addon plan check when deploy           |
| 🇨🇳 中文    |   支持 addon 部署前 plan 的校验           |
> For details on the cherry …
> feat: support addon plan check when deploy

- internal/core/openapi/legacy/api/apis/dop/cmdb_orgs_search.go
- internal/core/openapi/legacy/api/apis/uc/uc_user_export.go
Fix user export api spec CheckLogin.
| 🇺🇸 English |    Fix user export api spec CheckLogin.           |
| 🇨🇳 中文    |   修复用户导出身份认证           |
> fix: Fix user export and and org list api spec CheckLogin.

- api/proto/core/org/org.proto
- internal/apps/dop/endpoints/organization.go
- internal/apps/dop/endpoints/organization_test.go
- internal/core/org/org.service.go
- internal/core/org/org.service_test.go
Add Joined org list, remove org params.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMzM5LDEzMzcsMTMyMSwxMjk3XSwiYXNzaWduZWUiOlsiMTAwMTA3MyJdfQ%3D%3D&id=326743&iterationID=1321&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |  Add Joined org list, remove org params.            |
| 🇨🇳 中文    |    已加入的组织列表， 废弃org参数          |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CO …
> fix: Add Joined org list, remove org params.

- api/proto/dop/projectpipeline/projectpipeline.proto
- apistructs/labels.go
- apistructs/pipeline.go
- apistructs/pipeline_dto.go
- apistructs/pipeline_page.go
- apistructs/pipeline_page_test.go
- cmd/dop/conf/i18n/cp/common.yaml
- internal/apps/dop/component-protocol/components/project-pipeline-exec-list/common/commom.go
- internal/apps/dop/component-protocol/components/project-pipeline-exec-list/common/gshelper/helper.go
- internal/apps/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/filterContainer/customFilter/condition.go
- internal/apps/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/filterContainer/customFilter/condition_test.go
- internal/apps/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/filterContainer/customFilter/provider.go
- internal/apps/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/pipelineTable/provider.go
- internal/apps/dop/component-protocol/components/util/vars.go
- internal/apps/dop/providers/projectpipeline/service_impl.go
- internal/apps/dop/providers/projectpipeline/service_impl_test.go
- internal/apps/dop/services/pipeline/pipeline.go
- internal/apps/dop/services/pipeline/pipeline_test.go
- internal/tools/pipeline/initialize.go
- internal/tools/pipeline/providers/cron/daemon/cron_task.go
- internal/tools/pipeline/providers/reconciler/taskrun/taskop/prepare.go
- internal/tools/pipeline/providers/secret/platform_secret.go
- internal/tools/pipeline/services/pipelinesvc/convert.go
- internal/tools/pipeline/services/pipelinesvc/create_v2.go
- internal/tools/pipeline/spec/pipeline.go
- internal/tools/pipeline/spec/pipeline_extra.go
- internal/tools/pipeline/spec/pipeline_test.go
add owner user for pipeline
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=325576&iterationID=1321&pId=323784&type=TASK)
/assign @sfwn 
| 🇺🇸 English |   add owner user for pipeline           |
| 🇨🇳 中文    |     流水线增加拥有者        |
> feat: add owner user for pipeline

- internal/tools/orchestrator/services/runtime/runtime.go
fix project runtime list deploy time error when deploy failed
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=327163&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMDU1Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1321&type=BUG)
| 🇺🇸 English |  project runtime list deploy time error when deploy failed            |
| 🇨🇳 中文    |      部署失败时， 项目级 runtime 列表部署时间显示错误       | …
> fix: project runtime list deploy time error when deploy failed

- pipeline.yml
skip_lint
| 🇺🇸 English | skip_lint |
| 🇨🇳 中文    | 暂时跳过规约检查 |
> feat: skip_lint

- erda.yml
adjust exposed port order for erda-server
| 🇺🇸 English |   adjust exposed port order for erda-server           |
| 🇨🇳 中文    |    调整 erda-server 需要暴露的端口顺序          |
> chore: adjust exposed port order for erda-server

- cmd/hepa/bootstrap.yaml
- cmd/hepa/main.go
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=328001&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1337&tab=BUG&type=BUG)
/assign @sfwn 
| 🇺🇸 English |     inject org to hepa         |
| 🇨🇳 中文    |     heap注入org         |
> fix(hepa): inject org to hepa

- internal/apps/dop/services/pipeline/pipeline.go
- internal/apps/dop/services/pipeline/pipeline_test.go
check pipeline owner has permission to get app
| 🇺🇸 English |   Fix the bug that check pipeline owner has permission to get app           |
| 🇨🇳 中文    |    校验pipeline owner是否在应用内          |
> fix: check pipeline owner has permission to get app

- cmd/monitor/streaming/conf/clickhouse/metrics/ddl_create_tenant_tables.sql.tpl
tenant template fix
| 🇺🇸 English |       tenant template fix       |
| 🇨🇳 中文    |       租户模板修复       |
> fix: tenant template fix

- internal/tools/orchestrator/services/addon/addon.go
- internal/tools/orchestrator/services/runtime/runtime_test.go
remove deploy condition precheck
| 🇺🇸 English |  remove deploy condition precheck             |
| 🇨🇳 中文    |     移除部署条件校验         |
> fix(orchestrator): remove deploy condition precheck

- internal/tools/monitor/core/alert/alert-apis/alert.service.go
- internal/tools/monitor/core/alert/alert-apis/alert.service_test.go
Solve value conversion problems
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=328374&iterationID=1337&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |     Solve value conversion problems         |
| 🇨🇳 中文    |      解决值转换问题        |
/cherry-pick release/2.3-beta.3
> fix(monitor): Solve value conversion problems

- .erda/pipelines/ci-build-ce.yml
- .erda/pipelines/ci-deploy.yml
- pipeline.yml
specify image for erda pipeline build step (Go 1.17)
/assign @littlejiancc 
| 🇺🇸 English |    specify image for erda pipeline build step (Go 1.17)          |
| 🇨🇳 中文    |   Erda 流水线构建步骤指定镜像 (Go 1.17)           |
> chore: specify image for erda pipeline build step (Go 1.17)

- .erda/pipelines/ci-build-ce.yml
- .erda/pipelines/ci-deploy.yml
- pipeline.yml
fix build erda agents
| 🇺🇸 English |   fix build erda agents           |
| 🇨🇳 中文    |    修复 erda agents 的编译          |
> chore: fix build erda agents

- .erda/pipelines/ci-build-ce.yml
- .erda/pipelines/ci-deploy.yml
- .github/workflows/ci-it.yml
- Makefile
- build/dockerfiles/base/Dockerfile
- build/scripts/base_image.sh
- build/scripts/docker_image.sh
- pipeline.yml
update erda base image, install docker-ce-cli
| 🇺🇸 English |  update erda base image, install docker-ce-cli            |
| 🇨🇳 中文    |  更新 erda 基础镜像，安装 docker-ce-cli            |
> chore: update erda base image

- cmd/monitor/monitor/bootstrap.yaml
- internal/tools/monitor/core/metric/query/es-tsql/functions.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/ckFunctions.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/functions.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/query.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/query_clickhouse.go
- internal/tools/monitor/core/metric/query/es-tsql/query.go
- internal/tools/monitor/core/metric/query/metricmeta/manager.go
- internal/tools/monitor/core/metric/query/metricmeta/metric_meta.go
- internal/tools/monitor/core/metric/query/metricq/provider.go
- internal/tools/monitor/core/metric/query/metricq/routes.go
- internal/tools/monitor/core/metric/query/provider.go
- internal/tools/monitor/core/metric/query/query/search.go
- internal/tools/monitor/core/metric/storage/clickhouse/query.go
- internal/tools/monitor/core/metric/storage/elasticsearch/mock_query_test.go
feat: append meta to metric query
| 🇺🇸 English |     feat: append meta to metric query         |
| 🇨🇳 中文    |      metric 查询添加 meta 表        |
> feat: append meta to metric query

- cmd/monitor/monitor/bootstrap.yaml
- internal/tools/monitor/core/entity/persist/provider.go
fix: entity-storage-writer modify citations storage interface
add keypass environment variable
| 🇺🇸 English |  entity-storage-writer modify citations storage interface            |
| 🇨🇳 中文    |    entity-stroage-writer 修改引用的 storage 接口          |
> fix: entity-storage-writer modify citations storage interface

- cmd/monitor/streaming/bootstrap.yaml
fix: write all metrics to ck
| 🇺🇸 English | fix: write all metrics to ck |
| 🇨🇳 中文    | 所有指标写入clickhouse |
> fix: write all metrics to ck

- internal/pkg/audit/interceptor.go
fix: panic in audit
| 🇺🇸 English | fix: panic in audit  |
| 🇨🇳 中文    | 修复审计组件panic的问题 |
> fix: panic in audit

- internal/tools/monitor/oap/collector/core/pipeline/pipeline.go
metrics panic fix
| 🇺🇸 English |      metrics panic fix        |
| 🇨🇳 中文    |        metrics panic 修复      |
> fix: metrics panic fix

- .erda/migrations/config.yml
feat: config uc migration lint
| 🇺🇸 English | config uc migration lint |
| 🇨🇳 中文    | 允许 UC migrations 不符合某些规约 |
> feat: config uc migration lint

- cmd/monitor/monitor/bootstrap.yaml
- internal/tools/monitor/dashboard/org-apis/clickhouse_source.go
- internal/tools/monitor/dashboard/org-apis/clickhouse_source_test.go
- internal/tools/monitor/dashboard/org-apis/const.go
- internal/tools/monitor/dashboard/org-apis/host.go
- internal/tools/monitor/dashboard/org-apis/provider.go
- internal/tools/monitor/dashboard/org-apis/routes.go
- internal/tools/monitor/dashboard/org-apis/source.go
refactor: metrics query from ck
/assign @sixther-dc @erenming @tomatopunk 
| 🇺🇸 English | refactor: metrics query from ck |
| 🇨🇳 中文    | 重构云管平台中机器列表筛选和实例列表相关接口，改为从 clickhouse 中查询 |
> refactor: metrics query from ck

- cmd/monitor/monitor/bootstrap.yaml
- internal/tools/monitor/dashboard/org-apis/clickhouse_source.go
- internal/tools/monitor/dashboard/org-apis/clickhouse_source_test.go
1. remove deplicated monitor config
2. add tenant_id in sql
| 🇺🇸 English | bugfix: deplicate config |
| 🇨🇳 中文    |  删除重复的配置，在 sql 中添加 tenant_id 过滤条件  |
> fix: deplicate config

- internal/tools/monitor/oap/collector/lib/typeconvert/convertor.go
write bool type metric
/assign @erenming 
| 🇺🇸 English |      write bool type metric        |
| 🇨🇳 中文    |     写入 bool 类型指标         |
> feat: write bool type metric

- internal/tools/orchestrator/scheduler/executor/plugins/edas/edas.go
- internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s.go
- internal/tools/orchestrator/scheduler/executor/plugins/k8s/pod/pod.go
- internal/tools/orchestrator/scheduler/executor/plugins/k8s/pod/pod_test.go
- internal/tools/orchestrator/scheduler/executor/plugins/k8s/resourceinfo/resourceinfo.go
- internal/tools/orchestrator/services/runtime/runtime_test.go
refactor pod module in scheduler with client-go
| 🇺🇸 English | refactor pod module in scheduler with client-go             |
| 🇨🇳 中文    |  client-go 优化 scheduler pod 模块             |
> feat(orchestrator): refactor pod module in scheduler with client-go

- cmd/monitor/monitor/conf/chartview/runtime/runtime-container-detail.json
| 🇺🇸 English |          fix pod chartview config    |
| 🇨🇳 中文    |           修复pod图表配置 |
> fix: pod chartview config

- cmd/monitor/monitor/conf/chartview/runtime/runtime-container-detail.json
fix charview of runtime
| 🇺🇸 English |          fix charview of runtime    |
| 🇨🇳 中文    |            修复runtime的大盘  |
> fix: charview of runtime

- apistructs/pipeline_yml.go
- internal/apps/dop/services/migrate/scene_step.go
- internal/tools/pipeline/actionagent/define.go
- internal/tools/pipeline/actionagent/pull_bootstrap_info.go
- internal/tools/pipeline/actionagent/step_logic.go
- internal/tools/pipeline/actionagent/step_prepare.go
- internal/tools/pipeline/actionagent/step_prepare_test.go
- internal/tools/pipeline/actionagent/step_validate.go
- internal/tools/pipeline/actionagent/step_validate_test.go
- internal/tools/pipeline/endpoints/pipeline_task.go
- pkg/parser/pipelineyml/define.go
- pkg/parser/pipelineyml/define_test.go
- pkg/parser/pipelineyml/visitor_ref_op.go
pipeline custom command line support for newlines
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=325979&iterationID=1337&pId=0&type=REQUIREMENT)
- [custom shell link](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=328190&iterationID=1337&pId=0&type=REQUIREMENT)
/assign @sfwn 
| 🇺🇸 English |   pipeline custom command line support for newlines           |
| 🇨🇳 中文    |   pipeline自定义命令支持换行           | …
> refactor: pipeline custom command line support for newlines

- api/proto/dop/issue/core/core.proto
- apistructs/event.go
- cmd/dop/conf/i18n/cp/common.yaml
- internal/apps/dop/component-protocol/components/issue-manage/issueTable/render.go
- internal/apps/dop/component-protocol/standard-components/issueFilter/conditions.go
- internal/apps/dop/component-protocol/standard-components/issueFilter/filterset.go
- internal/apps/dop/component-protocol/standard-components/issueFilter/provider.go
- internal/apps/dop/providers/issue/core/property.go
- internal/apps/dop/providers/issue/core/relation.go
- internal/apps/dop/providers/issue/core/subscribe.go
- internal/apps/dop/providers/issue/dao/core.go
- internal/apps/dop/providers/issue/stream/common/model.go
- internal/apps/dop/providers/issue/stream/core/event.go
- internal/apps/dop/providers/issue/stream/core/event_test.go
- internal/apps/dop/providers/rule/actions/api/api.go
- internal/apps/dop/providers/rule/actions/api/api_test.go
- internal/apps/dop/providers/rule/db/record.go
- internal/apps/dop/providers/rule/db/rule.go
- internal/apps/dop/providers/rule/executor/execute.go
- internal/apps/dop/providers/rule/executor/expr.go
- internal/apps/dop/providers/rule/executor/expr_test.go
- internal/apps/dop/providers/rule/provider.go
- internal/apps/dop/providers/rule/rule.service.go
Add api config jsonnet snippet, issue participants in event data.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=330295&iterationID=1337&pId=328325&type=TASK)
/assign @sfwn 
| 🇺🇸 English |   Add api config jsonnet snippet, issue participants in event data.           |
| 🇨🇳 中文    |  api 配置信息使用 jsonnet,  事项事件增加参与人信息        |
> feat: Add api config jsonnet snippet, issue participants in event data.

- cmd/monitor/monitor/bootstrap.yaml
- internal/apps/msp/apm/trace/query/trace.service.go
- internal/tools/monitor/core/metric/model/result.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/SQLQuery.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_elasticsearch_test.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/query.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/query_clickhouse.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/query_clickhouse_test.go
- internal/tools/monitor/core/metric/query/es-tsql/query.go
- internal/tools/monitor/core/metric/query/es-tsql/tsql-test/main.go
- internal/tools/monitor/core/metric/query/metricmeta/metric_group.go
- internal/tools/monitor/core/metric/query/metricq/provider.go
- internal/tools/monitor/core/metric/query/metricq/routes.go
- internal/tools/monitor/core/metric/query/query/search.go
- internal/tools/monitor/core/metric/storage/clickhouse/provider.go
- internal/tools/monitor/core/metric/storage/clickhouse/query.go
- internal/tools/monitor/core/metric/storage/elasticsearch/mock_query_test.go
- internal/tools/monitor/core/metric/storage/elasticsearch/query.go
- internal/tools/monitor/core/metric/storage/elasticsearch/query_test.go
- pkg/common/trace/tool.go
- pkg/common/trace/tracing.go
add clickhouse metric to trace instrumentation
| 🇺🇸 English |    add clickhouse metric to trace instrumentation          |
| 🇨🇳 中文    |     clickhouse 指标查询添加 trace 跟踪         |
> feat: add clickhouse metric to trace instrumentation

- internal/tools/monitor/core/metric/query/es-tsql/influxql/query_clickhouse.go
- internal/tools/monitor/core/metric/storage/clickhouse/query.go
fix metric query nil point error
| 🇺🇸 English |    fix metric query nil point error          |
| 🇨🇳 中文    |        修复指标查询空指针错误      |
> fix: fix metric query nil point error

- api/proto/apps/devflow/flow/flow.proto
- internal/apps/devflow/flow/db/define.go
- internal/apps/devflow/flow/flow.service.go
- internal/apps/devflow/flow/flow.service_test.go
Solve the problem that the merge request page fails to get the workflow
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=331647&iterationID=1337&tab=BUG&type=BUG)
/assign @sfwn 
| 🇺🇸 English |    Solve the problem that the merge request page fails to get the workflow          |
| 🇨🇳 中文    |      解决合并请求页面获取工作流失败问题        |
> fix(dop): Solve the problem that the merge request page fails to get the workflow

- apistructs/pipeline_yml.go
- pkg/parser/pipelineyml/graph_pipelineyml.go
pipelineyml graph display action shell
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that pipelineyml graph display action shell           |
| 🇨🇳 中文    |     pipeline图形化界面展示shell字段         |
> fix: pipelineyml graph display action shell

- internal/core/file/http.go
- pkg/http/httpserver/response.go
fix httpserver response userid
| 🇺🇸 English |  fix httpserver response userid            |
| 🇨🇳 中文    |   修复 httpserver 响应里的 userid           |
> fix: httpserver response userid

- pkg/parser/pipelineyml/graph_pipelineyml.go
pipelineyml graph parse fronted action add shell field
/assign @sfwn 
| 🇺🇸 English |    pipelineyml graph parse fronted action add shell field          |
| 🇨🇳 中文    |       解析前端yml加上shell字段       |
> fix: pipelineyml parse fronted action add shell field

- .github/workflows/git-sync.yml
update git-sync.yml
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=330852&iterationID=1354&pId=0&type=REQUIREMENT)
| 🇺🇸 English |      update git-sync.yml        |
| 🇨🇳 中文    |       修改 git-sync.yml      |
> feat: update git-sync.yml

- cmd/monitor/monitor/conf/chartview/runtime/runtime-container-detail.json
fix: add i18n for runtime-container-detail  charview
| 🇺🇸 English |      add i18n for runtime-container-detail  charview        |
| 🇨🇳 中文    |        增加容器监控的国际化词条      |
> fix: add i18n for runtime-container-detail  charview

- .github/workflows/git-sync.yml
revert update git-sync.yml
| 🇺🇸 English |      revert update git-sync.yml        |
| 🇨🇳 中文    |      revert update git-sync.yml        |
> revert: update git-sync.yml

- cmd/monitor/monitor/bootstrap.yaml
- internal/tools/monitor/core/alert/details-apis/alertdetail.service.go
- internal/tools/monitor/core/alert/details-apis/clickhouse_source.go
- internal/tools/monitor/core/alert/details-apis/clickhouse_source_test.go
- internal/tools/monitor/core/alert/details-apis/provider.go
- internal/tools/monitor/dashboard/org-apis/clickhouse_source.go
refactor: query alert pod info from ck
/assign @sixther-dc @erenming @tomatopunk 
| 🇺🇸 English | refactor: query alert pod info from ck  |
| 🇨🇳 中文    | 重构：将 pod 告警信息查询接口改为从 ck 查询 |
> refactor: query alert pod info from ck

- .erda/migrations/qa/20220805-qa-sonar-gate-result.sql
- apistructs/qa.go
- internal/apps/dop/dbclient/sonar.go
- internal/apps/dop/endpoints/sonar.go
- internal/apps/dop/endpoints/sonar_test.go
qa sonar store quality gate result
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=331931&iterationID=1354&pId=0&type=TASK)
| 🇺🇸 English | qa sonar store quality gate result             |
| 🇨🇳 中文    |      sonar测试保存门禁检查结果        |
> feat(dop): qa sonar store quality gate result

- api/proto/oap/trace/tracing.proto
- cmd/monitor/monitor/bootstrap.yaml
- cmd/monitor/streaming/bootstrap.yaml
- internal/apps/msp/apm/trace/query/trace.service.go
- internal/tools/monitor/core/metric/query/query/search.go
- internal/tools/monitor/core/metric/storage/clickhouse/query.go
- internal/tools/monitor/oap/collector/lib/protoparser/oapspan/event.go
- internal/tools/monitor/oap/collector/lib/protoparser/oapspan/event_test.go
- internal/tools/monitor/oap/collector/plugins/receivers/kafka/provider.go
- internal/tools/monitor/oap/collector/plugins/receivers/opentelemetry/interceptor.go
support open-telemetry trace event
append metric query event
| 🇺🇸 English |   fix: support open-telemetry trace event           |
| 🇨🇳 中文    |        支持 otel trace event      |
> feat: support open-telemetry trace event

- internal/core/user/impl/kratos/service.go
- internal/core/user/impl/kratos/service_test.go
- internal/core/user/impl/uc/service.go
- internal/core/user/provider.go
Fix internal user nil response when request is empty.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=331920&iterationID=1337&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |  Fix internal user nil response when request is empty.            |
| 🇨🇳 中文    |   修复内部用户接口返回空           |
> fix: Fix internal user nil response when request is empty.

- cmd/monitor/monitor/conf/chartview/cmp/cmp-dashboard-nodeDetail-origin.json
fix: chartview of node detail
| 🇺🇸 English |      fix chartview of node detail        |
| 🇨🇳 中文    |          修复节点监控大盘    |
> fix: chartview of node detail

- cmd/monitor/monitor/conf/chartview/runtime/addon-mysql.json
fix: charview of addon-mysql
| 🇺🇸 English |      fix: charview of addon-mysql        |
| 🇨🇳 中文    |    修复mysql addon的监控大盘       |
> fix: charview of addon-mysql

- apistructs/container.go
- apistructs/service_job_status.go
- internal/tools/orchestrator/components/podscaler/manual_scale.go
- internal/tools/orchestrator/components/runtime/mock/mock_sg.go
- internal/tools/orchestrator/components/runtime/runtime.service.go
- internal/tools/orchestrator/dbclient/vpa.go
- internal/tools/orchestrator/endpoints/instance.go
- internal/tools/orchestrator/endpoints/instance_test.go
- internal/tools/orchestrator/endpoints/server_handler.go
- internal/tools/orchestrator/scheduler/executor/plugins/edas/edas.go
- internal/tools/orchestrator/scheduler/executor/plugins/k8s/daemonset.go
- internal/tools/orchestrator/scheduler/executor/plugins/k8s/deployment.go
- internal/tools/orchestrator/scheduler/executor/plugins/k8s/job.go
- internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s.go
- internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s_stateful.go
- internal/tools/orchestrator/scheduler/impl/servicegroup/operations.go
- internal/tools/orchestrator/scheduler/impl/servicegroup/servicegroup.go
- internal/tools/orchestrator/services/runtime/runtime.go
Merge runtime service's serviceinstance and podinstance
/assign @luobily @sixther-dc @iutx 
Feature: Merge runtime service's serviceinstance and podinstance（合并 Runtime 详情页的 service 的 服务详情 和 POD 详情）
| 🇺🇸 English |     Merge runtime service's serviceinstance and podinstance      |
| 🇨🇳 中文    |      合并 Runtime 详情页的 service 的 服务详情 和 POD 详情        |
> feat(orchestrator): merge runtime serviceinstance and podinstance

- cmd/monitor/monitor/conf/chartview/runtime/addon-es.json
- cmd/monitor/monitor/conf/chartview/runtime/addon-redis.json
fix: chartview of redis and es
| 🇺🇸 English |      fix: chartview of redis and es        |
| 🇨🇳 中文    |        修复redis es 的大盘图表      |
> fix: chartview of redis and es

- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/query_clickhouse.go
- internal/tools/monitor/core/metric/query/query/search.go
- internal/tools/monitor/core/metric/storage/clickhouse/query.go
- internal/tools/monitor/oap/collector/lib/protoparser/oapspan/event.go
- internal/tools/monitor/oap/collector/lib/protoparser/oapspan/event_test.go
- internal/tools/monitor/oap/collector/plugins/receivers/kafka/provider.go
fix trace and metric query closure bug
| 🇺🇸 English |     fix trace and metric query closure bug         |
| 🇨🇳 中文    |   修复 trace 与metric query 因闭包导致的 bug           |
> fix: fix trace and metric query closure bug

- api/proto/apps/devflow/flow/flow.proto
- internal/apps/devflow/flow/db/define.go
- internal/apps/devflow/flow/flow.service.go
- internal/apps/devflow/flow/flow.service_test.go
fix the bug of rejoin temp branch
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=332409&iterationID=1354&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |     fix the bug of rejoin temp branch         |
| 🇨🇳 中文    |    解决撤销临时合并的bug          |
> fix(dop): fix the bug of rejoin temp branch

- .erda/migrations/dop/20220809-devflow-index.sql
- internal/apps/devflow/flow/db/define.go
- internal/apps/devflow/flow/flow.service.go
- internal/apps/devflow/flow/flow.service_test.go
Compatible with temporary branches being deleted
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=332363&iterationID=1354&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |     Compatible with temporary branches being deleted         |
| 🇨🇳 中文    |       兼容临时分支被删除的情况       |
/cherry-pick release/2.3-beat.4
> fix(dop): Compatible with temporary branches being deleted

- api/proto/apps/devflow/flow/flow.proto
- internal/apps/devflow/flow/flow.service.go
- internal/apps/devflow/flow/flow.service_test.go
R&D workflow support deletion
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=331998&iterationID=1354&pId=0&type=REQUIREMENT)
/assign @sfwn 
| 🇺🇸 English |     R&D workflow support deletion         |
| 🇨🇳 中文    |     研发工作流支持删除         |
> feat(dop): R&D workflow support deletion

- .erda/pipelines/ci-build-ce.yml
- .erda/pipelines/ci-deploy.yml
- pipeline.yml
remove some outdated components in release
| 🇺🇸 English |  remove some outdated components in release            |
| 🇨🇳 中文    |  制品中移除一些过时组件            |
> chore: remove some outdated components in release

- internal/tools/monitor/dashboard/org-apis/clickhouse_source.go
fix: number of nodes is less than actual
| 🇺🇸 English | fix: number of nodes is less than actual |
| 🇨🇳 中文    | 修复查询节点数少于实际的问题 |
> fix: number of nodes is less than actual

- cmd/monitor/monitor/bootstrap.yaml
- internal/tools/monitor/core/metric/query/es-tsql/influxql/SQLQuery.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/ckFunctions.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/query_clickhouse.go
- internal/tools/monitor/core/metric/storage/clickhouse/provider.go
- internal/tools/monitor/core/metric/storage/clickhouse/query.go
fix rateps filter by zero
config append idle conns,max open conns env
filter org name use org_name column
| 🇺🇸 English |         fix rateps filter by zero      |
| 🇨🇳 中文    |    修复 rateps 过滤零值          |
> fix:  fix rateps filter by zero

- go.mod
- go.sum
- internal/core/openapi/openapi-ng/auth/uc-session/provider.go
openapi check injected redis field when initializing
| 🇺🇸 English |  openapi check injected redis field when initializing            |
| 🇨🇳 中文    |  openapi 启动时校验注入的 redis 字段            |
> fix: openapi check injected redis field when initializing

- .erda/migrations/config.yml
- .erda/migrations/dop/20220808-erda_rule_actor.sql
- api/proto/dop/rule/rule.proto
- internal/apps/dop/endpoints/issue_callback.go
- internal/apps/dop/providers/rule/actions/api/api.go
- internal/apps/dop/providers/rule/actions/api/api_test.go
- internal/apps/dop/providers/rule/db/record.go
- internal/apps/dop/providers/rule/db/rule.go
- internal/apps/dop/providers/rule/executor/execute.go
- internal/apps/dop/providers/rule/executor/execute_test.go
- internal/apps/dop/providers/rule/executor/expr.go
- internal/apps/dop/providers/rule/rule.service.go
Add rule actor, call outgoing api by actor.
- [1](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=331899&iterationID=1354&pId=331886&type=TASK)
- [2](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=331898&iterationID=1354&pId=331886&type=TASK)
- [3](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=332067&iterationID=1354&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |  Add rule actor, call outgoing api by actor.            |
| 🇨🇳 中文    |   工作流支持 actor           |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a- …
> feat: Add rule actor, call outgoing api by actor.

- cmd/monitor/monitor/conf/chartview/cmp/cmp-dashboard-nodeDetail.json
- cmd/monitor/monitor/conf/chartview/cmp/cmp-dashboard-podDetail.json
fix: pod & node chartview of cmp
| 🇺🇸 English |      fix pod & node chartview of cmp        |
| 🇨🇳 中文    |        修复云管的pod node 大盘      |
> fix: pod & node chartview of cmp

- internal/tools/orchestrator/hepa/services/legacy_upstream/impl/impl.go
handle apis while the apis are registerd with the same registerTag
| 🇺🇸 English | handle apis while the apis are registerd with the same registerTag |
| 🇨🇳 中文    | 处理同一 registerTag 多次注册不同路由的情况 |
> fix: handle missing apis while oflag is append

- internal/apps/dop/providers/rule/actions/api/api.go
- internal/apps/dop/providers/rule/actions/api/api_test.go
Fix rule api reset headers when header is nil.
/assign @sfwn 
| 🇺🇸 English |   Fix rule api reset headers when header is nil.           |
| 🇨🇳 中文    |   修复 header 为空           |
> fix: Fix rule api reset headers when header is nil.

- internal/tools/monitor/dashboard/org-apis/clickhouse_source.go
fix: number of nodes and pod is less than actual
| 🇺🇸 English | fix: number of nodes and pod is less than actual |
| 🇨🇳 中文    | 修复云管总览页面节点数和 pod 数量少于实际值的问题 |
> fix: number of nodes and pod is less than actual

- internal/apps/devflow/flow/db/define.go
- internal/apps/devflow/flow/flow.service.go
- internal/apps/devflow/flow/flow.service_test.go
- internal/apps/devflow/flow/provider.go
add transaction to delete devflow
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=333101&iterationID=1354&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |    add transaction to devflow delete         |
| 🇨🇳 中文    |       删除 devflow 增加事务      |
> fix(dop): add transaction to devflow delete

- api/proto/core/dicehub/image/image.proto
- api/proto/core/dicehub/release/getdice.proto
- api/proto/core/org/org.proto
- internal/apps/admin/provider.go
- internal/apps/dop/dicehub/initialize.go
- internal/apps/dop/initialize.go
- internal/core/legacy/initialize.go
- pkg/http/httpserver/router.go
fix erda-server missing route
/assign @sfwn 
| 🇺🇸 English |  Fix the bug that erda-server missing route            |
| 🇨🇳 中文    |     修复了erda-server丢失路由         |
> fix(erda-server): erda-server missing route

- internal/tools/monitor/core/metric/query/es-tsql/functions.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/SQLQuery.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/ckFunctions.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/ckFunctions_test.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/query_clickhouse.go
- internal/tools/monitor/core/metric/storage/clickhouse/query.go
- internal/tools/monitor/dashboard/org-apis/routes.go
exinclude cmp org condition
diffps use min function
| 🇺🇸 English |     exinclude cmp org condition         |
| 🇨🇳 中文    |       去除云管中 org 条件       |
> fix: exinclude cmp org condition

- conf/erda-configs/permission/backend/sys/org/org.yml
fix: add permisson of monitor_org_center to DEV TEST role
| 🇺🇸 English |      fix: add permisson of monitor_org_center to DEV TEST role        |
| 🇨🇳 中文    |          增加monitor_org_center的开发人员权限    |
> fix: add permisson of monitor_org_center to DEV TEST role

- internal/tools/orchestrator/hepa/services/micro_api/impl/impl.go
feat: update gatewayApi if exists
| 🇺🇸 English | update gatewayApi if exists |
| 🇨🇳 中文    | 如果 gatewayApi 存在则更新(避免创建重复路由) |
> feat: update gatewayApi if exists

- cmd/monitor/monitor/conf/chartview/frontend/ajax_detail.json
- cmd/monitor/monitor/conf/chartview/frontend/ajax_overview.json
- cmd/monitor/monitor/conf/chartview/frontend/browser_detail.json
- cmd/monitor/monitor/conf/chartview/frontend/browser_overview.json
- cmd/monitor/monitor/conf/chartview/frontend/domain_detail.json
- cmd/monitor/monitor/conf/chartview/frontend/domain_overview.json
- cmd/monitor/monitor/conf/chartview/frontend/page_detail.json
- cmd/monitor/monitor/conf/chartview/frontend/page_overview.json
- cmd/monitor/monitor/conf/chartview/frontend/script_overview.json
refactor: add frontend chartview
| 🇺🇸 English | refactor: add frontend chartview |
| 🇨🇳 中文    | 添加前端监控大盘配置 |
> refactor: add frontend chartview

- internal/apps/dop/services/publisher/publisher.go
make org-publisher-nexus process non block
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=332916&iterationID=1354&tab=BUG&type=BUG)
| 🇺🇸 English |   make org-publisher-nexus process non block           |
| 🇨🇳 中文    |  使企业发布商 nexus 相关流程不阻塞            |
> chore: make org-publisher-nexus process non block

- internal/tools/orchestrator/components/runtime/mock/mock.go
- internal/tools/orchestrator/components/runtime/mock/mock_sg.go
- internal/tools/orchestrator/endpoints/addon.go
- internal/tools/orchestrator/endpoints/instance.go
- internal/tools/orchestrator/scheduler/endpoints/servicegroup_endpoints.go
- internal/tools/orchestrator/scheduler/endpoints/servicegroup_endpoints_test.go
- internal/tools/orchestrator/scheduler/impl/servicegroup/operations.go
- internal/tools/orchestrator/scheduler/impl/servicegroup/operations_test.go
- internal/tools/orchestrator/scheduler/impl/servicegroup/servicegroup.go
- internal/tools/orchestrator/services/addon/addon.go
- internal/tools/orchestrator/services/addon/addon_deploy.go
- internal/tools/orchestrator/services/addon/addon_handler.go
- internal/tools/orchestrator/services/deployment/deployment_context.go
- internal/tools/orchestrator/services/runtime/runtime.go
delete runtime failed
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=333715&iterationID=1354&type=BUG)
| 🇺🇸 English |   delete runtime failed           |
| 🇨🇳 中文    |    删除 Runtime 失败          |
> fix(orchestrator): delete runtime failed

- internal/tools/monitor/apm/topology/clickhousesource/clickhouse_source.go
- internal/tools/monitor/apm/topology/clickhousesource/clickhouse_source_test.go
- internal/tools/monitor/apm/topology/topology.go
- internal/tools/monitor/apm/topology/topology_v2.go
fixing topology panic
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?id=333882&iterationID=1354&pId=0&type=BUG)
| 🇺🇸 English |       fix topology panic       |
| 🇨🇳 中文    |       修复topology panic       |
> fix: fixing topology panic

- bundle/publish_item.go
fix query publish item timeout
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=334154&iterationID=1354&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English | Fix the bug that query publish item timeout              |
| 🇨🇳 中文    |   修复了查询我的发布超时           |
> fix(erda-server): query publish item timeout

- cmd/monitor/monitor/conf/chartview/frontend/ajax_detail.json
- cmd/monitor/monitor/conf/chartview/frontend/ajax_overview.json
- cmd/monitor/monitor/conf/chartview/frontend/browser_overview.json
- cmd/monitor/monitor/conf/chartview/frontend/domain_detail.json
- cmd/monitor/monitor/conf/chartview/frontend/domain_overview.json
- cmd/monitor/monitor/conf/chartview/frontend/page_overview.json
- cmd/monitor/monitor/conf/chartview/frontend/script_overview.json
fix: chartview of frontend
| 🇺🇸 English |     fix: chartview of frontend         |
| 🇨🇳 中文    |      修复前端监控图表        |
> fix: chartview of frontend

- cmd/monitor/monitor/conf/analyzer/metrics/apm/application_db_service.json
- cmd/monitor/monitor/conf/analyzer/metrics/apm/application_mq_service.json
- internal/tools/monitor/apm/topology/topology_v2.go
- internal/tools/monitor/apm/topology/topology_v2_test.go
fix case when no tenant_id
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?id=334438&iterationID=1354&pId=0&type=BUG)
| 🇺🇸 English |      fix case when no tenant_id        |
| 🇨🇳 中文    |       修复无tenant_id的数据       |
> fix: fix case when no tenant_id

- internal/apps/msp/apm/checker/apis/checker.v1.service.go
check service is no data
| 🇺🇸 English |       fix: check service is no data       |
| 🇨🇳 中文    |         修复主动监控无数据的问题     |
> fix: check service is no data

- internal/apps/dop/providers/issue/core/file.go
- internal/apps/dop/providers/issue/core/query/convert.go
Use system local time instead of UTC in issue export.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=333521&iterationID=1354&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |  Use system local time instead of UTC in issue export.            |
| 🇨🇳 中文    |  事项导出 使用系统时间            |
> fix: Use system local time instead of UTC in issue export.

- apistructs/container.go
- internal/tools/orchestrator/endpoints/instance.go
- internal/tools/orchestrator/endpoints/instance_test.go
Optimal pod status  message
Feature: Optimal pod status  message （优化 Pod 状态相关的Message）
| 🇺🇸 English |       Optimal pod status  message        |
| 🇨🇳 中文    |     优化 Pod 状态相关的Message         |
> feat(orchestrator): optimal pod message

- apistructs/pipeline.go
- internal/tools/pipeline/actionagent/openapi.go
- internal/tools/pipeline/actionagent/openapi_test.go
- internal/tools/pipeline/providers/edgepipeline_register/provider.go
- internal/tools/pipeline/providers/reconciler/taskrun/taskop/prepare.go
fix action agent display eventbox log
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=331979&iterationID=1337&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |  Fix the bug that action agent display eventbox log             |
| 🇨🇳 中文    |  修复了actionagent打印eventbox的错误日志            |
> fix: action agent display eventbox log

- internal/tools/monitor/oap/collector/plugins/receivers/collector/collector.go
- internal/tools/monitor/oap/collector/plugins/receivers/collector/collector_test.go
- internal/tools/monitor/oap/collector/plugins/receivers/collector/provider.go
support get source from log message
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?id=333268&iterationID=-1&pId=0&type=TASK)
| 🇺🇸 English |       support get source from log message       |
| 🇨🇳 中文    |      支持从日志消息里获取source        |
> feat: support get source from log message

- internal/tools/orchestrator/hepa/services/openapi_rule/impl/impl.go
fix: transaction timeout
| 🇺🇸 English | transaction timeout |
| 🇨🇳 中文    | 修复一处事务没有透传导致的表锁问题 |
> fix: transaction timeout

- api/proto/dop/rule/rule.proto
- cmd/erda-server/bootstrap.yaml
- internal/apps/dop/endpoints/release.go
- internal/apps/dop/initialize.go
- internal/apps/dop/provider.go
- internal/apps/dop/provider_test.go
- internal/apps/dop/providers/rule/actions/pipeline/provider.go
- internal/apps/dop/providers/rule/actions/pipeline/provider_test.go
- internal/apps/dop/providers/rule/executor/execute.go
- internal/apps/dop/providers/rule/executor/execute_test.go
- internal/apps/dop/providers/rule/provider.go
Add pipeline action in rule, on push fire rule in release callback.
- [1](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=331900&iterationID=1354&pId=331880&type=TASK)
- [2](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=331901&iterationID=1354&pId=331880&type=TASK)
/assign @sfwn 
| 🇺🇸 English |  Add pipeline action in rule, on push fire rule in release callback.            |
| 🇨🇳 中文    |  规则触发支持 "git push" 事件；工作流支持 "执行流水线"      |
> feat: Add pipeline action in rule, on push fire rule in release callback.

- cmd/erda-server/bootstrap.yaml
- internal/apps/dop/providers/issue/stream/core/event.go
- internal/apps/dop/providers/rule/actions/dingtalkworknotice/provider.go
- internal/apps/dop/providers/rule/actions/dingtalkworknotice/provider_test.go
- internal/apps/dop/providers/rule/executor/execute.go
- internal/apps/dop/providers/rule/provider.go
Add DingTalk work notice action, issue state and assignee update.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=332529&iterationID=1354&pId=328289&type=TASK)
/assign @sfwn 
| 🇺🇸 English |   Add DingTalk work notice action, issue state and assignee update.           |
| 🇨🇳 中文    |    事项状态和处理人的流转, 增加钉钉工作通知          |
> feat: Add DingTalk work notice action, issue state and assignee update.

- internal/tools/monitor/dashboard/org-apis/clickhouse_source.go
- internal/tools/monitor/dashboard/org-apis/clickhouse_source_test.go
fix: query group hosts
| 🇺🇸 English | fix: query group hosts |
| 🇨🇳 中文    | 修复集群总览页面节点筛选错误的问题 |
> fix: query group hosts

- internal/tools/monitor/core/dataview/dashboard_file.go
| 🇺🇸 English |       fix: export dashboard file without ext       |
| 🇨🇳 中文    |         修复大盘文件导出缺少文件后缀     |
> fix: export dashboard file without ext

- internal/pkg/bundle-ex/cmdb/cmdb.go
- internal/pkg/bundle-ex/cmdb/org_cluster.go
- internal/tools/monitor/common/permission/permission.go
- internal/tools/monitor/core/alert/alert-apis/alert.service.go
- internal/tools/monitor/core/alert/alert-apis/provider.go
- internal/tools/monitor/core/alert/details-apis/permission.go
- internal/tools/monitor/core/alert/details-apis/provider.go
- internal/tools/monitor/core/alert/details-apis/routes.go
- internal/tools/monitor/core/log/query/provider.go
- internal/tools/monitor/core/log/query/routes.go
- internal/tools/monitor/dashboard/org-apis/clickhouse_source.go
- internal/tools/monitor/dashboard/org-apis/permission.go
- internal/tools/monitor/dashboard/org-apis/provider.go
- internal/tools/monitor/dashboard/report/apis/provider.go
- internal/tools/monitor/dashboard/report/apis/v1/provider.go
- internal/tools/monitor/notify/template/query/provider.go
fix: query container 404
| 🇺🇸 English | fix: query container 404  |
| 🇨🇳 中文    |  修复集群总览页面获取容器实例报 404 的问题   |
> fix: query container 404

- cmd/monitor/monitor/bootstrap.yaml
- cmd/monitor/streaming/bootstrap.yaml
- cmd/msp/bootstrap.yaml
fix: add QUERY_LOG_FROM_CLICKHOUSE_LOAD_MODE env
| 🇺🇸 English | fix: add QUERY_LOG_FROM_CLICKHOUSE_LOAD_MODE env |
| 🇨🇳 中文    | 添加环境变量用于修改 clickhouse-loader 的表缓存模式  |
> fix: add QUERY_LOG_FROM_CLICKHOUSE_LOAD_MODE env

- cmd/monitor/streaming/bootstrap.yaml
config adjust
| 🇺🇸 English |        config adjust      |
| 🇨🇳 中文    |       配置调整       |
> fix: config adjust

- internal/apps/dop/providers/publishitem/provider.go
publish response missing `success` field
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=334847&iterationID=1354&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |  fix publish response missing `success` field    |
| 🇨🇳 中文    |   修复了应用发布返回确实字段           |
> fix: publish response missing `success` field

- cmd/monitor/monitor/bootstrap.yaml
- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
- internal/tools/monitor/core/metric/storage/clickhouse/provider.go
- internal/tools/monitor/core/metric/storage/clickhouse/provider_test.go
fix no stabilize test
| 🇺🇸 English |     fix no stabilize test         |
| 🇨🇳 中文    |    修复不稳定的单测          |
> fix: no stabilize test

- internal/tools/orchestrator/hepa/providers/endpoint_api/endpoint.api.service.go
feat: no err if no api in deleting apis
| 🇺🇸 English | feat: no err if no api in deleting apis |
| 🇨🇳 中文    | 删除 api 时如果 api 不存在不返回错误 |
> feat: no err if no api

- apistructs/pipeline_queue.go
- cmd/erda-server/bootstrap.yaml
- cmd/erda-server/main.go
- internal/apps/dop/initialize.go
- internal/apps/dop/provider.go
- internal/apps/dop/providers/queue/calculate.go
- internal/apps/dop/providers/queue/calculate_test.go
- internal/apps/dop/providers/queue/interface.go
- internal/apps/dop/providers/queue/interface_test.go
- internal/apps/dop/providers/queue/provider.go
- internal/apps/dop/services/pipeline/pipeline.go
- pkg/numeral/max_min.go
- pkg/numeral/max_min_test.go
cicd pipeline bind queue
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=327948&iterationID=1354&pId=0&type=REQUIREMENT)
/assign @sfwn 
| 🇺🇸 English |  Support cicd pipeline bind queue            |
| 🇨🇳 中文    |      cicd流水线绑定队列        |
> feat: cicd pipeline bind queue

- internal/tools/monitor/apm/topology/clickhousesource/clickhouse_source.go
- internal/tools/monitor/apm/topology/topology_v2.go
- internal/tools/monitor/apm/topology/topology_v2_test.go
fix topology logic bug
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?id=334438&iterationID=1354&pId=0&type=BUG)
| 🇺🇸 English |        fix topology logic      |
| 🇨🇳 中文    |       拓扑逻辑修复       |
> fix: fix topology logic

- internal/apps/dop/endpoints/release.go
Fix get pipeline yml path.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=334905&iterationID=1354&tab=BUG&type=BUG)
/assign @sfwn 
| 🇺🇸 English |   Fix get pipeline yml path.           |
| 🇨🇳 中文    |    修复获取pipeline yml 路径          |
> fix: Fix get pipeline yml path.

- internal/apps/dop/providers/issue/core/query/relation.go
- internal/apps/dop/providers/issue/core/query/relation_test.go
Fix invalid issue plan time.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=334904&iterationID=1354&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |  Fix invalid issue plan time.            |
| 🇨🇳 中文    |  修复事项无效的计划时间            |
release/2.3-beta.5
> fix: Fix invalid issue plan time.

- .github/prlint.json
prlint support cherry-pick
| 🇺🇸 English |   prlint support cherry-pick           |
| 🇨🇳 中文    |   prlint 支持 cherry-pick           |
> chore: prlint support cherry-pick

- internal/tools/orchestrator/hepa/context/context.go
- internal/tools/orchestrator/hepa/providers/legacy_upstream/upstream.service.go
- internal/tools/orchestrator/hepa/repository/service/gateway_upstream_register_record_service.go
- internal/tools/orchestrator/hepa/services/legacy_upstream/impl/impl.go
feat: get record order by create_tiime desc
feat: get record order by create_tiime desc
| 🇺🇸 English | feat: get record order by create_tiime desc |
| 🇨🇳 中文    | 修复查询 upstream register record 没有按 create_time 倒序导致的查询结果错误的问题 |
> feat: get record order by create_tiime desc

- internal/apps/dop/dicehub/release/db/dbmock.go
- internal/apps/dop/dicehub/release/release.go
- internal/apps/dop/dicehub/release/release_test.go
project release import error with mode
| 🇺🇸 English |  fix project release import error with mode            |
| 🇨🇳 中文    |    修复项目级制品按模式导入错误          |
> fix(dicehub): project release import error with mode

- cmd/msp/bootstrap.yaml
span storage source configure adjust
| 🇺🇸 English |       span storage source conflict fix       |
| 🇨🇳 中文    |      span相关变量配置调整         |
> fix: span storage source configure adjust

- cmd/monitor/streaming/bootstrap.yaml
metric write configurable
| 🇺🇸 English |       metric write configurable       |
| 🇨🇳 中文    |       指标写入ES开关       |
> fix: metric write configurable

- .erda/pipelines/ci-build-ce.yml
update ci-build-ce.yml
| 🇺🇸 English |    update ci-build-ce.yml          |
| 🇨🇳 中文    |    更新  ci-build-ce.yml          |
> feat: update ci-build-ce.yml

- cmd/monitor/streaming/bootstrap.yaml
- cmd/monitor/streaming/main.go
add missing org provider
| 🇺🇸 English |        add missing org provider      |
| 🇨🇳 中文    |        添加org provider      |
> fix: add missing org provider

- cmd/monitor/monitor/conf/i18n/topology.yml
- internal/tools/monitor/apm/topology/topology.go
- internal/tools/monitor/apm/topology/topology_test.go
topology translator fix
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?id=335580&iterationID=1389&pId=0&type=BUG)
| 🇺🇸 English |       topology translator fix       |
| 🇨🇳 中文    |       拓扑翻译修复       |
> fix: translator fix

- internal/apps/msp/apm/service/components/transaction-http-slow/metric_table/provider.go
- internal/apps/msp/apm/trace/query/trace.service.go
- internal/apps/msp/apm/trace/query/trace.service_test.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse.go
fix: metric org name, and condition no tag 
| 🇺🇸 English |      fix: metric org name, and condition no tag         |
| 🇨🇳 中文    |       修复 metric 查询没有 orgname, 条件中不包含 tag        |
> fix: metric org name, and condition no tag 

- internal/tools/orchestrator/scheduler/executor/plugins/edas/edas.go
- internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/interface.go
- internal/tools/orchestrator/scheduler/executor/plugins/k8s/deployment.go
- internal/tools/orchestrator/scheduler/executor/plugins/k8s/deployment/deployment.go
- internal/tools/orchestrator/scheduler/executor/plugins/k8s/deployment/deployment_test.go
- internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s.go
- internal/tools/orchestrator/scheduler/executor/plugins/k8s/statefulset_test.go
refactor k8s plugin deployment
| 🇺🇸 English | optimize k8s plugin deployment             |
| 🇨🇳 中文    |      优化 deployment 插件        |
> feat(orchestrator): optimize k8s plugin deployment

- internal/tools/monitor/core/entity/storage/clickhouse/storage.go
fix: panic in entity count
| 🇺🇸 English | fix: panic in entity count |
| 🇨🇳 中文    | 修复错误分析页面产生 panic 的问题  |
> fix: panic in entity count

- internal/tools/pipeline/providers/leaderworker/impl_worker.go
skip cancel if worker not found logic task due to user frequent click
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=337650&iterationID=1389&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |  Fix the bug that skip cancel if worker not found logic task due to user frequent click            |
| 🇨🇳 中文    |    修复了由于用户频繁点击取消造成流水线panic的问题          |
> fix(pipeline): skip cancel if worker not found logic task due to user frequent click

- cmd/monitor/monitor/conf/chartview/error/error_count.json
refactor: add error_count chartview
| 🇺🇸 English | refactor: add error_count chartview |
| 🇨🇳 中文    | 添加错误计数大盘  |
> refactor: add error_count chartview

- erda.yml
refactor: modify the replica of log-service
| 🇺🇸 English | refactor: modify the replica of log-service |
| 🇨🇳 中文    | 修改 log-service 的副本数 |
> refactor: modify the replica of log-service

- internal/tools/orchestrator/hepa/apipolicy/policies/csrf/policy.go
- internal/tools/orchestrator/hepa/apipolicy/policies/sbac/dto.go
- internal/tools/orchestrator/hepa/apipolicy/policies/sbac/policy.go
- internal/tools/orchestrator/hepa/apipolicy/policies/sbac/policy_test.go
feat: global kong policy
| 🇺🇸 English | Fix global policy not taking effect |
| 🇨🇳 中文    | 修复全局策略不生效的问题 |
> feat: global kong policy

- cmd/monitor/monitor/conf/alert/rules/app_resource/app_resource_container_cpu/notify_template.yaml
- cmd/monitor/monitor/conf/alert/rules/app_resource/app_resource_container_mem/notify_template.yaml
- cmd/monitor/monitor/conf/alert/rules/app_resource/app_resource_container_oom/notify_template.yaml
- cmd/monitor/monitor/conf/alert/rules/app_transaction/app_transaction_http_path_error/analyzer_expression.json
- cmd/monitor/monitor/conf/alert/rules/app_transaction/app_transaction_http_path_error/notify_template.yaml
- cmd/monitor/monitor/conf/alert/rules/app_transaction/app_transaction_http_path_rt/analyzer_expression.json
- cmd/monitor/monitor/conf/alert/rules/app_transaction/app_transaction_http_path_rt/notify_template.yaml
- cmd/monitor/monitor/conf/alert/rules/app_transaction/app_transaction_http_service_error/analyzer_expression.json
- cmd/monitor/monitor/conf/alert/rules/app_transaction/app_transaction_http_service_error/notify_template.yaml
- cmd/monitor/monitor/conf/alert/rules/app_transaction/app_transaction_http_service_rt/analyzer_expression.json
- cmd/monitor/monitor/conf/alert/rules/app_transaction/app_transaction_http_service_rt/notify_template.yaml
feat: alert template add workspace
fix alert no service_name
| 🇺🇸 English |      alert template add workspace , fix alert no service_name         |
| 🇨🇳 中文    |          报警模板加入环境, 修复报警没有 service_name 的问题    |
> feat: alert template add workspace

- cmd/erda-server/bootstrap.yaml
- internal/apps/cmp/provider.go
fix: fix the issue that dop invoke cmp resource service failed
Tested in daily.
/assign @CraigMChen @iutx 
| 🇺🇸 English |   fix: fix the issue that dop invoke cmp resource service failed           |
| 🇨🇳 中文    |   修复 dop 调用 cmp 资源服务失败的问题           |
> fix: dop invoke cmp resource service failed

- cmd/monitor/monitor/bootstrap.yaml
- cmd/monitor/streaming/bootstrap.yaml
- cmd/msp/bootstrap.yaml
- internal/apps/cmp/component-protocol/components/cmp-dashboard-pods/podsTable/render.go
- internal/apps/msp/resource/provider.go
- internal/apps/msp/resource/runtime.go
- internal/tools/monitor/apm/runtime/provider.go
- internal/tools/monitor/apm/topology/provider.go
- internal/tools/monitor/core/alert/details-apis/provider.go
- internal/tools/monitor/core/metric/query/metricq/provider.go
- internal/tools/monitor/core/metric/query/provider.go
- internal/tools/monitor/dashboard/org-apis/provider.go
- internal/tools/monitor/extensions/loghub/index/query/clients.go
- internal/tools/monitor/extensions/loghub/index/query/provider.go
refactor: set monitor env to ck
/assign @sixther-dc @tomatopunk @erenming 
| 🇺🇸 English | set monitor env to clickhouse |
| 🇨🇳 中文    | 将监控默认的环境变量改为 clickhouse  |
> refactor: set monitor env to ck

- internal/apps/dop/component-protocol/components/issue-dashboard/filter/render.go
- internal/apps/dop/component-protocol/components/requirement-task-overview/distributePage/topFilter/render.go
- internal/apps/dop/endpoints/project.go
- internal/apps/dop/endpoints/project_test.go
fix: org center permission of cross-project leak
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=338406&iterationID=-1&tab=BUG&type=BUG)
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=338405&iterationID=-1&tab=BUG&type=BUG)
| 🇺🇸 English |  fix org center permission of cross-project leak            |
| 🇨🇳 中文    |   修复了管理中心项目越权漏洞           |
> fix: org center permission of cross-project leak

- cmd/monitor/extensions/cloud-import/bootstrap.yaml
- cmd/monitor/extensions/loghub/conf/output/bootstrap-elasticsearch-rollover.yaml
- cmd/monitor/extensions/loghub/conf/output/bootstrap-elasticsearch.yaml
- cmd/monitor/extensions/loghub/conf/output/bootstrap-stdout.yaml
- cmd/monitor/extensions/loghub/conf/output/bootstrap-udp.yaml
- cmd/monitor/extensions/loghub/log-metrics.yaml
- cmd/monitor/log-service/bootstrap.yaml
- internal/apps/msp/apm/log-service/analysis/provider.go
- internal/tools/monitor/extensions/loghub/exporter/provider.go
- internal/tools/monitor/extensions/loghub/sls-import/provider.go
kafka dependency fix
| 🇺🇸 English |       kafka dependency fix       |
| 🇨🇳 中文    |      kafka  依赖修复        |
> fix: kafka dependency fix

- cmd/monitor/streaming/bootstrap.yaml
fix: modify LOG_STORAGE_WRITER_SERVICE default value
| 🇺🇸 English | fix: modify LOG_STORAGE_WRITER_SERVICE default value |
| 🇨🇳 中文    | 修改 LOG_STORAGE_WRITER_SERVICE 环境变量的默认值 |
> fix: modify LOG_STORAGE_WRITER_SERVICE default value

- cmd/monitor/monitor/conf/chartview/cmp/cmp-dashboard-podDetail.json
fix: cmp pod metric chartview
| 🇺🇸 English | fix: cmp pod metric chartview |
| 🇨🇳 中文    | 修改 cmp pod 大盘图表配置 |
> fix: cmp pod metric chartview

- cmd/monitor/streaming/bootstrap.yaml
- cmd/monitor/streaming/conf/clickhouse/metrics/ddl_create_default_tables.sql.tpl
- internal/tools/monitor/core/metric/metric.go
- internal/tools/monitor/oap/collector/lib/kafka/batchreader.go
- internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/metric/metric.go
- internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/metric/metric_test.go
- internal/tools/monitor/oap/collector/plugins/receivers/kafka/provider.go
support metrics meta
| 🇺🇸 English |       support metrics meta       |
| 🇨🇳 中文    |       支持指标元数据       |
> feat: support metrics meta

- cmd/monitor/monitor/conf/chartview/error/error_count.json
- cmd/monitor/streaming/bootstrap.yaml
- cmd/monitor/streaming/conf/clickhouse/metrics/ddl_create_default_tables.sql.tpl
streaming config fix
| 🇺🇸 English |      streaming config fix        |
| 🇨🇳 中文    |      streaming配置修复        |
> fix: streaming config fix

- cmd/monitor/streaming/bootstrap.yaml
- internal/tools/monitor/core/settings/retention-strategy/provider.go
- internal/tools/monitor/core/storekit/clickhouse/table/initializer/provider.go
- internal/tools/monitor/core/storekit/clickhouse/table/initializer/ttl_sync.go
- internal/tools/monitor/core/storekit/clickhouse/table/loader/provider.go
- internal/tools/monitor/core/storekit/clickhouse/table/loader/table_loader.go
- internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/metric/metric.go
- internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/span/span.go
retention not effect fix, logic at start
| 🇺🇸 English |      retention not effect fix        |
| 🇨🇳 中文    |       过期策略生效问题修复       |
> fix: retention not effect fix

- cmd/monitor/log-service/bootstrap.yaml
fix: add es enable env for log-service
| 🇺🇸 English | fix: add es enable env for log-service |
| 🇨🇳 中文    | 为 log-service 组件添加 es 开关的环境变量  |
> fix: add es enable env for log-service

- cmd/monitor/log-service/bootstrap.yaml
- internal/tools/monitor/extensions/loghub/exporter/output/elasticsearch/elasticsearch.go
fix: add enable config for log-service
| 🇺🇸 English | fix: add enable config for log-service |
| 🇨🇳 中文    | 为 log-service 添加开关配置  |
> fix: add enable config for log-service

- erda.yml
specify grpc addr for merged-apps in erda.yml
| 🇺🇸 English |   specify gRPC addr for merged-apps in erda.yml           |
| 🇨🇳 中文    |   在 erda.yml 中为已合并的 apps 指定 gRPC 地址           |
> fix: specify grpc addr for merged-apps in erda.yml

- cmd/monitor/log-service/bootstrap.yaml
- internal/tools/monitor/extensions/loghub/exporter/output/elasticsearch/elasticsearch.go
fix: log-service start failed
| 🇺🇸 English | fix: log-service start failed |
| 🇨🇳 中文    | 修复 log-service 启动失败的问题 |
> fix: log-service start failed

- internal/tools/pipeline/providers/cron/compensator/provider.go
fix pipeline cron compensator nil pointer
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that pipeline cron compensator nil pointer            |
| 🇨🇳 中文    |    修复了pipeline定时补偿空指针的问题          |
> fix: pipeline cron compensator nil pointer

- cmd/monitor/streaming/bootstrap.yaml
fix: add clickhouse config for streaming
| 🇺🇸 English | fix: add clickhouse config for streaming  |
| 🇨🇳 中文    |  为 streaming 组件添加 clickhouse 环境变量 |
> fix: add clickhouse config for streaming

- api/proto/core/monitor/log/query/query.proto
- apistructs/dashboard.go
- bundle/dashboard.go
- internal/apps/cmp/component-protocol/components/cmp-dashboard-pods/podsTable/render.go
- internal/apps/dop/endpoints/cicd.go
- internal/tools/monitor/core/log/query/log.query.service.go
- internal/tools/monitor/core/log/storage/kubernetes-logs/provider.go
- internal/tools/monitor/core/log/storage/kubernetes-logs/storage.go
- internal/tools/monitor/core/log/storage/storage.go
feat: query pipeline log by k8s storage first
| 🇺🇸 English | feat: query pipeline log by k8s storage first |
| 🇨🇳 中文    | 流水线日志优先查询 k8s |
> feat: query pipeline log by k8s storage first

- cmd/monitor/monitor/conf/chartview/api-gateway/consumer-analyze.json
- cmd/monitor/monitor/conf/chartview/api-gateway/error-analyze.json
- cmd/monitor/monitor/conf/chartview/api-gateway/hotspot-analyze.json
- cmd/monitor/monitor/conf/chartview/api-gateway/package-analyze.json
feat: add chartview of api-gateway
| 🇺🇸 English |         feat: add chartview of api-gateway     |
| 🇨🇳 中文    |           增加api网关的大盘图表   |
> feat: add chartview of api-gateway

- cmd/monitor/monitor/conf/chartview/api-gateway/consumer-analyze.json
- cmd/monitor/monitor/conf/chartview/api-gateway/package-analyze.json
fix: adjust time config for api-gateway chartview
| 🇺🇸 English |        fix: adjust time config for api-gateway chartview      |
| 🇨🇳 中文    |          修复时间配置    |
> fix: adjust time config for api-gateway chartview

- cmd/monitor/monitor/bootstrap.yaml
- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_meta_test.go
- internal/tools/monitor/core/metric/query/es-tsql/query.go
- internal/tools/monitor/core/metric/query/metricmeta/manager.go
- internal/tools/monitor/core/metric/query/metricmeta/provider_meta_clickhouse.go
- internal/tools/monitor/core/metric/query/metricmeta/provider_meta_clickhouse_test.go
- internal/tools/monitor/core/metric/query/metricq/provider.go
- internal/tools/monitor/core/metric/query/provider.go
- internal/tools/monitor/core/metric/query/query/search.go
- internal/tools/monitor/core/metric/storage/elasticsearch/mock_query_test.go
- internal/tools/monitor/core/storekit/clickhouse/table/meta/cache.go
- internal/tools/monitor/core/storekit/clickhouse/table/meta/interface.go
- internal/tools/monitor/core/storekit/clickhouse/table/meta/meta_loader.go
- internal/tools/monitor/core/storekit/clickhouse/table/meta/meta_loader_test.go
- internal/tools/monitor/core/storekit/clickhouse/table/meta/mock_clickhouse_test.go
- internal/tools/monitor/core/storekit/clickhouse/table/meta/provider.go
offline update meta cache
| 🇺🇸 English |      offline update meta cache     |
| 🇨🇳 中文    |        离线更新缓存       |
> feat: offline update meta cache

- internal/tools/monitor/core/entity/storage/elasticsearch/provider.go
fix: modify entity-storage-elasticsearch provider service
| 🇺🇸 English | fix: modify entity-storage-elasticsearch provider service |
| 🇨🇳 中文    | 修改环境变量默认值 |
> fix: modify entity-storage-elasticsearch provider service

- internal/apps/dop/component-protocol/components/code-coverage/envFilter/render.go
- internal/apps/dop/component-protocol/components/test-dashboard/filter/model.go
fix test-dashboard & code-coverage cross-project leak
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=340580&iterationID=-1&type=BUG)
| 🇺🇸 English |  fix test-dashboard & code-coverage cross-project leak            |
| 🇨🇳 中文    |   修复 测试统计 和 代码覆盖率统计 项目越权          |
> fix: test-dashboard & code-coverage cross-project leak

- cmd/erda-server/bootstrap.yaml
- internal/apps/msp/resource/provider.go
fix: msp 404
| 🇺🇸 English | fix: msp 404 |
| 🇨🇳 中文    | 修复 msp 接口 404 的问题 |
> fix: msp 404

- internal/apps/dop/services/autotest/filetree_save_pipeline.go
fix save pipeline invalid memory address
[erda issue](https://erda.cloud/erda/dop/projects/387/ticket?id=341062&iterationID=-1&type=TICKET)
/assign @sfwn 
| 🇺🇸 English |    Fix the bug that save pipeline invalid memory address          |
| 🇨🇳 中文    |    修复了老项目流水线保存时空指针的问题          |
> fix: save pipeline invalid memory address

- internal/tools/pipeline/providers/engine/worker.go
- internal/tools/pipeline/providers/leaderworker/impl_general.go
engine worker actively trigger panic when context canceled
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?id=341285&iterationID=1403&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English | Fix the bug that engine worker actively trigger panic when context canceled             |
| 🇨🇳 中文    |    修复了pipeline由于链接etcd失败导致无worker可用的问题          |
> fix: engine worker actively trigger panic when context canceled

- cmd/monitor/monitor/bootstrap.yaml
- internal/tools/monitor/core/metric/query/es-tsql/influxql/SQLQuery.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_meta_test.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/query_clickhouse.go
- internal/tools/monitor/core/metric/query/metricmeta/provider_meta_clickhouse_test.go
- internal/tools/monitor/core/storekit/clickhouse/table/meta/cache.go
- internal/tools/monitor/core/storekit/clickhouse/table/meta/interface.go
- internal/tools/monitor/core/storekit/clickhouse/table/meta/meta_loader.go
- internal/tools/monitor/core/storekit/clickhouse/table/meta/meta_loader_test.go
- internal/tools/monitor/core/storekit/clickhouse/table/meta/mock_clickhouse_test.go
- internal/tools/monitor/core/storekit/clickhouse/table/meta/provider.go
fix offline cache no update and append trace
| 🇺🇸 English |     fix offline cache no update and append trace         |
| 🇨🇳 中文    |       修复离线缓存不更新的问题, 追加 trace       |
> fix: fix offline cache no update and append trace

- api/proto-go/go.mod
- api/proto-go/go.sum
update go mod for proto-go's update-gohub
| 🇺🇸 English |   update go mod for proto-go's update-gohub           |
| 🇨🇳 中文    |   为 proto-go 的 update-gohub 更新 go mod           |
> chore: update go mod for proto-go's update-gohub

- internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sflink/flink.go
- internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sjob/k8sjob.go
- internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sjob/k8sjob_test.go
- internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sspark/k8sspark.go
- internal/tools/pipeline/pipengine/actionexecutor/types/k8s_executor.go
- internal/tools/pipeline/pipengine/actionexecutor/types/k8s_executor_test.go
optimize k8s resource gc logic
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?id=340074&iterationID=1403&pId=0&type=TASK)
/assign @sfwn 
| 🇺🇸 English |     optimize k8s resource gc logic           |
| 🇨🇳 中文    |      优化k8s资源gc的逻辑        |
> fix: optimize k8s resource gc logic

- internal/tools/pipeline/dbclient/op_pipeline.go
- internal/tools/pipeline/providers/pipeline/detail.go
- pkg/common/pbutil/pbutil.go
- pkg/common/pbutil/pbutil_test.go
fix some fields of pipeline provider
/assign @sfwn 
| 🇺🇸 English |   fix some fields of pipeline provider            |
| 🇨🇳 中文    |     修复了pipeline service迁移后一些字段丢失和时间错误的问题         |
> fix: some fields of pipeline provider

- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_meta_test.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/query_clickhouse.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/query_clickhouse_test.go
metric query append default sort
| 🇺🇸 English |  metric query append default sort            |
| 🇨🇳 中文    |     指标查询, 加入默认的排序         |
> fix: chart view disorder

- cmd/monitor/monitor/conf/chartview/cmp/cmp-dashboard-nodeDetail-origin.json
- cmd/monitor/monitor/conf/chartview/cmp/cmp-dashboard-nodeDetail.json
- cmd/monitor/monitor/conf/chartview/cmp/cmp-dashboard-podDetail.json
- internal/apps/cmp/metrics/metrics.go
- internal/apps/msp/apm/alert/components/msp-alert-event-list/table/provider.go
- internal/apps/msp/apm/alert/components/msp-alert-event-list/table/trigger_count.go
- internal/apps/msp/apm/alert/components/msp-alert-event-list/table/trigger_count_test.go
- internal/apps/msp/apm/browser/components/browser-overview/kv_card/statistics.go
- internal/apps/msp/tenant/project/project.service.go
- internal/apps/msp/tenant/project/project.service_test.go
- internal/apps/msp/tenant/project/project_statistics.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/ckFunctions.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/ckFunctions_test.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/query.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/query_clickhouse.go
- internal/tools/monitor/core/metric/query/es-tsql/query.go
- internal/tools/monitor/core/metric/query/metricq/routes.go
- internal/tools/monitor/core/metric/storage/clickhouse/query.go
- internal/tools/monitor/core/metric/storage/elasticsearch/mock_query_test.go
- internal/tools/monitor/dashboard/org-apis/provider.go
- internal/tools/monitor/dashboard/org-apis/routes.go
feat: metric query performance optimization
| 🇺🇸 English |    feat: metric query performance optimization          |
| 🇨🇳 中文    |       指标查询性能优化       |
> feat: metric query performance optimization

- erda.yml
orchestrator use global msp addr
/assign @dspo @wangzhuzhen 
| 🇺🇸 English |   orchestrator use global msp addr           |
| 🇨🇳 中文    |  orchestrator 使用全局 msp 地址            |
> fix(orchestrator): orchestrator use global msp addr

- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/query_clickhouse.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/query_clickhouse_test.go
metric query chat view is twist
| 🇺🇸 English |  metric query chat view is twist            |
| 🇨🇳 中文    |    修复指标查询图表拧麻花的问题          |
> fix: metric query chat view is twist

- internal/tools/monitor/dashboard/org-apis/clickhouse_source.go
fix: filter host and container by org_name
| 🇺🇸 English | fix: filter host and container by org_name  |
| 🇨🇳 中文    | 修复集群总览页面上机器和实例没有根据组织过滤的问题  |
> fix: filter host and container by org_name

- build/dockerfiles/Dockerfile
make app can exit gracefully, [ref](https://pracucci.com/graceful-shutdown-of-kubernetes-pods.html)
| 🇺🇸 English |       make app can exit gracefully       |
| 🇨🇳 中文    |       使应用能优雅退出       |
> fix: make app can exit gracefully

- internal/apps/dop/providers/issue/core/query/paging.go
fix paging npe when issue doesn't have custom property
| 🇺🇸 English |   fix paging npe when issue doesn't have custom property           |
| 🇨🇳 中文    |   修复当 issue 没有自定义属性时分页查询 panic 的问题           |
> fix(dop): fix paging npe when issue doesn't have custom property

- internal/tools/pipeline/providers/pipeline/create_v2.go
fix `AutoRunAtOnce` compatibility logic
/assign @sfwn 
| 🇺🇸 English |  Fix the bug that `AutoRunAtOnce` compatibility logic            |
| 🇨🇳 中文    |   修复了`AutoRunAtOnce`兼容性问题           |
> fix(pipeline): `AutoRunAtOnce` compatibility logic

- internal/apps/cmp/component-protocol/components/cmp-dashboard-pods/podsTable/render.go
- internal/apps/cmp/impl/nodes/add.go
- internal/apps/cmp/impl/nodes/rm.go
fix: add node failed in cmp
| 🇺🇸 English | fix: add node failed in cmp |
| 🇨🇳 中文    | 修复上下线节点失败的问题 |
> fix: add node failed in cmp

- internal/apps/cmp/component-protocol/components/cmp-dashboard-pods/podsTable/render.go
- internal/apps/cmp/impl/nodes/add.go
- internal/apps/cmp/impl/nodes/rm.go
> fix: add node failed in cmp (cherry-pick)

- tools/cli/cmd/gw_debug_auth.go
- tools/cli/command/root_cmd.go
| 🇺🇸 English | add erda-cli gw debug-auth |
| 🇨🇳 中文    | 添加 erda-cli gw debug-auth |
```sh
% bin/erda-cli gw debug-auth -X POST --uri 'https://sample.io/api?name=chen&age=28' --content-type application/json --data '{"org": "erda"}' --auth-type sign --ak xxx --sk yyy --timestamp
[INFO] auth: sign, ak: xxx, sk: yyy, content-type: application/json, data: {"org": "erda"}, method: POST, uri: https://sample.io/api?name=chen&age=28, with timestampe: true
INFO[0000] content-type: application/json               
INFO[0000] encoded queries: apiTimestamp=1666069314&appKey=xxx&data={"org": "erda"} 
INFO[0000] siging string: …
```
> feat: add erda-cli gw debug-auth

- internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/mysql/mysql.go
- internal/tools/orchestrator/services/addon/addon_deploy.go
- internal/tools/orchestrator/services/addon/addon_deploy_test.go
- internal/tools/orchestrator/services/addon/addon_status.go
| 🇺🇸 English |    feature: support mysql operator 8.0          |
| 🇨🇳 中文    |      feature: support mysql operator 8.0        |
> feat: support mysql operator 8.0

- cmd/orchestrator/bootstrap.yaml
- cmd/orchestrator/main.go
- cmd/pipeline/bootstrap.yaml
- cmd/pipeline/main.go
pipeline,orchestrator enable pprof debug
/assign @sfwn 
| 🇺🇸 English |    pipeline,orchestrator enable pprof debug          |
| 🇨🇳 中文    |     pipeline和orchestrator开启pprof调试         |
> chore: pipeline,orchestrator enable pprof debug

- internal/apps/cmp/steve/middleware/middleware_test.go
- internal/apps/cmp/steve/middleware/shell_handler.go
fix cmp kubectl shell connect failed on kubernetes >= 1.24
changed kubectl in cmp, default auth 2 hours, expired cause:
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=345338&iterationID=1440&type=TASK)
| 🇺🇸 English |  fix cmp kubectl shell connect failed on kubernetes >= 1.24            |
| 🇨🇳 中文    |   修复 cmp kubectl  在 kubernetes >= 1.24 不可用的问题           | …
> fix: cmp kubectl shell connect failed on kubernetes >= 1.24

- internal/apps/cmp/endpoints/org_resource.go
- internal/apps/cmp/impl/clusters/add_edge_cluster.go
- internal/apps/cmp/impl/clusters/upgrade_edge_cluster.go
- internal/apps/cmp/impl/nodes/add.go
- internal/apps/cmp/impl/nodes/rm.go
- internal/apps/dop/endpoints/project_pipeline.go
- internal/apps/dop/endpoints/project_pipeline_test.go
- internal/apps/dop/providers/projectpipeline/service_impl.go
- internal/apps/dop/services/application/application.go
- internal/apps/dop/services/autotest_v2/scene.go
- internal/apps/dop/services/autotest_v2/sceneset.go
- internal/apps/dop/services/autotest_v2/testplan_v2.go
- internal/apps/dop/services/cq/analyze.go
- internal/apps/dop/services/pipeline/pipeline.go
- internal/apps/dop/services/testcase/apitest.go
- internal/apps/msp/resource/deploy/handlers/apigateway/apigateway.go
- internal/tools/monitor/dashboard/report/apis/report-task-apis.go
- internal/tools/monitor/dashboard/report/apis/v1/report.go
- internal/tools/orchestrator/services/runtime/runtime.go
internal server create pipeline with internal header
/assign @sfwn 
| 🇺🇸 English |  Fix the bug that internal server create pipeline with internal header            |
| 🇨🇳 中文    |    修复了内部服务调用pipeline无权限的问题          |
> fix: internal server create pipeline with internal header

- internal/tools/monitor/core/event/persist/consume.go
- internal/tools/monitor/core/event/persist/consume_test.go
fix: event decode error
| 🇺🇸 English | fix: event decode error |
| 🇨🇳 中文    | 修复 event 反序列化失败的问题 |
> fix: event decode error

- api/proto/oap/event/event.proto
- internal/apps/msp/apm/exception/query/source/elasticsearch_source.go
- internal/tools/monitor/core/event/persist/consume.go
- internal/tools/monitor/core/event/query/event.query.service.go
fix: modify pb.event
| 🇺🇸 English | fix: modify pb.event  |
| 🇨🇳 中文    | 修改 pb.event 字段类型，修复 event 反序列化失败的问题 |
> fix: modify pb.event

- internal/apps/msp/apm/trace/storage/cassandra_v1/provider.go
fix: use kafkago for trace on cassandra
| 🇺🇸 English |      fix: use kafkago for trace on cassandra        |
| 🇨🇳 中文    |          cassandra trace 修改为kafkago    |
> fix: use kafkago for trace on cassandra

- .github/workflows/ci-it-noneed.yml
github workflow support pure dbmigration PR
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=346752&iterationID=-1&tab=TASK&type=TASK)
/assign @chengjoey @iutx 
| 🇺🇸 English |   github workflow support pure dbmigration PR           |
| 🇨🇳 中文    |   github workflow 支持纯 dbmigration PR           |
> fix: github workflow support pure dbmigration PR

- apistructs/member.go
- internal/apps/dop/providers/project/home/provider.go
- internal/apps/dop/providers/project/home/service.go
- internal/core/legacy/endpoints/member.go
- internal/core/legacy/endpoints/member_test.go
- internal/core/legacy/services/approve/approve.go
- internal/core/legacy/services/member/member.go
- internal/core/legacy/services/member/member_test.go
- internal/tools/orchestrator/services/runtime/runtime.go
1. fix cross-project leak
2. listMembers desensitize userinfo
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=345834&iterationID=-1&type=TASK)
| 🇺🇸 English |  fix cross-project leak;  listMembers desensitize userinfo           |
| 🇨🇳 中文    |  修复项目水平越权漏洞；listMembers 脱敏            |
> fix: cross-project leak; desensitize userinfo

- internal/tools/orchestrator/scheduler/executor/plugins/k8s/ingress/extension/v1beta1/ingress.go
- internal/tools/orchestrator/scheduler/executor/plugins/k8s/ingress/networking/v1/ingress.go
fix create api-gateway ingress error
| 🇺🇸 English |  fix create api-gateway ingress error            |
| 🇨🇳 中文    |  修复创建网关 ingress 错误            |
> fix(orchestrator): create api-gateway ingress error

- apistructs/issue_stream_locale.go
- internal/apps/dop/endpoints/issue_callback.go
- internal/apps/dop/providers/issue/stream/common/model.go
- internal/apps/dop/providers/issue/stream/core/build.go
state issue event add labels
| 🇺🇸 English | Fix the bug that state issue event add labels              |
| 🇨🇳 中文    |   事项更改状态发送事件加上labels           |
> fix(dop): state issue event add labels

- internal/tools/monitor/core/settings/monitor.go
- internal/tools/monitor/core/settings/monitor_test.go
fix: modify default ttl
| 🇺🇸 English |  fix: modify default ttl  |
| 🇨🇳 中文    | 修改监控指标和日志数据的默认保存时间 |
> fix: modify default ttl

- pkg/common/errors/server.go
- pkg/common/errors/server_test.go
fix: alert overview null output `%!s(<nil>)` error
| 🇺🇸 English |    alert overview null output `%!s(<nil>)` error           |
| 🇨🇳 中文    |  告警大盘无数据时返回无意义空错误            |
> fix: alert overview null output `%!s(<nil>)` error

- cmd/monitor/streaming/conf/clickhouse/metrics/ddl_create_default_tables.sql.tpl
- cmd/monitor/streaming/conf/clickhouse/metrics/ddl_create_tenant_tables.sql.tpl
| 🇺🇸 English |    metric query optimize          |
| 🇨🇳 中文    |       指标查询优化       |
> feat: metric query optimize slow query

- internal/apps/msp/resource/deploy/handlers/apigateway/apigateway.go
- internal/tools/orchestrator/hepa/repository/service/gateway_package_api_service.go
- internal/tools/orchestrator/hepa/services/domain/impl/impl.go
set runtime domain successfully but invisible
/assign @iutx @sixther-dc @dspo @luobily 
Bugfix： Fix the bug that set runtime domain successfully but invisible（修复了设置 Runtime 的服务域名成功但不显示的问题）
| 🇺🇸 English |        Fix the bug that set runtime domain successfully but invisible      |
| 🇨🇳 中文    |         修复了设置 Runtime 的服务域名成功但不显示的问题     |
> fix: set runtime domain successfully but invisible

- cmd/monitor/collector/bootstrap-agent.yaml
- cmd/monitor/collector/bootstrap.yaml
addon-mysql monitor
| 🇺🇸 English |    addon-mysql monitor          |
| 🇨🇳 中文    |    addon-mysql 监控          |
> feat: addon-mysql monitor

- cmd/monitor/monitor/conf/alert/rules/addon/addon_elasticsearch_cpu/alert_rule.yaml
- cmd/monitor/monitor/conf/alert/rules/addon/addon_elasticsearch_mem/alert_rule.yaml
- cmd/monitor/monitor/conf/alert/rules/addon/addon_mysql_cpu/alert_rule.yaml
- cmd/monitor/monitor/conf/alert/rules/addon/addon_mysql_mem/alert_rule.yaml
- cmd/monitor/monitor/conf/alert/rules/addon/addon_mysql_slave_status/alert_rule.yaml
- cmd/monitor/monitor/conf/alert/rules/addon/addon_redis_mem/alert_rule.yaml
fix: create addon alert error
| 🇺🇸 English |    create addon alert error          |
| 🇨🇳 中文    |      修复创建 addon 监控时的异常报错        |
> fix: create addon alert error

- api/proto/core/pipeline/base/base.proto
- internal/tools/pipeline/actionagent/define.go
- internal/tools/pipeline/actionagent/execute.go
- internal/tools/pipeline/actionagent/exit.go
- internal/tools/pipeline/actionagent/file_watch_test.go
- internal/tools/pipeline/actionagent/filewatch/watch.go
- internal/tools/pipeline/actionagent/pull_bootstrap_info.go
- internal/tools/pipeline/actionagent/step_prepare.go
- internal/tools/pipeline/pkg/debug/breakpoint.go
- internal/tools/pipeline/pkg/debug/breakpoint_test.go
- internal/tools/pipeline/providers/pipeline/convert.go
- internal/tools/pipeline/providers/pipeline/create_v2.go
- internal/tools/pipeline/providers/reconciler/taskrun/taskop/prepare_test.go
- internal/tools/pipeline/providers/task/task.service.go
- internal/tools/pipeline/spec/pipeline_extra.go
- internal/tools/pipeline/spec/pipeline_task.go
- pkg/parser/pipelineyml/define.go
pipeline support debug on failure
/assign @sfwn 
| 🇺🇸 English |  Support pipeline debug on failure            |
| 🇨🇳 中文    |   实现流水线支持任务失败时断点调试           |
> feat(pipeline): pipeline support debug on failure

- cmd/erda-server/bootstrap.yaml
WRITE_LOG_TO_CLICKHOUSE_ENABLE default set to true
/assign @tomatopunk @sixther-dc 
| 🇺🇸 English |    WRITE_LOG_TO_CLICKHOUSE_ENABLE default set to true          |
| 🇨🇳 中文    |    WRITE_LOG_TO_CLICKHOUSE_ENABLE 默认设置为 true          |
> fix(msp): WRITE_LOG_TO_CLICKHOUSE_ENABLE default set to true

- internal/apps/dop/endpoints/pipeline.go
- internal/apps/dop/providers/projectpipeline/service_impl.go
- internal/apps/msp/resource/deploy/handlers/apigateway/apigateway.go
internal client request pipeline grpc interface with bundle context
/assign @sfwn 
| 🇺🇸 English |    Fix the bug that internal client request pipeline grpc interface with bundle context          |
| 🇨🇳 中文    |   修复了一些内部服务请求pipeline接口没有带上bundle的问题           |
> fix: internal client request pipeline grpc interface with bundle context

- tools/cli/cmd/push.go
- tools/cli/command/erda.go
- tools/cli/common/application.go
- tools/cli/common/issue.go
- tools/cli/common/mr.go
- tools/cli/common/project.go
- tools/cli/common/record.go
- tools/cli/common/repo.go
fix erda cli push and pull project
| 🇺🇸 English | fix erda cli push and pull project             |
| 🇨🇳 中文    |  修复 erda cli push 与 pull 项目            |
> fix: erda cli push and pull project

- cmd/monitor/monitor/conf/chartview/cmp/cmp-dashboard-podDetail.json
fix cloud manage pod detail chart, round float change to max
| 🇺🇸 English |   fix cloud manage pod detail chart, round float change to max           |
| 🇨🇳 中文    |    修改云管 pod 详情图表, round float -> max          |
> fix: fix cloud manage pod detail chart, round_float change to max

- internal/apps/admin/manager/cluster.go
- internal/apps/admin/manager/cluster_test.go
- internal/apps/admin/manager/id.go
1. fix clusters sensitive information leakage
2. add auth for get cluster
After fixed: 
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=355428&iterationID=1501&type=TASK)
| 🇺🇸 English |  fix clusters sensitive information leakage            |
| 🇨🇳 中文    |       修复集群敏感信息泄漏       |
> fix(erda-server): clusters sensitive information leakage

- cmd/erda-server/bootstrap.yaml
- cmd/erda-server/main.go
- internal/core/openapi/openapi-ng/interceptors/response/response.go
fix some security breach
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=355172&iterationID=1501&tab=TASK&type=TASK)
/assign @sfwn 
| 🇺🇸 English |  Fix the bug that some security breach            |
| 🇨🇳 中文    |     修复了两个安全漏洞         |
> fix: some security breach

- cmd/monitor/collector/bootstrap-agent.yaml
- erda.yml
fix: rename name tag to container_id
| 🇺🇸 English |      rename name tag to container_id        |
| 🇨🇳 中文    |       使用name作为容器指标的container_id字段       |
> fix: rename name tag to container_id

- internal/apps/admin/manager/cluster.go
list clusters nil ptr and missing org param
| 🇺🇸 English |  fix list clusters nil ptr and missing org param            |
| 🇨🇳 中文    |       修复集群列表空指针及缺少 org 参数问题       |
> fix: list clusters nil ptr and missing org param

- internal/core/openapi/openapi-ng/auth/over_permission/match/common.go
- internal/core/openapi/openapi-ng/auth/over_permission/org_id/check.go
- internal/core/openapi/openapi-ng/auth/over_permission/org_name/check.go
- internal/core/openapi/openapi-ng/auth/over_permission/org_name/check_test.go
/assign @sfwn 
| 🇺🇸 English |  fix: fix over_permission not work            |
| 🇨🇳 中文    |      修复越权不工作        |
> fix: fix over_permission not work

- cmd/monitor/log-service/bootstrap.yaml
- cmd/monitor/log-service/main.go
- erda.yml
- internal/apps/msp/apm/log-service/analysis/consumer.go
- internal/apps/msp/apm/log-service/analysis/processors/processors.go
- internal/apps/msp/apm/log-service/analysis/processors/regex/regex.go
- internal/apps/msp/apm/log-service/analysis/processors/regex/regex_test.go
- internal/apps/msp/apm/log-service/analysis/provider.go
- internal/apps/msp/apm/log-service/analysis/self_metrics.go
log-service use suitable regexp handler by pattern to speed up parsing.
Aleady tested on erda cloud.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=356777&iterationID=-1&type=TASK)
/assign @tomatopunk 
| 🇺🇸 English |   log-service use suitable regexp handler by pattern to speed up parsing           |
| 🇨🇳 中文    |   日志分析根据正则表达式使用合适的库来加速解析           |
> feat: log-service use suitable regexp handler by pattern

- internal/apps/msp/apm/service/components/transaction-http-error/metric_table/provider.go
fix transaction http error chart no data
| 🇺🇸 English |  fix transaction http error chart no data            |
| 🇨🇳 中文    |    修复http调用信息图标无数据          |
> fix: fix transaction http error chart no data

- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
fix cloud dashboard no data
| 🇺🇸 English |       fix cloud dashboard no data       |
| 🇨🇳 中文    |    修复云管大盘无数据          |
> fix: fix cloud dashboard no data

- internal/tools/monitor/core/metric/query/es-tsql/operator.go
- pkg/math/math.go
- pkg/math/math_test.go
fix metric inf panic
| 🇺🇸 English |  fix metric inf panic            |
| 🇨🇳 中文    |   修复指标 inf panic           |
> fix: metric inf panic

- internal/apps/dop/providers/publishitem/publish.item.service.go
fix publish-items weak permission check
/assign @sfwn 
| 🇺🇸 English |     Fix the bug that publish-items weak permission check         |
| 🇨🇳 中文    |     修复了查询发布接口弱校验的问题         |
> fix: publish-items weak permission check

- internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/rocketmq/rocketmq.go
- internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s.go
- internal/tools/orchestrator/services/addon/addon.go
- internal/tools/orchestrator/services/addon/addon_deploy.go
- internal/tools/orchestrator/services/addon/addon_test.go
- internal/tools/orchestrator/services/addon/middleware.go
- internal/tools/orchestrator/services/addon/middleware_test.go
rocketmq operator support all versions
| 🇺🇸 English |   rocketmq operator support all versions           |
| 🇨🇳 中文    |    实现rocketmq-operaotr支持所有的版本          |
> feat: rocketmq operator support all versions

- internal/apps/dop/providers/issue/core/file.go
- internal/apps/dop/providers/issue/core/file_test.go
fix issue-import stage value
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that issue-import stage value           |
| 🇨🇳 中文    |    修复了事项导入后stage值错误的问题          |
> fix(dop): issue-import stage value

- internal/apps/cmp/endpoints/cluster.go
- internal/core/legacy/endpoints/notify_item.go
- internal/core/legacy/endpoints/permission.go
- internal/tools/monitor/core/settings/settings.service.go
- internal/tools/monitor/core/settings/settings.service_test.go
fix sysadmin permission leak
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=359306&iterationID=1501&tab=TASK&type=TASK)
| 🇺🇸 English |   Fix the bug that sysadmin permission leak           |
| 🇨🇳 中文    |    修复了系统管理员权限泄露的问题          |
> fix(erda-server): sysadmin permission leak

- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
fix metric query sort no orderly
/assign @sfwn 
| 🇺🇸 English |    fix sort no orderly          |
| 🇨🇳 中文    | 修复手动排序后会导致结果无序             |
> fix: fix sort no orderly

- internal/apps/msp/apm/exception/query/source/elasticsearch_source.go
- internal/tools/monitor/core/event/persist/consume.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
/assign @sfwn 
| 🇺🇸 English |   fix error-analysis chart is empty           |
| 🇨🇳 中文    |     修复错误分析图表为空         |
> fix: error-analysis chart is empty

- cmd/monitor/monitor/bootstrap.yaml
- cmd/monitor/monitor/conf/chartview/runtime/addon-rocketmq.json
- internal/tools/monitor/core/storekit/clickhouse/table/meta/interface.go
- internal/tools/monitor/core/storekit/clickhouse/table/meta/meta_loader.go
- internal/tools/monitor/core/storekit/clickhouse/table/meta/meta_loader_test.go
- internal/tools/monitor/core/storekit/clickhouse/table/meta/provider.go
addon rocketmq monitor chart
/assign @sfwn 
| 🇺🇸 English |  addon rocketmq monitor chart            |
| 🇨🇳 中文    |    addon rocketmq 监控图表         |
> feat: addon rocketmq monitor chart

- internal/apps/msp/apm/checker/apis/checker.v1.service.go
- pkg/common/apis/header.go
fix status_page metric not ttl
/assign @sfwn 
| 🇺🇸 English |    fix status_page metric not ttl          |
| 🇨🇳 中文    |     修复 status_page 指标没有 ttl         |
> fix: fix status_page metric not ttl

- internal/apps/dop/providers/issue/core/query/convert.go
- internal/apps/dop/providers/issue/core/query/convert_test.go
- internal/tools/pipeline/providers/edgepipeline_register/edge_client.go
optimize user and time display of custom properties in issue export
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/iteration/1580/all?id=360638&iterationID=1580&tab=REQUIREMENT&type=REQUIREMENT)
/assign @sfwn 
| 🇺🇸 English |    Fix the bug that optimize user and time display of custom properties in issue export           |
| 🇨🇳 中文    |    优化了事项导出自定义字段中时间和用户信息的展示          |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/mast …
> fix(dop): optimize user and time display of custom properties in issue export

- internal/tools/orchestrator/scheduler/executor/plugins/edas/edas.go
- internal/tools/orchestrator/scheduler/executor/plugins/edas/edas_event.go
- internal/tools/orchestrator/scheduler/executor/plugins/edas/edas_test.go
- internal/tools/orchestrator/scheduler/executor/plugins/edas/utils.go
- internal/tools/orchestrator/scheduler/executor/plugins/edas/utils_test.go
fix o11 edas executor delete runtime error
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=349276&iterationID=1580&type=REQUIREMENT)
| 🇺🇸 English |  fix o11 edas executor delete application error            |
| 🇨🇳 中文    |     修复 o11 edas 删除应用失败         |
> fix(orchestrator): o11 edas executor delete application error

- internal/tools/monitor/core/metric/query/es-tsql/influxql/ckFunctions.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
clickhouse query agg column should be exist
| 🇺🇸 English |        clickhouse query agg column should be exist      |
| 🇨🇳 中文    | clickhouse查询时, 聚合列应当存在             |
> fix: clickhouse query agg column should be exist

- apistructs/addon.go
- internal/apps/dop/dicehub/release/release.service.go
- internal/pkg/addonutil/addonutil.go
- internal/pkg/addonutil/addonutil_test.go
- internal/tools/orchestrator/dbclient/addon_instance.go
- internal/tools/orchestrator/services/addon/addon.go
- internal/tools/orchestrator/services/addon/addon_handler.go
project release addon render error
cause by addon name alias
| 🇺🇸 English |    fix project release addon render error          |
| 🇨🇳 中文    |    修复项目级制品 addon 渲染失败错误          |
> fix: project release addon render error

- cmd/monitor/collector/bootstrap.yaml
fix service list no otel data
/assign @sfwn 
| 🇺🇸 English |    service list no otel data          |
| 🇨🇳 中文    |      修复服务列表无 otel 数据        |
> fix: service list no otel data

- cmd/monitor/collector/bootstrap.yaml
- internal/apps/msp/apm/service/components/service-list/provider.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
fix service list no data
* agg column not should exist, metric model is difference
* span not compatibility tag
fix service list no data
/assign @sfwn 
| 🇺🇸 English |     fix service list no data         |
| 🇨🇳 中文    |    修复服务列表无数据          |
> fix: fix service list no data

- internal/tools/orchestrator/components/runtime/runtime.service.go
- internal/tools/orchestrator/scheduler/executor/plugins/edas/edas.go
- internal/tools/orchestrator/scheduler/executor/plugins/edas/edas_test.go
fix edas runtime replicas show error
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=361219&iterationID=1580&type=TASK)
| 🇺🇸 English | fix edas runtime replicas show error             |
| 🇨🇳 中文    |     修复 edas runtime 副本数显示错误         |
> fix(orchestrator): edas runtime replicas show error

- internal/tools/orchestrator/endpoints/instance.go
- internal/tools/orchestrator/scheduler/executor/plugins/edas/edas.go
- internal/tools/orchestrator/scheduler/executor/plugins/edas/utils.go
- internal/tools/orchestrator/scheduler/executor/plugins/edas/utils_test.go
- internal/tools/orchestrator/scheduler/executor/plugins/k8s/deployment.go
fix o11 edas pod status show error
| 🇺🇸 English | fix o11 edas pod status show error             |
| 🇨🇳 中文    |        修复 edas pod 状态显示错误      |
> fix(orchestrator): o11 edas pod status show error

- internal/tools/monitor/core/storekit/clickhouse/table/meta/provider.go
fix org metric not show meta
/assign @sfwn 
| 🇺🇸 English |  fix org metric not show meta            |
| 🇨🇳 中文    |     修复无 org 的指标不能展示 meta         |
> fix: fix org metric not show meta

- build/scripts/docker_image.sh
polish: move arch from image tag to repository, like: `${prefix}/erda/arm64/erda-server:${tag}`
/assign @iutx 
| 🇺🇸 English |   polish: move arch from image tag to repository         |
| 🇨🇳 中文    |   优化：将 arch 从镜像 Tag 移动至 Repository           |
> build: move arch from image tag to repository

- build/dockerfiles/Dockerfile-volume-provisioner
- build/dockerfiles/cluster-agent/Dockerfile
- build/scripts/docker_image.sh
volume-provisioner and cluster-agent support arm arch
| 🇺🇸 English |   volume-provisioner and cluster-agent support arm arch           |
| 🇨🇳 中文    |   volume-provisioner \ cluster-agent 支持 arm           |
> feat: volume-provisioner and cluster-agent support arm arch

- cmd/monitor/monitor/bootstrap.yaml
- internal/tools/monitor/apm/topology/provider.go
- internal/tools/monitor/apm/topology/routes.go
- internal/tools/monitor/apm/topology/topology.go
- internal/tools/monitor/apm/topology/topology_test.go
- internal/tools/monitor/apm/topology/topology_v2.go
- internal/tools/monitor/apm/topology/topology_v2_test.go
topology merge TargetOtherNode by httpUrl
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=357636&iterationID=1580&tab=BUG&type=BUG)
/assign @tomatopunk 
| 🇺🇸 English |    topology merge TargetOtherNode by httpUrl          |
| 🇨🇳 中文    |   监控拓扑图根据 httpUrl 合并外部接口节点           |
> feat: topology merge TargetOtherNode by httpUrl

- cmd/monitor/streaming/bootstrap.yaml
- internal/apps/cmp/metrics/metrics.go
- internal/tools/monitor/core/log/persist/v1/provider_test.go
- internal/tools/monitor/core/settings/retention-strategy/provider.go
- internal/tools/monitor/core/settings/retention-strategy/ttl.go
- internal/tools/monitor/core/storekit/clickhouse/table/initializer/init.go
- internal/tools/monitor/core/storekit/clickhouse/table/initializer/mock_test.go
- internal/tools/monitor/core/storekit/clickhouse/table/initializer/provider.go
- internal/tools/monitor/core/storekit/clickhouse/table/initializer/ttl_sync.go
- internal/tools/monitor/core/storekit/clickhouse/table/initializer/ttl_sync_test.go
- internal/tools/monitor/core/storekit/clickhouse/table/loader/provider.go
- internal/tools/monitor/core/storekit/clickhouse/table/loader/table_loader.go
- internal/tools/monitor/core/storekit/clickhouse/table/loader/table_meta.go
- internal/tools/monitor/core/storekit/clickhouse/table/loader/table_meta_test.go
- internal/tools/monitor/core/storekit/clickhouse/table/table.go
- internal/tools/monitor/core/storekit/clickhouse/table/table_test.go
- internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/metric/metric_test.go
clickhouse cold hot ddl
/assign @sfwn 
| 🇺🇸 English |  clickhouse cold hot ddl            |
| 🇨🇳 中文    |       clickhouse 冷热 ddl       |
> feat: clickhouse cold hot ddl

- cmd/monitor/streaming/bootstrap.yaml
- erda.yml
optimize streaming resource
default kafka partition 24 
| 🇺🇸 English |  optimize streaming resource            |
| 🇨🇳 中文    |    优化 streaming 资源          |
> fix: optimize streaming resource

- .github/workflows/ci-it-noneed.yml
- .github/workflows/ci-it.yml
- .github/workflows/git-sync.yml
- .github/workflows/license.yml
fetch whole repo for scenarios like codecov in CI
| 🇺🇸 English |   fetch whole repo for scenarios like codecov in CI           |
| 🇨🇳 中文    |   在 CI 中拉取整个仓库，用于例如 codecov 的场景           |
> ci: fetch whole repo for scenarios like codecov

- api/proto/oap/collector/receiver/opentelemetry/opentelemetry.proto
- api/proto/oap/common/common.proto
- api/proto/oap/opentelemetry/metrics.proto
- internal/tools/monitor/oap/collector/plugins/receivers/collector/collector.go
- internal/tools/monitor/oap/collector/plugins/receivers/opentelemetry/otlp.service.go
- internal/tools/monitor/oap/collector/plugins/receivers/opentelemetry/provider.go
add otlp metric api
| 🇺🇸 English |         add otlp metric api     |
| 🇨🇳 中文    |         增加otlp metric api     |
> feat: add otlp metric api

- cmd/monitor/monitor/conf/i18n/settings.yml
- internal/tools/monitor/core/settings/monitor.go
- internal/tools/monitor/core/settings/monitor_test.go
- internal/tools/monitor/core/settings/ttl.go
- internal/tools/monitor/core/settings/ttl_test.go
- internal/tools/monitor/core/storekit/clickhouse/table/initializer/ttl_sync.go
add hot ttl config
/assign @sfwn 
| 🇺🇸 English |   add hot ttl config           |
| 🇨🇳 中文    |    添加热数据 TTL 配置          |
> feat: add hot ttl config

- internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/canal/canal.go
feat: canal zk to global
| 🇺🇸 English |     feat: canal zk to global         |
| 🇨🇳 中文    |       feat: canal zk to global        |
> feat: canal zk to global

- pkg/parser/diceyml/platform_visitor.go
- pkg/parser/diceyml/platform_visitor_test.go
fix  dice yml platform visitor match error
/assign @sixther-dc @chengjoey @sfwn @dspo 
| 🇺🇸 English |  fix  dice yml platform visitor match error            |
| 🇨🇳 中文    |    修复 dice.yml platforminfo visitor 正则匹配错误          |
> fix(orchestrator): dice yml platform visitor match error

- internal/tools/monitor/core/storekit/clickhouse/table/initializer/init.go
- internal/tools/monitor/core/storekit/clickhouse/table/initializer/mock_test.go
- internal/tools/monitor/core/storekit/clickhouse/table/initializer/provider.go
- internal/tools/monitor/core/storekit/clickhouse/table/initializer/ttl_sync.go
- internal/tools/monitor/core/storekit/clickhouse/table/initializer/ttl_sync_test.go
fix ddl sync nil point
/assign @sfwn 
| 🇺🇸 English |    fix ddl sync nil point          |
| 🇨🇳 中文    |    修复 ddl sync 空指针          |
> fix: fix ddl sync nil point

- internal/tools/monitor/core/storekit/clickhouse/table/initializer/ttl_sync.go
ddl in high frequency execution
/assign @sfwn 
| 🇺🇸 English |     fix ddl in high frequency execution         |
| 🇨🇳 中文    |     修复 ddl 被高频率执行         |
> fix: ddl in high frequency execution

- internal/tools/orchestrator/services/addon/addon_handler.go
skip addon dice.yml validate, some platform addon, such as registercenter don't need to validate. 
| 🇺🇸 English |  skip addon dice.yml validate            |
| 🇨🇳 中文    |    跳过 addon dice.yml 校验          |
> fix: skip addon dice.yml validate

- internal/tools/monitor/core/dataview/db/db.go
fix micro dashboard error, orderby column should by select
/assign @sfwn 
| 🇺🇸 English | fix micro dashboard error, orderby column should by select             |
| 🇨🇳 中文    |   修复微服务大盘错误, orderby 列必须在 select 中存在           |
> fix: fix micro dashboard error, orderby column should by select

- internal/apps/dop/providers/project/home/service.go
- internal/apps/dop/services/apierrors/errors.go
fix permission leak for project home
/assign @sfwn 
| 🇺🇸 English |  Fix permission leak for project home             |
| 🇨🇳 中文    |     修复了项目主页权限校验较弱的问题         |
> fix(dop): permission leak for project home

- internal/tools/monitor/core/storekit/clickhouse/table/initializer/ttl_sync.go
/assign @sfwn
| 🇺🇸 English |      append debug logs ttl sync        |
| 🇨🇳 中文    |    添加 ttl sync debug 日志          |
> fix: fix append debug logs ttl sync

- internal/apps/msp/tenant/project/project.service.go
/assign @sfwn 
| 🇺🇸 English |      fix: fix msp/tenant/project over permission        |
| 🇨🇳 中文    |       修复  msp/tenant/project接口越权     |
> fix: fix msp/tenant/project over permission

- build/dockerfiles/cluster-agent/Dockerfile
Upgrade kubectl version to erda default deploy version(1.24.x).
| 🇺🇸 English |  upgrade kubectl version            |
| 🇨🇳 中文    | 升级 kubectl 版本             |
> feat: upgrade kubectl version

- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
fix metric query time function no order
/assign @sfwn 
| 🇺🇸 English |  fix metric query time function no order            |
| 🇨🇳 中文    |    修复指标查询, time 方法 失去排序的 bug          |
> fix: fix metric query time function no order

- internal/apps/msp/apm/service/apm.service.service.go
fix metric model not stand,invoke agg column hits
/assign @sfwn 
| 🇺🇸 English |      fix metric model not stand,invoke agg column hits        |
| 🇨🇳 中文    |    修复因指标模型不一致,引起的聚合列被命中          |
> fix: fix metric model not stand,invoke agg column hits

- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
fix metric aggr function parse error
/assign @sfwn 
| 🇺🇸 English |  fix metric aggr function parse error            |
| 🇨🇳 中文    |    修复指标查询 聚合函数转换的错误          |
> fix: fix metric aggr function parse error

- cmd/monitor/collector/bootstrap.yaml
- internal/tools/monitor/oap/collector/core/pipeline/pipeline.go
- internal/tools/monitor/oap/collector/plugins/receivers/promremotewrite/provider.go
feat: collect metric append org tag
/assign @sfwn 
| 🇺🇸 English |    feat: collect metric append org tag          |
| 🇨🇳 中文    |     collect 指标追加 org tag         |
> feat: collect metric append org tag

- cmd/monitor/streaming/bootstrap.yaml
- internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/storage.go
fix: fix collector pool run out frequently
/assign @sfwn 
| 🇺🇸 English |   fix: fix collector pool run out frequently           |
| 🇨🇳 中文    |     修复 collect 池频繁的耗尽         |
Add comment like `/cherry-pick release/2.3` when this PR is merged.
> fix: fix collector pool run out frequently

- internal/apps/msp/apm/service/view/table/transaction.go
fix error count table no order
/assign @sfwn 
| 🇺🇸 English |     fix error count table no order         |
| 🇨🇳 中文    |    修复 错误调用次数 排序失效的问题          |
Add comment like `/cherry-pick release/2.3` when this PR is merged.
> fix: fix error count table no order

- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
sometime time colum no orderly
/assign @sfwn 
| 🇺🇸 English |      sometime time colum no orderly         |
| 🇨🇳 中文    |       某时 时间列无序       |
> fix: sometime time colum no orderly

- internal/apps/msp/apm/service/apm.service.service.go
fix application_service_node no application_service_node
/assign @sfwn 
| 🇺🇸 English |    fix application_service_node no target_service_id          |
| 🇨🇳 中文    |    修复   application_service_node   无target_service_id 的问题    |
> fix: fix application_service_node no target_service_id

- cmd/monitor/collector/bootstrap.yaml
arm containerd no match container id
/assign @sfwn 
| 🇺🇸 English |    arm containerd no match container id          |
| 🇨🇳 中文    |     修复 arm containerd 环境无法匹配到的 container id 问题         |
> fix: arm containerd no match container id

- internal/tools/orchestrator/scheduler/executor/plugins/k8s/service.go
- internal/tools/orchestrator/scheduler/executor/plugins/k8s/service_test.go
fix create service failure due to invalid label or selector
add validation for label and selector
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=371704&iterationID=1580&tab=BUG&type=BUG)
| 🇺🇸 English |     fix create service failure due to invalid label or selector         |
| 🇨🇳 中文    |    修复了由于非法的标签造成的service部署失败的问题          |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBU …
> fix(orchestrator): create service failure due to invalid label or selector

- Makefile
- internal/apps/msp/resource/deploy/handlers/configcenter/configcenter.go
- internal/apps/msp/resource/deploy/handlers/nacos/nacos.go
- internal/apps/msp/resource/deploy/handlers/registercenter/registercenter.go
feat: nacos grpc port
| 🇺🇸 English | nacos grpc port |
| 🇨🇳 中文    | nacos gRPC 端口 |
> feat: nacos grpc port

- go.mod
update go.mod(especially erda-proto-go) for later auto update by github
| 🇺🇸 English |   update go.mod(especially erda-proto-go) for later auto update by github           |
| 🇨🇳 中文    |   更新 go.mod 来适配 github 的自动 go.mod 更新           |
> chore: update go.mod(especially erda-proto-go) for later auto update by github

- internal/apps/dop/providers/contribution/provider.go
workbench contribution add permission check
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=372746&iterationID=1628&type=BUG)
| 🇺🇸 English |    fix: workbench contribution add permission check          |
| 🇨🇳 中文    |  修复：个人工作台贡献度增加权限校验             |
Add comment like `/cherry-pick release/2.3` when this PR is merged.
> fix: workbench contribution permission leak

- cmd/monitor/collector/bootstrap.yaml
fix: fix tail suffix container id not match
/assign @sfwn
| 🇺🇸 English | fix: fix tail suffix container id not match             |
| 🇨🇳 中文    |   修复尾部带有词缀的 container id 无法匹配           |
> fix: fix tail suffix container id not match

- api/proto/core/monitor/alert/alert.proto
- internal/apps/msp/apm/alert/alert.service.go
- internal/tools/monitor/core/alert/alert-apis/adapt/alert.go
- internal/tools/monitor/core/alert/alert-apis/alert.service.go
- internal/tools/monitor/core/alert/alert-apis/db/alert.go
fix: alert over permission
/assign @sfwn 
| 🇺🇸 English |  fix: alert over permission            |
| 🇨🇳 中文    |    修复告警列表越权          |
> fix: alert over permission

- internal/apps/msp/apm/checker/apis/checker.v1.service.go
- internal/apps/msp/apm/checker/apis/checker.v1.service_test.go
fix: fix checker table no data
/assign @sfwn 
| 🇺🇸 English |    fix: fix checker table no data          |
| 🇨🇳 中文    |    修复主动监控列表无数据          |
> fix: fix checker table no data

- internal/apps/msp/apm/checker/apis/checker.v1.service.go
fix check monitor detail no data
/assign @sfwn 
| 🇺🇸 English |      fix check monitor detail no data        |
| 🇨🇳 中文    |       修复制动监控 detail 无数据       |
> fix: fix check monitor detail no data

- internal/tools/orchestrator/hepa/apipolicy/policies/csrf/policy.go
- internal/tools/orchestrator/hepa/apipolicy/policies/sbac/policy.go
- internal/tools/orchestrator/hepa/gateway-providers/dto/credential_resp_dto.go
- internal/tools/orchestrator/hepa/gateway-providers/mse/common/constant.go
- internal/tools/orchestrator/hepa/gateway-providers/mse/dto/mse_plugin_configuration.go
- internal/tools/orchestrator/hepa/gateway-providers/mse/mse_adapter.go
- internal/tools/orchestrator/hepa/gateway-providers/mse/mse_adapter_test.go
- internal/tools/orchestrator/hepa/gateway-providers/mse/mse_openapi.go
- internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/common.go
- internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/common_test.go
- internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/mse_hmac_auth.go
- internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/mse_hmac_auth_test.go
- internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/mse_key_auth.go
- internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/mse_para_sign_auth.go
- internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/mse_para_sign_auth_test.go
- internal/tools/orchestrator/hepa/services/endpoint_api/impl/impl.go
- internal/tools/orchestrator/hepa/services/openapi_consumer/impl/impl.go
- internal/tools/orchestrator/hepa/services/openapi_consumer/impl/impl_test.go
- internal/tools/orchestrator/hepa/services/openapi_rule/impl/impl.go
- internal/tools/orchestrator/hepa/services/openapi_rule/interface.go
Hepa supports MSE custom plugin para-sign-auth  
/assign @dspo @iutx @sixther-dc @luobily 
Feature: Support MSE custom plugin para-sign-auth in hepa（Erda 网关支持 MSE 自定义鉴权插件 para-sign-auth）
| 🇺🇸 English |    Support MSE custom plugin para-sign-auth in hepa      |
| 🇨🇳 中文    |     Erda 网关支持 MSE 自定义鉴权插件 para-sign-auth        |
> feat: hepa support mse para-sign-auth plugin

- tools/cli/cmd/gw_debug_auth.go
feat: erda-cli hmac client
| 🇺🇸 English | feat: erda-cli hmac client |
| 🇨🇳 中文    | hmac debug 客户端工具 |
> feat: erda-cli hmac client

- internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sflink/util.go
fix flinkcluster job missing log due to org annotations
/assign @sfwn 
| 🇺🇸 English |  Fix the bug that flinkcluster job missing log due to org annotations            |
| 🇨🇳 中文    |    修复了flinkcluster的job任务丢失日志的问题          |
> fix(pipeline): flinkcluster job missing log due to org annotations

- internal/apps/ai-proxy/filters/audit/filter_test.go
- internal/apps/ai-proxy/filters/log-http/filter.go
Optimize http log printing
| 🇺🇸 English | Optimize http log printing             |
| 🇨🇳 中文    | 优化 http log 打印 |
> feat: loghttp

- build/dockerfiles/Dockerfile
use taobao npm registry install jackson-converter
| 🇺🇸 English |        use taobao npm registry install jackson-converter      |
| 🇨🇳 中文    |         使用淘宝源安装  jackson-converter  npm包    |
> fix: use taobao npm registry install jackson-converter

- build/dockerfiles/Dockerfile
- pipeline.yml
fix: use aliyun pypi to install package
| 🇺🇸 English |         use aliyun pypi to install package     |
| 🇨🇳 中文    |           使用阿里云的源安装python包   |
> fix: use aliyun pypi to install package

- build/dockerfiles/Dockerfile
fix: use tsinghua  pypi to install package
| 🇺🇸 English |        use tsinghua  pypi to install package      |
| 🇨🇳 中文    |         使用pypi的清华源     |
> fix: use tsinghua  pypi to install package

- pipeline.yml
fix: enable monitor-injector
| 🇺🇸 English |        fix: enable monitor-injector      |
| 🇨🇳 中文    |          开启   monitor-injector 组件 |
> fix: enable monitor-injector

- internal/tools/orchestrator/conf/conf.go
- internal/tools/orchestrator/scheduler/executor/plugins/k8s/deployment.go
- internal/tools/orchestrator/scheduler/executor/plugins/k8s/deployment_test.go
add collector env to dice service
```go
// add collector url
collectorUrl := conf.CollectorPublicURL()
if sg.ClusterName == conf.MainClusterName() {
collectorUrl = fmt.Sprintf("http://%s", discover.Collector())
}
envs = append(envs, corev1.EnvVar{
Name:  "DICE_COLLECTOR_URL",
Value: collectorUrl,
})
```
| 🇺🇸 English |    add collector env to dice service          |
| 🇨🇳 中文    |    在 dice 服务中增加 collector 环境变量          |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a- …
> feat(orchestrator): add collector env to dice service

- internal/tools/monitor/core/profile/query/app.go
fix query profile app missing url query
/assign @sfwn 
| 🇺🇸 English |     fix query profile app missing url query          |
| 🇨🇳 中文    |  修复了查询可持续性应用时丢失参数的问题            |
> fix(monitor): query profile app missing url query

- internal/tools/monitor/core/settings/retention-strategy/ttl.go
- internal/tools/monitor/oap/collector/core/pipeline/pipeline.go
/assign @sfwn 
| 🇺🇸 English |     fix streaming no data          |
| 🇨🇳 中文    |     修复 streaming 无数据         |
> fix: fix streaming no data

- internal/tools/orchestrator/hepa/apipolicy/policies/csrf/dto.go
- internal/tools/orchestrator/hepa/apipolicy/policies/csrf/policy.go
- internal/tools/orchestrator/hepa/apipolicy/policies/ip/policy.go
- internal/tools/orchestrator/hepa/apipolicy/policies/sbac/dto.go
- internal/tools/orchestrator/hepa/apipolicy/policies/sbac/policy.go
- internal/tools/orchestrator/hepa/apipolicy/policies/sbac/policy_test.go
- internal/tools/orchestrator/hepa/gateway-providers/mse/common/constant.go
- internal/tools/orchestrator/hepa/gateway-providers/mse/dto/mse_plugin_configuration.go
- internal/tools/orchestrator/hepa/gateway-providers/mse/mse_adapter.go
- internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/common.go
- internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/mse_erda_ip.go
- internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/mse_erda_sbac.go
- internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/mse_erda_sbac_test.go
- internal/tools/orchestrator/hepa/services/api_policy/impl/impl.go
- internal/tools/orchestrator/hepa/services/endpoint_api/impl/impl.go
Hepa support MSE custom plugin erda-sbac
/assign @dspo @luobily @sixther-dc @sfwn 
Feature: Support MSE custom erda-sbac in hepa（Hepa 支持接入 MSE 自定义插件 erda-sbac ）
| 🇺🇸 English |       Support MSE custom erda-sbac in hepa       |
| 🇨🇳 中文    |      Hepa 支持接入 MSE 自定义插件 erda-sbac        |
cherry-pick release/2.3
> feat: hepa support mse erda-sbac

- cmd/monitor/streaming/bootstrap.yaml
- internal/tools/monitor/oap/collector/plugins/receivers/kafka/provider.go
/assign @sfwn
| 🇺🇸 English |  fix: fix drop future metric data            |
| 🇨🇳 中文    |    丢弃未来指标          |
> fix: fix drop future metric data

- internal/tools/monitor/oap/collector/plugins/receivers/kafka/provider.go
fix: fix receiver_droped metric error
/assign @sfwn 
| 🇺🇸 English |    fix: fix receiver_droped metric error          |
| 🇨🇳 中文    |     修复 receiver_droped 指标报错        |
> fix: fix receiver_droped metric error

- .github/workflows/ci-it.yml
- cmd/ai-proxy/conf/providers.yml
- cmd/ai-proxy/conf/routes.yml
- internal/apps/ai-proxy/filters/audit/filter.go
- internal/apps/ai-proxy/filters/audit/filter_test.go
- internal/apps/ai-proxy/filters/log-http/filter.go
- internal/apps/ai-proxy/provider.go
- internal/pkg/ai-proxy/route/route.go
- pkg/reverseproxy/buffer.go
- pkg/reverseproxy/buffer_test.go
- pkg/reverseproxy/reverseproxy.go
- pkg/reverseproxy/transport.go
- pkg/reverseproxy/transport_test.go
feat: create on audit on request, update on audit on response
| 🇺🇸 English | feat: create on audit on request, update on audit on response              |
| 🇨🇳 中文    | audit filter 在 request 阶段插入数据, 在 response 阶段更新数据             |
> feat: create on audit on request, update on audit on response

- internal/tools/orchestrator/hepa/apipolicy/policies/csrf/policy.go
- internal/tools/orchestrator/hepa/apipolicy/policies/sbac/policy.go
- internal/tools/orchestrator/hepa/apipolicy/policy_engine.go
- internal/tools/orchestrator/hepa/gateway-providers/mse/common/constant.go
- internal/tools/orchestrator/hepa/gateway-providers/mse/dto/mse_plugin_configuration.go
- internal/tools/orchestrator/hepa/gateway-providers/mse/mse_adapter.go
- internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/common.go
- internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/mse_erda_csrf.go
- internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/mse_erda_csrf_test.go
- internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/mse_erda_sbac.go
- internal/tools/orchestrator/hepa/services/api_policy/impl/impl.go
- internal/tools/orchestrator/hepa/services/endpoint_api/impl/impl.go
Hepa MSE Gateway Support policy csrf by custom MSE plugin erda-csrf 
/assign @dspo @luobily @sixther-dc @sfwn 
Feature: Hepa MSE Gateway Support policy csrf by custom MSE plugin erda-csrf  （Heap 通过 MSE 网关自定义插件实现 跨站防护策略）
| 🇺🇸 English |      Hepa MSE Gateway Support policy csrf by custom MSE plugin erda-csrf      |
| 🇨🇳 中文    |      Heap 通过 MSE 网关自定义插件实现 跨站防护策略     |
> feat: hepa support mse erda-csrf

- internal/apps/cmp/steve/schemas.go
fix the surge in the number of goroutines caused by api change in erda-server
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/iteration/1628/all?id=385276&iterationID=1628&tab=TASK&type=TASK)
/assign @sfwn 
| 🇺🇸 English |   fix the surge in the number of goroutines caused by api change in erda-server           |
| 🇨🇳 中文    |      修复了erda-server的gouroutines数量激增的问题        |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master …
> fix(cmp): the surge in the number of goroutines caused by api change in erda-server

- internal/apps/msp/apm/trace/span.go
- internal/tools/monitor/core/log/log.go
- internal/tools/monitor/core/log/storage/clickhouse/writer.go
- internal/tools/monitor/core/metric/metric.go
- internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/metric/metric.go
- internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/metric/metric_test.go
- internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/span/span.go
- internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/span/span_test.go
- internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/storage.go
fix streaming no write
/assign @sfwn 
| 🇺🇸 English |      fix streaming no write        |
| 🇨🇳 中文    |     修复 streaming不写入         |
> fix: fix streaming no write

- go.mod
- go.sum
- internal/tools/monitor/core/profile/query/metrics.go
- internal/tools/monitor/core/profile/query/render-diff.go
- internal/tools/monitor/core/profile/query/render.go
feat: add profiling query metrics
/assign @sfwn 
| 🇺🇸 English |   add profiling query metrics           |
| 🇨🇳 中文    |     增加可持续性分析查询指标         |
> feat(monitor): add profiling query metrics

- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
/assign @sfwn
| 🇺🇸 English |     fix: fix clickhouse parser sql no order         |
| 🇨🇳 中文    |      修复 clickhouse parser sql 无序        |
> fix: fix clickhouse parser sql no order

- api/proto/core/org/org.proto
- internal/core/org/db/org.go
- internal/core/org/org.go
feat: add field config.enableAI to org
| 🇺🇸 English | feat: add field config.enableAI to org             |
| 🇨🇳 中文    | org config 增加 enableAI 字段             |
> feat: add field config.enableAI to org

- cmd/monitor/monitor/conf/alert/rules/app_resource/app_resource_container_network/alert_rule.yaml
- cmd/monitor/monitor/conf/alert/rules/app_resource/app_resource_container_network/analyzer_expression.json
- cmd/monitor/monitor/conf/alert/rules/app_resource/app_resource_container_network/notify_template.yaml
- cmd/monitor/monitor/conf/charts/report.yml
- cmd/monitor/monitor/conf/i18n/alert.yml
- cmd/monitor/monitor/conf/notify/monitor/app_resource/app_resource_container_network.yaml
- internal/tools/monitor/core/alert/alert-apis/adapt/expression.go
add pod network alert-rule
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=385999&iterationID=1737&tab=REQUIREMENT&type=REQUIREMENT)
/assign @sfwn 
| 🇺🇸 English |   add pod network alert-rule           |
| 🇨🇳 中文    |     微服务治理增加网络收发速率异常告警规则         |
> feat(monitor): add pod network alert-rule

- cmd/monitor/monitor/conf/chartview/cmp/cmp-dashboard-podDetail.json
- cmd/monitor/monitor/conf/chartview/frontend/ajax_overview.json
- cmd/monitor/monitor/conf/chartview/frontend/browser_overview.json
- cmd/monitor/monitor/conf/chartview/frontend/domain_overview.json
- cmd/monitor/monitor/conf/chartview/frontend/script_overview.json
- internal/apps/msp/apm/service/components/resources-node-monitor/node/provider.go
- internal/tools/monitor/apm/topology/topology.go
- internal/tools/monitor/apm/topology/topology_test.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/column.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
- internal/tools/monitor/core/metric/storage/clickhouse/query.go
fix single column no order
| 🇺🇸 English |    fix single column no order          |
| 🇨🇳 中文    |      修复单个列时无序        |
> fix: single column no order

- internal/apps/cmp/resource/class.go
- internal/apps/cmp/tasks/collect_daily_quota.go
- internal/apps/devflow/issuerelation/db/define.go
- internal/apps/dop/dao/label_relation.go
- internal/apps/dop/dao/nexus_repository.go
- internal/apps/dop/dao/ticket.go
- internal/apps/dop/dicehub/dbclient/release.go
- internal/apps/dop/dicehub/release/db/label_relation.go
- internal/apps/dop/dicehub/release/db/release.go
- internal/apps/dop/providers/issue/dao/core.go
- internal/apps/dop/providers/issue/dao/issue_testplancaserel_rel.go
- internal/apps/dop/providers/issue/dao/label_relation.go
- internal/apps/dop/services/code_coverage/code_coverage.go
- internal/apps/gallery/handler/funcs_test.go
- internal/core/legacy/dao/label_relation.go
- internal/core/legacy/dao/member.go
- internal/core/legacy/dao/nexus_repository.go
- internal/core/legacy/dao/project.go
- internal/core/legacy/dao/workspace.go
- internal/core/legacy/services/project/project.go
- internal/core/messenger/notify/db/notify_history.go
- internal/tools/monitor/core/metric/storage/elasticsearch/query_test.go
- internal/tools/orchestrator/dbclient/deployment.go
- internal/tools/orchestrator/scheduler/instanceinfo/instanceinfo.go
remove sql-level debug, use global db-level config
| 🇺🇸 English |    remove sql-level debug, use global db-level config          |
| 🇨🇳 中文    |   删除 SQL 级别的调试，使用全局数据库级别配置           |
> chore(sql): remove sql-level debug, use global db-level config

- apistructs/job.go
- apistructs/job_test.go
- apistructs/service.go
- internal/tools/pipeline/pipengine/actionexecutor/logic/job.go
- internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sjob/k8sjob.go
- internal/tools/pipeline/pkg/container_provider/container_instance_provider.go
- internal/tools/pipeline/providers/pipeline/create_task.go
- internal/tools/pipeline/providers/reconciler/taskrun/taskop/prepare.go
- internal/tools/pipeline/spec/pipeline_task.go
- pkg/parser/pipelineyml/generate_test.go
- pkg/parser/pipelineyml/graph_pipelineyml.go
pipeline job support network mode
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=362555&iterationID=1580&type=TASK)
| 🇺🇸 English |  Support pipeline job support network mode             |
| 🇨🇳 中文    |     实现流水线普通任务支持配置容器网络         |
> feat: pipeline job support network mode

- .erda/migrations/monitor/20230609-profile-name-length.sql
extend profile name field length
/assign @sfwn 
| 🇺🇸 English | Fix the bug that extend profile name field length             |
| 🇨🇳 中文    |      修复了持续性分析应用因名称长度无法写入的问题        |
> fix(monitor): extend profile name field length

- pipeline.yml
feat: add ai-proxy to pipeline.yml release action
| 🇺🇸 English | feat: add ai-proxy to pipeline.yml release action             |
| 🇨🇳 中文    | ai-proxy image 加入 release action             |
> feat: add ai-proxy to pipeline.yml release action

- internal/apps/dop/providers/issue/core/file.go
- internal/apps/dop/providers/issue/core/query/convert.go
- internal/apps/dop/providers/issue/core/query/convert_test.go
- internal/apps/dop/providers/issue/core/query/issueexcel/import.go
- internal/apps/dop/providers/issue/core/query/issueexcel/import_test.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheet_custom_field.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheet_issue_export.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheet_issue_import.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheet_issue_import_old.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheet_iteraion.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheet_label.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheet_user.go
- internal/apps/dop/providers/issue/dao/label_relation.go
1. ExportExcelAsync add desc when failed
2. manhour support 1w1d1h1m when import
3. support old old excel format which only have 18 fields when import
4. others
| 🇺🇸 English |   fix bunch of issue import issues            |
| 🇨🇳 中文    |   修复了一些导入问题           |
> fix(dop): issue import

- .erda/migrations/ai-proxy/20230425-filter-audit.sql
- .erda/migrations/config.yml
fix: miglint for ai-proxy
| 🇺🇸 English | fix: miglint for ai-proxy              |
| 🇨🇳 中文    |  修复 ai-proxy migration 规约            |
> fix: miglint for ai-proxy

- erda.yml
fix: ai-proxy resource
| 🇺🇸 English | fix: ai-proxy resource             |
| 🇨🇳 中文    | 修复 ai-proxy resource             |
> fix: ai-proxy resource

- internal/apps/msp/apm/service/view/card/avg_duration.go
/assign @sfwn 
| 🇺🇸 English |      fix avg rps single point no consistency         |
| 🇨🇳 中文    |    修复平均 rps 在单个点时数据的不一致          |
> fix: fix avg rps single point no consistency

- internal/apps/msp/apm/service/components/service-list/provider.go
| 🇺🇸 English |   fix: fix overview error rate no true           |
| 🇨🇳 中文    |     修复总览错误率不准         |
> fix: fix overview error rate no true

- internal/apps/msp/resource/deploy/coordinator/coordinator.go
fix: etcd mutex context leak on deploying addon
| 🇺🇸 English | fix: etcd mutex context leak on deploying addon             |
| 🇨🇳 中文    |  修复部署 addon 时 etcd mutex context 泄漏的问题            |
> fix: etcd mutex context leak on deploying addon

- internal/apps/dop/providers/issue/core/query/issueexcel/sheet_issue_import_old.go
remove empty rows when import for old format
| 🇺🇸 English |   remove empty rows when import for old format           |
| 🇨🇳 中文    |   导入旧格式时删除空行           |
Add comment like `/cherry-pick release/2.4-beta.1` when this PR is merged.
> chore: remove empty rows when import for old format

- .erda/migrations/qa/20230619-issue-import-desc-length.sql
enlarge desc field of erda_file_record table for error exhibition
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/ticket?id=430184&iterationID=-1&type=TICKET)
| 🇺🇸 English |   enlarge desc field of erda_file_record table for error exhibition           |
| 🇨🇳 中文    |   扩大erda_file_record表中的desc字段，以展示错误           |
Add comment like `/cherry-pick release/2.4-beta.1` when this PR is merged.
> chore: enlarge desc field of erda_file_record table for error exhibition

- internal/apps/dop/conf/conf.go
- internal/apps/dop/dao/file_records.go
- internal/apps/dop/initialize.go
- internal/apps/dop/services/testcase/file_records.go
file record add timeout logic
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=430985&iterationID=1841&tab=TASK&type=BUG)
| 🇺🇸 English |     file record add timeout logic          |
| 🇨🇳 中文    |    文件记录添加超时处理逻辑          |
> fix: file record add timeout logic

- api/proto/msp/apm/log-service/log_query.proto
- apistructs/profile.go
- bundle/profile.go
- cmd/erda-server/bootstrap.yaml
- cmd/erda-server/conf/i18n/msp-i18n.yaml
- cmd/monitor/streaming/bootstrap.yaml
- go.mod
- go.sum
- internal/apps/msp/apm/log-service/query/log.service.go
- internal/apps/msp/apm/log-service/query/log.service.histogram.go
- internal/apps/msp/apm/service/common/slow-transaction/inparams.go
- internal/apps/msp/apm/service/components/all.go
- internal/apps/msp/apm/service/components/service-overview/provider.go
- internal/apps/msp/apm/service/components/service-profile-overview/provider.go
- internal/apps/msp/apm/service/components/transaction-http-slow/slow_req_distribution/provider.go
- internal/apps/msp/apm/service/components/transaction-http-table/scenario.go
- internal/apps/msp/apm/service/components/transaction-http-table/table/provider.go
- internal/apps/msp/apm/service/components/transaction-http-table/table_filter/provider.go
- internal/apps/msp/apm/service/scenarios/service-profile-overview.yml
- internal/apps/msp/apm/service/scenarios/transaction-http-table.yml
- internal/apps/msp/menu/menu.service.go
- internal/tools/monitor/core/profile/query/render-diff.go
- internal/tools/monitor/core/profile/query/render.go
apm experience improvement
add some component about profile
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=363458&iterationID=1737&tab=REQUIREMENT&type=REQUIREMENT)
| 🇺🇸 English |   apm experience improvement           |
| 🇨🇳 中文    |     支持下钻，相关组件化协议         |
> feat(monitor): apm experience improvement

- cmd/erda-server/bootstrap.yaml
feat: make openapi-ng reloadbale
| 🇺🇸 English |  feat: make openapi-ng reloadable            |
| 🇨🇳 中文    | openapi-ng reloadable 为 true           |
> feat: make openapi-ng reloadable

- internal/core/user/common/model.go
- internal/core/user/common/model_test.go
- internal/tools/gittar/auth/auth.go
1. refactor GetUserInfoByTokenOrBasicAuth
2. print err when get user from uc failed
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/ticket?id=431723&iterationID=-1&type=TICKET)
/assign @chengjoey @cxr29 
| 🇺🇸 English |   refactor GetUserInfoByTokenOrBasicAuth; print err when get user from uc failed           |
| 🇨🇳 中文    |    重构 GetUserInfoByTokenOrBasicAuth；当从 uc 获取用户失败时打印 err          |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md) …
> refactor(gittar): refactor GetUserInfoByTokenOrBasicAuth; print err when get user from uc failed

- internal/tools/monitor/core/metric/query/es-tsql/influxql/column.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
fix metric seconds no order 
/assign @sfwn 
| 🇺🇸 English |   fix metric seconds no order            |
| 🇨🇳 中文    |      修复指标秒值无序        |
> fix: fix metric seconds no order 

- internal/tools/gittar/auth/auth.go
- pkg/http/httpclient/request.go
adjust gittar remote message format
| 🇺🇸 English |   adjust gittar remote message format           |
| 🇨🇳 中文    |  调整 gittar remote message 格式            |
> chore: adjust gittar remote message format

- apistructs/bigdata.go
- internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sflink/util.go
flinkcluster add optional for enable ui
/assign @sfwn 
| 🇺🇸 English |   Support flinkcluster add optional for enable ui           |
| 🇨🇳 中文    |   flink增加开关支持是否开启UI界面           |
> feat(pipeline): flinkcluster add optional for enable ui

- internal/tools/monitor/core/metric/query/es-tsql/influxql/column.go
- internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
/assign @sfwn 
| 🇺🇸 English |     fix: fix/fix tag expr use exprString         |
| 🇨🇳 中文    |    fix: fix/fix tag expr use exprString          |
> fix: fix/fix tag expr use exprString

- internal/tools/gittar/pkg/gitmodule/repo.go
gittar print some error logs to stderr for troubleshooting
/assign @sfwn 
| 🇺🇸 English |  Gittar print some error logs to stderr for troubleshooting            |
| 🇨🇳 中文    |   Gittar将一些错误打印到标准错误以方便排查问题           |
> chore(gittar): print some error logs to stderr for troubleshooting

- go.mod
- go.sum
- internal/tools/monitor/oap/collector/plugins/exporters/pyroscope/provider.go
1. add cache for apps
2. adjust the limit according to the number of dimension keys
/assign @sfwn 
| 🇺🇸 English |    Optimize streaming profiles          |
| 🇨🇳 中文    |      优化了profile的查询写入        |
> perf(streaming): cahce for applications

- internal/apps/dop/providers/issue/core/file.go
- internal/apps/dop/providers/issue/dao/core.go
fixt the bug that issue still be created instead of updated when import with correct id
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=446195&iterationID=-1&type=BUG)
| 🇺🇸 English |    fixt the bug that issue still be created instead of updated when import with correct id          |
| 🇨🇳 中文    |   修复了协同导入时即使使用正确的 ID 仍然是创建而非更新的问题           |
> fix(dop): issue still be created instead of updated when import with correct id

- internal/apps/dop/component-protocol/components/issue-dashboard/bar/stateVerticalBarChart/render.go
fix issue-dashboard scenario bug tab EOF
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=446218&iterationID=-1&type=BUG)
| 🇺🇸 English |   fix the bug that issue-dashboard scenario bug tab EOF           |
| 🇨🇳 中文    |   修复 issue-dashboard 场景中的错误标签 EOF 的问题           |
> fix(dop): issue dashboard bug EOF

- go.mod
- go.sum
upgrade clickhouse go pkg for some fixs
/assign @sfwn 
| 🇺🇸 English |   Chore upgrade clickhouse go pkg for some fixs           |
| 🇨🇳 中文    |    升级clickhouse-go的版本          |
> chore: upgrade clickhouse go pkg

- internal/apps/dop/services/apidocsvc/api_docs.go
- internal/apps/dop/services/apidocsvc/funcs.go
fix: ignore api_doc error
| 🇺🇸 English | fix: ignore api_doc error             |
| 🇨🇳 中文    | 忽略 api 设计因分支下无文档造成的错误             |
> fix: ignore api_doc error

- pkg/database/sqlparser/ddlreverser/reverser.go
- pkg/database/sqlparser/snapshot/snapshot.go
- pkg/database/sqlparser/snapshot/snapshot_test.go
feat: trim all utf8mb3
| 🇺🇸 English | feat: trim all utf8mb3             |
| 🇨🇳 中文    | 去除 create table 语句中的 utf8mb3           |
> feat: trim all utf8mb3

- internal/apps/dop/providers/issue/core/file.go
- internal/apps/dop/providers/issue/core/query/issueexcel/data.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheet_baseinfo.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheet_iteraion.go
export only related iterations if not exporting all issues
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=452456&iterationID=1841&tab=BUG&type=BUG)
| 🇺🇸 English |    export only related iterations if not exporting all issues         |
| 🇨🇳 中文    |   如果不是全事项导出，则只导出事项相关的迭代            |
> fix(dop): export only related iterations if not exporting all issues

- cmd/monitor/collector/bootstrap.yaml
- cmd/monitor/monitor/conf/alert/rules/app_resource/app_resource_container_network/analyzer_expression.json
- cmd/monitor/monitor/conf/alert/rules/app_resource/app_resource_container_network/notify_template.yaml
add rx,tx_bytes usage for fix container network alert
- [Erda Cloud Issue Link](https://erda.erda.cloud/erda/dop/projects/387/issues/all?id=438953&iterationID=1737&tab=BUG&type=BUG)
/assign @sfwn 
| 🇺🇸 English |  Support add rx,tx_bytes usage for fix container network alert            |
| 🇨🇳 中文    |      增加网络收发速率指标用于告警        |
> feat(monitor): add rx,tx_bytes usage for fix container network alert

- internal/tools/orchestrator/components/podscaler/db.service.go
- internal/tools/orchestrator/components/podscaler/db.service.impl.go
- internal/tools/orchestrator/components/podscaler/manual_scale_test.go
- internal/tools/orchestrator/dbclient/addon_attachment.go
- internal/tools/orchestrator/endpoints/addon.go
- internal/tools/orchestrator/endpoints/server_handler.go
- internal/tools/orchestrator/services/addon/addon.go
- internal/tools/orchestrator/services/addon/addon_test.go
fix addon list by runtime auth fail
runtime cross org:
| 🇺🇸 English |   fix addon list by runtime auth fail           |
| 🇨🇳 中文    |   修复通过 runtime 获取 addon 认证失败           |
> fix: addon list by runtime auth fail

- cmd/monitor/collector/bootstrap-agent.yaml
- cmd/monitor/collector/bootstrap.yaml
- cmd/monitor/streaming/bootstrap.yaml
- cmd/monitor/streaming/conf/clickhouse/external_metrics/ddl_create_db.sql.tpl
- cmd/monitor/streaming/conf/clickhouse/external_metrics/ddl_create_default_tables.sql.tpl
- internal/tools/monitor/oap/collector/core/config/config.go
- internal/tools/monitor/oap/collector/core/model/exporter.go
- internal/tools/monitor/oap/collector/core/model/odata/buffer.go
- internal/tools/monitor/oap/collector/core/model/odata/odata.go
- internal/tools/monitor/oap/collector/core/pipeline/pipeline.go
- internal/tools/monitor/oap/collector/core/pipeline/pipeline_test.go
- internal/tools/monitor/oap/collector/core/provider.go
- internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/external_metric/external_metrics.go
- internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/provider.go
- internal/tools/monitor/oap/collector/plugins/receivers/collector/kafka.go
- internal/tools/monitor/oap/collector/plugins/receivers/promremotewrite/provider.go
feat(streaming): external business metrics provider
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=467790&iterationID=1841&type=TASK)
/assign @sfwn 
| 🇺🇸 English | Support external business metrics provider             |
| 🇨🇳 中文    |      外部业务指标采集的prometheus通用接口        |
> feat(streaming): external business metrics provider

- internal/tools/orchestrator/endpoints/instance.go
- internal/tools/orchestrator/endpoints/instance_test.go
interface response:
pod status:
/assign @sixther-dc @wangzhuzhen 
| 🇺🇸 English |   fix service multi container order error           |
| 🇨🇳 中文    |   修复服务多容器顺序错误           |
> fix: service multi container order error

- internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/external_metric/external_metrics.go
fix external-metric missing non-need retention provider
/assign @sfwn 
| 🇺🇸 English |    Fix the bug that external-metric missing non-need retention provider          |
| 🇨🇳 中文    |    修复了外部指标缺失不需要的保留策略的问题          |
> fix(streaming): external-metric missing non-need retention provider

- .erda/pipelines/ci-build-ce.yml
- .erda/pipelines/ci-deploy.yml
- .github/workflows/ci-it.yml
- Makefile
- build/dockerfiles/Dockerfile
- build/dockerfiles/base/Dockerfile
- build/scripts/buildkit_image.sh
- build/scripts/docker_image.sh
- internal/tools/orchestrator/hepa/services/api_policy/impl/impl.go
- pipeline.yml
To support some nginx configurations defined in nginx modules.
/assign @dspo @luobily @sfwn 
Bugfix： Fix the bug that nginx custom configuration does not support configurations defined in modules.（修复了Nginx 自定义配置校验不支持 nginx 模块中定义的语法语义的问题）
| 🇺🇸 English |    Fix the bug that nginx custom configuration does not support configurations defined in modules.     |
| 🇨🇳 中文    |     修复了Nginx 自定义配置校验不支持 nginx 模块中定义的语法语义的问题    |
> fix(heap): nginx with modules

- internal/apps/dop/providers/project_report/query.go
fix project report metric randomly take values from daily data
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=494009&iterationID=-1&type=BUG)
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that project report metric randomly take values from daily data           |
| 🇨🇳 中文    |     修复了报表数据从每天没有按时间排序随机获取的指标数据的问题         |
> fix: project report metric randomly take values from daily data

- cmd/monitor/monitor/conf/chartview/frontend/browser_overview.json
- cmd/monitor/monitor/conf/chartview/frontend/script_overview.json
fix browser overview timeline error
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=495853&iterationID=-1&tab=BUG&type=BUG)
/assign @sfwn 
| 🇺🇸 English |    Fix the bug that browser overview timeline error          |
| 🇨🇳 中文    |   修复了脚本错误、浏览器性能图表时间轴错误的问题           |
> fix(monitor): browser overview timeline error

- cmd/ai-proxy/bootstrap.yml
- internal/apps/ai-proxy/dependent_providers.go
- internal/apps/ai-proxy/provider.go
- internal/pkg/ai-proxy/route/route.go
- internal/pkg/gorilla/mux/infra_encoder.go
- internal/pkg/gorilla/mux/middle.go
- internal/pkg/gorilla/mux/middles.go
- internal/pkg/gorilla/mux/mux.go
- internal/pkg/gorilla/mux/provider.go
feat: gorilla-mux
| 🇺🇸 English | feat: gorilla-mux             |
| 🇨🇳 中文    |  gorilla-mux provider, 更细粒度地管理接口 middles           |
> feat: gorilla-mux

- apistructs/issue.go
- internal/apps/dop/providers/issue/dao/core.go
- internal/apps/dop/providers/project_report/calculate.go
- internal/apps/dop/providers/project_report/metrics.go
- internal/apps/dop/providers/project_report/query.go
add estimated metrics for task
/assign @sfwn 
| 🇺🇸 English |    add estimated metrics for task          |
| 🇨🇳 中文    |     为迭代任务增加几个预估时间的指标         |
> feat(dop): add estimated metrics for task

- internal/apps/dop/providers/issue/core/query/property.go
log print issueID&propertyID when custom-field errors occurred
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=497073&iterationID=-1&tab=BUG&type=BUG)
| 🇺🇸 English |    log print issueID&propertyID when custom-field errors occurred           |
| 🇨🇳 中文    |    当自定义字段错误发生时，日志打印打印 issueID&propertyID          |
> polish(dop): log print issueID&propertyID when custom-field errors occurred

- internal/apps/dop/providers/project_report/calculate.go
fix iteration estimate time metric
/assign @sfwn 
| 🇺🇸 English |   fix iteration estimate time metric           |
| 🇨🇳 中文    |      修复了迭代预估工时指标计算失败的问题        |
> fix(dop): iteration estimate time metric

- api/proto/apps/aifunction/ai-function.proto
- apistructs/aifunction.go
- bundle/testcase.go
- internal/apps/ai-proxy/filters/audit/filter.go
- internal/apps/ai-proxy/filters/azure-director/filter.go
- internal/apps/ai-proxy/filters/openai-director/filter.go
- internal/pkg/ai-functions/functions/function.go
- internal/pkg/ai-functions/functions/test-case/function.go
- internal/pkg/ai-functions/functions/test-case/function_test.go
- internal/pkg/ai-functions/handler/handler_ai_function.go
- internal/pkg/ai-functions/handler/handler_ai_function_create_testcase.go
- internal/pkg/ai-functions/handler/handler_ai_function_create_testcase_test.go
- internal/pkg/ai-functions/handler/utils/handler_function_utils.go
- internal/pkg/ai-functions/sdk/client.go
- pkg/http/httputil/header.go
ai function batch create test case
/assign @sfwn 
Feature: Optimize ai function batch create test case （优化了AI Function 批量生成测试用例.）
| 🇺🇸 English |      Optimize ai function batch create test case        |
| 🇨🇳 中文    |       优化 AI Function 支持批量生成测试用例.       |
> feat: ai function batch create test case

- api/proto/dop/issue/core/core.proto
- cmd/erda-server/conf/i18n/cp/common.yaml
- internal/apps/dop/component-protocol/standard-components/issueFilter/conditions.go
- internal/apps/dop/component-protocol/standard-components/issueFilter/provider.go
- internal/apps/dop/providers/issue/dao/core.go
- internal/apps/dop/providers/project_report/query.go
issue-manage support query reopened bug issues
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=501931&iterationID=12560&type=TASK)
/assign @sfwn 
| 🇺🇸 English |   issue-manage support query reopened bug issues           |
| 🇨🇳 中文    |   项目协同支持展示重新打开次数大于0的缺陷事项           |
> feat(dop): issue-manage support query reopened bug issues

- api/proto/apps/aiproxy/client/client.proto
- api/proto/apps/aiproxy/session/session.proto
- internal/apps/ai-proxy/filters/context/filter.go
- internal/apps/ai-proxy/handlers/permission/method.go
- internal/apps/ai-proxy/models/client/dbclient.go
fix ai proxy
/assign @wangzhuzhen 
| 🇺🇸 English |    fix ai proxy          |
| 🇨🇳 中文    |    修复 ai proxy          |
> fix: ai proxy

- .erda/pipelines/ci-build-ce.yml
- .erda/pipelines/ci-deploy.yml
- .github/workflows/ci-it-noneed.yml
- .github/workflows/ci-it.yml
- api/proto-go/Makefile
- api/proto/apps/aiproxy/model/model.proto
- api/proto/apps/aiproxy/model_provider/model_provider.proto
- cmd/ai-proxy/bootstrap.yml
- internal/apps/ai-proxy/filters/azure-director/filter.go
- internal/apps/ai-proxy/filters/context/filter.go
- internal/apps/ai-proxy/handlers/handler_model/handler.go
- internal/apps/ai-proxy/handlers/handler_model_provider/handler.go
- internal/apps/ai-proxy/handlers/permission/method.go
- internal/apps/ai-proxy/models/metadata/metadata.go
- internal/apps/ai-proxy/models/model/dbclient.go
- internal/apps/ai-proxy/models/model/table.go
- internal/apps/ai-proxy/models/model_provider/dbclient.go
- internal/apps/ai-proxy/models/model_provider/table.go
- internal/apps/ai-proxy/providers/dao/provider.go
- internal/apps/ai-proxy/vars/consts.go
- pipeline.yml
- model & model_provider support paging
- recognize model.metadata.public.api_version
- treat ui input `undefined` as empty string
| 🇺🇸 English |    chore: ai proxy          |
| 🇨🇳 中文    |   ai-proxy 杂项           |
> chore: ai proxy

- api/proto/apps/aifunction/ai-function.proto
- internal/pkg/ai-functions/functions/test-case/function.go
- internal/pkg/ai-functions/handler/handler_ai_function.go
- internal/pkg/ai-functions/handler/handler_ai_function_create_testcase.go
- internal/pkg/ai-functions/handler/handler_ai_function_create_testcase_test.go
- internal/pkg/ai-functions/handler/utils/handler_function_utils.go
ai function support set system prompt
/assign @sfwn 
Feature: AI function support set system prompt （AI 功能支持指定系统提示词）
| 🇺🇸 English |    AI function support set system prompt     |
| 🇨🇳 中文    |    AI 功能支持指定系统提示词    |
> feat: ai function support set system prompt

- internal/tools/pipeline/providers/source/db/source.go
- internal/tools/pipeline/providers/source/pipeline_source.go
fix pipeline source is not unique due to version lock
/assign @sfwn 
| 🇺🇸 English |     Fix the bug that pipeline source is not unique due to version lock           |
| 🇨🇳 中文    |     修复了流水线定义由于git version不唯一的问题         |
> fix(pipeline): pipeline source is not unique due to version lock

- internal/tools/orchestrator/scheduler/instanceinfo/pod.go
Bugfix： repair sql injection （修复了orchestrator instances-usage sql 注入问题）
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=507824&iterationID=-1&type=TASK)
Bugfix： repair sql injection （修复了orchestrator instances-usage sql 注入问题）
| 🇺🇸 English |     repair sql injection - application_id         |
| 🇨🇳 中文    |       修复sql注入-application_id 问题       |
> fix(orchestrator): repair sql injection

- bundle/testcase.go
Fix bundle CreateTestCase Parse resp.Data error when data larger  than 999999
/assign @sfwn 
Bugfix： Fix the bug that CreateTestCase Parse resp.Data error when data larger  than 999999 （修复了 bundle CreateTestCase 解析的原始数据超过 999999 的问题，go 认为值是 float64 因而转成科学计算法，导致 strconv.ParseUint() 解析出错）
| 🇺🇸 English |        CreateTestCase Parse resp.Data error when data larger  than 999999      |
| 🇨🇳 中文    |       修复了 bundle CreateTestCase 解析的原始数据超过 999999 的问题，go 认为值是 float64 因而转成科学计算法，导致 strconv.ParseUint() 解析出错       |
> fix: bundle CreateTestCase Parse resp.Data

- apistructs/performance_measure.go
- cmd/erda-server/conf/i18n/cp/scenarios/personal-workbench.yaml
- internal/apps/admin/personal-workbench/component-protocol/components/personal-workbench/workTabs/workTabs.go
- internal/apps/dop/providers/efficiency_measure/efficiency_query.go
- internal/apps/dop/providers/issue/dao/performance_measure.go
efficiency measurement support group by project
/assign @sfwn 
| 🇺🇸 English |  efficiency measurement support group by project            |
| 🇨🇳 中文    |   效能度量指标支持根据项目进行分组           |
> feat(dop): efficiency measurement support group by project

- internal/apps/ai-proxy/filters/message-context/filter.go
wrap user prompt by |start| & |end| to avoid from content-filter
| 🇺🇸 English |   wrap user prompt by |start| & |end| to avoid from content-filter           |
| 🇨🇳 中文    |   使用 |start| & |end| 包装用户提示词来避免内容过滤          |
> feat(ai-proxy): wrap user prompt by |start| & |end| to avoid from content-filter

- cmd/ai-proxy/conf/routes.yml
- internal/apps/ai-proxy/dependent_filters.go
- internal/apps/ai-proxy/filters/initialize/filter.go
rename filter: `initial -> initialize` to match finalize filter
| 🇺🇸 English |   rename filter: `initial -> initialize` to match finalize filter           |
| 🇨🇳 中文    |    重命名 filter:  `initial -> initialize` 来匹配 finalize filter          |
> chore(ai-proxy): rename filter: `initial -> initialize` to match finalize filter

- internal/apps/ai-proxy/filters/audit/filter.go
- internal/apps/ai-proxy/filters/message-context/filter.go
- internal/apps/ai-proxy/vars/prompt.go
unwrap user prompt in audit
| 🇺🇸 English |   unwrap user prompt in audit           |
| 🇨🇳 中文    |    审计里取消 user prompt 的包装          |
> chore(ai-proxy): unwrap user prompt in audit

- internal/apps/dop/providers/efficiency_measure/efficiency_query.go
- internal/apps/dop/providers/efficiency_measure/provider.go
fix dev defect density
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that dev defect density           |
| 🇨🇳 中文    |    修复了效能度量开发缺陷密度指标          |
> fix(dop): dev defect density

- cmd/ai-proxy/conf/routes.yml
- internal/apps/ai-proxy/filters/audit/filter.go
ai-proxy support text-embeddings model
/assign @sfwn 
Feature: AI Proxy support text-embedding-ada-002 model（AI Proxy 支持 text-embedding-ada-002 模型）
| 🇺🇸 English |       Feature: AI Proxy support text-embedding-ada-002 model       |
| 🇨🇳 中文    |       AI Proxy 支持 text-embedding-ada-002 模型       |
> feat: ai-proxy support text-embeddings model

- internal/apps/dop/providers/efficiency_measure/efficiency_query.go
- internal/tools/gittar/metrics/collector.go
efficiency measurement metrics add projectID
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that efficiency measurement metrics add projectID           |
| 🇨🇳 中文    |   修复了效能度量指标缺少项目ID的问题           |
> fix(dop): efficiency measurement metrics add projectID

- internal/apps/dop/providers/efficiency_measure/calculate.go
fix user avg fix bug elapsed minute
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=511949&iterationID=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |     Fix the bug that user avg fix bug elapsed minute          |
| 🇨🇳 中文    |      修复了平均修复bug时长以处理人为当前用户的问题        |
> fix(dop): user avg fix bug elapsed minute

- internal/apps/dop/endpoints/iteration.go
- internal/apps/dop/services/iteration/iteration.go
iteration detail support show issue summary
/assign @sfwn 
| 🇺🇸 English | iteration detail support show issue summary             |
| 🇨🇳 中文    |     迭代详情支持展示进度信息         |
> feat(dop): iteration detail support show issue summary

- internal/apps/dop/providers/issue/core/query/issueexcel/sheet_issue_import.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheet_issue_import_test.go
issue excel import support `2006/1/2 0:00:00` format
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=512800&iterationID=12783&type=TASK)
| 🇺🇸 English |    issue excel import support `2006/1/2 0:00:00` format          |
| 🇨🇳 中文    |   事项 excel 导入支持 `2006/1/2 0:00:00` 格式      |
> feat(dop): issue excel time format

- internal/core/openapi/openapi-ng/interceptors/csrf/csrf.go
csrf token judge validation by referer and origin header
| 🇺🇸 English |   csrf token judge validation by referer and origin header           |
| 🇨🇳 中文    |   csrf token 根据 referer 和 origin 头来判断是否需要校验           |
Add comment like `/cherry-pick release/2.4-beta.4` when this PR is merged.
> fix(openapi): csrf token judge validation by referer and origin header

- api/proto/dop/issue/core/core.proto
- cmd/erda-server/conf/i18n/cp/scenarios/issue-manage.yaml
- internal/apps/admin/apierrors/errors.go
- internal/apps/devflow/flow/issue_mock.go
- internal/apps/dop/component-protocol/components/issue-dashboard/bar/labelHorizontalBarChart/render.go
- internal/apps/dop/component-protocol/components/issue-dashboard/filter/render.go
- internal/apps/dop/component-protocol/components/issue-gantt/gantt/render.go
- internal/apps/dop/component-protocol/components/issue-kanban/issueKanbanV2/provider.go
- internal/apps/dop/component-protocol/components/issue-manage/issueTable/props.go
- internal/apps/dop/component-protocol/components/issue-manage/issueTable/render.go
- internal/apps/dop/component-protocol/components/issue-manage/issueTable/render_test.go
- internal/apps/dop/component-protocol/components/requirement-task-overview/container/info/render.go
- internal/apps/dop/component-protocol/components/requirement-task-overview/distributePage/topFilter/render.go
- internal/apps/dop/component-protocol/components/requirement-task-overview/stackChartBlock/stackChart/model.go
- internal/apps/dop/component-protocol/scenarios/issue-manage.yml
- internal/apps/dop/component-protocol/standard-components/issueFilter/provider.go
- internal/apps/dop/component-protocol/types/const.go
- internal/apps/dop/initialize.go
- internal/apps/dop/providers/issue/core/provider.go
- internal/apps/dop/providers/issue/core/service.go
- internal/apps/dop/providers/issue/dao/core.go
- internal/apps/dop/providers/issue/dao/issue_relation.go
- internal/apps/dop/providers/issue/dao/property_relation.go
- internal/apps/dop/providers/issue/dao/state_circulation.go
- internal/apps/dop/services/apierrors/errors.go
- internal/core/legacy/services/apierrors/errors.go
- pkg/mock/issue_query_mock.go
feat:support batch deletion of projects
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=509911&iterationID=-1&tab=TASK&type=TASK)
| 🇺🇸 English |       feat:support batch deletion of projects       |
| 🇨🇳 中文    |        支持项目批量删除      |
> feat: support batch deletion of projects

- internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_user/import.go
support collect user keys from issue-sheet.custom-fields
| 🇺🇸 English |    support collect user keys from issue-sheet.custom-fields          |
| 🇨🇳 中文    |    支持从 issue-sheet.custom-fields 里获取 user keys          |
> fix(dop): support collect user keys from issue-sheet.custom-fields

- internal/tools/orchestrator/scheduler/instanceinfo/instance.go
fix(orchestrator): Modify the addition method of "now"
Before repair：
SELECT * FROM `s_instance_info`  WHERE (container_id = '529a37aa080dd55fd4c47ba59423b0dd6f30ce8821ec6884e31ba573ee6ab893') AND (runtime_id = '') AND (application_id = '') ORDER BY started_at desc
After repair：
SELECT * FROM `s_instance_info`  WHERE (container_id = "2a346dcec3fd40af7bdfceafd8ebc502dcce0a9073c53655719f29cf10d3810a" AND runtime_id = "19884" AND application_id = "8023") ORDER BY started_at desc
| 🇺🇸 English |      fix(orchestrator): Modify the addition method of now        |
| 🇨🇳 中文    |       修改 now 的添加方式       | …
> fix(orchestrator): Modify the addition method of now

- internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_user/import.go
issue import collectUserKeysFromCustomFields check cf type, fix npe
| 🇺🇸 English |   issue import collectUserKeysFromCustomFields check cf type, fix npe           |
| 🇨🇳 中文    |    issue 导入 collectUserKeysFromCustomFields 校验自定义字段类型，修复 npe          |
> fix(dop): issue import collectUserKeysFromCustomFields check cf type

- go.mod
- go.sum
- internal/apps/dop/providers/issue/core/query/issueexcel/export.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheets/interface.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_baseinfo/export.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_customfield/export.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_issue/export.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_issue/import_vars.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_iteration/export.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_label/export.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_state/export.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_user/export.go
- pkg/excel/cell.go
- pkg/excel/export_test.go
- pkg/excel/multi_sheet.go
For easy use, issue excel export with droplist.
| 🇺🇸 English |  issue excel export with droplist            |
| 🇨🇳 中文    |   事项 Excel 导出支持下拉框           |
> feat(dop): issue excel export with droplist

- api/proto/dop/issue/core/core.proto
- cmd/erda-server/conf/i18n/issue-excel.yaml
- internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_issue/export.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_issue/import.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_issue/import_old.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_issue/import_test.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_issue/import_vars.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_state/import.go
- internal/apps/dop/providers/issue/core/query/issueexcel/vars/data.go
- internal/apps/dop/providers/issue/core/query/issueexcel/vars/i18n.go
- pkg/excel/multi_sheet.go
- pkg/strutil/regexp.go
- pkg/strutil/regexp_test.go
- add droplist&tip for all required fields, include custom fields
- use different custom title styles to split common/requirement/task/bug
| 🇺🇸 English |   add droplist&tip for all required fields; use custom title style           |
| 🇨🇳 中文    |   为所有需要的字段增加 下拉框和提示；使用自定义标题样式           |
> feat(dop): add droplist&tip for all required fields; use custom title style

- internal/apps/dop/providers/project_report/query.go
feat:add function point indicators
feat:add function point indicators
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=516230&iterationID=12560&tab=TASK&type=TASK)
| 🇺🇸 English |        feat:add function point indicators      |
| 🇨🇳 中文    |       项目报表增加功能点指标       |
> feat: add function point indicators

- internal/pkg/ai-functions/functions/test-case/system-message.txt
- internal/pkg/ai-functions/handler/handler_ai_function_create_testcase.go
- internal/pkg/ai-functions/handler/utils/handler_function_utils.go
Optimal ai create testcase chatcompletionmessages to get better result
/assign @sfwn
Bugfix： Optimal ai create testcase chatcompletionmessages to get better result （优化 AI 生成测试用例的 Messges 输入以获取更好的生成效果）
| 🇺🇸 English |     Optimal ai create testcase chatcompletionmessages to get better result         |
| 🇨🇳 中文    |   优化 AI 生成测试用例的 Messges 输入以获取更好的生成效果    |
> fix: optimal ai create testcase chatcompletionmessage

- internal/apps/dop/providers/issue/core/query/export.go
- internal/apps/dop/providers/issue/core/query/issueexcel/import.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_customfield/import.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_issue/export.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_issue/export_template.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_issue/import.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_issue/import_test.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_user/import.go
- internal/apps/dop/providers/issue/core/query/issueexcel/vars/data.go
- internal/apps/dop/providers/issue/core/query/issueexcel/vars/model.go
- pkg/excel/multi_sheet.go
- pkg/excel/multi_sheet_test.go
- compatible issue stage when import & export
- issue import template use project's real data
- check import error after BeforeCreateIssues step
- precheck fieldCustomField when import
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=518422&iterationID=12783&tab=BUG&type=BUG)
| 🇺🇸 English |   issue excel import polishment           |
| 🇨🇳 中文    |    事项 excel 导入优化          |
> fix(dop): issue excel import polishment

- internal/apps/dop/providers/issue/core/query/issueexcel/import.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheets/interface.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_issue/export.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_issue/field.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_issue/import.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_issue/import_old.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_iteration/import.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_iteration/import_test.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_state/import.go
- internal/apps/dop/providers/issue/core/query/issueexcel/vars/data.go
issue excel Importer add Precheck step, iteration&state need precheck before check issues
| 🇺🇸 English |  issue excel Importer add Precheck step            |
| 🇨🇳 中文    |   事项 Excel 导入增加 Precheck 步骤           |
> feat(dop): issue excel Importer add Precheck step

- internal/apps/dop/providers/issue/core/file.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_issue/import.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_issue/import_test.go
- internal/apps/dop/providers/issue/core/query/issueexcel/vars/data.go
Fix the issue of not recognizing the project issue ids when create issue relations.
Before fixing, although precheck is passed, it failed to create issue relations.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=518464&iterationID=12783&tab=BUG&type=BUG)
| 🇺🇸 English |  fix the issue of not recognizing the project issue ids when create issue relations           |
| 🇨🇳 中文    |  修复了创建关联关系时不识别事项内事项 id 的问题            |
> fix(dop): fix the issue of not recognizing the project issue ids when create issue relations

- internal/tools/pipeline/pipengine/pvolumes/bind.go
currently, more and more of our clusters are using containerrd
bind containerd sock for pipeline jobs
/assign @sfwn 
| 🇺🇸 English |  feat bind containerd sock for pipeline jobs            |
| 🇨🇳 中文    |    给pipeline job容器绑定上containerd的socket文件          |
> feat(pipeline): bind containerd sock for pipeline jobs

- internal/apps/msp/apm/alert/components/msp-alert-event-detail/event-history-table/provider.go
alert out of index bug
| 🇺🇸 English |  fix alert out of index bug            |
| 🇨🇳 中文    |     修复告警 OOI 缺陷         |
> fix: alert out of index bug

- internal/tools/orchestrator/scheduler/executor/plugins/edas/edas.go
- internal/tools/orchestrator/scheduler/executor/plugins/edas/edas_app_flow.go
- internal/tools/orchestrator/scheduler/executor/plugins/edas/types/types.go
- internal/tools/orchestrator/scheduler/executor/plugins/edas/wrapclient/edas/app.client.go
- internal/tools/orchestrator/scheduler/executor/plugins/edas/wrapclient/edas/app.client_test.go
- internal/tools/orchestrator/scheduler/executor/plugins/edas/wrapclient/edas/changeorder.client.go
- internal/tools/orchestrator/scheduler/executor/plugins/edas/wrapclient/edas/errors.go
- internal/tools/orchestrator/scheduler/executor/plugins/edas/wrapclient/edas/provider.go
- internal/tools/orchestrator/scheduler/executor/plugins/edas/wrapclient/kubernetes/provider.go
- internal/tools/orchestrator/scheduler/executor/plugins/edas/wrapclient/kubernetes/service.go
- internal/tools/orchestrator/scheduler/executor/plugins/edas/wrapclient/kubernetes/service_test.go
fix edas update service selector error
| 🇺🇸 English |   fix edas update service selector error           |
| 🇨🇳 中文    |     修复 edas 更新 service selector 错误         |
> fix: edas update service selector error

- internal/apps/dop/providers/efficiency_measure/efficiency_query.go
feat: add performance measurement range value
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=516226&iterationID=12560&tab=TASK&type=TASK)
| 🇺🇸 English |      feat: add performance measurement range value        |
| 🇨🇳 中文    |       支持自然年，上下半年维度的效能度量查询       |
> feat: add performance measurement range value

- internal/core/openapi/legacy/api/apis/dop/efficiency_measure_query.go
- internal/core/openapi/legacy/api/apis/dop/func_pooints_query.go
- internal/core/openapi/legacy/api/apis/dop/personal_contribution_query.go
- internal/core/openapi/legacy/api/apis/dop/project_report_query.go
fix efficiency measure route no token check
/assign @sfwn 
| 🇺🇸 English |   fix efficiency measure route no token check           |
| 🇨🇳 中文    |      修复了效能度量接口token校验的问题        |
> fix(dop): efficiency measure route no token check

- internal/tools/pipeline/actionagent/agenttool/tar.go
- internal/tools/pipeline/actionagent/step_restore.go
- internal/tools/pipeline/actionagent/step_store.go
fix(pipeline):  cache file exceed limit size due to system link
/assign @sfwn 
| 🇺🇸 English | fix cache file exceed limit size due to system link             |
| 🇨🇳 中文    |     修复了缓存因为软连接文件的原因超过大小限制的问题         |
> fix(pipeline):  cache file exceed limit size due to system link

- internal/tools/orchestrator/scheduler/executor/plugins/edas/wrapclient/edas/app.client.go
feat add log execute loop termination
| 🇺🇸 English |   feat add log execute loop termination           |
| 🇨🇳 中文    |     添加循环停止状态检查日志         |
> feat: add log execute loop termination

- internal/apps/ai-proxy/filters/bailian-director/resp.go
convert bailian non-stream response to openai chat completion
| 🇺🇸 English |    convert bailian non-stream response to openai chat completion          |
| 🇨🇳 中文    |    将百炼非流式响应转换为 OpenAI ChatCompletion          |
> fix(ai-proxy): convert bailian non-stream response to openai chat completion

- internal/apps/dop/component-protocol/components/issue-manage/batchOperationTipModal/render.go
fix: use getOperations,fix batch deletion without pop-up window
| 🇺🇸 English |       fix: use getOperations,fix batch deletion without pop-up window       |
| 🇨🇳 中文    |        修复批量删除不弹窗不删除      |
> fix: use getOperations

- internal/apps/dop/component-protocol/components/issue-gantt/filter/model.go
- internal/apps/dop/component-protocol/components/issue-gantt/filter/provider.go
- internal/apps/dop/component-protocol/components/issue-gantt/gantt/render.go
- internal/apps/dop/providers/issue/dao/core.go
issue-gantt component support filter state conditions
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=540296&iterationID=12783&type=TASK)
/assign @sfwn 
| 🇺🇸 English |  Support issue-gantt component support filter state conditions            |
| 🇨🇳 中文    |   甘特图支持对状态进行筛选           |
> feat(dop): issue-gantt component support filter state conditions

- apistructs/performance_measure.go
- internal/apps/dop/providers/efficiency_measure/contributor_query.go
contribution supports display of trends by day
/assign @sfwn 
| 🇺🇸 English |  contribution supports display of trends by day            |
| 🇨🇳 中文    |       实现贡献趋势图按天进行展示       |
> feat(dop): contribution supports display of trends by day

- internal/apps/dop/providers/issue/dao/core.go
parent issue not filter by state id
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=540631&iterationID=12783&type=BUG)
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that parent issue not filter by state id           |
| 🇨🇳 中文    |      修复了甘特图的父事项没有同样按照状态进行筛选的问题        |
> fix(dop): parent issue not filter by state id

- build/dockerfiles/cluster-agent/Dockerfile
optimize cluster-agent kubectl source
/assign @sfwn 
| 🇺🇸 English |  optimize cluster-agent kubectl source            |
| 🇨🇳 中文    |   优化 cluster-agent kubectl 获取源           |
> feat: optimize cluster-agent kubectl source

- api/proto/apps/aiproxy/audit/audit.proto
- internal/apps/ai-proxy/common/ctxhelper/client_token.go
- internal/apps/ai-proxy/filters/audit-before-llm-director/req.go
- internal/apps/ai-proxy/models/audit/dbclient.go
- internal/apps/ai-proxy/models/audit/table.go
get audit identity from client token
| 🇺🇸 English |    get audit identity from client token          |
| 🇨🇳 中文    |   从客户端 token 里获取审计身份信息           |
> fix(ai-proxy): get audit identity from client token

- internal/apps/dop/providers/issue/dao/core.go
fix gantt children issues not filtered by states
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that gantt children issues not filtered by states            |
| 🇨🇳 中文    |   修复了甘特图的子事项没有按照状态进行筛选的问题           |
> fix(dop): gantt children issues not filtered by states

- internal/apps/dop/endpoints/testcase.go
Export xmind with fileUUID for download directly.
/assign @sfwn 
Feature: Optimize AI generated testcases exported xmind result  with fileUUID for download directly.（优化了AI 生成测试用例导出接口返回数据附带 fileUUID，以支持导出操作直接下载文件）
| 🇺🇸 English |  Feature: Optimize AI generated testcases exported xmind result  with fileUUID for download directly.（     |
| 🇨🇳 中文    |   优化了AI 生成测试用例导出接口返回数据附带 fileUUID，以支持导出操作直接下载文件     |
> feat(ai-function): export xmind with fileUUID for download directly

- api/proto/apps/aiproxy/client/rich_client.proto
- api/proto/apps/aiproxy/client/rich_client/rich_client.proto
- api/proto/apps/aiproxy/client_model_relation/client_model_relation.proto
- api/proto/apps/aiproxy/client_token/client_token.proto
- api/proto/apps/aiproxy/model/model.proto
- api/proto/apps/aiproxy/model_provider/model_provider.proto
- internal/apps/ai-proxy/handlers/common/akutil/ak.go
- internal/apps/ai-proxy/handlers/common/auth/auth.go
- internal/apps/ai-proxy/handlers/handler_rich_client/handler.go
- internal/apps/ai-proxy/handlers/permission/method.go
- internal/apps/ai-proxy/models/model/dbclient.go
- internal/apps/ai-proxy/models/model_provider/dbclient.go
- internal/apps/ai-proxy/provider.go
- internal/apps/ai-proxy/vars/consts.go
add rich-client management API
- [Erda Cloud Issue Link](https://erda.cloud/terminus/dop/projects/1265/issues/all?id=551391&iterationID=-1&type=REQUIREMENT)
| 🇺🇸 English |    ai-proxy add rich-client management API          |
| 🇨🇳 中文    |   ai-proxy 管理 API 新增 富客户端            |
> feat(ai-proxy): add rich-client management API

- internal/apps/msp/apm/service/view/table/error_transaction.go
- internal/apps/msp/apm/service/view/table/slow_transaction.go
fix the consistency problem of table and chart data in micro service monitor
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=552045&iterationID=12783&tab=BUG&type=BUG)
/assign @sfwn 
| 🇺🇸 English |   Fix the consistency problem of table and chart data in micro service monitor           |
| 🇨🇳 中文    |     修复了服务监控中图表和表格数据不一致的问题         |
> fix(msp): the consistency problem of table and chart data in micro service monitor

- internal/pkg/ai-functions/functions/test-case/function.go
- internal/pkg/ai-functions/functions/test-case/group.go
Optimize prompt
/assign @sfwn 
Feature: Optimize AI generated testcases prompt.（优化了AI 生成测试用例导提示词）
| 🇺🇸 English |  Feature: Optimize AI generated testcases prompt.   |
| 🇨🇳 中文    |   优化了AI 生成测试用例导提示词    |
> fix(ai-function): optimal prompt

- cmd/erda-server/conf/i18n/issue-excel.yaml
- internal/apps/dop/providers/issue/core/file.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_issue/export_template.go
- internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_issue/field.go
fix issue excel_export_template i18n
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=549175&iterationID=12783&type=BUG)
| 🇺🇸 English | fix issue excel_export_template i18n             |
| 🇨🇳 中文    |   修复下载导入模版文件中的字段国际化处理           |
> fix: fix issue excel_export_template i18n

- apistructs/container.go
- internal/tools/orchestrator/endpoints/instance.go
- internal/tools/orchestrator/endpoints/instance_test.go
add pod finished time
@iutx 
| 🇺🇸 English |  add pod finished time  |
| 🇨🇳 中文    |  为get-service接口添加pod停止运行的时间  |
> feat: add pod finished time

- internal/apps/msp/apm/service/view/table/transaction.go
fix transaction avg duration inconsistency
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=552045&iterationID=12783&tab=BUG&type=BUG)
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that transaction avg duration inconsistency            |
| 🇨🇳 中文    |     修复了服务监控的平均相应时间不一致的问题         |
> fix(monitor): transaction avg duration inconsistency

- internal/tools/gittar/ai/cr/impl/cr_mr_code_snippet/snippet.go
- internal/tools/gittar/ai/cr/impl/cr_mr_file/file.go
- internal/tools/gittar/models/note.go
- internal/tools/gittar/models/note_cr.go
polish ai code review
| 🇺🇸 English |   polish ai code review            |
| 🇨🇳 中文    |   优化 AI 代码审查           |
> feat(gittar): polish ai code review

- cmd/ai-proxy/conf/routes.yml
ai-proxy comment out default system message
- [Erda Cloud Issue Link](https://erda.cloud/terminus/dop/projects/1265/issues/all?id=552733&iterationID=-1&tab=ALL&type=BUG)
| 🇺🇸 English |    ai-proxy comment out default system message          |
| 🇨🇳 中文    |    ai-proxy 注释掉默认系统消息          |
> chore(ai-proxy): comment out default system message

- internal/apps/msp/apm/exception/query/provider.go
fix entity grpc client exceed default recv bytes
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=465513&iterationID=12783&type=BUG)
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that entity grpc client exceed default recv bytes          |
| 🇨🇳 中文    |      修复了错误分析 RPC 接收消息超过默认大小的问题        |
> fix(monitor): entity grpc client exceed default recv bytes

- bundle/pipeline.go
fix failed to sync records due to bundle missing error msg
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=552460&iterationID=12783&type=BUG)
/assign @sfwn 
| 🇺🇸 English |   fix failed to sync records due to bundle missing error msg           |
| 🇨🇳 中文    |   修复了由于bundle没有返回明确错误导致查看操作历史失败的问题           |
> fix(cmp): failed to sync records due to bundle missing error msg

- internal/tools/pipeline/providers/source/db/source.go
fix repeat source/definition records when create pipeline
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=548454&iterationID=-1&type=BUG)
/assign @sfwn 
| 🇺🇸 English |  fix repeat source/definition records            |
| 🇨🇳 中文    |    修复了创建流水线时重复创建source和definition记录问题          |
> fix: fix repeat source/definition records

- cmd/monitor/streaming/conf/clickhouse/profiles_ddl_create_default_tables.sql
- go.mod
- go.sum
- internal/tools/monitor/oap/collector/plugins/processors/profile/provider.go
optimize writing logic and accelerate query logic to optimize user experience
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=554629&iterationID=-1&tab=TASK&type=TASK)
/assign @sfwn 
| 🇺🇸 English |   optimize writing logic and accelerate query logic to optimize user experience           |
| 🇨🇳 中文    |    优化了可持续观测数据的写入查询逻辑          |
> perf(monitor): optimize writing logic and accelerate query logic to optimize user experience

- apistructs/extention.go
- bundle/dicehub.go
- internal/core/openapi/legacy/component-protocol/scenarios/action/components/actionForm/action_form.go
- internal/core/openapi/legacy/component-protocol/scenarios/action/components/actionForm/render.go
- internal/pkg/extension/provider.go
fix get action props i18n
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=549318&iterationID=12783&type=BUG)
/assign @sfwn 
| 🇺🇸 English |  fix get action props i18n            |
| 🇨🇳 中文    |   修复了可视化添加流水线节点时部分action参数介绍国际化的问题           |
> fix: fix get action props i18n

- api/proto/core/pipeline/cron/cron.proto
- internal/apps/dop/endpoints/pipelinecron.go
- internal/apps/dop/providers/projectpipeline/service_impl.go
- internal/apps/dop/providers/projectpipeline/service_impl_test.go
- internal/tools/pipeline/providers/cron/cron.service.go
- internal/tools/pipeline/providers/source/db/source.go
create pipeline_cron and not create the pipeline_base when create pipeline
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=554193&iterationID=-1&type=TASK)
/assign @sfwn 
| 🇺🇸 English |  fix create cron logic when create pipeline            |
| 🇨🇳 中文    |   修复新版流水线创建时会同时创建base记录问题，从创建base流程中单独提出cron创建流程来调用           |
> fix: fix create cron logic when create pipeline

- api/proto/apps/aiproxy/audit/audit.proto
- cmd/ai-proxy/conf/routes.yml
- internal/apps/ai-proxy/common/ctxhelper/audio.go
- internal/apps/ai-proxy/dependent_filters.go
- internal/apps/ai-proxy/filters/audit-after-llm-director/req.go
- internal/apps/ai-proxy/filters/audit-after-llm-director/resp.go
- internal/apps/ai-proxy/filters/audit-before-llm-director/req.go
- internal/apps/ai-proxy/filters/audit-before-llm-director/resp.go
- internal/apps/ai-proxy/filters/context-audio/filter.go
- internal/apps/ai-proxy/filters/context-audio/filter_test.go
- internal/apps/ai-proxy/models/audit/dbclient.go
- internal/apps/ai-proxy/models/metadata/meta_audit.go
- internal/apps/ai-proxy/vars/consts.go
- internal/tools/pipeline/dbclient/op_pipeline.go
- pkg/http/httputil/mediatype.go
- pkg/reverseproxy/filter.go
- pkg/reverseproxy/reverseproxy.go
- pkg/reverseproxy/transport.go
ai-proxy support STT (Speach to text)
- [Erda Cloud Issue Link](https://erda.cloud/terminus/dop/projects/1265/issues/all?id=554654&iterationID=13539&tab=REQUIREMENT&type=REQUIREMENT)
| 🇺🇸 English |   ai-proxy support STT (Speach to text)           |
| 🇨🇳 中文    |    ai-proxy 支持 STT (语音转文本)          |
> feat(ai-proxy): support STT (Speach to text)

- internal/tools/gittar/models/note.go
- internal/tools/gittar/models/note_test.go
refactor the gittar logic to find section according to old/new line numbers
- [Erda Cloud Issue Link](https://erda.cloud/terminus/dop/projects/1265/issues/all?id=528864&iterationID=13539&tab=REQUIREMENT&type=REQUIREMENT)
| 🇺🇸 English |      refactor the gittar logic to find section according to old/new line numbers        |
| 🇨🇳 中文    |    重构 gittar 根据 old/new 行号查找代码块的逻辑         |
> refactor(gittar): adjust find section logic

- apistructs/service_job_status.go
- build/scripts/docker_image.sh
- internal/tools/orchestrator/scheduler/executor/plugins/k8s/healthcheck.go
Optimize health check time
/assign @iutx 
| 🇺🇸 English |    Optimize health check time          |
| 🇨🇳 中文    |    优化健康检查时间         |
Add comment like /cherry-pick release/1.0 when this PR is merged.
> feat: reduce orchestrator HealthCheckDuration

- apistructs/iteration.go
- internal/apps/dop/component-protocol/components/test-dashboard/overview_group/quality_chart/render.go
- internal/apps/dop/component-protocol/components/test-dashboard/overview_group/quality_chart/render_test.go
- internal/apps/dop/providers/efficiency_measure/calculate.go
- internal/apps/dop/providers/efficiency_measure/metric.go
- internal/apps/dop/providers/efficiency_measure/metric_test.go
- internal/apps/dop/providers/efficiency_measure/provider.go
- internal/apps/dop/providers/issue/dao/core.go
- internal/apps/dop/providers/issue/dao/issue_relation.go
- internal/apps/dop/providers/issue/dao/performance_measure.go
- internal/apps/dop/providers/project_report/calculate.go
- internal/apps/dop/providers/project_report/calculate_test.go
- internal/apps/dop/providers/project_report/metrics.go
- internal/apps/dop/providers/project_report/prometheus.go
- internal/apps/dop/providers/project_report/provider.go
- pkg/arrays/arrays.go
- pkg/arrays/arrays_test.go
feat: metrics addition item IDs
fix: ids corresponds to each individual metric
feat: project report metrics add item ids
feat: metrics addition item IDs
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=531965&iterationID=12560&tab=TASK&type=TASK)
| 🇺🇸 English |       feat: metrics addition item IDs       |
| 🇨🇳 中文    |        指标补充事项 ID 信息，用于 diff 等      | …
> feat: metrics addition item IDs

- api/proto/apps/aiproxy/audit/audit.proto
- cmd/ai-proxy/conf/routes.yml
- go.mod
- go.sum
- internal/apps/ai-proxy/common/ctxhelper/image.go
- internal/apps/ai-proxy/dependent_filters.go
- internal/apps/ai-proxy/filters/audit-before-llm-director/req.go
- internal/apps/ai-proxy/filters/audit-before-llm-director/resp.go
- internal/apps/ai-proxy/filters/context-image/filter.go
- internal/apps/ai-proxy/models/audit/dbclient.go
- internal/apps/ai-proxy/models/metadata/meta_audit.go
- internal/apps/ai-proxy/vars/consts.go
AI-Proxy support proxy image API (dall-e)
- [Erda Cloud Issue Link](https://erda.cloud/terminus/dop/projects/1265/issues/all?id=557792&iterationID=13539&type=REQUIREMENT)
| 🇺🇸 English |   ai-proxy support proxy image API (dall-e)           |
| 🇨🇳 中文    |    ai-proxy 支持代理 image API (dall-e)          |
> feat(ai-proxy): support proxy image API (dall-e)

- internal/tools/orchestrator/scheduler/executor/plugins/edas/utils/runtime.go
remove the check on the Key of the environment variable
/assign @iutx 
| 🇺🇸 English |      feat: remove the check on the Key of the environment variable        |
| 🇨🇳 中文    |       移除对环境变量key的正则匹配检查       |
> feat: remove the check on the Key of the environment variable

- internal/tools/orchestrator/endpoints/addon.go
remove the check on the Key of the environment variable in addon
/assign @iutx 
| 🇺🇸 English |       remove the check on the Key of the environment variable in addon       |
| 🇨🇳 中文    |      删除自定义addon对key的正则校验        |
> feat: remove the check on the Key of the environment variable in addon

- api/proto/apps/aiproxy/model/model.proto
AI-Proxy support multimodal GPT-4V
- [Erda Cloud Issue Link](https://erda.cloud/terminus/dop/projects/1265/issues/all?id=556093&iterationID=13539&tab=REQUIREMENT&type=REQUIREMENT)
| 🇺🇸 English |     AI-Proxy support multimodal GPT-4V         |
| 🇨🇳 中文    |    AI-Proxy 支持多模态 GPT-4V          |
> feat(ai-proxy): support multimodal GPT-4V

- internal/apps/msp/apm/service/components/resources-container-monitor/container/provider.go
fix resource-container-monitor no data
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=560554&iterationID=-1&type=BUG)
| 🇺🇸 English |   Fix the bug that resource-container-monitor no data           |
| 🇨🇳 中文    |    修复了微服务容器监控可能无数据的问题          |
> fix(monitor): resource-container-monitor no data

- internal/tools/orchestrator/scheduler/executor/executortypes/types.go
fix register event chan concurrent map
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=559147&iterationID=12783&type=BUG)
/assign @sfwn 
| 🇺🇸 English |  fix register event chan concurrent map            |
| 🇨🇳 中文    |   修复注册event chan并发map           |
> fix(orchestrator): register event chan concurrent map

- internal/pkg/ai-functions/functions/function.go
- internal/pkg/ai-functions/functions/test-case/function.go
- internal/pkg/ai-functions/functions/test-case/function_test.go
- internal/pkg/ai-functions/functions/test-case/group.go
- internal/pkg/ai-functions/functions/test-case/system-message.txt
- internal/pkg/ai-functions/handler/handler_ai_function.go
AI generate testcase results international
/assign @sfwn 
Feature: Support AI generate testcases results international（支持 AI 生成测试用例结果国际化）
| 🇺🇸 English |     Support AI generate testcases results international       |
| 🇨🇳 中文    |     支持 AI 生成测试用例结果国际化   |
> feat: AI generate testcase international

- cmd/gittar/conf/i18n/i18n.yaml
- internal/tools/gittar/ai/cr/impl/cr_mr/mr.go
- internal/tools/gittar/ai/cr/impl/cr_mr_code_snippet/prompt-zh.yaml
- internal/tools/gittar/ai/cr/impl/cr_mr_code_snippet/prompt.yaml
- internal/tools/gittar/ai/cr/impl/cr_mr_code_snippet/snippet.go
- internal/tools/gittar/ai/cr/impl/cr_mr_file/file.go
- internal/tools/gittar/ai/cr/util/aiutil/invoke.go
- internal/tools/gittar/models/code_reviewe.go
- internal/tools/gittar/models/i18n.go
- internal/tools/gittar/models/note.go
ai mr code-review:
- get suggestion through ai-proxy session directly
- better i18n for session topic and prompts
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=561316&iterationID=12783&type=TASK)
| 🇺🇸 English |     better ai mr cr code snippet session          |
| 🇨🇳 中文    |    更好的 ai code-review 代码片段会话处理          |
Add comment like `/cherry-pick release/2.4-beta.5` when this PR is merged.
> fix(gittar): better ai mr cr code snippet session

- cmd/erda-server/conf/i18n/cp/scenarios/issue-manage.yaml
- internal/apps/dop/component-protocol/components/issue-manage/batchOperationTipModal/render.go
- internal/apps/dop/component-protocol/components/issue-manage/issueTable/render.go
fix: fix bulk deletion bug
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMywyMzM3Niw0NDE0LDQ0MTUsMjQ3OTYsMjQ3OTcsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDQzMjUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&tab=BUG)
| 🇺🇸 English |        fix: fix bulk deletion bug      |
| 🇨🇳 中文    |      修复批量删除多选框在删除后10条取消        | …
> fix: fix bulk deletion bug

- internal/tools/gittar/metrics/collector.go
- internal/tools/gittar/pkg/util/collector_test.go
feat: add code collection for all branches
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNywyMTAwMSw0NDEyLDQ1MzgsNDQxMywyMzM3Niw0NDE0LDQ0MTUsMjQ3OTYsMjQ3OTcsNDQxNiw0NDE4LDIzMjM2LDQ0MTksNDQyMCw0NDIxLDQ0MjJdLCJhc3NpZ25lZUlEcyI6WyIyMDEyNjIwIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9)
| 🇺🇸 English |      feat: add code collection for all branches        |
| 🇨🇳 中文    |      增加全代码采集分析        | …
> feat: add code collection for all branches

- api/proto/apps/aiproxy/audit/audit.proto
- cmd/ai-proxy/conf/routes.yml
- internal/apps/ai-proxy/filters/audit-before-llm-director/req.go
- internal/apps/ai-proxy/filters/audit-before-llm-director/resp.go
- internal/apps/ai-proxy/filters/body-size-limit/filter.go
- internal/apps/ai-proxy/filters/context-chat/filter.go
- internal/apps/ai-proxy/filters/context/filter.go
- internal/apps/ai-proxy/filters/rate-limit/filter.go
- internal/apps/ai-proxy/models/audit/dbclient.go
- internal/apps/ai-proxy/models/metadata/meta_audit.go
- internal/apps/ai-proxy/vars/header.go
- adapt GPT-4V
- split context to basic&specific context
- record filter intercepted error to audit; add rate-limit error now
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=561969&iterationID=12783&tab=REQUIREMENT&type=REQUIREMENT)
| 🇺🇸 English |     polish audit of ai-proxy         |
| 🇨🇳 中文    |    优化 ai-proxy 的审计          |
> feat(ai-proxy): polish audit

- conf/i18n/common.yml
- internal/apps/dop/providers/issue/core/state.go
fix:create-state adds duplicate name verification
fix:create-state adds duplicate name verification
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=560567&iterationID=12783&tab=BUG&type=BUG)
| 🇺🇸 English |        fix:create-state adds duplicate name verification      |
| 🇨🇳 中文    |        修复了组织下的协同事项工作流出现了两个测试中，同时增加重名校验      |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING …
> fix: create-state adds duplicate name verification

- internal/apps/dop/providers/issue/core/query/svc.go
issue-kanban show all states issues
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=562165&iterationID=12783&tab=TASK&type=TASK)
/assign @sfwn 
| 🇺🇸 English |   issue-kanban show all states issues           |
| 🇨🇳 中文    |      事项看板展示所有状态的事项        |
> chore(erda-server): issue-kanban show all states issues

- erda.yml
According to the O&M alarm, the collector-agent cannot meet the resource requirements.
| 🇺🇸 English | optimize collector-agent memory             |
| 🇨🇳 中文    | 优化 collector-agent 内存             |
> chore: optimize collector-agent memory

- internal/tools/orchestrator/services/addon/addon_handler.go
remove the logic for deploying the default version of cluster addon 
/assign @iutx 
| 🇺🇸 English |       remove the logic for deploying the default version of cluster addon        |
| 🇨🇳 中文    |       删除集群级别addon部署默认版本的逻辑       |
> feat: remove the logic for deploying the default version of cluster addon 

- apistructs/addon.go
- cmd/orchestrator/conf/i18n/orchestrator-log-trans.yaml
- internal/tools/orchestrator/services/addon/addon_handler.go
add deprecated field for addon, and deal with it at deployment time
/assign @iutx 
| 🇺🇸 English |      add `deprecated` field for addon, and deal with it at deployment time        |
| 🇨🇳 中文    |      为addon添加一个`废弃`字段，并在部署的时候处理这种Addon        |
> feat: add deprecated field for addon

- go.mod
- go.sum
upgrade profile client
/assign @sfwn 
| 🇺🇸 English |     upgrade profile client         |
| 🇨🇳 中文    |    升级可持续观测的client          |
> chore(monitor): upgrade profile client

- build/dockerfiles/Dockerfile
```shell
npm ERR! request to https://registry.npm.taobao.org/jackson-converter failed, reason: certificate has expired
```
| 🇺🇸 English |  update npm mirrors            |
| 🇨🇳 中文    |     更新 npm 镜像         |
> chore: update npm mirrors

- internal/tools/orchestrator/services/addon/addon_status.go
fix canal admin database param empty
/assign @luobily @sfwn 
| 🇺🇸 English |   fix canal admin database param empty           |
| 🇨🇳 中文    |   修复 canal admin 模式数据库参数缺失问题          |
> fix(orchestrator): canal admin database param empty

- api/proto/msp/apm/notifygroup/notifygroup.proto
add scopeId for notifygroup proto
/assign @iutx 
| 🇺🇸 English |      add scopeId for notifygroup proto        |
| 🇨🇳 中文    |      在通知组proto文件中添加参数`scopeId`         |
> feat: add scopeId for notifygroup proto

- internal/apps/cmp/dbclient/records.go
fix SQL injection in cmp
| 🇺🇸 English |       fix SQL injection in cmp       |
| 🇨🇳 中文    |        修复CMP中的SQL注入问题      |
> fix: fix SQL injection in cmp

- go.mod
- go.sum
- internal/apps/dop/dbclient/apitest.go
- internal/apps/dop/dbclient/project_test_env.go
- internal/tools/orchestrator/hepa/repository/orm/build_cond.go
- internal/tools/orchestrator/hepa/repository/orm/orm_engine.go
- internal/tools/pipeline/providers/definition/db/define.go
- internal/tools/pipeline/providers/definition/db/define_test.go
- pkg/database/cimysql/mysql.go
Upgraded xormplus version due to issues like query for sqlite3 on soft deletes in the old version. 
Besides, adjusted calls in erda to the methods which removed in new version.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=570664&iterationID=12783&type=TASK)
/assign #sfwn
| 🇺🇸 English |  chore: Bump xormplus version and replace calls to removed methods in new xorm version            |
| 🇨🇳 中文    |   升级了xormplus的版本，并替换了erda中对新版本已移除的某些方法的调用           |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-me …
> chore: bump xormplus version

- api/proto/msp/apm/notifygroup/notifygroup.proto
fix notifygroup exception notice in erda-server
change scopeID to scopeId in proto
| 🇺🇸 English |     fix notifygroup exception notice in erda-server         |
| 🇨🇳 中文    |     修复erda-server构建的镜像通知组异常提示        |
> fix: notifygroup exception notice in erda-server

- internal/core/legacy/dao/application.go
display the app list search results based on their relevancy(sorted based on their length of display_name)
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=562550&iterationID=12783&type=BUG)
/assign @sfwn 
| 🇺🇸 English |    display the app list search results based on their relevancy          |
| 🇨🇳 中文    |    新增应用模糊查询时按匹配度排序（根据查询的字段长度）          |
> feat: display the app list search results based on their relevancy

- internal/apps/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/inparams.go
- internal/apps/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/inparams_test.go
- internal/apps/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
fix issue of displaying pipelines from other applications while filtering in application's pipeline
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=553755&iterationID=12783&tab=ALL&type=BUG)
| 🇺🇸 English |   fix: incorrect app pipeline filtering           |
| 🇨🇳 中文    |    修复了在应用的流水线页面筛选时获得其他应用流水线的问题          |
> fix: incorrect app pipeline filtering

- internal/tools/gittar/ai/cr/impl/cr_mr/mr.go
- pkg/limit_sync_group/group.go
Fix gittar oom
- Fix gittar oom
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=568090&iterationID=13633&type=TASK)
| 🇺🇸 English |      Fix gittar oom        |
| 🇨🇳 中文    |       修复 gittar oom 问题       |
> fix: fix gittar oom

- internal/tools/pipeline/dbclient/op_pipeline.go
- internal/tools/pipeline/dbclient/op_pipeline_stage.go
- internal/tools/pipeline/dbclient/op_pipeline_task.go
- internal/tools/pipeline/dbclient/op_pipeline_task_test.go
- internal/tools/pipeline/providers/build/db/ci_v3_build_cache.go
- internal/tools/pipeline/providers/cache/impl_test.go
- internal/tools/pipeline/providers/cron/cron.service_test.go
- internal/tools/pipeline/providers/cron/db/define_extra.go
- internal/tools/pipeline/providers/edgereporter/reporter_test.go
- internal/tools/pipeline/providers/pipeline/callback_test.go
- internal/tools/pipeline/providers/pipeline/create_test.go
- internal/tools/pipeline/providers/pipeline/rerun_test.go
- internal/tools/pipeline/providers/reconciler/snippet_test.go
- internal/tools/pipeline/providers/reconciler/task_reconciler.go
- internal/tools/pipeline/providers/reconciler/task_reconciler_test.go
- internal/tools/pipeline/providers/reconciler/taskpolicy/provider.go
The new version of `xorm` does not support passing `*uint64` type in the ID method, so the corresponding usage here will be adjusted
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=573348&iterationID=-1&type=BUG)
/assign @sfwn 
| 🇺🇸 English |  fix: xorm.ID() does not support ptr type            |
| 🇨🇳 中文    |    修复了xorm.ID()方法传入指针类型的情况          |
> fix: xorm.ID() does not support ptr type

- api/proto/dop/issue/core/core.proto
- internal/apps/devflow/flow/issue_mock.go
- internal/apps/dop/component-protocol/components/issue-manage/issueTable/render.go
- internal/apps/dop/providers/issue/core/property.go
- internal/apps/dop/providers/issue/core/query/paging.go
- internal/apps/dop/providers/issue/core/query/property.go
- internal/apps/dop/providers/issue/core/query/provider.go
- internal/apps/dop/providers/issue/dao/issue_property.go
- pkg/mock/issue_query_mock.go
fix: fix p.BatchGetIssuePropertyInstances func
refactor: Unexposure OpenAPI and optimized code
fix: fix partial requirement list filtering does not include custom fields
refactor: use PropertyTypeEnum
feat: Change onlyProject to onlyCurrentScopeType
refactor: delete excess property-relation
fix: fix p.BatchGetIssuePropertyInstances func
refactor: Unexposure OpenAPI and optimized code
fix: fix partial requirement list filtering does not include custom fields
refactor: use PropertyTypeEnum
feat: Change onlyProject to onlyCurrentScopeType
refactor: delete excess property-relation
- [清理组织级别自定义事项](https://erda.cloud/erda/dop/projects/387/issues/all?id=567378&iterationID=12783&type=TASK)
- [协同事项筛选字段重复](https://erda.cloud/erda/dop/projects/387/issues/all?id=573504&itera …
> feat: add MigrateOrgCustomFileds interface

- internal/tools/pipeline/providers/dbgc/provider.go
add pipeline archive retain hour env
/assign @sfwn 
| 🇺🇸 English |   Support pipeline archive retain hour env           |
| 🇨🇳 中文    |     pipeline archive保留时间的env配置         |
> feat(pipeline): add pipeline archive retain hour env

- cmd/ai-proxy/bootstrap.yml
- cmd/ai-proxy/conf/routes/assistant.yml
- cmd/ai-proxy/conf/routes/file.yml
- internal/apps/ai-proxy/filters/context-file/filter.go
ai-proxy support complete file apis
| 🇺🇸 English |   ai-proxy support complete file apis           |
| 🇨🇳 中文    |   ai-proxy 支持完整的 file apis           |
> feat(ai-proxy): support complete file apis

- internal/tools/pipeline/providers/pipeline/cancel.go
fix pipeline cancel missing user when req userid is empty
/assign @sfwn 
| 🇺🇸 English |  Fix the bug that pipeline cancel missing user when req userid is empty            |
| 🇨🇳 中文    |     修复了停止流水线时缺失用户信息的问题         |
> fix(pipeline): pipeline cancel missing user when req userid is empty

- cmd/orchestrator/conf/i18n/orchestrator-log-trans.yaml
- internal/tools/orchestrator/services/addon/addon_handler.go
- internal/tools/orchestrator/services/addon/addon_test.go
- internal/tools/orchestrator/services/deployment/deployment_context.go
optimize deploy addon error message alerts
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=570070&iterationID=12783&type=TASK)
/assign @iutx 
| 🇺🇸 English |       optimize deploy addon error message alerts       |
| 🇨🇳 中文    |       Addon 部署预检查优化版本提示       |
> feat: optimize deploy addon error message alerts

- internal/apps/dop/component-protocol/components/issue-manage/batchOperationTipModal/model.go
- internal/apps/dop/component-protocol/components/issue-manage/batchOperationTipModal/render.go
fix: fix batch EOF deletion error
fix: fix batch EOF deletion error
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=577689&iterationID=12783&type=BUG)
/assign @sfwn 
| 🇺🇸 English |       fix: fix batch EOF deletion error       |
| 🇨🇳 中文    |       修复批量删除 EOF 错误       |
> fix: fix batch EOF deletion error

- go.mod
- go.sum
Upgrade erda-infra version. [PR](https://github.com/erda-project/erda-infra/pull/318)
/assign @sfwn 
| 🇺🇸 English |  upgrade erda-infra version            |
| 🇨🇳 中文    |     升级 erda-infra 版本         |
> chore: upgrade erda-infra version

- internal/tools/pipeline/aop/plugins/task/autotest_cookie_keep_after/plugin.go
fix non-config autotest missing cookie header between step
remove useless secret judgments
/assign @sfwn 
| 🇺🇸 English |  Fix the bug that non-config autotest missing cookie header between step            |
| 🇨🇳 中文    |   修复了没有配置环境的自动化测试接口丢失cookie的问题           |
> fix(pipeline): non-config autotest missing cookie header between step

- internal/tools/gittar/conf/conf.go
- internal/tools/gittar/conf/conf_test.go
- internal/tools/gittar/metrics/collector.go
add `feature/develop` for collecting git metrics
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=583937&iterationID=12783&tab=TASK&type=TASK)
/assign @sfwn 
| 🇺🇸 English |   Support add `feature/develop` for collecting git metrics           |
| 🇨🇳 中文    |    增加代码指标扫描的分支，支持可配          |
> feat(gittar): add `feature/develop` for collecting git metrics

- internal/apps/msp/tenant/db/tenant.go
fix  msp tenant missing related workspace
/assign @sfwn 
| 🇺🇸 English |    Fix the bug that msp tenant missing related workspace          |
| 🇨🇳 中文    |    修复了msp tenant丢失workspace的问题          |
> fix(msp):  msp tenant missing related workspace

- internal/tools/gittar/conf/conf.go
- internal/tools/gittar/metrics/collector.go
add organization whitelist configuration for code contribution
/assign @sfwn 
| 🇺🇸 English |    Support add organization whitelist configuration for code contribution          |
| 🇨🇳 中文    |   代码贡献采集增加组织白名单的可选配置           |
> feat(gittar): add organization whitelist configuration for code contribution

- internal/apps/msp/apm/browser/consumer.go
- internal/tools/monitor/core/collector/routes.go
browser analysics support attributes
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=586748&iterationID=12783&type=TASK)
/assign  @sfwn 
| 🇺🇸 English | browser analysics support attributes             |
| 🇨🇳 中文    |  浏览器数据分析支持属性字段            |
> feat: browser analysics support attributes

- cmd/erda-server/bootstrap.yaml
- internal/core/openapi/openapi-ng/interceptors/csrf/csrf.go
support set some http cookie security configuration
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=588168&iterationID=12783&type=TASK)
/assign @sfwn 
| 🇺🇸 English |    support set some http cookie security configuration          |
| 🇨🇳 中文    |   支持设置一些http cookie的安全配置           |
> feat: support set some http cookie security configuration

- internal/core/openapi/openapi-ng/interceptors/csrf/csrf.go
fix: csrf same site type error
/assign @sfwn 
| 🇺🇸 English |    Fix the bug that csrf same site type error          |
| 🇨🇳 中文    |    修复same site字段类型错误          |
> fix: csrf same site type error

- cmd/cluster-agent/bootstrap.yaml
- internal/tools/cluster-agent/config/config.go
- internal/tools/cluster-agent/pkg/client/client.go
- internal/tools/cluster-agent/pkg/client/client_test.go
1. replace apply token to create service account token secret.
2. dprecate get token from file.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=593225&iterationID=12783&type=TASK)
/assign @sfwn 
| 🇺🇸 English |  replace apply token to create service account token secret            |
| 🇨🇳 中文    |    创建 serviceaccount token secret 代替申请 token          |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md …
> feat: replace apply token to create service account token secret

- go.mod
- go.sum
upgrade infra for grpc server configuration
/assign @sfwn 
| 🇺🇸 English |    upgrade infra for grpc server configuration          |
| 🇨🇳 中文    |     升级erda-infra版本         |
> chore: upgrade infra for grpc server configuration

- internal/apps/dop/services/pipeline/pipeline.go
fix pipeline and queue cluster do not match when `job_cluster` is set
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that pipeline and queue cluster do not match when `job_cluster` is set           |
| 🇨🇳 中文    |     修复了在设置`job_cluster`时, 流水线与队列集群不匹配的问题         |
> fix: pipeline and queue cluster do not match when `job_cluster` is set

- internal/tools/monitor/core/log/query/log.query.service.go
- internal/tools/monitor/core/log/query/log.query.service_test.go
- internal/tools/monitor/core/log/query/routes.go
Related pr: [6338](https://github.com/erda-project/erda/pull/6338)
TBD: use main org to tag erda platform log.
| 🇺🇸 English |   fix  log service multi org search error           |
| 🇨🇳 中文    |  修复日志服务多企业查询错误            |
> fix: log service multi org search error

- .erda/pipelines/ci-build-ce.yml
- .erda/pipelines/ci-deploy.yml
- api/proto-go/Makefile
- pipeline.yml
upgrade base image for default pipeline
/assign @sfwn 
| 🇺🇸 English |  upgrade base image for default pipeline             |
| 🇨🇳 中文    |    更新默认流水线的base镜像          |
> chore: upgrade base image

- internal/apps/ai-proxy/filters/azure-director/filter.go
- internal/apps/ai-proxy/filters/context-chat/filter.go
- internal/apps/ai-proxy/filters/dashscope-director/req.go
- internal/apps/ai-proxy/filters/dashscope-director/resp.go
- internal/apps/ai-proxy/filters/dashscope-director/sdk/converter.go
- internal/apps/ai-proxy/filters/openai-director/filter.go
ai-proxy: use logger with filter name to facilitate problem location
| 🇺🇸 English |   ai-proxy: use logger with filter name to facilitate problem location           |
| 🇨🇳 中文    |  ai-proxy: 使用带有 filter 名称的 logger 以方便问题定位           |
> chore(ai-proxy): use logger with filter name

- internal/tools/monitor/core/collector/ta-js.md
Add ta.js status doc.
/assign @sfwn 
| 🇺🇸 English |   add ta-js.md           |
| 🇨🇳 中文    |      增加 ta.js 说明        |
> chore: add ta-js.md

- cmd/monitor/collector/bootstrap-agent.yaml
- cmd/monitor/collector/bootstrap.yaml
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=610655&iterationID=-1&type=TASK)
/assign @iutx 
| 🇺🇸 English |       Make collector support sentinel mode redis      |
| 🇨🇳 中文    |       让collector支持采集哨兵模式的redis       |
> feat: make collector support sentinel mode redis 

- cmd/monitor/collector/bootstrap-agent.yaml
- internal/tools/monitor/oap/collector/plugins/exporters/collector/provider.go
fix collector-agent failed to report raw metrics
[erda-issue](https://erda.cloud/erda/dop/projects/387/issues/all?id=607852&iterationID=12783&tab=TASK&type=TASK)
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that collector-agent failed to report raw metrics           |
| 🇨🇳 中文    |       修复了collector-agent无法上传原始指标的问题       |
> fix: collector-agent failed to report raw metrics

- internal/tools/pipeline/providers/lifecycle_hook_client/life.cycle.service.go
extend post life cycle hook timeout
/assign @sfwn 
| 🇺🇸 English |   extend post life cycle hook timeout           |
| 🇨🇳 中文    |     延长lifecycle hook的超时时间         |
> chore(pipeline): extend post life cycle hook timeout

- .erda/migrations/config.yml
- .erda/migrations/pipeline/20240702-runner-scheduler-add-orgid.sql
update baseline checksum.
[PR](https://github.com/erda-project/erda/pull/6385)
/assign @sfwn 
| 🇺🇸 English |  update baseline checksum            |
| 🇨🇳 中文    |      修改基线校验值       |
> chore: update baseline checksum

- internal/apps/msp/apm/service/components/resources-container-monitor/container/provider.go
fix container memory usage/limit metrics
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=612862&iterationID=-1&tab=BUG&type=BUG)
/assign @sfwn 
| 🇺🇸 English |  Fix the bug that container memory usage/limit metric            |
| 🇨🇳 中文    |     修复了资源监控中内存指标不准的问题         |
> fix: container memory usage/limit metric

- internal/apps/cmp/provider.go
cmp cfg nil pointer
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=613226&iterationID=12783&type=BUG)
/assign @iutx 
| 🇺🇸 English |      cmp cfg nil pointer         |
| 🇨🇳 中文    |      修复cfg空指针        |
> fix: cmp cfg nil pointer

- cmd/erda-server/bootstrap.yaml
- internal/apps/dop/providers/autotest/testplan/db/testplan.go
- internal/apps/dop/providers/autotest/testplan/provider.go
- internal/apps/dop/providers/autotest/testplan/testplan.service.go
support auto test exec history info database gc
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=615953&iterationID=12783&tab=ALL&type=TASK)
/assign @sfwn 
| 🇺🇸 English |   support auto test exec history info database gc           |
| 🇨🇳 中文    |     支持自动化测试结果后台dbgc         |
> feat: support auto test exec history info database gc

- internal/apps/msp/apm/service/view/card/avg_duration.go
- internal/apps/msp/apm/service/view/chart/avg_duration.go
- internal/apps/msp/apm/service/view/chart/avg_duration_distribution.go
- internal/apps/msp/apm/service/view/chart/error_duration_distribution.go
- internal/apps/msp/apm/service/view/chart/slow_duration_distribution.go
fix char/card,slow/error avg duration mistake
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=616855&iterationID=12783&tab=BUG&type=BUG)
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that char/card,slow/error avg duration mistake           |
| 🇨🇳 中文    |   修复了调用监控图表中平均耗时不准的问题           |
> fix(monitor): char/card,slow/error avg duration mistake

- internal/apps/dop/providers/project_report/provider.go
- internal/apps/dop/providers/project_report/query.go
- internal/apps/dop/providers/project_report/query_test.go
fix(dop):  project report sql injection
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=611654&iterationID=12783&tab=BUG&type=BUG)
/assign @sfwn 
| 🇺🇸 English | Fix the bug that project report sql injection             |
| 🇨🇳 中文    |    修复了项目报表sql注入的问题          |
> fix(dop):  project report sql injection

- internal/tools/orchestrator/dbclient/deployment.go
- internal/tools/orchestrator/services/deployment/deployment_context.go
- internal/tools/orchestrator/services/runtime/runtime.go
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=585516&iterationID=12783&type=TASK)
/assign @iutx 
| 🇺🇸 English |     fix release wrong gc        |
| 🇨🇳 中文    |      修复release制品被错误回收        |
> fix: release wrong gc

- internal/tools/orchestrator/dbclient/tmc_instance.go
- internal/tools/orchestrator/services/addon/addon.go
interlink deployed versions, whether deprecated or not
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=615447&iterationID=-1&type=TASK)
/assign @iutx 
| 🇺🇸 English |      interlink deployed versions, whether deprecated or not        |
| 🇨🇳 中文    |       关联已经部署的版本，不管是否被废弃       |
> feat: interlink deployed versions, whether deprecated or not

- internal/tools/monitor/core/log/storage/clickhouse/iterator.go
1. fix log-service timestamp order.
2. sql structure clearly.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=618183&iterationID=12783&type=BUG)
/assign @sfwn 
| 🇺🇸 English |fix log-service timestamp order              |
| 🇨🇳 中文    |      修复 log-service 时间排序问题        |
> fix(monitor): log-service timestamp order

- internal/apps/ai-proxy/common/image/image.go
- internal/apps/ai-proxy/filters/dashscope-director/resp.go
- internal/apps/ai-proxy/filters/dashscope-director/sdk/converter.go
- internal/apps/ai-proxy/filters/dashscope-director/sdk/resp.go
ai-proxy: fix non-stream mode of dashscope series models
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=618328&iterationID=12783&tab=ALL&type=TASK)
| 🇺🇸 English |   fix ai-proxy non-stream mode of dashscope series models           |
| 🇨🇳 中文    |  修复 ai-proxy dashscope 系列模型的非流式模式            |
> fix(ai-proxy): dashscope non-stream mode works now

- go.mod
- go.sum
- internal/tools/orchestrator/scheduler/executor/plugins/k8s/terminal.go
terminal command make panic due to index out of range
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that terminal command make panic due to index out of range           |
| 🇨🇳 中文    |   修复了控制台命令审计导致的panic问题           |
> fix(orchestrator): terminal command make panic due to index out of range

- internal/tools/pipeline/aop/plugins/pipeline/basic/plugin.go
- internal/tools/pipeline/aop/plugins/task/autotest_cookie_keep_after/plugin.go
- internal/tools/pipeline/aop/plugins/task/unit_test_report/plugin.go
- internal/tools/pipeline/commonutil/statusutil/status.go
- internal/tools/pipeline/commonutil/statusutil/status_test.go
- internal/tools/pipeline/dbclient/op_pipeline.go
- internal/tools/pipeline/pexpr/pexpr_params/task_params.go
- internal/tools/pipeline/pipengine/actionexecutor/plugins/apitest/apitest.go
- internal/tools/pipeline/pkg/taskinspect/inspect.go
- internal/tools/pipeline/providers/reconciler/snippet.go
- internal/tools/pipeline/providers/reconciler/taskrun/taskop/prepare.go
- internal/tools/pipeline/providers/reconciler/taskrun/taskop/prepare_test.go
- internal/tools/pipeline/spec/pipeline_task.go
- pkg/expression/expression_execute.go
- pkg/expression/expression_execute_test.go
Fix the issue that task with status NoNeedBySystem cause pipeline status to Failed.
Commonly seen in scenario that task with if expression.
1. treat task NoNeedBySystem status as success when CalculatePipelineStatusV2
2. set task status to AnalyzedFailed when if-expression parsed error
3. pipeline.task.inspect add metadata field for internal use
4. add more info for if expression exec result
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=617844&iterationID=12783&type=BUG)
| 🇺🇸 English |   Fix the issue that task with status NoNeedBySystem cause pipeline status to Failed.           |
| 🇨🇳 中文    |   修复了无需执行的 action 导致流水线状态为失败的问题          |
> fix(pipeline): task with status NoNeedBySystem cause pipeline status to Failed

- build/dockerfiles/Dockerfile
remove unused orgalorg
| 🇺🇸 English |  remove unused orgalorg            |
| 🇨🇳 中文    |    移除  orgalorg        |
> chore: remove unused orgalorg

- cmd/monitor/collector/bootstrap-agent.yaml
- cmd/monitor/collector/bootstrap.yaml
- internal/tools/monitor/oap/collector/core/model/odata/raw.go
- internal/tools/monitor/oap/collector/plugins/processors/dropper/provider.go
- internal/tools/monitor/oap/collector/plugins/receivers/collector/provider.go
- internal/tools/monitor/oap/collector/plugins/receivers/collector/provider_test.go
collector `dropper` processor support raw data
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=620248&iterationID=12783&type=TASK)
/assign @sfwn 
| 🇺🇸 English |  collector `dropper` processor support raw data            |
| 🇨🇳 中文    |     collector `dropper`控制器支持去除raw data类型的数据         |
> feat(collector): collector `dropper` processor support raw data

- internal/tools/pipeline/providers/cron/db/define.go
- internal/tools/pipeline/providers/cron/db/examples/client.go
- internal/tools/pipeline/providers/cron/db/examples/examples.yaml
- internal/tools/pipeline/providers/cron/db/examples/main.go
- internal/tools/pipeline/providers/dbgc/definition_cleanup/definition_cleanup.go
- internal/tools/pipeline/providers/dbgc/definition_cleanup/local_debug/local-debug.yaml
- internal/tools/pipeline/providers/dbgc/definition_cleanup/local_debug/main.go
- internal/tools/pipeline/providers/dbgc/definition_cleanup/provider.go
make pipeline definition cleanup works.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=620862&iterationID=12783&type=TASK)
| 🇺🇸 English |   make pipeline definition cleanup works           |
| 🇨🇳 中文    |    使 "流水线定义清理" 工作          |
> fix(pipeline): make pipeline definition cleanup works

- internal/tools/orchestrator/services/addon/addon_handler.go
- internal/tools/orchestrator/services/addon/addon_status.go
- internal/tools/orchestrator/services/addon/addon_status_test.go
fix canal interlink
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=610448&iterationID=12783&type=BUG)
/assign @iutx 
| 🇺🇸 English |       fix canal interlink       |
| 🇨🇳 中文    |       修复canal关联问题，同一个canal实例但存在多个routing       |
> fix: canal interlink

- go.mod
- go.sum
- internal/tools/cluster-manager/dialer/server/tunnel-server.go
fix cluster registration information is overwritten
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=388338&iterationID=12783&type=BUG)
/assign @iutx 
| 🇺🇸 English |      fix cluster registration information is overwritten        |
| 🇨🇳 中文    |       修复集群注册信息被覆盖       |
> fix: cluster registration information is overwritten

- internal/tools/pipeline/providers/dbgc/definition_cleanup/provider.go
- internal/tools/pipeline/providers/leaderworker/heartbeat.go
- internal/tools/pipeline/providers/leaderworker/impl_worker.go
pipeline stuck in queue status because etcd server abnormal
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=625465&iterationID=12783&tab=BUG&type=BUG)
/assign @sfwn 
| 🇺🇸 English |     Fix the bug that pipeline stuck in queue status because etcd server abnormal          |
| 🇨🇳 中文    |    修复了pipeline由于etcd server的异导致流水线卡在排队的状态          |
> fix:  pipeline stuck in queue status because etcd server abnormal

- pkg/parser/diceyml/basic_validate_visitor_test.go
- pkg/parser/diceyml/diceyml.go
fix dice yaml replace * error
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=632619&iterationID=-1&pId=0&type=BUG)
/assign @iutx 
| 🇺🇸 English |      fix dice yaml replace * error        |
| 🇨🇳 中文    |      修复dice yaml 替换 * 后导致反序列化错误        |
> fix: dice yaml replace * error

- .github/workflows/ci-it.yml
Reverts erda-project/erda#6430
> Revert "chore(deps): bump actions/download-artifact from 3 to 4.1.7 in /.github/workflows"

- internal/tools/orchestrator/dbclient/addon_instance.go
- internal/tools/orchestrator/services/addon/addon.go
- internal/tools/orchestrator/services/addon/addon_test.go
fix inject register-center version and gorm query condition
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=635446&iterationID=-1&type=BUG)
/assign @iutx 
| 🇺🇸 English |      fix inject register-center version and gorm query condition        |
| 🇨🇳 中文    |     修复注册中心版本自动注入，修改注册中心查询条件         |
> fix: inject register-center version and gorm query condition

- internal/apps/dop/endpoints/pipeline.go
adjust priority for config namespace
/assign @sfwn 
| 🇺🇸 English |    adjust priority for config namespace          |
| 🇨🇳 中文    |     整cicd流水线的配置ns优先级顺序         |
> fix: adjust priority for config namespace

- pipeline.yml
change pipeline.yml migration database from pipeline env
/assign @sfwn 
| 🇺🇸 English |  change pipeline.yml migration database from pipeline env          |
| 🇨🇳 中文    |      修改流水线 migration 数据库从环境变量获取       |
> chore: change pipeline.yml migration database from pipeline env

- internal/core/messenger/eventbox/dispatcher/filters/webhookfilter.go
- internal/core/messenger/eventbox/dispatcher/filters/webhookfilter_test.go
- internal/core/messenger/eventbox/webhook/builtin.go
- internal/core/messenger/eventbox/webhook/http.go
- internal/core/messenger/eventbox/webhook/impl.go
optimize list hooks for avoid unnecessary json marshal/unmarshal
/assign @sfwn 
| 🇺🇸 English |   optimize list hooks for avoid unnecessary json marshal/unmarshal            |
| 🇨🇳 中文    |    优化eventbox避免json序列化/反序列化的消耗          |
> refactor: optimize list hooks for avoid unnecessary json marshal/unmarshal

- apistructs/audits.go
- conf/erda-configs/audit/template.json
- internal/tools/orchestrator/endpoints/runtime.go
- internal/tools/orchestrator/services/runtime/runtime.go
Add kill pod audit template.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=734127&iterationID=12783&type=TASK)
| 🇺🇸 English |   add kill pod audit template           |
| 🇨🇳 中文    |     增加删除 Pod 审计模板         |
> chore: add kill pod audit template

- go.mod
- go.sum
- internal/tools/cluster-manager/dialer/server/tunnel-server.go
update remotedialer for cluster manager
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=641533&iterationID=-1&type=TASK)
| 🇺🇸 English |      update remotedialer for cluster manager        |
| 🇨🇳 中文    |     更新cluster-manager中的remotedialer        |
> feat: update remotedialer

- cmd/ai-proxy/conf/routes/routes.yml
- internal/apps/ai-proxy/filters/azure-director/filter.go
- internal/apps/ai-proxy/models/metadata/meta_model_provider.go
AI-Proxy support DeepSeek-R1 through Azure AI Services.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=736551&iterationID=12783&type=TASK)
| 🇺🇸 English |    AI-Proxy support DeepSeek-R1 through Azure AI Services          |
| 🇨🇳 中文    |   AI-Proxy 通过 Azure AI Services 支持 DeepSeek-R1           |
> feat(ai-proxy): support DeepSeek-R1 through Azure AI Services

- internal/apps/dop/component-protocol/components/app-runtime/list/list.go
- internal/tools/orchestrator/services/runtime/runtime.go
1. Fix runtime service wg not released properly.
2. Remove redundant code.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=737679&iterationID=14541&type=TASK)
| 🇺🇸 English |   runtime service wg not released properly           |
| 🇨🇳 中文    |    Runtime Service WG 没有正确释放          |
> fix(orchestrator): runtime service wg not released properly

- internal/tools/pipeline/spec/pipeline.go
- internal/tools/pipeline/spec/pipeline_test.go
Running pipeline, will panic: runtime error: invalid memory address or nil pointer dereference at EnsureGc
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=739303&iterationID=-1&type=TASK)
| 🇺🇸 English |    fix pipeline panic from nil pointer          |
| 🇨🇳 中文    |       修复了流水线运行时，因为空指针报错重启       |
> fix: pipeline EnsureGc nil pointer panic

- internal/tools/orchestrator/services/addon/addon.go
if registercenter is not exist, but config-center exists, use config-center version
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=741492&iterationID=-1&type=BUG)
| 🇺🇸 English |       if registercenter is not exist, but config-center exists, use config-center version       |
| 🇨🇳 中文    |    如果已部署的注册中心不存在，则使用已部署的配置中心的版本          | …
> fix: use exist addon instance version

- internal/tools/orchestrator/conf/conf.go
- internal/tools/orchestrator/scheduler/executor/plugins/k8s/instanceinfosync/gc.go
- internal/tools/orchestrator/scheduler/instanceinfo/instance.go
- internal/tools/orchestrator/scheduler/instanceinfo/instance_test.go
1. Replace the Chinese placeholder `？` with the appropriate value.
2. Optimize delete logic.
3. Reset `values` and `conditions` in all return statement.
4. Support params PodInstanceGCRecentDays, default: 7 days ago.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=750869&iterationID=12783&type=TASK)
/assign @sfwn 
| 🇺🇸 English |  fix instance gc failed            |
| 🇨🇳 中文    |      修复实例 gc 失败        | …
> fix(orchestrator): instance gc failed

- go.mod
- go.sum
- internal/apps/ai-proxy/filters/azure-director/filter.go
- internal/apps/ai-proxy/filters/azure-director/filter_test.go
- internal/apps/ai-proxy/filters/azure-director/req_test.json
- internal/apps/ai-proxy/filters/context-chat/filter.go
- internal/apps/ai-proxy/filters/openai-director/filter.go
- internal/tools/gittar/ai/cr/util/aiutil/invoke.go
ai-proxy /chat/completions api support json schema
| 🇺🇸 English |     ai-proxy /chat/completions api support json schema         |
| 🇨🇳 中文    |      ai-proxy使/chat/completions接口支持json Schema        |
> feat: /chat/completions support json schema

- internal/apps/msp/resource/deploy/handlers/mysql/mysql.go
- internal/tools/orchestrator/services/addon/addon.go
feat: skip registercenter if it is terminus-zkproxy
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=756222&iterationID=12783&type=TASK)
| 🇺🇸 English |       feat: skip interlink if  registercenter is terminus-zkproxy       |
| 🇨🇳 中文    |      terminus-zkproxy不关联配置中心        |
> feat: skip registercenter if it is terminus-zkproxy

- internal/apps/dop/dao/testset.go
- Add sorting by latest updated time in descending order when viewing the first-level directory in the Recycle Bin
- Retain existing order_num sorting for other cases
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=758934&iterationID=14541&type=TASK)
/assign @sfwn 
| 🇺🇸 English |  enhance testset sorting for Recycle Bin            |
| 🇨🇳 中文    |    增强功能测试回收站排序体验          | …
> feat(dop): enhance testset sorting for Recycle Bin

- .erda/ai-proxy/migrations/ai-proxy/20250321-mcp-server.sql
- api/proto/apps/aiproxy/mcp_server/mcp_server.proto
- internal/apps/ai-proxy/handlers/handler_mcp_server/handler.go
- internal/apps/ai-proxy/handlers/permission/method.go
- internal/apps/ai-proxy/models/mcp_server/dbclient.go
- internal/apps/ai-proxy/models/mcp_server/table.go
- internal/apps/ai-proxy/provider.go
- internal/apps/ai-proxy/providers/dao/provider.go
Feat: ai-proxy support mcp servers
/assign @sfwn @CeerDecy 
| 🇺🇸 English |  ai-proxy support mcp servers            |
| 🇨🇳 中文    |     ai-proxy 支持 MCP Servers         |
> feat: ai-proxy support mcp servers

- modules/orchestrator/scheduler/instanceinfo/instance.go
- modules/orchestrator/scheduler/instanceinfo/instance_test.go
fix instances-usage sql injection
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=760955&iterationID=12783&type=BUG)
| 🇺🇸 English |      fix instances-usage sql injection        |
| 🇨🇳 中文    |        修复/instances-usage接口的SQL注入问题      |
> fix(orchestrator): instances-usage sql injection

- modules/cmp/alert.go
- modules/cmp/endpoints/cluster.go
- modules/cmp/provider.go
- modules/openapi/api/apis/cmp/cmp_alert_condition.go
- modules/openapi/api/apis/cmp/cmp_cluster_init_command.go
fix lack of access authorization
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=760956&iterationID=12783&type=BUG)
| 🇺🇸 English |      fix lack of access authorization        |
| 🇨🇳 中文    |      修复cmp接口缺少鉴权的问题        |
> fix(cmp): lack of access authorization

- cmd/erda-server/conf/msp/init_sqls/tmc/nacos2.3.sql
support nacos 2.3.2
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=759509&iterationID=12783&type=TASK)
| 🇺🇸 English |     support nacos 2.3.2         |
| 🇨🇳 中文    |      添加nacos2.3.sql，以支持nacos部署        |
> feat: add nacos2.3.sql

- .gitignore
- internal/apps/ai-proxy/filters/context/model.go
- internal/apps/ai-proxy/filters/context/model_test.go
- internal/apps/ai-proxy/filters/openai-v1-models/filter.go
- internal/apps/ai-proxy/filters/openai-v1-models/model_name.go
- internal/apps/ai-proxy/filters/openai-v1-models/publisher.go
AI-Proxy support invoking completion API by `${publisher}/${model}` format.
- [Erda Cloud Issue Link](https://erda.cloud/terminus/dop/projects/190/issues/all?id=766204&iterationID=14838&tab=ALL&type=TASK)
| 🇺🇸 English |     AI-Proxy support invoking completion API by `${publisher}/${model}` format         |
| 🇨🇳 中文    |    AI-Proxy 支持用 `${publisher}/${model}` 格式调用 completion API          |
> feat(ai-proxy): support invoking completion api by `${publisher}/${model}` format

- cmd/monitor/extensions/loghub/conf/output/bootstrap-elasticsearch-rollover.yaml
- Update index_template_file path from "conf/elasticsearch.index.template.json" to "conf/output/elasticsearch.index.template.json"- Update rollover_body_file path from "conf/elasticsearch.index.rollover.json" to "conf/output/elasticsearch.index.rollover.json"
| 🇺🇸 English | update file paths for ES index template and rollover             |
| 🇨🇳 中文    |  更新 es index 模版            | …
> fix(loghub): update file paths for ES index template and rollover

- api/proto/apps/aiproxy/model/model.proto
- internal/apps/ai-proxy/handlers/handler_model/handler.go
- internal/apps/ai-proxy/handlers/permission/method.go
- internal/apps/ai-proxy/models/model/dbclient.go
AI-Proxy add API for updating model abilities info.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=767358&iterationID=12783&type=TASK)
| 🇺🇸 English |   AI-Proxy add API for updating model abilities info           |
| 🇨🇳 中文    |    AI-Proxy 添加用于更新模型能力信息的 API          |
> feat(ai-proxy): add API for updating model abilities info

- internal/tools/monitor/core/log/query/provider.go
- internal/tools/monitor/core/log/query/routes.go
/assign @iutx 
| 🇺🇸 English |       The log download supports custom duration.       |
| 🇨🇳 中文    |        日志下载功能支持自定义时长      |
> feat: The log download supports custom duration.

- internal/apps/ai-proxy/filters/directors/anthropic-compatible-director/common/message_converter/req.go
- internal/apps/ai-proxy/filters/directors/anthropic-compatible-director/common/message_converter/resp.go
AI-Proxy support tool call.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=775047&iterationID=12783&type=TASK)
| 🇺🇸 English |    AI-Proxy support tool call          |
| 🇨🇳 中文    |    AI-Proxy 支持工具调用          |
> fix(ai-proxy): support tool call

- internal/tools/orchestrator/scheduler/executor/plugins/edas/edas.go
- update EDAS plugin to use correct fillServiceSpec parameter
- Changed the third parameter of fillServiceSpec from false to true
/assign @sfwn 
| 🇺🇸 English |  fix edas scale application command render error  |
| 🇨🇳 中文    |     修复 edas 扩缩容应用时，command 渲染错误问题         |
> fix(orchestrator): edas scale application command render error

- internal/apps/ai-proxy/cache/cachetypes/interface.go
- internal/apps/ai-proxy/cache/config.go
- internal/apps/ai-proxy/cache/config_test.go
- internal/apps/ai-proxy/cache/items.go
- internal/apps/ai-proxy/cache/manager.go
- internal/apps/ai-proxy/common/ctxhelper/keys.go
- internal/apps/ai-proxy/provider.go
- internal/apps/ai-proxy/reverse_proxy.go
- internal/apps/ai-proxy/route/filters/request/context-family/context/model.go
- internal/apps/ai-proxy/route/filters/request/context-family/context/model_test.go
AI-Proxy:
- add cache for model & provider
- model support `${model.provider.type}/${model.name}` format
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=783125&iterationID=12783&type=TASK)
| 🇺🇸 English |     AI-Proxy add cache for model & provider         |
| 🇨🇳 中文    |    AI-Proxy 为 model 和 provider 添加缓存机制          |
> feat(ai-proxy): add cache for model & provider

- cmd/ai-proxy/integration-tests/chat_completions_test.go
- cmd/ai-proxy/integration-tests/common/client.go
- internal/apps/ai-proxy/common/audit/dumplog/dump_response.go
- internal/apps/ai-proxy/provider.go
- internal/apps/ai-proxy/route/reverse_proxy/error_handler.go
- internal/apps/ai-proxy/route/reverse_proxy/request_rewrite.go
- internal/apps/ai-proxy/route/reverse_proxy/response_header.go
- internal/apps/ai-proxy/route/reverse_proxy/response_header_test.go
- internal/apps/ai-proxy/route/reverse_proxy/response_modify.go
AI-Proxy handle CORS by reverse-proxy framework directly.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=783394&iterationID=12783&type=TASK)
| 🇺🇸 English |     AI-Proxy handle CORS by reverse-proxy framework directly         |
| 🇨🇳 中文    |    AI-Proxy 在反向代理框架里直接处理 CORS          |
> fix(ai-proxy): handle CORS by reverse-proxy framework directly

- apistructs/notify_channel.go
- internal/core/messenger/eventbox/conf/conf.go
- internal/core/messenger/eventbox/dispatcher/dispatcher.go
- internal/core/messenger/eventbox/subscriber/email/email.go
- internal/core/messenger/notify-channel/channel.service.go
support email sent from anonymous user
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=788168&iterationID=-1&type=TASK)
/assign @iutx @luobily @sfwn 
| 🇺🇸 English |      support email sent from anonymous user        |
| 🇨🇳 中文    |      告警通知支持匿名邮箱用户发送邮件        |
> feat: support email sent from anonymous user in notify channel
