modules/cmp/impl/clusters/credential_test.go
modules/pipeline/conf/conf.go
modules/pipeline/pipengine/actionexecutor/plugins/k8sflink/type.go
modules/pipeline/pipengine/actionexecutor/plugins/k8sjob/k8sjob.go
modules/pipeline/pipengine/actionexecutor/plugins/k8sjob/k8sjob_test.go
modules/pipeline/pipengine/actionexecutor/plugins/k8sspark/type.go
pkg/k8sclient/client.go

in-cluster pipeline job create k8sclient directly
/assign @sfwn 
| 🇺🇸 English |  in-cluster pipeline job create k8sclient directly            |
| 🇨🇳 中文    |    当前集群的流水线任务直连k8s          |

feat(pipeline): in-cluster pipeline job create k8sclient directly

---

modules/dicehub/release/release.go
modules/dicehub/release/release.service.go

fix: panic when parse empty dice yml
| 🇺🇸 English | fix: panic when parse empty dice yml |
| 🇨🇳 中文    | 修复解析空dice.yml时panic的问题 |

fix: panic when parse empty dice yml

---

go.mod
go.sum
pkg/crypto/uuid/snowflake.go
pkg/crypto/uuid/snowflake/machine_id.go
pkg/crypto/uuid/snowflake/machine_id_test.go
pkg/crypto/uuid/snowflake/snowflake.go
pkg/crypto/uuid/snowflake_test.go

implement 53-bit snowflake id for js compatible.
SnowFlakeIDUint64 return sequence uuid:
- 38 bits for time in units of 10 msec
- 7 bits for a sequence number
- 8 bits for a machine id
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=306508&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1174&type=TASK)
/assign @Effet @littlejiancc 
| 🇺🇸 English |   implement 53-bit snowflake id for js compatible           |
| 🇨🇳 中文    |  实现 53-bit 雪花 ID 以兼容 JS Number 最大值问题            |

feat: implement 53-bit snowflake id for js compatible

---

apistructs/pipeline_status.go
modules/pipeline/providers/engine/interface.go
modules/pipeline/providers/queuemanager/manager/pop_out.go

support cancel when status is Queue in queueManager
/assign @chengjoey @Effet 
| 🇺🇸 English |   support cancel when status is Queue in queueManager           |
| 🇨🇳 中文    |  支持取消队列管理器中状态为 Queue 的流水线            |

fix(pipeline): support cancel when status is Queue in queueManager

---

modules/pipeline/providers/queuemanager/load.go
modules/pipeline/providers/reconciler/pipeline_reconciler.go
modules/pipeline/providers/reconciler/snippet.go

fix the issue of canceling and UpdateCurrentReconcileStatusIfNecessary
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=306774&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjkyIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1218&tab=BUG&type=BUG)
| 🇺🇸 English | fix the issue of canceling and UpdateCurrentReconcileStatusIfNecessary             |
| 🇨🇳 中文    |  修复了流水线取消以及推进时状态计算错误的问题            |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cher …

fix(pipeline): fix the issue of canceling and UpdateCurrentReconcileStatusIfNecessary

---

modules/pipeline/providers/leaderworker/interface.go
modules/pipeline/providers/leaderworker/leader_framework.go
modules/pipeline/providers/leaderworker/leader_listen_worker_task.go
modules/pipeline/providers/leaderworker/provider.go
modules/pipeline/providers/queuemanager/load.go

load canceling logic tasks after load need-handled success
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=306742&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=-1&tab=BUG&type=BUG)
| 🇺🇸 English | leaderworker load canceling logic tasks after load need-handled success             |
| 🇨🇳 中文    |  leaderworker 在完成加载需要处理的任务后再加载需要取消的任务            | …

fix(pipeline): load canceling logic tasks after load need-handled success

---

modules/hepa/apipolicy/policies/csrf/policy.go

fix: invalid memory address on getting plugin
| 🇺🇸 English | fix: invalid memory address on getting plugin |
| 🇨🇳 中文    | 修复了查询 Kong Plugin 时结果为空的情况下的空指针问题 |
> modules/hepa/kong/v2/kong_adapter.go:56
```go
func (impl *KongAdapterImpl) GetPlugin(req *KongPluginReqDto) (*KongPluginRespDto, error) {
/* ... */
if code == 200 {
respDto := &KongPluginsDto{}
err = json.Unmarshal(body, respDto)
if err != nil {
return nil, errors.Wrap(err, ERR_JSON_FAIL)
}
if len(respDto.Data) > 0 {
respDto.Data[0].Compatiable()
return &respDto.Data[0], nil
}
**		return nil, nil
}
/* ... */
}
```
> …

fix: invalid memory address on getting plugin

---

pkg/apitestsv2/apitest.go
pkg/encoding/jsonparse/parse.go
pkg/encoding/jsonparse/parse_test.go

1. Fix that the automated test could not customize the content type header
2. Fix that the automated test cannot get a result that is not JSON
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTc4LDExOTAsMTIxOCwxMTc0XSwiYXNzaWduZWUiOlsiMTAwMDU2MCJdfQ%3D%3D&id=306533&iterationID=1174&pId=0&type=BUG)
| 🇺🇸 English |       fix autotest can not set Content-Type header，and can not get result that not a json        |
| 🇨🇳 中文    |      修复自动测试无法设置 Content-Type header，和无法得到非 json 的结果        |

fix(dop,pipeline): fix autotest can not set Content-Type header and can not get result that not a json

---

modules/pipeline/pipengine/actionexecutor/plugins/k8sspark/k8sspark.go

k8sspark transfer affinity to node selector
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=307044&iterationID=1174&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English | Fix the bug that k8sspark transfer affinity to node selector             |
| 🇨🇳 中文    |   将spark任务的亲和性转换为节点选择器           |

fix(pipeline): k8sspark transfer affinity to node selector

---

apistructs/container.go
modules/orchestrator/endpoints/instance.go
modules/orchestrator/endpoints/instance_test.go
modules/orchestrator/scheduler/executor/plugins/k8s/instanceinfosync/pod.go

runtime instance return pod meta info
/assign # @sixther-dc 
| 🇺🇸 English |  runtime instance return pod meta info            |
| 🇨🇳 中文    |     runtime 实例返回 pod 元信息         |

feat: runtime instance return pod meta info

---

modules/pipeline/pipengine/actionexecutor/plugins/k8sflink/util.go

flink pod remove invalid msp envs
msp label(org_id,org_name) is invalid in envs
/assign @sfwn 
| 🇺🇸 English |  Fix the bug that flink pod remove invalid msp envs            |
| 🇨🇳 中文    |   将无效的环境变量从flink任务删除           |

fix(pipeline): flink pod remove invalid msp envs

---

modules/cmp/component-protocol/cputil/util.go
modules/orchestrator/scheduler/executor/plugins/k8s/k8s.go
modules/pipeline/pipengine/actionexecutor/plugins/k8sflink/type.go
modules/pipeline/pipengine/actionexecutor/plugins/k8sjob/k8sjob.go
modules/pipeline/pipengine/actionexecutor/plugins/k8sspark/type.go
pkg/k8sclient/client.go
providers/k8s-client-manager/provider.go

k8sclient new-func support some custom options
in [this pr](https://github.com/erda-project/erda/pull/4633), i make new k8sclient directly by erda-operator injected conf  if in-cluster, but in-cluster is insufficient permissons for cmp, so i add `priorityUseInCluster` option for pipeline
/assign @sfwn  @iutx 
| 🇺🇸 English | Fix the bug that k8sclient new-func support some custom options             |
| 🇨🇳 中文    |  修复了多云管理平台k8sclient的权限不足            | …

fix: k8sclient new-func support some custom options

---

modules/pipeline/providers/reconciler/pipeline_reconciler.go
modules/pipeline/providers/reconciler/pipeline_reconciler_impl.go
modules/pipeline/providers/reconciler/pipeline_reconciler_impl_test.go
modules/pipeline/providers/reconciler/pipeline_reconciler_test.go
modules/pipeline/providers/reconciler/reconcile.go
modules/pipeline/providers/reconciler/task_reconciler.go
modules/pipeline/providers/reconciler/util.go

refacotor pipeline reconcile loop, add processedTasks syncmap to determine normally done.
| 🇺🇸 English |  add processedTasks syncmap to determine normally done            |
| 🇨🇳 中文    |  增加 已处理的任务 字段来标识正常的推进结束            |

refactor(pipeline): add processedTasks syncmap to determine normally done

---

conf/admin/admin.yaml
conf/openapi/openapi.yaml
erda.yml
modules/admin/provider.go
modules/openapi/api/apis/admin/admin_dingtalk.go
pkg/parser/diceyml/diceyml_test.go

merge port of http-server in admin self and erda-infra
| 🇺🇸 English |       feat: merge port of http-server in admin self and erda-infra       |
| 🇨🇳 中文    |        合并erda-infra跟admin组件自己的端口      |

feat: merge port of http-server in admin self and erda-infra

---

modules/orchestrator/endpoints/deployment_order.go
modules/orchestrator/services/deployment_order/deployment_order_cancel.go
modules/orchestrator/services/deployment_order/deployment_order_cancel_test.go
modules/orchestrator/services/deployment_order/deployment_order_create.go

fix: deployment order deploy duplicate, app release can't cancled
| 🇺🇸 English |  deployment order deploy duplicate, app release can't cancel            |
| 🇨🇳 中文    |   修复部署单错误情况下的重复部署，应用制品在错误下无法取消的情况           |

fix: deployment order deploy duplicate, app release can't cancel

---

modules/pipeline/providers/reconciler/pipeline_reconciler.go
modules/pipeline/providers/reconciler/pipeline_reconciler_test.go

fix the issue that totalTaskNum is unset if pipeline is already in running status
| 🇺🇸 English |  fix the issue that totalTaskNum is unset if pipeline is already in running status            |
| 🇨🇳 中文    |   修复了当流水线状态为运行中时，totalTaskNum 未设置的问题           |

fix(pipeline): must set totalTaskNum

---

apistructs/cluster_info.go
modules/orchestrator/scheduler/executor/plugins/k8s/clusterinfo/clusterinfo.go
modules/pipeline/providers/clusterinfo/interface.go
modules/pipeline/providers/clusterinfo/interface_test.go
modules/pipeline/providers/clusterinfo/provider.go

clusterinfo provider support get current cluster from configmap, because could't get clusterinfo from cluster-manager when edge deploying
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=306739&iterationID=1190&pId=306714&type=TASK)
/assign @sfwn 
| 🇺🇸 English | clusterinfo provider support get current cluster from configmap             |
| 🇨🇳 中文    |   支持边缘部署的pipeline解耦cluster-manage           |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a …

feat(pipeline): clusterinfo provider support get current cluster from configmap

---

modules/pipeline/providers/reconciler/taskrun/framework.go
modules/pipeline/providers/reconciler/taskrun/framework_test.go

fix loop tasks created many times due to network-error
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=308870&iterationID=1178&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English | fix loop tasks created many times due to network-error             |
| 🇨🇳 中文    |    修复了由于网络错误导致的循环任务重复创建          |

fix(pipeline): loop tasks created many times due to network-error

---

modules/hepa/kong/dto/kong_route_req_dto.go

fix: kong route no field 'tags' in v0.14
| 🇺🇸 English | kong route no field 'tags' in v0.14 |
| 🇨🇳 中文    | 修复创建 Kong Route 时打 tag 不兼容 Kong v0.14 |
https://docs.konghq.com/gateway-oss/0.14.x/admin-api/#add-route
https://docs.konghq.com/gateway-oss/2.2.x/admin-api/#add-route

fix: kong route no field 'tags' in v0.14

---

modules/pipeline/pipengine/reconciler/taskrun/feamework_test.go
modules/pipeline/pipengine/reconciler/taskrun/framework.go

hotfix loop tasks created many times due to network-error
[related pr](https://github.com/erda-project/erda/pull/4725)
/assign @sfwn 
| 🇺🇸 English |  Fix loop tasks created many times due to network-error            |
| 🇨🇳 中文    |     修复了配置循环的任务在遇到网络问题时创建了多个实例         |

hotfix: loop tasks created many times due to network-error

---

pkg/apitestsv2/apitest.go

Move the api-test code location to fix null pointer exception
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTkwLDExNzQsMTIxOF0sImFzc2lnbmVlIjpbIjEwMDA1NjAiXX0%3D&id=306533&iterationID=1174&pId=0&type=BUG)
| 🇺🇸 English |      Move the api-test code location to fix null pointer exception        |
| 🇨🇳 中文    |       移动api-test代码位置，修复空指针异常       |

fix(pipeline): Move the api-test code location to fix null pointer exception

---

bundle/cluster_dialer.go
modules/pipeline/providers/edgepipeline_register/interface.go
modules/pipeline/providers/edgepipeline_register/interface_test.go

edge register bundle `IsClusterDialerClientRegistered` force use client type
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that edge register bundle `IsClusterDialerClientRegistered` force use client type           |
| 🇨🇳 中文    |     强制dialer的一些bundle使用类型参数         |

fix: edge register bundle `IsClusterDialerClientRegistered` force use client type

---

.erda/migrations/pipeline/20220427-pipeline-edge-cron.sql
apistructs/pipeline.go
apistructs/pipeline_cron.go
bundle/pipeline_cron.go
modules/pipeline/providers/cron/compensator/provider.go
modules/pipeline/providers/cron/cron.service.go
modules/pipeline/providers/cron/cron.service_test.go
modules/pipeline/providers/cron/daemon/cron_task.go
modules/pipeline/providers/cron/daemon/provider.go
modules/pipeline/providers/cron/db/define.go
modules/pipeline/providers/cron/db/define_test.go
modules/pipeline/providers/cron/provider.go
modules/pipeline/spec/pipeline_cron.go

The pipeline edge cron, synchronizes the cron data between the pipeline at the center and the pipeline at the edge
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTc4LDExNzQsMTE5MF0sImFzc2lnbmVlIjpbIjEwMDA1NjAiXX0%3D&id=300218&iterationID=1174&pId=301655&type=TASK)
| 🇺🇸 English |        Synchronize cron information between center pipeline and edge pipeline      |
| 🇨🇳 中文    |        中心 pipeline 和边缘 pipeline 同步 cron 信息      |

feat(pipeline): pipeline edge cron

---

modules/pipeline/providers/reconciler/task_reconciler.go

remove invalidate oauth2Token after pipeline task tear down，
this causes the deployment to not be canceled
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTkwLDEyMThdLCJhc3NpZ25lZSI6WyIxMDAxMjYxIl19&id=309956&iterationID=1190&pId=0&type=BUG)
/assign #sfwn
| 🇺🇸 English |       remove invalidate oauth2Token after pipeline task tear down       |
| 🇨🇳 中文    |      pipeline取消的时候，取消删除oauth2Token       | …

fix(pipeline): remove invalidate oauth2Token after pipeline task tear down

---

modules/pipeline/providers/actionmgr/common.go
modules/pipeline/providers/actionmgr/common_test.go
modules/pipeline/providers/actionmgr/db/client.go
modules/pipeline/providers/actionmgr/impl.go
modules/pipeline/providers/actionmgr/impl_test.go

The edge pipeline does not query the extension on dicehub
| 🇺🇸 English |       The edge pipeline does not query the extension on dicehub       |
| 🇨🇳 中文    |      边缘流水线不查询 dicehub 上的 extension        |

fix(pipeline): The edge pipeline does not query the extension on dicehub

---

conf/pipeline/pipeline.yaml
modules/pipeline/providers/clusterinfo/provider.go

pipeline reduce refresh clusterinfo interval
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=310755&iterationID=1190&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |  Fix the bug that  pipeline reduce refresh clusterinfo interval            |
| 🇨🇳 中文    |    pipeline加快集群信息缓存的刷新速度          |

fix: pipeline reduce refresh clusterinfo interval

---

modules/actionagent/callback.go
modules/actionagent/callback_reporter.go
modules/actionagent/callback_test.go
modules/actionagent/define.go

action agent support set file stream timeout by env
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/ticket?id=310784)
/assign @sfwn 
| 🇺🇸 English | Fix the bug that action agent support set file stream timeout by env             |
| 🇨🇳 中文    |   action agent支持配置文件流的超时时间           |

fix: action agent support set file stream timeout by env

---

modules/pipeline/providers/actionmgr/db/client.go
modules/pipeline/providers/actionmgr/db/client_test.go

Fix the problem that unmarshal has no value when pipeline tasks do not need to be internationalized
| 🇺🇸 English |      Fix the problem that unmarshal has no value when pipeline tasks do not need to be internationalized        |
| 🇨🇳 中文    |      修复流水线任务不需要国际化时候 Unmarshal 没有值的问题        |

fix(pipeline): Fix the problem that unmarshal has no value when pipeline tasks do not need to be internationalized

---

modules/pipeline/providers/reconciler/pipeline_reconciler_impl.go
modules/pipeline/providers/reconciler/pipeline_reconciler_impl_test.go
modules/pipeline/providers/reconciler/reconcile.go

pipeline status is always running when all tasks are disabled
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=311116&iterationID=1190&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |    Fix the bug that pipeline status is always running when all tasks are disabled          |
| 🇨🇳 中文    | 修复了流水线的状态一直running中当所有任务都被禁用             | …

fix(pipeline): pipeline status is always running when all tasks are disabled

---

modules/pipeline/providers/reconciler/snippet.go
modules/pipeline/providers/reconciler/snippet_test.go
modules/pipeline/providers/reconciler/task_reconciler.go

fulfill parent snippet task status stored in processed tasks
/assign @sfwn 
| 🇺🇸 English | Fix the bug that fulfill parent snippet task status stored in processed tasks             |
| 🇨🇳 中文    |  修复了内存中嵌套流水线任务的状态错误            |

fix(pipeline): fulfill parent snippet task status stored in processed tasks

---

modules/dop/services/autotest_v2/space_data.go
modules/dop/services/autotest_v2/space_data_test.go

set api-spec-id  zero when export scene step
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=309640&iterationID=1174&pId=0&type=BUG)
| 🇺🇸 English |  Fix the bug that autotest show step  api market error             |
| 🇨🇳 中文    |  修复了查看步骤详情错误            |

fix(dop): set api-spec-id  zero when export scene step

---

modules/dop/dbclient/dao.go
modules/dop/providers/qa/unittest/unittest-service.go

return parent code coverage data when list qa unittest
| 🇺🇸 English |   return parent code coverage data when list qa unittest           |
| 🇨🇳 中文    |  查询测试覆盖率列表时返回父节点的值            |

feat(dop): return parent code coverage data when list qa unittest

---

modules/msp/apm/log-service/rules/log_metric_config.go
modules/msp/apm/log-service/rules/log_metric_config_test.go

| 🇺🇸 English |      log_metrics support use tag keys without dice prefix        |
| 🇨🇳 中文    |       分析规则指标支持使用不带dice前缀的标签key       |

fix: log_metrics support use tag keys without dice prefix

---

modules/dop/component-protocol/components/release-manage/releaseTable/render.go
modules/monitor/dashboard/org-apis/permission.go
modules/monitor/dashboard/org-apis/provider.go

fix: autowired clusterSvc in monitor
| 🇺🇸 English | fix: autowired clusterSvc in monitor |
| 🇨🇳 中文    | 修复monitor组件中注入clusterSvc失败导致panic的问题 |

fix: autowired clusterSvc in monitor

---

modules/pipeline/endpoints/v2_test.go
modules/pipeline/providers/reconciler/taskrun/taskop/prepare_test.go

add unit test for taskop-prepare
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=305706&iterationID=1190&pId=0&type=TASK)
/assign @sfwn 
| 🇺🇸 English |  add unit test for taskop-prepare            |
| 🇨🇳 中文    |     增加prepare的单元测试         |

feat: add unit test for taskop-prepare

---

modules/pipeline/endpoints/v2_test.go
modules/pipeline/providers/cron/cron.service.go
modules/pipeline/providers/cron/cron.service_test.go
modules/pipeline/providers/cron/db/define_extra.go

query cron is-existed by transaction session to avoid competing links
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=311911&iterationID=1224&pId=0&type=TASK)
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that query cron is-existed by transaction session to avoid competing links            |
| 🇨🇳 中文    |     修复并发数大于mysql链接数的情况下事物卡住         | …

fix(pipeline): query cron is-existed by transaction session to avoid competing links

---

modules/hepa/apipolicy/policies/csrf/policy.go

select route by option not by struct.
| 🇺🇸 English | Fixed the problem that the incoming condition may be empty when querying route, resulting in unexpected results |
| 🇨🇳 中文    | 修复了查询 route 时传入条件可能为空导致查询出意外的结果的问题 |

fix: select route by option

---

modules/orchestrator/scheduler/executor/plugins/k8s/k8s.go
modules/orchestrator/scheduler/executor/plugins/k8s/k8s_test.go

dlock failed cause orchestrator panic
| 🇺🇸 English | fix dlock failed cause orchestrator panic             |
| 🇨🇳 中文    |    修复分布式锁获取失败导致 orchestrator panic         |

fix: dlock failed cause orchestrator panic

---

.erda/migrations/cmdb/20220517-notify-histories-add-index.sql

dice_notify_histories add column index
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=311070&iterationID=1224&pId=0&type=TASK)
/assign @sfwn 
| 🇺🇸 English |  dice_notify_histories add column index            |
| 🇨🇳 中文    |     通知历史表添加索引         |

feat: dice_notify_histories add column index

---

modules/orchestrator/scheduler/executor/plugins/k8s/job.go
modules/orchestrator/scheduler/executor/plugins/k8s/job_test.go

fix: panic when history job list less than 2
| 🇺🇸 English |     fix: panic when history job list less than 2         |
| 🇨🇳 中文    |       修复历史job小于2的panic问题       |

fix: panic when history job list less than 2

---

modules/cluster/cluster-manager/dialer/server/tunnel-server.go
modules/dop/component-protocol/components/release-manage/releaseTable/render.go

fix: return error if cluster-manager ip not found for clusterkey
| 🇺🇸 English | fix: return error if cluster-manager ip not found for clusterkey |
| 🇨🇳 中文    | 若找不到目标clusterKey对应的cluster-manager ip地址则返回错误 |

fix: return error if cluster-manager ip not found for clusterkey

---

conf/cluster-agent/cluster-agent.yaml
modules/openapi/api/apis/cluster_manager/connect.go

fix: add cluster-manager connect path to openapi
| 🇺🇸 English | fix: add cluster-manager connect path to openapi |
| 🇨🇳 中文    | 把cluster-manager接收cluster-agent注册的路由暴露到openapi |

fix: add cluster-manager connect path to openapi

---

pkg/mock/mock_test.go
pkg/mock/time.go

add comma for time type format
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=313329&iterationID=-1&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that add comma for time type format            |
| 🇨🇳 中文    |   修复了自动化测试执行时时间类型格式错误           |

fix: add quotation marks for time type format

---

pkg/database/sqlparser/migrator/scripts.go
pkg/database/sqlparser/testdata/alter_permission_test_data3/service_a/318-1.sql

feat: to consider that alter table name in alter permission lint
| 🇺🇸 English | to consider that alter table name in alter permission lint |
| 🇨🇳 中文    | 在检查 SQL 文件修改权限时考虑表名被修改了的情况 |

feat: to consider that alter table name in alter permission lint

---

.erda/migrations/qa/20220520-file-record-name-length.sql

fix export autotest failure due to `file_name` length
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=302217&iterationID=-1&pId=0&type=BUG)
| 🇺🇸 English |   Fix export autotest failure due to `file_name` length           |
| 🇨🇳 中文    | 修复由于记录表名称限制导致的自动化测试导出失败             |

fix(dop): export autotest failure due to `file_name` length

---

pkg/mock/mock_test.go
pkg/mock/time.go

This reverts commit a8079a2acb790c15d67307b02a5e69d676f40212.
add quotation marks for time type format (#4895)
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=313329&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDA0MzIiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=-1&tab=BUG&type=BUG)
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that revert quotation marks for time type format            |
| 🇨🇳 中文    |     回退给时间类型的mock添加引号         | …

revert: add quotation marks for time type format (#4895)

---

api/proto/core/dicehub/release/release.proto
modules/dicehub/release/release.go
modules/dicehub/release/release.service.go
modules/dicehub/release/release_test.go
modules/dop/component-protocol/components/release-manage/releaseTable/render.go

1. reutrn null if opus is null
2. add project displayName in list release
| 🇺🇸 English | reutrn null if opus is null; add project displayName in list release  |
| 🇨🇳 中文    | 修复获取来源为gallery的制品时返回所有制品的问题；获取制品接口返回值添加projectDisplayName字段  |

fix: reutrn null if opus is null

---

.github/workflows/ci-it-noneed.yml

We use pr number from workflow context before, so it fails when squash merged (it's a push event, no pr id).
| 🇺🇸 English |   use changed-files action to handle push event           |
| 🇨🇳 中文    |     使用 changed-files Action 来处理 Push 事件         |

fix: use changed-files action to handle push event

---

api/proto/core/pipeline/build/build.proto

add build-routers to common openapi
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that add build-routers to common openapi           |
| 🇨🇳 中文    |  修复了构建产物相关路由添加到openapi            |

fix: add build-routers to common openapi

---

modules/tools/pipeline/actionagent/execute.go
modules/tools/pipeline/actionagent/file_watch.go
modules/tools/pipeline/actionagent/file_watch_collector.go
modules/tools/pipeline/actionagent/filewatch/watch.go

end listening log lines use context done instead of end tail flag
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=314618&iterationID=-1&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |   end listening log lines use context done instead of end tail flag           |
| 🇨🇳 中文    |     修复agent监听日志长时间卡住         |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/ …

fix(pipeline): end listening log lines use context done instead of end tail flag

---

.erda/pipelines/ci-build-ce.yml
.erda/pipelines/ci-deploy.yml
.github/workflows/ci-it.yml
api/proto-go/Makefile
pipeline.yml

specify gohub image tag to 1.0.5
| 🇺🇸 English |   specify gohub image tag to 1.0.5           |
| 🇨🇳 中文    |    指定 gohub 镜像 tag 为 1.0.5          |

chore: specify gohub image tag to 1.0.5

---

internal/tools/pipeline/providers/reconciler/taskrun/framework.go

task op always begin queue due to `fetchLatestTask`
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/ticket?id=317259&issueFilter__urlQuery=e30%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=-1&type=TICKET)
/assign @sfwn 
| 🇺🇸 English | Fix the bug that task op always begin queue due to `fetchLatestTask` when user click cancel             |
| 🇨🇳 中文    |   修复用户点击取消后后状态一直变成取消           | …

fix(pipeline): task op always begin queue due to `fetchLatestTask` when user click cancel

---

api/proto/core/pipeline/action_runner_scheduler/runner_task.proto

change action-runner-scheduler auth check
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=317801&iterationID=1250&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |   change action-runner-scheduler auth check           |
| 🇨🇳 中文    |    修复了action-runner-scheduler接口的权限校验          |

fix: change action-runner-scheduler auth check

---

internal/tools/pipeline/providers/reconciler/task_reconciler.go
internal/tools/pipeline/providers/reconciler/task_reconciler_test.go

overwrite current task with latest when status is ending
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=317954&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |  overwrite current task with latest when status is ending            |
| 🇨🇳 中文    |       修复了自动化测试 setcookie 没有继承下去       |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUT …

fix(pipeline): overwrite current task with latest when status is ending

---

apistructs/pipeline_page.go
apistructs/pipeline_page_test.go
internal/apps/dop/providers/projectpipeline/service_impl.go
internal/tools/pipeline/providers/run/run.go
internal/tools/pipeline/providers/run/run_test.go
internal/tools/pipeline/services/pipelinesvc/create_v2.go

Solve the problem that the pipeline records of timed execution cannot be queried according to the executor
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMjgwLDEyNTBdLCJhc3NpZ25lZSI6WyIxMDAxMjYxIl19&id=317719&iterationID=1280&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |      Solve the problem that the pipeline records of timed execution cannot be queried according to the executor        |
| 🇨🇳 中文    |      解决定时执行的流水线记录根据执行者查询不到问题        |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTIN …

fix(pipeline): Solve the problem that the pipeline records of timed execution cannot be queried according to the executor

---

apistructs/event_request.go
apistructs/event_request_test.go
internal/core/messenger/eventbox/dispatcher/dispatcher.go
internal/tools/pipeline/events/event.go
internal/tools/pipeline/events/event_pipeline.go
internal/tools/pipeline/events/event_task.go
internal/tools/pipeline/events/event_task_runtime.go
internal/tools/pipeline/providers/edgepipeline_register/interface.go
internal/tools/pipeline/providers/edgepipeline_register/mock.go
internal/tools/pipeline/providers/edgepipeline_register/provider.go
internal/tools/pipeline/providers/edgepipeline_register/webhook.go
internal/tools/pipeline/providers/edgepipeline_register/webhook_test.go

edge-side pipeline support register webhook client and dispatch events
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=313658&iterationID=1218&pId=0&type=TASK)
/assign @sfwn 
| 🇺🇸 English |  edge-side pipeline support register webhook client and dispatch events             |
| 🇨🇳 中文    |   边缘pipeline支持注册webhook并发送事件           | …

feat(pipeline): edge-side pipeline support register webhook and dispatch events

---

api/proto/core/pipeline/cron/cron.proto
apistructs/cluster_dialer.go
apistructs/event.go
bundle/cluster_manager.go
internal/core/cluster-manager/dialer/provider.go
internal/core/cluster-manager/dialer/server/client_data.go
internal/core/cluster-manager/dialer/server/client_data_test.go
internal/core/cluster-manager/dialer/server/dialer_test.go
internal/core/cluster-manager/dialer/server/tunnel-server.go
internal/core/cluster-manager/dialer/server/tunnel-server_test.go
internal/tools/pipeline/providers/cron/cron.service.go
internal/tools/pipeline/providers/cron/db/define_extra.go
internal/tools/pipeline/providers/edgepipeline_register/cluster_access_key.go
internal/tools/pipeline/providers/edgepipeline_register/edge_client.go
internal/tools/pipeline/providers/edgepipeline_register/edge_client_test.go
internal/tools/pipeline/providers/edgepipeline_register/interface.go
internal/tools/pipeline/providers/edgepipeline_register/mock.go
internal/tools/pipeline/providers/edgepipeline_register/provider.go
pkg/k8sclient/client.go

support dispatch cron to edge when edge side pipeline registered
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=313905&iterationID=-1&pId=0&type=TASK)
/assign @sfwn 
| 🇺🇸 English |   support dispatch cron to edge when edge side pipeline registered           |
| 🇨🇳 中文    |    dge pipeline 注册上来之后，center pipeline 主动下发相关 cron          | …

feat(pipeline): support dispatch cron to edge when edge side pipeline registered

---

internal/tools/monitor/core/log/storage/kubernetes-logs/provider.go
internal/tools/monitor/core/log/storage/kubernetes-logs/storage.go

Unreliable kubernetes log
The bottom line is through the timestamp, if it is empty, it will be skipped
| 🇺🇸 English |    Unreliable kubernetes log, Skip empty interval           |
| 🇨🇳 中文    |    不可信的 kubernetes log, 跳过空区间          |

fix(monitor): Unreliable kubernetes log, Skip empty interval

---

internal/apps/dop/providers/projectpipeline/service_impl.go
internal/apps/dop/providers/projectpipeline/service_impl_test.go

Special Handling 1970 Time
/assign @sfwn 
| 🇺🇸 English |    Special Handling 1970 Time          |
| 🇨🇳 中文    |     特殊处理1970时间         |

fix(dop): Special Handling 1970 Time

---

apistructs/pipeline_actions.go
apistructs/pipeline_report_basic.go
apistructs/pipeline_task.go
apistructs/pipeline_task_test.go
internal/apps/cmp/impl/clusters/add_edge_cluster.go
internal/tools/pipeline/actionagent/define.go
internal/tools/pipeline/actionagent/step_validate.go
internal/tools/pipeline/dbclient/op_pipeline_task.go
internal/tools/pipeline/events/event_task.go
internal/tools/pipeline/pkg/taskerror/err.go
internal/tools/pipeline/pkg/taskerror/err_test.go
internal/tools/pipeline/pkg/taskerror/ordered.go
internal/tools/pipeline/pkg/taskerror/ordered_test.go
internal/tools/pipeline/pkg/taskinspect/inspect.go
internal/tools/pipeline/pkg/taskinspect/inspect_test.go
internal/tools/pipeline/pkg/taskinspect/machine.go
internal/tools/pipeline/pkg/taskresult/result.go
internal/tools/pipeline/providers/reconciler/snippet.go
internal/tools/pipeline/providers/reconciler/snippet_test.go
internal/tools/pipeline/providers/reconciler/task_reconciler.go
internal/tools/pipeline/providers/reconciler/task_reconciler_test.go
internal/tools/pipeline/providers/reconciler/taskrun/framework.go
internal/tools/pipeline/providers/reconciler/taskrun/framework_test.go
internal/tools/pipeline/providers/reconciler/taskrun/taskop/prepare.go
internal/tools/pipeline/providers/reconciler/taskrun/update.go
internal/tools/pipeline/services/pipelinesvc/callback.go
internal/tools/pipeline/services/pipelinesvc/callback_test.go
internal/tools/pipeline/services/pipelinesvc/detail.go
internal/tools/pipeline/spec/pipeline_task.go
internal/tools/pipeline/spec/pipeline_task_test.go

split task result/inspect/error from apistructs
| 🇺🇸 English |   split task result/inspect/error from apistructs           |
| 🇨🇳 中文    |   将 task result/inspect/error 从 apistructs 中分离           |

refactor: split task result/inspect/error from apistructs

---

pkg/goroutinepool/goroutinepool.go

groutinepool pkg `WaitGroup is reused before previous Wait has returned` panic
/assign @sfwn 
| 🇺🇸 English |  Fix the bug that groutinepool pkg `WaitGroup is reused before previous Wait has returned` panic            |
| 🇨🇳 中文    |  修复了goroutinepool公共包panic的问题          |

fix: groutinepool pkg `WaitGroup is reused before previous Wait has returned`

---

modules/pipeline/providers/reconciler/task_reconciler.go
modules/pipeline/providers/reconciler/task_reconciler_test.go

hotfix overwrite current task with latest when status is ending
related pr: (https://github.com/erda-project/erda/pull/5044/files)
/assign @sfwn 
`xxx` is one of DevOps/Micro Service/Cloud Management
-->
| 🇺🇸 English |  overwrite current task with latest when status is ending            |
| 🇨🇳 中文    |     修复了自动化测试 setcookie 没有继承下去         |

fix: overwrite current task with latest when status is ending

---

internal/apps/cmp/component-protocol/components/cmp-cluster-list/common/model.go
internal/apps/cmp/component-protocol/components/cmp-cluster-list/list/render.go
internal/apps/cmp/impl/clusters/clusterinfo.go
internal/apps/cmp/impl/clusters/credential.go
internal/apps/cmp/impl/clusters/credential_test.go
internal/tools/orchestrator/hepa/k8s/k8s_adapter.go
internal/tools/pipeline/conf/conf.go
internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sjob/k8sjob.go
internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sjob/k8sjob_test.go
pkg/k8s-client-manager/provider.go
pkg/k8s/interface_factory/discover.go
pkg/k8s/interface_factory/ingress.go
pkg/k8sclient/client.go

1. switch buildkitd certs namespace from default to erda namespace
2. fix clientset from *kubernetes.Clientset to kubernetes.Interface, now can use "k8s.io/client-go/kubernetes/fake" to programing unit test about client-go.
/assign @sixther-dc @sfwn @chengjoey 
| 🇺🇸 English | switch buildkitd certs namespace from default to erda namespace             |
| 🇨🇳 中文    |     切换 buildkitd 证书命名空间，从 default 到 erda 所在 namespace         | …

fix(pipeline): switch buildkitd certs namespace from default to erda namespace

---

codecov.yml

codecov ignore legacy openapi specs
| 🇺🇸 English |   codecov ignore legacy openapi specs           |
| 🇨🇳 中文    |   codecov 忽略老的 openapi 定义           |

chore: codecov ignore legacy openapi specs

---

conf/erda-configs/i18n/notify_item.yml

Modify the notification link triggered by the pipeline execution
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMjgwLDEyOTddLCJhc3NpZ25lZSI6WyIxMDAxMjYxIl19&id=318731&iterationID=1280&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |      update notify link of pipeline        |
| 🇨🇳 中文    |      修改流水线执行触发的通知链接        |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUT …

fix(pipeline): Modify the notification link triggered by the pipeline execution

---

api/proto/common/openapi.proto

openapi proto add doc field for old spec migration
| 🇺🇸 English |  openapi proto add doc field for old spec migration            |
| 🇨🇳 中文    |   openapi proto option 增加 doc 字段，支持迁移老的 openapi 定义 doc 字段           |

feat(protobuf): openapi proto  add doc field for old spec migration

---

internal/tools/monitor/core/log/query/log.query.service.go
internal/tools/monitor/core/log/storage/kubernetes-logs/storage.go
internal/tools/monitor/core/log/storage/kubernetes-logs/storage_test.go

- downgrade log for empty, isfallback return false
- let go of query restrictions
- stream is stdout or stderr, not downgrade
| 🇺🇸 English |       downgrade log optimization       |
| 🇨🇳 中文    |            日志降级优化  |

feat: Optimization Downgrade log

---

internal/apps/dop/providers/issue/core/file.go
internal/apps/dop/providers/issue/core/file_test.go

tips of finished time parse error
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=320064&iterationID=1280&pId=0&type=BUG)
| 🇺🇸 English |    Fix the bug that tips of finished time parse error          |
| 🇨🇳 中文    |     事项导入错误提示信息优化         |

fix: tips of finished time parse error

---

internal/tools/pipeline/actionagent/execute.go
internal/tools/pipeline/actionagent/file_watch.go
internal/tools/pipeline/actionagent/file_watch_collector.go
internal/tools/pipeline/actionagent/filewatch/watch.go

This reverts commit 831627f7ac64946f2f8a46dea39ee9e689c305f7.
revert end listening log lines use context done instead of end tailflag (#4984)
/assign @sfwn 
| 🇺🇸 English |  revert end listening log lines use context done instead of end tailflag (#4984)            |
| 🇨🇳 中文    |   回退解决actionagent日志卡住的提交           |

revert: end listening log lines use context done instead of end tailflag (#4984)

---

internal/tools/cluster-agent/pkg/client/credential.go
internal/tools/cluster-agent/pkg/client/credential_test.go
internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s.go
internal/tools/pipeline/providers/edgepipeline_register/cluster_access_key.go

retrywatcher resource version reference error
| 🇺🇸 English |    fix retrywatcher resource version reference error          |
| 🇨🇳 中文    |    修复 retrywatcher resourceVersion 引用错误的问题          |

fix(cluster-manager): retrywatcher resource version reference error

---

internal/apps/dop/providers/issue/core/query/update.go
internal/apps/dop/providers/issue/core/query/update_test.go

Set time location in issue update request for time comparison.
Convert to local time for comparing date without location in issue update and stream.
/assign @sfwn 
| 🇺🇸 English |  Set time location in issue update request for time comparison.            |
| 🇨🇳 中文    |    设置时区          |
release/2.2

fix: Set time location in issue update request for time comparison.

---

apistructs/pipeline_status.go
internal/tools/pipeline/providers/run/can_manual_run.go
internal/tools/pipeline/services/pipelinesvc/convert.go
internal/tools/pipeline/services/pipelinesvc/convert_test.go
internal/tools/pipeline/services/pipelinesvc/precheck.go

transfer pipeline status to analyzed failed when precheck fails
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=318195&iterationID=1297&pId=0&type=REQUIREMENT)
/assign @sfwn 
| 🇺🇸 English | transfer pipeline status to analyzed failed when precheck fails             |
| 🇨🇳 中文    |     将禁止执行的流水线置为初始化失败状态         |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/C …

feat: transfer pipeline status to analyzed failed when precheck fails

---

api/proto/core/hepa/endpoint_api/endpoint_api.proto
internal/tools/orchestrator/hepa/providers/endpoint_api/endpoint.api.service.go
internal/tools/orchestrator/hepa/providers/endpoint_api/provider.go
internal/tools/orchestrator/hepa/services/micro_api/impl/impl.go
pkg/common/errors/data.go

fix the problem that fail to init service hub: fail to Init provider openapi-protobuf-routes: fail to discover url (GET /api/gateway/openapi/invalid-endpoints) of service "erda.core.hepa.endpoint_api.EndpointApiService": resolve service endpoint failed, service:erda.core.hepa.endpoint_api.EndpointApiService: lookup erda.core.hepa.endpoint_api.EndpointApiService ..: no such host
| 🇺🇸 English | fix the problem that failed to init service hub in openapi module|
| 🇨🇳 中文    | 修复 Openapi 中寻找 hepa 某接口的地址失败的问题 | …

fix: openapi transport

---

internal/tools/pipeline/dbclient/op_pipeline_labels.go
internal/tools/pipeline/dbclient/op_pipeline_test.go

query any match labels only once instead of multiple queries
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=311070&iterationID=1224&pId=0&type=TASK)
/assign @sfwn 
| 🇺🇸 English | query any match labels only once instead of multiple queries             |
| 🇨🇳 中文    |     减少标签的查询次数         |

refactor(pipeline): query any match labels only once instead of multiple queries

---

internal/tools/openapi/legacy/auth/token.go
internal/tools/openapi/legacy/auth/token_test.go

solve path mismatch caused by case
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=322439&iterationID=1297&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |    solve path mismatch caused by case           |
| 🇨🇳 中文    |     修复了由大小写造成的路径不匹配         |

fix(openapi): solve path mismatch caused by case

---

internal/tools/pipeline/providers/reconciler/taskrun/framework.go
internal/tools/pipeline/providers/reconciler/taskrun/framework_test.go

solve status of task is reset to running due to cancel timeout
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=322849&iterationID=1321&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |   solve status of task is reset to running due to cancel timeout           |
| 🇨🇳 中文    |    修复了流水线取消成功后任务状态有的还在运行中          |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIB …

fix(pipeline): solve status of task is reset to running due to cancel timeout

---

pkg/http/httpserver/router.go
pkg/http/httpserver/singleton.go
pkg/http/httpserver/singleton_test.go

- http-endpoints support singleton mode
- add servicehub.Listener to register routes of http-endpoints to new http-server router
| 🇺🇸 English |  http-endpoints support singleton mode            |
| 🇨🇳 中文    |   http-endpoints 支持单例模式           |

feat(http-server): http-endpoints support singleton mode

---

internal/tools/orchestrator/components/horizontalpodscaler/hp.scaler.service.go

Fix hpa rules which use cron trigger not scale down to 0
Bugfix： Fix hpa rules which use cron trigger not scale down to 0（修复了支持 cron hpa 将副本数缩为 0）
| 🇺🇸 English |      Fix hpa rules which use cron trigger not scale down to 0       |
| 🇨🇳 中文    |      修复了支持 cron hpa 将副本数缩为 0      |

fix: hpa support min replicas to 0

---

bundle/pipeline.go
bundle/utils.go
internal/apps/dop/endpoints/endpoints.go
internal/apps/dop/endpoints/pipeline.go
internal/apps/dop/initialize.go
internal/apps/dop/providers/projectpipeline/provider.go
internal/apps/dop/providers/projectpipeline/service.go
internal/apps/dop/providers/projectpipeline/service_impl.go
internal/apps/dop/providers/projectpipeline/service_impl_test.go
pkg/common/apis/response.go
pkg/common/apis/response_test.go

project pipeline display existed running link when runs repeatedly
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=322630&iterationID=1297&pId=0&type=REQUIREMENT)
/assign @sfwn 
| 🇺🇸 English |  project pipeline display existed running link when runs repeatedly            |
| 🇨🇳 中文    |   项目级流水线展示正在运行的流水线链接           |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/ma …

feat: project pipeline display existed running link when runs repeatedly

---

.github/workflows/ci-it.yml
api/proto/core/hepa/endpoint_api/endpoint_api.proto
internal/tools/orchestrator/hepa/k8s/k8s_adapter.go
internal/tools/orchestrator/hepa/k8s/k8s_adapter_test.go
internal/tools/orchestrator/hepa/providers/endpoint_api/endpoint.api.service.go
internal/tools/orchestrator/hepa/providers/endpoint_api/provider.go
internal/tools/orchestrator/hepa/services/endpoint_api/impl/impl.go

find invalid kong route and service by redirect inner address
| 🇺🇸 English | find invalid kong route and service by redirect inner address |
| 🇨🇳 中文    | 查找转发的内部地址已无效的路由(package_api) 对应的 kong Route 和 Service |

feat: find invalid kong route and service by redirect inner address

---

bundle/approve.go
bundle/audit.go
bundle/notice.go
bundle/user.go
internal/apps/admin/provider.go
internal/apps/dop/dicehub/initialize.go
internal/core/legacy/endpoints/endpoints.go
internal/core/legacy/initialize.go
pkg/http/httpserver/router.go
pkg/http/httpserver/router_test.go

handle dup api for admin and core-services
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=324601&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1297&type=TASK)
| 🇺🇸 English |   handle dup api for admin and core-services           |
| 🇨🇳 中文    |    处理 erda-server 中路径相同的 API          |

refactor: handle dup api for admin and core-services

---

internal/tools/orchestrator/scheduler/executor/plugins/k8s/instanceinfosync/sync.go

for hpa events in edge cluster, center cluster orchestrator orgCache may not cached the Org info for that hpa,  so orgCache may get nil
Bugfix： Fix the bug that the orgCache may not cached the Org  info, need set default org Locale    （修复了处理 HPA 事件时获取Org 信息失败导致获取 Org 的 Locate 为空引发空指针的问题）
| 🇺🇸 English |    Fix the bug that the orgCache may not cached the Org  info, so need set default org Locale  |
| 🇨🇳 中文    |      修复了处理 HPA 事件时获取Org 信息失败导致获取 Org 的 Locate 为空引发空指针的问题        |
2.3-alpha

fix(orchestrator): process hpa event may get nil from orgCache

---

cmd/msp/bootstrap.yaml

should default to cassandra instead of elasticsearch
| 🇺🇸 English |       msp default to cassandra       |
| 🇨🇳 中文    |      msp默认以cassandra存储        |

fix: msp default to cassandra

---

internal/tools/orchestrator/cache/org/org.go
pkg/http/httpclient/request.go
pkg/http/httpclient/request_test.go
tools/cli/cmd/gw.go
tools/cli/cmd/gw_del.go
tools/cli/cmd/gw_del_test.go
tools/cli/cmd/gw_ls.go
tools/cli/cmd/gw_ls_test.go
tools/cli/command/generate/collect/collect.go

a erda-cli command for retrieving invalid Route and Service.
you can use `erda-cli gw ls` to list all invalid endpoints with the specified cluster.
```shell
erda-cli gw ls \
--host 'https://your-host' \
--cluster your-cluster
```
it will output a result file. you can use it as input file to delete the endpints from kong gateway.
```shell
erda-cli gw del \
--host 'https://your-host' \
--cluster your-cluster \
--input 'your-cluster.invalid-endpoints.json' \
--output 'result.07091916.terminus-captain.invalid-endpoints.txt' \
--kong-admin 'https://your-kong-admin-host' \
--yes
```
| 🇺🇸 English | A erda-cli command for list and delete invalid …

feat: erda-cli gw commands

---

internal/tools/pipeline/aop/plugins/task/autotest_cookie_keep_before/cookie.go
internal/tools/pipeline/aop/plugins/task/autotest_cookie_keep_before/cookie_test.go
internal/tools/pipeline/aop/plugins/task/autotest_cookie_keep_before/plugin.go

aop `autotest_cookie_keep_before` plugin merge all cookies from report
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=325656&iterationID=1321&pId=0&type=BUG)
| 🇺🇸 English |   aop `autotest_cookie_keep_before` plugin merge all cookies from report           |
| 🇨🇳 中文    |     修复了自动化测试缺失cookie的问题         | …

fix: aop `autotest_cookie_keep_before` plugin merge all cookies from report

---

internal/tools/pipeline/providers/cms/cms.service.go
internal/tools/pipeline/providers/cms/pipeline_cms.go
internal/tools/pipeline/providers/cms/pipeline_cms_test.go

cms batch query configs remain the same order as namespaces
/assign @sfwn 
| 🇺🇸 English |  Fix the bug that cms batch query configs remain the same order as namespaces            |
| 🇨🇳 中文    |   修复了cms批量查询结果保持namespaces的顺序           |

fix: cms batch query configs remain the same order as namespaces

---

internal/tools/orchestrator/components/horizontalpodscaler/manual_scale.go
internal/tools/orchestrator/endpoints/server_handler.go

If manual scale down to zero update addon attachement to status 'S', when redeploy runtime before delete runtime, will result addon referenced more than once, so display repeated addons on runtime detail web page.
Bugfix： manual scale not update addon attachment（修复了 手动缩容服务副本数到0，修改 addon attachment 表导致不删除runtime直接重新部署的情况下 addon 重复显示）
| 🇺🇸 English |     manual scale not update addon attachment         |
| 🇨🇳 中文    |        修复了 手动缩容服务副本数到0，修改 addon attachment 表导致不删除runtime直接重新部署的情况下 addon 重复显示      |

fix: manual scale not update addon attachment

---

internal/apps/dop/endpoints/pipeline.go
internal/apps/dop/endpoints/pipeline_test.go

filter empty string when query pipelines
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=327651&iterationID=1321&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English | Fix the bug that filter empty string when query pipelines             |
| 🇨🇳 中文    |   修复了查询cicd流水线为空           |

fix(dop): filter empty string when query pipelines

---

internal/core/openapi/legacy/util/org.go
internal/core/openapi/legacy/util/org_test.go

fix "index out of range" issue of orgNameRetriever when domain is empty
| 🇺🇸 English |   fix "index out of range" issue of orgNameRetriever when domain is empty           |
| 🇨🇳 中文    |   修复当 domain 为空时 orgNameRetriever 的数组越界问题           |

fix(openapi): fix "index out of range" issue of orgNameRetriever when domain is empty

---

internal/apps/dop/services/pipeline/pipeline.go

missing reource type when check owner permission
| 🇺🇸 English |   Fix the bug that missing reource type when check owner permission           |
| 🇨🇳 中文    |      修复了查询owner权限时少了resource        |

fix: missing reource type when check owner permission

---

erda.yml

Fix erda-server service addr env inject error.
> Envs level: public component generate(gittar, collector, erda-server) > global envs
If doesn't set default port, will inject `ERDA_SERVER_ADDR` use first port `9529` in dice-operator.
Port `9529` already expose in ingress when use erda on erda.
/assign # @sixther-dc 
| 🇺🇸 English |  erda-server service addr env inject error        |
| 🇨🇳 中文    |   erda-server 服务地址环境变量中注入错误          |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-p …

fix: erda-server service addr env inject error

---

cmd/cluster-agent/bootstrap.yaml
go.mod
go.sum
internal/tools/cluster-agent/config/config.go
internal/tools/cluster-agent/pkg/client/client.go
internal/tools/cluster-agent/pkg/client/client_test.go

cluster agent token expire in kubernetes >= 1.21
/assign  @sixther-dc 
| 🇺🇸 English |   cluster agent token expire in kubernetes >= 1.21           |
| 🇨🇳 中文    |    cluster-agent token 在 kubernetes 1.21 版本及以上过期问题修复          |

fix: cluster agent token expire in kubernetes >= 1.21

---

internal/core/legacy/services/filesvc/download.go
internal/core/legacy/services/filesvc/download_test.go

add apk content-type `application/vnd.android.package-archive` to whitelist
/assign @sfwn 
| 🇺🇸 English |   add apk content-type `application/vnd.android.package-archive` to whitelist           |
| 🇨🇳 中文    |   下载apk文件时返回正确的content-type           |

fix: add apk content-type `application/vnd.android.package-archive` to whitelist

---

internal/apps/dop/providers/cms/cicdcmsservice.go
internal/apps/dop/providers/cms/cicdcmsservice_test.go

Solve the problem that the encrypted value is empty when batch update
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=329181&iterationID=1337&pId=0&type=BUG)
| 🇺🇸 English |     Solve the problem that the encrypted value is empty when batch update         |
| 🇨🇳 中文    |      解决批量修改的时候加密value为空问题        |

fix(dop): Solve the problem that the encrypted value is empty when batch update

---

cmd/erda-server/bootstrap.yaml
internal/core/openapi/legacy/proxy/http/modifyresponse.go
internal/core/openapi/legacy/proxy/http/modifyresponse_test.go

- delete logic that res remove headers already exist in rw
- make openapi.http-server.log.max_body_size_bytes configurable through env
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=329611&iterationID=1337&tab=BUG&type=BUG)
| 🇺🇸 English |  fix: openapi lost Content-Type header after proxy             |
| 🇨🇳 中文    |  修复 openapi 在 proxy 后丢失 Content-Type 的问题           |

fix: openapi lost Content-Type header after proxy

---

internal/tools/cluster-agent/provider.go

cluster-agent doesn't exit when start failed
| 🇺🇸 English |  cluster-agent doesn't exit when start failed            |
| 🇨🇳 中文    |    修复 cluster-agent 启动失败未退出          |

fix: cluster-agent doesn't exit when start failed

---

internal/apps/dop/component-protocol/components/auto-test-plan-list/components/addButton/render.go
internal/apps/dop/component-protocol/scenarios/auto-test-plan-list.yml

set `isUpdate` false value when add test
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=327132&iterationID=1354&pId=0&type=BUG)
/assign @sfwn
| 🇺🇸 English |   set `isUpdate` false value when add test           |
| 🇨🇳 中文    |    修复了自动化测试计划创建失败          |

fix(dop): set `isUpdate` false value when add test

---

.erda/migrations/config.yml

feat: BooleanFieldLinter do not applied to uc module
| 🇺🇸 English | BooleanFieldLinter do not applied to UC module |
| 🇨🇳 中文    | feat: BooleanFieldLinter 不约束 UC 模块 |

feat: BooleanFieldLinter do not applied to uc module

---

.github/workflows/ci-it.yml
internal/tools/pipeline/actionagent/callback.go

golangci-lint skip cache, because cache is too big to upload (more than 5GB)
| 🇺🇸 English |  golangci-lint skip cache            |
| 🇨🇳 中文    |   golangci-lint 跳过缓存           |

chore: golangci-lint skip cache

---

internal/core/openapi/legacy/api/apis/files/download.go
internal/core/openapi/legacy/api/apis/files/download_v2.go
internal/core/openapi/legacy/api/apis/files/head.go
internal/core/openapi/legacy/api/apis/files/upload.go

recover lost files routes, for openapi proxy use.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=331857&iterationID=1337&tab=BUG&type=BUG)
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=331858&iterationID=1337&tab=BUG&type=BUG)
| 🇺🇸 English |   recover lost files routes for openapi proxy use           |
| 🇨🇳 中文    |   恢复删除的 files 路由，供 openapi 转发使用           |

fix(files): recover lost files routes for openapi proxy use

---

internal/tools/pipeline/actionagent/step_logic.go
internal/tools/pipeline/actionagent/step_logic_test.go

agent change dir to task workdir before run commands
/assign @sfwn 
| 🇺🇸 English |    Fix the bug that agent change dir to task workdir before run commands          |
| 🇨🇳 中文    |   agent执行commands前切换到workdir           |

fix: agent change dir to task workdir before run commands

---

internal/apps/dop/providers/rule/actions/api/api.go
internal/apps/dop/providers/rule/executor/execute.go
internal/apps/dop/providers/rule/executor/execute_test.go

Add api action is https, add output for empty nodes.
/assign @sfwn 
| 🇺🇸 English |  Add api action is https, add output for empty nodes.             |
| 🇨🇳 中文    |    增加api action ishttps          |

fix: Add api action is https, add output for empty nodes.

---

internal/tools/pipeline/actionagent/step_prepare.go
internal/tools/pipeline/actionagent/step_prepare_test.go

agent shell commands failed to load variables
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=331980&iterationID=1337&tab=BUG&type=BUG)
/assign @sfwn 
| 🇺🇸 English | Fix the bug that agent shell commands failed to load variables             |
| 🇨🇳 中文    |    修复了自定义shell命令读取变量失败          |

fix: agent shell commands failed to load variables

---

erda.yml
go.mod
go.sum

add `TRACE_HOOK_ENABLE` env
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=331979&iterationID=1337&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |  add `TRACE_HOOK_ENABLE` env for trace hook            |
| 🇨🇳 中文    |    修复了agent打印infra日志          |

chore: add `TRACE_HOOK_ENABLE` env for trace hook

---

internal/tools/pipeline/providers/leaderworker/heartbeat.go

worker set timeout when report heartbeat
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/ticket?id=332499&iterationID=-1&type=TICKET)
/assign @sfwn 
| 🇺🇸 English |  Fix the bug that worker set timeout when report heartbeat           |
| 🇨🇳 中文    |   给worker的心跳检测设置超时时间        |

fix: worker set timeout when report heartbeat

---

internal/tools/orchestrator/endpoints/instance.go
internal/tools/orchestrator/endpoints/instance_test.go

When kill pod in runtime service then call get_service_pods immediately, new pod may be in creating (for example in Phase Pending),  Pod Status has no needed info, so  processing pod.Status info may cause panic 
/assign @luobily @sixther-dc @iutx 
Bugfix： Fix the bug that kill pod in runtime service then call get_service_pods immediately may cause panic  （修复了 在服务的 Pod 详情页面删除 Pod 之后立即调用 get_service_pods 接口获取的 Pod Status 相关字段为空导致处理逻辑 Panic）
| 🇺🇸 English |       Fix the bug that kill pod in runtime service then call get_service_pods immediately may cause panic      |
| 🇨🇳 中文    |     修复了在服务的 Pod 详情页面删除 Pod 之后立即调用 get_service_pods 接口获取的 Pod Status 相关字段为空可能导致处理逻辑 Panic 的问题    |

fix: kill pod then call get_service_pods immediately may panic

---

internal/apps/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/pipelineTable/provider.go
internal/apps/dop/endpoints/pipeline.go
internal/tools/pipeline/spec/pipeline.go
internal/tools/pipeline/spec/pipeline_test.go

manual trigger mode pipeline use run-user permission
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=331588&iterationID=1354&pId=0&type=REQUIREMENT)
/assign @sfwn 
| 🇺🇸 English |   manual trigger mode pipeline use run-user permission           |
| 🇨🇳 中文    |      手动触发的流水线所有节点按执行者权限决定        |

refactor: manual trigger mode pipeline use run-user permission

---

pkg/http/httpserver/server.go
pkg/http/httpserver/vars.go
pkg/http/httpserver/vars_test.go

legacyhttpserver try to get muxVars from infrahttpserver. Because in somecases, legacyhttpserver only be used as router, not httpserver, so no vars handle logic executed.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=333366&iterationID=1354&tab=BUG&type=BUG)
| 🇺🇸 English |  legacyhttpserver try to get muxVars from infrahttpserver            |
| 🇨🇳 中文    |  legacyhttpserver 尝试从 infrahttpserver 中获取路径变量            |

fix: legacyhttpserver try to get muxVars from infrahttpserver

---

internal/apps/msp/apm/alert/components/msp-alert-event-detail/event-history-table/provider.go
internal/apps/msp/apm/alert/components/msp-alert-event-detail/event-overview-info/command.go
internal/apps/msp/apm/alert/components/msp-alert-event-detail/monitor-data-chart/provider.go
internal/apps/msp/apm/alert/components/msp-alert-event-list/table/provider.go
internal/apps/msp/apm/alert/components/msp-alert-overview/alert-duration-analysis/alert-duration-distribution/provider.go
internal/apps/msp/apm/alert/components/msp-alert-overview/alert-event-charts/groupby-level-count/provider.go
internal/apps/msp/apm/alert/components/msp-alert-overview/alert-event-charts/groupby-type-count/provider.go
internal/apps/msp/apm/alert/components/msp-alert-overview/composite-header/cards/statistics.go
internal/apps/msp/apm/alert/components/msp-alert-overview/composite-header/unrecover-alert-chart/provider.go
internal/apps/msp/apm/checker/apis/checker.v1.service.go
internal/tools/monitor/core/metric/storage/clickhouse/query.go
internal/tools/monitor/oap/collector/lib/protoparser/spotmetric/spotmetric.go

compatible org_name is empty, compatible metric name contains `-`
| 🇺🇸 English |      compatible org_name is empty, compatible metric name contains `-`  |
| 🇨🇳 中文    |      兼容 org_name 为空, 以及指标名称包含中划线        |

fix: compatible org_name is empty, compatible metric name contains `-`

---

cmd/monitor/monitor/conf/chartview/runtime/addon-mysql.json

fix: chartview of addon-mysql
| 🇺🇸 English |       fix: chartview of addon-mysql       |
| 🇨🇳 中文    |      修复mysql的监控图表     |

fix: chartview of addon-mysql

---

internal/tools/orchestrator/endpoints/instance.go
internal/tools/orchestrator/endpoints/instance_test.go

get_services_pods for running pods need exclude terminated pods. For now, if pod evicted, there may be many Failed pods which displayed.
/assign @luobily @sixther-dc @iutx 
Bugfix： Fix the bug that get_services_pods for running pods need exclude terminated pods （修复了get_services_pods 接口没有排除终止或者未知状态的 Pods ）
| 🇺🇸 English |     Fix the bug that get_services_pods for running pods need exclude terminated pods         |
| 🇨🇳 中文    |        修复了get_services_pods 接口没有排除终止或者未知状态的 Pods      |

fix: get_services_pods for running pods exclude terminated Pod

---

internal/tools/orchestrator/dbclient/dbmock.go
internal/tools/orchestrator/dbclient/deployment.go
internal/tools/orchestrator/dbclient/deployment_test.go
internal/tools/orchestrator/services/runtime/runtime.go
internal/tools/orchestrator/services/runtime/runtime_test.go

release not found when redeploy
| 🇺🇸 English | release not found when redeploy             |
| 🇨🇳 中文    |   重启时制品获取失败           |

fix(orchestrator): release not found when redeploy

---

internal/apps/dop/component-protocol/components/release-manage/releaseTable/release_gallery.go
internal/apps/dop/dicehub/release/release.service.go
internal/apps/dop/dicehub/release/release.service_test.go
pkg/common/apis/header.go
pkg/common/apis/header_test.go

gallery operation auth failed
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=333727&iterationID=1354&type=BUG)
| 🇺🇸 English |  gallery operation auth failed            |
| 🇨🇳 中文    |    gallery 操作鉴权失败          |

fix(erda-server): gallery operation auth failed

---

internal/tools/orchestrator/components/runtime/mock/mock_sg.go
internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s.go
internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s_test.go
internal/tools/orchestrator/scheduler/impl/servicegroup/operations.go
internal/tools/orchestrator/scheduler/impl/servicegroup/servicegroup.go
internal/tools/orchestrator/services/runtime/runtime.go

get service_pods return different runtime's pods in the same k8s namespace but with different runtimeID
Bugfix： Fix the bug that get service_pods return different runtime's pods in the same k8s namespace but with different runtimeID（修复了 get service_pods 接口返回同一个namespace 下具有相同 serviceName 的不同 runtimeID 的 pods ）
| 🇺🇸 English |      Fix the bug that get service_pods return different runtime's pods in the same k8s namespace but with different runtimeID        |
| 🇨🇳 中文    |      修复了 get service_pods 接口返回同一个namespace 下具有相同 serviceName 的不同 runtimeID 的 pods         |

fix: get service_pods return different runtime's pods 

---

apistructs/ticket.go
apistructs/ticket_test.go
internal/apps/dop/endpoints/sonar.go
internal/apps/dop/endpoints/ticket.go
internal/apps/dop/services/ticket/ticket.go

fix delete sonar tickets no rows affected
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=313601&iterationID=-1&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English | Fix the bug that delete sonar tickets no rows affected             |
| 🇨🇳 中文    |     修复了sonar问题列表没有删除         |

fix(erda-server): delete sonar tickets no rows affected

---

internal/tools/orchestrator/services/deployment_order/deployment_order_create.go
internal/tools/orchestrator/services/deployment_order/deployment_order_create_test.go

Fix deployment order render application repeated.
For example:
- Mode `Go` contains: `go-demo`，`go-admin-demo`
- Mode `QuickStart` contains: `go-demo`
Will cause repeated error: application `go-demo` repeated
| 🇺🇸 English |  deployment order render application repeated            |
| 🇨🇳 中文    |   应用重复导致部署单渲染失败           |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIB …

fix(orchestrator): order render application repeated

---

internal/apps/dop/utils/gittar.go
internal/apps/dop/utils/gittar_test.go

fix(dop): update edge gittar repo url to avoid 302
The curl change seems to be from 620ea2141 (transfer: redirects to other
protocols or ports clear auth, 2022-04-25). The goal is to avoid leaking
credentials between ports: https://curl.se/docs/CVE-2022-27774.html
/assign @sfwn 
| 🇺🇸 English |    update edge gittar repo proto to avoid 302          |
| 🇨🇳 中文    |     修改边缘集群gittar地址的协议，避免302         | …

fix(dop): update edge gittar repo proto to avoid 302

---

internal/apps/cmp/impl/clusters/import_cluster.go
internal/apps/cmp/impl/clusters/import_cluster_test.go

cluster import cpu subscribe ratio error
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=335802&iterationID=1354&tab=BUG&type=BUG)
| 🇺🇸 English | cluster import cpu subscribe ratio error             |
| 🇨🇳 中文    |    集群导入 cpu 超买比错误          |

fix(cmp): cluster import cpu subscribe ratio error

---

internal/apps/dop/services/autotest_v2/scene.go
internal/apps/dop/services/autotest_v2/scene_test.go

replace value of the autotest step if needed after it is created
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=332053&iterationID=1389&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |    Fix the bug that replace value of the autotest step if needed after it is created           |
| 🇨🇳 中文    |      修复了自动化测试步骤复制后循环条件引用自身ID没有变更的问题        |

fix: replace value of the autotest step if needed after it is created

---

internal/apps/dop/dicehub/release/release.go
internal/apps/dop/dicehub/release/release_test.go

import release repeat in mode
before fix:
after fix:
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=336727&iterationID=1403&type=BUG)
| 🇺🇸 English |   import release repeat in mode           |
| 🇨🇳 中文    |   导入模式制品会存在重复           |

fix(dicehub): import release repeat in mode

---

internal/apps/cmp/initialize.go
pkg/time/ticker/ticker.go
pkg/time/ticker/ticker_test.go

pkg time/ticker support execAtBegin configurable
/assign @dspo 
| 🇺🇸 English |  pkg time/ticker support execAtBegin configurable            |
| 🇨🇳 中文    |   包 pkg/ticker 支持 "开始时立即执行" 可配置           |

chore: pkg time/ticker support execAtBegin configurable

---

internal/apps/cmp/initialize.go

cmp steve route use ** as wildcard
/assign @CraigMChen 
| 🇺🇸 English |   cmp steve route use ** as wildcard           |
| 🇨🇳 中文    |   cmp steve 路由使用 ** 作为通配符           |

fix(cmp): cmp steve route use ** as wildcard

---

api/proto/core/pipeline/graph/graph.proto

openapi miss pipeline-yml-graph route
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that openapi miss pipeline-yml-graph route           |
| 🇨🇳 中文    |   修复了openapi丢失graph路由的问题           |

fix: openapi miss pipeline-yml-graph route

---

internal/apps/dop/providers/issue/core/query/convert.go
internal/apps/dop/providers/issue/core/query/convert_test.go

issue export set empty value for custom property column if value not set. 
otherwise, row columns will mismatch with title.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=338304&iterationID=1389&type=BUG)
/assign @chengjoey @luobily 
| 🇺🇸 English |   issue export set empty value for custom property column if value not set           |
| 🇨🇳 中文    |  事项导出时，如果自定义字段未设置值，则置空值，否则列会匹配不上            |

fix: issue export set empty value for custom property column if value not set

---

cmd/monitor/streaming/bootstrap.yaml

fix: modify enable env of clickhouse.table.initializer@log
| 🇺🇸 English | fix: modify enable env of clickhouse.table.initializer@log |
| 🇨🇳 中文    | 修改启用 clickhouse.table.initializer@log 的环境变量 |

fix: modify enable env of clickhouse.table.initializer@log

---

internal/apps/cmp/endpoints/endpoints.go
internal/apps/cmp/impl/clusters/upgrade_edge_cluster.go
internal/apps/cmp/impl/mns/mns.go
internal/apps/cmp/provider.go

cmp use org.Interface to replace org.ClientInterface because it bootstrapped on erda-server
/assign @CraigMChen 
| 🇺🇸 English |  cmp use org.Interface to replace org.ClientInterface because it bootstrapped on erda-server            |
| 🇨🇳 中文    |   由于 cmp 已经由 erda-server 启动，cmp 使用 org.Interface 来替换 org.ClientInterface      |

fix(cmp): cmp use org.Interface because it bootstrapped on erda-server

---

internal/core/openapi/openapi-ng/routes/openapi-v1/provider.go

openapiv1 enable hooks to filter invalid headers like org-id and user-id.
- [Related Erda Issue](https://erda.cloud/erda/dop/projects/387/issues/all?id=340579&iterationID=-1&type=TASK)
/assign @chengjoey @dspo 
| 🇺🇸 English |   openapiv1 enable hooks to filter invalid headers like org-id and user-id          |
| 🇨🇳 中文    |   openapiv1 启用 hooks 来过滤非法请求头，比如 org-id 和 user-id           |

fix(openapi): enable openapiv1 hooks

---

internal/apps/dop/component-protocol/components/scenes-import-record/table/render.go

fix scenes file record download url
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?id=340373&iterationID=1403&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |    fix scenes file record download url          |
| 🇨🇳 中文    |       修复了自动化测试记录文件下载链接错误的问题       |

fix: scenes file record download url

---

cmd/cluster-agent/bootstrap.yaml
internal/tools/cluster-agent/config/config.go
internal/tools/cluster-agent/pkg/client/client.go

>= kubernetes version 1.24, serviceaccount not bind secret default
use tokenCreate to suit.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=341632&iterationID=1403&type=TASK)
| 🇺🇸 English |  cluster-agent collect token after k8s version 1.24            |
| 🇨🇳 中文    |    cluster-agent 采集 token k8s version >=1.24          | …

fix: cluster-agent collect token after k8s version 1.24

---

internal/apps/dop/endpoints/project_pipeline.go
internal/apps/dop/endpoints/project_pipeline_test.go

project-pipeline add orgName label for monitor collector
/assign @sfwn @CraigMChen 
| 🇺🇸 English |   Fix the bug that project-pipeline add orgName label for monitor collector            |
| 🇨🇳 中文    |   修复了新监控采集项目流水线日志时，缺失orgName的问题           |

fix: project-pipeline add orgName label for monitor collector

---

internal/tools/pipeline/providers/run/run.go

pipeline panic due to nil run param
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that pipeline panic due to nil run param           |
| 🇨🇳 中文    |    修复了由于运行参数为空造成pipeline panic的问题          |

fix: pipeline panic due to nil run param

---

internal/tools/pipeline/providers/pipeline/provider.go

pipeline and actionmgr provider transaction session competing mysql links
/assign @sfwn 
| 🇺🇸 English |  Fix the bug that pipeline and actionmgr provider transaction session competing mysql links            |
| 🇨🇳 中文    |   修复了pipeline和actionmgr provider互相竞争mysql链接的问题           |

fix(pipeline): pipeline and actionmgr provider transaction session competing mysql connections

---

internal/tools/pipeline/providers/cache/impl.go
internal/tools/pipeline/providers/cache/impl_test.go
internal/tools/pipeline/providers/cache/interface.go
internal/tools/pipeline/providers/cache/provider.go
internal/tools/pipeline/providers/pipeline/create_v2.go
internal/tools/pipeline/providers/pipeline/create_v2_test.go

pipeline try get orgName if empty
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that pipeline try get orgName if empty           |
| 🇨🇳 中文    |    修复了流水线请求没有带上组织名的情况下无日志的问题          |

fix: pipeline try get orgName if empty

---

internal/core/legacy/initialize.go

core-services websocket route use ** as wildcard
caused by: [#5467](https://github.com/erda-project/erda/pull/5467/files#diff-4cf51b0897a2dbafb7bacd9cccea88db27dc43a644ffd0bcaf4ab6888c330f4fR54)
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=344988&iterationID=1440&type=BUG)
/assign @chengjoey @sixther-dc 
| 🇺🇸 English |   core-services websocket route use ** as wildcard           |
| 🇨🇳 中文    |  core-services websocket 路由使用 ** 作为通配符            |
Add comment like `/cherry-pick release/2.3-beta.7` when this PR is merged.

fix(core-services): websocket route use ** as wildcard

---

apistructs/issue_test.go
internal/apps/msp/resource/deploy/handlers/apigateway/apigateway.go
internal/tools/orchestrator/scheduler/executor/plugins/k8s/ingress/common/parse.go
internal/tools/orchestrator/scheduler/executor/plugins/k8s/ingress/common/parse_test.go
internal/tools/orchestrator/scheduler/executor/plugins/k8s/ingress/extension/v1beta1/ingress.go
internal/tools/orchestrator/scheduler/executor/plugins/k8s/ingress/extension/v1beta1/ingress_test.go
internal/tools/orchestrator/scheduler/executor/plugins/k8s/ingress/ingress.go
internal/tools/orchestrator/scheduler/executor/plugins/k8s/ingress/networking/v1/ingress.go
internal/tools/orchestrator/scheduler/executor/plugins/k8s/ingress/networking/v1/ingress_test.go
internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s.go
internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s_stateful.go
internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s_test.go
internal/tools/orchestrator/scheduler/executor/plugins/k8s/statefulset_test.go
internal/tools/orchestrator/scheduler/executor/util/discovery.go

1. o11 suite ingress networking/v1.
2. clean up ingress code in scheduler.
| 🇺🇸 English |  o11 suite ingress networking/v1             |
| 🇨🇳 中文    |   协调器适配 ingress  networking/v1            |

feat(orchestrator): o11 suite ingress networking/v1

---

internal/tools/orchestrator/hepa/repository/service/gateway_az_info_service.go

erda-server  api  /api/projects/{projectId}  need set Header "Org-ID", heap call erda-server for this api not set Header "Org-ID"
/assign @iutx @sixther-dc 
Bugfix： Fix the bug that heap call erda-server for this api not set Header "Org-ID" （修复了 heap 调用 erda-server 接口未设置 Header "Org-ID" 导致 tb_gateway_az_info 无法插入数据）
| 🇺🇸 English |         Fix the bug that heap call erda-server for this api not set Header "Org-ID"     |
| 🇨🇳 中文    |      修复了 heap 调用 erda-server 接口未设置 Header "Org-ID" 导致 tb_gateway_az_info 无法插入数据        |

fix: hepa get cluster info failed

---

cmd/orchestrator/bootstrap.yaml

fix: o11 start with admin http-server
| 🇺🇸 English |     fix o11 start with admin http-server         |
| 🇨🇳 中文    |            o11 启动增加 http-server admin  |

fix(orchestrator): o11 start with admin http-server

---

.erda/migrations/gittar/20221027-gittar-alert-pipeline-id.sql

fix `dice_repo_check_runs` pipelineID filed out of range value
/assign @sfwn @Effet 
| 🇺🇸 English |    Fix the bug that `dice_repo_check_runs` pipelineID filed out of range value          |
| 🇨🇳 中文    |     修复了gittar `dice_repo_check_runs`表的pipelineID字段长度过短的问题         |

fix(gittar): `dice_repo_check_runs` pipelineID filed out of range value

---

.erda/migrations/gittar/20221027-gittar-alert-pipeline-id.sql

fix alert `dice_repo_check_runs` pipelineID sql
/assign @sfwn 
| 🇺🇸 English |    Fix the bug that alert `dice_repo_check_runs` pipelineID sq          |
| 🇨🇳 中文    |    修复了更改migration语法限制的sql语句          |

fix: alert `dice_repo_check_runs` pipelineID sql

---

tools/cli/cmd/project_deployment_start.go
tools/cli/cmd/project_deployment_stop.go
tools/cli/command/context.go
tools/cli/common/org.go
tools/cli/common/project.go

New erda ui and erda-server need erda-cli  adjust http header to org, need to call openapi  api through openapi addr
/assign @iutx @sixther-dc @luobily 
Bugfix： Fix the bug that  new erda ui and erda-server need erda-cli  adjust http header to org, need to call openapi  api through openapi addr（修复了  erda  ui 和 erda-server 调整导致 erda-cli 工具无法正常运行的问题）
| 🇺🇸 English |      Fix the bug that  new erda ui and erda-server need erda-cli  adjust http header to org, need to call openapi  api through openapi addr        |
| 🇨🇳 中文    |      修复了  erda  ui 和 erda-server 调整导致 erda-cli 工具无法正常运行的问题        |

fix: erda-cli need org Header and openapi  host

---

internal/apps/dop/component-protocol/components/auto-test-plan-list/components/table/render.go
internal/apps/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileExecute/executeHead/executeHistory/executeHistoryPop/executeHistoryTable/render.go
internal/apps/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileExecute/executeInfo/render.go
internal/apps/dop/component-protocol/components/auto-test-space-list/components/recordTable/render.go
internal/apps/dop/component-protocol/components/auto-test-space-list/components/spaceList/render.go
internal/core/openapi/legacy/component-protocol/scenarios/auto-test-plan-detail/components/executeHistoryTable/render.go
internal/core/openapi/legacy/component-protocol/scenarios/auto-test-plan-detail/components/executeInfo/render.go
internal/tools/pipeline/actionagent/step_prepare.go
internal/tools/pipeline/actionagent/step_prepare_test.go
internal/tools/pipeline/actionagent/step_validate.go

format pipeline time in local
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=347386&iterationID=-1&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that format pipeline time in local           |
| 🇨🇳 中文    |    修复了测试计划等时间展示少8小时的问题          |

fix: format pipeline time in local

---

internal/pkg/extension/db/extension.go
internal/pkg/extension/extension.service.go

fix extension record not found type judgment error
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that extension record not found type judgment error           |
| 🇨🇳 中文    |      修复了extension记录无法找到的类型错误问题        |

fix: extension record not found type judgment error

---

go.mod
go.sum
internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sflink/flink.go
internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sflink/util.go
pkg/k8sclient/scheme/register.go

fix flink-operator compatibility in k8s 1.24 version
/assign @sfwn @cxr29 
| 🇺🇸 English | Fix the bug that flink-operator compatibility in k8s 1.24 version              |
| 🇨🇳 中文    |      修复了flink在k8s 1.24版本的兼容性问题        |

fix: flink-operator compatibility in k8s 1.24 version

---

internal/tools/pipeline/aop/plugins/task/autotest_cookie_keep_before/cookie.go
internal/tools/pipeline/aop/plugins/task/autotest_cookie_keep_before/cookie_test.go
internal/tools/pipeline/aop/plugins/task/autotest_cookie_keep_before/plugin.go

sort the cookie reports in order to make sure the latest cookie will be used
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that sort the cookie reports in order to make sure the latest cookie will be used           |
| 🇨🇳 中文    |   修复了自动化测试接口没有使用最新cookie的问题           |

fix: sort the cookie reports in order to make sure the latest cookie will be used

---

.erda/migrations/cmdb/20221213-code-coverage-include-exclude.sql

extend the length limit of the field `includes` `excludes`
/assign @sfwn 
| 🇺🇸 English |Fix the bug that extend the length limit of the field `includes` `excludes`              |
| 🇨🇳 中文    |   修复了覆盖率部分字段长度限制太短的问题           |

fix: extend the length limit of the field `includes` `excludes`

---

internal/tools/pipeline/providers/dispatcher/consistent.go
internal/tools/pipeline/providers/leaderworker/leader_listen_worker_task.go

fix leaderwork failed to init assign map due to context cancel
/assign @sfwn 
| 🇺🇸 English |    Fix the bug that leaderwork failed to init assign map due to context cancel          |
| 🇨🇳 中文    |     修复了context done造成重复失败的问题    |

fix: leaderwork failed to init assign map due to context cancel

---

internal/tools/pipeline/providers/edgepipeline_register/interface.go
internal/tools/pipeline/providers/edgepipeline_register/interface_test.go

fix leader pipeline too many network connections due to query is edge cluster
/assign @sfwn 
| 🇺🇸 English |    Fix the bug that leader pipeline too many network connections due to query is edge cluster          |
| 🇨🇳 中文    |    修复了pipeline的定时补偿由于大量查询边缘集群导致的链接数太多问题          |

fix(pipeline): leader pipeline too many network connections due to query is edge cluster

---

internal/apps/cmp/endpoints/cluster_credential.go
internal/apps/cmp/endpoints/common.go
internal/apps/cmp/endpoints/commone_test.go
internal/apps/cmp/i18n/i18n.go

fix cluster access key render auth fail
| 🇺🇸 English | fix cluster access key render auth fail             |
| 🇨🇳 中文    | 修复渲染 集群 ak 鉴权失败             |

fix: cluster access key render auth fail

---

.erda/migrations/cmdb/requirements.txt

remove redundant migration dependency package
mysql-client depend on mysql devel package, e.g. ‘mysql.sh’, not pure python.
In arm64, mysql use mysql-community-minimal，install mysql-community-devel will cause package conflict.
| 🇺🇸 English |   remove redundant migration dependency package           |
| 🇨🇳 中文    |    删除 migration 中无用的依赖包          | …

fix: remove redundant migration dependency package

---

apistructs/service.go
go.mod
go.sum
internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/rocketmq/rocketmq.go
internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s.go
internal/tools/orchestrator/services/addon/addon.go
internal/tools/orchestrator/services/addon/addon_deploy.go
internal/tools/orchestrator/services/addon/addon_status.go
internal/tools/orchestrator/services/addon/addon_status_test.go
internal/tools/orchestrator/services/addon/middleware.go
pkg/k8sclient/scheme/register.go

support rocketmq operator executor
1. create rocketmq cluster by operator where version >= 5.0.0
2. auto enable rocketmq exporter for metrics
| 🇺🇸 English | Suppor rocketmq operator executor on orchestrator             |
| 🇨🇳 中文    |    实现rocketmq operator的executor，支持5.0.0版本用operator创建集群          |

feat: support rocketmq operator executor

---

internal/tools/monitor/core/metric/query/metricmeta/manager.go
internal/tools/monitor/core/metric/query/metricmeta/manager_test.go

fix metric use es meta panic
| 🇺🇸 English |    fix metric use es meta panic          |
| 🇨🇳 中文    |        指标使用 es 时, meta 造成 panic      |

fix: metric use es meta panic

---

internal/core/legacy/endpoints/label.go
internal/core/legacy/endpoints/label_test.go

fix project label permission leak
Tested on erda daily. Now, code will check operator's **PROJECT UPDATE** permission for write operations(create / delete / update), and check **PROJECT GET** permission for read operations(get / list).
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=358748&iterationID=1501&type=TASK)
| 🇺🇸 English |  fix project label permission leak            |
| 🇨🇳 中文    |   修复项目标签越权           |

fix(erda-server): project label permission leak

---

apistructs/issue_stream_locale.go
internal/apps/dop/providers/issue/core/service.go
internal/apps/dop/providers/issue/stream/common/model.go

fix issue-stream's compatibility with label types
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that issue-stream's compatibility with label types           |
| 🇨🇳 中文    |  修复了issue-stream修改标签事件对新老数据的兼容性问题            |

fix(dop): issue-stream's compatibility with label types

---

internal/core/legacy/endpoints/notify_item.go

fix general user query notify-items access denied
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=359654&iterationID=-1&tab=BUG&type=BUG)
/assign @sfwn 
| 🇺🇸 English |  Fix the bug that general user query notify-items access denied            |
| 🇨🇳 中文    |     修复了普通用户查询通知项无权限的问题         |

fix: general user query notify-items access denied

---

apistructs/addon.go
internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s_stateful.go
internal/tools/orchestrator/scheduler/executor/plugins/k8s/statefulset.go
internal/tools/orchestrator/services/addon/addon_status.go
internal/tools/orchestrator/services/addon/addon_status_test.go

redis addon sts add exporter sidecar
| 🇺🇸 English |    Support redis addon sts add exporter sidecar          |
| 🇨🇳 中文    |   redis addon支持监控exporter的sidecar           |

feat(orchestrator): redis addon sts add exporter sidecar

---

internal/apps/msp/apm/service/components/resources-runtime-monitor-java/runtime/provider.go

fix memory graph of the container monitor is inconsistent with the memory graph of the instance monitor
/assign @sfwn 
| 🇺🇸 English |   fix: memory chart no true           |
| 🇨🇳 中文    |     修复内存图表不准确         |

fix: memory chart no incorrect

---

apistructs/container.go
internal/tools/orchestrator/endpoints/instance.go
internal/tools/orchestrator/endpoints/instance_test.go
internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s.go
internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s_test.go

Due to some deployed runtime  about 1.5 years ago,  runtime's pod without runtimeID info in Pod Labels (which use for match pods), so get pod will get no matched pod. 
/assign @sixther-dc @luobily @iutx @sfwn 
Bugfix： Fix the bug that runtime's pod without runtimeID info in Pod Labels  can not get matched pod （修复了  Pod 的 Labels 中无 RuntimeID 信息，导致获取重启次数无法获取）
| 🇺🇸 English |      Fix the bug that runtime's pod without runtimeID info in Pod Labels  can not get matched pod         |
| 🇨🇳 中文    |      修复了  Pod 的 Labels 中无 RuntimeID 信息，导致获取重启次数无法获取        |

fix: fix get pod status from k8s failed due pod without runtimeId label

---

internal/apps/dop/providers/issue/core/query/convert.go
internal/apps/dop/providers/issue/core/query/convert_test.go
internal/apps/dop/providers/issue/core/service.go

fix  issue detail missing property instances
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=360159&iterationID=1580&type=BUG)
/assign @sfwn 
| 🇺🇸 English |    Fix the bug that issue detail missing property instances           |
| 🇨🇳 中文    |    修复了事项详情丢失了自定义用户信息的问题          |

fix(dop): issue detail missing property instances

---

internal/apps/cmp/component-protocol/components/cmp-dashboard-nodes/podTable/render.go
internal/apps/cmp/component-protocol/components/cmp-dashboard-nodes/podTable/render_test.go
internal/apps/cmp/component-protocol/components/cmp-dashboard-nodes/table/render.go

fix cmp server panic due to steveServer not initialized
/assign @sfwn @dspo 
| 🇺🇸 English |   Fix the bug that cmp server panic due to steveServer not initialized           |
| 🇨🇳 中文    |   修复了cmp由于服务没初始化完全造成的panic问题           |

fix(cmp): cmp server panic due to steveServer not initialized

---

internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go

metric query head time bucket not full, time is not true
/assign @sfwn 
| 🇺🇸 English |    metric query head time bucket not full, time is not true          |
| 🇨🇳 中文    |      指标查询, 头部 time bucket 未满时, 时间错误        |

fix: metric query head time bucket not full, time is not true

---

internal/tools/monitor/oap/collector/interceptor/constants.go
internal/tools/monitor/oap/collector/plugins/receivers/opentelemetry/interceptor.go

Since the trace-id of the otlp javaagent is 32 bits, when the upstream is erda java-agent and the downstream is otlp javaagent, the traceid (uuid format) of erda java-agent cannot be recognized by the oltp java-agent, so the method of using attr to store in the otlp javaagent and then performing data replacement at the collector is adopted.
由于otlp javaagent的 trace-id 为32位，当上游是erda java-agent，下游是otlp javaagent时，erda java-agent 的 traceid （uuid格式）无法被oltp java-agent识别，因此采用在otlp javaagent使用attr来存储， 然后再collector处再进行数据替换的方法。
| 🇺🇸 English |       compatible the span data from erda java-agent to otlp java-agent       |
| 🇨🇳 中文    | …

feat: compatible the span data from erda java-agent to otlp java-agent

---

internal/apps/dop/component-protocol/components/auto-test-space-list/components/recordTable/render.go

fix autotest download url
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=362449&iterationID=-1&tab=BUG&type=BUG)
/assign @sfwn 
| 🇺🇸 English |    Fix the bug that autotest download url           |
| 🇨🇳 中文    |       修复了接口测试导出为html的问题       |

fix: autotest download url

---

erda.yml

declare pprof port for continuous profiling in erda.yaml
| 🇺🇸 English |   declare pprof port for continuous profiling in erda.yaml          |
| 🇨🇳 中文    |    在 erda.yaml 中声明 pprof 端口用于持续分析          |

feat: declare pprof port for continuous profiling in erda.yaml

---

.github/workflows/git-sync.yml

remove useless git unshallow after fetching all
| 🇺🇸 English |  CI remove useless git unshallow after fetching all           |
| 🇨🇳 中文    |   CI 在拉取仓库所有历史后删除无用的 git unshallow     |

ci: remove useless git unshallow after fetching all

---

apistructs/cluster_info.go
internal/tools/pipeline/providers/actionmgr/impl.go
internal/tools/pipeline/providers/actionmgr/interface.go
internal/tools/pipeline/providers/reconciler/taskrun/taskop/prepare.go
internal/tools/pipeline/providers/reconciler/taskrun/taskop/prepare_test.go
internal/tools/pipeline/providers/secret/platform_secret.go

pipeline render extension image for different architecture
/assign @sfwn 
| 🇺🇸 English |    Support pipeline render extension image for different architecture          |
| 🇨🇳 中文    |    Support pipeline render extension image for different architecture          |

feat(pipeline): pipeline render extension image for different architecture

---

internal/tools/orchestrator/services/addon/addon_status.go

add addon id for mysql addon label
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=366260&iterationID=-1&type=BUG)
/assign @sfwn 
| 🇺🇸 English | Fix the bug that add addon id for mysql label             |
| 🇨🇳 中文    |    修复了mysql丢失addonid以致于监控无法采集的问题          |

fix: add addon id for mysql label

---

internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/mysql/mysql.go
internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/redis/legacy/redis.go
internal/tools/orchestrator/services/addon/addon_deploy.go
internal/tools/orchestrator/services/addon/addon_status.go

fix redis mysql operator deployment failure
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=367866&iterationID=1628&tab=BUG&type=BUG)
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that redis mysql operator deployment failure            |
| 🇨🇳 中文    |    修复了redis和mysql addon部署失败的问题          |

fix(orchestrator): redis mysql operator deployment failure

---

internal/apps/msp/apm/service/components/resources-runtime-monitor-java/runtime/provider.go

ref: https://github.com/erda-project/erda-java-extensions/blob/master/agent-plugins/agent-jvm-plugin/src/main/java/cloud/erda/agent/plugin/jvm/GCStatsProvider.java#L51
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/ticket?id=369141&iterationID=-1&type=TICKET)
/assign @tomatopunk 
| 🇺🇸 English |  fix: jvm gc time unit should be ms            |
| 🇨🇳 中文    |   修复：JVM GC 时间单位应为毫秒           |
Add comment like `/cherry-pick release/2.3` when this PR is merged.

fix: jvm gc time unit should be ms

---

apistructs/application.go
internal/tools/orchestrator/scheduler/executor/plugins/k8s/deployment.go
internal/tools/orchestrator/scheduler/executor/plugins/k8s/lifecycle.go
internal/tools/orchestrator/scheduler/executor/plugins/k8s/lifecycle_test.go
internal/tools/orchestrator/scheduler/executor/util/util.go

support lifecycle prestop in prod env
test result:
| 🇺🇸 English |     support lifecycle prestop in prod env         |
| 🇨🇳 中文    |       支持生产环境 lifecycle prestop       |

feat(orchestrator): support lifecycle prestop in prod env

---

internal/tools/orchestrator/hepa/apipolicy/policies/built-in/policy.go
internal/tools/orchestrator/hepa/apipolicy/policies/cors/policy.go
internal/tools/orchestrator/hepa/apipolicy/policies/csrf/policy.go
internal/tools/orchestrator/hepa/apipolicy/policies/custom/policy.go
internal/tools/orchestrator/hepa/apipolicy/policies/ip/policy.go
internal/tools/orchestrator/hepa/apipolicy/policies/proxy/policy.go
internal/tools/orchestrator/hepa/apipolicy/policies/sbac/policy.go
internal/tools/orchestrator/hepa/apipolicy/policies/server-guard/policy.go
internal/tools/orchestrator/hepa/apipolicy/policies/waf/policy.go
internal/tools/orchestrator/hepa/apipolicy/policy_engine.go
internal/tools/orchestrator/hepa/services/api_policy/impl/impl.go

Fix the bug that:  when set kong sbac and csrf policy for specified API without routeId result global kong policy., so all existed APIs can not accessed。
/assign @luobily @iutx @dspo @sixther-dc 
Bugfix： Fix the bug that when set kong sbac and csrf policy for specified API without routeId result global kong policy., so all existed APIs can not accessed（修复了 kong 设置 sbac和 csrf 策略不带 roueId 导致设置成全局变量.）
| 🇺🇸 English |      Fix the bug that when set kong sbac and csrf policy for specified API without routeId result global kong policy., so all existed APIs can not accessed         |
| 🇨🇳 中文    |     修复了 kong 设置 sbac和 csrf 策略不带 roueId 导致设置成全局变量         |

fix: kong sbac and csrf plugin parse for specified routeId

---

cmd/monitor/monitor/conf/chartview/runtime/addon-rocketmq.json

fix  rocketmq chart no data due to startTime and EndTime
/assign @sfwn @tomatopunk 
| 🇺🇸 English |   Fix the bug that rocketmq chart no data due to startTime and EndTime           |
| 🇨🇳 中文    |      修复了addon rocketmq监控无数据的问题        |

fix(monitor): rocketmq chart no data due to startTime and EndTime

---

pipeline.yml

default pipelineYml use ((target_arch)) instead of ((arch))
/assign @sfwn 
| 🇺🇸 English |   default pipelineYml use ((target_arch)) instead of ((arch))          |
| 🇨🇳 中文    |    用target_arch代替流水线arch变量          |

chore: default pipeline.yml use ((target_arch)) instead of ((arch))

---

internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sflink/flink.go

fix flinkcluster idempotent deletion task failure due to the returned type error
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=371332&iterationID=1580&tab=BUG&type=BUG)
/assign @sfwn 
| 🇺🇸 English | Fix the bug that flinkcluster executor idempotent deletion task failure due to the returned type error             |
| 🇨🇳 中文    |   修复了flinkcluster由于返回类型错误导致的幂等删除任务失败的问题           | …

fix(pipeline): flinkcluster executor idempotent deletion task failure due to the returned type error

---

internal/tools/orchestrator/services/addon/addon_deploy.go
internal/tools/orchestrator/services/addon/addon_handler.go
internal/tools/orchestrator/services/addon/addon_status.go
internal/tools/orchestrator/services/addon/addon_test.go

fix addons deployment failure due to failed to get clusterinfo
this bug is start at [5724](https://github.com/erda-project/erda/pull/5724)
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=367866&iterationID=1580&tab=BUG&type=BUG)
| 🇺🇸 English |    Fix the bug that addons deployment failure due to failed to get clusterinfo           |
| 🇨🇳 中文    |  修复了由于无集群名称参数造成的mysql,redis部署失败问题            | …

fix(orchestrator): addons deployment failure due to failed to get clusterinfo

---

internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/elasticsearch/elasticsearch.go
internal/tools/orchestrator/services/addon/addon_status.go
internal/tools/orchestrator/services/addon/addon_status_test.go

set podSecurityContext for es addon
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=370993&iterationID=-1&tab=TASK&type=TASK)
| 🇺🇸 English |  Support set podSecurityContext for es addon            |
| 🇨🇳 中文    |     orchestrator为es-addon配置容器安全上下文         |

feat(orchestrator): set podSecurityContext for es addon

---

internal/tools/pipeline/providers/reconciler/taskrun/taskop/wait.go
internal/tools/pipeline/providers/reconciler/taskrun/taskop/wait_test.go

fix the waiting time of taskOP.Wait overflows when the declineRatio to loopedTimes power bigger than int64
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=371566&iterationID=1628&tab=TASK&type=TASK)
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that the waiting time of taskOP.Wait overflows when the declineRatio to loopedTimes power bigger than int64           |
| 🇨🇳 中文    |    修复了流水线查询任务状态的时间间隔大小溢出导致频率过高的问题          | …

fix(pipeline): the waiting time of taskOP.Wait overflows when the declineRatio to loopedTimes power bigger than int64

---

internal/tools/orchestrator/hepa/gateway-providers/kong/dto/kong_target_dto.go
internal/tools/orchestrator/hepa/gateway-providers/kong/dto/kong_target_dto_test.go
internal/tools/orchestrator/hepa/gateway-providers/mse/mse_adapter.go
internal/tools/orchestrator/hepa/services/legacy_upstream_lb/impl/impl.go

请求 /upstreams/{upstreamId}/targets 相关接口时, 返回如下错误
```text
statusCode:400 response body: {"success":false,"err":{"code":"400","msg":"parameter request error invalid: json: cannot unmarshal number 1679018347.926 into Go struct field KongTargetDto.created_at of type int64","ctx":"/api/gateway/target/online"}}2023-03-17 09:59:11.600INFO[admin-web] ---  - [main] utoConfigurationReportLoggingInitializer: Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.2023-03-17 09:59:11.618ERROR[admin-web] ---  - [main] o.s.boot.SpringApplication              : Application startup failed
```
是由于 hepa 没有正确 unmarshal kong 返回的结果.
kong 协议文档中 created_at 示例是整数类型,
因此 hepa 中定义的也是整数类型,
但 kong 接口返回的却可能是小数,
因此将 `CreatedAt int64` 类型改成 `CreatedAt …

fix: kong data field created_at unmarshal

---

.erda/pipelines/ci-build-ce.yml
.erda/pipelines/ci-deploy.yml
.github/workflows/ci-it.yml
Makefile
build/scripts/docker_image.sh
pipeline.yml

```shell
$ docker manifest inspect registry.erda.cloud/erda/erda-base:20230130
{
"schemaVersion": 2,
"mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
"manifests": [
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 2851,
"digest": "sha256:ab5a3568626efd6e066ed2178ddcf09f6d92d154769dbf61f523d186c4533650",
"platform": {
"architecture": "amd64",
"os": "linux"
}
},
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 2851,
"digest": "sha256:9121a4b55da4081f2dbd2fc7e7c8e49201b1c46f5d6e76f63e37dd72e2331784",
"platform": {
"architecture": "arm64",
"os": "linux"
}
}
]
}
```
| --------- | …

feat: multi-arch image for erda-base:20230130

---

cmd/monitor/collector/bootstrap.yaml
internal/tools/monitor/oap/collector/plugins/processors/aggregator/functions.go
internal/tools/monitor/oap/collector/plugins/processors/aggregator/provider_test.go

fix missing `oomkilled` metric after collect metrics from cadvisor
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=366248&iterationID=-1&tab=TASK&type=TASK)
/assign @sfwn @tomatopunk 
| 🇺🇸 English |    fix(collector) missing `oomkilled` metric after collect metrics from cadvisor          |
| 🇨🇳 中文    |     修复了oom类告警由于丢失`oomkilled`指标无法发出的问题         |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md …

fix(collector): missing `oomkilled` metric after collect metrics from cadvisor

---

.erda/migrations/hepa/20230331-hepa-gateway-consumer-credential.sql

create table tb_gateway_credential if not exist
/assign @dspo @sixther-dc 
Bugfix： Fix the bug that reate table tb_gateway_credential if not exist（修复了 表存在重复创建失败的问题  ）
| 🇺🇸 English |     Fix the bug that reate table tb_gateway_credential if not exist          |
| 🇨🇳 中文    |    修复了 表 tb_gateway_credential 存在重复创建失败的问题           |

fix: create table tb_gateway_credential if not exist

---

internal/apps/dop/component-protocol/standard-components/issueFilter/conditions.go
internal/apps/dop/component-protocol/standard-components/issueFilter/conditions_test.go
internal/apps/dop/component-protocol/standard-components/issueFilter/provider.go

fix: issues states always be default after refresh
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that issues states always be default after refresh           |
| 🇨🇳 中文    |   修复了事项协同状态筛选总是在刷新后变成默认值的问题           |

fix(dop): issues states always be default after refresh

---

internal/tools/orchestrator/services/addon/addon_status.go
internal/tools/orchestrator/services/addon/addon_status_test.go

fix rocketmq resource missing replicas definition
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that rocketmq resource missing replicas definition           |
| 🇨🇳 中文    |     修复了rocketmq资源部署时丢失了副本数定义的问题         |

fix(orchestrator):  rocketmq resource missing replicas definition

---

internal/tools/orchestrator/hepa/services/openapi_rule/impl/impl.go

fix: domain policy regex
网关的鉴权模型, 会使用正则表达式去匹配 http 请求的域名, 如果能匹配上, 则将鉴权策略应用于该次请求.
鉴权模型里有个 "^(xxx\\.com)" 这样的正则表达式, 当请求 xxx.com.cn 这个域名时, 也会被这个正则表达式命中, 因此对 xxx.com.cn 这个域名的请求会被鉴权策略拦截.
本 PR 修复 erda 上关于这段正则表达式生成的部分代码, 使其正确匹配请求的域名.
| 🇺🇸 English | fix: domain policy regex |
| 🇨🇳 中文    | 修复 domain-policy 正则表达式错误的问题 | …

fix: domain-policy regex

---

internal/tools/monitor/oap/collector/core/pipeline/pipeline.go

fix collect metric concurrent read map
/assign @sfwn 
| 🇺🇸 English |    fix collect metric concurrent read map           |
| 🇨🇳 中文    |     修复 collect 指标并行读 map         |

fix: fix collect metric concurrent read map

---

cmd/monitor/monitor/conf/chartview/runtime/addon-kafka.json
internal/tools/orchestrator/services/addon/addon_status.go
internal/tools/orchestrator/services/addon/addon_status_test.go

add exporter sidecar for kafka cluster addon
add kafka monitor config
/assign @sfwn 
| 🇺🇸 English |    add exporter sidecar for kafka cluster addon          |
| 🇨🇳 中文    |   中间件kafka增加exporter监控大盘           |

feat(orchestrator): add exporter sidecar for kafka cluster addon

---

internal/apps/dop/component-protocol/standard-components/issueFilter/provider.go
internal/apps/dop/component-protocol/standard-components/issueFilter/provider_test.go

issue-manager default show unfinished state tickets
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=373953&iterationID=1628&tab=REQUIREMENT&type=REQUIREMENT)
/assign @sfwn 
| 🇺🇸 English |    Support issue-manager default show unfinished state tickets          |
| 🇨🇳 中文    |      工单页默认展示 “未解决事项”        |

feat(dop): issue-manager default show unfinished state tickets

---

.erda/migrations/config.yml
.erda/migrations/monitor/20230515-sp-profile-apps.sql
cmd/monitor/streaming/bootstrap.yaml
go.mod
go.sum

set profile data 1day ttl
/assign @sfwn 
| 🇺🇸 English |   set profile data 1day ttl           |
| 🇨🇳 中文    |    将可持续性观测数据的默认保留时间设置为默认1天          |

chore(monitor): set profile data 1day ttl

---

internal/tools/pipeline/providers/reconciler/pipeline_reconciler.go

1. increase pipeline processing total when processing
2. add task processing total metrics
/assign @sfwn 
| 🇺🇸 English |    adjust pipeline, task processing metrics           |
| 🇨🇳 中文    |     修改流水线相关指标数据         |

chore(pipeline): pipeline, task processing metrics

---

internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go

fix clickhouse parse timestamp desc invalid
/assign @tomatopunk @sfwn 
| 🇺🇸 English |   fix clickhouse parse timestamp desc invalid            |
| 🇨🇳 中文    |  修复clickhouse解析timestamp排序字段无效的问题            |

fix: clickhouse parse timestamp desc invalid

---

internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go

no need to do orderby on selected-column, in the case of already sorted by time
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/iteration/1737/all?id=380220&iterationID=1737&tab=BUG&type=BUG)
/assign @sfwn @sixther-dc @tomatopunk 
| 🇺🇸 English |   Fix the bug that no need to do orderby on selected-column, in the case of already sorted by time           |
| 🇨🇳 中文    |  修复了 在已经按时间排序的情况下仍然对select的column做排序的问题            | …

fix(monitor): no need to do orderby on selected-column, in the case of already sorted by time

---

internal/tools/orchestrator/scheduler/executor/executor.go
internal/tools/orchestrator/scheduler/task/sched.go
pkg/goroutinepool/goroutinepool.go
pkg/goroutinepool/goroutinepool_test.go

fix cluster recreate executor cause goroutine pool panic
| 🇺🇸 English |   fix cluster recreate executor cause goroutine pool panic           |
| 🇨🇳 中文    |        修复集群重新注册导致goroutine 池panic问题      |

fix(orchestrator): cluster recreate executor cause goroutine pool panic

---

build/dockerfiles/Dockerfile-action-agent
internal/tools/pipeline/actionagent/exit.go
internal/tools/pipeline/actionagent/file_watch.go
internal/tools/pipeline/actionagent/file_watch_test.go
internal/tools/pipeline/actionagent/prestop.go

fix agent missing logs when logic quickly
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=385340&iterationID=-1&tab=BUG&type=BUG)
/assign @sfwn 
| 🇺🇸 English |      fix agent missing logs when logic quickly        |
| 🇨🇳 中文    |      修复了agent在任务逻辑太快结束时无法展示日志的问题        |

fix(pipeline): agent missing logs when logic quickly

---

internal/tools/orchestrator/hepa/apipolicy/policies/csrf/dto.go

Adjust web info about mse gateway csrf policy, which will not set  RefreshTTL.
Bugfix： Fix the bug that ... in xxx platform （修复了 xxx 平台的 ...）
| 🇺🇸 English |     Adjust web info about mse gateway csrf policy, allow  not set  RefreshTTL in config    |
| 🇨🇳 中文    |      前端页面适配 MSE csrf 策略，不再支持设置  RefreshTTL，因此后端在其为 MSE 网关的情况想要允许设置为0       |

fix(hepa): mse csrf validate allow RefreshTTL<=0

---

internal/tools/orchestrator/hepa/apipolicy/policies/csrf/policy.go
internal/tools/orchestrator/hepa/apipolicy/policies/sbac/dto.go

Gateway policy csrf and sbac added config for mse not allowed for kong.
/assign @dspo @luobily @sixther-dc 
Bugfix： Fix the bug that gateway policy csrf and sbac added config for mse not allowed for kong（修复了为支持 MSE 网关策略而新增的配置项导致Kong网关校验策略配置失败的问题）
| 🇺🇸 English |      Fix the bug that gateway policy csrf and sbac added config for mse not allowed for kong        |
| 🇨🇳 中文    |       修复了为支持 MSE 网关策略而新增的配置项导致Kong网关校验策略配置失败的问题       |

fix: gateway policy csrf and sbac added config for mse not allowed for kong

---

internal/tools/orchestrator/hepa/services/api_policy/impl/impl.go

…ng  version is 0.14.1
hepa check nginx custom config confliction will case err when kong version is 0.14.1
https://erda.cloud/erda/dop/projects/387/ticket?id=388014&iterationID=-1&type=TICKET
/assign @dspo @luobily 
Bugfix： Fix the bug that hepa check nginx custom config err when kong version is 0.14.1 （修复了 kong 0.14.1 版本 nginx 自定义配置冲突校验 csrf 和 sbac 策略解析报错的问题）
| 🇺🇸 English |    Fix the bug that hepa check nginx custom config err when kong version is 0.14.1    |
| 🇨🇳 中文    |    修复了 kong 0.14.1 版本 nginx 自定义配置冲突校验 csrf 和 sbac 策略解析报错的问题    |

fix: hepa check nginx custom config err when kong version is 0.14.1

---

internal/tools/orchestrator/hepa/services/api_policy/impl/impl.go

Hepa check nginx custom config error when set return, because cors policy have set return 200 default when it enabled。
/assign @dspo @luobily 
Bugfix： Fix the bug that hepa check nginx custom config error when set return（修复了 hepa 检查 nginx 自定义配置 return 语句与 cors 策略默认配置冲突的错误）
| 🇺🇸 English |  Fix the bug that hepa check nginx custom config error when set return   |
| 🇨🇳 中文    |   修复了 hepa 检查 nginx 自定义配置 return 语句与 cors 策略默认配置冲突的错误  |
/cherry-pick release/2.4-beta.1

fix: hepa check nginx custom config error when set return

---

internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/mysql/mysql.go
internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/mysql/mysql_test.go
internal/tools/orchestrator/services/addon/addon_status.go

fix addon mysql missing cluster name label
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=388558&iterationID=1737&tab=BUG&type=BUG)
/assign @sfwn @cxr29 
| 🇺🇸 English |   Fix the bug that addon mysql missing cluster name label            |
| 🇨🇳 中文    |     修复了mysql addon实例缺少集群标签的问题         |

fix(orchestrator): addon mysql missing cluster name label

---

internal/tools/pipeline/providers/build/provider.go

fix failed to clean build cache images due to bundle initialization
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that failed to clean build cache images due to bundle initialization           |
| 🇨🇳 中文    |      修复了缓存镜像gc失败的问题        |

fix(pipeline): failed to clean build cache images due to bundle initialization

---

internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/redis/redis.go

fix redis-operator deploy failure due to arm64-cow-bug
| 🇺🇸 English |   Fix the bug that redis-operator deploy failure due to arm64-cow-bug           |
| 🇨🇳 中文    |    修复了中间件redis在arm环境部署失败的问题          |

fix(orchestrator): redis-operator deploy failure due to arm64-cow-bug

---

go.mod
internal/apps/cmp/component-protocol/components/cmp-dashboard-nodeDetail/yamlFileEditor/render.go
internal/apps/cmp/component-protocol/components/cmp-dashboard-podDetail/yamlFileEditor/render.go
internal/apps/cmp/component-protocol/components/cmp-dashboard-pods/addPodFileEditor/render.go
internal/apps/cmp/component-protocol/components/cmp-dashboard-pods/yamlFileEditor/render.go
internal/apps/cmp/component-protocol/components/cmp-dashboard-workload-detail/yamlFileEditor/render.go
internal/apps/cmp/component-protocol/components/cmp-dashboard-workloads-list/yamlFileEditor/render.go
internal/apps/cmp/steve/predefined/init.go
internal/apps/dop/endpoints/task.go
internal/apps/dop/pipeline/pipelineyml/pipeline.go
internal/apps/dop/providers/publishitem/db/publish_item_version.go
internal/apps/msp/resource/deploy/handlers/generalability/general_ability.go
internal/pkg/extension/db/extension.go
internal/tools/monitor/core/alert/alert-apis/provider.go
pkg/k8s/node/drain/node_test.go
pkg/parser/pipelineyml/pipelineymlv1/gogenerate/builtin_action_spec.go
pkg/parser/pipelineyml/pipelineymlv1/pipelineyml.go
pkg/parser/pipelineyml/pipelineymlv1/taskconfig_decode.go
tools/cli/cmd/extensions_push.go
tools/cli/cmd/extensions_retag.go

The `github.com/ghodss/yaml` package is no longer being actively maintained. `sigs.k8s.io/yaml` is a permanent fork of `github.com/ghodss/yaml`, which is actively maintained by Kubernetes SIG and widely used in K8s projects.
The notable change is that `github.com/ghodss/yaml` uses `gopkg.in/yaml.v2 v2.2.2`, while `sigs.k8s.io/yaml` uses `gopkg.in/yaml.v2 v2.4.0`. You can see the changes between the two versions here: [v2.2.2...v2.4.0](https://github.com/go-yaml/yaml/compare/v2.2.2...v2.4.0), which mostly consists of bug fixes.
/assign @sfwn 
| 🇺🇸 English | Replace unmaintained `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`             |
| 🇨🇳 中文    | 将不再积极维护中的 `github.com/ghodss/yaml` 依赖替换为 `sigs.k8s.io/yaml`             |

chore: replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`

---

internal/tools/orchestrator/hepa/apipolicy/policies/built-in/policy.go
internal/tools/orchestrator/hepa/apipolicy/policies/built-in/policy_test.go
internal/tools/orchestrator/hepa/apipolicy/policies/cors/policy.go
internal/tools/orchestrator/hepa/apipolicy/policies/cors/policy_test.go
internal/tools/orchestrator/hepa/apipolicy/policies/csrf/policy.go
internal/tools/orchestrator/hepa/apipolicy/policies/csrf/policy_test.go
internal/tools/orchestrator/hepa/apipolicy/policies/custom/policy.go
internal/tools/orchestrator/hepa/apipolicy/policies/custom/policy_test.go
internal/tools/orchestrator/hepa/apipolicy/policies/ip/policy.go
internal/tools/orchestrator/hepa/apipolicy/policies/ip/policy_test.go
internal/tools/orchestrator/hepa/apipolicy/policies/proxy/policy.go
internal/tools/orchestrator/hepa/apipolicy/policies/proxy/policy_test.go
internal/tools/orchestrator/hepa/apipolicy/policies/sbac/policy.go
internal/tools/orchestrator/hepa/apipolicy/policies/sbac/policy_test.go
internal/tools/orchestrator/hepa/apipolicy/policies/server-guard/policy.go
internal/tools/orchestrator/hepa/apipolicy/policies/waf/policy.go
internal/tools/orchestrator/hepa/apipolicy/policies/waf/policy_test.go
internal/tools/orchestrator/hepa/apipolicy/policy_engine.go
internal/tools/orchestrator/hepa/gateway-providers/mse/mse_adapter_test.go
internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/mse_key_auth_test.go
internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/mse_para_sign_auth_test.go
internal/tools/orchestrator/hepa/services/api_policy/impl/impl.go
internal/tools/orchestrator/hepa/services/api_policy/impl/impl_test.go
internal/tools/orchestrator/hepa/services/endpoint_api/impl/impl.go

Adapting for Erda API Gateway web call GetPolicy() get default config for policy,  different gateway  provider (mse or kong) need return different config for default。 
/assign @dspo @luobily @sixther-dc 
Bugfix： Fix the bug that different gateway  provider (mse or kong) need return different config for default （修复了前端页面适配网关类型获取不同网关对应的网关策略的默认设置）
| 🇺🇸 English |    Fix the bug that different gateway  provider (mse or kong) need return different config for default   |
| 🇨🇳 中文    |   修复了前端页面适配网关类型获取不同网关对应的网关策略的默认设置  |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-m …

fix: hepa get policy return

---

internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/elasticsearch/elasticsearch.go
internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/redis/redis.go
internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/redis/redis_test.go

fix redis addon deployed by operator missing exporter
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=438836&iterationID=-1&tab=BUG&type=BUG)
/assign @sfwn 
| 🇺🇸 English |  Fix the bug that redis addon deployed by operator missing exporter            |
| 🇨🇳 中文    |     修复了redis通过operator部署后没有exporter的问题         |

fix(orchestrator): redis addon deployed by operator missing exporter

---

internal/core/legacy/conf/conf.go
internal/core/legacy/conf/conf_test.go
internal/core/legacy/dao/audit.go
internal/core/legacy/services/audit/audit.go

change default org audit retention days to 30
| 🇺🇸 English |     Optimize change default org audit retention days to 30         |
| 🇨🇳 中文    |     将企业审计日志默认保留时间调整为30天         |

feat: change default org audit retention days to 30

---

apistructs/iteration.go
apistructs/label.go
internal/apps/dop/dao/iteration.go
internal/apps/dop/dao/iteration_test.go
internal/apps/dop/endpoints/iteration.go
internal/apps/dop/endpoints/iteration_test.go

iteration support label relation
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=455812&iterationID=1841&type=TASK)
/assign @sfwn 
| 🇺🇸 English |   iteration support label relation          |
| 🇨🇳 中文    |      支持迭代与标签进行关联        |

feat(dop): iteration support label relation

---

internal/tools/monitor/core/log/query/log.query.service.go
internal/tools/monitor/core/log/storage/clickhouse/iterator.go

Closing lastResp in defer causes `fetch` func to be executed limit(pageSize) times.
`it.Close()` will be executed outside `fetch` func where the iterator created.
**Updated:**
`it.Close()` can only close lastResp, but will leak lastLastResp, so we should close inside `fetch` func.
| 🇺🇸 English |  closing lastResp in defer causes `fetch` func to be executed limit(pageSize) times            |
| 🇨🇳 中文    |   在 defer 中关闭 lastResp 会导致 `fetch` 函数被执行 limit(pageSize) 次           | …

fix(monitor): closing lastResp in defer causes `fetch` func to be executed limit(pageSize) times

---

internal/apps/msp/apm/log-service/query/log.service.download.go
internal/apps/msp/apm/log-service/query/log.service.go
internal/apps/msp/apm/log-service/query/log.service.histogram.go
internal/apps/msp/apm/log-service/query/log.service.search.go
internal/apps/msp/apm/log-service/query/log.service.terms.go
internal/apps/msp/apm/log-service/query/provider.go
internal/apps/msp/apm/log-service/query/utils.go
internal/apps/msp/apm/log-service/query/utils_test.go

log-service's `startTime` field is set to `time.Now().Nano()`.
So, if msp(erda-server) restart, for example, when you query log about 5 mins ago, log-query-request's `timeStart` field is older than log-service's `startTime`, so we lose some important tags for query, so returned nothing.
And when msp is lived more than 5 mins, the same log-query request will return truly data.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=456067&iterationID=-1&tab=BUG&type=BUG)
/assign @chengjoey @tomatopunk 
| 🇺🇸 English |  remove log-service startTime for msp restart            |
| 🇨🇳 中文    |   log-service 删除 startTime 参数           |
> For details on …

fix: remove log-service startTime for msp restart

---

internal/apps/msp/menu/menu.service.go

fix log-analytics interface not exist
the front end will judge whether the logKey is 'undefined', so the value cannot be set to empty
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that log-analytics interface not exist           |
| 🇨🇳 中文    |      修复了日志分析页面显示不存在的问题        |

fix: log-analytics interface not exist

---

internal/apps/cmp/component-protocol/components/cmp-dashboard-events-list/filter/render.go
internal/apps/cmp/component-protocol/components/cmp-dashboard-pods/addPodFilter/render.go
internal/apps/cmp/component-protocol/components/cmp-dashboard-pods/filter/render.go
internal/apps/cmp/component-protocol/components/cmp-dashboard-pods/filter/render_test.go
internal/apps/cmp/component-protocol/components/cmp-dashboard-workloads-list/addWorkloadFilter/render.go
internal/apps/cmp/component-protocol/components/cmp-dashboard-workloads-list/filter/render.go
internal/apps/cmp/component-protocol/components/cmp-dashboard-workloads-list/filter/render_test.go
internal/apps/cmp/component-protocol/cputil/util.go
internal/apps/cmp/component-protocol/cputil/util_test.go

1. failed to render project namespace on cmp
2. cleanup unuse code
| 🇺🇸 English | failed to render project namespace on cmp             |
| 🇨🇳 中文    |  cmp 渲染项目级 namespace 失败             |

fix: failed to render project namespace on cmp

---

cmd/monitor/monitor/conf/chartview/frontend/page_overview.json

/assign @sfwn 
| 🇺🇸 English |   fix page orderview no order           |
| 🇨🇳 中文    |     修复 page orderview 无序         |

fix: fix page orderview no order

---

internal/tools/orchestrator/conf/conf.go
internal/tools/orchestrator/services/deployment/deployment_context.go
internal/tools/orchestrator/services/deployment/deployment_context_test.go

fix init-container download file failed due to openapi url
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/ticket?id=452723&iterationID=-1&type=TICKET)
/assign @sfwn 
| 🇺🇸 English |  Fix the bug that init-container download file failed due to openapi url            |
| 🇨🇳 中文    |   修复了init-container下载配置失败的问题           |

fix(orchestrator): init-container download file failed due to openapi url

---

internal/tools/pipeline/pipengine/actionexecutor/logic/job.go
internal/tools/pipeline/pipengine/actionexecutor/logic/job_test.go
internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sjob/k8sjob.go

In certain custom DNS hosts scenarios, it may lead to DNS resolution failure.
/assign @sixther-dc @chengjoey @sfwn 
| 🇺🇸 English | fix pipeline job dns policy in host network mode             |
| 🇨🇳 中文    |   修复 hostnetwork 下dns 策略           |

fix:  pipeline job dns policy in host network mode

---

internal/tools/orchestrator/scheduler/executor/plugins/edas/edas.go
internal/tools/orchestrator/scheduler/executor/plugins/edas/edas_test.go

fix  edas application group list error 
| 🇺🇸 English | fix  edas application group list error             |
| 🇨🇳 中文    |   修复edas应用获取失败问题           |

fix: edas application group list error

---

cmd/monitor/monitor/conf/chartview/frontend/ajax_overview.json
cmd/monitor/monitor/conf/chartview/frontend/page_overview.json

fix fronted chart overview wrong timestamp order
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=467820&iterationID=-1&tab=BUG&type=BUG)
/assign @sfwn 
| 🇺🇸 English |  Fix the bug that fronted chart overview wrong timestamp order             |
| 🇨🇳 中文    |   修复了前端监控图表时间轴时间顺序出错的问题           |

fix(monitor): frontend chart overview wrong timestamp order

---

cmd/monitor/monitor/conf/chartview/frontend/domain_overview.json

fix domain overview chart timestamp error
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=472697&iterationID=-1&tab=BUG&type=BUG)
/assign @sfwn 
| 🇺🇸 English | Fix the bug that domain overview chart timestamp error             |
| 🇨🇳 中文    |    修复了访问域名大盘时间轴乱序的问题          |

fix(monitor): domain overview chart timestamp error

---

apistructs/issue.go
cmd/erda-server/bootstrap.yaml
cmd/erda-server/main.go
cmd/monitor/collector/bootstrap.yaml
internal/apps/dop/providers/issue/dao/core.go
internal/apps/dop/providers/issue/dao/issue_relation.go
internal/apps/dop/providers/project_report/cache.go
internal/apps/dop/providers/project_report/calculate.go
internal/apps/dop/providers/project_report/calculate_test.go
internal/apps/dop/providers/project_report/metrics.go
internal/apps/dop/providers/project_report/metrics_test.go
internal/apps/dop/providers/project_report/prometheus.go
internal/apps/dop/providers/project_report/prometheus_test.go
internal/apps/dop/providers/project_report/provider.go
internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/external_metric/external_metrics.go

project delivery management report basic provider
make prometheus collector for iteration
at present, the provider only collector iteration basic metrics for project
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=453638&iterationID=1841&type=TASK)
/assign @sfwn 
| 🇺🇸 English |   Support make project delivery management report basic provider           |
| 🇨🇳 中文    |    实现项目交付报表基础指标采集的provider          | …

feat: make project delivery management report basic provider

---

internal/core/messenger/eventbox/dispatcher/filters/webhookfilter.go
internal/core/messenger/eventbox/dispatcher/filters/webhookfilter_test.go
internal/tools/orchestrator/scheduler/executor/executor.go
internal/tools/orchestrator/scheduler/executor/executortypes/types.go

fix executor goroutine pool empty when update
1. eventbox repeated callback invocation.
2. executor update failed when goroutine already stoped.
| 🇺🇸 English | fix update executor goroutine pool empty              |
| 🇨🇳 中文    |   修复更新 executor gotouine pool 为空问题           |

fix: executor goroutine pool empty when update

---

apistructs/issue.go
apistructs/label.go
apistructs/project.go
bundle/label.go
internal/apps/dop/endpoints/project.go
internal/apps/dop/providers/project_report/calculate.go
internal/apps/dop/providers/project_report/prometheus.go
internal/core/legacy/dao/label_relation.go
internal/core/legacy/endpoints/project.go
pkg/mock/mock.go
pkg/mock/mock_test.go

support for associating project with labels
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=473770&iterationID=1841&type=TASK)
/assign @sfwn 
| 🇺🇸 English |   support for associating project with labels           |
| 🇨🇳 中文    |      支持项目与标签进行关联        |

feat(dop): support for associating project with labels

---

internal/tools/orchestrator/hepa/services/api_policy/impl/impl.go

nginx custom validating support set more add_header
/assign @dspo @luobily @sfwn 
Bugfix： Fix the bug that nginx custom validating not support set more add_header  （修复了 nginx 自定义配置不支持设置多个 add_header 的错误）
| 🇺🇸 English |    Fix the bug that nginx custom validating not support set more add_header      |
| 🇨🇳 中文    |     修复了 nginx 自定义配置不支持设置多个 add_header 的错误       |

fix(hepa): nginx custom validating support set more add_header

---

internal/apps/dop/providers/issue/core/query/issueexcel/model_sample.go

first requirement demo model add TaskOnly&BugOnly fields to ensure excel title order correct
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=502836&iterationID=12560&type=BUG)
| 🇺🇸 English |   first requirement demo model add TaskOnly&BugOnly fields to ensure excel title order correct           |
| 🇨🇳 中文    |   第一个需求 Demo 模型添加 TaskOnly&BugOnly 字段，保证导出的 Excel 标题顺序正确           |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/m …

fix(dop): first requirement model add TaskOnly&BugOnly fields to ensure excel title order correct

---

bundle/testset.go
cmd/erda-server/bootstrap.yaml
internal/pkg/ai-functions/functions/test-case/function.go
internal/pkg/ai-functions/handler/handler_ai_function_create_testcase.go
internal/pkg/ai-functions/handler/handler_ai_function_create_testcase_test.go

AI function create  testcase will create testset if not set testSetID
/assign @sfwn 
Feature: Support ai function create testset if not set testSetID（支持AI function 在测试集 ID 未指定的情况下创建测试集.）
| 🇺🇸 English |    Support ai function create testset if not set testSetID          |
| 🇨🇳 中文    |       支持AI function 在测试集 ID 未指定的情况下创建测试集.       |

feat(ai-function): create testset if not set testSetID

---

internal/pkg/ai-functions/handler/handler_ai_function_create_testcase.go

When call testcase create with  testCaseCreateReq, no need set prompt parameter.
/assign @sfwn 
Bugfix： Fix the bug that  no need validate prompt parameter for ruquirement with testCaseCreateReq parameter （修复了 应用修改完成的测试用例时，无需提供 prompt 的校验逻辑）
| 🇺🇸 English |       Fix the bug that  no need validate prompt parameter for ruquirement with testCaseCreateReq parameter         |
| 🇨🇳 中文    |        修复了 应用修改完成的测试用例时，无需提供 prompt 的校验逻辑      |

fix: ai function validate Params

---

.gitignore
cmd/ai-proxy/bootstrap.yml
cmd/ai-proxy/conf/routes.yml
internal/apps/ai-proxy/common/ctxhelper/config.go
internal/apps/ai-proxy/common/ctxhelper/ctx.go
internal/apps/ai-proxy/common/ctxhelper/logger.go
internal/apps/ai-proxy/config/config.go
internal/apps/ai-proxy/dependent_filters.go
internal/apps/ai-proxy/filters/initial/filter.go
internal/apps/ai-proxy/filters/log-http/filter.go
internal/apps/ai-proxy/filters/message-context/filter.go
internal/apps/ai-proxy/provider.go

- commit reoutes.yaml
- add initial filter to split default OnResponseXXX actions from log-http filter
- refactor config; put config into ctx
| 🇺🇸 English |   refactor ai-proxy: routes & config & initial-filter           |
| 🇨🇳 中文    |   重构 ai-proxy: 路由 & 配置 & 用于初始化的 Filter           |

refactor(ai-proxy): routes & config & initial-filter

---

internal/tools/orchestrator/services/deployment_order/deployment_order_render.go
internal/tools/orchestrator/services/deployment_order/deployment_order_render_test.go

Souce: Erda addon where query conditions are case-insensitive.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=506036&iterationID=-1&type=TASK)
| 🇺🇸 English | fix deployment order custom addon name precheck             |
| 🇨🇳 中文    |   修复部署单自定义 addon 准备就绪名称检查           |

fix(orchestrator): deployment order custom addon name precheck

---

internal/apps/dop/providers/efficiency_measure/calculate.go
internal/apps/dop/providers/efficiency_measure/contributor_query.go
internal/apps/dop/providers/efficiency_measure/efficiency_query.go
internal/apps/dop/providers/efficiency_measure/metric.go
internal/apps/dop/providers/efficiency_measure/provider.go
internal/apps/dop/providers/issue/dao/performance_measure.go

fix some bug metrics should not contain wont fix states
/assign @sfwn 
| 🇺🇸 English |   fix some bug metrics should not contain wont fix states           |
| 🇨🇳 中文    |    修复效能度量缺陷指标包含了无需修复状态的问题          |

fix(dop): some bug metrics should not contain wont fix states

---

internal/core/openapi/openapi-ng/interceptors/csrf/csrf.go
internal/core/openapi/openapi-ng/interceptors/csrf/csrf_test.go

skip validate csrf token for self-addr and same host-port.
See `url.URL.Host`:
```go
Host        string    // host or host:port
```
so we need plus port for host before compare.
| 🇺🇸 English |   skip validate csrf token for self-addr and same host-port           |
| 🇨🇳 中文    |   csrf-token 跳过验证 self-addr 和相同的 host-port           |
Add comment like `/cherry-pick release/2.4` when this PR is merged.

fix(openapi): skip validate csrf token for self-addr and same host-port

---

internal/apps/dop/providers/issue/dao/core.go
internal/apps/dop/providers/project_report/calculate.go
internal/apps/dop/providers/project_report/metrics.go
internal/apps/dop/providers/project_report/query.go

project report support show unfinished assignee ids detail
/assign @sfwn 
| 🇺🇸 English |  project report support show unfinished assignee ids detail            |
| 🇨🇳 中文    |    项目报表支持展示成员详情          |

feat(dop): project report support show unfinished assignee ids detail

---

api/proto/dop/issue/core/core.proto
cmd/erda-server/bootstrap.yaml
cmd/erda-server/conf/i18n/issue-excel.yaml
internal/apps/dop/initialize.go
internal/apps/dop/providers/issue/core/file.go
internal/apps/dop/providers/issue/core/provider.go
internal/apps/dop/providers/issue/core/query/issueexcel/export.go
internal/apps/dop/providers/issue/core/query/issueexcel/import.go
internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_issue/export.go
internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_issue/export_template.go
internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_issue/field.go
internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_issue/import.go
internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_issue/import_old.go
internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_issue/import_vars.go
internal/apps/dop/providers/issue/core/query/issueexcel/vars/data.go
internal/apps/dop/providers/issue/core/query/issueexcel/vars/export_type.go
internal/apps/dop/providers/issue/core/query/issueexcel/vars/i18n.go
internal/apps/dop/providers/issue/core/query/issueexcel/vars/i18n_test.go
internal/apps/dop/providers/issue/core/query/issueexcel/vars/model.go
internal/apps/dop/providers/issue/core/service.go

issue excel title support i18n
| 🇺🇸 English |    issue excel title support i18n          |
| 🇨🇳 中文    |    事项 Excel 标题支持国际化          |

feat(dop): issue excel title support i18n

---

internal/apps/dop/providers/issue/core/provider.go

window.open do not have header, so use query param to get lang
related ui pr: https://github.com/erda-project/erda-ui/pull/3928
| 🇺🇸 English |   window.open do not have header, so use query param to get lang           |
| 🇨🇳 中文    |   window.open 没有 header，因此使用查询参数来获取 lang          |

feat(dop): window.open do not have header, so use query param to get lang

---

internal/apps/dop/component-protocol/components/issue-manage/batchOperationTipModal/model.go
internal/apps/dop/component-protocol/components/issue-manage/batchOperationTipModal/render.go
internal/apps/dop/component-protocol/components/issue-manage/batchOperationTipModal/render_test.go
internal/apps/dop/component-protocol/components/issue-manage/issueTable/model.go
internal/apps/dop/component-protocol/components/issue-manage/issueTable/render.go
internal/apps/dop/component-protocol/components/issue-manage/scenario.go
internal/apps/dop/component-protocol/scenarios/issue-manage.yml

feat:add confirmation button for batch deletion
refactor: Isolate func and model
feat:add confirmation button for batch deletion
- [Erda Cloud Issue Link]()
| 🇺🇸 English |      refactor: Isolate func and model，feat:add confirmation button for batch deletion        |
| 🇨🇳 中文    |       重构，隔离函数与结构体，批量删除-增加确认弹窗    |

refactor: Isolate func and model

---

internal/apps/dop/component-protocol/components/issue-manage/batchOperationTipModal/model.go
internal/apps/dop/component-protocol/components/issue-manage/batchOperationTipModal/render.go
internal/apps/dop/component-protocol/components/issue-manage/batchOperationTipModal/render_test.go
internal/apps/dop/component-protocol/components/issue-manage/issueTable/render.go

refactor: change the use of Transfer to cputil.ObjJSONTransfe
| 🇺🇸 English |      refactor: change the use of Transfer to cputil.ObjJSONTransfe        |
| 🇨🇳 中文    |       将使用Transfer 改为使用 cputil.ObjJSONTransfe       |

refactor: change the use of Transfer to cputil.ObjJSONTransfe

---

internal/apps/msp/resource/deploy/coordinator/coordinator.go
internal/apps/msp/resource/deploy/coordinator/coordinator_test.go

If Erda deploy on Aliyun ACK,  api-gateway addon will use Aliyun MSE Gateway, so no need to deploy  Erda Kong api-gateway depended postgresql addon
Bugfix： Fix the bug that  no need to deploy  Erda Kong api-gateway depended postgresql addon when use Aliyun MSE Gateway（修复了 Erda 平台使用阿里云 MSE 网关的情况下，依然部署了 Kong 网关底层依赖的 postgresql addon 的问题 ）
| 🇺🇸 English |       Bugfix： Fix the bug that  no need to deploy  Erda Kong api-gateway depended postgresql addon when use Aliyun MSE Gateway      |
| 🇨🇳 中文    |        修复了 Erda 平台使用阿里云 MSE 网关的情况下，依然部署了 Kong 网关底层依赖的 postgresql addon 的问题     |

fix: deploy MSE gateway no need deploy pgsql

---

internal/tools/orchestrator/services/addon/addon_deploy.go
internal/tools/orchestrator/services/addon/addon_deploy_test.go

only redis versions greater than 6.0 are deployed using the operator
[reference](https://github.com/spotahome/redis-operator/blob/632aa3da88ee2a28ccb9fc4f571ddcb556dbd713/README.md?plain=1#L11)
/assign @sfwn 
| 🇺🇸 English |    Fix the bug that only redis versions greater than 6.0 are deployed using the operator          |
| 🇨🇳 中文    |    修复了redis低于6.0版本使用operator发布失败的问题          |

fix(orchestrator): only redis versions greater than 6.0 are deployed using the operator

---

internal/apps/ai-proxy/common/ctxhelper/stream.go
internal/apps/ai-proxy/filters/bailian-director/filter.go
internal/apps/ai-proxy/filters/bailian-director/resp.go
internal/apps/ai-proxy/filters/message-context/filter.go
internal/apps/ai-proxy/vars/consts.go

bailian qwenv1 support both stream&non-stream request
- [Erda Cloud Issue Link](https://erda.cloud/terminus/dop/projects/1265/issues/all?id=532809&iterationID=13370&type=TASK)
/assign @wangzhuzhen 
| 🇺🇸 English |   bailian qwenv1 support both stream&non-stream request           |
| 🇨🇳 中文    |  阿里云百炼通义千问模型支持流式和非流式请求            |

feat(ai-proxy): bailian qwenv1 support both stream&non-stream request

---

cmd/monitor/collector/bootstrap-agent.yaml
internal/tools/monitor/oap/collector/lib/util_test.go

pr: #5631 
Name may not necessarily represent the container ID in some distributions.
e.g.
| 🇺🇸 English |   fix collector-agent docker_container_summary modifier processor get container id error           |
| 🇨🇳 中文    |     修复 collector-agent    docker_container_summary modifier processor  获取容器 id 失败问题    |

fix: collector-agent docker_container_summary modifier processor get container id error

---

internal/apps/ai-proxy/filters/bailian-director/filter.go
pkg/http/httputil/mediatype.go

Auto del accept-encoding for bailian lllm.
Test result:
- gzip is not ok
- deflate is ok
- br is ok
| 🇺🇸 English |    auto del accept-encoding for bailian lllm          |
| 🇨🇳 中文    |   百炼大模型自动删除 accept-encoding header           |

feat(ai-proxy): auto del accept-encoding for bailian lllm

---

internal/apps/dop/providers/efficiency_measure/contributor_query.go
internal/apps/dop/providers/efficiency_measure/efficiency_query.go
internal/apps/dop/providers/efficiency_measure/func_points_trend.go
internal/apps/dop/providers/project_report/query.go
internal/apps/dop/providers/project_report/query_test.go
pkg/strutil/convert.go
pkg/strutil/convert_test.go

fix(performance_measure.go):convert ProjectIDs type to []string]
| 🇺🇸 English |     fix(performance_measure.go):convert ProjectIDs type to []string]         |
| 🇨🇳 中文    |        转换 ProjectIDs 为 []string，类型转换     |

fix: convert ProjectIDs type to []string

---

cmd/monitor/collector/bootstrap-agent.yaml
cmd/monitor/collector/bootstrap.yaml

retag component_name from label dice/component
avg component from metrics 
```shell
SELECT toNullable(tag_values[indexOf(tag_keys,'component_name')]) AS "component_name::tag" FROM "monitor"."metrics_all" WHERE (("timestamp" >= fromUnixTimestamp64Nano(cast(1699340010037000000,'Int64'))) AND ("timestamp" < fromUnixTimestamp64Nano(cast(1699350810037000000,'Int64'))) AND (org_name = 'erda-demo') AND ("org_name" IN ('erda-demo', 'erda', '')) AND ("tenant_id" = 'erda-demo') AND ("metric_group" IN ('docker_container_summary'))) GROUP BY "component_name::tag" ORDER BY "component_name::tag" ASC
```
| 🇺🇸 English |  add component name from label …

feat(collector): retag component_name from label dice/component

---

internal/tools/monitor/oap/collector/lib/compressor/writer.go
internal/tools/monitor/oap/collector/lib/compressor/writer_test.go

fix collector exporter compress panic due to index out of range
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=540704&iterationID=-1&tab=BUG&type=BUG)
/assign @sfwn 
| 🇺🇸 English |    Fix the bug that collector exporter compress panic due to index out of range           |
| 🇨🇳 中文    |    修复了collector的exporter由于数组越界造成panic的问题          |

fix(collector): collector exporter compress panic due to index out of range

---

cmd/monitor/monitor/conf/chartview/runtime/runtime-container-detail.json

fix runtime container no metric detail due to container id missing
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=547849&iterationID=-1&tab=BUG&type=BUG)
| 🇺🇸 English |   Fix the bug that runtime container no metric detail due to container id missing           |
| 🇨🇳 中文    |    修复了容器监控指标在丢失containerid时图表无数据的问题          |

fix(monitor): runtime container no metric detail due to container id missing

---

cmd/monitor/monitor/conf/chartview/runtime/runtime-container-detail.json

fix container `mem_limit` value same with machine mem
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=548259&iterationID=12783&tab=BUG&type=BUG)
| 🇺🇸 English |  Fix the bug that container `mem_limit` value same with machine mem            |
| 🇨🇳 中文    |     修复了容器监控的内存限制由于pause容器的原因与机器内存一致的问题         |

fix(monitor): container `mem_limit` value same with machine mem

---

internal/tools/orchestrator/scheduler/executor/plugins/edas/edas_app_flow.go
internal/tools/orchestrator/scheduler/executor/plugins/edas/wrapclient/kubernetes/provider.go
internal/tools/orchestrator/scheduler/executor/plugins/edas/wrapclient/kubernetes/service.go
internal/tools/orchestrator/scheduler/executor/plugins/edas/wrapclient/kubernetes/service_test.go

fix edas update kubernetes service error
will cause
```shell
invalid: metadata.resourceVersion: Invalid value: \"\": must be specified for an update
```
/assign @sfwn 
| 🇺🇸 English |  fix edas update kubernetes service error            |
| 🇨🇳 中文    |    修复 o11 edas 更新 k8s service 错误          |

fix(orchestrator): edas update kubernetes service error

---

apistructs/extension_test.go
apistructs/extention.go
cmd/erda-server/conf/i18n/issue-manage.yaml
cmd/erda-server/conf/i18n/msp-i18n.yaml
internal/tools/pipeline/providers/graph/graph.service.go
internal/tools/pipeline/providers/graph/graph.service_test.go
internal/tools/pipeline/providers/pipeline/detail.go
internal/tools/pipeline/providers/pipeline/interface.go
internal/tools/pipeline/providers/pipeline/provider.go
internal/tools/pipeline/providers/pipeline/task_view.go
internal/tools/pipeline/providers/task/task.service.go

update get language method in `pipeline` and `graph` providers
use `apis.GetLang()` to instaed `i18n.GetGoroutineByLang()` if the ctx has the `lang` value.
because the goroutine will get the repeated goroutineID, then use `goroutine_context.GetContext()` will get the ctx from previous goroutine with the same goroutineID if we have not cleared the ctx while the goroutine ends
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=549197&iterationID=12783&type=BUG)
| 🇺🇸 English |  fix action i18 issue            |
| 🇨🇳 中文    |   修复了action国际化不稳定的问题           | …

fix(pipeline): fix action i18n issue

---

apistructs/addon.go
internal/tools/orchestrator/dbclient/addon_instance.go
internal/tools/orchestrator/endpoints/middleware.go

fix  addon detail show not found instance error
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/ticket?id=547543&iterationID=-1&type=TICKET)
| 🇺🇸 English |   Fix the bug that addon detail show not found instance error           |
| 🇨🇳 中文    |   修复了多云管理平台的addon详情报错的问题           |

fix(orchestrator):  addon detail show not found instance error

---

pkg/excel/multi_sheet.go
pkg/excel/multi_sheet_test.go

set ErrorStyle=information for cell DropList to avoid warning opening by Microsoft-Excel
| 🇺🇸 English |   set ErrorStyle=information for cell DropList to avoid warning opening by Microsoft-Excel           |
| 🇨🇳 中文    |    将单元格DropList的错误样式设置为信息，以避免在Microsoft Excel中打开时出现警告。          |

feat: set ErrorStyle=information for cell DropList to avoid warning opening by Microsoft-Excel

---

internal/tools/orchestrator/hepa/services/endpoint_api/impl/impl.go
internal/tools/orchestrator/hepa/services/openapi_consumer/impl/impl.go
internal/tools/orchestrator/hepa/services/openapi_consumer/interface.go

Fix the bug that when enable skip authorization, meanwhile reset callers. Then 2 acl rules left, leaked.
refers：https://erda.cloud/erda/dop/projects/387/ticket?id=552453&iterationID=-1&type=TICKET
| 🇺🇸 English |  Fix the bug that when enable skip authorization, meanwhile reset callers. Then 2 acl rules left, leaked.   |
| 🇨🇳 中文    |   设置路由跳过鉴权的期间同时重新对调用方授权，两个接口的操作导致 acl rule 泄漏   |

fix(heap): acl rule leak

---

api/proto/dop/projectpipeline/projectpipeline.proto
internal/apps/dop/providers/projectpipeline/project_source.go
internal/apps/dop/providers/projectpipeline/service_impl.go

fix: Ignore pipeline source creation logic if the source already exists when creating a pipeline
Due to the previous issue of duplicate source creation, it is possible for a YAML file to have multiple sources. 
Therefore, validation is required to ensure data integrity. 
In the future, data cleanup will be necessary to solve this issue.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=557235&iterationID=-1&type=BUG)
/assign @sfwn
| 🇺🇸 English | fix: Ignore pipeline source creation logic if the source already exists when creating a pipeline             |
| 🇨🇳 中文    |   修复了创建流水线时，由于之前存在重复source，导致报错：`source it not unique`           |
Add comment like `/cherry-pick release/1.0` …

fix: Ignore pipeline source creation logic if the source already exists when creating a pipeline

---

internal/pkg/ai-functions/functions/test-case/function.go
internal/pkg/ai-functions/functions/test-case/group.go
internal/pkg/ai-functions/provider.go

Optimize prompt for task names only use  task with type dev 
/assign @sfwn 
Optimize task names in prompt only use  task with type dev （优化prompt 中任务名称列表，仅允许使用类型为开发的任务名称）
| 🇺🇸 English |     Optimize task names in prompt only use  task with type dev  |
| 🇨🇳 中文    |     优化prompt 中任务名称列表，仅允许使用类型为开发的任务名称   |
cherry-pick release/2.4

fix: optimal prompt

---

internal/apps/dop/dicehub/release/cron.go
internal/apps/dop/dicehub/release/release.go
internal/apps/dop/dicehub/release/release.service.go
internal/apps/dop/dicehub/release/release_test.go

fix gc deprecated release.
1. The actual execution will be outside of `72h+24h` if the configuration is `72h`.
2. Use diceyml parser instead of yaml parser.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=557339&iterationID=12783&type=TASK)
/assign @sfwn 
| 🇺🇸 English |  fix gc deprecated release        |
| 🇨🇳 中文    |   修复清理过期制品错误          |

fix: gc deprecated release

---

internal/apps/msp/apm/service/view/table/transaction.go

fix transaction table sort by avgDuration failed
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=557586&iterationID=12783&tab=BUG&type=BUG)
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that transaction table sort by avgDuration failed           |
| 🇨🇳 中文    |   修复了http调用查询相应时间表失败的问题           |

fix(monitor): transaction table sort by avgDuration failed

---

internal/apps/ai-proxy/filters/audit-before-llm-director/resp.go
pkg/reverseproxy/reverseproxy.go

- fix stt audit empty responseBody
- set content-type to application/json when filter error
| 🇺🇸 English |   fix ai-proxy stt audit empty responseBody           |
| 🇨🇳 中文    |    修复 ai-proxy STT 审计 responseBody 为空的问题          |

fix(ai-proxy): stt audit empty responseBody

---

internal/tools/gittar/models/note.go
internal/tools/gittar/models/note_test.go

gittar skip find diff section if all line numbers is 0 (e.g. MR_FILE type ai code-review)
| 🇺🇸 English |  gittar skip find diff section if all line numbers is 0 (e.g. MR_FILE type ai code-review)           |
| 🇨🇳 中文    |    当所有 line numbers 均为 0 时，gittar 不再查找 diff section (例如 MR_FILE 类型的 AI 代码审查)         |

fix(gittar): skip find diff section if all line numbers is 0 (e.g. MR_FILE type ai code-review)

---

.erda/migrations/cmdb/requirements.txt

The common pip proxies, such as `Aliyun`, `Tsinghua`, and `CAS`, do not currently support the official version `2.31.0` of requests. 
This will cause the erda migration to fail. To fix this, you can downgrade the requests version to `2.27.1`. 
In the future, it is best to avoid frequent dependency upgrades to avoid this issue.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=556116&iterationID=12783&type=TASK)
/assign @sfwn 
| 🇺🇸 English |  fix migration interrupted due to requests version            |
| 🇨🇳 中文    |      修复 requetes 版本问题导致 migration 中断        |
> For details on the cherry pick process, see the …

fix: migration interrupted due to requests version

---

internal/tools/gittar/models/note.go

- fix: store oldLineTo/newLineTo to data
- feat: restore diff-lines from old-diff-note in one discussion
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=556935&iterationID=12783&tab=BUG&type=BUG)
| 🇺🇸 English |  AI code-review restore diff-lines from old-diff-note in one discussion            |
| 🇨🇳 中文    |   AI 代码审查从同一个会话中恢复 diff-lines            |
Add comment like `/cherry-pick release/2.4-beta.5` when this PR is merged.

fix(gittar): AI code-review restore diff-lines from old-diff-note in one discussion

---

internal/tools/orchestrator/hepa/repository/service/gateway_upstream_api_service.go

optimize the sql statement to get the last api id
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=558817&iterationID=12783&tab=TASK&type=TASK)
/assign @sfwn @wangzhuzhen 
| 🇺🇸 English | optimize the sql statement to get the last api id             |
| 🇨🇳 中文    |   优化了hepa获取last apiid的sql语句           |

perf(orchestrator): optimize the sql statement to get the last api id

---

internal/tools/orchestrator/scheduler/executor/plugins/edas/wrapclient/edas/app.client.go

The EDAS list application utilizes the fuzzy matching technique, which distinguishes it from the anticipated approach.
Currently EDAS does not support getting by the get `application name`.
e.g. `go-demo` will get multi response.
/assign @sfwn 
| 🇺🇸 English | fix edas list application multi response error              |
| 🇨🇳 中文    |     修复 edas 获取应用多返回错误        | …

fix(orchestrator): edas list application multi response error

---

internal/tools/orchestrator/hepa/services/org_client/impl/impl.go

fix hepa `EOF` due to client not found
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=558468&iterationID=12783&tab=BUG&type=BUG)
/assign @sfwn @wangzhuzhen 
| 🇺🇸 English |    Fix the bug that hepa `EOF` due to client not found          |
| 🇨🇳 中文    |    修复了不存在的client导致hepa EOF的问题          |

fix(hepa): hepa `EOF` due to client not found

---

pkg/parser/diceyml/diceyml.go
pkg/parser/diceyml/diceyml_test.go
pkg/parser/diceyml/errors.go
pkg/parser/diceyml/fieldname_validate_visitor.go
pkg/parser/diceyml/fieldname_validate_visitor_test.go

1. fix resolve panic when parsing invalid data in diceyml.
2. add friendly tips when provided invalid data.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/ticket?id=559389&iterationID=-1&type=TICKET)
/assign @sfwn 
| 🇺🇸 English | fix resolve panic when parsing invalid data in diceyml             |
| 🇨🇳 中文    |    修复错误数据解析 diceyml 导致的 panic 问题          |

fix(parser): resolve panic when parsing invalid data in diceyml

---

internal/tools/orchestrator/services/addon/addon_extension_cache.go
internal/tools/orchestrator/services/addon/addon_extension_cache_test.go
internal/tools/orchestrator/services/addon/addon_test.go

Fix o11 addon cache without default version
There's only one version, set it as the default version.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=562503&iterationID=12783&type=BUG)
/assign @sfwn @CeerDecy 
| 🇺🇸 English |  fix o11 addon cache custom addon without default version            |
| 🇨🇳 中文    |    修复 o11 自定义 addon 缓存没有默认版本          |

fix(orchestrator): addon cache custom addon without default version

---

internal/pkg/ai-functions/functions/test-case/group.go
internal/pkg/ai-functions/handler/utils/handler_function_utils.go
internal/pkg/ai-functions/sdk/api.go
internal/pkg/ai-functions/sdk/api_test.go

Adjust ai-proxy source and email plaintext
/assign @sfwn 
Bugfix： Fix the bug that define ai-proxy source and get email plaintext （修复了对接 ai-proxy 的 source 调整以及 email 脱敏）
| 🇺🇸 English |        Fix the bug that define ai-proxy source and get email plaintext       |
| 🇨🇳 中文    |      修复了对接 ai-proxy 的 source 调整以及 email 脱敏     |

fix: adjust ai-proxy source and email plaintext

---

internal/tools/gittar/ai/cr/util/aiutil/invoke.go
internal/tools/gittar/conf/conf.go

ai-mr-cr source add `___${cluster_name}` suffix, to distinguish invoker cluster.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=562371&iterationID=12783&type=TASK)
| 🇺🇸 English |    ai-mr-cr source add `___${cluster_name}` suffix, to distinguish invoker cluster.          |
| 🇨🇳 中文    |    ai 代码审查 source 添加 `___$cluster_name}` 后缀，用来区分调用者集群          |
Add comment like `/cherry-pick release/2.4-beta.5` when this PR is merged.

feat(gittar): ai-mr-cr source add `___${cluster_name}` suffix

---

internal/tools/gittar/ai/cr/impl/cr_mr_file/file.go
internal/tools/gittar/ai/cr/impl/cr_mr_file/prompt.yaml

add content truncated flag to file code-review prompt
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=563983&iterationID=12783&type=BUG)
| 🇺🇸 English |     add content truncated flag to file code-review prompt         |
| 🇨🇳 中文    |    将内容截断标志添加到文件代码审查提示中          |
Add comment like `/cherry-pick release/2.4-beta.5` when this PR is merged.

fix(gittar): add content truncated flag to file code-review prompt

---

internal/tools/pipeline/pkg/taskerror/ordered.go
internal/tools/pipeline/pkg/taskerror/ordered_test.go
internal/tools/pipeline/providers/reconciler/provider.go
internal/tools/pipeline/providers/reconciler/task_reconciler.go

task reconciler reties and appends errors continuously, leading to memory growth if the error not resolved(will cause oom).
existing mechanism of merging errors is to compare with the last err, but fails with cycling difference err will ignore this mechanism, so it needs adjustment
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=550206&iterationID=12783&type=TASK)
/assign @sfwn 
| 🇺🇸 English |   fix constant appending of errors when task reconciler causing oom          |
| 🇨🇳 中文    |    修复了task调度时错误不断追加导致OOM的问题           | …

fix: constant appending of errors causing oom

---

go.mod
go.sum

bump erda-infra version for gohook
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=549269&iterationID=12783&type=BUG)
| 🇺🇸 English |   bump erda-infra version for gohook           |
| 🇨🇳 中文    |   升级 erda-infra 版本以适应 gohook          |

chore: bump erda-infra version for gohook

---

internal/tools/orchestrator/hepa/providers/micro_api/service.go

POST /api/gateway/api  to add api will fail due ignore parameter consumerId
- [【0124答疑】中海油微服务API添加异常](https://erda.cloud/erda/dop/projects/387/ticket?id=565857&iterationID=-1&type=TICKET)
Bugfix： Fix the bug that POST /api/gateway/api to add api will fail due ignore parameter consumerId in hepa（修复了 微服务API管理页面手动 添加服务API 失败报错 参数不能为空的问题（因 consumerId 参数在处理过程中被忽略））
| 🇺🇸 English |      Fix the bug that POST /api/gateway/api to add api will fail due ignore parameter consumerId in hepa        |
| 🇨🇳 中文    |     修复了 微服务API管理页面手动 添加服务API 失败报错 参数不能为空的问题（因 consumerId 参数在处理过程中被忽略）    |

fix(hepa): add api failed due to lost consumerId

---

build/scripts/docker_image.sh

Remove arch path in single image build.
Build a single-architecture image without the need for an additional layer of identification; this approach may be utilized in the development environment. For multi-architecture scenarios, utilize `buildx`.
/assign @sfwn 
| 🇺🇸 English |  remove arch path in single image build            |
| 🇨🇳 中文    |     单架构构建移除 arch 路径         | …

chore: remove arch path in single image build

---

internal/pkg/extension/db/extension.go
internal/pkg/extension/extension.service.go
internal/pkg/extension/extension.service_test.go

Addressed the inconsistency in public status that could lead to inconsistent overrides across multiple versions.
After the fix, determine whether it is public based on the current version and existing versions.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=568294&iterationID=12783&pId=0&type=BUG)
| 🇺🇸 English |  fix public push exception for the extension            |
| 🇨🇳 中文    |     修复extesion public 推送异常         | …

fix(dicehub): public field  push exception for the extension

---

go.mod
go.sum

bump erda-infra version for gohook
see: #6248 
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=549269&iterationID=12783&type=BUG)
| 🇺🇸 English |   bump erda-infra version for gohook           |
| 🇨🇳 中文    |    升级 erda-infra 版本以适应 gohook          |

chore: bump erda-infra version for gohook [release/2.4-beta.5]

---

internal/tools/monitor/core/metric/query/es-tsql/influxql/ckFunctions.go
internal/tools/monitor/core/metric/query/es-tsql/influxql/ckFunctions_test.go
internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go

let the logic of max func be consistent with min, if not existing it is null
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=568386&iterationID=12783&tab=ALL&type=BUG)
/assign @sfwn 
| 🇺🇸 English |  Fix the bug that  let the logic of max func be consistent with min, if not existing it is null             |
| 🇨🇳 中文    |   修复了ck函数解析时max聚合函数的逻辑与min不一致的问题           |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/C …

fix(monitor): let the logic of max func be consistent with min, if not existing it is null

---

internal/apps/msp/apm/service/components/resources-container-monitor/container/provider.go

use `container_spec_memory_limit_bytes` as container memory limit metric source
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=568840&iterationID=12783&tab=ALL&type=BUG)
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that contianer memory limit metirc incorrect           |
| 🇨🇳 中文    |      修复了容器监控的内存限制变为主机内存的问题        |

fix: use `container_spec_memory_limit_bytes` as container memory limit metric source

---

internal/tools/monitor/core/settings/monitor.go

fix failed to parse log ttl duration
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=569014&iterationID=12783&tab=ALL&type=BUG)
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that failed to parse log ttl duration           |
| 🇨🇳 中文    |      修复了monitor解析log_ttl环境变量失败        |

fix(monitor): failed to parse log ttl duration

---

api/proto/dop/issue/core/core.proto
internal/apps/dop/providers/issue/core/file.go
internal/apps/dop/providers/issue/core/property.go
internal/apps/dop/providers/issue/core/query/convert.go
internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_customfield/import.go
internal/apps/dop/providers/issue/core/query/property.go
internal/apps/dop/providers/issue/dao/issue_property.go
internal/apps/dop/providers/issue/dao/issue_test.go

feat: project level enterprise level duplicate name coverage
feat: Double name verification sinking
fix: optimize code — project level enterprise level duplicate name coverage
feat: project level enterprise level duplicate name coverage
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=561569&iterationID=12783&type=TASK)
/assign @chengjoey @sfwn @chengjoey  @sfwn 
| 🇺🇸 English |       feat: project level enterprise level duplicate name coverage       |
| 🇨🇳 中文    |       项目级事项自定义字段，优先级相关代码，重名覆盖，重名下沉       | …

feat: project level enterprise level duplicate name coverage

---

internal/apps/dop/component-protocol/components/issue-manage/batchOperationTipModal/model.go
internal/apps/dop/component-protocol/components/issue-manage/batchOperationTipModal/render.go
internal/apps/dop/endpoints/endpoints.go
internal/apps/dop/endpoints/iteration.go
internal/apps/dop/initialize.go
internal/apps/dop/providers/issue/core/service.go
internal/apps/dop/providers/issue/dao/core.go
internal/apps/dop/services/iteration/iteration.go

refactor: delete iterations and their sub items together
feat: initialize issueService
refactor: delete iterations and their sub items together
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/iteration/12783/all?id=502433&iterationID=12783&type=REQUIREMENT)
/assign @chengjoey @sfwn @luobily 
| 🇺🇸 English |      refactor: delete iterations and their sub items together        |
| 🇨🇳 中文    |      【项目协同】删除迭代支持选择确认删除迭代中所有事项并删除迭代        | …

refactor: delete iterations and their sub items together

---

api/proto/core/pipeline/pipeline/pipeline.proto
apistructs/pipeline.go
internal/tools/pipeline/dbclient/op_pipeline.go
internal/tools/pipeline/dbclient/op_pipeline_definition.go
internal/tools/pipeline/providers/dbgc/dbgc.go
internal/tools/pipeline/providers/dbgc/dbgc_test.go
pkg/strutil/example_slice_test.go
pkg/strutil/slice.go
pkg/strutil/slice_test.go

The dbgc in the pipeline has two issues. 
- One is that some invalid data fails to parse, causing the gc process fail
- The other is that data bound to a definition is skipped in the GC process
This PR modified the logic of dbgc for pipeline records bound to a definition. Now, only the pipeline record associated with the last execution of the definition is retained, and all other records that meet the GC conditions will cleaned up.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=557257&iterationID=-1&type=BUG)
/assign @sfwn 
| 🇺🇸 English | fix pipeline dbgc             |
| 🇨🇳 中文    |  修复了流水线 dbgc 失效的问题           |
Add comment like `/cherry-pick release/1.0` when this PR is …

fix: fix pipeline dbgc

---

internal/tools/orchestrator/services/addon/addon_deploy.go
internal/tools/orchestrator/services/addon/addon_status.go

pass elasticsearch spec nodes to plugin
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=571886&iterationID=-1&tab=ALL&type=TASK)
/assign @sfwn 
| 🇺🇸 English |  pass elasticsearch spec nodes to plugin            |
| 🇨🇳 中文    |    传递es的正确副本数给operator插件          |

feat(orchestrator): pass elasticsearch spec nodes to plugin

---

internal/apps/dop/providers/issue/dao/issue_property.go
internal/apps/dop/providers/issue/dao/issue_test.go

refactor: refactor NameConflict func
refactor: refactor NameConflict func
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=571895&iterationID=12783&type=BUG)
| 🇺🇸 English |         refactor: refactor NameConflict func     |
| 🇨🇳 中文    |        修复重名覆盖函数导致的数据查询不到问题      |

refactor: refactor NameConflict func

---

go.mod
go.sum
internal/tools/pipeline/providers/cron/db/define_test.go
internal/tools/pipeline/providers/dbgc/definition_cleanup/definition_cleanup_test.go
internal/tools/pipeline/providers/definition/db/define_test.go

In unit tests, SQLite3 might cause a 'disk I/O error'. Therefore, to avoid this situation, set the journal_mode to memory
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=572723&iterationID=-1&type=BUG)
/assign @sfwn 
| 🇺🇸 English | fix: set the journal mode to memory in SQLite3             |
| 🇨🇳 中文    | 设置单测中sqlite3的日志模式为内存模式             |

fix: set the journal mode to memory in SQLite3

---

apistructs/notify_group.go
apistructs/notify_group_test.go
internal/core/legacy/services/notify/notify_group.go
internal/core/messenger/notifygroup/group.service.go

fix failed to get notify detail due to msp_env scope type
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=572035&iterationID=12783&tab=ALL&type=BUG)
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that failed to get notify detail due to msp_env scope type           |
| 🇨🇳 中文    |    修复了微服务治理中查询告警通知详情失败的问题          |

fix(msp): failed to get notify detail due to msp_env scope type

---

internal/tools/pipeline/providers/definition/db/define.go
internal/tools/pipeline/providers/definition/db/define_test.go

In the newer version of xorm, when using limit(0), the value of 0 is not ignored and will be appended as "LIMIT 0" in the sql. Therefore, special handling is required for cases where the value is 0.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=573578&iterationID=-1&type=BUG)
/assign @sfwn 
| 🇺🇸 English |  fix: fix xorm limit(0)            |
| 🇨🇳 中文    |  修复xorm limit(0)导致查无数据的问题            | …

fix: fix issue with xorm limit(0) causing no data retrieval

---

go.mod
go.sum
internal/tools/pipeline/dbclient/op_pipeline_task_test.go
internal/tools/pipeline/providers/cron/db/define_test.go
internal/tools/pipeline/providers/dbgc/definition_cleanup/definition_cleanup_test.go
internal/tools/pipeline/providers/definition/db/define_test.go

The same file name might cause a panic, as the db file from a previous test may not have been deleted properly.
The subsequent test reuses the previous db file, leading to its test results being impacted by the previous test.
Therefore, we adopt random naming here to avoid interference between them
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=574330&iterationID=-1&type=BUG)
/assign @sfwn 
| 🇺🇸 English |   feat: add random name for sqlite3 file           |
| 🇨🇳 中文    |   新增sqlite3创建数据库时的随机命名           | …

feat: add random name for sqlite3 file

---

internal/apps/msp/tenant/db/tenant.go
internal/apps/msp/tenant/project/project.service.go

fix microservice failed to find cluster name
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=580816&iterationID=12783&tab=BUG&type=BUG)
/assign @sfwn 
| 🇺🇸 English |  Fix the bug that microservice failed to find cluster name            |
| 🇨🇳 中文    |     修复了新项目进入微服务监控报错         |

fix(msp): microservice failed to find cluster name

---

internal/tools/monitor/core/metric/query/es-tsql/influxql/ckFunctions.go
internal/tools/monitor/core/metric/query/es-tsql/influxql/ckFunctions_test.go

fix disk blk_read_bytes being negative due to `diffps`
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=581160&iterationID=12783&tab=BUG&type=BUG)
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that disk blk_read_bytes being negative due to `diffps`           |
| 🇨🇳 中文    |      修复了容器监控磁盘读写为负数的问题        |

fix(monitor):  disk blk_read_bytes being negative due to `diffps`

---

internal/tools/orchestrator/hepa/apipolicy/policies/proxy/policy.go
internal/tools/orchestrator/hepa/config/config.go
internal/tools/orchestrator/hepa/provider.go

feat  api proxy host pass-through set default as true
/assign @luobily @wangzhuzhen 
| 🇺🇸 English |  api proxy host pass-through set default as true            |
| 🇨🇳 中文    |     网关默认host透传设置开启         |

feat(hepa): api proxy host pass-through set default as true

---

.github/workflows/ci-it.yml
internal/tools/monitor/core/log/query/log.query.service.go
internal/tools/monitor/core/log/query/log.query.service_test.go
internal/tools/monitor/core/log/query/routes.go

add `erda` orgName in selector when download logs
/assign @sfwn 
| 🇺🇸 English |   Support add `erda` orgName in selector when download logs           |
| 🇨🇳 中文    |     下载日志时默认增加查询erda组织         |

feat(monitor): add `erda` orgName in selector when download logs

---

conf/openapi/openapi.yaml
modules/core/openapi-ng/interceptors/csrf/csrf.go

manual cherry-pick of #6343 support set some http cookie security configuration
/assign @sfwn 
| 🇺🇸 English |    Fix the bug that support set some http cookie security configuration           |
| 🇨🇳 中文    |   手动cherry-pick，支持http cookie的配置           |

fix: manual cherry-pick of #6343 support set some http cookie security configuration

---

cmd/erda-server/bootstrap.yaml
internal/core/openapi/openapi-ng/auth/uc-session/login.go
internal/core/openapi/openapi-ng/auth/uc-session/provider.go

support setting uc openapi session
/assign @sfwn 
| 🇺🇸 English |   support setting uc openapi session           |
| 🇨🇳 中文    |     支持uc openapisession的配置         |

feat: support setting uc openapi session

---

conf/openapi/openapi.yaml
modules/core/openapi-ng/auth/uc-session/login.go
modules/core/openapi-ng/auth/uc-session/provider.go

manual cherry-pick of #6347
support setting uc openapi session
/assign @sfwn 
| 🇺🇸 English |  support setting uc openapi session            |
| 🇨🇳 中文    |   支持uc openapi session配置           |

hotfix: manual cherry-pick of #6347

---

cmd/erda-server/bootstrap.yaml

fix unknown unit 'd' in duration
/assign @sfwn 
| 🇺🇸 English | Fix the bug that unknown unit 'd' in duration             |
| 🇨🇳 中文    |    修复了默认cookie过期时间的单位问题          |

fix(openapi): unknown unit 'd' in duration

---

internal/tools/pipeline/actionagent/execute.go
internal/tools/pipeline/actionagent/exit.go

fix  the agent is stuck in the waiting logs done due to prepare failure
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=592755&iterationID=12783&type=BUG)
/assign @sfwn 
| 🇺🇸 English |    Fix the bug that the agent is stuck in the waiting logs done due to prepare failure           |
| 🇨🇳 中文    |   修复了agent在prepare失败时卡在等待结束标志的问题           |

fix(pipeline):  the agent is stuck in the waiting logs done due to prepare failure

---

cmd/monitor/monitor/conf/alert/rules/addon/addon_elasticsearch_cpu/analyzer_expression.json
cmd/monitor/monitor/conf/alert/rules/addon/addon_elasticsearch_mem/analyzer_expression.json
cmd/monitor/monitor/conf/alert/rules/addon/addon_mysql_cpu/analyzer_expression.json
cmd/monitor/monitor/conf/alert/rules/addon/addon_mysql_mem/analyzer_expression.json
cmd/monitor/monitor/conf/alert/rules/addon/addon_mysql_slave_status/analyzer_expression.json
cmd/monitor/monitor/conf/alert/rules/addon/addon_redis_mem/analyzer_expression.json
internal/tools/monitor/core/alert/alert-apis/adapt/expression.go

Fix addon alert cross workspace.
Cause of the bug: Addon metrics only use `org_name` and  `addon_type` for filtering，and lack a namespace filter such as `terminus_key`、`tk` or `workspace`.
Addon metric event doesn't carry `terminus_key` as well as current MSP project workspace is capital-letters.
The existed operator can't support filter string which case-sensitive, so we introduced a new filter operator -`ieq` .
Result verification: 
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=589326&iterationID=13633&type=BUG)
/assign @sfwn 
| 🇺🇸 English |   fix addon alert cross workspace           |
| 🇨🇳 中文    |        修复 addon 告警跨环境问题      |
Add comment like `/cherry-pick release/1.0` …

fix(monitor): addon alert cross workspace

---

internal/apps/cmp/dbclient/records.go

```shell
(/go/src/github.com/erda-project/erda/internal/apps/cmp/dbclient/records.go:112) 
[2024-05-27 18:10:57]  Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '%d second) AND (status in (?,?)) AND (record_type in (?,?,?,?)) ORDER BY created' at line 1 
ERRO[2024-05-27 18:10:57.727492874] get create cluster record failed, error: Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '%d second) AND (status in (?,?)) AND (record_type in (?,?,?,?)) ORDER BY created' at line 1 
```
/assign @sfwn @CeerDecy 
| …

fix(cmp): dbclient sql build error

---

.erda/pipelines/ci-build-ce.yml
.erda/pipelines/ci-deploy.yml
.github/workflows/ci-it.yml
Makefile
build/dockerfiles/base/Dockerfile
build/dockerfiles/base/deploy.sh
build/dockerfiles/base/sbom-amd64.txt
build/dockerfiles/base/sbom-arm64.txt
build/scripts/buildkit_image.sh
build/scripts/docker_image.sh
pipeline.yml

update git version to avoid [CVE-2024-32002](https://nvd.nist.gov/vuln/detail/CVE-2024-32002).
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=602511&iterationID=-1&type=TASK)
| 🇺🇸 English |   update git version to avoid CVE-2024-32002           |
| 🇨🇳 中文    |   升级 git 版本以避免 CVE-2024-32002           |

chore(gittar): update git version to avoid CVE-2024-32002

---

.erda/pipelines/ci-build-ce.yml
.erda/pipelines/ci-deploy.yml
.github/workflows/ci-it.yml
Makefile
build/dockerfiles/base/Dockerfile
build/dockerfiles/base/sbom-amd64.txt
build/dockerfiles/base/sbom-arm64.txt
build/scripts/buildkit_image.sh
build/scripts/docker_image.sh
pipeline.yml

set safe.directory at Dockerfile side to prevent "dubious ownership" errors
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=604917&iterationID=12783&tab=ALL&type=TASK)
| 🇺🇸 English |    fix github ci: set safe.directory at Dockerfile side to prevent "dubious ownership" errors          |
| 🇨🇳 中文    |   修复 github ci: 在 Dockerfile 侧设置 safe.directory 来避免 "dubious ownership" 错误          |

fix(gh-ci):  set safe.directory at Dockerfile side to prevent "dubious ownership" errors

---

build/dockerfiles/base/Dockerfile

use `--system` instead of `--global` to make it work for all users
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=604917&iterationID=12783&tab=ALL&type=TASK)
| 🇺🇸 English | use `--system` instead of `--global` to make it work for all users to prevent "dubious ownership" error          |
| 🇨🇳 中文    |  使用 `--system` 而不是 `--global` 使所有用户生效，来避免 "dubious ownership" 错误           |

fix(gh-ci): use `--system` instead of `--global` to make it work for all users

---

internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/external_metric/external_metrics.go
internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/log/log.go
internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/metric/metric.go
internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/profile/profile.go
internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/span/span.go

return the connection to the pool after `PrepareBatch`
see [detail](https://github.com/ClickHouse/clickhouse-go/blob/8ad6ec6b95d8b0c96d00115bc2d69ff13083f94b/README.md?plain=1#L289-L293)
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that streaming missing connection when batch write data           |
| 🇨🇳 中文    |     修复了streaming消费数据时链接耗尽的问题         |

fix(streaming): return the connection to the pool after `PrepareBatch`

---

cmd/monitor/collector/bootstrap-agent.yaml
internal/tools/monitor/oap/collector/plugins/all/all.go
internal/tools/monitor/oap/collector/plugins/processors/dropper/provider.go

add `dropper` provider for application metric
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=605800&iterationID=12783&type=TASK)
| 🇺🇸 English |  Support add `dropper` provider for application metric            |
| 🇨🇳 中文    |  collector实现可以丢弃不需要的指标            |

feat(collector): add `dropper` provider for application metric

---

internal/apps/msp/apm/service/view/table/transaction.go

fix `transaction-http-analysis` failed to order by avgDuration
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=567488&iterationID=12783&tab=BUG&type=BUG)
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that `transaction-http-analysis` failed to order by avgDuration           |
| 🇨🇳 中文    |     修复了http监控按平均相应时间排序失败的问题         |

fix: `transaction-http-analysis` failed to order by avgDuration

---

internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sflink/util.go

fix pipeline taskOP `queue` panic due to nil flink taskManager status
/assign @sfwn 
| 🇺🇸 English |  Fix the bug that pipeline taskOP `queue` panic due to nil flink taskManager status            |
| 🇨🇳 中文    |      修复了由于升级flink导致状态空指针的问题        |

fix(pipeline): pipeline taskOP `queue` panic due to nil flink taskManager status

---

.github/prlint.json
go.mod

fix go mod, no need `go mod vendor` anymore.
| 🇺🇸 English |   go.mod: add missing deps in replace part           |
| 🇨🇳 中文    |    go.mod: 在 replace 部分增加缺失的依赖          |

fix(go.mod): add missing deps in replace part

---

internal/tools/monitor/oap/collector/lib/protoparser/spotlog/spotlog.go
internal/tools/monitor/oap/collector/plugins/receivers/kafka/provider.go

add offset and partition id for log record
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=611023&iterationID=12783&tab=BUG&type=BUG)
/assign @sfwn 
| 🇺🇸 English |  Support add offset and partition id for log record            |
| 🇨🇳 中文    |   streaming消费日志时为记录加上offset和partitionid           |

feat(streaming): add offset and partition id for log record

---

.erda/migrations/pipeline/20240702-runner-scheduler-add-orgid.sql
api/proto/core/pipeline/action_runner_scheduler/runner_task.proto
apistructs/runner_task.go
cmd/action-runner/build.sh
cmd/action-runner/config.json
cmd/action-runner/main.go
internal/tools/pipeline/action-runner/apis.go
internal/tools/pipeline/action-runner/conf.go
internal/tools/pipeline/providers/action_runner_scheduler/db/runner_task.go
internal/tools/pipeline/providers/action_runner_scheduler/runner.task.service.go

ios app build support dispatching runner task by org id.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=610827&iterationID=12783&type=REQUIREMENT)
| 🇺🇸 English |   ios app build supports dispatching runner task by org id          |
| 🇨🇳 中文    |   ios 应用打包支持按企业维度下发任务           |

feat(ios-build): dispatch runner task by org id

---

go.mod
go.sum
internal/apps/ai-proxy/filters/dashscope-director/sdk/converter.go
internal/apps/ai-proxy/filters/dashscope-director/sdk/resp.go

Add chat completion usage for dashscope director.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=612128&iterationID=12783&type=TASK)
| 🇺🇸 English |   ai-proxy add chat completion usage for dashscope director           |
| 🇨🇳 中文    |   ai-proxy 为 dashscope director 增加 chat completion usage           |

feat(ai-proxy): add chat completion usage for dashscope director

---

internal/tools/orchestrator/scheduler/instanceinfo/pod.go

orchestrator get pods use precompiled sql to avoid sql injection
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=611655&iterationID=-1&type=BUG)
| 🇺🇸 English |   orchestrator get pods use precompiled sql to avoid sql injection           |
| 🇨🇳 中文    |   orchestrator get pods 使用预编译 sql 来避免 sql 注入           |

fix(orchestrator): use precompiled sql to avoid sql injection

---

Makefile
build/dockerfiles/Dockerfile
build/dockerfiles/Dockerfile-action-agent
build/dockerfiles/Dockerfile-cluster-ops
build/dockerfiles/Dockerfile-volume-provisioner
build/dockerfiles/agent-injector/Dockerfile
build/dockerfiles/base/Dockerfile
build/dockerfiles/cli/Dockerfile
build/dockerfiles/cluster-agent/Dockerfile
build/dockerfiles/reportengine/Dockerfile
build/scripts/buildkit_image.sh
pipeline.yml

set docker syntax using erda registry
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=612943&iterationID=12783&tab=BUG&type=BUG)
/assign @sfwn 
| 🇺🇸 English |  set docker syntax using erda registry            |
| 🇨🇳 中文    |    更改默认dockerfile的syntax          |

chore: set docker syntax using erda registry

---

internal/tools/orchestrator/scheduler/executor/plugins/k8s/instanceinfosync/pod.go
internal/tools/orchestrator/scheduler/instanceinfo/pod.go

Reader `values` doesn't reset, will cause where condition error.
Delete history duplicate data with cluster and pod uid when pod event is delete.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=615876&iterationID=12783&type=TASK)
/assign @sfwn
| 🇺🇸 English |   fix pod info sync duplicate          |
| 🇨🇳 中文    |  修复 pod 数据同步重复            |

fix(orchestrator): pod info sync duplicate

---

cmd/monitor/monitor/bootstrap.yaml
internal/tools/monitor/core/settings/provider.go
internal/tools/monitor/core/settings/sync_config.go
internal/tools/monitor/oap/collector/lib/const.go

auto create monitor default ttl config for orgs
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=570198&iterationID=-1&tab=ALL&type=TASK)
/assign @sfwn 
| 🇺🇸 English |    Support auto create monitor default ttl config for orgs          |
| 🇨🇳 中文    |    实现为组织自动创建默认的monitor ttl记录          |

feat(monitor): auto create monitor default ttl config for orgs

---

go.mod
go.sum

owngrade pyroscope-go client to avoid useless `session-id` tag
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=617784&iterationID=12783&tab=BUG&type=BUG)
/assign @sfwn 
| 🇺🇸 English |  Fix the bug that downgrade pyroscope-go client to avoid useless `session-id` tag            |
| 🇨🇳 中文    |   修复了erda-server等服务由于多了session导致持续性观测数据丢失的问题           |

fix(monitor): downgrade pyroscope-go client to avoid useless `session-id` tag

---

.github/workflows/ci-it-noneed.yml
.github/workflows/ci-it.yml
internal/apps/ai-proxy/common/on.go
pkg/strutil/json_test.go

Use codecov/codecov-action@v4 instead of bash script to upload codecov reports.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=585546&iterationID=12783&type=TASK)
| 🇺🇸 English |   use codecov-action@v4 to upload codecov reports           |
| 🇨🇳 中文    |    使用 codecov-action@v4 上传 codecov 报告         |

fix(codecov): use codecov/codecov-action@v4 instead of bash script

---

Makefile
build/dockerfiles/Dockerfile
build/scripts/docker_image.sh

Fully use `docker buildx build`.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=618622&iterationID=12783&type=TASK)
| 🇺🇸 English |  build image fully use `docker buildx build`            |
| 🇨🇳 中文    |   制作镜像全面使用 `docker buildx build`           |

chore(build): fully use `docker buildx build`

---

internal/apps/msp/apm/service/components/resources-container-monitor/container/provider.go

fix cpu usage in resource-container-monitor
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=619713&iterationID=12783&tab=BUG&type=BUG)
/assign @sfwn 
| 🇺🇸 English |    Fix the bug that cpu usage in resource-container-monitor          |
| 🇨🇳 中文    |  修复了微服务容器监控cpu使用率错误的问题            |

fix(monitor):  cpu usage in resource-container-monitor

---

cmd/erda-server/bootstrap.yaml
internal/apps/cmp/endpoints/endpoints.go
internal/apps/cmp/initialize.go
internal/apps/cmp/provider.go
internal/apps/cmp/steve/aggregator.go

remove steve cache ttl
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=619173&iterationID=-1&type=TASK)
/assign @iutx 
| 🇺🇸 English |       remove steve cache ttl       |
| 🇨🇳 中文    |      取消Steve cache的过期时间        |

fix: remove steve cache ttl

---

internal/tools/pipeline/providers/reconciler/taskrun/taskop/wait.go
internal/tools/pipeline/spec/pipeline_task.go
internal/tools/pipeline/spec/pipeline_task_test.go

- use timeUpdated as timeBegin if task skip queue op due to conditions like component panic
- also set timeBegin & costTimeSec when convert to pb
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=620779&iterationID=12783&type=BUG)
| 🇺🇸 English |   handle task time_begin & cost_time_sec if not set correctly           |
| 🇨🇳 中文    |   处理 task 的 time_begin & cost_time_sec 当未正确设置时           |

fix(pipeline): handle task time_begin & cost_time_sec if not set correctly

---

internal/tools/orchestrator/scheduler/instanceinfo/pod.go
internal/tools/orchestrator/scheduler/instanceinfo/pod_test.go

fix: pod info table has not been GC
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=619012&iterationID=-1&type=BUG)
/assign @iutx 
| 🇺🇸 English |       fix pod info table has not been GC       |
| 🇨🇳 中文    |     修复pod_info表没有被GC，导致quota统计错误         |

fix: pod info table has not been GC

---

cmd/monitor/collector/bootstrap-agent.yaml
internal/apps/msp/apm/service/apm.service.service.go
internal/tools/monitor/oap/collector/plugins/processors/dropper/provider.go

`dropper` processer support metric white list
/assign @sfwn 
| 🇺🇸 English |    `dropper` processer support metric white list          |
| 🇨🇳 中文    |     `dropper`支持指标白名单         |

feat: `dropper` processer support metric white list

---

cmd/monitor/monitor/conf/chartview/cmp/cmp-dashboard-podDetail.json

pod monitoring charts modified to show Pods as the smallest unit
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=623909&iterationID=12783&type=BUG)
/assign @iutx 
| 🇺🇸 English |      pod monitoring charts modified to show Pods as the smallest unit       |
| 🇨🇳 中文    |       将Pod详情页的监控图表修改为以Pod为最小单位显示       |

feat: pod monitoring charts modified to show Pods as the smallest unit

---

cmd/erda-server/bootstrap.yaml
internal/core/openapi/openapi-ng/auth/uc-session/login.go
internal/core/openapi/openapi-ng/auth/uc-session/login_test.go
internal/core/openapi/openapi-ng/auth/uc-session/provider.go

UC login redirect dismatch under NodePort service.
Frontend fix: [4056](https://github.com/erda-project/erda-ui/pull/4056)
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=627358&iterationID=13633&type=TASK)
/assign @sfwn 
| 🇺🇸 English |   fix uc login redirect dismatch under NodePort service           |
| 🇨🇳 中文    |       修复平台使用 NodePort Service 登陆跳转不匹配       |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CON …

fix: uc login redirect dismatch under NodePort service

---

pkg/parser/diceyml/servicename_visitor.go
pkg/parser/diceyml/servicename_visitor_test.go

diceyml env regexp support .-
New regexp from kubernetes env name rules: `[-._a-zA-Z][-._a-zA-Z0-9]*`
/assign @sfwn 
| 🇺🇸 English |  diceyml env regexp support .-            |
| 🇨🇳 中文    |    diceyml 正则支持 .-          |

feat: diceyml env regexp support .-

---

internal/tools/orchestrator/hepa/services/api_policy/impl/impl.go
internal/tools/orchestrator/hepa/services/endpoint_api/impl/impl.go
internal/tools/orchestrator/hepa/services/openapi_rule/impl/impl.go

fix hepa failed to delete `route` due to nil zoneInfo make panic
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that failed to delete `route` due to nil zoneInfo make panic           |
| 🇨🇳 中文    |      修复了hepa删除流量入口路由失败的问题        |

fix(hepa): failed to delete `route` due to nil zoneInfo make panic

---

internal/tools/orchestrator/endpoints/instance.go
internal/tools/orchestrator/scheduler/executor/plugins/k8s/instanceinfosync/pod.go
internal/tools/orchestrator/scheduler/impl/terminal/terminal.go

1. get terminal params from args 
2. more logs in `s_instance_info` watcher
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=628274&iterationID=12783&type=TASK)
/assign @iutx 
| 🇺🇸 English |       get terminal params from args and more logs in `s_instance_info` watcher        |
| 🇨🇳 中文    |       terminal参数从args中获取，并改造watcher，多输出些日志       |

feat: get terminal params from args 

---

internal/apps/msp/resource/deploy/coordinator/coordinator.go

get same mutex lock for registercenter and configcenter
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=629039&iterationID=-1&type=BUG)
/assign @iutx 
| 🇺🇸 English |       get same mutex lock for registercenter and configcenter       |
| 🇨🇳 中文    |      注册中心和配置中心获取同一把锁，避免它俩同时部署        |

feat: get same mutex lock for registercenter and configcenter

---

internal/apps/ai-proxy/filters/audit-after-llm-director/resp.go
internal/apps/ai-proxy/filters/dashscope-director/resp.go
internal/apps/ai-proxy/filters/dashscope-director/util.go
internal/apps/ai-proxy/models/metadata/meta_dashscope.go

- dashscope non-stream mode for openai response_type works now
- add missing actual_response_body
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=634273&iterationID=12783&type=TASK)
| 🇺🇸 English |   dashscope non-stream mode for openai response_type models works now       |
| 🇨🇳 中文    |    修复百炼非流式模式下的 openai 风格模型不可用的问题          |

fix(ai-proxy): dashscope non-stream openai style

---

.erda/migrations/msp/20240809-mse-nacos.sql
.erda/migrations/msp/20240812-insert-config-center.sql

fix sql migrations error
/assign @iutx 
| 🇺🇸 English |       remove id, create&update time       |
| 🇨🇳 中文    |       删除SQL中id、create和update time       |

fix: sql migrations error

---

internal/apps/cmp/steve/aggregator.go

fix new cluster steve not ready
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=635433&iterationID=12783&type=BUG)
/assign @iutx 
| 🇺🇸 English |       fix new cluster steve not ready       |
| 🇨🇳 中文    |      修复云管中新集群的Steve not ready        |

fix: new cluster steve not ready

---

internal/tools/monitor/oap/collector/plugins/receivers/collector/provider.go

fix  auth validator is nil
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/ticket?id=635802&iterationID=-1&type=TICKET)
| 🇺🇸 English | fix auth validator is nil             |
| 🇨🇳 中文    |      修复 collector validator 空指针        |

fix(collector): auth validator is nil

---

internal/apps/dop/endpoints/pipeline.go
internal/apps/dop/endpoints/pipeline_test.go

inject project/org default namespace for ci/cd pipeline
/assign @sfwn 
| 🇺🇸 English |   Support inject project/org default namespace for ci/cd pipeline           |
| 🇨🇳 中文    |    为cicd流水线注入默认的项目/组织配置ns          |

feat(pipeline): inject project/org default namespace for ci/cd pipeline

---

.erda/migrations/.patches/patch-20210528-cmdb-base.sql
.erda/migrations/cmdb/20210528-cmdb-base.sql
.erda/migrations/cmdb/20211221-dice-member-userID-varchar.sql
.erda/migrations/config.yml

baseline dice_member user_id change to varchar(36)
/assign @sfwn 
| 🇺🇸 English |  baseline dice_member user_id change to varchar(36)            |
| 🇨🇳 中文    |    基线   dice_member user_id 修改为 varchar(36)         |

chore: baseline dice_member user_id change to varchar(36)

---

go.mod
go.sum
pkg/k8sclient/client.go

init controller-runtime logger
reference [Github issue](https://github.com/rook/rook/issues/12434)
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=641448&iterationID=-1&type=BUG)
/assign @iutx 
| 🇺🇸 English |       init controller-runtime logger       |
| 🇨🇳 中文    |      修复controller-runtime报错        |

fix: init controller-runtime logger

---

cmd/monitor/collector/bootstrap-agent.yaml
cmd/monitor/collector/bootstrap.yaml

fix redis cpu(sys,user,children) percent
/assign @sfwn @CeerDecy 
| 🇺🇸 English |  Fix the bug that redis cpu(sys,user,children) percent            |
| 🇨🇳 中文    |    修复了redis cpu使用率失准的问题          |

fix(monitor): redis cpu(sys,user,children) percent

---

internal/apps/ai-proxy/filters/dashscope-director/sdk/converter.go
internal/apps/ai-proxy/filters/dashscope-director/sdk/resp.go

ai-proxy return no choices when using aliyun dashscope non-stream mode for ds response_type.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=642480&iterationID=12783&type=TASK)
| 🇺🇸 English |      dashscope non-stream mode for ds response_type works now        |
| 🇨🇳 中文    |   修复灵积非流式模式下的 ds 风格模型不可用的问题           |

fix(ai-proxy): dashscope non-stream mode for ds response_type works now

---

internal/tools/orchestrator/dbclient/addon_instance.go
internal/tools/orchestrator/scheduler/executor/plugins/k8s/instanceinfosync/pod.go

add status as a condition for searching registercenter
/assign @iutx 
| 🇺🇸 English |      add status as a condition for searching registercenter        |
| 🇨🇳 中文    |       添加status作为查询注册中心的条件       |

fix: add status as a condition for searching registercenter

---

internal/core/messenger/eventbox/dispatcher/filters/lastfilter.go
internal/core/messenger/eventbox/types/types.go

print human-readable error log
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=644236&iterationID=12783&type=TASK)
/assign @iutx 
| 🇺🇸 English |    polish(eventbox): print human-readable error log          |
| 🇨🇳 中文    |   优化(eventbox): 打印人类可读的错误日志           |

chore(eventbox): print human-readable error log

---

internal/tools/orchestrator/scheduler/executor/plugins/k8s/lifecycle.go
internal/tools/orchestrator/scheduler/executor/plugins/k8s/lifecycle_test.go

fix eci fluent-bit sidecar log collect error.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=645014&iterationID=12783&type=TASK)
/assign @sfwn 
| 🇺🇸 English |  fix eci fluent-bit sidecar log collect error            |
| 🇨🇳 中文    |  修复 eci fluent-bit sidecar 容器采集失败的问题            |

fix(orchestrator): eci fluent-bit sidecar log collect error

---

apistructs/addon.go
cmd/orchestrator/conf/i18n/orchestrator-log-trans.yaml
internal/tools/orchestrator/dbclient/addon_instance_routing.go
internal/tools/orchestrator/endpoints/addon.go
internal/tools/orchestrator/endpoints/addon_test.go
internal/tools/orchestrator/endpoints/endpoints.go
internal/tools/orchestrator/scheduler/executor/plugins/k8s/instanceinfosync/pod.go
internal/tools/orchestrator/services/addon/addon.go
internal/tools/orchestrator/services/addon/addon_extension_cache.go
internal/tools/orchestrator/services/addon/addon_handler.go

feat custom deploy addon support cluster addon and can select version
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=635782&iterationID=12783&type=TASK)
/assign @iutx 
| 🇺🇸 English |     feat custom deploy addon support cluster addon and can select version         |
| 🇨🇳 中文    |       自定义部署Addon支持集群级别Addon并且支持版本选择       |

feat: custom deploy addon support cluster addon and can select version

---

internal/apps/ai-proxy/filters/dashscope-director/sdk/converter.go
internal/apps/ai-proxy/filters/dashscope-director/sdk/converter_test.go

dashscope non-stream support vlm multipart
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=646372&iterationID=12783&type=TASK)
| 🇺🇸 English |  ai-proxy: dashscope non-stream support vlm multipart            |
| 🇨🇳 中文    |    ai-proxy: 灵积非流式支持 vlm multipart          |

fix(ai-proxy): dashscope non-stream support vlm multipart

---

pkg/mock/mock.go

The intention here should be to initialize a slice with a capacity of 8 rather than initializing the length of this slice. 
The only demo: https://go.dev/play/p/q1BcVCmvidW
| 🇺🇸 English |      fix slice init length        |
| 🇨🇳 中文    |         修复切片初始化的长度     |

fix: fix slice init length

---

go.mod
go.sum

when we use go 1.23 to run `make prepare`,   will encounter this problem：
`#command-line-arguments
Link: github.com/timandy/routine/g: invalid reference to runtime.g0internal/core/openapi/legacy/api/generate/generate.go:33: running "go": exit status 1make: *** [prepare] Error 1`
fix condition for use go 1.22 to run make prepare
https://github.com/timandy/routine/commit/8b58b7d7f96cfdf549a0fdb66562b5cd70ede8db
- [Erda Cloud Issue Link()
| 🇺🇸 English |      fix condition for use go 1.23 to run make prepare        |
| 🇨🇳 中文    |       修复了使用go 1.23运行make prepare的问题       |
> For details on the cherry pick process, see the …

chore: update routine version to 1.1.4 from 1.1.2

---

internal/tools/pipeline/providers/dbgc/dbgc.go
internal/tools/pipeline/providers/dbgc/dbgc_test.go

fix dbgc online effectiveness problem. 
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=557257&iterationID=12783&type=BUG)
| 🇺🇸 English |     Fixed the issue of online dbgc failure in the erda cloud platform.      |
| 🇨🇳 中文    |     修复了erda-cloud平台中，线上dbgc失效的问题。         |

fix: DBGC online effectiveness

---

internal/apps/cmp/steve/aggregator.go

fix erda-server steve oom
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=617299&iterationID=13633&type=TASK)
| 🇺🇸 English |       fix erda-server steve oom       |
| 🇨🇳 中文    |     修复erda-server瞬时加载steve导致的OOM         |

fix: erda-server steve oom

---

.github/workflows/ci-it.yml
internal/apps/ai-proxy/filters/azure-director/filter.go

Fix deprecated actions/upload-artifact@v3 in GitHub CI.
- Fixes CI #6487 
| 🇺🇸 English |    Fix deprecated actions/upload-artifact@v3 in GitHub CI.          |
| 🇨🇳 中文    |    修复 GitHub CI 中已弃用的 action/upload-artifact@v3。          |

fix(github-ci): upgrade actions/upload-artifact@v3 to v4

---

api/proto/core/monitor/settings/settings.proto
internal/tools/monitor/common/db/monitor_config_register.go
internal/tools/monitor/common/db/table.go
internal/tools/monitor/core/settings/monitor.go
internal/tools/monitor/core/settings/settings.service.go
internal/tools/monitor/core/settings/sync_config.go
internal/tools/monitor/core/settings/types.go

refresh logs and metrics separately
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=732453&iterationID=-1&type=BUG)
| 🇺🇸 English |       refresh logs and metrics separately       |
| 🇨🇳 中文    |      分别对logs和metrics配置进行同步        |

feat: refresh logs and metrics separately

---

api/proto/apps/aiproxy/model_provider/model_provider.proto
internal/apps/ai-proxy/filters/azure-director/filter.go
internal/apps/ai-proxy/filters/bailian-director/filter.go
internal/apps/ai-proxy/filters/context-audio/filter.go
internal/apps/ai-proxy/filters/dashscope-director/filter.go
internal/apps/ai-proxy/filters/openai-director/filter.go
internal/apps/ai-proxy/filters/openai-v1-models/model_name.go
internal/apps/ai-proxy/handlers/handler_model_provider/handler.go
internal/apps/ai-proxy/handlers/handler_rich_client/handler.go
internal/apps/ai-proxy/models/metadata/meta_model_provider.go
internal/apps/ai-proxy/models/model_provider/table.go

AI-Proxy support custom displayProviderType for self-hosted provider.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=739940&iterationID=12783&type=TASK)
| 🇺🇸 English |   AI-Proxy support custom displayProviderType for self-hosted provider           |
| 🇨🇳 中文    |   AI-Proxy 为自建供应商提供自定义类型用于展示          |

feat(ai-proxy): support custom displayProviderType for self-hosted provider

---

cmd/ai-proxy/bootstrap.yml
cmd/ai-proxy/conf/routes/responses.yml
internal/apps/ai-proxy/common/request_path.go
internal/apps/ai-proxy/dependent_filters.go
internal/apps/ai-proxy/filters/azure-director/filter.go
internal/apps/ai-proxy/filters/context-responses/filter.go
internal/apps/ai-proxy/filters/context-responses/filter_test.go
internal/apps/ai-proxy/filters/context/filter.go

- Fix Missing body, will cause method like GET or DELETE.. error.
- Add new route and filters for handling Responses API requests- Implement context filter to extract user prompts from API input
- Update request path constants to include new Responses API endpoint- Add unit tests for new context filter functionality
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=749255&iterationID=12783&type=TASK)
/assign @sfwn 
| 🇺🇸 English |   add support for OpenAI Responses API           |
| 🇨🇳 中文    |   支持 OpenAI Responses API           | …

feat(ai-proxy): add support for OpenAI Responses API

---

internal/tools/pipeline/conf/conf.go
internal/tools/pipeline/providers/dbgc/dbgc.go
internal/tools/pipeline/providers/dbgc/dbgc_test.go
internal/tools/pipeline/providers/dbgc/dbgcconfig/config.go
internal/tools/pipeline/providers/dbgc/dbgcconfig/config_test.go
internal/tools/pipeline/providers/dbgc/provider.go
internal/tools/pipeline/spec/pipeline.go

chore of pipeline:
- move dbgc config items from pipeline global into provider
- convert unit from sec to human-readable time.Duration
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=756918&iterationID=12783&tab=TASK&type=TASK)
| 🇺🇸 English |    move pipeline dbgc config items from pipeline global into provider         |
| 🇨🇳 中文    |    将散落在 pipeline 全局配置里的 dbgc 配置项移动至 provider 内部          |

chore(pipeline): move dbgc config items from pipeline global into provider

---

cmd/ai-proxy/conf/routes/routes.yml
internal/apps/ai-proxy/dependent_filters.go
internal/apps/ai-proxy/filters/extra-body/filter.go
internal/apps/ai-proxy/filters/extra-body/json_body.go
internal/apps/ai-proxy/filters/extra-body/json_body_test.go

ai-proxy support set extra-body for some models.
such as: qwen3-235b-a22b non-stream set unofficial `enable-thinking=false` as default.
default configs configured at model's public metadata:
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=759363&iterationID=12783&type=TASK)
| 🇺🇸 English |   ai-proxy  support set extra-body for some models          |
| 🇨🇳 中文    |    ai-proxy 支持为模型设置额外 request body          |

feat(ai-proxy): support set extra-body for some models

---

cmd/erda-server/bootstrap.yaml
internal/core/openapi/openapi-ng/auth/uc-session/login.go
internal/core/openapi/openapi-ng/auth/uc-session/provider.go
internal/core/openapi/openapi-ng/auth/uc-session/refer.go
internal/core/openapi/openapi-ng/auth/uc-session/refer_test.go

- Add referMatcher struct and buildReferMatcher method to validate referer
- Implement Match method in referMatcher to check if referer is allowed
- Add refer validation logic in UC login handler
- Update bootstrap.yaml to include platform_domain and allowed_referrers config
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=757954&iterationID=12783&type=TASK)
/assign @sfwn 
| 🇺🇸 English |   add referer validation for UC login direct           |
| 🇨🇳 中文    |     增加 uc 登录跳转后 referer 认证         | …

feat(auth): add referer validation for UC login direct

---

internal/apps/ai-proxy/filters/directors/anthropic-compatible-director/anthropic_official/anthropic.go
internal/apps/ai-proxy/filters/directors/anthropic-compatible-director/anthropic_official/eventstream.go
internal/apps/ai-proxy/filters/directors/anthropic-compatible-director/aws_bedrock/bedrock.go
internal/apps/ai-proxy/filters/directors/anthropic-compatible-director/aws_bedrock/bedrock_test.go
internal/apps/ai-proxy/filters/directors/anthropic-compatible-director/aws_bedrock/eventstream.go
internal/apps/ai-proxy/filters/directors/anthropic-compatible-director/common/message_converter/req.go
internal/apps/ai-proxy/filters/directors/anthropic-compatible-director/common/message_converter/resp.go
internal/apps/ai-proxy/filters/directors/anthropic-compatible-director/common/openai_extended/openai_extended.go
internal/apps/ai-proxy/filters/directors/anthropic-compatible-director/common/openai_extended/thinking/getter.go
internal/apps/ai-proxy/filters/directors/anthropic-compatible-director/common/openai_extended/thinking/getter_test.go
internal/apps/ai-proxy/filters/directors/anthropic-compatible-director/common/openai_extended/thinking/thinking.go
internal/apps/ai-proxy/filters/directors/anthropic-compatible-director/common/openai_extended/thinking/thinking_test.go
internal/apps/ai-proxy/filters/directors/anthropic-compatible-director/filter.go
internal/apps/ai-proxy/provider.go

AI-Proxy Anthropic-Compatible Director support Thinking config:
- add OpenAIRequestExtended struct to store extra fields
- support Qwen & Anthropic two style thinking config
- abstract unified req&resp logic
- force avoid duplicated Access-Control-Allow-Origin header
- [Erda Cloud Issue Link](https://erda.cloud/terminus/dop/projects/190/issues/all?id=762963&iterationID=14782&type=TASK)
| 🇺🇸 English |   AI-Proxy Anthropic-Compatible Director support Thinking config           |
| 🇨🇳 中文    |    AI-Proxy Anthropic-Compatible Director 支持是否启用思考          |

feat(ai-proxy): Anthropic-Compatible Director support Thinking config

---

internal/core/openapi/openapi-ng/auth/uc-session/refer.go
internal/core/openapi/openapi-ng/auth/uc-session/refer_test.go

In some cases, the browser jump source will be changed to uc.
ChangeLog:
- Add UCAddr to exactDomains map in refer.go
- Update refer_test.go to include test case for UCAddr
| 🇺🇸 English |  allow UCAddr in referer validation            |
| 🇨🇳 中文    |    允许 UC 地址作为跳转来源          |

feat(openapi): allow UCAddr in referer validation

---

internal/apps/ai-proxy/provider.go

AI-Proxy ensure sse content-type to `text/event-stream`, for aws-bedrock and others.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=772779&iterationID=12783&type=TASK)
| 🇺🇸 English |    AI-Proxy ensure sse content-type to `text/event-stream`     |
| 🇨🇳 中文    |      AI-Proxy 确保 SSE Content-Type = `text/event-stream`     |

fix(ai-proxy): ai-proxy ensure sse content-type to text/event-stream (such as aws-bedrock)

---

internal/tools/orchestrator/scheduler/executor/plugins/edas/edas_app_flow.go
internal/tools/orchestrator/scheduler/executor/plugins/edas/edas_app_flow_test.go
internal/tools/orchestrator/scheduler/executor/plugins/edas/types/types.go
internal/tools/orchestrator/scheduler/executor/plugins/edas/wrapclient/edas/app.client.go
internal/tools/orchestrator/scheduler/executor/plugins/edas/wrapclient/edas/app.client_test.go
internal/tools/orchestrator/scheduler/executor/plugins/edas/wrapclient/kubernetes/provider.go
internal/tools/orchestrator/scheduler/executor/plugins/edas/wrapclient/kubernetes/service.go
internal/tools/orchestrator/scheduler/executor/plugins/edas/wrapclient/kubernetes/service_test.go

- Add labels to EDAS application specifications
- Implement logic to extract and set labels from service groups
- Update service creation and update functions to handle labels
/assign @sfwn 
| 🇺🇸 English |    add label support for EDAS applications           |
| 🇨🇳 中文    |    edas 支持 erda 标签          |

feat(edas): add label support for EDAS applications

---

internal/tools/orchestrator/scheduler/executor/plugins/edas/edas_app_flow.go
internal/tools/orchestrator/scheduler/executor/plugins/edas/edas_app_flow_test.go
internal/tools/orchestrator/scheduler/executor/plugins/edas/types/types.go
internal/tools/orchestrator/scheduler/executor/plugins/edas/wrapclient/kubernetes/service.go
internal/tools/orchestrator/scheduler/executor/plugins/edas/wrapclient/kubernetes/service_test.go

In certain scenarios, EDAS contains mixed labels, and the app label cannot be overridden. Therefore, the new label conventions of Erda are used instead.
- Replace EDASAppIDLabel with LabelServiceName and LabelServiceGroupID- Update label usage in service creation and tests
- Modify edas_app_flow and tests to use new label keys
/assign @sfwn 
| 🇺🇸 English |  update label keys for service name and group ID            |
| 🇨🇳 中文    |    edas 更新 service-name/ servicegroup-id 标签          | …

refactor(edas): update label keys for service name and group ID

---

internal/tools/orchestrator/services/runtime/runtime.go

fix: If the artifact is still referenced within the rollback point, do not need to mark the deployment as outdated.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDQ0MDMsMjc2NzIsNzEwNiw0NDA0LDQ0MDYsNDQwNywyMTAwMSw0NDEyLDQ1MzgsMjc2OTcsNDQxMywyMzM3Niw0NDE0LDQ0MTUsMjQ3OTcsNDQxNiw0NDE4LDIzMjM2LDQ0MTksNDQyMCw0NDIxLDQ0MjJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9)
/assign @iutx 
| 🇺🇸 English |     If the artifact is still referenced within the rollback point, do not need to mark the deployment as outdated. |
| 🇨🇳 中文    |      如果制品还在回滚点内被引用，则不需要标记deployment为outdated       |
Add comment like `/cherry-pick release/1.0` …

fix: add unmark deployment

---

internal/apps/ai-proxy/route/filters/request/context-family/context/model.go
internal/apps/ai-proxy/route/filters/request/openai-v1-models/model_name.go

AI-Proxy `/v1/models` and context-find-model only use model.name or publisher/model.name, no more `model.metadata.public.{model_name/model_id}`.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=778242&iterationID=12783&type=TASK)
| 🇺🇸 English |   AI-Proxy `/v1/models` and context-find-model only use model.name or publisher/model.name           |
| 🇨🇳 中文    |    AI-Proxy `/v1/models` 和 context-find-model 只使用 model.name 或 publisher/model.name          |

fix(ai-proxy): `/v1/models` and context-find-model only use model.name or publisher/model.name

---

internal/apps/ai-proxy/route/filters/common/anthropic-compatible-director/common/message_converter/req.go

AI-Proxy use string content directly when converting openai tool_result to anthropic style.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=780069&iterationID=12783&type=TASK)
| 🇺🇸 English |   AI-Proxy use string content directly when converting openai tool_result to anthropic style           |
| 🇨🇳 中文    |   AI-Proxy 在转换 tool_result 至 anthropic 风格时直接使用 string content           |

fix(ai-proxy): use string content directly when converting openai tool_result to anthropic style

---

internal/apps/ai-proxy/route/filters/common/anthropic-compatible-director/aws_bedrock/bedrock.go
internal/apps/ai-proxy/route/filters/common/anthropic-compatible-director/common/message_converter/req.go
internal/apps/ai-proxy/route/filters/common/anthropic-compatible-director/common/openai_extended/openai_extended.go

AI-Proxy force convert image_url to base64 for bedrock anthropic.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=780146&iterationID=12783&type=TASK)
| 🇺🇸 English |   AI-Proxy force convert image_url to base64 for bedrock anthropic           |
| 🇨🇳 中文    |   AI-Proxy 强制将 image_url 转换为 base64 以支持 bedrock anthropic           |

feat(ai-proxy): force convert image_url to base64 for bedrock anthropic

---

internal/apps/ai-proxy/route/filters/common/anthropic-compatible-director/common/message_converter/req.go
internal/apps/ai-proxy/route/filters/common/anthropic-compatible-director/common/openai_extended/thinking/thinking.go

AI-Proxy set anthropic req.thinking.budget_tokens=req.max_tokens/2 if empty.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=779599&iterationID=12783&type=TASK)
| 🇺🇸 English |   AI-Proxy set anthropic req.thinking.budget_tokens=req.max_tokens/2 if empty           |
| 🇨🇳 中文    |   AI-Proxy 在 req.thinking.budget_tokens 为空时设置其为 req.max_tokens/2           |

fix(ai-proxy): set anthropic req.thinking.budget_tokens=req.max_tokens/2 if empty

---

cmd/erda-server/bootstrap.yaml
internal/core/openapi/legacy/auth/auth.go
internal/core/openapi/legacy/auth/user.go
internal/core/openapi/legacy/loginserver.go
internal/core/openapi/legacy/provider.go
internal/core/openapi/legacy/server.go
internal/core/openapi/openapi-ng/auth/password/check.go
internal/core/openapi/openapi-ng/auth/password/provider.go
internal/core/openapi/openapi-ng/auth/uc-session/check.go
internal/core/openapi/openapi-ng/auth/uc-session/login.go
internal/core/openapi/openapi-ng/auth/uc-session/provider.go
internal/core/openapi/openapi-ng/auth/uc-session/user.go
internal/core/openapi/openapi-ng/routes/openapi-v1/provider.go
internal/core/openapi/settings/provider.go

openapi settings provider and configurable session expiration time in redis
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=760957&iterationID=-1&type=BUG
| 🇺🇸 English |      openapi settings provider and configurable session expiration time in redis        |
| 🇨🇳 中文    |       可配置的Session过期时间       |

feat: openapi settings provider and configurable session expiration time in redis

---

cmd/erda/main.go
cmd/openapi/main.go
conf/erda/erda.yaml
conf/openapi/openapi.yaml
modules/core/openapi-ng/auth/password/check.go
modules/core/openapi-ng/auth/password/provider.go
modules/core/openapi-ng/auth/uc-session/check.go
modules/core/openapi-ng/auth/uc-session/login.go
modules/core/openapi-ng/auth/uc-session/provider.go
modules/core/openapi-ng/auth/uc-session/user.go
modules/core/openapi-ng/routes/openapi-v1/provider.go
modules/openapi/auth/auth.go
modules/openapi/auth/user.go
modules/openapi/loginserver.go
modules/openapi/provider.go
modules/openapi/server.go
modules/openapi/settings/provider.go

openapi settings provider and configurable session expiration time in redis
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=760957&iterationID=-1&type=BUG)
/assign @sfwn 
| 🇺🇸 English |       openapi settings provider and configurable session expiration time in redis       |
| 🇨🇳 中文    |      可配置的Session过期时间        |

feat(release 2.1): openapi settings provider and configurable session expiration time in redis

---

internal/apps/ai-proxy/route/reverse_proxy/response_header.go
internal/apps/ai-proxy/route/reverse_proxy/response_modify.go

AI-Proxy fix concurrent map read and write for resp header.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=783125&iterationID=12783&type=TASK)
| 🇺🇸 English |    AI-Proxy fix concurrent map read and write for resp header          |
| 🇨🇳 中文    |    AI-Proxy 修复响应头并发读写 map 的问题          |

fix(ai-proxy): fix concurrent map read and write for resp header

---

cmd/ai-proxy/integration-tests/curl_tests/thinking/chat_completions/bytedance_style_thinking_auto.json
cmd/ai-proxy/integration-tests/curl_tests/thinking/chat_completions/bytedance_style_thinking_disabled.json
cmd/ai-proxy/integration-tests/curl_tests/thinking/chat_completions/bytedance_style_thinking_enabled.json
cmd/ai-proxy/integration-tests/thinking_handler_curl_test.go
internal/apps/ai-proxy/common/common_types/common_types_util/service_provider.go
internal/apps/ai-proxy/common/common_types/common_types_util/service_provider_test.go
internal/apps/ai-proxy/common/common_types/model_publisher.go
internal/apps/ai-proxy/common/common_types/service_provider.go
internal/apps/ai-proxy/route/filters/request/thinking-handler/encoders/impl/model-publisher/anthropic.go
internal/apps/ai-proxy/route/filters/request/thinking-handler/encoders/impl/model-publisher/anthropic_test.go
internal/apps/ai-proxy/route/filters/request/thinking-handler/encoders/impl/model-publisher/bytedance.go
internal/apps/ai-proxy/route/filters/request/thinking-handler/encoders/impl/model-publisher/bytedance_test.go
internal/apps/ai-proxy/route/filters/request/thinking-handler/encoders/impl/model-publisher/openai_chat.go
internal/apps/ai-proxy/route/filters/request/thinking-handler/encoders/impl/model-publisher/openai_chat_test.go
internal/apps/ai-proxy/route/filters/request/thinking-handler/encoders/impl/model-publisher/openai_responses.go
internal/apps/ai-proxy/route/filters/request/thinking-handler/encoders/impl/model-publisher/openai_responses_test.go
internal/apps/ai-proxy/route/filters/request/thinking-handler/encoders/impl/model-publisher/qwen.go
internal/apps/ai-proxy/route/filters/request/thinking-handler/encoders/impl/model-publisher/qwen_test.go
internal/apps/ai-proxy/route/filters/request/thinking-handler/encoders/impl/service-provider/aliyun_bailian.go
internal/apps/ai-proxy/route/filters/request/thinking-handler/encoders/impl/service-provider/aliyun_bailian_test.go
internal/apps/ai-proxy/route/filters/request/thinking-handler/encoders/impl/service-provider/volcengine_ark.go
internal/apps/ai-proxy/route/filters/request/thinking-handler/encoders/impl/service-provider/volcengine_ark_test.go
internal/apps/ai-proxy/route/filters/request/thinking-handler/encoders/registry/registry.go

AI-Proxy add service-provider thinking encoder.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=789300&iterationID=12783&type=TASK)
| 🇺🇸 English |    AI-Proxy add service-provider thinking encoder          |
| 🇨🇳 中文    |    AI-Proxy 增加 服务提供商 级别的思考配置编码器           |

feat(ai-proxy): add service provider thinking encoder
