erda-project/erda

- go.mod
latest version of alibaba-cloud-sdk-go is bad, they changed too many struct.
> Downgrade version of github.com/aliyun/alibaba-cloud-sdk-go to v1.61.426

- go.mod
- pkg/httpserver/server.go
httpserver remove promxp to fix compile error.
after `telemetry/promxp` opensourced, then add it again.
> hotfix: httpserver remove promxp to fix compile error

- go.mod
- go.sum
I triggered a bug in gopsutil when compiling, please refer to https://github.com/shirou/gopsutil/issues/976 for details. The error message is as follows
```
../../vendor/github.com/shirou/gopsutil/v3/cpu/cpu_darwin_cgo.go:13:5: error: 'TARGET_OS_MAC' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
#if TARGET_OS_MAC
^
1 error generated.
make[1]: *** [build] Error 2
make: *** [build-all] Error 2
```
Then I upgraded gopsutil to v3.21.3 and this problem was solved.
> Update gopsutil to v3.21.3

- modules/pipeline/aop/aoptypes/tunepoint.go
- modules/pipeline/aop/plugins/pipeline/plugins/precheck_before_pop/plugin.go
- modules/pipeline/aop/plugins/pipeline/tunechain.go
feature
Pipeline add `pipeline_in_queue_precheck_before_pop` type of aop tunepoint.
Pipeline dependency logic will be added here.
Related doc: https://www.yuque.com/erda-project/design/sdvvwl
> Pipeline add `pipeline_in_queue_precheck_before_pop` type of aop tunepoint

- modules/scheduler/executor/plugins/k8sjob/job.go
/kind bug
Fix the error name spelling mistake when creating PVC on Kubernetes
Fixes #
> fix(scheduler): the error name spelling mistake when creating PVC on Kubernetes

- modules/pipeline/pipengine/reconciler/queuemanage/manager/pipeline.go
bug
Before fix, when pipeline service restart, instance which status is "Running" will re-enter queue, 'rollback' to "Queue" and re-emit p_i changed event.
> Fix: don't update pipeline status and emit event when p_i re-enter queue

- modules/pipeline/aop/plugins/task/plugins/autotest_cookie_keep_after/plugin.go
- modules/pipeline/aop/plugins/task/plugins/autotest_cookie_keep_before/plugin.go
- modules/pipeline/pipengine/actionexecutor/plugins/apitest/logic/meta.go
- modules/pipeline/pipengine/reconciler/taskrun/teardown.go
- pkg/apitestsv2/apitest.go
- pkg/apitestsv2/header.go
- pkg/apitestsv2/netportal.go
- pkg/apitestsv2/netportal_test.go
bug
use `Set-Cookie` header in response instead of CookieJar, and set `Cookie` header for latter apis to simulate login.
> apitest recognize Set-Cookie header and set cookie to latter apis

- modules/uc-adaptor/provider.go
/kind bug
uc-adaptor's provider name is wrong, it caused him to fail to boot
/assgin @sfwn
> modify the uc-adaptor's provider name

- modules/pipeline/services/pipelinesvc/create.go
feature
1. create pipeline if query action yaml was empty, create pipeline will null point error
2. uc change id struct  unmarshal will error int id can not change to string
> bugfix pipeline query error and uc error

- modules/monitor/apm/topology/topology.go
Topology bug fix
/kind bug
Fixes #
- Solve the problem of overcalculating the number of application instances
- Fixed an issue where the running count of application instances on the topology page was incorrectly displayed 
- Fixed the incorrect number of incorrect requests and service exceptions in the global overview
> Topology bug fix

- modules/pipeline/services/crondsvc/crond.go
bug
Acquire lock before print snapshot of crond. Otherwise, it may causes panic if crond is reloading at the same time.
> hotfix: acquire lock before print snapshot of crond

- apistructs/testset.go
- modules/qa/endpoints/testset.go
- modules/qa/services/testset/list_by_parent.go
feature
Manual testSet's query detail return with ancestors info, so frontend can locate this testSet in the whole testSet tree.
> Manual testset's query detail support return ancestors info

- build/dockerfiles/Dockerfile
bug
Dockerfile install QA required commands, such as xmindparser, dicttoxml.
QA testcases import will use these commands.
> Dockerfile install qa required commands

- pkg/apitestsv2/apitest.go
/kind bug
when api content type is x-www-form-urlencoded, use interface field unmarshal value field
Fixes #
> fix apitest unmarshal bug

- apistructs/openapi.go
- modules/openapi/oauth2/jwt.go
- modules/openapi/oauth2/server.go
feature
Openapi oauth2 disallowed token request without accessTokenExpiredIn param.
Client must set expected accessTokenExpiredIn explicitly.
All related clients have been adjusted.
> openapi oauth2 disallowed token request without accessTokenExpiredIn param

- modules/actionagent/callback.go
- modules/actionagent/callback_test.go
- modules/pipeline/pipengine/actionexecutor/plugins/apitest/logic/meta.go
bug
At present, the return result of the task is to intercept the contents of the file according to the newline character. In the autotest, the return value of some tasks has a newline character, which causes part of the return value to be lost.
> bug fix if the action result value has a newline character, the result of the task will be truncated

- modules/qa/services/autotest_v2/scene.go
- modules/qa/services/autotest_v2/testplan_v2.go
/kind bug
qa autotest need the same mock params value in different scenes
> qa autotest generate and replace random value before create pipeline yml

- modules/hepa/apipolicy/policies/proxy/dto.go
- modules/hepa/apipolicy/policies/proxy/policy.go
/kind bug
this nginx directive `client_header_timeout` is not allowed in location snippet.
> fix client_header_timeout in ingress annotations

- modules/pipeline/pipengine/actionexecutor/plugins/apitest/logic/envconf.go
- pkg/jsonparse/parse_test.go
/kind bug
use jsonOnline instead of strutil string compatible json type param, header, assert
> pipeline apitest use json oneline instead of strutil string

- modules/cmdb/conf/conf.go
- modules/cmdb/endpoints/file.go
bug
cmdb disable file permission check for multi-domain temporarily
> hotfix: cmdb disable file permission check for multi-domain temporarily

- modules/pipeline/pipengine/reconciler/queuemanage/queue/add_pipeline.go
bug
Before fix, workflow in running status won't be reconciled when pipeline component reload because no done signal sent to channel.
Now, workflow will be added into processing queue and send done signal to continue reconcile directly.
> queue manager handle runningPipeline correctly when reload into queue

- pkg/expression/expression_reconcile.go
- pkg/expression/expression_reconcile_test.go
bug
It will be unexpected panic from lib if action IF expression is invalid, such as `aa`, `bb`.
> fix(pipeline): action if expression handle unexpected panic

- modules/pipeline/pipengine/reconciler/queuemanage/queue/range_pending_queue.go
/kind bug
Pipeline queue manager acquire read lock before read pipelineCaches.
Otherwise, it will cause `concurrent map read and map write` panic.
> Pipeline queue manager acquire read lock before read pipelineCaches

- modules/monitor/core/metrics/metricq/es-tsql/influxql/query.go
Fixed an issue where interval may be empty if bucket is an integral divisor of the timestamp difference.
example:
```sql
SELECT max(cpu_usage_active::field)
FROM  host_summary
GROUP BY time(10m);
```
Here is the DSL of influxql converted.
```json
{
"aggregations": {
"histogram": {
"aggregations": {
"687cf45294c71d1f": {
"max": {
"field": "fields.cpu_usage_active"
}
}
},
"histogram": {
"extended_bounds": {
"max": 1622021455605479000,
"min": 1622017855605479000
},
"field": "timestamp",
"interval": 600000000000,
"min_doc_count": 0,
"offset": 1622017855605479000
}
}
},
"query": {
"bool": {
"filter": {
"range": {
"timestamp": {
"from": 1622017855605479000,
"include_lower": true,
"include_upper": true,
"to": 1622021455605479000
}
}
}
}
},
"size": 0
}
```
the result 
```json
"took": 2, …
```
> Fixed possible null exception of ElasticSearch bucket

- CONTRIBUTING.md
- docs/guides/dev/cherry-pick.md
Add guide doc for (automated) cherry-pick.
You can use PR comment `/cherry-pick release/1.0` to created a cherry-pick PR automaticlly.
> contribution: add guide doc for auto-cherry-pick

- codecov.yml
ignore boilerplate code for coverage, like
- conf
- dbclient
- dao
@sfwn
> feat: ignore boilerplate for coverage

- modules/hepa/gateway/service/gateway_openapi_service.go
/kind feature
if there is no api from custom origin in the endpoint， then the endpoint need be recycled.
> optimize runtime endpoint gc

- modules/gittar-adaptor/service/filetree/filetree.go
/kind bug
set default content when creating yml file,otherwise pipeline-yml-graph will report an error for parse null yml content
> set default content when creating yml file

- modules/gittar/pkg/gitmodule/repo_diff.go
/kind bug
fix: cancel line character limit of commit's and compare's response
https://erda-org.erda.cloud/erda/workBench/projects/387/issues/all?id=63802&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMTI2MSJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=429&type=BUG
/assign @sfwn
> fix: cancel line character limit of commit's and compare's response

- modules/monitor/core/metrics/metricq/es-tsql/functions.go
- modules/monitor/core/metrics/metricq/es-tsql/influxql/functions.go
- modules/monitor/core/metrics/metricq/es-tsql/influxql/query.go
- modules/monitor/core/metrics/metricq/es-tsql/tsql-test/main.go
Signed-off-by: luoyu <o.sparkli@outlook.com>
ElasticSearch query engine support some custom functions
- diff 
Show difference value for the countervalue field, that is, the difference between the upper and lower bucket.
- diffps
Is the rate of the countervalue field, that is, the rate of the difference between the upper and lower bucket per second.
/kind feature
For some fields witch one use counter to calculate the difference and rate.
> ElasticSearch query engine support diff and diffps functions

- modules/monitor/apm/topology/topology.go
Error analysis may have too many repetitions, making it impossible to visualize the wrong layout, so add grouping.
> Add exception analysis operations grouped according to error id

- modules/monitor/core/metrics/metricq/es-tsql/influxql/query.go
- modules/monitor/core/metrics/metricq/es-tsql/tsql-test/main.go
/kind bug
There is a problem with the sequence of removing the end bucket, resulting in repeated judgment to remove extra bucet.
###before 
###after
> Fix the problem of removing excess bucket

- apistructs/cluster.go
- bundle/bundle.go
- bundle/cluster.go
- bundle/ecp.go
- bundle/events.go
- bundle/urls.go
- cmd/cluster-manager/main.go
- conf/cluster-manager/cluster-manager.yaml
- modules/cluster-manager/conf/conf.go
- modules/cluster-manager/dbclient/cluster.go
- modules/cluster-manager/dbclient/dbclient.go
- modules/cluster-manager/endpoints/cluster.go
- modules/cluster-manager/endpoints/endpoints.go
- modules/cluster-manager/endpoints/prehandle.go
- modules/cluster-manager/initialize.go
- modules/cluster-manager/model/model.go
- modules/cluster-manager/provider.go
- modules/cluster-manager/services/apierrors/errors.go
- modules/cluster-manager/services/cluster/cluster.go
- pkg/discover/address.go
- pkg/k8sclient/client.go
/kind feature
1. new component cluster-manager, move from cmdb
2. **_model deprecated: orgID, URLs, Settings, Config. There fields will get from configmap (dice-cluster-info)_**
3. pkg/k8sclient instead request from cmdb to cluster-manager
4. bundle support cluster manager
5. cluster-dialer support register cluster info
> feature: add cluster-manager

- apistructs/extention.go
/kind feature
Erda Version 1.1 is lower than old Dice Version like 3.21. So cli push ext will delete ext needed.
Add new field `supportedErdaVersions` in spec.yml and version from erda 1.0 to distinguish dice version.
- [Erda Cloud Issue Link](https://erda.cloud/erda/workBench/projects/387/issues/all?id=65286&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiOTIiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=429&type=TASK)
No. Just for 1.1.
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to- …
> feature(dicehub): extension spec parse supportedVersions field from `supportedErdaVersions` tag

- modules/scheduler/executor/plugins/k8s/deployment.go
- modules/scheduler/impl/servicegroup/scale.go
/kind bug
- feat(scale): support scale the resource not restart pod
> feat(scale): support scale the resource not restart pod

- pkg/database/sqlparser/ddlreverser/reverser.go
/kind feature
the SQL spec option 'if exists'/'if not exists' is only supported by MariaDB, so remove it.
> remove 'if exists' in alter table specs

- modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sjob/k8sjob.go
/kind bug
k8sjob executor status use jobName
> k8sjob query status use jobName

- modules/pipeline/pexpr/pexpr_params/task_params.go
- modules/pipeline/pipengine/reconciler/taskrun/task_loop.go
/kind bug
```yaml
version: "1.1"
stages:
- stage:
- custom-script:
alias: custom-script
image: centos:7
commands:
- echo "hello world"
loop:
break: task_status == 'Success'
strategy:
max_times: 5
decline_ratio: 2
decline_limit_sec: 60
interval_sec: 5
```
The loop judges that the current task cannot be obtained is a successful state. The above task execution will be executed 5 times. The reason is that the loop execution is before the storage, so the current task state needs to be passed for judgment.
> pipeline loop task generate params add current task status, because loop is before update current task db storage status

- docs/guides/deploy/How-to-install-Erda-zh.md
- docs/guides/deploy/How-to-install-Erda.md
/kind document
Helm get package version from Erda VERSION, not fixed 0.1.0.
/cherry-pick master
> update install doc: helm get package version from Erda VERSION

- modules/openapi/server.go
- modules/pkg/innerdomain/innerdomain.go
/kind polish
fix: update k8sHost to short domain and remove the CUSTOM_NAMESPACE=local env of openapi
/assign @sfwn 
> fix: update k8sHost to short domain

- modules/msp/resource/deploy/handlers/handler.go
- modules/msp/resource/utils/nacos_client.go
/kind bug
in cases msp service may shutdown when deploy is processing, thus may lead the tmcinstance stay at INIT status which should not be reused in next deploy request, so filter it. same reason for the instance_tenant.
> bugfix: optimize on deploy continuous processing when interrupted

- modules/dop/endpoints/pipeline.go
feature
pipeline merge branch allow wildcard
e.g.
```
on:
merge:
branches: 
- feature/*
```
> pipeline merge branch allow wildcard

- bundle/gen_example.go
- bundle/gen_example_test.go
/kind feature
Previously, when the example was generated, if the user customized the example, it was returned directly. It did not take into account that the example from the user was not a string. Now it is changed to that, if the user customizes the example, it will be converted into an escaped string.
> bugfix: fix generate schema example error

- bundle/audit.go
- modules/admin/manager/audit.go
/kind bug
fix(admin): export excel without orgID when the user is the administrator
> fix(admin): export excel without orgID when the user is administrator

- apistructs/extention.go
- modules/pipeline/services/pipelinesvc/create_task.go
- modules/pipeline/services/pipelinesvc/create_task_test.go
/kind feature
The apitest task will use the apitest executor when it is executed, but version 1.0 should use the schduler executor, version 2.0 only use the apitest executor, so the executor selection field is added to the action spec, and subsequent actions can choose the executor by themselves
action spec add field like: 
```yaml
executor:
executorKind: "APITEST"
executorName: "api-test"
```
> action spec adds the execution selector field, and the pipeline selects the executor according to the field

- modules/dop/endpoints/project.go
- modules/dop/endpoints/testplan.go
bug
Runtime nil pointer dereference
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/workBench/projects/387/issues/all?id=73766&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMTA3MyJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=429&type=BUG)
> Fix project list nil pointer dereference

- modules/orchestrator/endpoints/instance.go
/kind bug
fix: solve the problem of instance list get fail
https://erda-org.erda.cloud/erda/workBench/projects/387/issues/all?id=73823&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=BUG
/assign @sfwn …
> fix: solve the problem of instance list get fail

- modules/orchestrator/services/deployment/deployment_context.go
/kind bug
fix deploy panic when addon config is empty
- [nil point interface](https://erda.cloud/erda/workBench/projects/387/issues/all?id=74081&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDQzNiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=-1&type=BUG)
> fix orchestrator nil pointer dereference error

- apistructs/cluster_info.go
- modules/hepa/repository/service/gateway_kong_info_service.go
- modules/pipeline/pipengine/reconciler/taskrun/taskop/prepare.go
- pkg/netportal/netportal.go
/kind bug
acquire the netportal url by "inet://" + clusterName, not from scheduler api.
> fix the cluster netportal acquisition logic

- erda.yml
/kind feature
The default value of `cpu` should be equal to `max_cpu`(which does not work in erda but works in erda operator).
We use resource oversold to set a  less `request cpu` in erda.
> update cluster-agent/cluster-dailer resource request

- modules/dop/endpoints/projectpipelinefiletree.go
bug
Fix pipeline filetree node, add url unescape before decoding node path
/assign @sfwn
> Fix pipeline filetree node, add url unescape before decoding node path

- pkg/database/sqlparser/migrator/scripts.go
/kind feature
select migration history without module name, because filename is globally unique
> fix: select migration history without module name

- apistructs/autotest_scene.go
- modules/dop/services/autotest_v2/scene.go
- modules/openapi/component-protocol/scenarios/auto-test-scenes/components/apiEditor/helper.go
- modules/openapi/component-protocol/scenarios/auto-test-scenes/components/apiEditor/helper_test.go
- modules/openapi/component-protocol/scenarios/auto-test-scenes/components/apiEditor/render.go
- modules/pipeline/pexpr/pexpr_params/task_params.go
/kind feature
autotest add loop field, that some test cace can wait other case output
erda issue: [erda-issue](https://erda.cloud/erda/workBench/projects/387/issues/all?id=70717&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDU2MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=REQUIREMENT)
> autotest add loop field

- bundle/pipeline.go
- modules/dop/endpoints/getpipelinelink_test.go
- modules/dop/endpoints/pipeline.go
- modules/dop/services/apierrors/errors.go
- modules/pipeline/services/pipelinesvc/run.go
- pkg/http/httpserver/errorresp/errors.go
- pkg/http/httpserver/errorresp/response.go
- pkg/http/httpserver/ierror/ierror.go
- pkg/http/httpserver/response.go
(cherry picked from commit 29d9fa6495b4f1413e41573b39c993530ab967ec)
kind bug
When there is a task that is already being executed in the pipeline, the link error of clicking the execution prompt is wrong
Steps to reproduce:
Corresponding to the existing branch of yml, click to create a new pipeline when executing, an error message is displayed, and the copy link cannot be opened
> fix PipelineLink url

- modules/pipeline/dbclient/dbclient.go
/kind bug
set charset=utf8mb4&collation=utf8mb4_unicode_ci when connect to mysql if env: mysql_url is null
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/workBench/projects/387/issues/all?id=201276&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=429&type=BUG)
> set charset utf8mb4 and set collation utf8mb4_unicode_ci if url is null

- .erda/migrations/cmdb/20210721-fixAuditHistory.sql
/kind bug
If the fields of table `dice_audit_history` and table `dice_audit` are inconsistent, the audit archive will fail
/assign @Effet
> fix table audit_history error

- modules/dop/endpoints/projectpipelinefiletree.go
bug
before decode inode path, add url queryunescape inode in delete and find ancestor file tree node
/assign @sfwn
> Url queryunescape inode in delete and find ancestor file tree node

- go.mod
- go.sum
- modules/dicehub/image/image.service.go
- modules/dicehub/image/image.service_test.go
- modules/dicehub/image/provider.go
/kind feature
move provider named dicehub to corn in erda-proto
update import
> move dicehub to core in proto

- apistructs/org.go
- modules/core-services/endpoints/organization.go
- modules/core-services/model/organization.go
- modules/dop/endpoints/issue_callback.go
/kind feature
Too many personal messages, the mail server has a limit on the number of emails sent
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=202091&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDQzNiJdfQ%3D%3D&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=429&type=TASK)
/assign @sfwn @Effet 
> add a send email switch for personal message

- erda.yml
/kind bug
discover detect use gprc port as PIPELINE_ADDR, so bundle invoke get malformed response.
> erda.yml declare global PIPELINE_ADDR for discover multi-port random-detect

- modules/dop/services/cdp/cdp.go
- pkg/erda-configs/i18n/notify_item.yml
kind feature
You can directly click on the url in the Dingding group to enter the pipeline page
https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/requirement?id=65866&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&type=requirement
old:
now:
> add pipeline event url

- modules/cmp/initialize.go
/kind bug
fix: cancel autoScanner due to open source
https://erda.cloud/erda/dop/projects/387/issues/all?id=202413&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=429&type=BUG …
> fix: cancel autoScanner

- modules/openapi/component-protocol/scenarios/action/components/actionForm/render.go
kind bug
Modified the problem that the componentized protocol cannot be executed when creating a new action node
pre:
now:
> fix action component protocol

- modules/dop/services/autotest/global_config.go
/kind bug
autotest add missing kvs when create global configs
> hotfix: autotest add missing kvs when create global configs

- modules/openapi/component-protocol/scenarios/auto-test-scenes/components/apiEditor/render.go
- modules/openapi/component-protocol/scenarios/auto-test-scenes/components/inParamsForm/inParamsForm.go
/kind bug
autotest api-test step use configs add autoest prefix
erda-issue: [erda-issue](https://erda.cloud/erda/dop/projects/387/issues/bug?id=202597&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDU2MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=BUG)
> autotest configs bug fix

- modules/pipeline/dbclient/op_pipeline_event.go
- modules/pipeline/dbclient/op_pipeline_event_test.go
/kind bug
The order of the records of the pipeline events is modified. The original count number and the order of the records is not correct, events should be able to express the order instead of just counting.
erda-issue: [erda-issue](https://erda.cloud/erda/dop/projects/387/issues/all?id=200490&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDU2MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG)
> pipeline events show order

- modules/pipeline/dbclient/op_pipeline_cron.go
- modules/pipeline/services/crondsvc/crond.go
- modules/pipeline/services/crondsvc/crond_test.go
- modules/pipeline/services/crondsvc/define.go
- modules/pipeline/services/pipelinecronsvc/define.go
- modules/pipeline/services/pipelinesvc/create_v2.go
/kind bug
It turns out that when the timed task is updated or deleted, the timed task list is loaded from the database in batches. If there is always a timed task update, all the timed tasks will be unavailable.
erda-issue: [erda-issue](https://terminus-org.app.terminus.io/erda/workBench/projects/387/issues/all?id=69217&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDU2MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=BUG)
> add or delete cron task use go channel watch remove watch etcd

- pkg/erda-configs/i18n/notify_item.yml
/kind bug
fix that the personal message mailbox cannot access the project link
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=200998&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDQzNiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=BUG)
> fix that the personal message mailbox cannot access the project link

- apistructs/autotest.go
- modules/dop/services/autotest/global_config.go
- modules/openapi/component-protocol/scenarios/action/components/actionForm/render.go
/kind feature
The original parameter configuration of the automated test is not sorted. When there are too many, the previously created ones will always be in the front.
erda-issue: [erda-issue](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=72042&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDU2MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=BUG)
need cherry-pick release/1.2
> autotest configs order by update time

- conf/dicehub/dicehub.yaml
/kind bug
delete  EXTENSION_MENU in dicehub provider.
it is useless now
> delete dicehub yml extension_menu

- quick-start/quick-start.sh
/kind bug
fixed quick-start.sh
1. after clone repository, switching the working directory does not take effect.
2. tell *nix shell which interpreter to run
> fixed quick-start.sh

- apistructs/pipeline_status.go
- modules/pipeline/events/manager.go
- modules/pipeline/pipengine/reconciler/listen.go
- modules/pipeline/pipengine/reconciler/reconcile.go
- modules/pipeline/pipengine/reconciler/teardown.go
- modules/pipeline/pipengine/reconciler/teardown_test.go
/kind bug
move update pipeline status from reconcile to listen
avoid concurrent update pipeline status
- [Erda Cloud Issue Link](https://erda.cloud/erda/workBench/projects/387/issues/all?id=67613&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls0MzEsNDY3XSwic3RhdGVCZWxvbmdzIjpbIk9QRU4iLCJXT1JLSU5HIiwiUkVPUEVOIiwiUkVTT0xWRUQiLCJXT05URklYIl0sImFzc2lnbmVlSURzIjpbIjU1IiwiMTAwMTIwNSIsIjkyIiwiMTAwMDQzNiIsIjEwMDA1NjAiLCIxMDAxMjYxIiwiMTAwMTA3MyIsIjEwMDA4MDUiLCIxMDAwODMyIl0sImZpbmlzaGVkQXRTdGFydEVuZCI6W251bGwsMTYyNzIyODc5OTk5OV19&issueGantt__urlQuery=eyJ0b3RhbCI6MTYsInBhZ2VObyI6MSwicGFnZVNpemUiOjIwMCwiaXNzdWVWaWV3R3JvdXBWYWx1ZSI6ImdhbnR0IiwiSXNzdWVUeXBlIjoiQUxMIn0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6Imd …
> move update pipeline status from reconcile to listen

- modules/gittar/pkg/gitmodule/repo_edit.go
/kind bug
fix: trim space of the field in createCommit validate
https://erda.cloud/erda/dop/projects/387/issues/all?id=203071&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMTI2MSJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=BUG
- [Erda Cloud Issue Link](paste your link herefix: trim space of the field in createCommit validate)
/assign @sfwn 
> For …
> fix: trim space of the field in createCommit validate

- modules/core-services/endpoints/organization.go
feature
Remove deprecated org prefix in org dto domain
| 🇺🇸 English | Remove organization prefix in domain of official website redirect link  |
| 🇨🇳 中文    | 官网跳转erda.cloud链接域名移除组织前缀   |
> Remove deprecated org prefix in org dto domain

- modules/dop/services/cdp/cdp.go
/kind bug
https://erda.cloud/erda/dop/projects/387/issues/bug?id=204104&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&type=bug
Return a paragraph of text instead of the end after the query log fails
> fix Log display

- modules/pipeline/pipengine/reconciler/listen.go
/kind bug
if status is end status like stopByUser, should return immediately
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=204383&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=BUG)
> if end status don`t calculate status

- modules/pipeline/pipengine/reconciler/listen.go
/kind bug
The events sent when the pipeline is updated to the running state are missing information, which will cause the FDP service to report an error
erda-issue: [erda-issue](https://erda-org.erda.cloud/erda/dop/projects/387/issues/bug?id=204419&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=467&type=BUG)
> bugfix pipeline send running events lost info

- modules/eventbox/webhook/builtin.go
- modules/scheduler/server/server.go
/kind bug
1. remove eventbox buildin scheduler webhook
2. add scheduler register cluster event webohook
| 🇺🇸 English |     scheduler maybe register empty address to eventbox         |
| 🇨🇳 中文    |     修复 Erda 部署时，scheduler webhook 注册到 eventbox 中为空的情况         |
> fix: scheduler maybe register empty address to eventbox

- modules/dicehub/service/extension/extension.go
- modules/dicehub/service/extension/git.go
/kind feature
Modified the code of the DiceHub module
Support to get pipeline-action from git
Support to concurrent query extension 
pipeline get  pipeline-action definition form erda-action project before. In order to debug pipeline-action ,support get it form git
because get pipeline-action form git need a lot of time. Support concurrent query. Call the interface once for about 5 seconds
> Support to get Action from git, in order to debug Action quickly 

- pkg/nexus/nexus.go
/kind bug
when update publisher request nexus will timeout
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/bug?id=205345&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwibGFiZWxJRHMiOlsyMDU2XX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=431&type=BUG)
> modify nexus timeout

- modules/openapi/component-protocol/scenarios/action/components/actionForm/render.go
- modules/openapi/component-protocol/scenarios/action/components/actionForm/testplan-run.go
- modules/openapi/component-protocol/scenarios/action/components/actionForm/testplan-run_test.go
/kind feature
In order not to waste too much time in unimportant automated tests when executing ci/cd, asynchronous capabilities are provided.
When asynchronous, testplan-run action will execute the pipeline, and then it will end directly, without paying attention to the success or failure of the pipeline
> add Asynchronous ability for testplan-run action

- modules/scheduler/executor/plugins/k8s/k8s.go
- modules/scheduler/executor/util/util.go
- modules/scheduler/executor/util/util_test.go
/kind bug
fix: manage config is nil in edas executor
/assign @luobily @wangyc117 
| 🇺🇸 English |  fix: manage config is nil in edas executor            |
| 🇨🇳 中文    |    修复 Edas 在1.2版本中变更迁移 GetClient 函数导致的 manage config nil          |
> fix: manage config is nil in edas executor

- modules/dop/endpoints/pipeline.go
/kind bug
The pipeline cannot be triggered when merging, and it is found that there is a problem with the code logic, and it breaks directly when it matches the branch.
Test link:[Test](https://erda.dev.terminus.io/terminus/dop/projects/2/apps/142)
Steps:
1. Create a new master branch
2. Create a develop branch based on the master branch
3. Create a pipeline.yml file in the develop branch and add on merge
4. Create a merge request from develop to master
Results of the test:
> Modified the problem that the pipeline cannot be triggered when on merge

- modules/openapi/api/generate/generate_doc.go
- modules/scheduler/executor/plugins/edas/edas.go
/kind bug
- update(edas): return error when application list is zero
| 🇺🇸 English |update(edas): return error when application list is zero |
| 🇨🇳 中文    | 为 edas 获取列表时，若列表数量为空，则直接报错返回|
> update(edas): return error when application list is zero

- bundle/msp.go
- modules/msp/resource/deploy/handlers/handler.go
- modules/msp/resource/deploy/handlers/handler_test.go
/kind bug
createtenant request to hepa, processing is slow, should increase the timeout value, and should not retry because the processing is not idempotent
/assign @johnlanni
> optimize: not retry on post request to hepa

- Makefile
- build/dockerfiles/Dockerfile
- build/scripts/dicehub/extension-push.sh
- build/scripts/docker_image.sh
- modules/dicehub/extension/action.go
- modules/dicehub/extension/action_test.go
- modules/dicehub/extension/db/extension.go
- modules/dicehub/extension/extention.service.go
- modules/dicehub/extension/provider.go
/kind feature
Before, push extension need admin permission
Therefore, open source users who want to push extensions need to create an admin account first.
To solve this problem, allow users to push extensions from external repositories
When packaging the image, download the external code, and every time the “dicehub” provider is started,  new actions will be created according to the action in the external repositories
if want to push extension in erda-addons and erda-actions, you can use it to build docker image.
`make build-push-image MODULE_PATH=dicehub EXTENSION_ADDR="https://codeload.github.com/erda-project/erda-addons/zip/master,https://codeload.github.com/erda-project/erda-actions/zip/master"`
I delete some extension in DEV sql . and update image
> Support pushing Extension from external repository，push extension no longer requires admin account

- modules/monitor/alert/alert-apis/adapt/alert_convert.go
- modules/monitor/alert/alert-apis/adapt/customize.go
- modules/monitor/alert/alert-apis/org-custom-apis.go
/kind bug
chngc set cluster_name in filter rule but invalidate
| 🇺🇸 English |      chngc set cluster_name does not take effect when it exists in custom filter rules        |
| 🇨🇳 中文    |       中国金币设置cluster_name在自定义过滤规则中存在时不生效       |
> chngc set cluster_name in filter rule but invalidate

- modules/dop/conf/conf.go
/kind feature
set env nexus_username and nexus_password not require
e.g. dice-addons-info
```yaml
NEXUS_ADDR: maven.aliyun.com
NEXUS_PUBLIC_URL: maven.aliyun.com
```
tested at erda-demo which deployed by helm
/assign @sfwn 
| 🇺🇸 English |  set env nexus_username and nexus_password not require            |
| 🇨🇳 中文    |    设置 DOP 环境变量 nexus username 以及 password 不是必需的          |
/cherry-pick release/1.1 release/1.2 …
> feature: set env nexus_username and nexus_password not require

- modules/openapi/component-protocol/scenarios/app-pipeline-tree/components/fileTree/render.go
- modules/openapi/component-protocol/scenarios/app-pipeline-tree/components/nodeFormModal/render.go
- pkg/erda-configs/i18n/pipeline.json
/kind bug
In the case of the project market in English, the title of each statistical chart is still in Chinese, and two English market configurations are added, so that the English environment can query the English market configuration
erda-issue: [erda-issue](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=206478&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDU2MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG)
> pipeline filetree add il8n format

- modules/core/monitor/alert/alert-apis/adapt/alert_convert.go
/kind bug
| 🇺🇸 English |      Use system built-in rules to create an alarm report assert cluster_name or application_is is failed        |
| 🇨🇳 中文    |        使用系统内置规则创建告警报assert cluster_name or application_is is failed      |
> create alert rule is failed

- Makefile
- build/dockerfiles/Dockerfile
- build/scripts/dicehub/extension-push.sh
- build/scripts/docker_image.sh
- modules/dicehub/dbclient/extention.go
- modules/dicehub/endpoints/endpoints.go
- modules/dicehub/initialize.go
- modules/dicehub/service/extension/action.go
- modules/dicehub/service/extension/extension.action_test.go
/kind feature
Before, push extension need admin permission
Therefore, open source users who want to push extensions need to create an admin account first.
To solve this problem, allow users to push extensions from external repositories
When packaging the image, download the external code, and every time the “dicehub” is started, new actions will be created according to the action in the external repositories
if want to push extension in erda-addons and erda-actions, you can use it to build docker image.
make build-push-image MODULE_PATH=dicehub EXTENSION_ZIP_ADDRS="https://github.com/erda-project/erda-actions/archive/refs/heads/master.zip"
The original PR is based on the extension provider, release/1.2 does not have an extension provider yet, so this pr was created for release/1.2 …
> release/1.2 support push extension no need Admin account

- modules/scheduler/executor/plugins/k8s/instanceinfosync/gc.go
- modules/scheduler/executor/plugins/k8s/instanceinfosync/sync.go
- modules/scheduler/executor/plugins/k8s/k8s.go
/kind bug
- fix(scheduler): sync instance info memory leak
| 🇺🇸 English | fix(scheduler): sync instance info memory leak |
| 🇨🇳 中文    |修复获取实例列表内存泄漏的问题|
> fix(scheduler): sync instance info memory leak

- modules/openapi/component-protocol/scenarios/issue-manage/components/issueFilter/state_conditions.go
- modules/openapi/component-protocol/scenarios/issue-manage/components/issueFilter/state_conditions_test.go
feature
Put selected users at the top of issue filter list, make it easy to select/unselect.
| 🇺🇸 English |  Put selected users at the top of issue management filter list  |
| 🇨🇳 中文    |   事项协同里已选择的用户放在过滤器列表最前面     |
> Put selected users at the top of issue filter list

- Makefile
- build/dockerfiles/Dockerfile
/kind feature
when "make build-push-all" ,add extension file in image for init extension data in SQL
I have tested it:
only keep dicehub and dop in /cmd 
make build-push-all EXTENSION_ZIP_ADDRS="https://github.com/erda-project/erda-actions/archive/refs/heads/master.zip"
docker run 
extensions dir is right
> when "make build-push-all" ,add extension file in image

- quick-start/docker-compose.yml
- quick-start/quick-start.sh
/kind feature
- update quick-start image to v1.2
- auto check and modify the vm.max_map_count, see issue [here](https://github.com/docker-library/elasticsearch/issues/111)
> update quick-start image to v1.2

- modules/pipeline/services/pipelinesvc/passedDataWhenCreate.go
- modules/pipeline/services/pipelinesvc/passedDataWhenCreate_test.go
/kind bug
The passedDataWhenCreate method will read the map concurrently, which will cause the pipeline to restart
erda-issue: [erda-issue](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=206764&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDU2MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=BUG)
> when creating a pipeline to cache action information, add a lock to read the map

- apistructs/pipeline_task.go
- apistructs/pipeline_task_test.go
- modules/pipeline/pipengine/reconciler/task.go
- modules/pipeline/pipengine/reconciler/task_test.go
- modules/pipeline/pipengine/reconciler/taskrun/framework.go
- modules/pipeline/pipengine/reconciler/taskrun/taskop/prepare.go
- modules/pipeline/pipengine/reconciler/taskrun/update.go
- modules/pipeline/pkg/errorsx/errors.go
- modules/pipeline/pkg/errorsx/errors_test.go
- modules/pipeline/services/pipelinesvc/callback.go
- modules/pipeline/services/pipelinesvc/callback_test.go
- modules/pipeline/spec/pipeline_task.go
/kind bug
add two error type(platform, user)
retry reconcile task always  if error is platform error
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=207028&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=TASK)
@sfwn
> retry reconcile task until no platform errors

- apistructs/service.go
- modules/scheduler/executor/plugins/k8s/addon/interface.go
- modules/scheduler/executor/plugins/k8s/deployment.go
- modules/scheduler/executor/plugins/k8s/deployment/deployment.go
- modules/scheduler/executor/plugins/k8s/k8s.go
- modules/scheduler/impl/servicegroup/servicegroup.go
- pkg/parser/diceyml/define.go
- pkg/parser/diceyml/diceyml.go
- pkg/parser/diceyml/diceyml_test.go
- pkg/parser/diceyml/fieldname_validate_visitor.go
- pkg/parser/diceyml/utils.go
/kind feature
we can use k8s_snippet in the erda.yml like this:
```yaml
version: 2.0
services:
web:
ports:
- port: 8080
deployments:
replicas: 1
resources:
cpu: 1
mem: 512
k8s_snippet:
container:
readinessProbe:
failureThreshold: 20
periodSeconds: 15
successThreshold: 1
tcpSocket:
port: 8080
timeoutSeconds: 10
```
| 🇺🇸 English |   erda.yml now support the `k8s_snippet` field which will patch to the container definition of the k8s deployment resource.   |
| 🇨🇳 中文    |   erda.yml 支持了一个新字段 `k8s_snippet`，可以调整对应的 k8s deployment 中关于 container 的配置定义  | …
> support patch container snippet through erda.yml

- modules/orchestrator/services/addon/addon.go
- modules/orchestrator/services/addon/addon_test.go
/kind feature
feature: change the error prompt from Chinese to English for addon delete
https://erda.cloud/erda/dop/projects/387/issues/all?id=206519&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG
/assign @sfwn  …
> fix: change the error prompt from Chinese to English for addon delete

- modules/dicehub/extension/action.go
/kind feature
in infos, cur.Isdir() must be true . No need to judge
add /addons in init extension path 
if push failed, return name and version
> Support pushing extensions according to the git directory of repo/addons

- modules/dicehub/service/extension/action.go
/kind feature
in infos, cur.Isdir() must be true . No need to judge
add /addons in init extension path
if push failed, return name and version
> release/1.2 Support pushing extensions according to the git directory of repo/addons

- apistructs/pipeline_task.go
- apistructs/pipeline_task_test.go
- modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sjob/k8sjob.go
- modules/pipeline/pipengine/actionexecutor/plugins/scheduler/scheduler.go
- modules/pipeline/pipengine/actionexecutor/plugins/scheduler/scheduler_test.go
/kind bug
restore task uuid after remove in cancel func, because gc will make job id but cancel don't make job id
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=209285&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=-1&type=BUG)
| 🇺🇸 English |  fix stop by user task uuid bug            |
| 🇨🇳 中文    |   修复stopbyuser时将taskuuid修改的问题           |
> restore task uuid after cancel

- apistructs/component_protocol.go
- apistructs/steve.go
- bundle/steve.go
- bundle/steve_node.go
- modules/cmp/steve/aggregator.go
- modules/openapi/api/apis/cmp/cmp_k8s_create.go
- modules/openapi/api/apis/cmp/cmp_k8s_get.go
- modules/openapi/api/apis/cmp/cmp_k8s_list.go
- modules/openapi/api/apis/cmp/cmp_k8s_update.go
- modules/openapi/component-protocol/scenarios/cmp-dashboard-events/components/eventTable/model.go
- modules/openapi/component-protocol/scenarios/cmp-dashboard-events/components/eventTable/render.go
- modules/openapi/component-protocol/scenarios/cmp-dashboard-events/components/eventTable/render_test.go
- modules/openapi/component-protocol/scenarios/cmp-dashboard-events/components/filter/model.go
- modules/openapi/component-protocol/scenarios/cmp-dashboard-events/components/filter/render.go
- modules/openapi/component-protocol/scenarios/cmp-dashboard-events/components/filter/render_test.go
- modules/openapi/component-protocol/scenarios/cmp-dashboard-events/protocol.yml
/kind feature
1. modify bundle and apistruct for steve server
2. add component protocol scenario events list for dashboard
> feat: add event list scenario

- modules/dop/services/cdp/cdp.go
- modules/orchestrator/services/runtime/runtime.go
- modules/orchestrator/services/runtime/runtime_test.go
/kind bug
Reason: In this case, the PipelineYmlName of the pipeline running is not bound to the branch
Basic feasible solution: bind the newly created pipeline during redeployment to the default pipeline on the master branch
[Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=209949&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDgwNSJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=431&type=BUG)
/assign sfwn
> fix Redeploy pipelineYmlName

- modules/msp/tenant/db/dbmock.go
- modules/msp/tenant/db/project_test.go
- modules/msp/tenant/project/project.service.go
- modules/msp/tenant/project/project.service_test.go
- modules/openapi/api/apis/msp/tenant/project/get_msp_metric_project_overview.go
Cherry pick of #1524 on release/1.2.
Squashed commit message:
```
commit c9061f040f539f4a74c05a5d56098e322baa82da
Author: innerpeacez <innerpeace.zhai@gmail.com>
Date:   Wed Aug 25 16:54:53 2021 +0800
bugfix:fix msp project overview (#1524)
* fix msp project overview
* add test ut
* add ut TestMSPProjectDB_Query()
* import format
* add license and add uts
* add ut Test_projectService_DeleteProject()
```
/kind bug
project overview data error.
delete old project fail.
Specified Reviewers:
> Cherry pick of #1524: bugfix:fix msp project overview

- erda.yml
/kind bugfix
magic temp hack: dop inject DOP_ADDR to localhost:9527 to fix internal invoke timeout issue in cp.
TODO change to internal method invoke in component-protocol and remove this hack.
/assign @Effet
> magic temp hack: dop inject DOP_ADDR to localhost:9527 to fix internal invoke timeout issue in cp

- modules/core-services/dao/mbox.go
- modules/core-services/endpoints/endpoints.go
- modules/core-services/endpoints/mbox.go
- modules/core-services/services/apierrors/errors.go
- modules/core-services/services/mbox/mbox.go
- modules/openapi/api/apis/core_services/cmdb_mbox_read_all.go
/kind feature
add feature: read all unread mbox with one click
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=202613&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDQzNiJdfQ%3D%3D&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=REQUIREMENT)
/assign @Effet
> read all unread mbox with one click

- modules/scheduler/executor/plugins/edas/edas.go
- modules/scheduler/executor/plugins/k8s/addon/redis/redis.go
- modules/scheduler/executor/plugins/k8s/statefulset.go
- modules/scheduler/executor/plugins/k8s/statefulset_test.go
/kind feature
- feat(addon): set addon_id/Redis label for the addon to split pod to different nodes
| 🇺🇸 English |  feat(addon): support set addon_id/Redis label for the addon to split pod to different nodes  |
| 🇨🇳 中文    |   支持给 addon 设置 addon_id 或 redis 标签，以便将 pod 打散到不通的节点上           | …
> feat(addon): set addon_id/redis label for the addon to split pod to different nodes

- go.mod
- modules/openapi/api/apis/openapi/component_protocol/notspec_response.go
/kind bugfix
openapi cp proxy show logic error correctly.
Json Unmarshal will use embed pb struct's custom unmarshal method before this change, so `code` and `err` will be ignored.
Before:
After: 
/assign @Effet
> fix: openapi cp proxy resolve embed unmarshal to show logic error

- pkg/parser/diceyml/servicename_visitor.go
/kind bug
Service name mandatory lowercase only
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=71555&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDQzNiJdfQ%3D%3D&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG)
/assign @Effet
> service name can only be lowercase

- conf/monitor/monitor/chartview/report/bug.json
- conf/monitor/monitor/chartview/report/working.json
/kind bug
In the case of the project market in English, the title of each statistical chart is still in Chinese, and two English market configurations are added, so that the English environment can query the English market configuration
erda-issue: [erda-issue](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=206478&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDU2MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG)
> project dashboard add internationalization

- modules/dop/component-protocol/components/issue-manage/issueTable/render.go
- modules/dop/component-protocol/components/issue-manage/issueTable/render_test.go
bug
Fix page size reset to default when filter conditions change
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=208473&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMTA3MyJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=506&type=BUG)
/assign @sfwn
> Fix page size reset to default when filter conditions change

- modules/gittar/auth/auth.go
/kind feature
fix: remove git inner user
[gittar 删除内置 git_inner_user](https://erda.cloud/erda/dop/projects/387/issues/all?id=208148&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=TASK)
/assign @sfwn 
| 🇺🇸 English |     remove git inner user         |
| 🇨🇳 中文    |      gittar删除内置 git inner user        |
> For details on the cherry pick process, see the …
> feature: remove git inner user

- modules/dop/endpoints/apidoc.go
- modules/dop/services/apidocsvc/api_docs.go
- modules/dop/services/apidocsvc/filetree.go
- modules/dop/services/apidocsvc/funcs.go
- modules/dop/services/apidocsvc/ws_handler.go
- modules/dop/services/apidocsvc/ws_upgrade.go
/kind feature
- do not query whether there are documents under the branch
> feature: do not query whether there are documents under the branch

- modules/cmp/impl/clusters/import_cluster.go
/kind bug
label node when import cluster（erda inner cluster）
| 🇺🇸 English |  label node when import cluster（erda inner cluster）            |
| 🇨🇳 中文    |    修复导入 Erda 所在 Kubernetes 集群时未打企业标的问题          |
> fix: label node when import cluster which erda inner

- bundle/addon.go
- modules/openapi/component-protocol/scenarios/action/components/actionForm/mysql-cli.go
- modules/openapi/component-protocol/scenarios/action/components/actionForm/mysql-cli_test.go
- modules/openapi/component-protocol/scenarios/action/components/actionForm/render.go
/kind feature
mysql-cli action add componentized rendering, In this way, the user can automatically fill in the database after selecting the data source
erda-issue: [erda-issue](https://erda.cloud/erda/dop/projects/387/issues/all?id=57004&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDU2MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG)
Associated pr: https://github.com/erda-project/erda-actions/pull/177#issue-724284291
> mysql-cli action render

- pkg/parser/pipelineyml/graph_pipelineyml.go
- pkg/parser/pipelineyml/graph_pipelineyml_test.go
- pkg/parser/pipelineyml/visitor_cron.go
/kind bug
The default timing compensation will make users think that this is a timing task switch, so the default timing compensation configuration is removed
erda-issue: [erda-issue](https://erda.cloud/erda/dop/projects/387/issues/all?id=210303&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDU2MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=TASK)
> pipeline remove default cron compensator

- modules/core/openapi-ng/interceptors/csrf/csrf.go
/kind feature
Not return set-cookie if token is valid.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/bug?id=219588&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJSRU9QRU4iXSwibGFiZWxJRHMiOlsxNDUzXX0%3D&issueGantt__urlQuery=eyJ0b3RhbCI6NjQsInBhZ2VObyI6MSwicGFnZVNpemUiOjIwMCwiaXNzdWVWaWV3R3JvdXBWYWx1ZSI6ImdhbnR0IiwiSXNzdWVUeXBlIjoiQlVHIn0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTAwfQ%3D%3D&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=506&type=BUG)
/assign @recallsong
> csrf-interceptor set-cookie if token is invalid

- modules/core/openapi-ng/auth/uc-session/login.go
- modules/core/openapi-ng/interceptors/csrf/csrf.go
/kind bug
- get csrf secure from referer firstly
- set default http-only to true
before set http-only: 
after set http-only:
> get csrf secure from referer firstly; set default http-only to true

- modules/core/openapi-ng/interceptors/csrf/csrf.go
- modules/pipeline/aop/plugins/task/autotest_cookie_keep_before/cookie.go
- modules/pipeline/aop/plugins/task/autotest_cookie_keep_before/cookie_test.go
- modules/pipeline/aop/plugins/task/autotest_cookie_keep_before/plugin.go
/kind bugfix
After this pr, autotest's set-cookie will not overwrite all existed cookie. 
Otherwise, a single set-cookie will cause other cookie lost and 401 indeed.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=219588&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiOTIiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG)
screenshot see erda issue
/assign @Effet @kakj-go
> bugfix: autotest set-cookie do not overwrite all existed cookie

- apistructs/testplan_v2.go
- modules/dop/dao/testplan_v2.go
- modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/table/render.go
- modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/table/table_test.go
- modules/openapi/component-protocol/scenarios/auto-test-plan-list/protocol.yml
/kind feature
add executeTime and passRate in autotest-plan table component
> show executeTime and passRate in autotest-plan list

- .erda/migrations/qa/20210906-auto-test-plan-execute.sql
/kind bug
TIMESTAMP DEFAULT NULL => datetime DEFAULT NULL
> fix autotest-testplan sql

- modules/dop/dao/testplan_v2.go
- modules/openapi/component-protocol/scenarios/auto-test-plan-detail/protocol.yml
- modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/table/render.go
- modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/table/table_test.go
/kind bug
func (tp *TestPlanV2Join) Convert2DTO() will cause duplicate executeTime
change  *TestPlanV2Join to TestPlanV2Join
plan env should refresh when click ExecuteHistoryTable
> fix BUG: duplicate data in the test plan list and the env of plan is not refreshed

- modules/pipeline/services/pipelinesvc/snippet.go
- modules/pipeline/services/pipelinesvc/snippet_test.go
/kind bug
The version field is not passed when querying the action details on the front end, and the query interface will return a 404 error
> Solve the failure of querying node details without passing version

- modules/gittar/auth/auth.go
/kind bug
fix: modify the error message returned
/assign @sfwn 
| 🇺🇸 English |      修改返回的错误信息        |
| 🇨🇳 中文    |      modify the error message returned        |
> fix: modify the error message returned

- pkg/erda-configs/permission/backend/sys/org/project/project.yml
/kind bug
change permission of autotest space
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/bug?id=220551&issueFilter__urlQuery=eyJ0aXRsZSI6IumbhuaIkOeOr%2BWigyIsInN0YXRlQmVsb25ncyI6WyJPUEVOIiwiV09SS0lORyIsIldPTlRGSVgiLCJSRU9QRU4iLCJSRVNPTFZFRCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=506&type=BUG)
| 🇺🇸 English | change permission of autotest space             |
| 🇨🇳 中文    |  增加研发主管,测试工程师有权限创建测试空间            |
> change permission of autotest space

- conf/dicehub/dicehub.yaml
- modules/dicehub/extension/action.go
- modules/dicehub/extension/provider.go
- modules/dicehub/extension/provider_test.go
/kind feature
Timed tasks automatically synchronize the extension information of the git address
erda-issue: [erda-issue](https://erda.cloud/erda/dop/projects/387/issues/all?id=209340&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDU2MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=TASK)
> Timed tasks automatically synchronize the extension information of the git address

- build/scripts/docker_image.sh
- modules/dop/provider.go
- modules/pipeline/providers/definition_client/deftype/client_process.go
- modules/pipeline/providers/definition_client/provider.go
- modules/pipeline/providers/definition_client/provider_test.go
/kind feature
synchronize autotest, config-sheet, project-pipeline, gittar-pipeline to pipeline in dop
erda-issue: [erda-issue](https://erda.cloud/erda/dop/projects/387/issues/all?id=206835&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDU2MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=TASK)
> pipeline definition sync provider

- cmd/orchestrator/main.go
- conf/orchestrator/orchestrator.yaml
/kind bug
###
Only GET /api/runtimes/{:idOrName} was refactored, however Delete /api/runtimes/{:idOrName} was also handled by new http server unexpectedly. Revert the change to fix the runtimes can't delete.
> revert proto refactor temporary to fix delete runtime bug

- modules/cmp/provider.go
/kind bug
After move component-protocol to cmp, it will send request to itseltf. Change path to localhost in that case.
> fix: set localhost in cmp self request

- conf/pipeline/pipeline.yaml
- modules/pipeline/initialize.go
- modules/pipeline/provider.go
/kind feature
When protobuf adds an open interface, the address port of the route will be old, and it is impossible to specify a route to any port, which causes the open interface declared by protobuf to be unable to be routed, so the pipeline components need to be changed to use the same routing port
> pipeline legacy and infra http server use the same route and port

- modules/dop/services/org/nexus.go
- modules/dop/services/org/nexus_test.go
/kind feature
Org-level nexus configs is heavy. Most org doesn't need these nexus configs.
If no nexus info, always return false.
Otherwise, judge by crossCluster and isPublisher.
/assign @Effet
> feature: org sync nexus configs only if crossCluster or isPublisher

- modules/dop/dao/testplan_v2.go
- modules/dop/services/autotest_v2/testplan_v2.go
- modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeTaskTable/render.go
- modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeTaskTable/render_test.go
- modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/table/render.go
- modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/table/table_test.go
/kind feature
Modify the type of the executed_time of the autotest-testplan,
if type is time.time{}. when data in SQL is NULL, after time.format(), will be 0001-01-01  
so modify it to *time.time
and fix the bug of taskHistoryTable will panic
| 🇺🇸 English |       modity the type of executed_time, fix  taskHistoryTable panic     |
| 🇨🇳 中文    |   修改执行时间的类型，修复执行历史记录列表可能panic的问题          |
> Modify the type of the executed_time of the autotest-testplan,and fix the bug of taskHistoryTable will panic

- build/dockerfiles/Dockerfile-cluster-ops
- pkg/helm/manager.go
/kind bug
fix cluster init error when use old version
e.g. if center cluster version is 1.2, latest erda version is 1.2.1.check installed can't match.
resolve: install doesn't need check install version, through warning instead error.
| 🇺🇸 English |  cluster init error when use old version            |
| 🇨🇳 中文    |   修复 Erda 版本号导致的集群初始化失败           | …
> fix: cluster init error when use old version

- modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/cancelExecuteButton/render.go
- modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/cancelExecuteButton/render_test.go
/kind bug
the problem of panic when clicking the execution details when there is no execution data
to
/assign @sfwn
> fix the problem of panic when clicking the execution details when there is no execution data

- erda.yml
/kind bug
add GOLANG_PROTOBUF_REGISTRATION_CONFLICT  env.
it will cause DOP pod start failed
| 🇺🇸 English |        fix bug: DOP pod failed to start  |
| 🇨🇳 中文    |      修复DOP容器无法启动的bug        |
> Fix bug: DOP pod failed to start

- modules/cmp/component-protocol/components/cmp-dashboard-podDetail/podStatus/render.go
- modules/cmp/component-protocol/components/cmp-dashboard-pods/podsTable/render.go
- modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/podsTable/render.go
/kind bug
1. Change pod color from lightgreen to green for Running status
2. Change pod metrics to "N/A" if result less than 1e-4
> update pod status color; display N/A when pod metrics less than 1e-4

- modules/dop/services/autotest_v2/scene.go
/kind bug
The automated test step is executed, and the parsing will fail when the output parameter is json
> Automated test step executes json output parameter analysis

- modules/core/openapi-ng/routes/openapi-v1/provider.go
- modules/core/openapi-ng/routes/openapi-v1/provider_test.go
/kind bug
openapi-ng fix router for openapi-v1 match-any
for examples:
- gittar `/api/repo/*`
- fdp `/api/fdp/*`
need /cherry-pick release/1.3
> openapi-ng fix router for openapi-v1 match-any

- modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/tabExecuteButton/executeButton.go
- modules/pipeline/aop/plugins/pipeline/testplan_after/plugin.go
- modules/pipeline/aop/plugins/pipeline/testplan_after/plugin_test.go
/kind bugfix
send messgae with orgID and projectID
eventBox get http path form webHook, if orgID and projectID are -1 ,will insert two httpPath
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/bug?id=222230&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDgzMiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=429&type=BUG)
> when testplan executed, send messgae with orgID and projectID

- .erda/migrations/cmdb/20210913-issue-subscriber-index.sql
bug
Issue subscriber userid column fit index length limit
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=222277&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMTA3MyJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=506&type=BUG)
> Issue subscriber userid column fit index length limit

- modules/cmp/component-protocol/components/cmp-dashboard-events-list/filter/render.go
- modules/cmp/component-protocol/components/cmp-dashboard-pods/filter/render.go
- modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/filter/render.go
- modules/cmp/steve/middleware/middleware_test.go
- modules/cmp/steve/middleware/shell_handler.go
/kind bug
cluster-agent pod has label dice/component=cluster-agent rather than app=cluster-agent when manual deploy.
> list agent pod by dice/component=cluster-agent label

- conf/dicehub/dicehub.yaml
- modules/dicehub/extension/provider.go
/kind bug
When multi instance dicehub synchronizes the extension, it is set that only a single instance can be synchronized
erda-issue: [erda-issue](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=210670&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDU2MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG)
test image:
> multi-instance dicehub synchronizes local extension

- modules/core/openapi-ng/interceptors/csrf/csrf.go
/kind bug
Frontend JS cannot set OPENAPI-CSRF-TOKEN header from cookie if http-only is true .
/assign @Effet @recallsong 
> fix: openapi csrf token set default to false

- modules/openapi/component-protocol/scenarios/action/components/actionForm/testplan-run.go
- modules/openapi/component-protocol/scenarios/action/components/actionForm/testscene_run.go
/kind bug
The data queried in the action drop-down box executed by the automated test plan is missing. All data should be queried, and then the search box should be searched.
> autotest plan action show search input, and set pageSize

- modules/gittar/auth/auth.go
- modules/gittar/auth/auth_test.go
- modules/gittar/initialize.go
- modules/gittar/models/web_hook.go
/kind feature
fix: gittar remove skipAuth
[【gittar】鉴权取消skipAuth](https://erda.cloud/erda/dop/projects/387/issues/all?id=222904&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=-1&type=TASK)
/assign @sfwn 
| 🇺🇸 English |      gittar remove skipAuth        |
| 🇨🇳 中文    |      取消skipAuth逻辑，使用协议来区分鉴权逻辑      |
> For details on the cherry pick process, see the [cherry …
> fix: gittar remove skipAuth

- modules/dop/services/filetree/filetree.go
/kind bug
The pipeline link deployed by the deployment center can be viewed in the pipeline
erda-issue: [erda-issue](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=222559&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDU2MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG)
> The pipeline link deployed by the deployment center can be viewed in the pipeline

- build/dockerfiles/Dockerfile-action-agent
- modules/actionagent/file_watch.go
- modules/actionagent/file_watch_collector.go
- modules/actionagent/file_watch_collector_test.go
- modules/actionagent/file_watch_test.go
- modules/actionagent/filewatch/watch.go
- modules/actionagent/prestop_test.go
/kind bug
Agent close filewatcher when action done.
Otherwise, filewatcher will wait 10s to force close it.
Tested on hkci.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=222900&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiOTIiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=506&type=BUG)
/assign @kakj-go @Effet 
1.3 & 1.2
> fix: actionagent close filewatcher when action done

- apistructs/cluster.go
- modules/pipeline/pipengine/actionexecutor/plugins/scheduler/logic/shceduleinfo.go
/kind bug
set enableWorkspace default true for bigdata job schedule
TODO: cluster-manager should control enableWorkspace, enableTag and so on
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/bug?id=202730&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiOTIiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=506&type=BUG)
| 🇺🇸 English | set enableWorkspace default true for bigdata job schedule …
> set enableWorkspace default true for bigdata job schedule

- modules/pipeline/services/pipelinesvc/precheck.go
- modules/pipeline/services/pipelinesvc/precheck_test.go
/kind bug
When release declares other yml files, but other files do not exist, the release precheck will not be executed, thus losing the cross-cluster logic
erda-issue: [erda-issue](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=71416&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDU2MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG)
> release cross cluster bugfix

- pkg/database/sqlparser/migrator/scripts.go
- pkg/database/sqlparser/migrator/scripts_test.go
- pkg/database/sqlparser/testdata/alter_permission_test_data2/service_a/318-1-err.sql
- pkg/database/sqlparser/testdata/alter_permission_test_data2/service_a/318-1.sql
- pkg/database/sqlparser/testdata/alter_permission_test_data3/service_a/318-1-err.sql
- pkg/database/sqlparser/testdata/alter_permission_test_data3/service_a/318-1.sql
/kind feature
feature: can not reference the table which is not created in the same moduel
> feature: can not reference the table which is not created in the same moduel

- modules/pipeline/pipengine/engine.go
- modules/pipeline/pipengine/reconciler/before_listen.go
- modules/pipeline/pipengine/reconciler/define.go
- modules/pipeline/pipengine/reconciler/listen.go
- modules/pipeline/pipengine/reconciler/queuemanage/manager/define.go
- modules/pipeline/pipengine/reconciler/queuemanage/manager/stop.go
- modules/pipeline/pipengine/reconciler/queuemanage/manager/stop_test.go
- modules/pipeline/pipengine/reconciler/queuemanage/types/manager.go
- modules/pipeline/pipengine/reconciler/throttler.go
- modules/pipeline/pipengine/reconciler/throttler_test.go
/kind bug
Stop queueManager&throttler when pipeline lost leader. Otherwise, multi pipeline queueManager instances will check & push pipeline in the meanwhile and cause error.
Tested in hkci.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=228022&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiOTIiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG)
/assign @chengjoey @Effet
> fix: stop queueManager&throttler when pipeline lost leader

- modules/pipeline/pipengine/actionexecutor/plugins/scheduler/scheduler.go
- modules/pipeline/pipengine/actionexecutor/plugins/scheduler/scheduler_test.go
/kind bug
modify scheduler log info
| 🇺🇸 English | modify scheduler log info             |
| 🇨🇳 中文    |   修改pipeline的scheduler日志输出           |
> modify scheduler log info

- modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeInfo/render.go
- modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeInfo/render_test.go
- modules/pipeline/aop/plugins/pipeline/testplan_before/plugin.go
/kind bug
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/bug?id=228040&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=506&type=BUG)
| 🇺🇸 English |  get execute env from report env            |
| 🇨🇳 中文    |   执行计划增加真实环境的显示           | …
> get execute env from report env

- modules/pipeline/aop/plugins/pipeline/testplan_after/plugin.go
/kind bug
fix: solve the panic caused by the null pointer
/assign @sfwn 
> fix: solve the panic caused by the null pointer

- modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeTaskTable/render.go
- modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeTaskTable/render_test.go
/kind bug
fix: deal with the case that costTimeSec is negative
if costTimeSec is -1, the time format is "23:59:59"
/assign @sfwn 
> fix: deal with the case that costTimeSec is negative

- modules/openapi/component-protocol/pkg/type_conversion/parse.go
- modules/openapi/component-protocol/pkg/type_conversion/parse_test.go
- modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/formModal/render.go
- modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/table/render.go
- modules/openapi/component-protocol/scenarios/auto-test-scenes/components/apiEditor/render.go
/kind bug
this problem will block users from accessing the schedule list, resulting in unavailability of the function
erda-issue: [erda-issue](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=221807&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDU2MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=467&type=BUG)
> automated test query plan list error strconv.ParseUint: parsing "1.000022e+06": invalid syntax problem solved

- modules/cmp/impl/clusters/import_cluster.go
/kind feature
feature: rename worker cluster tag
| 🇺🇸 English |  rename worker cluster tag            |
| 🇨🇳 中文    |    更改 worker 集群 tag          |
> feature: rename worker cluster tag

- modules/core-services/conf/conf.go
- modules/core-services/endpoints/audit.go
- modules/core-services/services/audit/audit.go
/kind feature
- Audit cleanup interval days configurable from env
- default is 180d
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=66752&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiOTIiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG)
| 🇺🇸 English |  Audit log max retention days adjust to 180 days         |
| 🇨🇳 中文    |    审计日志最大保留天数默认调整为 180 天          |
> audit: cleanup interval days configurable from env, default is 180d

- modules/dop/component-protocol/components/test-dashboard/overview_group/quality_chart/render.go
- modules/dop/component-protocol/components/test-dashboard/overview_group/quality_chart/render_test.go
/kind bug
test-dashboard polish each score before calc total score
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=240804&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyI5MiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=541&type=BUG) …
> fix: test-dashboard polish each score before calc total score

- apistructs/notify_channel.go
- apistructs/notify_channel_test.go
- bundle/notify_channel.go
- modules/eventbox/subscriber/group/group.go
- modules/eventbox/subscriber/sms/sms.go
- modules/pkg/etcdclient/etcdclient.go
- modules/pkg/etcdclient/etcdclient_test.go
/kind feature
feature: eventbox support custom notify channel
/assign @liuhaoyang @innerpeacez 
| 🇺🇸 English |       Support send sms alert via custom notify channel       |
| 🇨🇳 中文    |      支持使用自定义通知渠道发送告警短信        |
> feature: eventbox support custom notify channel

- modules/pipeline/endpoints/pipeline.go
- modules/pipeline/pipengine/reconciler/before_listen.go
- modules/pipeline/pipengine/reconciler/queuemanage/manager/queue.go
- modules/pipeline/pipengine/reconciler/queuemanage/manager/queue_test.go
- modules/pipeline/pipengine/reconciler/queuemanage/types/manager.go
/kind bug
queue manager send pop out pipeline id to etcd, and watch pop out in leader
> send pop out pipeline id to etcd, and watch pop out in leader

- modules/dop/services/pipeline/pipeline.go
- modules/dop/services/pipeline/pipeline_test.go
- modules/pipeline/providers/cms/app.go
- modules/pipeline/providers/cms/app_test.go
/kind bugfix
dop ci generate pipeline cms ns by workspace's main-branch
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=235867&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyI5MiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=-1&type=BUG) …
> fix: dop ci generate pipeline cms ns by workspace's main-branch

- modules/openapi/component-protocol/scenarios/app-pipeline-tree/components/fileTree/render.go
/kind bugfix
The key agreed upon with the front end accidentally added the key suffix
| 🇺🇸 English |      Remove the suffix key of mobile_init_key        |
| 🇨🇳 中文    |        去除 mobile_init_key 的后缀 key      |
> remove mobile init key

- modules/msp/apm/trace/storage/consumer.go
- modules/msp/apm/trace/storage/consumer_test.go
- modules/msp/apm/trace/trace.service.go
- modules/msp/apm/trace/trace.service_test.go
/kind bugfix
fix span missing bug
> fix span missing bug

- modules/orchestrator/services/addon/addon_deploy.go
- modules/orchestrator/services/addon/addon_deploy_test.go
/kind feature
basic mysql: disable master-slave mode, use standalone mode
| 🇺🇸 English | basic mysql: disable master-slave mode, use standalone mode |
| 🇨🇳 中文    | 基础版本的mysql，去除 slave，只发布 standalone master |
> disable mysql basic ha

- modules/pipeline/pipengine/reconciler/taskrun/task_loop.go
- modules/pipeline/pipengine/reconciler/taskrun/taskop/queue.go
- modules/pipeline/pipengine/reconciler/taskrun/taskop/queue_test.go
/kind bugfix
The start execution time is not reset when the pipeline cyclic task is executed. The result of the reset is that the user cannot know the execution time of the cyclic task
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=242852&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNTYwIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=541&type=BUG)
| 🇺🇸 English |       The pipeline does not reset the start execution time of the cyclic task       |
| 🇨🇳 中文    | …
> loop task not reset begintime

- modules/gittar/api/repo.go
- modules/gittar/conf/conf.go
/kind feature
The git search interface adds dynamic configuration search depth
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=243943&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNTYwIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=467&type=TASK)
| 🇺🇸 English |      The git search interface adds dynamic configuration search depth        |
| 🇨🇳 中文    |       git search 接口增加动态配置搜索深度       |
> gittar add tree search depth config

- modules/core-services/services/security/process.go
bugfix
Check guest role of member info with empty resource value
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=239766&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMDczIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=-1&type=BUG)
/assign @sfwn  …
> Check guest role of member info with empty resource value

- modules/extensions/loghub/index/query/clients.go
- modules/extensions/loghub/index/query/index.go
/kind bugfix
bugfix: log index cache got overwritten when multi esurls exists in erda cluster
| 🇺🇸 English |      Fix the bug that log index cache got overwritten when multi esurls exists in erda cluster        |
| 🇨🇳 中文    |      修复同一集群中存在多个日志分析es时预加载日志索引缓存数据被相互覆盖的问题        |
> bugfix: log index cache got overwritten when multi esurls exists in erda cluster

- apistructs/issue.go
- apistructs/issue_test.go
- modules/dop/services/issue/convert.go
- modules/dop/services/issue/convert_test.go
- modules/dop/services/issue/import.go
- pkg/erda-configs/i18n/issue.json
/kind bugfix
issue import support estimate time, export support finish time
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=244026&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=541&type=BUG) …
> issues import support estimate time

- modules/dop/component-protocol/components/code-coverage/treeMapChart/render.go
/kind bugfix
init toolTip,value,path if report is nil
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/bug?id=245903&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1NDFdLCJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=541&type=BUG) …
> init toolTip,value,path if report is nil

- modules/hepa/provider.go
/kind bugfix
when hepa proxy the metric request to monitor, missing the Lang header will lead to i18n not work.
> fix the i18n in apim chart

- modules/pipeline/services/pipelinesvc/create_task.go
/kind bugfix
make snippet task can be disable
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=245987&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=541&type=BUG) …
> make snippet task can be disable

- .erda/migrations/cmdb/20211102-mbox-deduplicateid-length.sql
bugfix
Mbox deduplicate id column does not exceed the index length limit
/assign @sfwn 
> Mbox deduplicate id column does not exceed the index length limit

- modules/pipeline/pipengine/reconciler/define.go
- modules/pipeline/pipengine/reconciler/listen.go
- modules/pipeline/pipengine/reconciler/listen_test.go
/kind bugfix
After the timing task is turned on and the compensation is not executed, the pipeline is repeatedly executed, which will cause the pipeline to directly change to the successful state, and the task state in the pipeline is noNeedBySystem
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=245842&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNTYwIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=467&type=TASK)
| 🇺🇸 English |       The pipeline adds a map to …
> bugfix pipeline repeated execution

- .erda/migrations/qa/20211109-manual-test-fix-slow-sql.sql
- apistructs/testplan.go
- go.mod
- go.sum
- modules/dop/dao/testcase.go
- modules/dop/dao/testcase_test.go
- modules/dop/dao/testplan_testcase_relation.go
- modules/dop/dao/testplan_testcase_relation_test.go
- modules/dop/dao/testset.go
- modules/dop/dao/testset_test.go
- modules/dop/endpoints/testplan.go
- modules/dop/services/testcase/paging.go
- modules/dop/services/testplan/testplan.go
- modules/dop/services/testplan/testplan_test.go
- modules/dop/services/testset/create.go
/kind refactor
fix slow sql:
- refactor: manual test case&plan-case-relations paging use sql join
[Tested in dev](https://erda.dev.terminus.io/sfwn-org/dop/projects/62/manual/testCase?eventKey=0-19294&orderBy=updatedAt&orderRule=DESC&pageNo=1&pageSize=15&recycled=false&testSetID=19294) and feels good :P 
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=243655&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyI5MiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=541&type=TASK) …
> refactor: manual test case&plan-case-relations paging use sql join

- modules/pipeline/pipengine/reconciler/reconcile.go
- modules/pipeline/pipengine/reconciler/taskrun/taskop/prepare.go
- modules/pipeline/pipengine/reconciler/taskrun/taskop/prepare_test.go
/kind feature
Bootstrap token is no longer set for automated testing. In automated testing, a large number of interfaces to apply for tokens cause excessive pressure on the openapi interface, and the applied tokens are useless
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=247030&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTYsNDQwOF0sImFzc2lnbmVlSURzIjpbIjEwMDA1NjAiXSwiZmluaXNoZWRBdFN0YXJ0RW5kIjpbMTYzNjEyODAwMDAwMCxudWxsXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=467&type=BUG)
| 🇺🇸 …
> autotest not set bootstrap token

- modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeTaskTable/render.go
- modules/openapi/component-protocol/scenarios/auto-test-scenes/components/executeTaskTable/render.go
/kind bugfix
autotest openapi component step concurrency interface display
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=237839&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG) …
> autotest step concurrency interface display

- modules/extensions/loghub/index/query/clients.go
- pkg/http/httpclient/client.go
- pkg/http/httpclient/request.go
- pkg/http/httpclient/trace.go
/kind bugfix
/kind polish
shared http transport
/assign @johnlanni
> shared http transport

- apistructs/permission.go
- modules/core-services/endpoints/permission.go
- modules/core-services/endpoints/permission_test.go
/kind feature
Added permission verification to return project name and application name
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=248325&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTYsNDQwOF0sImFzc2lnbmVlSURzIjpbIjEwMDA1NjAiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=-1&type=TASK)
| 🇺🇸 English |      Added permission verification to return project name and application name        |
| 🇨🇳 中文    |        权限校验增加返回项目名称和应用名称      |
> check permission add project and app name

- modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/table/render.go
- modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/table/table_test.go
/kind bugfix
The execution rate of the automated test plan does not retain 2 decimal places but uses %.f for the value, which will cause 99.89 to become 100, which leads to inconsistencies.
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=249480&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNTYwIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)
| 🇺🇸 English |       automated test plan execution pass rate retains 2 decimal places       |
| 🇨🇳 中文    | …
> automated test plan pass rate display retains 2 decimal places

- apistructs/cluster_info.go
- modules/dop/services/pipeline/pipeline.go
- modules/dop/services/pipeline/pipeline_test.go
/kind bugfix
use job cluster as cluster name if not empty
[source pr](https://github.com/erda-project/erda/pull/3042)
> use job cluster as cluster name if not empty

- apistructs/pipeline_yml.go
- modules/pipeline/pipengine/reconciler/policy.go
- modules/pipeline/pipengine/reconciler/policy_test.go
- modules/pipeline/pipengine/reconciler/reconcile.go
- modules/pipeline/pipengine/reconciler/reconcile_data_process.go
- modules/pipeline/spec/pipeline_task.go
- pkg/parser/pipelineyml/define.go
- pkg/parser/pipelineyml/graph_pipelineyml.go
/kind feature
The pipeline task execution strategy is added. The new strategy can make the task no longer execute but directly fetch the latest successful result. This function can be used in automated testing, and users can save time to execute the same set of scenarios
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=228823&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTYsNDQwOF0sImFzc2lnbmVlSURzIjpbIjEwMDA1NjAiXSwiZmluaXNoZWRBdFN0YXJ0RW5kIjpbMTYzNjEyODAwMDAwMCxudWxsXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=TASK)
| Language | …
> task policy

- modules/dop/dao/testcase.go
- modules/dop/dao/testplan_testcase_relation.go
/kind bugfix
fix: manual-test case paging `LIKE` clause use correct testSet directory
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=248026&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyI5MiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)
/cherry-pick release/1.5-alpha1 release/1.4
> fix: manual-test case paging `LIKE` clause use correct testSet directory

- modules/dop/services/workbench/workbench.go
- modules/dop/services/workbench/workbench_test.go
bugfix
Fix home page content table group for users without any projects
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=248918&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMDczIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)
/assign @sfwn  …
> Fix home page content table group for users without any projects

- conf/monitor/monitor/logs/default_field_settings.yml
/kind bugfix
log-analysis, offset and timestampNanos fields should not display by default.
> bugfix: add missing log fields settings

- .erda/migrations/pipeline/20211112-pipeline-task-metadata-inspect.sql
- apistructs/pipeline_task.go
- apistructs/pipeline_task_test.go
- modules/pipeline/aop/plugins/pipeline/basic/plugin.go
- modules/pipeline/aop/plugins/task/autotest_cookie_keep_after/plugin.go
- modules/pipeline/aop/plugins/task/unit_test_report/plugin.go
- modules/pipeline/dbclient/op_pipeline.go
- modules/pipeline/dbclient/op_pipeline_task.go
- modules/pipeline/events/event_task.go
- modules/pipeline/pexpr/pexpr_params/task_params.go
- modules/pipeline/pipengine/actionexecutor/plugins/apitest/apitest.go
- modules/pipeline/pipengine/reconciler/reconcile_data_process.go
- modules/pipeline/pipengine/reconciler/snippet.go
- modules/pipeline/pipengine/reconciler/snippet_test.go
- modules/pipeline/pipengine/reconciler/taskrun/framework.go
- modules/pipeline/pipengine/reconciler/taskrun/task_loop.go
- modules/pipeline/pipengine/reconciler/taskrun/taskop/prepare.go
- modules/pipeline/pipengine/reconciler/taskrun/taskop/prepare_test.go
- modules/pipeline/pipengine/reconciler/taskrun/update.go
- modules/pipeline/services/pipelinesvc/callback.go
- modules/pipeline/services/pipelinesvc/callback_test.go
- modules/pipeline/services/pipelinesvc/detail.go
- modules/pipeline/spec/pipeline_task.go
- modules/pipeline/spec/pipeline_task_test.go
/kind bugfix
split the result filed to metadata and inspect, update metadata only when task callback
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=209158&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)
> For details on the cherry pick process, …
> split the result filed to metadata and inspect

- modules/pipeline/services/pipelinesvc/snippet.go
/kind bugfix
fix the bug of concurrent create snippet pipelines
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=252139&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=249137&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsN …
> fix the bug of concurrent create snippet pipelines

- modules/eventbox/dispatcher/dispatcher.go
- modules/eventbox/subscriber/email/email.go
- modules/openapi/api/apis/eventbox/eventbox_smtp_info.go
/kind feature
Increase the query interface of smtp information and provide it for remote query of email action
| 🇺🇸 English |       Increase the query interface of smtp information      |
| 🇨🇳 中文    |       增加 smtp 的信息的查询接口       |
/cherry-pick release/1.5
> add smtp info api

- modules/openapi/component-protocol/scenarios/action/components/actionForm/render.go
- modules/openapi/component-protocol/scenarios/action/components/actionForm/render_test.go
- pkg/erda-configs/i18n/action.json
/kind bugfix
The action graphical interface adds a timeout input field
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=228378&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNTYwIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)
| 🇺🇸 English |       The action graphical interface adds a timeout input field      |
| 🇨🇳 中文    |      action 图形化界面增加 timeout 输入字段        |
> action add timeout input

- modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/formModal/render.go
- modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/table/render.go
- modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/table/render_test.go
- modules/openapi/component-protocol/scenarios/auto-test-plan-list/protocol.yml
/kind bugfix
When the user edits the name of the plan, the paging data of the table will be reloaded. This behavior does not conform to the user's operating habits
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=223455&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNTYwIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)
| 🇺🇸 English |      After the automated test pagination is edited, the pagination will no longer change        |
| 🇨🇳 中文    | …
> edit autotest plan reload table but not reset pageNum

- apistructs/autotest_space.go
- modules/openapi/component-protocol/scenarios/auto-test-space-list/components/spaceList/operation.go
- modules/openapi/component-protocol/scenarios/auto-test-space-list/components/spaceList/render.go
bugfix
Auto test space archive status color by status
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=250883&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMDczIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)
/assign @sfwn  …
> Auto test space archive status color by status

- modules/dop/services/issue/convert.go
- modules/dop/services/issue/convert_test.go
/kind bugfix
issue-import judge data length about estimate time and close time
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=249116&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)
| 🇺🇸 English | Fix the bug that import issue status code 502 in dopplatform …
> issue-import judge data length about estimate time and close time

- pkg/apitestsv2/apitest.go
- pkg/apitestsv2/apitest_test.go
/kind bugfix
request and response information are also returned when the automated test fails to execute
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=252901&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNTYwIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)
| 🇺🇸 English |      Request and response information are also returned when the automated test fails to execute        |
| 🇨🇳 中文    |       自动化测试执行失败的时候也返回 request 和 response 信息 …
> request and response information are also returned when the automated test fails to execute

- modules/dop/component-protocol/components/auto-test-scenes/leftPage/fileFormModal/render.go
/kind bugfix
fix: solve the EOF problem of scene copy to empty scene set
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=256552&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)
/assign @sfwn 
> For …
> fix: solve the EOF problem of scene copy to empty scene set

- modules/dop/component-protocol/components/auto-test-scenes/leftPage/fileTree/render.go
- modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesSetConfig/scenesStages/operation.go
- modules/dop/services/autotest_v2/sceneset.go
- modules/dop/services/autotest_v2/testplan_v2.go
bugfix
Fix parallel scenes execution in auto test plan
> Fix parallel scenes execution in auto test plan

- modules/cmp/component-protocol/components/cmp-dashboard-podDetail/podInfo/model.go
- modules/cmp/component-protocol/components/cmp-dashboard-podDetail/podInfo/render.go
/kind bugfix
add nodeIP query params in pod detail info
> fix: graph has no data in node detail from pod detail

- conf/cmp/i18n/cp/scenarios/cmp-dashboard-nodes.yaml
- modules/cmp/component-protocol/components/cmp-cluster-list/list/render.go
- modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/table/table.go
- modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/table/table_test.go
- modules/cmp/metrics/metrics.go
> refactor: 💡 add log, fix some bugs

- cmd/monitor/monitor/main.go
- conf/monitor/monitor/i18n/alert.yml
- conf/monitor/monitor/monitor.yaml
- modules/core-services/services/notify/channel/notify.chanel.service.go
- modules/core/monitor/alert/alert-apis/adapt/expression.go
- modules/core/monitor/alert/alert-apis/alert.service.go
- modules/core/monitor/alert/alert-apis/interfaces.go
- modules/core/monitor/alert/alert-apis/provider.go
/kind bugfix
| 🇺🇸 English |      customize alert add dingtalk_work_notice and delete vms        |
| 🇨🇳 中文    |      自定义告警通知方式增加钉钉工作通知并删除电话        |
> customize alert add dingtalk_work_notice and delete vms

- apistructs/org.go
- bundle/org.go
- modules/core-services/endpoints/organization.go
- modules/core-services/endpoints/organization_test.go
- modules/dop/endpoints/organization.go
- modules/openapi/component-protocol/scenarios/home-page-sidebar/components/orgSwitch/render.go
/kind bug
When the admin account enters the workbench, all organizations will be queried, and subsequent admin access to these organizations will not pass the verification authority.
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=252574&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNTYwIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)
| 🇺🇸 English |       The admin account no longer queries all organizations       |
| 🇨🇳 中文    | …
> admin access to the workbench no longer query all organization information

- modules/dop/component-protocol/components/test-report/filter/render.go
- modules/dop/dao/issue.go
- modules/dop/endpoints/iteration.go
- modules/dop/endpoints/iteration_test.go
- modules/dop/services/iteration/iteration.go
/kind bugfix
optimization of  query issue summary state
reduce the query of the sql statement
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=257960&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)
| 🇺🇸 English |   Fix the bug that cost long time when query …
> optimization of issue summary state

- modules/core-services/services/notify/channel/kind/dingtalk_work_notice.go
- modules/core-services/services/notify/channel/kind/dingtalk_work_notice_test.go
/kind refactor
| 🇺🇸 English |       move dingtalk struct from aliyun_sms.go to dingtalk_work_notice.go       |
| 🇨🇳 中文    |     移动钉钉工作通知中的结构体和方法         |
> move dingtalk struct from aliyun_sms.go to dingtalk_work_notice.go

- modules/hepa/services/api_policy/impl/impl.go
- pkg/k8s/interface_factory/ingress.go
/kind feature
if k8s version <1.19  then use the version of extensions/v1beta1;
if k8s version >=1.19 then  use the version of networking.k8s.io/v1;
networking.k8s.io/v1beta1 is useless.
> remove useless version of ingress: networking.k8s.io/v1beta1

- apistructs/pipeline_queue.go
- modules/openapi/api/apis/pipeline/pipeline_queue_create.go
- modules/openapi/api/apis/pipeline/pipeline_queue_delete.go
- modules/openapi/api/apis/pipeline/pipeline_queue_get.go
- modules/openapi/api/apis/pipeline/pipeline_queue_list.go
- modules/openapi/api/apis/pipeline/pipeline_queue_priority_upgrade.go
- modules/openapi/api/apis/pipeline/pipeline_queue_update.go
/kind feature
register pipeline queues endpoints to openapi
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=257961&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=TASK)
| 🇺🇸 English | Support pipeline queues endpoints in openapi              |
| 🇨🇳 中文    | …
> register pipeline queues endpoints to openapi

- modules/dop/component-protocol/components/test-dashboard/at_case_rate_trending_chart_group/chart/render.go
- modules/dop/component-protocol/components/test-dashboard/at_case_rate_trending_chart_group/filter/model.go
- modules/dop/component-protocol/components/test-dashboard/at_case_rate_trending_chart_group/filter/render.go
- modules/dop/component-protocol/components/test-dashboard/at_plan_latest_waterfall_chart_group/chart/render.go
- modules/dop/component-protocol/components/test-dashboard/at_plan_latest_waterfall_chart_group/filter/render.go
- modules/dop/component-protocol/components/test-dashboard/common/gshelper/helper.go
- modules/dop/component-protocol/scenarios/test-dashboard.yml
feature: update relation between trending and waterfall
/kind feature
feature: update relation between trending and waterfall
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=258275&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)
/assign @sfwn 
| 🇨🇳 中文    | …
> feature: update relation between trending and waterfall chart of test dashboard

- .erda/migrations/qa/20211201-auto-test-exec-history-index.sql
- apistructs/autotest_exec_history.go
- apistructs/autotest_space.go
- modules/dop/component-protocol/components/test-dashboard/at_api_chart_group/at_api_avg_cost_chart/render.go
- modules/dop/component-protocol/components/test-dashboard/at_api_chart_group/at_api_rate_failed_chart/render.go
- modules/dop/component-protocol/components/test-dashboard/common/gshelper/helper.go
- modules/dop/component-protocol/components/test-dashboard/filter/render.go
- modules/dop/component-protocol/components/test-dashboard/overview_group/blocks/at/at_num_api/render.go
- modules/dop/component-protocol/components/test-dashboard/overview_group/blocks/at/at_num_scene/render.go
- modules/dop/component-protocol/components/test-dashboard/scene_chart_group/scene_avg_cost_chart/render.go
- modules/dop/component-protocol/components/test-dashboard/scene_chart_group/scene_rate_failed_chart/render.go
- modules/dop/component-protocol/components/test-dashboard/scene_chart_group/scene_rate_passed_chart/render.go
- modules/dop/dao/autotest_exec_history.go
- modules/dop/dao/autotest_scene.go
- modules/dop/dao/autotest_scene_step.go
- modules/dop/dao/testplan_v2_step.go
- modules/dop/services/autotest_v2/scene.go
/kind polish
fix: optimize sql of test dashboard to solve the problem of slow sql
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=257257&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)
/assign @sfwn 
Add comment like `/cherry-pick release/1.0` when this PR is …
> fix: optimize sql of test dashboard to solve the problem of slow sql

- .erda/migrations/cmdb/20211129-issue-relation-type.sql
- apistructs/component_protocol.go
- apistructs/issue.go
- apistructs/issue_related.go
- apistructs/issue_state.go
- conf/dop/dop.yaml
- conf/openapi/openapi.yaml
- modules/dop/component-protocol/components/all.go
- modules/dop/component-protocol/components/issue-gantt/filter/model.go
- modules/dop/component-protocol/components/issue-gantt/filter/render.go
- modules/dop/component-protocol/components/issue-gantt/gantt/model.go
- modules/dop/component-protocol/components/issue-gantt/gantt/render.go
- modules/dop/component-protocol/components/issue-gantt/ganttContainer/render.go
- modules/dop/component-protocol/components/issue-gantt/issueAddButton/render.go
- modules/dop/component-protocol/components/issue-gantt/page/render.go
- modules/dop/component-protocol/components/issue-gantt/scenario.go
- modules/dop/component-protocol/components/issue-gantt/topHead/render.go
- modules/dop/component-protocol/scenarios/issue-gantt.yml
- modules/dop/dao/issue.go
- modules/dop/dao/issue_issue_relation.go
- modules/dop/endpoints/issue_related.go
- modules/dop/services/issue/convert.go
- modules/dop/services/issue/convert_test.go
- modules/dop/services/issue/import.go
- modules/dop/services/issue/issue.go
- modules/dop/services/issuerelated/issue_related.go
Issue gantt chart set up, issue inclusion relation
| 🇺🇸 English | Issue gantt chart             |
| 🇨🇳 中文    |   项目协同 甘特图           |
> Issue gantt chart set up, issue inclusion relation

- modules/openapi/component-protocol/scenarios/action/components/actionForm/render.go
- modules/openapi/component-protocol/scenarios/action/components/actionForm/render_test.go
/kind bugfix
Pipeline task timeout configuration
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=260508&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNTYwIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)
| 🇺🇸 English |       Pipeline task timeout configuration       |
| 🇨🇳 中文    |        流水线任务超时时间配置      |
> task timeout setting

- modules/dop/component-protocol/components/issue-gantt/gantt/render.go
- modules/dop/dao/issue.go
- modules/dop/services/issue/issue.go
feature
Issue gantt filter root instead of children node
> Issue gantt filter root instead of children node

- modules/dop/endpoints/iteration.go
/kind bugfix
keep iterations order after set issue summaries
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=261505&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)
| 🇺🇸 English | keep iterations order after set issue summaries              |
| 🇨🇳 中文    | …
> keep iterations order after set issue summaries

- modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sspark/k8sspark.go
- modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sspark/util.go
- modules/pipeline/pkg/containers/task_container.go
- modules/pipeline/pkg/containers/task_container_test.go
/kind feature
support spark job logs
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=240364&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=772&type=REQUIREMENT)
| 🇺🇸 English | Support spark job logs             |
| 🇨🇳 中文    |   实现spark 任务日志查看           |
Add comment like …
> add terminus_define_tag lable for spark job

- modules/pipeline/dbclient/op_pipeline_task.go
- modules/pipeline/pipengine/reconciler/taskrun/task_loop.go
- modules/pipeline/pipengine/reconciler/taskrun/task_loop_test.go
- modules/pipeline/pipengine/reconciler/taskrun/update.go
/kind bugfix
pipeline loop task clean result
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=258315&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)
| 🇺🇸 English |   Fix the bug that clean pipeline loop task            |
| 🇨🇳 中文    |  修复了loop task 没有清空result …
> pipeline loop task clean result

- modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileExecute/executeTaskTable/render.go
/kind bugfix
The details of the execution configuration sheet of the scene set cannot be displayed, resulting in the user not being able to see the log
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=262679&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNTYwIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)
| 🇺🇸 English |       Scene set detailed configuration sheet display       |
| 🇨🇳 中文    |        场景集明细配置单展示      |
> scene set execution configuration sheet detailed display

- modules/core-services/endpoints/application.go
- modules/core-services/endpoints/application_test.go
- modules/core-services/model/project.go
/kind bugfix
optimization of query applications
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=258142&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)
| 🇺🇸 English | optimization of query applications             |
| 🇨🇳 中文    |       优化了应用列表查询慢       |
Add …
> optimization of query applications

- conf/dop/dop.yaml
- modules/dop/component-protocol/components/all.go
- modules/dop/component-protocol/components/requirement-task-overview/chartBlock/burnoutChart/model.go
- modules/dop/component-protocol/components/requirement-task-overview/chartBlock/burnoutChart/render.go
- modules/dop/component-protocol/components/requirement-task-overview/chartBlock/burnoutChartFilter/model.go
- modules/dop/component-protocol/components/requirement-task-overview/chartBlock/burnoutChartFilter/render.go
- modules/dop/component-protocol/components/requirement-task-overview/chartBlock/render.go
- modules/dop/component-protocol/components/requirement-task-overview/common/condition.go
- modules/dop/component-protocol/components/requirement-task-overview/common/gshelper/helper.go
- modules/dop/component-protocol/components/requirement-task-overview/common/util.go
- modules/dop/component-protocol/components/requirement-task-overview/common/vars.go
- modules/dop/component-protocol/components/requirement-task-overview/container/info/model.go
- modules/dop/component-protocol/components/requirement-task-overview/container/info/render.go
- modules/dop/component-protocol/components/requirement-task-overview/container/render.go
- modules/dop/component-protocol/components/requirement-task-overview/container/simpleChart/model.go
- modules/dop/component-protocol/components/requirement-task-overview/container/simpleChart/render.go
- modules/dop/component-protocol/components/requirement-task-overview/distributePage/render.go
- modules/dop/component-protocol/components/requirement-task-overview/distributePage/topFilter/model.go
- modules/dop/component-protocol/components/requirement-task-overview/distributePage/topFilter/render.go
- modules/dop/component-protocol/components/requirement-task-overview/page/render.go
- modules/dop/component-protocol/components/requirement-task-overview/pageContent/render.go
- modules/dop/component-protocol/components/requirement-task-overview/scenario.go
- modules/dop/component-protocol/components/requirement-task-overview/tabs/render.go
- modules/dop/component-protocol/scenarios/requirement-task-overview.yml
- modules/dop/services/issue/issue.go
/kind feature
feature: add requirement-task-overview scenario
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=263125&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjYxIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=680&type=TASK) …
> feature: add requirement-task-overview scenario

- modules/dop/component-protocol/components/issue-manage/issueKanban/issue_kanban.go
- modules/dop/component-protocol/components/issue-manage/issueKanban/render.go
- modules/dop/dao/issue.go
- modules/dop/endpoints/issue.go
- modules/dop/services/issuepanel/issue_panel.go
/kind feature
- feature: issue-kanban order by updatedAt desc
- fix: issue paging expectIDs use `WHERE NOT IN` clause
- feature: issue-kanban custom panel update issue's updatedAt
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=263111&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyI5MiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=TASK)
/assign @Effet
> feature: issue-kanban order by updatedAt desc

- modules/dop/component-protocol/components/issue-gantt/gantt/model.go
- modules/dop/component-protocol/components/issue-gantt/gantt/render.go
- modules/dop/component-protocol/components/issue-manage/issueTable/render.go
- modules/dop/dao/issue.go
- modules/dop/services/issue/issue.go
feature
Issue gantt chart children filtered by assignee, issue table style
> Issue gantt chart children filtered by assignee, issue table style

- modules/scheduler/conf/conf.go
- modules/scheduler/executor/executor.go
- modules/scheduler/executor/plugins/k8s/k8s.go
- modules/scheduler/executor/plugins/k8s/k8s_test.go
- modules/scheduler/executor/util/util.go
/kind feature
/kind bugfix
1.  optimize timeout，default 10s.
2. optimize start order with client-go and http-client.
3. change the executor startup mode to asynchronous.
Testing result:
clusters: 5 error cluster and 2 normal cluster.
timeout: 5s
before: 6min18s
```shell
time="2021-12-02 14:58:48.076" level=info msg="provider scheduler is initializing"
......
time="2021-12-02 15:05:06.905958304" level=info msg="added endpoint: GET /api/capacity"
```
after:
- service start：0.26s
- executor create complete：5s
```shell
time="2021-12-03 14:13:14.418" level=info msg="provider scheduler is initializing"
time="2021-12-03 14:13:14.597375116" level=info msg="created executor: EDASFORSHELECTRICTEST"
...
time="2021-12-03 14:13:14.679703234" level=info msg="added …
```
> feature: optimize scheduler startup time

- modules/core-services/services/project/project.go
/kind bugfix
Fix the problem that the audit information is incorrect when the quota is 0 before the upgrade and the quota is modified after the upgrade
> fix: quota audit

- tools/cli/cmd/build.go
- tools/cli/cmd/fetch_pipe.go
- tools/cli/cmd/view.go
- tools/cli/common/workspace.go
/kind feature
Without changing the original command line function, modify the `erda-cli build` command and add the `erda-cli view` command to create a pipeline and build applications without leaving the IDE or command line. Very useful for M1 users. …
> add erda-cli view cmd 

- modules/dop/dao/issue.go
- modules/dop/services/issue/issue.go
- modules/dop/services/workbench/workbench.go
- modules/dop/services/workbench/workbench_test.go
bugfix
Fix work bench issue data query
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=262614&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMDczIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)
/assign @sfwn  …
> Fix work bench issue data query

- conf/core-services/i18n/i18n.yaml
- go.mod
- go.sum
- modules/core-services/endpoints/project.go
- modules/core-services/services/project/project.go
- pkg/goroutine_context/context.go
- pkg/http/httpclient/request.go
- pkg/http/httpserver/server.go
- pkg/i18n/helper.go
- pkg/i18n/helper_test.go
/kind bugfix
When users call most of the apis, because the lang in the request header is not passed through the bdl call, the information returned by the subsequent apis is not internationalized, resulting in a mixture of various languages
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=257975&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNTYwIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)
| 🇺🇸 English |       Internationalized …
> bdl requests to pass internationalized information

- modules/msp/menu/menu.service.go
/kind bugfix
bugfix: add terminusKey for LogAnalyze menu item, to fix the bug that create log-analysis-rule with wrong scopeId
/cherry-pick release/1.5-alpha.4
> bugfix: add terminusKey for LogAnalyze menu item

- modules/scheduler/executor/plugins/edas/edas.go
/kind bugfix
edas list recent change order info error
will cause scheduler panic
| 🇺🇸 English | fix edas list recent change order info error             |
| 🇨🇳 中文    |    修复 edas 接口错误          |
> fix: edas list recent change order info error

- apistructs/pipeline_task.go
- apistructs/pipeline_task_test.go
- modules/pipeline/pipengine/reconciler/task.go
- modules/pipeline/pipengine/reconciler/taskrun/framework.go
/kind bugfix
limit task retry when system error
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=240758&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=772&type=BUG) …
> limit task retry when system error

- conf/msp/msp.yaml
- modules/msp/apm/service/view/chart/http_code.go
> bugfix: http code

- modules/orchestrator/services/deployment/deployment_context.go
- modules/orchestrator/services/deployment/deployment_context_test.go
/kind bugfix
jump over nil addon field
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=263634&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=-1&type=BUG)
| 🇺🇸 English |  Fix the bug that jump over empty addon            |
| 🇨🇳 中文    |   修复了orchestrator遇到空的addon配置panic的问题 …
> jump over empty addon

- go.sum
- modules/core-services/services/project/cache.go
- modules/core-services/services/project/project.go
/kind bugfix
Fixed the problem of inaccurate project resource request value
| 🇺🇸 English |  |
> fix: allows podInfo.Cluster to be empty

- modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileExecute/executeTaskTable/render.go
- modules/dop/component-protocol/components/issue-gantt/gantt/render.go
- modules/dop/dao/issue.go
- modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeTaskTable/render.go
/kind feature
Automated testing removes paging events, returns all information, so as to achieve front-end paging
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=263116&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNTYwIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)
| 🇺🇸 English |     Automated testing removes paging events, returns all information, so as to achieve front-end paging         |
| 🇨🇳 中文    | …
> autotest task table remove page operator

- modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sflink/flink.go
- modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sspark/k8sspark.go
/kind feature
gc namespace for k8sspark k8sflink
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=265418&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=TASK)
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=265633&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUE …
> gc namespace for k8sspark k8sflink

- modules/openapi/component-protocol/components/base/provider.go
/kind bugfix
cp base provider creator return new instance. Otherwise, each time provider instance is the same one.
/assign @Effet @shuofan
> bugfix: cp base provider creator return new instance

- conf/monitor/streaming/streaming.yaml
/kind bugfix
- fix log missing when new erda deployed 
[(SO)](https://stackoverflow.com/questions/32390265/what-determines-kafka-consumer-offset)
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODEsNjgwLDc3Ml0sIm1lbWJlciI6WyIxMDAwMzAxIl0sImxhYmVsIjpbMTQ1NV19&id=210672&iterationID=881&pId=0&type=TASK)
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a …
> streaming log consumer default to earliest

- quick-start/quick-start.sh
/kind feature
the whole quick-start script file move to the `erda-release` repo, so here we can make the script to execute the local docker-compose.yml file, not download from the release oss
> feature: optimize quick-start script to use local docker-compose file

- apistructs/service.go
- pkg/k8s/storage/detect_sc.go
- pkg/k8s/storage/detect_sc_test.go
/kind feature
/ for pipeline ECI Pod enabled, need detect storageclass  base diskType and cloud provider
/assign @iutx 
add pkg/k8s/storage
add constant and struct info in apistructs
> add pkg storage: for detect storageclass name

- pkg/i18n/helper.go
/kind bugfix
The MAC system does not support obtaining the current collaboration process, which will lead to panic
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls3NzJdLCJtZW1iZXIiOlsiMTAwMDU2MCJdfQ%3D%3D&id=266876&iterationID=772&pId=0&type=BUG)
| 🇺🇸 English |      The i18n global setting header no longer supports the mac system, because the underlying library for getting the coroutine does not support        |
| 🇨🇳 中文    |       i18n 全局设置 header 忽略 Mac 系统，因为底层获取协程的库不支持       |
> If it is a MAC system, skip the global configuration internationalizttion information

- modules/pipeline/pipengine/actionexecutor/plugins/apitest/apitest.go
- modules/pipeline/pipengine/actionexecutor/plugins/wait/wait.go
- modules/pipeline/pipengine/reconciler/taskrun/taskop/wait.go
- modules/pipeline/pipengine/reconciler/taskrun/taskrun.go
- modules/pipeline/spec/pipeline_task.go
- modules/pipeline/spec/pipeline_task_test.go
/kind bugfix
check data version when accept from executor done chan
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=264469&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)
| 🇺🇸 English |  Fix the bug that get outputs error from pre-task            |
| 🇨🇳 中文 …
> check data version when accept from executor done chan

- pkg/parser/pipelineyml/visitor_ref_op.go
/kind feature
```yaml
name: ${{ outputs.xxx.name }}
```
```yaml
name:  #1
```
```yaml
name: ${{ outputs.xxx.name.wrap_double_quotes }}
```
```yaml
name:  "#1"
```
Because yml file performs template replacement, some replacement strings have # prefix, which will cause problems in the entire yml file
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODEsNzcyXSwibWVtYmVyIjpbIjEwMDA1NjAiXX0%3D&id=265771&iterationID=772&pId=0&type=BUG)
| 🇺🇸 English |      Syntax ${{ outputs.xxx.xxx.wrap_double_quotes }}, add double quotes to the replaced value of the outputs placeholder     |
| 🇨🇳 中文    |      语法 ${{ outputs.xxx.xxx.wrap_double_quotes }}，给 outputs …
> Syntax ${{ outputs.xxx.xxx.wrap_double_quotes }}, add double quotes to the replaced value of the outputs placeholder

- build/dockerfiles/Dockerfile
- conf/dicehub/dicehub.yaml
- modules/dicehub/extension/action.go
- modules/dicehub/extension/provider.go
- modules/dicehub/extension/source.go
- modules/dicehub/extension/source_test.go
/kind feature
The update architecture of the extension source is upgraded, and the local source and github source are automatically updated without manual operation, and directly monitor file changes
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=264393&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNTYwIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=TASK)
| 🇺🇸 English |       Automatic update of dicehub extension source monitoring file …
> auto sync extension by source

- modules/pipeline/services/pipelinesvc/cron_compensate.go
- modules/pipeline/spec/pipeline_cron.go
- modules/pipeline/spec/pipeline_cron_test.go
/kind bugfix
cron compensate generate new map when create pipeline to avoid concurrent map problem
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls3NzIsNjgwLDg4MV0sIm1lbWJlciI6WyIxMDAxMjA1Il19&id=267763&iterationID=772&pId=0&type=BUG)
| 🇺🇸 English |  cron compensate generate new map when create pipeline to avoid concurrent map problem            |
| 🇨🇳 中文    |  修复了pipeline定时补偿时并发读写map panic的问题            | …
> cron compensate generate new map when create pipeline

- build/dockerfiles/Dockerfile
/kind bugfix
Change the dockerfile and extension folder to determine whether they exist
| 🇺🇸 English |      Change the dockerfile and extension folder to determine whether they exist        |
| 🇨🇳 中文    |       变更 dockerfile，判定 extension 文件不存在       |
/cherry-pick release/1.5
> dockerfile change extension mv command

- pkg/erda-configs/permission/backend/sys/org/org.yml
bugfix
Add data manager permission role in member list
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=229778&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMDczIl19&issueTable__urlQuery=eyJwYWdlTm8iOjIsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG)
/assign @sfwn  …
> Add data manager permission role in member list

- modules/volume-provisioner/netdatavolume/provision.go
/kind bugfix
netdata volume use os.MkdirAll(volPath, 0666) to create directory, if system use umask 022, then created directory volPath with mode 0644, which disabled non-root user write file to directory volPath.
/assign @iutx @luobily 
> Bug fix: netdatavolume can not 

- Makefile
/kind script
Add `make build-image-all` command to compile all services into the same docker image
> Add makefile command: compile all services into the same docker image

- apistructs/pipeline_yml.go
- modules/dop/component-protocol/components/auto-test-scenes/leftPage/fileFormModal/render.go
- modules/pipeline/aop/plugins/pipeline/apitest_report/plugin.go
- modules/pipeline/pipengine/reconciler/policy.go
/kind feature
A new execution strategy is added to the automated test scenario reference scenario set to reference the results of the last successful execution
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls3NzJdLCJtZW1iZXIiOlsiMTAwMDU2MCJdfQ%3D%3D&id=258470&iterationID=772&pId=0&type=REQUIREMENT)
| 🇺🇸 English |      Pipeline tasks add strategies that reference the results of recent successful execution        |
| 🇨🇳 中文    |        流水线任务增加引用`最近执行成功的结果`的策略      |
> Add a new reference execution strategy to the automated test reference scenario set

- .github/PULL_REQUEST_TEMPLATE.md
remove the needless of pr type, because we mandant committer write good pr title for type.
/assign @sfwn 
| 🇨🇳 中文    |    修改 PR template，去除了不需要的 type        |
> chore: remove the needless of pr type in pr template

- .github/prlint.json
check chinese & english changelog before pr merged
/assign @sfwn 
| 🇺🇸 English |     check chinese & english changelog before pr merged as required         |
| 🇨🇳 中文    |   增加 prlint.json 强制要求 pr 必须提供 changelog           |
> chore: check chinese & english changelog before pr merged

- modules/actionagent/agenttool/mv.go
- modules/actionagent/agenttool/mv_test.go
- modules/actionagent/step_restore.go
- modules/actionagent/step_sore_test.go
- modules/actionagent/step_store.go
/kind bugfix
store and restore cache by temp file
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=270099&issueFilter__urlQuery=eyJ0aXRsZSI6Iua1geawtOe6v2NhY2hl5paH5Lu25q276ZSBIiwic3RhdGVzIjpbNDQwMiw3MTA0LDcxMDUsNDQwMyw0NDA0LDcxMDYsNDQwNiw0NDA3LDQ0MTIsNDUzOCw0NDEzLDQ0MTQsNDQxNSw0NDE2XX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG)
| 🇺🇸 English | Fix the bug pipeline cache lock             |
| 🇨🇳 中文    |    pipeline缓存死锁          | …
> fix: store and restore cache by temp file

- pkg/goroutine_context/context.go
- pkg/i18n/helper.go
Goroutine binds some global context and needs to ignore the arm64 system. The arm64 system uses some open source packages to bind the PA
| 🇺🇸 English |       The arm64 system ignores the bound global context       |
| 🇨🇳 中文    |       arm64 系统忽略绑定全局的 context       |
> fix: Arm64 ignore getting goid

- modules/orchestrator/services/runtime/runtime.go
fix deployment outdate when runtime is deleted
| 🇺🇸 English |         fix deployment outdate when runtime is deleted     |
| 🇨🇳 中文    |         删除runtime同时将runtime关联的deployment过期掉    |
> fix: deployment outdate when runtime is deleted

- modules/core/monitor/alert/alert-apis/adapt/alert.go
- modules/core/monitor/alert/alert-apis/adapt/alert_test.go
fix the bug ofcreate customize alert return id is 0
| 🇺🇸 English |      fix the bug ofcreate customize alert return id is 0        |
| 🇨🇳 中文    |       使用自定义告警规则创建告警策略id返回0       |
Add comment like `/cherry-pick release/1.6` when this PR is merged.
> fix: create customize alert return id is 0

- modules/dop/services/issuestream/issue_stream.go
- modules/dop/services/issuestream/issue_stream_template.go
- modules/dop/services/issuestream/issue_stream_template_test.go
- modules/dop/services/issuestream/issue_stream_test.go
issue event get context by org locale
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls3NzIsNjgwLDg4MSw4ODNdLCJtZW1iZXIiOlsiMTAwMTIwNSJdfQ%3D%3D&id=206539&iterationID=772&pId=0&type=BUG)
| 🇺🇸 English |  fix: issue event get context by org locale            |
| 🇨🇳 中文    |   事项发送内容中英文           |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTR …
> fix: issue event get context by org locale

- modules/pipeline/pipengine/reconciler/taskrun/taskop/prepare.go
When the default value of the loop field declineratio declinelimitsec of the original pipeline is empty, the value set is wrong and does not meet the user's expectations
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls3NzJdLCJtZW1iZXIiOlsiMTAwMDU2MCJdfQ%3D%3D&id=270607&iterationID=772&pId=0&type=BUG)
| 🇺🇸 English |      Pipline loop declineratio and declinelimitsec default settings modified        |
| 🇨🇳 中文    |      修改了 pipeline loop 的 declineratio和declinelimitsec默认设置        |
> fix: Pipline loop declineratio and declinelimitsec default settings modified

- modules/openapi/conf/conf.go
- modules/openapi/conf/conf_test.go
- modules/openapi/proxy/director.go
- modules/openapi/proxy/director_test.go
- pkg/discover/address.go
- pkg/discover/resolver.go
openapi support specify custom k8s svc addr from env
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=257374&issueFilter__urlQuery=eyJ0aXRsZSI6Im9wZW5hcGkiLCJzdGF0ZXMiOls0NDA2LDQ0MDddfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=883&type=TASK)
| 🇺🇸 English | openapi support specify custom service addr from env           |
| 🇨🇳 中文    | OPENAPI 支持从环境变量中获取 k8s 服务的自定义地址            | …
> feat: openapi support specify custom k8s svc addr from env

- apistructs/labels.go
- apistructs/pipeline_queue.go
- modules/pipeline/services/pipelinesvc/create_v2.go
- modules/pipeline/services/pipelinesvc/run.go
- modules/pipeline/spec/pipeline.go
- modules/pipeline/spec/pipeline_extra.go
- modules/pipeline/spec/pipeline_test.go
support enqueue condition
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls3NzIsNjgwLDg4MSw4ODNdLCJtZW1iZXIiOlsiMTAwMTIwNSJdfQ%3D%3D&id=208629&iterationID=772&pId=0&type=REQUIREMENT)
| 🇺🇸 English |   support enqueue condition            |
| 🇨🇳 中文    |  增加了入队策略，支持跳过running的检查入队            |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTI …
> feat: support enqueue condition

- modules/dop/dao/testcase.go
- modules/dop/dao/testplan.go
- modules/dop/dao/testplan_testcase_relation.go
- modules/dop/endpoints/testcase.go
- pkg/ucauth/unassigned.go
- pkg/ucauth/unassigned_test.go
- pkg/ucauth/user.go
fix: manual-test recognize member 'unassigned' as id
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=269348&issueFilter__urlQuery=eyJ0aXRsZSI6IuacquaMh%2BWumiIsInN0YXRlcyI6WzQ0MTIsNDUzOCw0NDEzLDQ0MTQsNDQxNSw0NDE2XX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG)
| 🇺🇸 English |  Fixed an bug that manual-test could not filter out "unspecified" users          |
| 🇨🇳 中文    |   修复了手动测试无法过滤出"未指定"用户的问题           |
> fix: manual-test recognize member 'unassigned' as id

- bundle/orchestrator.go
bugfix: batch runtime scale API return data may be nil
bugfix: batch runtime scale API return data may be nil
| 🇺🇸 English |     bugfix: batch runtime scale API return data may be nil         |
| 🇨🇳 中文    |       问题修复：批量 runtimes scale 处理 API 可能返回空值导致空指针错误        |
> fix: batch runtime scale API return data may be nil

- .erda/migrations/qa/20220110-file-record-soft-delete.sql
fix file record migration,non-need add uk index
| 🇺🇸 English | fix file record migration,non-need add uk index             |
| 🇨🇳 中文    | 去除联合索引             |
> fix: fix file record migration

- modules/core-services/services/project/project.go
- modules/openapi/api/apis/core_services/cmdb_projects_update.go
fix duplicated audits of update project
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=240645&issueFilter__urlQuery=eyJ0aXRsZSI6IuS%2FruaUuemhueebriBxdW90Ye%2B8jOWuoeiuoeaXpeW%2Fl%2BaYvuekuuS4pOadoSIsInN0YXRlcyI6WzQ0MTIsNDUzOCw0NDEzLDQ0MTQsNDQxNSw0NDE2XX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG)
| 🇺🇸 English | fix duplicated audits of update project               |
| 🇨🇳 中文    |    修复了更新项目审计多余的bug          |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRI …
> fix: fix duplicated audits of update project

- modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/pipelineTable/provider.go
project pipeline exec list begin time panic bugfix
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODMsNzcyXSwibWVtYmVyIjpbIjEwMDEyNjEiLCIxMDAwNTYwIl19&id=275895&iterationID=772&pId=0&type=BUG)
| 🇺🇸 English |      project pipeline exec list begin time panic bugfix        |
| 🇨🇳 中文    |       项目流水线空指针问题解决       |
> fix: project pipeline exec list begin time panic bugfix

- conf/dop/i18n/cp/scenarios/test-report.yaml
- modules/dop/component-protocol/components/test-report/createReportButton/render.go
- modules/dop/component-protocol/components/test-report/filter/render.go
- modules/dop/component-protocol/components/test-report/table/render.go
i18n of test report component
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=272293&issueFilter__urlQuery=eyJ0aXRsZSI6IuOAkOWbvemZheWMluOAkVRlc3QgbWFuYWdlbWVudC9UZXN0IHJlcG9ydCIsInN0YXRlcyI6WzQ0MDYsNDQwN119&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=TASK)
| 🇺🇸 English |  Fix the bug that i18n of test report            |
| 🇨🇳 中文    |  修复了测试报告国际化            | …
> fix: i18n of test report

- modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/pipelineTable/provider.go
fix: project pipeline records add userIDs
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODMsNzcyXSwibWVtYmVyIjpbIjEwMDEyNjEiXX0%3D&id=276020&iterationID=772&pId=0&type=BUG)
| 🇺🇸 English |     project pipeline records add userIDs         |
| 🇨🇳 中文    |         项目级流水线增加userIDs     |
> fix: project pipeline records add userIDs

- bundle/org.go
- modules/core-services/services/org/org.go
Move find cluster resource in dereference cluster to bundle
| 🇺🇸 English |  Core-services dereference cluster decouple orchestrator      |
| 🇨🇳 中文    |     Core-services 接触集群关联 解耦 orchestrator            |
> refactor: Core-services dereference cluster decouple orchestrator   

- conf/monitor/monitor/monitor.yaml
- modules/monitor/monitoring/provider.go
disable stats metric storage
| 🇺🇸 English |       disable stats metric storage default      |
| 🇨🇳 中文    |       默认情况下禁用指标容量统计       |
> refactor: disable stats default

- modules/actionagent/agenttool/tar.go
- modules/actionagent/define.go
- modules/actionagent/step_prepare.go
- modules/actionagent/step_restore.go
- modules/actionagent/step_sore_test.go
- modules/actionagent/step_store.go
agent support limit cache file size
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls3NzIsNjgwLDg4MSw4ODMsNDY3XSwibWVtYmVyIjpbIjEwMDEyMDUiXX0%3D&id=274465&iterationID=772&pId=0&type=TASK)
| 🇺🇸 English |   agent limit cache file size           |
| 🇨🇳 中文    |  pipeline cache大小限制            |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTI …
> fix: agent support limit cache tar file size

- modules/dop/conf/conf.go
- modules/dop/services/application/application.go
The push code failed due to a problem with the generated action params address
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODMsNzcyXSwibWVtYmVyIjpbIjEwMDA1NjAiXX0%3D&id=276871&iterationID=772&pId=0&type=BUG)
| 🇺🇸 English |      Fix mobile app initialization failure        |
| 🇨🇳 中文    |        修复移动应用初始化失败的问题      |
> fix: DOP failed to initialize mobile app

- modules/cmp/component-protocol/components/cmp-dashboard-events-list/eventTable/render.go
- modules/cmp/endpoints/cluster.go
- modules/cmp/steve/aggregator.go
fix: update steve when update cluster
| 🇺🇸 English | fix: update steve when update cluster |
| 🇨🇳 中文    | 更新集群后更新对应的steve |
> fix: update steve when update cluster

- modules/dop/component-protocol/scenarios/project-pipeline-exec-list.yml
- modules/pipeline/dbclient/op_pipeline.go
fix: records support fuzzy matching and add defaultrendering
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODMsNzcyXSwibWVtYmVyIjpbIjEwMDEyNjEiXX0%3D&id=276032&iterationID=772&pId=0&type=BUG)
| 🇺🇸 English |      fix: records support fuzzy matching and add defaultrendering        |
| 🇨🇳 中文    |     项目级流水线执行记录支持名称模糊匹配         | …
> fix: records support fuzzy matching and add defaultrendering

- modules/dop/providers/projectpipeline/service_impl.go
- modules/pipeline/providers/definition/pipeline_definition.go
If the createrequest commit and confignamespace of the pipeline are not updated, the pre check of the execution pipeline will fail
| 🇺🇸 English |        Update the commit and confignamespaces information when the project pipeline is executing     |
| 🇨🇳 中文    |       项目流水线执行的时候更新 commit 和 configNamespaces 信息       |
> fix: Update pipeline createRequest commit information and confignamespaces information when the project pipeline executing

- modules/openapi/component-protocol/generate/gen_auto_register.go
- modules/openapi/component-protocol/protocol.go
- modules/openapi/component-protocol/scenario_render.go
Legacy component default render support i18n
/assign @sfwn 
| 🇺🇸 English |  Legacy component default render support i18n            |
| 🇨🇳 中文    |     组件化 默认定义 国际化         |
> feat: Legacy component default render support i18n

- modules/orchestrator/services/deployment_order/deployment_order_get.go
- modules/orchestrator/services/deployment_order/deployment_order_list.go
- modules/orchestrator/services/deployment_order/deployment_order_render.go
fix deployment order resp type is empty
| 🇺🇸 English | fix deployment order resp type is empty             |
| 🇨🇳 中文    |  修复部署单类型返回是空的情况           |
> fix: deployment order resp type is empty

- modules/pipeline/dbclient/op_pipeline.go
Fix the null pointer caused by the abnormal connection of the pipeline
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=277885&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDA2LDQ0MDddfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=0&type=TASK)
| 🇺🇸 English |      Fix the abnormal connection of the pipeline, causing the null pointer to restart        |
| 🇨🇳 中文    |       修复流水线异常连接，导致空指针重启       |
> fix: fix the null pointer caused by the abnormal connection of the pipeline

- modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/filter/render.go
- modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/formModal/render.go
- modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/table/render.go
- modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/table/render_test.go
- modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/table/table_test.go
- modules/openapi/component-protocol/scenarios/auto-test-plan-list/helper.go
- modules/openapi/component-protocol/scenarios/auto-test-plan-list/i18n/i18n.go
(cherry picked from commit 459c203eab553eed478d3920e61de2bcd5bd002e)
hotfix i18n of autotest plan list (#3735)
| 🇺🇸 English |   hotfix i18n of autotest plan list (#3735)            |
| 🇨🇳 中文    |   自动化测试列表的国际化hotfix           |
> fix: i18n of autotest plan list (#3735)

- modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
Project pipeline inode access pipeline details access failed
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODMsNzcyXSwibWVtYmVyIjpbIjEwMDA1NjAiXX0%3D&id=278442&iterationID=772&pId=0&type=BUG)
| 🇺🇸 English |      Modify the inode base64 method, use urlEncode       |
| 🇨🇳 中文    |      修改inode base64方法, 使用 urlEncode        |
> fix: Project pipeline inode access pipeline details access failed

- modules/orchestrator/endpoints/addon.go
The addon creation interface has been changed, and the query of automatic test configuration sheet needs to be changed
| 🇺🇸 English |       The addon creation interface has been changed, and the query of automatic test configuration sheet needs to be changed       |
| 🇨🇳 中文    |        addon 创建接口有变更，需要变更下自动化测试配置单的查询      |
> fix: autotest configsheet datasource addon search

- modules/orchestrator/services/runtime/runtime.go
fix: concurrent map writes in get runtime service status
| 🇺🇸 English |       fix: concurrent map writes in get runtime service status       |
| 🇨🇳 中文    |          修复getRuntimeService的map并发写入问题    |
> fix: concurrent map writes in get runtime service status

- modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/inParamsForm/inParamsForm.go
- modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/inParamsForm/render.go
- modules/dop/component-protocol/scenarios/auto-test-scenes.yml
Fix the repeated call interface of automatic test scenario input parameters
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODMsNzcyXSwibWVtYmVyIjpbIjEwMDA1NjAiXX0%3D&id=278894&iterationID=772&pId=0&type=TASK)
| 🇺🇸 English |        Fix the repeated call interface of automatic test scenario input parameters      |
| 🇨🇳 中文    |       修复自动化测试场景入参重复调用接口       |
> feat: the repeated call interface of automatic test scenario input parameters

- modules/dop/component-protocol/scenarios/addon-mysql-account.yml
render fail when delete mysql addon
| 🇺🇸 English |    fix(dop): unexpected render missing create button when delete mysql addon account          |
| 🇨🇳 中文    |      修复删除mysql 账号时渲染失败缺少创建按钮的问题        |
> fix(dop): unexpected render missing create button when delete mysql addon account

- .licenserc.json
- conf/resources.go
- go.mod
- go.sum
- modules/core/services/filenamager/common.go
- modules/core/services/filenamager/file.manager.service.go
- modules/openapi/api/apis/monitor/monitor_filemanager_download.go
- modules/openapi/api/apis/monitor/monitor_filemanager_upload.go
- pkg/k8s/httpstream/spdy/connection.go
- pkg/k8s/httpstream/spdy/connection_test.go
- pkg/k8s/httpstream/spdy/roundtripper.go
- pkg/k8s/httpstream/spdy/roundtripper_test.go
- pkg/k8s/httpstream/spdy/tls.go
- pkg/k8s/httpstream/spdy/upgrade.go
- pkg/k8s/httpstream/spdy/upgrade_test.go
- pkg/k8s/remotecommand/remotecommand.go
- pkg/k8s/spdy/spdy.go
1、k8s remotecommand support cluster-dialer
2、fix monitor agent injector config path
3、fix filemanager openapi path
| 🇺🇸 English |     k8s remotecommand support cluster-dialer         |
| 🇨🇳 中文    |    支持 通过 cluster-dialer 执行 k8s  pod 命令    |
> fix: k8s remotecommand support cluster-dialer

- modules/openapi/api/apis/uc/uc_user_update_userinfo.go
- modules/openapi/reverseproxy.go
- modules/openapi/reverseproxy_test.go
deal X-Forwarded-For header value filter space
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=278853&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG)
| 🇺🇸 English |Fix the bug that deal X-Forwarded-For header value filter space              |
| 🇨🇳 中文    |   修复了审计日志client IP错误           |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to …
> fix: deal X-Forwarded-For header value filter space

- conf/dop/i18n/cp/common.yaml
- conf/dop/i18n/cp/scenarios/app-list-all.yaml
- modules/dop/component-protocol/components/app-list-all/list/app.go
- modules/dop/component-protocol/components/app-list-all/list/provider.go
- modules/dop/component-protocol/components/common/urlQuery.go
- modules/dop/component-protocol/components/issue-manage/issueTable/render.go
App list icon selectable, operation, icon update
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODMsMTA2OSw4ODEsNjgwLDc3MiwtMV0sIm1lbWJlciI6WyIxMDAxMDczIl19&id=277548&iterationID=772&pId=0&type=TASK)
/assign @sfwn 
| 🇺🇸 English |   App list icon selectable, operation, icon update           |
| 🇨🇳 中文    |    应用列表 更新          |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CO …
> feat: App list item selectable, goto operation, icon update

- modules/cmp/component-protocol/components/cmp-dashboard-pods/consoleButton/render.go
- modules/cmp/component-protocol/components/cmp-dashboard-pods/scenario.go
- modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/consoleButton/render.go
- modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/scenario.go
- modules/cmp/component-protocol/scenarios/cmp-dashboard-pods.yml
- modules/cmp/component-protocol/scenarios/cmp-dashboard-workloads-list.yml
fix: cherry-pick add console button #3819 to release/1.5
| 🇺🇸 English | fix: cherry-pick add console button #3819 to release/1.5 |
| 🇨🇳 中文    | 在release/1.5版本中修复英文状态下CMP dashboard中控制台按钮与创建按钮重合的问题 |
> fix: cherry-pick add console button #3819 to release/1.5

- modules/pipeline/aop/plugins/pipeline/testplan_after/plugin.go
filter out duplicate pipelines when reporting the number of executions
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODMsNzcyXSwibWVtYmVyIjpbIjEwMDEyNjEiXX0%3D&id=274143&iterationID=772&pId=0&type=BUG)
| 🇺🇸 English |      filter out duplicate pipelines when reporting the number of executions        |
| 🇨🇳 中文    |      上报执行数量时过滤掉重复上报的流水线       | …
> fix(pipeline): filter out duplicate pipelines when reporting the number of executions

- modules/core-services/services/project/project.go
- modules/dop/endpoints/project.go
- modules/dop/initialize.go
Optimize project list statistics
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOlsxMDY5LDEwOTBdLCJtZW1iZXIiOlsiMTAwMTI2MSJdfQ%3D%3D&id=279349&iterationID=1090&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |      Optimize project list statistics        |
| 🇨🇳 中文    |       优化项目列表统计       |
> fix(dop): Optimize project list statistics

- modules/dop/services/filetree/filetree.go
- modules/dop/services/filetree/filetree_test.go
Modification of branch calculation method, If the number of / characters of the branch is calculated incorrectly, the pipelines directory will not be obtained.
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOlsxMDY5LDg4Myw3NzIsMTA5MF0sIm1lbWJlciI6WyIxMDAwNTYwIl19&id=281110&iterationID=772&pId=0&type=BUG)
| 🇺🇸 English |       Modification of branch calculation method       |
| 🇨🇳 中文    |       分支计算方式修改       |
> fix: Modification of branch calculation method

- modules/dop/component-protocol/components/release-manage/releaseFilter/render.go
fix: (cherry-pick to release/1.6-alpha.2) hide aggregate button (#4019)
| 🇺🇸 English | fix: (cherry-pick to release/1.6-alpha.2) hide aggregate button (#4019 )
| 🇨🇳 中文    | 在release/1.6中隐藏聚合按钮 |
> fix: (cherry-pick to release/1.6-alpha.2) hide aggregate button (#4019)

- go.mod
- go.sum
- modules/dop/component-protocol/scenarios/auto-test-scenes.yml
- modules/dop/services/autotest_v2/scene.go
Solve the problem of broken link caused by adding scenes
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOlsxMDY5LDEwOTBdLCJtZW1iZXIiOlsiMTAwMTI2MSJdfQ%3D%3D&id=282043&iterationID=1090&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |     Solve the problem of broken link caused by adding scenes         |
| 🇨🇳 中文    |       解决添加场景引起的断链问题       | …
> fix(dop): Solve the problem of broken link caused by adding scenes

- apistructs/addon.go
- apistructs/runtime_dto.go
- bundle/orchestrator.go
- modules/orchestrator/dbclient/addon_instance_routing.go
- modules/orchestrator/endpoints/addon.go
- modules/orchestrator/endpoints/endpoints.go
- modules/orchestrator/services/addon/addon.go
- modules/orchestrator/services/addon/addon_deploy.go
- modules/orchestrator/services/addon/addon_test.go
- modules/orchestrator/services/apierrors/errors.go
- modules/scheduler/executor/plugins/k8s/addon/redis/legacy/redis.go
- modules/scheduler/executor/plugins/k8s/addon/redis/redis.go
when erda deployment deleted, the addon pods will always running unless you delete addon,but addon may be reused for next deployment, so to release resources (cpu/memorys), can stop addon by scale addon services replicas to 0, this can retain addon services's PVC for reused，If you want reuse addon adgin,  can start addon by scale addon services replicas  original values 
Added an API for scale down or scale up addon
| 🇺🇸 English |     Added an API for scale down or scale up addon    |
| 🇨🇳 中文    |        addon scale API 支持停止/启动 addon      |
> feat: basic addon surpport stop/start

- modules/dop/component-protocol/scenarios/scenes-import-record.yml
set option: `returnAllComponents` true value
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=282456&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=0&type=BUG)
| 🇺🇸 English | Fix the bug that set option: `returnAllComponents` true value             |
| 🇨🇳 中文    |  修复了自动化测试组件化渲染            | …
> fix: set option: `returnAllComponents` true value

- modules/dop/component-protocol/components/release-manage/releaseTable/render.go
fix: print error rather than return if unmarshal release list failed
| 🇺🇸 English | fix: print error rather than return if unmarshal release list failed |
| 🇨🇳 中文    | 对项目制品的引用列表反序列化失败时只打印错误而不是直接返回 |
Need cherry-pick to release/1.6-alpha.3
> fix: print error rather than return if unmarshal release list failed

- pkg/apitestsv2/apitest_test.go
- pkg/apitestsv2/netportal.go
- pkg/apitestsv2/netportal_test.go
Automated testing, the request is proxied to the edge cluster regardless of whether it is an internal address or not
| 🇺🇸 English |     Automated testing, the request is proxied to the edge cluster regardless of whether it is an internal address or not         |
| 🇨🇳 中文    |       通过自动测试，无论请求是否为内部地址，都会将其代理到边缘群集       |
> feat: Automated testing, the request is proxied to the edge cluster regardless of whether it is an internal address or not

- modules/core-services/services/filesvc/svc.go
- modules/kms/endpoints/endpoints.go
- modules/kms/endpoints/kms.go
- pkg/kms/kms_test.go
- kms describe api invoke wrong method
- fix dop kms action as before (rotate cmk privateKeyVersion at bootstrap)
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=282686&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1069&type=TASK)
| 🇺🇸 English |   fix: kms describe api invoke wrong method           |
| 🇨🇳 中文    |     修复了 KMS Describe API 的错误方法调用         |
> fix: kms describe api invoke wrong method

- modules/dicehub/service/release/release.go
- modules/dop/component-protocol/components/release-manage/releaseTable/render.go
fix: release group can not be empty
| 🇺🇸 English | fix: release group can not be empty |
| 🇨🇳 中文    | 修复创建项目制品时引用应用制品组为空后还能创建成功的问题 |
Need cherry-pick to release/1.6-alpha.3
> fix: release group can not be empty

- conf/monitor/monitor/monitor.yaml
- modules/core/monitor/log/query/log.query.service.go
- modules/core/monitor/log/query/provider.go
- modules/core/monitor/storekit/elasticsearch/iterator.go
- modules/core/monitor/storekit/ratelimit.go
- modules/core/monitor/storekit/ratelimit_test.go
throttle download api
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODEsNjgwLDc3MiwtMSw4ODMsMTA5MCwxMDY5XSwibWVtYmVyIjpbIjEwMDAzMDEiXX0%3D&id=282713&iterationID=1090&pId=0&type=REQUIREMENT)
| 🇺🇸 English |       download log throttling       |
| 🇨🇳 中文    |      日志下载接口限流        |
> feat: download log API throttling

- .erda/migrations/cmdb/20220214-delete-empty-userid-member.sql
- pkg/ucauth/user_admin.go
check user is-existed when add member
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOlsxMDY5LDg4Myw4ODEsMTA5MCw3NzJdLCJtZW1iZXIiOlsiMTAwMTIwNSJdfQ%3D%3D&id=282243&iterationID=1090&pId=0&type=BUG)
| 🇺🇸 English |  Fix the bug that empty user in dice_member            |
| 🇨🇳 中文    |  修复了项目成员列表存在空成员的bug            |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/m …
> fix: check user is-existed when add member

- modules/core-services/services/member/member.go
- modules/core-services/services/member/member_test.go
- pkg/ucauth/user_admin.go
check user is-existed in member service
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=e30%3D&id=282243&iterationID=1090&pId=0&type=BUG)
| 🇺🇸 English | Fix the bug that check user is-existed in member service             |
| 🇨🇳 中文    |   用户是否存在的校验放在上层service中           |
> fix: check user is-existed in member service

- conf/core-services/i18n/i18n.yaml
- conf/dop/i18n/cp/scenarios/auto-test-scenes.yaml
- modules/core-services/endpoints/member.go
- modules/core-services/initialize.go
- modules/core-services/services/member/member.go
- modules/dop/component-protocol/scenarios/auto-test-scenes.yml
- pkg/erda-configs/i18n/cmdb.json
- pkg/erda-configs/i18n/orchestrator.json
Add member project owner error i18n, fix duplicate i18n key
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOls3NzIsNjgwLDg4MSw4ODMsMTA2OSwxMDkwXSwiYXNzaWduZWUiOlsiMTAwMTA3MyJdfQ%3D%3D&id=279903&iterationID=1090&pId=0&type=BUG)
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOls3NzIsNjgwLDg4MSw4ODMsMTA2OSwxMDkwXSwiYXNzaWduZWUiOlsiMTAwMTA3MyJdfQ%3D%3D&id=285086&iterationID=1090&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |  Add member project owner error i18n, fix duplicate i18n key             |
| 🇨🇳 中文    |    添加项目所有者错误国际化          |
Add comment like `/cherry-pick release/1.0` when …
> fix: Add member project owner error i18n, fix duplicate i18n key

- modules/pipeline/conf/conf.go
- modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/manager.go
pipeline creates k8s executors concurrently when initializing
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOlsxMDkwXSwibWVtYmVyIjpbIjEwMDEyMDUiXX0%3D&id=283781&iterationID=1090&pId=0&type=TASK)
| 🇺🇸 English |  Fix the bug that pipeline creates k8s executors concurrently when initializing           |
| 🇨🇳 中文    |     pipeline启动时并发的去创建k8s executor         | …
> fix: pipeline creates k8s executors concurrently when initializing

- modules/hepa/apipolicy/policies/server-guard/dto.go
- modules/hepa/apipolicy/policies/server-guard/dto_test.go
- modules/hepa/apipolicy/policies/server-guard/policy.go
- pkg/strutil/interpolate.go
When the current limit is triggered, cross-domain is allowed
| 🇺🇸 English | When the current limit is triggered, cross-domain is allowed. When the throttling reject response conforms to JSON format, Content-Type is automatically set to application/json. |
| 🇨🇳 中文    | 当触发限流时，允许跨域。当限流的拒绝响应符合 JSON 格式时，Content-Type 自动设置为 application/json. | …
> feat: cors in rate-limiting

- apistructs/pipeline_container_instance.go
- modules/pipeline/pkg/container_provider/container_instance_provider.go
- modules/pipeline/pkg/container_provider/container_provider_test.go
- modules/pipeline/services/pipelinesvc/create_v2.go
disable eci for pipelines containing custom tasks
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMDkwLDExMTVdLCJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=285869&iterationID=1115&pId=0&type=TASK)
/assign @sfwn 
| 🇺🇸 English |  Fix the bug that disable eci for pipelines containing custom tasks            |
| 🇨🇳 中文    |  禁止包含自定义任务的流水线使用eci            | …
> fix(pipeline): disable eci for pipelines containing custom tasks

- modules/dicehub/release/release.go
- modules/dop/component-protocol/components/release-manage/releaseTable/render.go
fix: use old release dice if conflict when upload
| 🇺🇸 English | fix: use old release dice if conflict when upload |
| 🇨🇳 中文    | 上传制品时如果存在相同version且不同dice.yml的应用制品，使用旧制品的dice.yml而不是上传文件中的dice.yml |
Need cherry-pick to release/1.6-alpha.4
> fix: use old release dice if conflict when upload

- conf/dop/i18n/cp/common.yaml
- modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
project pipeline table add source file field
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMDkwLDExMTUsMTA2OV0sImFzc2lnbmVlIjpbIjU1IiwiMTAwMTIwNSIsIjkyIiwiMTAwMDU2MCIsIjEwMDEyNjEiLCIxMDAxMDczIl19&id=285636&iterationID=1090&pId=0&type=REQUIREMENT)
| 🇺🇸 English |       project pipeline table add source file field       |
| 🇨🇳 中文    |       项目流水线table增加 sourceFile 字段       |
> feat: project pipeline table add source file field

- modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
remove project pipeline table source file column
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMDkwLDExMTUsMTA2OV0sImFzc2lnbmVlIjpbIjU1IiwiMTAwMTIwNSIsIjkyIiwiMTAwMDU2MCIsIjEwMDEyNjEiLCIxMDAxMDczIl19&id=285636&iterationID=1090&pId=0&type=REQUIREMENT)
| 🇺🇸 English |     remove project pipeline table source file column         |
| 🇨🇳 中文    |      删除项目流水线表源文件列        |
> feat: remove project pipeline table source file column

- modules/orchestrator/services/addon/addon_sourcecov.go
for pass some configurations to sourcecov agent, need set volumes configurations, but did not set volume targetPath, which result to servicegroup can not create  
Bugfix： Fix the bug that  sourcecov addon can not create （修复了 sourcecov addon 部署失败的问题）
| 🇺🇸 English |      Fix the bug that  sourcecov addon can not create         |
| 🇨🇳 中文    |      修复了 sourcecov addon 部署失败的问题        |
/cherry-pick release/1.6-alpha.4
> fix: sourcecov volume config

- modules/orchestrator/scheduler/executor/plugins/k8s/instanceinfosync/pod.go
Get containerID from Pod Status may get unknown container which containerID may be nil. 
| 🇺🇸 English |         Fix the bug that get containerID from Pod Status may get unknown container which containerID is nil.,which result in out of range fatal     |
| 🇨🇳 中文    |      修复了 Pod Status 中包含未知状态的容器导致容器ID为空触发数组越界        |
/cherry-pick 1.6-alpha.4
> fix: fix get containerID out of range fatal

- modules/orchestrator/scheduler/impl/servicegroup/servicegroup.go
- modules/orchestrator/services/deployment/deployment_context.go
- pkg/k8s/storage/detect_sc.go
- pkg/k8s/storage/detect_sc_test.go
1. service volumes in old type define may be not set  `storage` filed, need detect it as old volume type by 'path' filed. 
2. Adjust volume with not set storage, set default volume type as dice-nfs-volume
Bugfix： Fix the bug that need detect volume as old volume type by 'path' filed.（修复了 Service 的 volumes 的旧的格式定义可能 storage 字段不设置，导致无法通过 storage 字段识别是否是旧格式的 volume 的问题，同时调整默认 volume 类型）
| 🇺🇸 English |       Fix the bug that need detect volume as old volume type by 'path' filed.    |
| 🇨🇳 中文    |     修复了 Service 的 volumes 的旧的格式定义可能 storage 字段不设置，导致无法通过 storage 字段识别是否是旧格式的 volume 的问题，同时调整默认 volume 类型     |
/cherry-pick   1.6-alpha.4
> fix: fix volume without storage, set default volume type

- modules/orchestrator/components/addon/mysql/mysql.service.go
- modules/orchestrator/components/addon/mysql/provider.go
bad mysql addon password decryption
| 🇺🇸 English |   bad mysql addon password decryption           |
| 🇨🇳 中文    |     修复历史数据 mysql addon 密码解密失败         |
> fix: bad mysql addon password decryption

- modules/core/monitor/storekit/elasticsearch/index/loader/routes.go
- modules/core/monitor/storekit/elasticsearch/index/loader/routes_test.go
show tenant size
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTE1LDEwOTAsMTA2OSw4ODNdLCJhc3NpZ25lZSI6WyIxMDAwMzAxIl0sImxhYmVsIjpbMTQ1NV19&id=286925&iterationID=1069&pId=0&type=TASK)
| 🇺🇸 English |        add tenant index size API      |
| 🇨🇳 中文    |       增加租户索引容量接口       |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md) …
> feat: index loader support tenant size

- modules/core/monitor/alert/alert-apis/adapt/expression.go
add vms target in customize alert rule
| 🇺🇸 English |       add vms target in customize alert rule       |
| 🇨🇳 中文    |       增加电话告警通知方式       |
> fix: add vms target in customize alert rule

- apistructs/notify_history.go
add json tag for cluster name
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=287393&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=0&type=BUG)
| 🇺🇸 English | Fix the bug that missing `clusterName` when create notify             |
| 🇨🇳 中文    |     修复了通知缺少了集群名称         | …
> fix(eventbox): add json tag for cluster name

- modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
Hide the delete button without permission
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=279365&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDA1NjAiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1115&type=BUG)
| 🇺🇸 English |       Hide the delete button without permission       |
| 🇨🇳 中文    |       没有权限就将删除按钮隐藏       |
> feat(dop): project pipeline Hide the delete button without permission

- modules/eventbox/subscriber/common.go
- modules/eventbox/subscriber/dingding/dingding.go
- modules/eventbox/subscriber/dingtalk_worknotice/dingtalk_worknotice.go
- modules/eventbox/subscriber/email/email.go
- modules/eventbox/subscriber/mbox/mbox.go
- modules/eventbox/subscriber/sms/sms.go
- modules/eventbox/subscriber/vms/vms.go
eventbox save notify history is nil pointer dereference
| 🇺🇸 English |       eventbox save notify history is nil pointer dereference       |
| 🇨🇳 中文    |       eventbox存通知记录panic       |
> fix: eventbox save notify history is nil pointer dereference

- modules/dop/services/pipeline/pipeline.go
This reverts commit 5eef37267208a558d56f74d923335b8c55fc8a05.
revert: "dop remove workspace label"
| 🇺🇸 English | revert commit of workspace label              |
| 🇨🇳 中文    |   回退workspace标签的去除           |
> revert: "dop remove workspace label"

- modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
When adding a cron expression to the YML file, the start cron button is turned on. When removing the cron expression, the cron button is hidden
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=275783&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDA1NjAiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1115&type=BUG)
| 🇺🇸 English |       When adding a cron expression to the YML file, the start cron button is turned on. When removing the cron expression, the cron button is hidden       |
| 🇨🇳 中文    |       将 cron 表达式添加到YML文件时，cron 按钮处于打开状态。删除 cron 表达式时，cron 按钮将隐藏       |
> feat(dop): project pipeline decide whether to turn on or off the cron button according to the yml cron expression

- modules/pipeline/dbclient/op_pipeline_definition.go
- modules/pipeline/pipengine/reconciler/dbgc.go
Solve the problem that the pipeline bound by the definition is GC, which causes the user to view the execution details and report an error
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=289045&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDA1NjAiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1115&type=BUG)
| 🇺🇸 English |       Solve the problem that the pipeline bound by the definition is GC, which causes the user to view the execution details and report an error       |
| 🇨🇳 中文    |       解决由于 definition 绑定的 pipeline 被 gc，导致用户查看执行明细报错       |
test image:
change bind pipeline_id time info:
restart pipeline gc info:
> fix(dop): When the pipeline is GC, if the definition is bound to the pipeline_ ID does not perform GC operations

- modules/orchestrator/scheduler/impl/servicegroup/servicegroup.go
- modules/orchestrator/services/deployment/deployment_context.go
- pkg/k8s/storage/detect_sc.go
- pkg/k8s/storage/detect_sc_test.go
…(#4180)"
This reverts commit 96a4fc2b5ad4e896db6ce28f3982cca00c67c9db.
回退适配ECI的设置默认存储类型逻辑
| 🇺🇸 English |      revert    fix set volume without storage, set default volume type      |
| 🇨🇳 中文    |      回退适配ECI的设置默认存储类型逻辑        |
> fix: Revert fix set volume without storage, set default volume type

- modules/dicehub/service/release_rule/release_rule.go
- modules/dop/services/apidocsvc/ws_upgrade.go
- modules/eventbox/webhook/impl.go
- modules/orchestrator/scheduler/impl/job/job.go
- modules/orchestrator/scheduler/impl/volume/volume.go
- modules/orchestrator/scheduler/impl/volume/volume_test.go
- modules/pipeline/providers/definition/pipeline_definition.go
- modules/pipeline/providers/source/db/source.go
- pkg/crypto/uuid/uuid.go
- pkg/crypto/uuid/uuid_test.go
see: https://en.wikipedia.org/wiki/Universally_unique_identifier#Format
refactor: uuid return form of xxxxxxxx-xxxx-Mxxx-Nxxx-xxxxxxxxxxxx
| 🇺🇸 English |  UUID use standard RFC4122 format: xxxxxxxx-xxxx-Mxxx-Nxxx-xxxxxxxxxxxx           |
| 🇨🇳 中文    |    UUID 使用 RFC4122 标准格式 ：xxxxxxxx-xxxx-Mxxx-Nxxx-xxxxxxxxxxxx        |
> refactor: use standard RFC4122 form of uuid with hyphens

- apistructs/pipeline_task.go
- modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sflink/util.go
- modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sjob/k8sjob.go
- modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sspark/k8sspark.go
- modules/pipeline/pkg/containers/task_container.go
add `terminus_define_tag` annotation on k8sjob flink spark
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=290139&iterationID=1115&pId=0&type=TASK)
| 🇺🇸 English | Fix the bug that add `terminus_define_tag` annotation on k8sjob flink spark             |
| 🇨🇳 中文    |   将监控新定义的标签添加到annotation           | …
> fix(pipeline): add `terminus_define_tag` annotation on k8sjob flink spark

- modules/pipeline/conf/conf.go
- modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/manager.go
- modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sflink/type.go
- modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sjob/k8sjob.go
- modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sjob/k8sjob_test.go
- modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sspark/type.go
- modules/pipeline/pipengine/actionexecutor/plugins/scheduler/scheduler.go
- modules/pipeline/pipengine/actionexecutor/plugins/scheduler/scheduler_test.go
- modules/pipeline/pkg/clusterinfo/clusterinfo.go
optimization of pipeline k8s executor initialization
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=286324&iterationID=1115&pId=0&type=TASK)
| 🇺🇸 English |Fix the bug that optimization of pipeline k8s executor initialization              |
| 🇨🇳 中文    |     修复pipeline启动时多集群耗时慢的问题         | …
> fix(pipeline): optimization of pipeline k8s executor initialization

- apistructs/labels.go
- modules/dop/providers/projectpipeline/service_impl.go
The project pipeline executor search problem is fixed. The previous search was based on the search criteria of the creator of the definition as the executor
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=291011&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDA1NjAiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1115&type=BUG)
| 🇺🇸 English |       The project pipeline executor search problem is fixed. Previously, it was searched according to the creator of the definition, which is inconsistent with the existing semantics       |
| 🇨🇳 中文    |      项目流水线执行人搜索问题修复, 之前是按照definition的创建人来搜索的，这和现有的语义不符合        |
> fix(dop): Project pipeline executor search problem repair

- pkg/mock/mock_test.go
- pkg/mock/time.go
feat: support comstom date format
| 🇺🇸 English | support comstom date format in pipeline |
| 🇨🇳 中文    | 支持在流水线中输入格式更丰富的时间格式 |
```yaml
version: "1.1"
stages:
- stage:
- custom-script:
alias: custom-script
description: 运行自定义命令
version: "1.0"
image: registry.erda.cloud/erda-actions/custom-script-action:1.0-20211216-b1d5635
commands:
- echo "action meta:ANSIC=${{ random.datetime_custom_ANSIC }}"
- echo "action meta:UnixDate=${{ random.datetime_custom_UnixDate }}"
- echo "action meta:RubyDate=${{ random.datetime_custom_RubyDate }}"
- echo "action meta:RFC822=${{ random.datetime_custom_RFC822 }}"
- echo "action meta:RFC822Z=${{ …
```
> feat: support comstom date format

- modules/cmp/component-protocol/components/cmp-dashboard-pods/podsCharts/render.go
fix: display NaN% when total number of pod is 0
| 🇺🇸 English | fix: display NaN% when total number of pod is 0 |
| 🇨🇳 中文    | 修复CMP dashboard在pod总数为0时Pod chart显示NaN%的问题 |
> fix: display NaN% when total number of pod is 0

- erda.yml
set pipeline replicas default to 2
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=282421&issueFilter__urlQuery=eyJ0aXRsZSI6IuawtOW5s%2BaJqeWxlSIsInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNiw0NDA1XSwiYXNzaWduZWVJRHMiOlsiOTIiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1115&type=REQUIREMENT)
/assign @luobily @Effet 
| 🇺🇸 English |   set pipeline replicas default to 2           |
| 🇨🇳 中文    |   pipeline 组件的副本数默认设置为 2           |
> chore: set pipeline replicas default to 2

- modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesSetConfig/scenesStages/model.go
Remove setid of automated test scenessstages__ Urlquery and sceneid__urlQuery state
| 🇺🇸 English |        Remove setid of automated test scenessstages__ Urlquery and sceneid__urlQuery state      |
| 🇨🇳 中文    |       移除自动化测试 scenesStages 的 SetId__urlQuery 和 SceneId__urlQuery state       |
> refactor(dop): Remove setid of automated test scenes stages__urlquery and sceneid__urlquery state

- modules/hepa/repository/orm/gateway_zone.go
- modules/hepa/repository/orm/gateway_zone_test.go
- modules/hepa/services/zone/impl/impl.go
feat: need not delete ingress if the zone dose not hava ingress
| 🇺🇸 English | need not delete ingress if the zone dose not hava ingress |
| 🇨🇳 中文    | 修复了删除不符合 Ingress 命名合法性的流量入口失败的问题 |
> feat: need not delete ingress if the zone dose not hava ingress

- modules/hepa/gateway/assembler/gateway_kong_assembler.go
- modules/hepa/kong/base/kong_adapter.go
- modules/hepa/kong/dto/kong_route_req_dto.go
- modules/hepa/kong/dto/kong_route_req_dto_test.go
- modules/hepa/services/endpoint_api/impl/impl.go
feat: default 'v1' for kong path handling
| 🇺🇸 English | default 'v1' for kong path handling |
| 🇨🇳 中文    | 将 API 网关 Kong 的路径处理语法更换为 `v1` |
change Kong (API Gateway) path handling from red to bule.
> feat: default 'v1' for kong path handling

- modules/openapi/component-protocol/scenarios/action/components/actionForm/render.go
The project pipeline is special, and the manual review action needs to be added with scopeID props
| 🇺🇸 English |     the manual review action needs to be added with scopeID props       |
| 🇨🇳 中文    |      人工审核 action 需要额外加上 scopeID props        |
> fix(openapi): the manual review action needs to be added with scopeID props

- modules/dop/component-protocol/components/auto-test-scenes/leftPage/fileTree/model.go
- modules/dop/component-protocol/components/auto-test-scenes/leftPage/fileTree/render.go
- modules/dop/component-protocol/components/auto-test-scenes/leftPage/fileTree/scenes.go
Scene set supports drag and drop
https://user-images.githubusercontent.com/23724009/158137792-701191db-11ab-40be-a73c-d0be818a58f2.mov
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTMxLDExNDYsMTExNV0sImFzc2lnbmVlIjpbIjEwMDEyNjEiXX0%3D&id=291519&iterationID=1146&pId=0&type=TASK)
/assign @sfwn 
| 🇺🇸 English |      Scene set supports drag and drop         |
| 🇨🇳 中文    |       场景集支持拖拽       | …
> feat(dop): Scene set supports drag and drop

- tools/cli/cmd/clone.go
- tools/cli/cmd/config_delete.go
- tools/cli/cmd/config_get.go
- tools/cli/cmd/config_set.go
- tools/cli/cmd/config_update.go
- tools/cli/cmd/create.go
- tools/cli/cmd/project_deployment_start.go
- tools/cli/cmd/project_deployment_stop.go
- tools/cli/cmd/push.go
- tools/cli/common/config.go
- tools/cli/common/org.go
- tools/cli/common/project.go
Adjust erda-cli config and project-deployment logic for consistency with other erda-cli commands
/assign @sixther-dc @jferic 
Feature: Optimize erda-cli config and project-deployment logic for consistency with other erda-cli commands（优化 erda-cli config 和 erda-cli project-deployment 命令逻辑）
| 🇺🇸 English |       Optimize erda-cli config and project-deployment logic for consistency with other erda-cli commands       |
| 🇨🇳 中文    |    优化 erda-cli config 和 erda-cli project-deployment 命令逻辑         |
> refactor: adjust erda-cli config and project-deployment logic

- modules/hepa/kong/base/kong_adapter.go
- modules/hepa/kong/dto/kong_route_req_dto.go
- modules/hepa/kong/dto/kong_route_req_dto_test.go
feat: only set path_handling "v2" on Kong 2.x
| 🇺🇸 English | only set `path_handling` on Kong 2.x to be compatible with different versions of Kong |
| 🇨🇳 中文    | 仅在 Kong 为 2.x 版本时设置 `path_handling` 参数以兼容不同版本的 Kong |
> feat: only set `path_handling` on Kong 2.x to be compatible with different versions of Kong

- conf/dicehub/dicehub.yaml
fix: remove metricq-client in dicehub conf
| 🇺🇸 English | fix: remove metricq-client in dicehub conf |
| 🇨🇳 中文    | 移除dicehub的conf文件中对msp的依赖 |
> fix: remove metricq-client in dicehub conf

- .erda/migrations/cmdb/20220307-quota-user-id.sql
- apistructs/project_quota.go
- apistructs/project_test.go
- modules/core-services/services/project/project.go
- modules/core-services/services/project/project_test.go
cast userID to String
- Fixes #4057 
| 🇺🇸 English | fix the problem that failed to create project when the user_id is not int |
| 🇨🇳 中文    | 修复 user_id 不为数字时创建项目失败的问题 |
> feat: cast userID to String

- modules/pipeline/services/extmarketsvc/list.go
use pointer instead of passing by value when constructAllActions
| 🇺🇸 English | Fix the bug that pipeline panic caused by concurrent map write and read             |
| 🇨🇳 中文    |  修复了pipeline因为并发读写map造成的panic            |
> fix(pipeline): use pointer instead of passing by value when constructAllActions

- modules/pipeline/providers/leaderworker/worker/worker.go
Allow the handler to be null when the worker is not used to process logical task.
If you new a worker but not use it to handle task, no handler is acceptable.
tested on erda daily:
task dispatch key delete correctly:
| 🇺🇸 English |   Allow the handler to be null when the worker is not used to process logical task    |
| 🇨🇳 中文    |  当 worker 不用于处理逻辑任务时，允许 handler 为空            |
Add comment like `/cherry-pick release/2.1-beta.2` when this PR is merged.
> fix(pipeline): allow the handler to be null when the worker is not used to process logical task

- .erda/migrations/pipeline/20220322-pipeline-archive-add-index.sql
- modules/pipeline/providers/dbgc/db/pipeline_archives.go
- modules/pipeline/providers/dbgc/dbgc.go
- modules/pipeline/providers/dbgc/provider.go
clean up pipeline archives that have exceeded default retention time
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=248988&iterationID=-1&pId=290591&type=TASK)
| 🇺🇸 English |   Support clean up pipeline archives           |
| 🇨🇳 中文    |  实现了pipeline归档表的自动清理            |
> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTIN …
> feat: clean up pipeline archives

- modules/dop/component-protocol/components/auto-test-scenes/leftPage/fileTree/render.go
- modules/dop/component-protocol/components/auto-test-scenes/leftPage/fileTree/scenes.go
Do not expand when dragging
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTQ2XSwiYXNzaWduZWUiOlsiMTAwMTI2MSJdfQ%3D%3D&id=294297&iterationID=1146&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |      The scene set does not expand when dragging       |
| 🇨🇳 中文    |     场景集拖拽的时候不去展开         |
> fix(dop): The scene set does not expand when dragging

- modules/dop/services/autotest_v2/import.go
- modules/dop/services/autotest_v2/space_data.go
- modules/dop/services/i18n/i18n.go
- pkg/erda-configs/i18n/qa.json
add disabled field for autotest step when import and export
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTQ2XSwiYXNzaWduZWUiOlsiMTAwMTIwNSJdfQ%3D%3D&id=297516&iterationID=1146&pId=0&type=BUG)
| 🇺🇸 English |   Fix the bug that add disabled field for autotest step when import and export            |
| 🇨🇳 中文    |    修复了自动化测试复制时禁用功能的丢失          | …
> fix(dop): add disabled field for autotest step when import and export

- modules/dop/services/autotest_v2/scene.go
add is disable for step when copy autotest scene
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTQ2XSwiYXNzaWduZWUiOlsiMTAwMTIwNSJdfQ%3D%3D&id=297516&iterationID=1146&pId=0&type=BUG)
| 🇺🇸 English |  Fix the bug that add is disable for step when copy autotest scene             |
| 🇨🇳 中文    |   修复了复制场景时步骤禁用的丢失           | …
> fix(dop): add is disable for step when copy autotest scene

- modules/pipeline/providers/clusterinfo/cache.go
- modules/pipeline/providers/clusterinfo/chache_test.go
deep copy cluster info when query cluster from cache
| 🇺🇸 English |Fix the bug that concurrent write cluster info map              |
| 🇨🇳 中文    |   修复了并发写集群信息的问题           |
> fix(pipeline): deep copy cluster info when query cluster

- modules/pipeline/providers/reconciler/taskpolicy/provider.go
inject missing provider field for reconciler try-last-result task-policy
| 🇺🇸 English |  inject missing provider field for reconciler try-last-result task-policy            |
| 🇨🇳 中文    |  解决 "最近一次执行的结果" 执行策略空指针问题         |
Add comment like `/cherry-pick release/2.1-beta.3` when this PR is merged.
> fix(pipeline): reconciler try-last-result missing provider

- tools/cli/cmd/create.go
- tools/cli/cmd/issue_close.go
- tools/cli/cmd/mr_create.go
you may init env one by one
| 🇺🇸 English |      add --init-env parameter to  create project by package      |
| 🇨🇳 中文    |        使用工程包初始化项目支持指定环境      |
> feat: init env by project package

- modules/pipeline/commonutil/linkutil/link.go
- modules/pipeline/services/actionagentsvc/script.go
- modules/pipeline/services/pipelinesvc/run.go
query cluster info from provider instead of orchestrator
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that query cluster info from provider instead of orchestrator           |
| 🇨🇳 中文    |     解耦了pipeline查询orchestrator集群信息的依赖         |
> fix(pipeline): query cluster info from clusterinfo provider instead of orchestrator

- modules/orchestrator/scheduler/executor/plugins/k8s/instanceinfosync/pod.go
Different ECI pods have duplicated container ID result incorrect logic
Bugfix： Fix the bug that  different ECI pods have duplicated container ID result incorrect logic
（修复了 ECI Pod 可能具有相同的 containerID 导致 erda 工作台使用 containerID 展示服务信息失败 ）
| 🇺🇸 English |      Fix the bug that  different ECI pods have duplicated container ID result incorrect logic        |
| 🇨🇳 中文    |      修复了 ECI Pod 可能具有相同的 containerID 导致 erda 工作台使用 containerID 展示服务信息失败        |
> fix: different ECI pods have duplicated container ID

- erda.yml
- modules/orchestrator/scheduler/executor/plugins/k8s/deployment.go
- modules/orchestrator/scheduler/executor/plugins/k8s/deployment_test.go
- modules/orchestrator/scheduler/executor/plugins/k8s/job.go
- modules/orchestrator/scheduler/executor/plugins/k8s/k8s.go
- modules/orchestrator/scheduler/executor/plugins/k8s/k8s_test.go
- modules/orchestrator/scheduler/executor/plugins/k8s/statefulset.go
ECI Pod fluent-bit image need set by Env,  ECI Pod fluent-bit container need add env DICE_IS_EDGE for deployed in edge cluster
/assign @sixther-dc @iutx @luobily 
Bugfix： ECI Pod fluent-bit image need set by Env,  ECI Pod fluent-bit container need add env DICE_IS_EDGE for deployed in edge cluster （修复了 ECI Pod fluent-bit 镜像设置参数，对于 Edge 环境部署需要增加环境变量 DICE_IS_EDGE ）
| 🇺🇸 English |        ECI Pod fluent-bit image need set by Env,  ECI Pod fluent-bit container need add env DICE_IS_EDGE for deployed in edge cluster        |
| 🇨🇳 中文    |     修复了 ECI Pod fluent-bit 镜像设置参数，对于 Edge 环境部署需要增加环境变量 DICE_IS_EDGE          |
> fix: ECI pod fluent-bit container image and env

- modules/dop/providers/cms/cicdcmsservice.go
- modules/dop/providers/cms/cicdcmsservice_test.go
Delete unnecessary keys in project pipeline configuration
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTY0XSwiYXNzaWduZWUiOlsiMTAwMDU2MCJdfQ%3D%3D&id=299271&iterationID=1164&pId=293275&type=TASK)
| 🇺🇸 English |      Delete unnecessary keys in project pipeline configuration        |
| 🇨🇳 中文    |        项目流水线配置删除不需要的key      |
> feat(dop): Delete unnecessary keys in project pipeline configuration

- modules/pipeline/providers/reconciler/pipeline_reconciler.go
- modules/pipeline/providers/reconciler/task_reconciler.go
fix reconciler calculate pipeline status by all reconciled tasks.
before this fix, tasks which should be `NoNeedBySystem` but be reconciled.
| 🇺🇸 English |   fix tasks which should be `NoNeedBySystem` but be reconciled          |
| 🇨🇳 中文    |  修复了流水线中应该是"无需执行"的任务却被推进的问题           |
> fix(pipeline): reconciler calculate pipeline status by all reconciled tasks

- modules/pipeline/providers/leaderworker/leader_framework.go
- modules/pipeline/providers/reconciler/pipeline_reconciler.go
- modules/pipeline/providers/reconciler/reconcile.go
reconciler push in DAG mode
| 🇺🇸 English |  reconciler trigger pipeline's next reconcile-loop immediately when one task done            |
| 🇨🇳 中文    |  当一个任务结束时，立即触发 pipeline 的下一次推进            |
> feat(pipeline): reconciler trigger pipeline's next reconcile-loop immediately when one task done

- bundle/filetree.go
- modules/dop/endpoints/pipeline.go
- modules/dop/endpoints/release.go
- modules/dop/endpoints/release_test.go
.erda/ pipelines and The pipeline yml in the .dice/pipelines folder supports on push events
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTY0XSwiYXNzaWduZWUiOlsiMTAwMDU2MCJdfQ%3D%3D&id=299403&iterationID=1164&pId=295915&type=TASK)
| 🇺🇸 English |      .erda/ pipelines and The pipeline yml in the .dice/pipelines folder supports on push events       |
| 🇨🇳 中文    |       .erda/pipelines 和 .dice/pipelines  文件夹下的流水线文件支持 on push 事件      |
> fix(dop): .erda/ pipelines and The pipeline yml in the .dice/pipelines folder supports on push events

- modules/orchestrator/scheduler/executor/plugins/edas/edas.go
- modules/orchestrator/services/runtime/runtime.go
fix: remove runtime status event send for edas executor
fix: remove runtime status event send for edas executor
| 🇺🇸 English |     fix: remove runtime status event send for edas executor         |
| 🇨🇳 中文    |       移除edas调度器的runtime status 事件发送       |
> fix: remove runtime status event send for edas executor

- modules/dop/endpoints/release.go
The repair app cannot be continuously integrated
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTc0LDExNjQsMTE0Nl0sImFzc2lnbmVlIjpbIjEwMDA1NjAiXX0%3D&id=303196&iterationID=1164&pId=0&type=BUG)
| 🇺🇸 English |       fix the issue that app cannot be continuously integrated      |
| 🇨🇳 中文    |      修复应用无法进行持续集成        |
> fix(dop): app cannot be continuously integrated

- apistructs/pipeline_yml.go
- pkg/parser/pipelineyml/graph_pipelineyml.go
The pipeline graph interface displays the croncontroller field
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTc0LDExNjQsMTE0Nl0sImFzc2lnbmVlIjpbIjEwMDA1NjAiXX0%3D&id=303639&iterationID=1164&pId=0&type=BUG)
| 🇺🇸 English |       The pipeline graph interface displays the croncontroller field       |
| 🇨🇳 中文    |       流水线 graph 接口展示 cronCompensator 字段       |
> fix(pipeline): The pipeline graph interface displays the croncontroller field

- modules/pipeline/providers/cron/compensator/provider.go
Fix the problem that the cron compensates that the action of git-checkout cannot get the git information
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTc0LDExNjQsMTE0Nl0sImFzc2lnbmVlIjpbIjEwMDA1NjAiXX0%3D&id=303665&iterationID=1164&pId=0&type=BUG)
| 🇺🇸 English |       Fix the problem that the cron compensates that the action of git-checkout cannot get the git information    |
| 🇨🇳 中文    |       修复定时补偿执行 git-checkout action, 无法拿到仓库信息       |
> fix(pipeline): Fix the problem that the cron compensates that the action of git-checkout cannot get the git information

- modules/dop/providers/projectpipeline/provider.go
- modules/dop/providers/projectpipeline/service.go
- modules/dop/providers/projectpipeline/service_impl.go
When creating a definition, a scheduled task is created asynchronously
| 🇺🇸 English |      When creating a definition, a scheduled task is created asynchronously        |
| 🇨🇳 中文    |       创建定义的时候异步创建定时任务       |
> fix(pipeline): When creating a definition, a cron info is created asynchronously

- apistructs/pipeline_status.go
- modules/pipeline/providers/reconciler/taskrun/task_loop.go
skip loop task if status is stopbyuser
/assign @sfwn 
| 🇺🇸 English |   Fix the bug that loop task can't stop when cancel           |
| 🇨🇳 中文    |   修复了loop类型的task无法取消执行           |
> fix(pipeline): skip loop task if status is stopbyuser

- modules/pipeline/providers/cache/secret.go
- modules/pipeline/services/pipelinesvc/precheck.go
- modules/pipeline/services/pipelinesvc/run.go
platformSecrets do not use cache
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTc0XSwiYXNzaWduZWUiOlsiMTAwMTI2MSJdfQ%3D%3D&id=305483&iterationID=1174&pId=0&type=BUG)
/assign @sfwn 
| 🇺🇸 English |     platformSecrets do not use cache         |
| 🇨🇳 中文    |   platformSecrets不使用缓存           |
> fix(pipeline): platformSecrets do not use cache

- modules/pipeline/providers/reconciler/taskrun/taskop/queue.go
stop queue when pipeline canceled
before cancel pipeline:
after cancel pipeline, queue stopped:
| 🇺🇸 English |   stop queue when pipeline canceled           |
| 🇨🇳 中文    |  当流水线被取消时，任务停止排队            |
> feat(pipeline): stop queue when pipeline canceled

- apistructs/cluster_dialer.go
- bundle/cluster_dialer.go
- modules/cluster-dialer/server/client_data.go
- modules/cluster-dialer/server/client_data_test.go
- modules/cluster-dialer/server/tunnel-server.go
cluster-dialer support record and query client data
/assign @sfwn 
| 🇺🇸 English |    cluster-dialer support record and query client data          |
| 🇨🇳 中文    |   cluster-dialer支持记录查询客户端信息           |
> feat(cluster-dialer): cluster-dialer support record and query client data

- modules/dicehub/release/release.service.go
polish: parse dice.yml concurrently when get release
| 🇺🇸 English | polish: parse dice.yml concurrently when get release |
| 🇨🇳 中文    | 获取项目制品详情是并发地解析dice.yaml以优化相应时间  |
> fix: polish: parse dice.yml concurrently when get release

- apistructs/cluster_dialer.go
- bundle/bundle.go
- cmd/pipeline/main.go
- conf/pipeline/pipeline.yaml
- modules/pipeline/endpoints/endpoints.go
- modules/pipeline/initialize.go
- modules/pipeline/provider.go
- modules/pipeline/providers/edgepipeline/interface.go
- modules/pipeline/providers/edgepipeline/interface_test.go
- modules/pipeline/providers/edgepipeline/provider.go
- modules/pipeline/providers/edgepipeline_register/interface.go
- modules/pipeline/providers/edgepipeline_register/interface_test.go
- modules/pipeline/providers/edgepipeline_register/provider.go
- pkg/http/httpclient/client.go
add edgepipeline and dialeragent provider for communication between center and edge
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=304696&iterationID=1174&pId=301655&type=TASK)
/assign @sfwn 
| 🇺🇸 English |   Support communication between center and edge for pipeline           |
| 🇨🇳 中文    |    实现pipeline中心和边缘之间的通讯          | …
> feat(pipeline): add edgepipeline and register provider for communication between enter and edge
